### ISSUE TITLE
VIP: Support for protected-embeds

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#10]
Protected Embeds are kinda weird (they rely on a javascript) and we probably need some workarounds for them.

**Comment by philipjohn** [comment]
What does the protected embeds JS do? I see some resize stuff.

Is there an easy way, within Protected Embeds that we can just say `if ( is_amp() )` or something, and conditionally print the JS? Or is that lazy wishful thinking?

**Comment by mjangda** [comment]
We can add an `is_amp_endpoint()` function to check.

**Comment by mjangda** [comment]
This is a bit of a pain. Protected embeds use javascript (form submit to an iframe via POST) to avoid GET URL limits in some browsers. Since javascript isn't allowed, we can't swap this out as-is so will need to either revert back to GET with an iframe for AMP or find some other clever approach.

**Comment by maxhartshorn** [comment]
This would be a very good feature to have. We try to leverage shortcodes as much as possible but still many of our producers copy/paste embeds directly which get converted into protected embeds. It's hard to justify keeping this as an option if protected embeds don't work in AMP

**Comment by brianlayman** [comment]
Likewise, sites that cannot directly include youtube videos use this method to display them.  Not having this feature disables all videos on the site.

**Comment by brianlayman** [comment]
Also on VIP scribd embeds convert to protected-iframes and so are used without any choice in the matter.

**Comment by brianlayman** [comment]
Would it be possible to GET in there for now? That would be much better having over 8000 posts with missing data.

Could you please provide the protected-iframe embed source so that we can look at a solution?

**Comment by mjangda** [comment]
This should mostly work now. There's a wpcom commit to allow switching to standard iframes and 702b18e6d6a760a9c1bc03bfc589b38459cf0130 forces it on for AMP content.

Caveats:
- some embeds may not work in some browsers (because of the really long URLs).
- dynamic resizing most likely won’t work either (although, i haven’t tested).

**Comment by bcampeau** [comment]
There's actually still a bug with this for AMP. Sometimes the protected embeds don't set a width and/or height param for the iframe. This isn't allowed in AMP and will cause a validation error. I'm seeing a lot fo these on nypost.com. Here's an example: http://nypost.com/2015/12/06/almost-impossible-to-stop-all-terrorism-homeland-security-chair/amp/

**Comment by mjangda** [comment]
I think the bigger issue is that the iframe-sanitizer doesn't handle empty width/height values well. For now, I've pushed a workaround for protected embeds (internal ref: r134693-wpcom).

**Comment by bcampeau** [comment]
Fair point. Thanks.
