### ISSUE TITLE
[Gutenberg] Extend existing core blocks for AMP specific functionality

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1008]
**As a WordPress site running Gutenberg, my core/native blocks should have extended AMP-HTML markup features.**

- [ ] AC1: Extend core blocks which have validation errors so that the appropriate AMP markup is output to faithfully render the block when the page is served as AMP. This would be done via some combination of the render_callback that integrates with a new block sanitizer/preprocessor.

- [ ] AC2: Further extend core blocks to leverage AMP functionality, such as layout.

**Comment by westonruter** [comment]
See https://github.com/Automattic/amp-wp/pull/902#issuecomment-371672321

**Comment by kienstra** [comment]
**Update On Related Work**

Hi @postphotos,
You probably saw @westonruter's [comment above](https://github.com/Automattic/amp-wp/issues/1008#issuecomment-371733796), linking to [#902](https://github.com/Automattic/amp-wp/pull/902#issuecomment-371672321):

>3. Extend core blocks which have validation errors so that the appropriate AMP markup is output to faithfully render the block when the page is served as AMP.

In #1010, @miina is now working on a block that doesn't support AMP: ['categories' with a dropdown](https://github.com/Automattic/amp-wp/wiki/Gutenberg-Block-Support).

>4. Further extend core blocks to leverage AMP functionality, such as layout.

This would be a good possibility for this issue.

**Comment by postphotos** [comment]
Thanks for calling it out, @kienstra - I believe the addition of the story and AC at the top of this issue pulls the items from #902 clearly.

**Comment by miina** [comment]
Just FI that started looking into this and will add a possible "prototype" of the approach for discussing  (based on adding `AMP Layout` setting) in the beginning of the new week.

**Comment by westonruter** [comment]
Awesome. I'm looking forward to seeing that!

**Comment by miina** [comment]
Created a PR with initial take on the approach: https://github.com/Automattic/amp-wp/pull/1026. Would be great to receive some feedback before continuing.

**Comment by westonruter** [comment]
Regarding `amp-carousel` see https://github.com/Automattic/amp-wp/issues/1065

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

1. Go to https://native-ampconfdemo.pantheonsite.io/
2. Create a new post
3. Test all of the AMP blocks, which will show when you search for "AMP"
<img width="1435" alt="amp-blocks" src="https://user-images.githubusercontent.com/4063887/41003836-6c499278-68dd-11e8-83b6-9982d6845c22.png">
4. Often, there are example IDs or values in the site ampbyexample.com. Like if you need an ID to test the AMP Ready Player, you could go to: https://ampbyexample.com/components/amp-reach-player/
5. Expected: The blocks render properly on the front-end. The media players won't render the media in the editor, but they will on the front-end.
6. Expected:

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

1. Go to https://native-ampconfdemo.pantheonsite.io/
2. Create a new post
3. Add an image block
4. In the "Block" panel, choose a different value for "AMP Layout" 
5. Select "AMP lightbox effect"
6. Click "Save Draft"
7. Expected: those settings still display
8. Click "Preview"
9. Click the image
10. Expected: It expands to fill the screen, in a "Lightbox Effect"
11. Repeat steps 3-10, but with the "Gallery" block

**Comment by csossi** [comment]
verified in QA
