### ISSUE TITLE
[Gutenberg] Integrate validator with Gutenberg blocks

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1009]
**As a WordPress site running Gutenberg, my core blocks' AMP-HTML markup should be validated and results should appear in the Compatibility Tool.**

- [x] AC1: Integrate block validation results with the UI to reveal when a validation error does occur. Normally such errors will not happen for core blocks, but for the Custom HTML block in particular it is a distinct possibility. It is also key for plugins which introduce blocks so that their AMP validity can also be reported.

**Comment by westonruter** [comment]
See https://github.com/Automattic/amp-wp/pull/902#issuecomment-371672321

**Comment by westonruter** [comment]
I have some code for validation that is pending pushing.

**Comment by westonruter** [comment]
@kienstra See #1019. Next step is to communicate back the validation errors when saving a post in the Gutenberg editor, and then showing the validation error notice in the same way we're doing for the classic editor.

**Comment by postphotos** [comment]
The main issue description has been updated with a formal Story and Acceptance Criteria.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this when you can? It's not as important as the `0.7.1` regression testing, though.

1. Go to the editor of a post, [like this](https://develop-ampconfdemo.pantheonsite.io/wp-admin/post.php?post=345&action=edit). Your login details should be the same as the other testing sites.
2. Add a Custom HTML block
3. Enter invalid AMP, like:
```html
<script>doSomething()</script>
<button onclick="doThis()">Click me</button>
```
4. Click "Save draft"
Expected: 
* A notice appears at the top of the editor, and at the top of the block
* The "Details" link in the top notice leads to a page that highlights where the error is
<img width="1435" alt="errors-editor" src="https://user-images.githubusercontent.com/4063887/40196503-5c4d9600-59d6-11e8-8370-a61e5a7f26fe.png">

5. Add other blocks
Expected:
* There aren't notices above those blocks, like there are above that Custom HTML block above
* The notice at the top of the page still appears

**Comment by csossi** [comment]
verified in QA
