### ISSUE TITLE
No control over images getting resized and expanded beyond their dimensions

### ISSUE THREAD

**Issue by rudygalfi** [Automattic/amp-wp#101]
Any images will be resized to the width of the container, even if it's larger then the image's actual dimensions. This leads to blurring.

It would be nice to enable the content creator some control here or to have better default handling (e.g. image keeps its original dimension unless the container size shrinks, in which case it scales down proportionally).

I believe this is getting worked on but wanted to resolve https://github.com/ampproject/amphtml/issues/1182 and have something for tracking.

**Comment by mjangda** [comment]
This should be fixed now.
