### ISSUE TITLE
[Gutenberg] Fixing any issues with rendering native blocks in AMP

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1010]
**As a WordPress site running Gutenberg, my core/native blocks should be renderable as AMP-HTML compatible markup.**

AC1: Any issues previously identified with core blocks from #845 should be fixed here.

**Comment by westonruter** [comment]
See https://github.com/Automattic/amp-wp/pull/902#issuecomment-371672321

**Comment by kienstra** [comment]
**More Blocks Supported**

Hi @miina,
Please see this [comment on #845](https://github.com/Automattic/amp-wp/issues/845#issuecomment-373252322), if you haven't already. I marked [more blocks as supported](https://github.com/Automattic/amp-wp/wiki/Gutenberg-Block-Support).

**Comment by miina** [comment]
@westonruter Looks like as of now the only non-supported core blocks is the `Categories` with dropdown block. The issue there seems to be removing the script that's handling the option selection. For this specific case maybe a separate `AMP_Block_Sanitizer` for processing the comments wouldn't be necessary and we could just replace the `render_callback` of the block (similar as your [Categories Widget](https://github.com/Automattic/amp-wp/blob/develop/includes/widgets/class-amp-widget-categories.php#L70) solution) for the AMP page. Thoughts?

**Comment by postphotos** [comment]
Hi @miina and @kienstra:
I've The updated the issue here with a formal Story and Acceptance Criteria. When #845 concludes, let me know and I'll flesh out what's here based on your discovery. Thanks!

**Comment by postphotos** [comment]
Oh also @miina pointed out that AC1 from #1008 may apply here. :+1:
