### ISSUE TITLE
Move WPCOM and Jetpack-specific codebase into the Jetpack plugin

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1021]
As we work to add AMP support to the WordPress ecosystem it is not feasible for the AMP plugin itself to support all of the plugins. Instead, the plugins themselves should be supporting AMP. So the current Jetpack-specific code should be moved into the AMP plugin. The new Lazy Images feature of Jetpack actually was built with [AMP-support baked in](https://github.com/Automattic/jetpack/blob/7c3d69bbf27e761e515d758fcdd6fbb6199e5836/modules/lazy-images/lazy-images.php#L104-L107). 

Code in scope for moving to Jetpack:

* Jetpack-specific embeds.
* `/jetpack-helper.php`
* `/wpcom`
* `/wpcom-helper.php`

**Comment by postphotos** [comment]
Hey @westonruter , I've taken a crack at writing a story and some ACs out of this. Let me know if I'm missing anything.

**As a WordPress user, I should expect each plugin to contain AMP-specific code in its own codebase, not in the main AMP-WP plugin.**

- [ ] AC1: Add appropriate AMP support directly to the Jetpack plugin if necessary.
- [ ] AC2: Remove Jetpack files from `AMP-WP` plugin.
- [ ] AC3: Validate that all Jetpack AMP-compatible features that work before this adjustment still work.
- [ ] AC4: Add basic documentation to the Wiki that outlines why we don't include direct plugin support and gives specific direction to a plugin developer looking to add AMP support (if needed) to their plugin.

I've taken the liberty of adding AC4, let me know if you think it's necessary.

**Comment by philipjohn** [comment]
> /wpcom-helper.php

I wouldn't class this under the same umbrella as Jetpack, because it's specific to the WordPress.com VIP environment. We also have vipgo-helper.php files for VIP Go.

We (VIP) do need a better way of inserting our environment-specific modification than including in plugins although the solution we end up with will likely only get applied to VIP Go. Regardless, it's not something that really belongs in Jetpack either.

For now, with plugins like Liveblog, we version control the helpers in Github and then exclude from the WordPress.org releases.

**Comment by amedina** [comment]
It is important to do this to decouple the plugin from any dependencies. If the code is not moved to Jetpack, what would the plan be?

**Comment by westonruter** [comment]
It sounds like the code should be incorporated into WordPress.com's platform codebase and not made part of any plugin then.

**Comment by gravityrail** [comment]
I moved some wpcom-helper features to Jetpack in https://github.com/Automattic/jetpack/pull/9458. AMP plugin side is https://github.com/Automattic/amp-wp/pull/1149

**Comment by gravityrail** [comment]
The Jetpack side is merged, so I'm just waiting on someone to review https://github.com/Automattic/amp-wp/pull/1149 against the Jetpack master branch (6.2)

**Comment by westonruter** [comment]
@jeherve Is it safe now to remove `jetpack-helper.php` and `wpcome-helper.php`? See see #1925.

**Comment by jeherve** [comment]
Yup, it looks safe now!

**Comment by westonruter** [comment]
@jeherve Just to be clear: all of the code in `wpcom-helper.php` has been copied to WordPress.com (including Go)?

**Comment by jeherve** [comment]
My bad, I only looked at `jetpack-helper.php` in #1925, I did not check `wpcom-helper.php`. 

I am not familiar with the file, so it may be best to ask someone who is more familiar with it. cc @mjangda Do you think you could take a look at this?

**Comment by gravityrail** [comment]
@jeherve and @westonruter - the wpcom helper is no longer used on wpcom as far as I can tell. It's not required anywhere.
