### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by taoyouh** [Automattic/amp-wp#1025]
The footer in AMP pages needs localization.
"Catagories", "Tags", "Leave a comment", "Powered by WordPress", "Back to top" does not support Simplified Chinese.

**Comment by westonruter** [comment]
You can actually contribute the translations yourself via https://translate.wordpress.org/projects/wp-plugins/amp

Translations are no longer packaged with the plugin. They are sourced from translate.wordpress.org.
