### ISSUE TITLE
Let amp-live-list for comments be opt-in

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1028]
We should add a theme support flag for `comments_live_list` to control whether or not comment submission is intercepted. Without flag, default full-page-reload behavior should be retained to allow themes without `amp-live-list` in comments to work normally.

The theme can do:

```php
add_theme_support( 'amp', array(
	'comments_live_list' => true,
) );
```

And then the plugin can read it like this:

```php
<?php
add_filter( 'comment_post_redirect', function( $url, $comment ) {
	$theme_support = get_theme_support( 'amp' );

	// Return with simply success when amp-live-list will show newly-posted comment.
	if ( ! empty( $theme_support['comments_live_list'] ) ) {
		wp_send_json_success();
	}

	// Add the comment ID to the URL to force AMP to refresh the page.
	$url = add_query_arg( 'comment', $comment->comment_ID, $url );

	return $url;
}, PHP_INT_MAX, 2 );
```

This will allow `amp` support to be added to an existing theme without requiring its comments template to be retrofitted with `amp-live-list`.

Alternatively, if we think that `amp-live-list` should _really_ be the default we want to always be used, then there could instead be an opt-out flag.

**Comment by westonruter** [comment]
Naturally the `wp_send_json_success()` bit would change in light of https://github.com/Automattic/amp-wp/pull/1020#issuecomment-373889605

**Comment by DavidCramer** [comment]
Thanks @westonruter .

**Comment by westonruter** [comment]
There is an issue with

**Comment by westonruter** [comment]
To test without opt-in, making a comment at: https://paired-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/

Should result in a page refresh with a URL like https://paired-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/?comment=34#comment-34

For a native AMP site where the flag is present, there should be no refresh and instead the Update Comments button should appear to update the live list: https://dev-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/

**Comment by westonruter** [comment]
Three issues I see:

1. When in paired mode, if I submit the comment at https://paired-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/amp/ then it will redirect me to the non-AMP article. The `comment_post_redirect` filter should be making sure that if paired mode is enabled that it redirects to the AMP version of the post instead. 

2. Related: when in non-paired mode such as at https://paired-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/#respond I cannot submit the form. Why? Because the `amp-runtime` script is erroneously getting enqueued. This results in:

![image](https://user-images.githubusercontent.com/134745/37738257-a12ae16e-2d13-11e8-9b5e-dde6721d8b17.png)

3. When submitting a comment from a site I can see now that `_wp_amp_action_xhr_converted` really should be used to determine whether the logic in `AMP_Theme_Support::handle_xhr_request()` runs.

**Comment by westonruter** [comment]
To test, try commenting on AMP article in paired mode: https://paired-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/amp/

And try commenting on the non-AMP version of the article: https://paired-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/

In both cases, the page should reload after submitting with the comment scrolled into view.

Also try commenting on AMP article in native mode: https://dev-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Are you available to test this, using @westonruter's [instructions above](https://github.com/Automattic/amp-wp/issues/1028#issuecomment-375174840)?

**Comment by csossi** [comment]
yes, will be on this today/tomorrow @kienstra @westonruter

**Comment by csossi** [comment]
- when I post a comment on native mode site, the display refreshes with the "awaiting moderation" message appearing just below the comment form - doesn't reposition anywhere. Can I assume that's the intent here, @westonruter ?

**Comment by westonruter** [comment]
@csossi After submitting the comment, it should look like this with the New Comment(s) button momentarily appearing (within 15 seconds) above the form:

> ![image](https://user-images.githubusercontent.com/134745/38158798-3a5cfa0a-3450-11e8-86b1-2d3b08c89c16.png)

Upon clicking the New Comments button it should scroll you up to your posted comment, and look like this:

> ![image](https://user-images.githubusercontent.com/134745/38158803-4f3315e0-3450-11e8-9b9c-509a3558f88d.png)
