### ISSUE TITLE
Capture script tag contents in AMP validator errors

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1031]
The AMP validator utilities should capture script tag contents when it is less than 1KB (or some threshold) so that we can gather data about the scripts which are removed, so we can begin to identify the most common scripts that should get their own dedicated post-processor to convert to AMP (e.g. Google Analytics, AdSense, etc).

**Comment by westonruter** [comment]
This is being added in https://github.com/Automattic/amp-wp/commit/811d133f18741177a27aad0ed2cef9e821479deb#diff-7d234989187d87a372e2aa6aa1299a71R672 via #1093.

**Comment by kienstra** [comment]
**Steps To Test**

Hi @csossi, Could you please test this?

1. Go to this [staging site](https://native-ampconfdemo.pantheonsite.io/)
2. Create a new post
3. Add this in the post content (using the "Text" tab, not the "Visual" one):
`
<script>doSomething(); alsoDoThis();</script>
`
4. Publish the post
5. Observe that a notice appears:
>There is content which fails AMP validation. Non-accepted validation errors prevent AMP from being served. Review issues
6. Click "Review issues"
7. Expected: The content of that script appears in the `text` field of a validation error: `doSomething(); andDoThis();`

**Comment by csossi** [comment]
verified in QA
