### ISSUE TITLE
Understand the level of effort for enabling AMP support on native themes

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1036]
AC1: Test and report the experience of converting the three most recent core themes (`Twenty Fifteen`, `Twenty Sixteen`, `Twenty Seventeen`) to be compatible. Document this process.
AC2: Report CSS findings - this is related to the CSS Tree Shaking issue #930

**Comment by kienstra** [comment]
**Working On This Now**

Hi @westonruter,
If it's OK, I'm working on this now, starting with Twenty Fifteen.

**Comment by kienstra** [comment]
**Twenty Fifteen Features**
*Tested On Posts And Pages, Using A Paired Mode Child Theme*
- [x] Customizer > Header Image
- [x] Customizer Colors (including Base Color Schemes, Background Color, Header and Sidebar Text Color, Header and Sidebar Background Color)
- [x] Customizer > Site Identity > Logo
There's still a minor image display issue related to #1104

**Twenty Fifteen: Removed By Validator**
We should dequeue these illegal [scripts](https://github.com/WordPress/wordpress-develop/tree/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/js) that the validator strips ([original add_action](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/functions.php#L316)):
```php
wp_dequeue_script( 'twentyfifteen-skip-link-focus-fix' );
wp_dequeue_script( 'twentyfifteen-script' );
wp_dequeue_script( 'twentyfifteen-keyboard-image-navigation' );
wp_dequeue_script( 'comment-reply' );
remove_action( 'wp_head', 'twentyfifteen_javascript_detection', 0 );
```

[This rule](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/style.css#L2709) in `style.css` caused this error in the validator:
>CSS @-ms-viewport rules are currently disallowed

There's also an `invalid_element` error from [header.php](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/header.php#L15):
```php
<meta name="viewport" content="width=device-width">
```
And [this JavaScript file](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/header.php#L19) is output inline in [header.php](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/header.php#L19).

**Comment by westonruter** [comment]
See also this PR adds `amp` theme support to _s, which could have some useful pieces, especially in regards to the nav menus: https://github.com/Automattic/_s/pull/1286

**Comment by westonruter** [comment]
> And this illegal script is output inline in header.php.

Is that the script that is getting reported? Since it is inside of conditional comments it should get ignored by the whitelist sanitizer.

**Comment by kienstra** [comment]
**Script In Header**

Hi @westonruter,
You're right that the `header.php` script isn't reported in the validator. I just crossed it out of the comment above.

**Comment by kienstra** [comment]
**Twenty Sixteen: Removed By Validator**
**WIP**

So far, the validation errors look really similar to those in Twenty Fifteen.

We should probably dequeue these illegal [scripts](https://github.com/WordPress/wordpress-develop/tree/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/js) that the validator strips ([original add_action](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentyfifteen/functions.php#L316)):
```php
wp_dequeue_script( 'twentysixteen-html5' ); 
wp_dequeue_script( 'twentysixteen-skip-link-focus-fix' );
wp_dequeue_script( 'comment-reply' );
wp_dequeue_script( 'twentysixteen-script' );
remove_action( 'wp_head', 'twentysixteen_javascript_detection', 0 );
```
There's also an error from [style.css](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentysixteen/style.css#L2735): `illegal_css_at_rule: CSS @-ms-viewport rules are currently disallowed` 

And there's an `invalid_element error` from [header.php](https://github.com/WordPress/wordpress-develop/blob/489acfc57e53a7439943db8971154c0d7df2a82b/src/wp-content/themes/twentysixteen/header.php#L16):
```php
<meta name="viewport" content="width=device-width">
```

**Comment by kienstra** [comment]
**[Twenty Seventeen](https://codex.wordpress.org/Twenty_Seventeen) Support**
*Tested in Paired Mode and Native AMP (with simple child themes)*

- [x] [Social Icons Menu](https://codex.wordpress.org/Twenty_Seventeen#Add_Social_Icons) 
- [x] [Front Page Sections](https://codex.wordpress.org/Twenty_Seventeen#Front_Page)
- [x] [One And Two Column Layouts](https://codex.wordpress.org/Twenty_Seventeen#One_and_Two_Column_Layouts) of pages
- [ ] [Header Media](https://codex.wordpress.org/Twenty_Seventeen#Header_Media): neither the Header Image nor Header Video are supported, as @westonruter mentioned in #1074 
- [ ] The "Top Menu" hamburger icon doesn't appear, and the entire menu always displays on mobile (this [stripped script](https://github.com/WordPress/wordpress-develop/blob/977f7eba2462513453cd84532f8efb7340f71e7e/src/wp-content/themes/twentyseventeen/assets/js/navigation.js#L11) drives it)
- [ ] [Custom Colors](https://codex.wordpress.org/Twenty_Seventeen#Custom_Colors) mainly work, but the 'Social Icons Menu' icons are sometimes distorted ([screenshot](https://cloudup.com/ciq10-am9DU)). This is [fixed](https://github.com/Automattic/amp-wp/pull/1074/files#diff-5d05e505f93786061c2078486784c46dR68) in @westonruter's PR #1074.

**Twenty Seventeen: Validator Errors**

We should probably dequeue the illegal [scripts](https://github.com/WordPress/wordpress-develop/blob/977f7eba2462513453cd84532f8efb7340f71e7e/src/wp-content/themes/twentyseventeen/functions.php#L486) from these handles:
```
'html5'
'twentyseventeen-skip-link-focus-fix'
'twentyseventeen-navigation'
'comment-reply'
'jquery-scrollto'
'twentyseventeen-global'
```

And remove [an action](https://github.com/WordPress/wordpress-develop/blob/977f7eba2462513453cd84532f8efb7340f71e7e/src/wp-content/themes/twentyseventeen/functions.php#L394) that prints a `<script>`:
```php
remove_action( 'wp_head', 'twentyseventeen_javascript_detection', 0 );
```

Similar to the 2 themes above, there's an `invalid_element` error from this begin output in [header.php](https://github.com/WordPress/wordpress-develop/blob/977f7eba2462513453cd84532f8efb7340f71e7e/src/wp-content/themes/twentyseventeen/header.php#L19):
```php
<meta name="viewport" content="width=device-width, initial-scale=1">
```
