### ISSUE TITLE
[Gutenberg] Introduction of new blocks for AMP specific features

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1039]
Possibly to be included in v1.0 release. Formal story + AC to come soon.

**Comment by westonruter** [comment]
Regarding `amp-carousel` see https://github.com/Automattic/amp-wp/issues/1065

**Comment by miina** [comment]
Went through the potential Gutenberg blocks. Thoughts here:
- `amp-accordion`: Not sure how useful this would be as an addition for existing core blocks. Perhaps a new block which would allow creating different text sections for `amp-accordion` could make more sense?
- `amp-carousel`: Makes sense as adding to existing `Gallery` block;

**Comment by westonruter** [comment]
All Gutenberg PRs have been merged, so I believe this is now ready for QA.

**Comment by kienstra** [comment]
**Thanks For Testing**

Hi @csossi,
Thanks for testing this.

1. I also saw that the `amp-springboard-player` doesn't display on the front-end:
<img width="1429" alt="amp-springboard-player" src="https://user-images.githubusercontent.com/4063887/41126154-3e24459c-6a6c-11e8-9c73-a120841b3846.png">

But the values that the AMP by Example site gives don't even cause the player to render on that page:
https://ampbyexample.com/components/amp-springboard-player/
After a brief search, I couldn't find any other values for this. We might revisit this for later, but I'd propose that it's alright for now.

2. Good point, it's hard to find IDs for the Ooyala player. I copied the ones from [this doc](https://www.ampproject.org/docs/reference/components/amp-ooyala-player) into the editor, and they seem to [display well](https://native-ampconfdemo.pantheonsite.io/2018/06/07/qa-test-post/
):
<img width="1430" alt="ooyala-player" src="https://user-images.githubusercontent.com/4063887/41126275-9a12293c-6a6c-11e8-9ba7-333bc5362c4d.png">

**Comment by miina** [comment]
Hey @kienstra, thanks for looking into this, let me know if that's something that would be good if I would investigate (springboard player issue).
