### ISSUE TITLE
Structured Data Testing Tool errors

### ISSUE THREAD

**Issue by RecensioniDroni** [Automattic/amp-wp#104]
Hi everybody,
plugin needs some fixes.

- BlogPosting

logo:	 missing and required

image: missing and required

dateModified: missing and recommended

**Comment by Otto42** [comment]
Same here. The publisher.logo appears to be required. Could use the site icon if available.

The image is also required. Suggest featured image and a default. Reference issue #98

**Comment by cfinke** [comment]
<blockquote>Could use the site icon if available.</blockquote>

Site icons are always (?) square, but publisher.logo is supposed to be rectangular, with a max height of 60px and max width of 600px, according to https://developers.google.com/structured-data/rich-snippets/articles. I supposed it could be 60x60.

**Comment by mjangda** [comment]
> dateModified: missing and recommended

dateModified was added in dc69efff26a531a7b5fb777c812a36b5452a8667

**Comment by mjangda** [comment]
Closing this as we have other issues tracking this.
