### ISSUE TITLE
disabled by default for individual Posts

### ISSUE THREAD

**Issue by akashsky44** [Automattic/amp-wp#1044]
AMP to be disabled by default for individual Posts writer has decision enable or not when writing a story by default amp disable show then the writer has the decision to enable or disable. how to do this?

**Comment by westonruter** [comment]
This will do it:

```php
add_filter( 'amp_post_status_default_enabled', function( $default, $post ) {
	if ( 'post' === $post->post_type ) {
		$default = false;
	}
	return $default;
}, 10, 2 );
```

I've added this to the Wiki at https://github.com/Automattic/amp-wp/wiki/Custom-Post-Type-Support
