### ISSUE TITLE
Google AMP Pages Test

### ISSUE THREAD

**Issue by kkranzo** [Automattic/amp-wp#105]
I just received emails from Google this morning after they tested several of my sites that have the amp-wp plugin installed. Below are the errors that were received for pretty much all the AMP pages on my sites. So the wp-amp plugin must not be setting things up correctly.

- Error in schema.org NewsArticle
- Invalid attribute value (type=text/javascript, allowfullscreen=allowfullscreen, etc.)
- Prohibited tag (img)
- Stylesheet CDATA attribute missing or invalid (Disallowed @import in CSS)
- Incorrectly nested tag (body > script)

I also received this error on a few pages on all my sites as well

- Required attribute missing (height)

**Comment by mjangda** [comment]
Are you using the latest version of the plugin from Github? Or the version currently in the WordPress plugins directory?

**Comment by kkranzo** [comment]
I am using the one in the plugins directory (0.1).

**Comment by rudygalfi** [comment]
@mjangda Are you planning any release updates to the plugins directory soon?

**Comment by mjangda** [comment]
Yep, hopefully a release next week.

**Comment by benbowler** [comment]
Perfect! I had the same issue so good to see it's been resolved

**Comment by DaleeCro** [comment]
Hey,

i had the same problems in webmastertools:

Error/not permitted Atttribute:

content_max_width

layout="fill"

allowfullscreen=true

i use the plugin from github directory and have downloaded 1 week ago. When you plan the update to WordPress Directory?

Best wishes

**Comment by kkranzo** [comment]
Looks like all these validation errors are still present in the Google Amp Report even after updating to version 0.2 from the repository.

**Comment by HammyHavoc** [comment]
I'm also getting errors from Google's Search Console validation tests for https://www.previousmagazine.com/five-ways-to-keep-elderly-loved-ones-comfortable-at-home/amp

The errors are as follows:

- `Invalid attribute values: type=text/javascript`
- `Incorrectly nested tags: body > script`

**Comment by mjangda** [comment]
@HammyHavoc Looks like this cloudflare(?) script is breaking things:

```
<body><script type="text/javascript">
//<![CDATA[
try{(function(a){var b="https://",c="www.previousmagazine.com",d="/cdn-cgi/cl/",e="img.gif",f=new a;f.src=[b,c,d,e].join("")})(Image)}catch(e){}
//]]>
</script>
```
