### ISSUE TITLE
Automatically add <![CDATA[ that broke my microdata

### ISSUE THREAD

**Issue by ulissse** [Automattic/amp-wp#1052]
Hello,

I have microdata on my website, and the AMP plugin correctly add it within the amp post but it automatically add  <![CDATA[  just after this : <script type="application/ld+json">

<br>

how to remove this tag that causes a syntax error on google.

Thank you for your help.

Edit : Ok, here is a little more information about my trouble :

In fact, i had 2 schema scripts, one from my rating pluging and the other from the AMP plugin.

I have removed the structured data of the AMP plugin because it was not complete so i’m now with the structured data of the rating plugin but still can’t found how to remove the annoying tag <!CDATA[“”].

I hope someone can help me out with that.

ps: sorry for my bad English 🙁

**Comment by westonruter** [comment]
The `<![CDATA[` problem will be fixed in the 0.7 release. The PR that has the fix is #891.

Ref. https://wordpress.org/support/topic/cdata-tab-block-structured-data/#post-10142844
