### ISSUE TITLE
Confirm the "comments" content still validates on output.

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1053]
As a result of amp-live-list changes and as a part of the `v0.7` Beta 2 release, we want to confirm comments work as expected in WordPress.

Also when comments are in ascending order (oldest comments at top) the AMPConf theme's single template should validate via validator.ampproject.org when the `amp-live-list` has `sort=ascending`.

This note is for QA to check PR #1024 works as expected.

**Comment by westonruter** [comment]
Here is HTML which can be pasted into the [validator](https://validator.ampproject.org/) to check if it passes:

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-live-list" src="https://cdn.ampproject.org/v0/amp-live-list-0.1.js"></script>
</head>
<body>
  <amp-live-list id="my-live-list" data-poll-interval="15000" data-max-items-per-page="20" sort="ascending"> 
    <button update on="tap:my-live-list.update">You have updates!</button>
    <div items></div>
    <!-- pagination is optional -->
    <div pagination></div>
  </amp-live-list>
</body>
</html>
```

This issue can be closed when there is no longer a validation error reported as follows:

![image](https://user-images.githubusercontent.com/134745/38279726-75593494-3756-11e8-9c06-5e332d73997d.png)

**Comment by westonruter** [comment]
Probably should be tested once https://github.com/ampproject/amphtml/issues/13552 is closed.

**Comment by westonruter** [comment]
Next week is the current ETA on this. See https://github.com/ampproject/amphtml/issues/5396#issuecomment-379007426

**Comment by kienstra** [comment]
**Error Still Exists**

Pasting the snippet from @westonruter's [comment above](https://github.com/Automattic/amp-wp/issues/1053#issuecomment-378423731) in the [validator](https://validator.ampproject.org/) still causes the same validation failure.

**Comment by westonruter** [comment]
Validation error is still present.

**Comment by westonruter** [comment]
This is now live!
