### ISSUE TITLE
Let amp-carousel be optional for galleries

### ISSUE THREAD

**Issue by RitaRoca** [Automattic/amp-wp#1065]
Hi, I see that the plugin converts automatically a Wordpress Gallery into a slider. Can I disable that option to get the normal gallery?

Thanks

**Comment by westonruter** [comment]
This is something I've noticed that I think needs to change. The gallery output in AMP should be the same as the normal gallery, with opt-in for enhancements such as carousel. Maybe lightbox could be included by default. We can take cues from Jetpack's gallery extensions here.

**Comment by postphotos** [comment]
Thanks @RitaRoca - We have this in our backlog as an item to work on and I believe we'll find a decent alternative here. 👍 

Reminds me of [Should I use a carousel](http://shouldiuseacarousel.com) and [Yoast's summary on sliders](https://yoast.com/opinion-on-sliders/).

**Comment by westonruter** [comment]
Fixed in #1121

**Comment by kienstra** [comment]
**Moving To "Ready For Merging"**

The [test steps](https://github.com/Automattic/amp-wp/pull/1121#issuecomment-394861467) in #1121 should cover this issue.
