### ISSUE TITLE
@charset isn't being stripped from CSS; causes AMP validation error

### ISSUE THREAD

**Issue by douglyuckling** [Automattic/amp-wp#1068]
My theme's `style.css` begins with `@charset "UTF-8";`, but that apparently isn't allowed in AMP. It's not being stripped out when I use my theme in "paired mode", which causes an AMP validation error for me.

In case it matters, the version of this plugin I'm using is commit `5ba9f5b` from the 0.7 branch.

**Comment by westonruter** [comment]
@douglyuckling thanks. This is something that is being addressed with having an actual CSS parser in #1048 now merged into `develop` (1.0-alpha). You can see from the unit tests that `@charset` is specifically being accounted for and getting stripped:

https://github.com/Automattic/amp-wp/blob/40d1945778c9917ed258e74595d504ad31719d39/tests/test-amp-style-sanitizer.php#L133-L140

Please try the `develop` branch and you should see it gets removed successfully.
