### ISSUE TITLE
Add support for header videos

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1078]
In Twenty Seventeen there is a header video feature: https://make.wordpress.org/core/2016/11/26/video-headers-in-4-7/

![image](https://user-images.githubusercontent.com/134745/38881658-2dbd8c12-421d-11e8-8451-5f72eca75604.png)

This is not working in Twenty Seventeen when the `amp` theme support is added. It is just shown as blank (as with header image in the theme):

![image](https://user-images.githubusercontent.com/134745/38881813-9588f5a2-421d-11e8-8fdd-b12b96fa340e.png)

**Comment by kienstra** [comment]
**Steps To Test**

1. Visit [this staging site](https://core-themes-ampconfdemo.pantheonsite.io/)
2. It currently has a YouTube URL as the header video, but there's a header image on mobile displays
3. Ensure that display well, without obvious styling issues
4. In the Customizer, click "Select video" to choose a different video:
<img width="1430" alt="header-video" src="https://user-images.githubusercontent.com/4063887/40988113-eba21762-68af-11e8-8a17-e1544453a6fb.png">
5. Ensure that the video displays well on the front-end, and that it doesn't display on mobile devices

**Comment by csossi** [comment]
verified in QA
