### ISSUE TITLE
Hook to Add CSS Append directly into amp-custom style?

### ISSUE THREAD

**Issue by casbboy** [Automattic/amp-wp#1082]
Some of my posts have external CSS requests (when using offsite embeds). I'd like to run a function to find those CSS files, do a readfile, and place the stylesheet code into the amp-custom area. Then delete the CSS from the post.

But was trying to see if there was an easy hook to add code directly into the style amp-custom tag.

Cheers!
Ryan

**Comment by westonruter** [comment]
@casbboy this should be fixed in the plugin itself by 1.0 but in the mean time you can use the following workaround plugin as of v0.6: https://gist.github.com/westonruter/f272303fc4bf2d5d71fe1bd88a5fcee3

**Comment by westonruter** [comment]
We'll fix the issue in the plugin permanently via #1083. In the mean time, that workaround plugin above should do the trick.

**Comment by casbboy** [comment]
Thanks! Just to be certain, I just copy and paste this code into my functions file?

**Comment by westonruter** [comment]
@casbboy I just updated the Gist plugin to allow for scheme-less URLs: https://gist.github.com/westonruter/f272303fc4bf2d5d71fe1bd88a5fcee3/revisions

**Comment by casbboy** [comment]
What's strange is that it does have rel="stylesheet", but for some reason that gets removed on the amp version. I thought it might be Yoast doing it, but deactivated Yoast and it still happens. Can't figure out why. Trying now...

**Comment by westonruter** [comment]
The removal of the `rel` attribute is a bug in 0.6 that is fixed in 0.7-beta, where in 0.7 the entire `link` element is removed. However, the plugin above should remove the `link` entirely before it gets to that point after grabbing the contents to put in the `style[amp-custom]`.

**Comment by casbboy** [comment]
This time it definitely pulled the external CSS file request from the page, but it doesn't place the CSS contained in that file within the page. Is that how it is supposed to work?  I have a class I was looking for: .outer-embed-ta 

But it isn't on the page after external CSS removal. Just wanted to make sure I wasn't missing something.

**Comment by westonruter** [comment]
It should be adding the CSS to the `<style amp-custom>` element in the `head`. That's what this bit of code in the plugin does:

```php
add_action( 'amp_post_template_css', function() use ( $css ) {
	echo $css;
} );
```

This action is connected with the AMP plugin via:

https://github.com/Automattic/amp-wp/blob/31016b1cc92f8a2e3b75f57dac034b76efafda2e/templates/html-start.php#L20-L23

**Comment by casbboy** [comment]
Interesting. For some reason it is not doing it, but perhaps Cloudflare is blocking the request to the CSS to read. It's the only thing I can think of. I'll keep playing with it.

**Comment by westonruter** [comment]
I just made another rev to the plugin: https://gist.github.com/westonruter/f272303fc4bf2d5d71fe1bd88a5fcee3/revisions

It may be that it is having trouble making the request for a scheme-less URL.

**Comment by casbboy** [comment]
That fixed it. Thanks!
