### ISSUE TITLE
AMP passes all validations, still shows errors in webmasters

### ISSUE THREAD

**Issue by amrutashelar123** [Automattic/amp-wp#1084]
![amp issue](https://user-images.githubusercontent.com/28562527/38987618-05aa56c4-43ee-11e8-80ee-b25e8dc1a466.jpg)

One of the issue says 

The tag 'stom:ohei015-desibr' is disallowed.
I don't even have that on AMP page.

**Comment by westonruter** [comment]
@amrutashelar123 you'll have to share the URL of the page in question in order for us to advise.
