### ISSUE TITLE
Facebook like button amp-iframe background color

### ISSUE THREAD

**Issue by cras4202tw** [Automattic/amp-wp#1088]
I use facebook button in my post，but amp-iframe is set to background: #c2c2c2

![amp-iframe](https://i.imgur.com/Ub5UfTR.png)

Can change the background color of fb like button to transparent?

![amp-iframe-edit](https://i.imgur.com/EqFZ59j.png)

**Comment by westonruter** [comment]
You should use the `amp-facebook-like` component instead of an `amp-iframe`. It has a `data-colorscheme` attribute you can use. See https://www.ampproject.org/docs/reference/components/amp-facebook-like

**Comment by westonruter** [comment]
You'll need to make sure you include the script for `amp-facebook-like` via:

```php
add_filter( 'amp_post_template_data', function( $data ) {
    $data['amp_component_scripts']['amp-facebook-like'] = 'https://cdn.ampproject.org/v0/amp-facebook-like-0.1.js';
    return $data;
} );
```

Put that in your theme's `functions.php` for example.
