### ISSUE TITLE
The tag 'amp-anim' requires including the 'amp-anim' extension JavaScript.

### ISSUE THREAD

**Issue by JonHendershot** [Automattic/amp-wp#1090]
Google Search Console is returning this issue for makup on our site. 

> The tag 'amp-anim' requires including the 'amp-anim' extension JavaScript.

Worth noting that we're using code on branch v0.7 as per your recommendation in ticket #1076 

<img width="1663" alt="screen shot 2018-04-20 at 1 46 55 pm" src="https://user-images.githubusercontent.com/8424532/39065993-8cdcb80e-44a1-11e8-90ea-007d5502bae6.png">

**Comment by westonruter** [comment]
@JonHendershot Please share the URL for the page in question.

**Comment by JonHendershot** [comment]
@westonruter sorry! here ya go 

https://www.wellandgood.com/good-sweat/sky-ting-yoga-brooklyn-expansion/amp/

**Comment by westonruter** [comment]
@JonHendershot ah, you caught a bug in 0.7! Fix submitted in #1092.

**Comment by westonruter** [comment]
@JonHendershot please give the 0.7 branch a try now.

**Comment by JonHendershot** [comment]
hi @westonruter  -- similar to our other ticket, we're still seeing the same issues after updating the plugin. 

url for staging:
https://amp-slides-well-good.pantheonsite.io/good-sweat/sky-ting-yoga-brooklyn-expansion/amp/

meta tag in head:
<meta name="generator" content="AMP Plugin v0.7-beta1-d65578d-20180420T213729Z" />

**Comment by JonHendershot** [comment]
ah! grabbing it now & will report back. Thanks @westonruter
