### ISSUE TITLE
Update changelog for v1.0 release [placeholder]

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1108]
As we work we should track the progress of the plugin development. When appropriate, we should merge this in. 👍

**Comment by kienstra** [comment]
Hi @postphotos,
Per our discussion, I will work on this changelog as the first priority today.

This will include the Ready for QA and Ready for Merging items on the [v1.0 board](https://github.com/Automattic/amp-wp/projects/6)
