### ISSUE TITLE
Getting error embedded social feeds

### ISSUE THREAD

**Issue by RohitPra** [Automattic/amp-wp#1122]
Getting error on all embedded social feeds, be it Twitter, Instagram or Facebook.

We can't post links to post because they don't show for some reason.

Now the latest update has spoiled it. It isn't showing any of those feeds in AMP. Don't know what to do, Disabled the plugin, still it won't show.

**Comment by westonruter** [comment]
@RohitPra How are you adding social feeds to a post?

Please share the URL to a post that has the problem.

**Comment by westonruter** [comment]
We can re-open if we get more info.
