### ISSUE TITLE
AMP for custom post types is not automatically set up.

### ISSUE THREAD

**Issue by uri3000** [Automattic/amp-wp#1123]
When I try to access the /amp url for a custom post type post, its not showing up as AMP, and Google AMP test does not recognize it either.
The website: https://overdraftapps.com

**Comment by amedina** [comment]
Actually it is: https://overdraftapps.com/open-business-checking-account-online/amp/

Can you share a specific link of the custom post type that is not working?

**Comment by westonruter** [comment]
We can reopen this if we get more details.
