### ISSUE TITLE
Deprecate the pre_amp_render_post action (when AMP theme support is present)

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1129]
In v0.7 we've added `amp` theme support where you can have the entire theme be served as AMP, not just the post templates. For example, you could have your blog index template be served as AMP now (see example site: https://ampdemo.xwp.io/). In that case, there is no `$post_id` to be passed as the arg for the `pre_amp_render_post` action. But you can see from the source that the `pre_amp_render_post` action actually runs at `template_redirect` (priority 10) anyway:

https://github.com/Automattic/amp-wp/blob/7439d2ab5eebd0ee071749a849fda946a2eff4be/amp.php#L326-L383

As such, we should deprecate the `pre_amp_render_post` action entirely in favor of themes and plugins doing:

```php
add_action( 'template_redirect', function() {
    if ( is_amp_endpoint() ) {
        // ...
    }
}, 9 );
```

The `pre_amp_render_post` action should only emit a deprecation warning when `amp` theme support is present.

We could also consider adding a new action that gets triggered here instead, like `pre_amp_render_template` which does not pass any `$post_id` arg.

See #1125.

**Comment by oscarssanchez** [comment]
Hi @westonruter,

Would `_deprecated_hook()` work for this? https://developer.wordpress.org/reference/functions/_deprecated_hook/

Since it's not intented to be used by plugin developers and a similar one ( ` _deprecated_function()` ) was replaced in this commit https://github.com/Automattic/amp-wp/pull/1141 i'm not sure if it would be fine to use it to output a warning

**Comment by westonruter** [comment]
@oscarssanchez hi, I think actually what you're looking for is [`do_action_deprecated()`](https://developer.wordpress.org/reference/functions/do_action_deprecated/). That should do it.
