### ISSUE TITLE
Erro with inline style

### ISSUE THREAD

**Issue by wtricks** [Automattic/amp-wp#1134]
I get this error in Google Search Console "Erro de sintaxe CSS na tag "style amp-custom". URL incorreto." 

About 137 pages get this error. 

`url(data:image/png; base64,ivborw0kggoaaaansuheugaaacwaaaascamaaaapwqozaaaabgdbtueaalgpc/xhbqaaaafzukdcak7ohokaaaamuexurczmzpf399fx1+bm5mzy9amaaadisurbvdjlvzxbesmgces5/p8/t9furvcrmu73jwlzosgsiizurcjo/ad+eqjjb4hv8bft+idpqocx1wjosbfhh2xssxeiyn3uli/6mnree07uiwjev8ueowds88ly97kqytlijkktuybbruayvh5wohixmpi5we58ek028czwyuqdlkpg1bkb4nnm+veanfhqn1k4+gpt6ugqcvu2h2ovuif/gwufyy8owepdyzsa3avcqpvovvzzz2vtnn2wu8qzvjddeto90gsy9mvlqtgysy231mxry6i2ggqjrty0l8fxcxfcbbhwrsyyaaaaaelftksuqmcc);display:block;height:44px;margin:0 auto -44px;position:relative;top:-22px;max-width:44px;}.amp-wp-inline-20ec941da908ec4d43921bd2c3c4ae13{margin:8px 0 0 0;padding:0 4px;}.amp-wp-inline-8d116f7ca7c3a36c0c19c735f24bf9b0{color:#000;font-family:Arial,sans-serif;font-size:14px;font-style:normal;font-weight:normal;line-height:17px;text-decoration:none;word-wrap:break-word;}.`

**Comment by westonruter** [comment]
Remove the space after `data:image/png;`. This is the same issue as #1089.
