### ISSUE TITLE
bug: wp admin bar validation error since 0.7

### ISSUE THREAD

**Issue by amgmbs** [Automattic/amp-wp#1140]
On plugin version 0.7 it outpus part of the wp admin bar if the user is logged in

This was not the case on 0.6 and I understand that the  google bot will not see this (invalid) amp, as it is not not logged in of course, but I believe it should be corrected.

The code is

```html
<script type="text/javascript">function w3tc_popupadmin_bar(url) {
return window.open(url, '', 'width=800,height=600,status=no,toolbar=no,menubar=no,scrollbars=yes');
}</script>
```

**Comment by westonruter** [comment]
@amgmbs is this with `amp` theme support present?

**Comment by andremacola** [comment]
Using my own custom template I'm having some problems with validation when user is logged in.
The problem is with the admin bar. So I need to place _**add_filter('show_admin_bar', '__return_false');**_ to pass the validation

**Comment by westonruter** [comment]
@andremacola Do you have `amp` theme support enabled?

**Comment by andremacola** [comment]
@westonruter it was autoptimize plugin problem. See https://github.com/futtta/autoptimize/issues/159 for more info if necessary

**Comment by futtta** [comment]
not 100% agree this is entirely an autoptimize problem, esp. as AO will never output W3TC JS, but happy you got this fixed anyhow ;-)
