### ISSUE TITLE
How to implement comments form in paired mode?

### ISSUE THREAD

**Issue by TinBoyko** [Automattic/amp-wp#1145]
And comments live list

**Comment by westonruter** [comment]
Do you mean without adding `amp` theme support? The paired mode with `amp` theme support is the recommended way to accomplish this: https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support#paired-mode

There is probably a way to add commenting support to the (legacy) post templates bundled in the plugin but they are going to be deprecated in favor of using `amp` theme support going forward, so it is highly recommended to try switching.
