### ISSUE TITLE
Support for amp-geo

### ISSUE THREAD

**Issue by jdcauley** [Automattic/amp-wp#1152]
Request for update of `includes/sanitizers/class-amp-allowed-tags-generated.php` to support `amp-geo`.

https://www.ampproject.org/docs/reference/components/amp-geo

**Comment by westonruter** [comment]
Thanks for raising this. We need to re-run the spec parser to add support.

**Comment by westonruter** [comment]
Here are the instructions for doing so if we don't get to it first: https://github.com/Automattic/amp-wp/blob/develop/contributing.md#updating-allowed-tags-and-attributes

**Comment by jdcauley** [comment]
Just saw this will take care of it if it's not done

**Comment by westonruter** [comment]
See #1172.

**Comment by westonruter** [comment]
@jdcauley PR is ready for review: #1172.

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/46259451-9b5dd300-c4a7-11e8-8375-fc06e24d8513.png)
