### ISSUE TITLE
preg_match error sanitizer

### ISSUE THREAD

**Issue by nickreale** [Automattic/amp-wp#1154]
I installed the plugin on several sites. I only seem to have an issue with one site where every amp post is giving this error.

> Warning: preg_match() expects parameter 2 to be string, array given in /home/molloy6/public_html/familytireandautoservice.com/wp-content/plugins/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php on line 1179

Here is a link
http://www.familytireandautoservice.com/locations/tires-needed-denver-tires/amp/

I have several hundred posts and it has this error on all I have checked.

Any ideas or help is appreciated.

**Comment by nickreale** [comment]
This is the code from the php file
private function check_attr_spec_rule_value_casei( $node, $attr_name, $attr_spec_rule ) {
		/**
		 * Check 'value_casei' - case insensitive
		 */
		if ( isset( $attr_spec_rule[ AMP_Rule_Spec::VALUE_CASEI ] ) ) {
			$rule_value = strtolower( $attr_spec_rule[ AMP_Rule_Spec::VALUE_CASEI ] );
			if ( $node->hasAttribute( $attr_name ) ) {
				$attr_value = strtolower( $node->getAttribute( $attr_name ) );
				if ( $attr_value === (string) $rule_value ) {
					return AMP_Rule_Spec::PASS;
				} else {
					return AMP_Rule_Spec::FAIL;
				}
			} elseif ( isset( $attr_spec_rule[ AMP_Rule_Spec::ALTERNATIVE_NAMES ] ) ) {
				foreach ( $attr_spec_rule[ AMP_Rule_Spec::ALTERNATIVE_NAMES ] as $alternative_name ) {
					if ( $node->hasAttribute( $alternative_name ) ) {
						$attr_value = strtolower( $node->getAttribute( $alternative_name ) );
						if ( $attr_value === (string) $rule_value ) {
							return AMP_Rule_Spec::PASS;
						} else {
							return AMP_Rule_Spec::FAIL;
						}
					}
				}
			}
		}
		return AMP_Rule_Spec::NOT_APPLICABLE;
	}

**Comment by nickreale** [comment]
private function check_attr_spec_rule_valid_url( $node, $attr_name, $attr_spec_rule ) {
		if ( isset( $attr_spec_rule[ AMP_Rule_Spec::VALUE_URL ] ) ) {
			if ( $node->hasAttribute( $attr_name ) ) {
				$urls_to_test = preg_split( '/\s*,\s*/', $node->getAttribute( $attr_name ) );
				foreach ( $urls_to_test as $url ) {
					$url = urldecode( $url );
					// Check if the host contains invalid chars.
					$url_host = wp_parse_url( $url, PHP_URL_HOST );
					if ( $url_host && preg_match( '/[!"#$%&\'()*+,\/:;<=>?@[\]^`{|}~\s]/i', $url_host ) ) {
						return AMP_Rule_Spec::FAIL;
					}

					// Check if the protocol contains invalid chars.
					$dots_pos = strpos( $url, ':' );
					if ( false !== $dots_pos && preg_match( '/[!"#$%&\'()*+,\/:;<=>?@[\]^`{|}~\s]/i', substr( $url, 0, $dots_pos ) ) ) {
						return AMP_Rule_Spec::FAIL;
					}
				}

				return AMP_Rule_Spec::PASS;
			}
		}

		return AMP_Rule_Spec::NOT_APPLICABLE;
	}

**Comment by westonruter** [comment]
@nickreale What version of WordPress PHP are you running? What appears to be happening is on this line:

https://github.com/Automattic/amp-wp/blob/5ab7f0840a2b0735e6e982b8d3a3c4376d449075/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L1178

The `PHP_URL_HOST` param is not being recognized. This second `$component` param was introduced in WordPress 4.7. Are you using an older version of WordPress? Notice that the plugin requires at least WordPress 4.7:

https://github.com/Automattic/amp-wp/blob/5ab7f0840a2b0735e6e982b8d3a3c4376d449075/readme.txt#L4-L5

**Comment by nickreale** [comment]
I am using the latest version.

**Comment by nickreale** [comment]
4.9.6

**Comment by westonruter** [comment]
I'm confused. If this is the code in question:

```php
$url = urldecode( $url );
// Check if the host contains invalid chars.
$url_host = wp_parse_url( $url, PHP_URL_HOST );
if ( $url_host && preg_match( '/[!"#$%&\'()*+,\/:;<=>?@[\]^`{|}~\s]/i', $url_host ) ) {
```
The `urldecode()` function returns a string, and `wp_parse_url()` would return a string here. So I don't see how `$url_host` could be anything other than a string.

**Comment by nickreale** [comment]
i am also confused. You can go here
http://taylorfamilyfuneralhome.com/tributes/elena-sepulveda/

and see the error for yourself. I just did the WP update as well.

This is the error reported:


   *Fatal error*: Uncaught Error: Call to undefined function
   twentyseventeen_get_svg() in
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-content/themes/CherryFramework/comments.php:62
   Stack trace: #0
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-includes/comment-template.php(1474):
   require() #1
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-content/themes/CherryFramework/loop/loop-single.php(25):
   comments_template('/comments.php', true) #2
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-includes/template.php(690):
   require('/homepages/30/d...') #3
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-includes/template.php(647):
   load_template('/homepages/30/d...', false) #4
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-includes/general-template.php(155):
   locate_template(Array, true, false) #5
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-content/themes/CherryFramework/single.php(14):
   get_template_part('loop/loop-singl...') #6
   /homepages/30/d261456565/htdocs/clickandbuilds/TFFH/w in
   */homepages/30/d261456565/htdocs/clickandbuilds/TFFH/wp-content/themes/CherryFramework/comments.php*
    on line *62*

**Comment by nickreale** [comment]
I would agree but i cannot find this problem documented anywhere else.  I
even uninstalled 2017. Not sure where to go from here

**Comment by westonruter** [comment]
By best guess is it is a problem with CherryFramework, so I'm going to close this for now.
