### ISSUE TITLE
There is missing schema.org data on attachment pages

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#1157]
As reported in this [support topic](https://wordpress.org/support/topic/structured-data-error-for-attachment-pages-media/) by [@shrewdies](https://wordpress.org/support/users/shrewdies/), the schema.org data doesn't have an `image` value on attachment pages. 

Steps to reproduce:
1. Select an image in `wp-admin/` > Media > Library
2. In the [Attachment Details](https://native-ampconfdemo.pantheonsite.io/wp-admin/upload.php?item=312) modal, click 'View attachment page'
<img width="1362" alt="view-attachment-page" src="https://user-images.githubusercontent.com/4063887/40216302-6d269e2c-5a2b-11e8-8220-49816a29e559.png">

3. Enter the [URL of that page](https://native-ampconfdemo.pantheonsite.io/312/) into the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fnative-ampconfdemo.pantheonsite.io%2F312%2F)

Expected: There is 'image' data
Actual: That value is missing

<img width="1349" alt="image-value-missing" src="https://user-images.githubusercontent.com/4063887/40216494-9fb22ee6-5a2c-11e8-9921-0c4a2d50a8ae.png">

**Comment by kienstra** [comment]
**New Issue**

Hi @postphotos,
Feel free to review or edit this.

**Comment by westonruter** [comment]
I created a 0.7.2 milestone and added this to it.
