### ISSUE TITLE
Consider passing '/' as argument to home_url()

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#1158]
In this [support topic](https://wordpress.org/support/topic/need-to-add-slash-to-end-of-url/#post-10293713), the `<a>` that wraps the site logo has an `href` value that doesn't end with a slash. 

https://www.traileraddict.com/article/fox-planning-6-x-men-movies-2018-2020-report/amp/?cb=16

<img width="1355" alt="no-trailing-slash" src="https://user-images.githubusercontent.com/4063887/40218283-36d57b4e-5a36-11e8-8b2c-bb0829aeb3eb.png">

In many cases, this probably doesn't make a difference. But in that case, it [caused a 404](https://www.traileraddict.com/article).

To correct this, [for the home_url value](https://github.com/Automattic/amp-wp/blob/c65cbf85d0110620c0fcb29c3db12348f2aa1df3/includes/templates/class-amp-post-template.php#L116), we might consider passing a `'/'` argument.

```php
'home_url'              => home_url(),
```
Could instead be:
```php
'home_url'              => home_url( '/' ),
```

The [documentation](https://codex.wordpress.org/Function_Reference/home_url#Default_Usage) says that it's the default usage.

**Comment by kienstra** [comment]
**New Issue**

Hi @postphotos,
Here's a new issue from a support topic. This would also ideally be in the `0.7.0` milestone, but we've almost begun testing that already.

**Comment by westonruter** [comment]
Use of `home_url('/')` is standard in themes, for example: https://github.com/WordPress/wordpress-develop/blob/186bb7c8a908de977934d77fc5633b493ba2223f/src/wp-content/themes/twentyfifteen/header.php#L36-L38

So I'd say this is a natural fix to make.

**Comment by kienstra** [comment]
Thanks, @westonruter! I'll open a PR now to `develop` if that's alright.
