### ISSUE TITLE
AMP

### ISSUE THREAD

**Issue by pechnik777** [Automattic/amp-wp#1159]
![2018-05-18_18-52-05](https://user-images.githubusercontent.com/39413420/40244833-a2452aa0-5acc-11e8-99b9-2b4fef758a7f.png)
  | Необходимый тег "amphtml engine v0.js script" отсутствует или указан неверно.
-- | --

**Comment by westonruter** [comment]
I don't know what the issue is.

**Comment by DavidCramer** [comment]
Translation: 
The required "amphtml engine v0.js script" tag is missing or incorrect.

**Comment by westonruter** [comment]
So the URL is https://7zet.ru/sozdat-reklamny-account-facebook/amp/

The error is:

> The mandatory tag 'amphtml engine v0.js script' is missing or incorrect. Learn more.

My guess is that WP-Super-Cache may be causing the script to be stripped out. Try deactivating it.

**Comment by pechnik777** [comment]
Deactivated wp-super-cache. Still a mistake.
![2018-05-18_20-21-54](https://user-images.githubusercontent.com/39413420/40248779-ada621b2-5ad9-11e8-9cf0-bac185737179.png)

**Comment by westonruter** [comment]
Any other caching or optimizing plugins installed?

**Comment by pechnik777** [comment]
Autoptimize

**Comment by pechnik777** [comment]
I've found it. This Is Autoptimize. I just don't know what to do with it.
![2018-05-18_21-54-49](https://user-images.githubusercontent.com/39413420/40252902-8297ec3c-5ae6-11e8-8b1f-1fcc4cacbbfe.png)
![2018-05-18_21-57-01](https://user-images.githubusercontent.com/39413420/40252903-82d1b8cc-5ae6-11e8-97d0-34e135a149c2.png)

**Comment by westonruter** [comment]
@pechnik777 try deactivating it.

**Comment by westonruter** [comment]
I suggest opening a support topic on their forum: https://wordpress.org/support/plugin/autoptimize

**Comment by futtta** [comment]
weird as Autoptimize bails on AMP-pages, cfr. https://github.com/futtta/autoptimize/blob/master/autoptimize.php#L230

**Comment by pechnik777** [comment]
I'm not good with codes. This is how Google shows the error on one of the amp pages
![oshibka](https://user-images.githubusercontent.com/39413420/40267520-86de76e6-5b66-11e8-9eb1-ba1b16373874.png)

**Comment by futtta** [comment]
Well, I'm 99,987654321% sure that that's not Autoptimize's doing @pechnik777 . 

The screenshots you posted higher up are just a list of "blocked resources" (might be blocked by your robots.txt or maybe the CSS/ JS got cleaned when doing a cache purge) for your normal pages (non-AMP) and as such has nothing to do with your AMP-problem.

**Comment by pechnik777** [comment]
Okay, thank you. I'm distracting you for nothing. I'll manage.
