### ISSUE TITLE
Inline style priority

### ISSUE THREAD

**Issue by ktmn** [Automattic/amp-wp#1163]
Inline styles are usually meant to take priority. 

The style sanitizer assigns a long class name `amp-wp-inline-163938e7aff7c2dfb28939a56cca5b36` and CSS `.amp-wp-inline-163938e7aff7c2dfb28939a56cca5b36 { color: red }`

Perhaps the class name shouldn't be so long, instead keep an index number somewhere to get a shorter class name `__amp1`, `__amp2`, etc.

And more importantly, the generated CSS could use the specificity hack:

`.__amp1.__amp1.__amp1 { color: red }`

Still should end up with less bytes used while being more specific.

**Comment by westonruter** [comment]
Thanks. This has already been fixed in the `develop` branch. You can build 1.0-alpha to try it.
