### ISSUE TITLE
Composer integration should support `vendor` outside project root

### ISSUE THREAD

**Issue by davisshaver** [Automattic/amp-wp#1180]
When managing a WordPress installation with a `composer.json`, the resulting `vendor` directly will often be at webroot or at a level above webroot (the latter being preferred for security reasons). In the check for `vendor` we could also accept the condition when the `\Sabberworm\CSS\RuleSet\DeclarationBlock` class or similar is already defined.

**Comment by davisshaver** [comment]
I can make a patch if this sounds OK

**Comment by westonruter** [comment]
@davisshaver When running a build of the plugin, the `composer.json` is not included. The plugin should get deployed as part of a build and not from source (though see #1167). I'm not sure exactly what you have in mind, but feel free to open a PR to elaborate.

**Comment by davisshaver** [comment]
Good call, @westonruter, #1167 seems like a better fit with the existing project setup. For comparison though, here's how I activate Gutenberg loaded from Composer in my server repo:

```
  "build-gutenberg": "cd site/wp-content/plugins/gutenberg && npm install && npm run build"
```

As the build here is generating a Zip and not updating files in place, the `build` branch makes sense to me.

**Comment by westonruter** [comment]
@davisshaver FYI: There is a 0.7.1-built tag now: https://github.com/Automattic/amp-wp/issues/1167#issuecomment-396125193
