### ISSUE TITLE
Youtube oembed - Custom template problem

### ISSUE THREAD

**Issue by andremacola** [Automattic/amp-wp#1185]
Hi,

When copy and past youtube URLs for oembed inside the post my custom template is not working and I'm getting several validation errors.

The post has only the youtube url and only posts with youtube aren't working.

```
add_theme_support( 'amp', array(
	'template_dir' => './templates/amp',
	'available_callback' => 'is_singular'
) );
```

**Comment by westonruter** [comment]
What are the validation errors?

**Comment by andremacola** [comment]
@westonruter Solved the problem, sorry. One of the developers created a filter for custom templates in a specific category.
