### ISSUE TITLE
Disallowed attribute in HTML tag 'col' or Not Vaild AMP page

### ISSUE THREAD

**Issue by dhavalmistry11** [Automattic/amp-wp#1191]
Dear,

Google search console show this error "Disallowed attribute in HTML tag 'col'. 

for this 2 Url, "https://www.thetrendingmagazine.com/katrina-kaif/amp/" and "https://www.thetrendingmagazine.com/zareen-khan/amp/"  

Please solve the issue.

Mistry Dhaval

**Comment by westonruter** [comment]
This has been fixed in https://github.com/Automattic/amp-wp/pull/1064 and it will be released as part of 1.0.
