### ISSUE TITLE
Upgrade from 0.6.2 to 0.7.x removes `post_amp_content` output

### ISSUE THREAD

**Issue by matthewmcvickar** [Automattic/amp-wp#1201]
Upon upgrading from plugin version 0.6.2 to 0.7.0 (or 0.7.1), my template doesn't show the post content. Everything else is output correctly. I'm showing with `<?php echo $this->get( 'post_amp_content' ); ?>`. I am running PHP 5.3 on the server. On the frontend, there are no errors shown in the devtools console or the AMP validator plugin. Any ideas why this might be happening? Were there changes to `post_amp_content` in 0.7.0?

**Comment by westonruter** [comment]
There hasn't been any changes to `post_amp_content` AFAIK.

**Comment by westonruter** [comment]
Sharing the template you're using may be helpful.

**Comment by matthewmcvickar** [comment]
Thank you for your response here; I'm not sure what did it.

Here is the template: https://gist.github.com/matthewmcvickar/21fe40cf98b27da1d052c2097cd0b681

**Comment by rbfonbuena** [comment]
@matthewmcvickar Seems to be an issue with PHP 5.3. I run PHP 7 on my localhost and content shows normally but when uploading to our server running PHP 5.3 the content isn't shown. Were you able to resolve this on your site?

**Comment by matthewmcvickar** [comment]
@rbfonbuena Yes, I also think it is an issue with PHP 5.3; I also have no problem when running PHP 7. Unfortunately, I can't upgrade the PHP version on a particular site yet, and my understanding is that WordPress (and its plugins) are meant to support 5.2.4+.

**Comment by westonruter** [comment]
This plugin currently requires PHP 5.3+.

**Comment by matthewmcvickar** [comment]
Ah, that’ll do it then.
