### ISSUE TITLE
Category / Custom Taxonomy pages not working

### ISSUE THREAD

**Issue by paulcunningham8** [Automattic/amp-wp#121]
Hi guys, I installed the plugin and am finding the category pages, and my custom taxonomy pages are not working, in addition, featured images are not showing in blog posts. 
Also wondering how different AMP is to an RSS feed, and can this be used as a foundation for a workaround to the above as I'm worried about losing traffic to my competition?

Thanks guys!

**Comment by mjangda** [comment]
Thanks for the report @paulcunningham8. We currently only support posts in the plugin.

> Also wondering how different AMP is to an RSS feed

RSS feeds are typically consumed by feed readers, which format the content for end users. AMP versions of pages will be viewed directly by visitors to your site. I'd suggest reading through this post for more details: https://www.ampproject.org/docs/get_started/about-amp.html

**Comment by j3j5** [comment]
I am not completely sure if this is the same issue as mentioned above, but on our page we use an `extra permastruct` with the category as part of the permalinks for posts but, when using it the `query_var` doesn't show up, thus wrongly identifying the enpoint as 'not amp' (`is_amp_endpoint()` returns false).

I am still trying to hunt down the cause for it but I saw this and I thought it may be related.

Just to be clear, I am talking about posts on a URL that has a category on it, but posts after all.

**Comment by j3j5** [comment]
I forgot to mention that they don't work when using `/amp`, when using `?amp=1` everything works as expected.

**Comment by mjangda** [comment]
@j3j5 likely a different issue. Can you open a new ticket with details on
what your extra_permastructs looks like and how you're adding it?

If I had to guess, it's that add_rewrite_endpoint doesn't add to the
extras.

**Comment by j3j5** [comment]
I'm trying to gather all details and I'll open the issue asap, I thought it'd be related to https://core.trac.wordpress.org/ticket/33728 but adding the patch did not fix the issue.

Still hunting it down!
