### ISSUE TITLE
Custom template shows blank screen

### ISSUE THREAD

**Issue by mariusrudolph** [Automattic/amp-wp#1222]
Hi there, I tried to add a custom template for my amp site. I added the following code to my functions.php:

`add_action( 'amp_init', 'amp_berufsbilder' );
function amp_berufsbilder() {
add_post_type_support( 'ausbildung', AMP_QUERY_VAR );
}
add_filter( 'amp_post_template_file', 'amp_berufsbilder_template', 10, 3 );

function amp_berufsbilder_template( $file, $type, $post ) {
if ( 'single' === $type && 'ausbildung' === $post->post_type ) {
$file = dirname( FILE ) . '/amp_berufsbilder.php';
}
return $file;
}`

The amp_berufsbilder.php is just a copy of the single.php and it is in the same folder. Any help is appreciated!

**Comment by westonruter** [comment]
A blank screen may indicate a server error. Can you look at your PHP error log or enable WP_DEBUG?

**Comment by mariusrudolph** [comment]
Hi @westonruter , I activated WP_DEBUG. I got the following message:

Notice: Use of undefined constant FILE - assumed 'FILE' in /www/htdocs/w014ca00/domain.de/wp-content/themes/talenthero/functions.php on line 312

Notice: AMP_Post_Template::verify_and_include wurde fehlerhaft aufgerufen. Path validation for template (./amp_berufsbilder.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 0.1 hinzugefügt.) in /www/htdocs/w014ca00/domain.de/wp-includes/functions.php on line 4148

I am not really sure what to do.

**Comment by westonruter** [comment]
Replace `FILE` with `__FILE__`.

**Comment by mariusrudolph** [comment]
@westonruter : Thanks! I still have the following message:

Notice: AMP_Post_Template::verify_and_include wurde fehlerhaft aufgerufen. Path validation for template (/www/htdocs/w014ca00/domain.de/wp-content/themes/talenthero/amp_berufsbilder.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 0.1 hinzugefügt.) in /www/htdocs/w014ca00/domain.de/wp-includes/functions.php on line 4148

I moved the amp_berufsbilder.php to my themes folder but there is no change.

**Comment by westonruter** [comment]
It's probably failing because the file doesn't exist. After you do:

```
$file = dirname( __FILE__ ) . '/amp_berufsbilder.php';
```

Try printing out `$file` to see where you are constructing the path.

**Comment by mariusrudolph** [comment]
It says "/www/htdocs/w014ca00/domain.de/wp-content/themes/talenthero/amp_berufsbilder.php

I have uploaded the amp_berufsbilder.php to the themes folder.

**Comment by westonruter** [comment]
Next look at the `\AMP_Post_Template::verify_and_include()` function:

https://github.com/Automattic/amp-wp/blob/70711f0cd647f233b02ffa1bbbd58496eeeea510/includes/templates/class-amp-post-template.php#L425-L446

I'm not sure what is wrong, but you can debug around the `is_valid_template()` to figure out what is going on.

**Comment by mariusrudolph** [comment]
Hi @westonruter , thanks a lot for your help. I am not quite sure how to debug this function and see the output on my amp site. Can you help me out here?

**Comment by westonruter** [comment]
Sorry, I can't really help further.
