### ISSUE TITLE
validation error- amp iframe

### ISSUE THREAD

**Issue by sayakshinobu** [Automattic/amp-wp#1223]
the page i am using is 
https://psychologyunleashed.com/ant-depressive-drugs/amp
the result is
The tag 'amp-iframe' requires including the 'amp-iframe' extension JavaScript.
https://search.google.com/test/amp?id=qiRu7JGCTuBc_Ut2JW8aKQ

**Comment by westonruter** [comment]
You have some kind of web optimizer plugin active that is corrupting the AMP response. The AMP component scripts are getting combined into a single script in the footer:

```html
<script type="text/javascript" src="https://psychologyunleashed.com/wp-content/cache/min/1/33bc2fbee8eed175c454682c7801bfcb.js" data-minify="1" async="async" crossorigin="anonymous"></script>
```

Turn off the optimizer plugin, or deactivate it for AMP responses.

**Comment by sayakshinobu** [comment]
can you specify the url of the js file of amp? like /wp-content/amp/....js
