### ISSUE TITLE
Google: Custom Javascript is not allowed

### ISSUE THREAD

**Issue by e11productions** [Automattic/amp-wp#1224]
I'm not sure if this is caused by our theme or the plugin. We haven't gotten this error until now, but have been using the same theme and plugin for over 1.5 years. Any ideas? https://episode11productions.com

**Comment by westonruter** [comment]
See validator response: https://validator.ampproject.org/#url=https%3A%2F%2Fepisode11productions.com%2Fvideo-edit-is-important%2Famp%2F

This JS is being injected into the head:

```html
<script src='/google_analytics_auto.js'></script>
```

This is due to some plugin you have active.
