### ISSUE TITLE
Add AMP enabled/disabled toggle to Gutenberg editor

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1230]
The classic post editor has a toggle to enable/disable AMP for a given post:

![image](https://user-images.githubusercontent.com/134745/41952109-1569d2d6-7983-11e8-95b3-e3e097108b66.png)

This needs to be added to Gutenberg as well.

**Comment by westonruter** [comment]
@jwold This needs some Gutenberg design insights.

**Comment by westonruter** [comment]
The AMP-specific blocks should not be made available on the Inserter when AMP is disabled for a given post, even in native mode.

**Comment by jwold** [comment]
@westonruter what would happen in this scenario:

1. Enable AMP in a Gutenberg post
2. Add an AMP-specific block
3. Disable Gutenberg
4. What happens to that block that's already on the page? Should we display a notice around it that it's incompatible, should we gray it out?

**Comment by jwold** [comment]
![screen shot on 2018-07-10 at 08_04_29](https://user-images.githubusercontent.com/3411173/42519016-f1b2f68e-8417-11e8-8384-812dc4549a29.png)

For the interface in Gutenberg I'm thinking something as simple as this ^

Any concerns?

**Comment by westonruter** [comment]
@jwold that mock looks good to me. I'm assuming Gutenberg has is extensible to allow new toggles to be added in that location.

> What happens to that block that's already on the page? Should we display a notice around it that it's incompatible, should we gray it out?

Good question. In the case where you've added an AMP-specific block to content but then you disable AMP, the next time you access the post then the block would be unrecognized and it would show the same notice as if a block from a plugin were in content but then the plugin was deactivated:

![image](https://user-images.githubusercontent.com/134745/42525790-e4b118d8-8428-11e8-8471-aaac2ea89d80.png)

This seems acceptable to me.

**Comment by jwold** [comment]
> In the case where you've added an AMP-specific block to content but then you disable AMP, the next time you access the post then the block would be unrecognized and it would show the same notice as if a block from a plugin were in content but then the plugin was deactivated:

I'm good with this approach, my only question is if we should change the wording at all to be specific, such as, 

"This block requires enabling AMP in the document settings"
[ Re-enable AMP button ]   [ Edit as HTML button ]

**Comment by westonruter** [comment]
That screenshot is just the default view as presented in Gutenberg for a block that is no longer recognized. I'm not sure how easy it is to customize it for specific blocks. That would be nice for the AMP case here.

**Comment by kienstra** [comment]
Here's a document on how to add a row in the Gutenberg "Status & Visibility" panel:

https://wordpress.org/gutenberg/handbook/packages/packages-edit-post/#pluginpoststatusinfo

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

1. [Create a new post](https://paired-ampconfdemo.pantheonsite.io/wp-admin/post-new.php), using Gutenberg

2. Expected: the "Enable AMP" toggle is on
<img width="1432" alt="post-block-editor" src="https://user-images.githubusercontent.com/4063887/43661023-4b22cab6-9726-11e8-892d-04dc39c326a4.png">

3. Add a title to the new post, then click "Save Draft" and "Preview"
4. Add `&amp` to the URL, and go to that address. 
5. Expected: it's a valid AMP page, per the [Chrome AMP Extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=es):
<img width="1434" alt="valid-amp-page" src="https://user-images.githubusercontent.com/4063887/43661200-fc0f61b8-9726-11e8-81ec-f799e4a3ca6c.png">

6. Go back to the editor, uncheck the "Enable AMP" toggle, and click "Save Draft"
7. Repeat step 4.
8. Expected: The page redirects to the URL without `&amp` appended, as the AMP page isn't available
9. Go to the AMP settings page, ensure "Paired" is selected, and uncheck "Pages":
<img width="1183" alt="amp-general-settings" src="https://user-images.githubusercontent.com/4063887/43661378-99b26046-9727-11e8-8754-0f11b47c0f24.png">

10. Create a [new page](https://paired-ampconfdemo.pantheonsite.io/wp-admin/post-new.php?post_type=page) using Gutenberg:
11. Expected: There's no "Enable AMP" toggle, only a notice:
<img width="1433" alt="amp-notice" src="https://user-images.githubusercontent.com/4063887/43661461-fba4325c-9727-11e8-9aa6-53cd5a19791d.png">
12. Check the "Pages" box again from step 9, and click "Save Changes"

**Comment by kienstra** [comment]
**Request For Regression Testing**

 Hi @csossi,
Thanks for testing this. Could you please retest this to ensure there wasn't a regression, using the [test steps above](https://github.com/Automattic/amp-wp/issues/1230#issuecomment-410351014)?

Here's the staging site:
https://paired-ampconfdemo.pantheonsite.io/

Thanks, Claudio!

**Comment by csossi** [comment]
Verified in QA
