### ISSUE TITLE
Invalid CSS stylesheet

### ISSUE THREAD

**Issue by bianqui149** [Automattic/amp-wp#1231]
Hi, I have this issue:
Invalid CSS stylesheet: CSS syntax error in tag 'style amp-custom' - incomplete declaration.
Line 400:48 font=size:14pt;}	</style>
/* Inline styles */
.amp-wp-inline-1563bfb46b2335ae0c56ceb9a90c2666{font=size:14pt;}	
Any idea how should fixed?

**Comment by westonruter** [comment]
What is the URL to your AMP page that has the problem?

**Comment by bianqui149** [comment]
HI! This is the url
https://www.actionaidusa.org/blog/preventing-disaster-dhaka/amp/

**Comment by westonruter** [comment]
Your underlying post has invalid CSS. On the [non-AMP version](https://www.actionaidusa.org/blog/preventing-disaster-dhaka/] I can see:

```html
<p style="font=size: 14pt;">
```

Replace that with:

```html
<p style="font-size: 14pt;">
```

And the error will go away.

**Comment by westonruter** [comment]
Aside: The 1.0 version of this plugin will automatically strip such syntax errors and prevent them from being served in the AMP version.
