### ISSUE TITLE
Plugin update from 0.6.2 to 0.7.1 causing Google validation errors

### ISSUE THREAD

**Issue by jagsileo** [Automattic/amp-wp#1233]
Hello,

We updated the AMP plugin from 0.6.2 to 0.7.1 and ever since we have been receiving the following validation errors causing our AMP pages to be removed from Google indexing.

| The attribute 'defer' may not appear in tag 'amphtml engine v0.js script'.
| The attribute 'defer' may not appear in tag 'amp-analytics extension .js script'.
| The attribute 'defer' may not appear in tag 'amp-iframe extension .js script'.

![screen shot 2018-06-20 at 10 44 45 pm](https://user-images.githubusercontent.com/16673020/42057650-0c1cba80-7aec-11e8-858b-9a188a026494.png)

Tried turning off other plugins to see if this was due to a plugin conflict but negative. Updating to 0.7.2 also did not help. For now, we have reverted to 0.6.2, we notice the defer attribute goes away and the post passes validation. Here are our wordpress installation details:

WordPress version: 4.9.6
Theme: Avada – 5.4.

Any help would be appreciated.

Thanks,
Jagathshree

**Comment by westonruter** [comment]
Those are being added by another plugin you have active. In any case, v0.7.2 which we released yesterday should have fixed this problem (via #1227). Please update to the latest version.
