### ISSUE TITLE
How change amphtml or URL 

### ISSUE THREAD

**Issue by bambibambi1** [Automattic/amp-wp#1234]
Hi
I found difference between 'amphtml' and valid URL about custom post type.

・normal post type
'amphtml' :  "http://mydomain.com/archives/postID?amp"

”http://mydomain.com/archives/postID?amp” and  ”http://mydomain.com/archives/postID/amp”
Both is available.

・Custom post type
'amphtml' :  http://mydomain.com/custom/postID/amp 

”http://mydomain.com/archives/postID?amp” is only available.

I tried to access ~/amp,but not found(404).

I'd like to change  '/amp'  into '?amp'.   

How can I change 'amphtml'?

**Comment by westonruter** [comment]
See https://github.com/Automattic/amp-wp/issues/1148#issuecomment-388987756

**Comment by bambibambi1** [comment]
Thanks!
