### ISSUE TITLE
Decide whether declared theme support should include 'optional'

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1238]
In #1235 support was added for theme support to be declared but optionally. For example:

```php
add_theme_support( 'amp', array(
    'optional' => true,
    'comments_live_list' => true,
) )
```

The idea here is that this would allow a theme to pre-configure a theme to have support but for the plugin to not actually apply the `amp` theme support unless the user opts-in via the admin screen. This would allow a user to activate such a theme but retain the Classic template mode until they decide they want it. This doesn't seem like a very compelling use case and it could be eliminated.

**Comment by kienstra** [comment]
**Theme support argument of 'optional'**

Hi @westonruter,
It's good to consider this `'optional'` argument. But I don't think themes that register support also need to be able to use "Classic" mode.

It looks like users can still disable any "Supported Template," even if the theme has:
```php
add_theme_support( 'amp', array(
	'comments_live_list' => true,
	'mode'               => 'native',
) );
```
<img width="1020" alt="supported-templates-amp" src="https://user-images.githubusercontent.com/4063887/42244752-d61e6728-7edb-11e8-83c3-528e66d485d5.png">

I think this is enough, and we probably don't have to support "Classic" templates in theme support cases.
