### ISSUE TITLE
Add Support for Jetpack / WP.com related posts

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#124]

**Comment by gibrown** [comment]
Took a quick look at how to implement this. We currently only render related posts on the client side for Jetpack. I think with the implied caching of AMP that it would be better to render the related posts on the page load. Links of course should get changed to point to the amp version of the pages.

Doing this requires adding a new method of rendering the related posts in https://github.com/Automattic/jetpack/blob/master/modules/related-posts/jetpack-related-posts.php

**Comment by mjangda** [comment]
We could possible use `amp-list` (I even wrote an example for it :) https://github.com/Automattic/amp-wp#custom-embed-handler) although, it expects the endpoint to return data in a specific format (namely, it wants a JSON object with an `items` key).

**Comment by gibrown** [comment]
Interesting, ya that could be made to work. Right now related posts passes the query through to the site where various filters are applied rather than hitting our public api directly.

The benefit of embedding it in the original html is that we can probably use any existing filters or customizations that the user has applied. But maybe those customizations wouldn't make sense anyways with AMP.

**Comment by gibrown** [comment]
Oh, also we should add some sort of click tracking for clicking on the related posts, but I think this is a general problem with Jetpack Related posts.

**Comment by gibrown** [comment]
Per https://www.alexkras.com/google-may-be-stealing-your-mobile-traffic/ this should maybe be implemented in general. When a related posts system exists, then use that. When it doesn't exist, then show the X most recent posts other than the current post. Try to keep the user on the current site.

**Comment by westonruter** [comment]
This should rather be added to the Jetpack plugin itself. See #1021.

**Comment by westonruter** [comment]
For the Jetpack issue specifically for Related Posts compatibility with AMP, see https://github.com/Automattic/jetpack/issues/9556
