### ISSUE TITLE
Update CSS Parser to eliminate CSS3 calc() workaround 

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1240]
As a site admin, I should have the fix that eliminates CSS3 `calc()` workarounds inside the AMP core codebase.

- [ ] AC1: Merge in the code (as specified below) and validate the CSS parser works as expected, removing the lingering workaround in our plugin core.

--- 

In #1116 we added a workaround to preserve CSS3 `calc()` functions since they weren't supported in PHP-CSS-Parser. However, now they are: https://github.com/sabberworm/PHP-CSS-Parser/pull/128. So we can merge the latest into [our fork](https://github.com/xwp/PHP-CSS-Parser) and eliminate the `calc()` placeholders.

**Comment by postphotos** [comment]
Hi @westonruter, Thanks for this! I've written up a quick user story here. It sounds like this should be pretty straightforward to squeeze into our v1.0 stable release. 👍

**Comment by kienstra** [comment]
**Moving to 'Ready For Merging'**

If it's alright, I'm moving this to 'Ready For Merging,' as it looks like this doesn't need functional testing.
