### ISSUE TITLE
"Template Mode" is set to "Native," and <input> elements are disabled

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#1245]
This might be the intended behavior, but when using a Core theme like Twenty Seventeen, the "Template Mode" is always "Native," and the `<input>` elements are disabled.

**Steps to reproduce:**
1. Activate Twenty Seventeen
2. Go to the "AMP Settings Page"
3. Expected (I think): you can select the "Template Mode" of "Classic," "Paired," or "Native"
4. Actual: "Native" is selected, and the `<input>` elements are disabled:

<img width="1257" alt="native-selected" src="https://user-images.githubusercontent.com/4063887/42242255-dee26782-7ed2-11e8-8658-617e9136bf3d.png">

This existed even after doing `wp option delete amp-options`, to ensure that a previous option I selected wasn't interfering.

Maybe the [disabled() calls](/Users/ryankienstra/Projects/vvv2/www/loc/public_html/wp-content/plugins/amp/includes/options/class-amp-options-menu.php) should be `disabled( ! $mode_mutable )` instead of `disabled( ! $theme_support_mutable )`.

**Comment by westonruter** [comment]
Fixed by #1246.
