### ISSUE TITLE
analytics options empty and ID box disabled

### ISSUE THREAD

**Issue by pmkloet** [Automattic/amp-wp#1253]
Hello All,
Within de amp analytics options they type box is empty, nothing can be selected. Also the ID input box is disabled (grey). What can be wrong? See screenshot att. I don't have a unix login on my webserver.
![screenshot 2018-07-06 09 53 56](https://user-images.githubusercontent.com/40594410/42367109-5c096b7a-8103-11e8-8207-5b26e78d63cf.png)

**Comment by westonruter** [comment]
The ID is not something you are supposed to enter; it is automatically populated. You just enter the type (e.g. `googleanalytics`) and then the JSON data. Please see https://github.com/Automattic/amp-wp/wiki/Analytics
