### ISSUE TITLE
Show admin pointer for AMP admin screen when updating to 1.0

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1254]
Since 1.0 introduces an admin UI for managing the theme support mode, including allowing the user to opt-in to paired and native modes without having to make any code changes, we should add an admin pointer to invite users to try out the new modes:

![image](https://user-images.githubusercontent.com/134745/42391708-e82a2fce-8115-11e8-871b-c1a41368cd01.png)

This could be paired with the ability to do a scan of their site to check for compatibility (see #1007).

**Comment by kienstra** [comment]
**Moving To "Ready For Merging"**

This might be able to use functional testing. But this is hard to test, as once you dismiss the pointer, it never appears again. 

So once this is deployed to a staging environment, someone might dismiss the pointer before it can be tested.
