### ISSUE TITLE
Live-blog functionality w/ amp-live-list

### ISSUE THREAD

**Issue by ericlindley-g** [Automattic/amp-wp#1256]
AMP makes it easy to create a live blog with [amp-live-list](https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list.md): developers wrap live content in amp-live-list, and re-publish the page when new entries are available. This feature request is to implement this functionality in WP.

Options:
- Gutenberg block for live blog entries or special page type for live blog entries?
- In AMP WP plugin or through different mechanism?

/cc @amedina @westonruter

**Comment by westonruter** [comment]
@ericlindley-g The [Liveblog plugin](https://github.com/Automattic/liveblog) actually is getting updated to support `amp-live-list` out-of-the-box, supported by the AMP plugin. I don't see a PR for it yet, but I know it is being worked on. We talked with the devs during the VIP Workshop in May.

Alternatively, the AMP plugin does today allow you to create a Liveblog of sorts by turning comments list into an `amp-live-list`: https://github.com/Automattic/amp-wp/wiki/Commenting#live-commenting-using-a-live-list

**Comment by ericlindley-g** [comment]
Great to hear! So it sounds like nothing extra is needed for the AMP WP plugin—does that sound right to you?

Though I'm wondering if there's something that needs to be done to make it so the liveblog plugin
can be used on a WP.com site? (I couldn't find the plugin while searching on a set site)

**Comment by westonruter** [comment]
I found the PR and it has been merged: https://github.com/Automattic/liveblog/pull/450

I see it is coming in the v1.9 release which is not out yet. 

I don't recall Liveblog being available on WordPress.com generally. I remember it was an add-on that was only available to VIP sites. I think this is because of the additional server resources required to serve it.

In any case, you're right that there's nothing else required by the AMP plugin to support liveblogging.

**Comment by ericlindley-g** [comment]
Ah, interesting — maybe we can create documentation that makes it clear how to do liveblogging with the comment functionality. (I wonder if at some point it would be worth putting the existing functionality in a wrapper that makes the use-case really obvious, as well)

**Comment by westonruter** [comment]
I think the Liveblog plugin should be the general solution for this. I don't think WordPress.com would allow using comments for liveblogging either if the underlying issue is the additional server resources required, but we should just check with them. @philipjohn thoughts?
