### ISSUE TITLE
Amp 1.0 beta Auto Ads  excluded

### ISSUE THREAD

**Issue by markbiernat** [Automattic/amp-wp#1258]
Native works perfectly with WP Twenty Seventeen theme.
Version 1.0-beta1-024e4507-20180706T154134Z
However, all Auto AMP Adsense ads do not display.
I inserted the code in the html-start.php after the <head> and after <body class=...?>">
When I view source of a page I see no ad code.
I believe AMP  excludes this script.
Since many people use Adsense it would be a good feature allow.

**Comment by westonruter** [comment]
Try adding `amp-auto-ads` to a child theme if Twenty Seventeen. Add it to a `header.php` file in the child theme. The `html-start.php` template part is only for the legacy templating mode which is not used when you select native or paired modes. You'd have to do additional work to get the required component script to be added in classic mode.

**Comment by markbiernat** [comment]
It works, thank you.

**Comment by markbiernat** [comment]
The Auto Ads exist in the child header and body as specified.
I tried keeping the code from the non-amp auto ads.
and removing the code from the non-amp auto ads.
While keeping the amp auto ads in the child and neither brings ads to a desktop display
Except disabling AMP.
I tried disabling cache and Jetpack also but it was only AMP that affect the desktop display.
On a positive note AMP runs fast and the mobile version works.

**Comment by westonruter** [comment]
@markbiernat I'm not sure there's any issue here in regards to the AMP plugin. It sounds like your question may be for the AMP project itself or for AdSense.

**Comment by markbiernat** [comment]
I have posted on the AMP Project github and written Google. I do not expect reply but I will report here if I have any resolve.

**Comment by markbiernat** [comment]
[https://github.com/ampproject/amphtml/issues/16599#issuecomment-405319769](url)

This is the issue posted on the AMP project.  I added some images for clarity and there is a link to my site.
