### ISSUE TITLE
Hummingbird WPMU DEV plugin not working with Beta

### ISSUE THREAD

**Issue by markbiernat** [Automattic/amp-wp#1262]
There are a series of complex settings with Hummingbird, so it might not be AMPs fault. However, when I use Hummingbird WPMU DEV plugin with AMP Beta it strips away any formatting. 

That is, the page appears white with no CSS and just unformatted text and blue links.

I think AMP is moving in the right direction, just making you aware of potential issues.

**Comment by westonruter** [comment]
It could be that there is too much CSS and so it is getting excluded.

**Comment by markbiernat** [comment]
I am testing this with the Twenty Seventeen theme and only  a couple  Wordpress (Automattic or WPMU) plugins.

This is a very basic install. I am purposely testing the AMP plugin on a basic install to help the project and of course use it on my site.

I stripped out any CSS that does not come with the out of the box with the standard Wordpress Twenty Seventeen theme.

 Is there a way to make this plugin work with WPMU's  Hummingbird?

**Comment by postphotos** [comment]
Hi @markbiernat, thanks for writing in. I haven't used Hummingbird, but based on [this page](https://premium.wpmudev.org/project/wp-hummingbird/) I see their marketed feature set is:
- Performance Report
- Asset Optimization
- Gzip Compression
- Complete Cache Suite
- Cloudflare Cache-Control
- Hosted File Optimization

I can't speak to its utility, but I believe plugin (as per [what AMP is designed to do](https://www.ampproject.org/learn/overview/)) are running additional optimizations which are likely unnecessary when running a Native AMP site using this plugin. I see there's a known conflict with Cloudflare Rocket Loader, which I think would be a similar issue (that plugin modifies your site's output of AMP pages). I had similar issues with Autoptimize as well on a site but just used AMP on its own as multiple plugins trying to optimize can be hard to do.

I'd recommend choosing a single optimization strategy - i.e. choose just one plugin. and if there's a core feature you need from the Hummingbird plugin and you'd prefer to use both, I'd consider reaching out to the WPMUdev team and asking them to test this.

**Comment by westonruter** [comment]
I've seen generally that such performance plugins should be configured to turn off features when serving AMP responses. This probably would be something WPMU DEV should add to their plugin for compatibility.

**Comment by markbiernat** [comment]
Thank you again. I turned the plug-in and am going to run AMP native as my primary optimization because the multiple performance tests indicate Native AMP is serving highly optimized pages without the need for extras.
