### ISSUE TITLE
How to remove blacklist element?

### ISSUE THREAD

**Issue by arshidkv12** [Automattic/amp-wp#1263]
I am developing amp form. It is working in page. But not working by do_shortcode. 

How to load amp-form js ?

**Comment by westonruter** [comment]
You'll need to provide more information. How are you embedding the form in the page? Is it inside the page content or outside the content? Are you using [`amp` theme support](https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support) or classic mode?

**Comment by arshidkv12** [comment]
I want use in outside of the content and amp theme support.

**Comment by westonruter** [comment]
You shouldn't have to do anything. By merely outputting `<form>` to your template, the `amp-form` component script will automatically be added. See https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support#auto-enqueue-component-scripts
