### ISSUE TITLE
Change the order of template modes in admin interface

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#1264]
**As a user, I should see "Native" as the first toggleable option for AMPhtml so that I am most likely to choose this option.**

- [ ] AC1: Instead of the ordering list of "Classic, Paired, Native" I should see "Native, Paired, Classic" as the three options.

---

Currently the operational mode of the plugin can be configured in the admin via toggle buttons. The current ordering of the buttons reflects the chronological evolution of the modes: `Classic`, `Paired`, `Native`. Proposal: Change the order to have `Native` first to implicitly encourage that as the best option.

<img width="1137" alt="screen shot 2018-07-10 at 2 24 23 pm" src="https://user-images.githubusercontent.com/506089/42512683-2f1ede5e-844d-11e8-92eb-a07091192937.png">

**Comment by postphotos** [comment]
Hi @amedina, Thanks for this! I've wrote a quick user story for this ticket. We should be able to add this to our v1.0 stable release.

**Comment by kienstra** [comment]
**Confirmed, Moving To "Ready For Merging"**

This look good. "Native" now appears at the top of the "Template Mode" field.

I'm moving this to "Ready For Merging."

<img width="1398" alt="amp-settings" src="https://user-images.githubusercontent.com/4063887/43659767-97045d04-9722-11e8-805c-fae393cefb14.png">
