### ISSUE TITLE
Header scripts out of order

### ISSUE THREAD

**Issue by what2think** [Automattic/amp-wp#1265]
According to Google (via [this guide](https://developers.google.com/analytics/devguides/collection/amp-analytics)):

> To add AMP analytics functionality to your page include the following script in the `<head>`, **before** the AMP JS library

The plugin puts the AMP JS library first, followed by the analytics script

**Comment by westonruter** [comment]
You're right. We need to optimize the order of elements that are output in the `head`. In addition to the placement of the AMP runtime script, there are other optimizations to be made including the use of the `rel=preload` link for the script, hero images, and custom fonts. @sebastianbenz has been putting more details which we can implement here.

**Comment by sebastianbenz** [comment]
The GA documentation is wrong in this case (I filed a bug). The import order is not critical (all imports are async anyway). However, there are a few performance best practices I'm currently documenting ([current draft](https://docs.google.com/document/d/169XUxtSSEJb16NfkrCr9y5lqhUR7vxXEAsNxBzg07fM/edit#)).

**Comment by westonruter** [comment]
Performance best practices have been implemented in https://github.com/Automattic/amp-wp/pull/1295

**Comment by kienstra** [comment]
**'Moving to 'Ready For Merging'**

If it's alright, I'm moving this to 'Ready For Merging,' as it looks like this doesn't need functional testing.
