### ISSUE TITLE
Google error

### ISSUE THREAD

**Issue by ecomotive95** [Automattic/amp-wp#1266]
I have this issue in google amp : 
The tag 'amp-social-share extension .js script' appears more than once in the document. This will soon be an error.
I search this code in plugin editor to clean but i don't find it !
What i can do to fix this problem in google errors ?
Tnx

**Comment by westonruter** [comment]
Please see https://wordpress.org/support/topic/the-tag-amp-social-share-extension-js-script-appears-more-than-once/
