### ISSUE TITLE
Youtube Subscribe button

### ISSUE THREAD

**Issue by markbiernat** [Automattic/amp-wp#1268]
I use  a Youtube Subscribe button in my sidebar.

I use the code Google recommends:

https://developers.google.com/youtube/youtube_subscribe_button

When I activate AMP (Native) I get:

no link to my Youtube channel.

What is circled in yellow disappears.
![econ](https://user-images.githubusercontent.com/30418497/42770976-b1691afa-88f3-11e8-83c0-c3d9cf154ea8.jpg)

**Comment by westonruter** [comment]
@markbiernat This is entirely expected. If the snippet is:

```html
<script src="https://apis.google.com/js/platform.js"></script>

<div class="g-ytsubscribe" data-channel="GoogleDevelopers" data-layout="default" data-count="default"></div>
```

The `script` is not valid AMP and so it is getting removed by the sanitizer. I don't see YouTube providing any `noscript` alternative using a straight `iframe`, so I don't see what can be done by the plugin. Google should provide an AMP-based solution for this button.
