### ISSUE TITLE
CSS changes on homepage

### ISSUE THREAD

**Issue by markbiernat** [Automattic/amp-wp#1269]
On a standard Twenty Seventeen theme, and I activate AMP Beta Native, it seems to have CSS issues.
Please see the

before activation:
![before](https://user-images.githubusercontent.com/30418497/42773646-e7a76812-88fb-11e8-92b6-7394a539cbdf.jpg)

and after activation:
![after](https://user-images.githubusercontent.com/30418497/42773652-ecd9359a-88fb-11e8-8712-917ad42d8434.jpg)

It puts a top menu that should not be there and cuts off the tagline.  Further when I resize in a mobile view it does not resize the mobile title and tagline properly.
![mobile](https://user-images.githubusercontent.com/30418497/42773760-3d42bf60-88fc-11e8-8526-01da9c4626e1.jpg)

**Comment by westonruter** [comment]
@markbiernat this may be an issue with a nav menu having more items than fit on one line. Does the issue go away if you remove a couple items so they all fit on one line?

**Comment by markbiernat** [comment]
It does not. I tried it with three menu items and the same result.

**Comment by westonruter** [comment]
@markbiernat I'm using (a child theme of) Twenty Seventeen myself on my own site and I don't see this issue:  https://weston.ruter.net/

**Comment by westonruter** [comment]
Is the added CSS getting excluded due to there being too much?

**Comment by westonruter** [comment]
If you can make your site publicly available in paired mode so that the non-AMP and AMP versions can be compared, then that would be helpful.

**Comment by markbiernat** [comment]
http://political-economy.com/   I changed it to pair mode from native.   I will change it back when you are done as I do not want to search engines to get too confused.

**Comment by westonruter** [comment]
The AMP version is redirecting to the non-AMP version. You'll need to enable auto-sanitization of the validation errors:

![image](https://user-images.githubusercontent.com/134745/44417472-7e3df800-a52a-11e8-9ede-84af132bc53d.png)

**Comment by westonruter** [comment]
The difference I see in the header:

# Non-AMP Version

![image](https://user-images.githubusercontent.com/134745/44419703-c95b0980-a530-11e8-9ffb-16a2196ead86.png)

# AMP Version

![image](https://user-images.githubusercontent.com/134745/44419721-d2e47180-a530-11e8-9d05-116c311666b0.png)

# Non-AMP Version with JavaScript Disabled

![image](https://user-images.githubusercontent.com/134745/44419931-65851080-a531-11e8-8698-cd2d55bb05b3.png)

**Comment by westonruter** [comment]
One obvious problem is that the Quicksand font is not loading. One key reason I see that could be causing a problem is this CSS in your child theme:

```css
@import url('https://fonts.googleapis.com/css?family=Quicksand');`
```

Using `@import` is not a recommended way to load CSS. You should use `wp_enqueue_style()` instead, similar to how Twenty Seventeen is doing. This will ensure that the stylesheet is loaded at the optimal time, and that WordPress can add the `preconnect` link.

**Comment by markbiernat** [comment]
I can try that.  Thank you for looking at this.

I had fixed the initial more important issue of the header alignment and duplicate appearance of the menu (top and bottom)  by deleting some css which simply changed the font size of the menu font. I am able to live with the default menu font size. However, I can take your suggestions for the load CSS. Thank you again.
