### ISSUE TITLE
/amp/ only works with Blog posts, not pages

### ISSUE THREAD

**Issue by lee-supportedbusiness** [Automattic/amp-wp#1270]
As above.

Put quite simply, I can only see /amp/ working at the end of the URL for posts. If I have a page with AMP 'Enabled', I can view the version by adding ?amp at the end, but using /amp/ results in a 404 error page.

This is even after trying to flush Permalinks by Saving the settings, and also checking 'Page' in the AMP settings and saving.

Is this expected behaviour, surely it's not?

**Comment by giuliohome** [comment]
TwiitterLite is also using AMP and it causes this sort of issue with links in tweets like this 
https://mobile.twitter.com/fannicanelles/status/1018911387928682496
leading to error 404

**Comment by westonruter** [comment]
@lee-supportedbusiness This is expected. Please read https://wordpress.org/support/topic/0-6-0-not-working-for-pages/#post-9903766

To find out what the AMP version of a given URL, please look at the source code for the non-AMP version of the page and find `<link rel="amphtml" href="...">`. The value in the `href` attribute will be the AMP version of the page. If there is no such `link` element in the page, then this means that there is no AMP version available and you may need to enable post type support or enable support at the post/page level.

Going forward the `/amp/` endpoint will be deprecated in favor of `?amp` for consistency. The query var will always be used when [AMP theme support](https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support) is present.

@giuliohome I don't see any such `amphtml` link on http://www.socialnews.it/blog/2018/07/16/human-o-digital-driven-ritorno-al-futuro/ so it makes sense why this would 404.

**Comment by giuliohome** [comment]
Please note, the amp link is `https://t.co/hOgGWD7utp?amp=1` and it is present in the twitterlite (=mobile web version) page of the tweet (I have reported in my previous comment, it starts with mobile.twitter).
I suspect it is a wordpress page (not an article) and that is causing the 404 issue with the AMP link.

**Comment by giuliohome** [comment]
Let me add that a user of Twitter simply writes a tweet with a non-amp link, so for example a tweet with a normal link to a WordPress page. So when you write "it is expected, please see...", consider that it is the twitterlite app which automatically adds the amp suffix to any tweet. Then it should be explained to them that this can be a problem in some cases...

**Comment by giuliohome** [comment]
Thank you for closing the issue anyway: sometimes it seems that it is a complete waste of time to report a problem to github and people are using public repositories because it is trendy but they don't really want to read any issue.

**Comment by giuliohome** [comment]
Yes, now we can no longer see the problem with that tweet now. I don't know who solved it, I eonder if it was Twitter itself or the admin of the wp site.
