### ISSUE TITLE
How to fix - 'script' appears more than once' - validation error

### ISSUE THREAD

**Issue by markbiernat** [Automattic/amp-wp#1272]
This is not an issue but a fix, I know others will come across this, I thought it would help.

When you have a validation error:  tag 'amp-auto-ads extension .js script' appears more than once in the document."    Slight modification from Weston's code he posted on the legacy support forum.

The whole idea is a filter.

Remove from your head the code and then
Add this to functions.php

```php
add_filter( 'wp_head', function( $data ) {
	$data['amp_component_scripts'] = array_merge(
		$data['amp_component_scripts'],
		array(
			'amp-ad' => 'https://cdn.ampproject.org/v0/amp-ad-latest.js',
		)
	);
	return $data;
} );
```

**Comment by westonruter** [comment]
Thank you.
