### ISSUE TITLE
How response extra header in wp-ajax?

### ISSUE THREAD

**Issue by shangdev** [Automattic/amp-wp#1276]
I create comments form in amp, when i submit this form, i need Response must contain the AMP-Access-Control-Allow-Source-Origin header.

I use wp_send_json() complate response, how to contain the AMP-Access-Control-Allow-Source-Origin header?

Please help me!

**Comment by westonruter** [comment]
A custom comments form and not the standard WordPress one? Please share the code you are using.

**Comment by shangdev** [comment]
```
<?php
/**
 * Comments template part.
 *
 * @package AMP
 */

if ( !is_ssl() )
    return;
?>
<div class="amp-wp-meta amp-wp-comments">
    <div class="amp-wp-comments-slug"><?php esc_html_e( 'Inquiry for us', 'trueniu' ); ?></div>
    <form method="post"
          action-xhr="<?php echo home_url(); ?>/wp-admin/admin-ajax.php"
          target="_top"
          custom-validation-reporting="show-first-on-submit">
        <div class="amp-wp-comments-group">
            <label><?php esc_html_e( 'Name:', 'trueniu' ); ?></label>
            <input type="text" name="author" id="name">
        </div>
        <div class="amp-wp-comments-group">
            <label><?php esc_html_e( 'E-mail:', 'trueniu' ); ?><strong>*</strong></label>
            <input type="email" name="email" id="show-first-on-submit-email" required>
            <span visible-when-invalid="valueMissing" validation-for="show-first-on-submit-email"></span>
            <span visible-when-invalid="typeMismatch" validation-for="show-first-on-submit-email"></span>
        </div>
        <div class="amp-wp-comments-group">
            <label><?php esc_html_e( 'Phone:', 'trueniu' ); ?></label>
            <input type="text" name="phone">
        </div>
        <div class="amp-wp-comments-group">
            <label><?php esc_html_e( 'Content:', 'trueniu' ); ?><strong>*</strong></label>
            <textarea name="comment" id="show-first-on-submit-comments" required></textarea>
            <span visible-when-invalid="valueMissing" validation-for="show-first-on-submit-comments"></span>
            <span visible-when-invalid="typeMismatch" validation-for="show-first-on-submit-comments"></span>
        </div>
        <input type="submit" value="<?php esc_html_e( 'Send', 'trueniu' ); ?>" class="amp-wp-comments-btn">
        <input type="hidden" name="action" value="trueniu_amp_comments_post">
        <input type="hidden" name="comment_post_ID" value="<?php echo get_the_ID(); ?>">
        <input type="hidden" name="comment_parent" value="0">
        <div submit-success>
            <template type="amp-mustache"><?php esc_html_e( 'Send successful!', 'trueniu' ); ?></template>
        </div>
        <div submit-error>
            <template type="amp-mustache"><?php esc_html_e( 'Send failed!', 'trueniu' ); ?></template>
        </div>
    </form>
</div>
```

This is my code.

**Comment by westonruter** [comment]
Have you seen the relevant wiki page? https://github.com/Automattic/amp-wp/wiki/Creating-Forms-That-Submit-POST-Requests

**Comment by shangdev** [comment]
@westonruter 
Yes, I seen it.
And found the relevant sample code here.[code](https://github.com/Automattic/amp-wp/blob/1e2cd22f1bfe8ab9d833c901e02111120f52fe72/includes/class-amp-theme-support.php)

And I noticed that "There's no need to enqueue the required amp-form script, as this plugin will do that when it finds a <form>. The same applies to all AMP components."
Does this mean. Even if I use a custom comments template, he can still automatically introduce the scripts required by amp-form？

**Comment by westonruter** [comment]
@shangdev If you have a template that adds a `<form>` then the `amp-form` component script will automatically be included, yes.

So is there anything else left unexplained now?

**Comment by shangdev** [comment]
@westonruter 
Now I have adds a <form>, But script not automatically be included. I need to add the script manually
Is my template wrong?

**Comment by westonruter** [comment]
Are you using `amp` theme support or the legacy templating?

**Comment by shangdev** [comment]
@westonruter 
I use customize theme, And added the amp folder.

I don't quite understand what amp theme is? And what is the legacy templating?

**Comment by westonruter** [comment]
@shangdev Please read this document: https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support

**Comment by shangdev** [comment]
@westonruter 
I have read it.
But there is still some confusion.
1. How to keep  two versions of URLs for AMP and canonical.
2. When i add add_theme_support(), The template file contained in amp under theme does not work.
as follows:
```
add_action( 'after_setup_theme', function() {
    add_theme_support( 'amp', array(
        'template_dir' => 'amp/',
    ) 
);
```
My theme dir is:
```
theme
- amp
-- single-product.php
-- footer.php
-- header-bar.php
- assets
- inc
404.php
...
```

**Comment by westonruter** [comment]
> How to keep two versions of URLs for AMP and canonical.

When you `add_theme_support( 'amp' )` and you supply a `template_dir` then this will imply the paired mode so you will have AMP-specific URLs that are separate from your non-AMP URLs.

> When i add add_theme_support(), The template file contained in amp under theme does not work.
as follows:

Does not work in what way? What is the content of `single-product.php`? Note that the templates in this `amp` directory should be normal WP templates. There shouldn't be any `$this->load_parts()` anywhere, as that is part of the legacy AMP templating.

**Comment by shangdev** [comment]
@westonruter 
In my opinion, if it is pairing mode or native mode, you must define add_theme_support in function.php.

Currently I have not added add_theme_support in function.php, just create a new amp folder under the theme, and then rewrite some traditional templates inside（header-bar.php,meta-comments-link.php,...）, what is this mode?

This is a template I customized（single-product.php）in amp folder, the post details used to show post type is product:
```
<?php
$this->load_parts( array( 'html-start' ) );
?>

<?php $this->load_parts( array( 'header' ) ); ?>

	<article class="amp-wp-article">
		<header class="amp-wp-article-header">
			<h1 class="amp-wp-title"><?php echo esc_html( $this->get( 'post_title' ) ); ?></h1>
			<?php $this->load_parts( apply_filters( 'amp_post_article_header_meta', array( 'meta-author', 'meta-time' ) ) ); ?>
		</header>

		<?php $this->load_parts( array( 'meta-gallery-image', 'meta-excerpt' ) ); ?>

		<div class="amp-wp-article-content">
            <h2 class="amp-wp-meta-slug"><?php esc_html_e( 'Post content', 'trueniu' ); ?></h2>
			<?php echo $this->get( 'post_amp_content' ); // WPCS: XSS ok. Handled in AMP_Content::transform(). ?>
		</div>

		<footer class="amp-wp-article-footer">
			<?php $this->load_parts( apply_filters( 'amp_post_article_footer_meta', array( 'meta-taxonomy', 'meta-comments-link', 'meta-related-product' ) ) ); ?>
		</footer>
	</article>

<?php $this->load_parts( array( 'footer' ) ); ?>

<?php
$this->load_parts( array( 'html-end' ) );
```
As you can see,I use $this->load_parts(),And can work normally.

So you said "There shouldn't be any $this->load_parts() anywhere, as that is part of the legacy AMP templating.", is it specifically the pairing mode and the native mode?

**Comment by westonruter** [comment]
If you don't do `add_theme_support('amp')` then you are using the legacy paired mode.  If you want to use forms according to the wiki page above, you should add `add_theme_support('amp', array( 'template_dir' => 'amp' ))` to your `functions.php` file.

Otherwise, if you want to use forms with legacy templating you'll need to manually add the `Access-Control-Allow-Source-Origin` header in your admin-ajax handler. This is done automatically when using AMP theme support:

https://github.com/Automattic/amp-wp/blob/e3d036c2db60b215636a2b665414b0e599e9ad97/includes/class-amp-theme-support.php#L887-L891

**Comment by shangdev** [comment]
@westonruter 
Good work!
I enabled the new paired mode.
```
add_theme_support( 'amp', array(
	'template_dir' => './amp/',
) );
```
But it seems that I need to write a new template, how can I quote the old traditional template?
Example:
```
$this->load_parts( array( 'html-start' ) );
```
If not, then how can I introduce the public template part('html-start.php','header.php') in the page, similar '$this->load_parts( array( 'html-start' ) );'

Best wish!

**Comment by westonruter** [comment]
@shangdev That's right, you need to write a new template that uses standard WordPress template functionality. Instead of using `$this->load_parts( array( 'html-start' ) );'` you should use standard PHP like `include __DIR__ . '/html-start.php';` or use `get_template_part(...)`.
