### ISSUE TITLE
AMP Invalid URL post type erroneously makes the slug metabox available

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1282]
When looking at a Invalid AMP Page (URL) post I can see that the Slug metabox is made available:

![image](https://user-images.githubusercontent.com/134745/43176345-128dfe92-8f78-11e8-873a-ae8581e5f0ad.png)

This is wrong. Not only should the metabox not be shown but it also should be immutable, since the slug is a MD5 hash of the underlying URL and changing the slug will break the URL lookup.

The slug metabox should be unregistered in the same way we unregister the status metabox (since we replace it with one of our own).

https://github.com/Automattic/amp-wp/blob/c21f944160d791cb213509e7cfbc2bc40f05b2f1/includes/validation/class-amp-invalid-url-post-type.php#L1019-L1028

This is part of #1006.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

*Steps To Test*
1. Go to [AMP > Invalid Pages](https://paired-ampconfdemo.pantheonsite.io/wp-admin/edit.php?post_type=amp_invalid_url):
<img width="1240" alt="this-submenu" src="https://user-images.githubusercontent.com/4063887/43660335-4dfc0c22-9724-11e8-98c2-799df92ebf74.png">

2. Click one of the URLs:
<img width="1240" alt="click-one" src="https://user-images.githubusercontent.com/4063887/43660371-703a5b9a-9724-11e8-8475-46a472ce9c35.png">

3. Expected: there's no slug metabox, like the one [shown above](https://github.com/Automattic/amp-wp/issues/1282#issue-344269542):
<img width="1132" alt="no-slug-meta-box" src="https://user-images.githubusercontent.com/4063887/43660445-9fd668da-9724-11e8-9375-c5c6d7ab33e7.png">
4. Click "Screen Options"
<img width="1427" alt="no-slug-checkbox" src="https://user-images.githubusercontent.com/4063887/43660673-507da89c-9725-11e8-9935-a86929f91dfa.png">

5. Expected: there's no "Slug" checkbox, as [shown above](https://github.com/Automattic/amp-wp/issues/1282#issue-344269542).

**Comment by csossi** [comment]
nothing happening on clicking "Screen Options" - unable to see checkboxes area, @kienstra
