### ISSUE TITLE
AMP doesn't activate on home page.

### ISSUE THREAD

**Issue by srinathperera101** [Automattic/amp-wp#1285]
When I install the amp-wp I able to activate on all the pages but not in homepage.
my website is www.ecom.services

**Comment by westonruter** [comment]
Did you enable AMP for the homepage specifically?

![image](https://user-images.githubusercontent.com/134745/43231464-5b226bee-9021-11e8-8441-b8fa19034118.png)

**Comment by srinathperera101** [comment]
Hi My homepage doesn't have a page.
it loaded from the theme.

**Comment by westonruter** [comment]
OK, then AMP will not be available for your homepage unless you switch to using [AMP theme support](https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support). In legacy template mode (the standard mode until now), only posts and pages can be served as AMP.

**Comment by shangdev** [comment]
@westonruter 
Hello, I have the same problem.
And I have enable AMP for the homepage specifically.

But the homepage is still not activated.
