### ISSUE TITLE
Invalid CSS stylesheet

### ISSUE THREAD

**Issue by ersanjay1995** [Automattic/amp-wp#1290]
{/*width:166.75px;height:116px;}.amp-wp-inline-74249978fa109897ea98666545f4f931{background-size:cover;background:url('http://13.232.26.89/articles/wp-content/uploads/2018/07/Depression-and-ED.jpg') 50% 50% no-repeat;height:116px;margin-bottom:5px;max-width:100%;max-width:166.75px;}.amp-wp-inline-df628c64772e0888acc62913bda5684c{font-size:13px;font-weight:bold;}.amp-wp-inline-535d42ad641b4c630830fd19d19e544c{background-size:cover;background:url('http://13.232.26.89/articles/wp-content/uploads/2016/12/rsz_shutterstock_160939187.jpg') 50% 50% no-repeat;height:116px;margin-bottom:5px;max-width:100%;max-width:166.75px;}.amp-wp-inline-7b2a6756e2aa5fb6b809f34fb2265a54{background-size:cover;background:url('http://13.232.26.89/articles/wp-content/uploads/2017/03/rsz_shutterstock_416937217.jpg') 50% 50% no-repeat;height:116px;margin-bottom:5px;max-width:100%;max-width:166.75px;}.amp-wp-inline-5dfd9f563c7d1fed7bc770e30baf83c9{background-size:cover;background:url('http://13.232.26.89/articles/wp-content/uploads/2016/05/9553365685_6ec1b6ef3e_z-2.jpg') 50% 50% no-repeat;height:116px;margin-bottom:5px;max-width:100%;max-width:166.75px;}.amp-wp-inline-651279c1bb6060a61aa9bfbf07c362f3{background-size:cover;background:url('http://13.232.26.89/articles/wp-content/uploads/2018/07/heart-specialist.jpg') 50% 50% no-repeat;height:116px;margin-bottom:5px;max-width:100%;max-width:166.75px;}.amp-wp-inline-99ca04549057236a3821f451620f8da9{background-size:cover;background:url('http://13.232.26.89/articles/wp-content/uploads/2018/04/hemoglobin-foods.jpg') 50% 50% no-repeat;height:116px;margin-bottom:5px;max-width:100%;max-width:166.75px;}	</style>

**Comment by ersanjay1995** [comment]
i am not able find where to come this code from 

other internal CSS come from amp/templates/style.php

**Comment by westonruter** [comment]
Please test in 1.0-beta1. It should be fixed there.
