### ISSUE TITLE
AMP validation error is not displaying at the block level in the Gutenberg editor.

### ISSUE THREAD

**Issue by hellofromtonya** [Automattic/amp-wp#1292]
**As a user, I expect AMP validation notices to appear on each block that has an AMP issue.**

- [x] AC1: Identify when and why the block level notices do not appear.
- [x] AC2: Ensure block level validation notices appear on with the block after saving and when the editor is in a clean state.

## What we want

An AMP validation error should display at the block level within the Gutenberg editor to provide the user with more information at a granular level.  

This is the UI notice we want:

![amp-issue-block-level-notification](https://user-images.githubusercontent.com/7284611/43412179-0e2e2b1e-93f2-11e8-87c1-9b47be8457ed.png)

## Noted problems 

There are multiple contributing factors for this issue.  Here is a list:

- [x] Gutenberg update changed filter hook name from `blocks.BlockEdit` to `editor.BlockEdit`.
- [x] Gutenberg update changed the block `uid` property from `id` to `clientId`.
- [x] Block uids go out-of-sync.  Witnessed on page/editor load and intermittently.
- [x]  Duplicated blocks cause all block level notices to disappear.
- [x] The warning notice remains after removing all affected blocks.
- [x] Both the top level and block level notices remain when turning off AMP on a post, i.e. switching the AMP toggle to off.

**Comment by hellofromtonya** [comment]
>`blocks.BlockEdit` filter removed. Please use `editor.BlockEdit` instead.

The filter's hook name changed in [Gutenberg 3.3](https://github.com/WordPress/gutenberg/blob/41fd116ca1f73a9b5c962c66ea0c4aae338ea35e/docs/reference/deprecated.md#330) and is now `editor.BlockEdit`. 

This change impacts this line of code in the `assets/js/amp-block-validation.js` file:

https://github.com/Automattic/amp-wp/blob/6be1d84a07f471de3dc34f18865c0164918f27cf/assets/js/amp-block-validation.js#L45

>All references to a block's `uid` have been replaced with equivalent props and selectors for `clientId`.

The block `uid` changed in [Gutenberg 3.5.0](https://github.com/WordPress/gutenberg/blob/41fd116ca1f73a9b5c962c66ea0c4aae338ea35e/docs/reference/deprecated.md#350) from `.id` to `.clientId`.  This change impacts this line of code:

https://github.com/Automattic/amp-wp/blob/6be1d84a07f471de3dc34f18865c0164918f27cf/assets/js/amp-block-validation.js#L385

Correcting these 2 problems does display the notification on each block during the save/update.

**Comment by hellofromtonya** [comment]
In addition to the above noted issues, there is an intermittent problem of block uids being out of sync.

**Comment by hellofromtonya** [comment]
>Duplicated blocks cause all block level notices to disappear.

When duplicating a block, the block level notices disappear upon save.  

Before duplicating:
<img width="809" alt="screen shot 2018-08-01 at 12 27 54 pm" src="https://user-images.githubusercontent.com/7284611/43545652-16c2ac54-959c-11e8-9e02-fb78d3fe9e53.png">

This is after duplicating and then saving:
<img width="814" alt="screen shot 2018-08-01 at 12 28 28 pm" src="https://user-images.githubusercontent.com/7284611/43545662-1f96a290-959c-11e8-8d20-927c04e99d71.png">

### Root cause

The root cause of this particular issue is the use of `uid` instead of `clientId`.  Gutenberg made a change where `getBlock()` requires the `clientId`.  

https://github.com/Automattic/amp-wp/blob/6be1d84a07f471de3dc34f18865c0164918f27cf/assets/js/amp-block-validation.js#L274-L277

As noted in [Gutenberg 3.5](https://github.com/WordPress/gutenberg/blob/41fd116ca1f73a9b5c962c66ea0c4aae338ea35e/docs/reference/deprecated.md#350), `uid` is being completely replaced by `clientId`.  It's deprecated now. 

[This commit](https://github.com/Automattic/amp-wp/pull/1293/commits/98f0d7049c37e6e996a1e9d42f67c20fe14c7c8f) in PR #1293 fixes the issue as well as replaces all `uid` with `clientId`.

**Comment by kienstra** [comment]
**Moving To "Ready For Merging"**

Based on the code review in #1293 and some testing there, I think this has been tested enough.

If you think this could use more functional testing, feel free to move it back to "Ready For QA."
