### ISSUE TITLE
Add New Post breaks when add_theme_support is used

### ISSUE THREAD

**Issue by loratov** [Automattic/amp-wp#1297]
The add new post url breaks when I add the template directory through the add_theme_support function.  I keep getting a 302 error when I try to visit that page. 

error: [302]: /?p=39735&amp&amp_validate=1&amp_cache_bust=58240603

url : http://localhost:8080/wp/wp-admin/post-new.php

code:
`add_action( 'after_setup_theme', function() {
		add_theme_support( 'amp', array(
	        'template_dir' => 'amp-templates/',
	        'available_callback' => 'is_singular', 
	    ));
     }
);`

**Comment by westonruter** [comment]
Are you using 0.7?

Is your home URL set to http://localhost:8080/ or http://localhost:8080/wp/ ?

**Comment by westonruter** [comment]
And by “breaks” you mean there is an error in the log. The new post screen is still accessible as normal, correct?

**Comment by loratov** [comment]
I'm using 0.7.2

home url:  http://localhost:8080
wp url: http://localhost:8080/wp

The New Post screen is inaccessible - I just get a white screen and then the server stops responding. I'm using the PHP built-in web server and receive the following notifications: 

[
![desktop screenshot](https://user-images.githubusercontent.com/37795755/43505404-801a6c0a-956f-11e8-8b9b-c3a6fdd1ed8f.png)
](url)


It can take a few times upon visiting the page for it to happen. For example, I just tried it and it was successful the first four times or so and then it became inaccessible. 

I tried implementing the function only on the front end of the site and not in the admin and that does seem to resolve the issue. 

`add_action( 'after_setup_theme', function() {
		if (!is_admin()) {
			add_theme_support( 'amp', array(
		        'template_dir' => 'amp-templates/',
		        'available_callback' => 'is_singular', 
		    ));
		}
     }
);
`

**Comment by westonruter** [comment]
Can you edit an existing post and save changes?

**Comment by loratov** [comment]
Yes, editing existing post and saving it has been only.

**Comment by westonruter** [comment]
Well, I created a fix for a related issue in #1301. If you can test the latest `develop` version then you'd be able to confirm if it fixes your issue.
