### ISSUE TITLE
Convert block validation script to a module, and bundle it with block toggle module

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#1298]
AC1. Convert [amp-block-validation.js](https://github.com/Automattic/amp-wp/blob/21ebbc69289ec46a6752df39d2170a625c70faf7/assets/js/amp-block-validation.js) to an [ES6 module](http://exploringjs.com/es6/ch_modules.html)
AC2. Create a new file that will `import` both this module and [amp-block-editor-toggle.js](https://github.com/Automattic/amp-wp/pull/1275/files#diff-f10def20383407dba28e5820c57ba9b1R1) (though that might have since been renamed). This can be similar to [blocks/index.js](https://github.com/Automattic/amp-wp/blob/21ebbc69289ec46a6752df39d2170a625c70faf7/blocks/index.js).
AC3. Add that new file with the `import` statements to [webpack.config.js](https://github.com/Automattic/amp-wp/blob/21ebbc69289ec46a6752df39d2170a625c70faf7/webpack.config.js#L7), so it will be compiled with `npm run dev`
AC4. Ensure that the compiled files have sourcemaps.

This should probably wait for the work on `amp-block-validation.js` in #1293

**Comment by kienstra** [comment]
Hi @postphotos,
If it's alright, I opened this issue with basic ACs. Feel free to edit this if you'd like.

This arose from the work on [https://github.com/Automattic/amp-wp/pull/1275#discussion_r206317004](https://github.com/Automattic/amp-wp/pull/1275#discussion_r206317004).

**Comment by hellofromtonya** [comment]
@kienstra PR #1293 is now merged.  You have a green light to convert the `amp-block-validation.js` script into an E6 module.

**Comment by kienstra** [comment]
Thanks, @hellofromtonya! I'm not sure if I'll work on this issue soon, though.

**Comment by kienstra** [comment]
**Adding Another Script To The Requirements**

Per [this conversation](https://github.com/Automattic/amp-wp/pull/1418#discussion_r218880084), please also convert [amp-invalid-url-post-edit-screen.js](https://github.com/Automattic/amp-wp/blob/bdf411e7e326dfb3069eb8578aee11ab561bed29/assets/js/amp-invalid-url-post-edit-screen.js) to an ES6 module.

**Comment by westonruter** [comment]
I'm going to close this because this will come automatically once we refactor the admin screens to use JS-driven interfaces as opposed to the PHP-driven ones we've largely tried to re-use from what WordPress provides.
