### ISSUE TITLE
AMP carousel doesn't work with RoyalSlider gallery

### ISSUE THREAD

**Issue by leecollings** [Automattic/amp-wp#1300]
I know this involves a third party plugin, but where or what would be causing this issue?

I have a gallery on a page that takes IDs of attachments, and displays them in a RoyalSlider gallery:

```
[gallery royalslider="2" ids="6311,6334,6349,6884,6340,6341"]
```

However this doesn't get converted to an amp-img carousel. 
![bellavou local_gallery__preview_id 3377 preview_nonce b350f27311 _thumbnail_id 6350 preview true amp 1 iphone 6_7_8 plus](https://user-images.githubusercontent.com/6681733/43523469-5d2d6506-9594-11e8-9670-9c2e96cb6736.png)

Removing the "royalslider="2" attribute shows the carousel correctly though. 
![bellavou local_gallery__preview_id 3377 preview_nonce b350f27311 _thumbnail_id 6350 preview true amp 1 iphone 6_7_8 plus 1](https://user-images.githubusercontent.com/6681733/43523486-6f9ceebe-9594-11e8-8fbe-de0738642b0b.png)

I most definitely want to be able to keep the shortcode to a single one, and not have to hack to display this for AMP Versions. Is there anything that can be changed here?

**Comment by westonruter** [comment]
How is RoyalSlider integrating with the `gallery` shortcode? Is it using the `post_gallery` filter? If so, then it could be overriding what the AMP plugin is [doing](https://github.com/Automattic/amp-wp/blob/a15be99b46db50094a812efa85dd9068b0795da5/includes/embeds/class-amp-gallery-embed.php#L19):

https://github.com/Automattic/amp-wp/blob/a15be99b46db50094a812efa85dd9068b0795da5/includes/embeds/class-amp-gallery-embed.php#L142-L165

**Comment by leecollings** [comment]
@dimsemenov

**Comment by westonruter** [comment]
Ideally the AMP plugin's gallery should be deferring to whatever other plugin is powering the gallery. Going forward with [AMP theme support](https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support), the gallery carousel functionality should also be opt-in. In Gutenberg we now expose this option explicitly (though it is broken at the moment per #1303). For `gallery` shortcode, however, the default behavior for carousel is retained for back-compat but only in classic mode.

**Comment by leecollings** [comment]
@westonruter I don't really understand what you're saying, but basically, I'd like AMP to override this rather than RoyalSlider. is there a function/hook/template I can use that will bump the priority from 10 to 60 instead as a resolution that will remain after updating without editing your core code?

**Comment by westonruter** [comment]
What I mean to say is that going forward the AMP version should replicate the non-AMP version as much as possible. If RoyalSlider wants to add special AMP support to use `amp-carousel` then it should do so. The AMP plugin shouldn't be overriding a plugin's customizations without being explicitly allowed to.
