### ISSUE TITLE
Changing settings can result in erroneous notices regarding post types

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1302]
I've found sometimes when switching between template modes or supported templates that I get blasted with error notices regarding post type support, even when I made no changes to the post types:

![image](https://user-images.githubusercontent.com/134745/43535153-0d224d9a-956e-11e8-81c8-4fafcc8f6831.png)

**Comment by westonruter** [comment]
I noticed this again when switching the template mode from Classic to Native/Paired after upgrading a site from 0.7 to 1.0-beta2.

**Comment by hellofromtonya** [comment]
I was able to reproduce the notice blasting conditions when upgrading from 0.7 to 1.0-beta2 but only when the default post type of 'Posts` was selected (none of the others).  Then upon upgrading and switching from Classic to Paired or Native, the notice blasts occurred.  See this GIF for the steps:

![amp-issue-1302](https://user-images.githubusercontent.com/7284611/43970091-fbb46a2c-9c91-11e8-9418-46577e85cdaa.gif)

Why?

When first switching from Classic to Paired or Native, notice that the `Serve all templates as AMP regardless of what is being queried.` , i.e. option `amp-options[all_templates_supported]`, is `on` (checked) by default.

We should revisit what state we want that `all_templates_supported` option to be when first upgraded or installed.  

- If first installed, then it can be set to `on`.
- Else, set it to `off` as the default and use the post types that were previously set in the last version of the plugin.

>I've found sometimes when switching between template modes or supported templates that I get blasted with error notices regarding post type support, even when I made no changes to the post types:

@westonruter Did you happen to notice what which post types were selected?  Was it just the default of `Posts`?

**Comment by kienstra** [comment]
**Moving To 'Ready For Merging'**

If it's alright, I'm moving this to 'Ready For Merging.' It [looks like](https://github.com/Automattic/amp-wp/issues/1302#issuecomment-412910057) reproducing this on the [staging site](https://paired-ampconfdemo.pantheonsite.io) will be complex, though we could create a new site for this if you think it's important.
