### ISSUE TITLE
AMP extensions to Gutenberg blocks are not appearing in sidebar

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1303]
When adding a Gallery, there should be toggles for carousel and lightbox:

![image](https://user-images.githubusercontent.com/134745/43536485-9170f706-9571-11e8-8c57-58233a791b56.png)

The paragraph block should have options for fit-text:

![image](https://user-images.githubusercontent.com/134745/43536538-ab2946d0-9571-11e8-8c50-0b4f62c375e7.png)

The Image block should have `noloading` toggle:

![image](https://user-images.githubusercontent.com/134745/43536593-d14f2a78-9571-11e8-9d41-92577d03d854.png)

And so on. These have been lost for some reason. It may be due to a filter name change in Gutenberg.

**Comment by miina** [comment]
Looking into the issue.

**Comment by miina** [comment]
@westonruter Looks like it was due to filter name change indeed, should be fixed by https://github.com/Automattic/amp-wp/pull/1308.
