### ISSUE TITLE
Every theme returning "file_path_not_found" error for CSS files on Windows

### ISSUE THREAD

**Issue by Stephen-Cronin** [Automattic/amp-wp#1310]
I'm using version 1.0-beta1-024e4507-20180706T154134Z. All themes on my system are returning AMP validation errors like this: 

 ![image](https://user-images.githubusercontent.com/1502350/43580281-3a966dda-9698-11e8-826d-da00e98b5052.png)

I tracked it down to failing the second condition on [line 505](https://github.com/Automattic/amp-wp/blob/develop/includes/sanitizers/class-amp-style-sanitizer.php#L505) of class-amp-style-sanitizer.php: 

`
if ( ! $file_path || false !== strpos( '../', $file_path ) || 0 !== validate_file( $file_path ) || ! file_exists( $file_path ) ) {
`

Maybe it's happening because I'm on Windows? At that point in the plugin's execution `$file_path` has a value of `C:\SJCHD\Dev\!Sites\dev-test/wp-content/themes/twentysixteen/style.css` 

`$file_path` doesn't have '../' in it, like the plugin seems to expect, but it seems like the plugin should be able to find that file.

**Comment by christophherr** [comment]
All external stylesheets are failing. 
`validate_file()` returns 2
`file_exists()` returns 1

**Comment by westonruter** [comment]
Thank you, that is helpful. So the problem is [in `validate_file()`](https://github.com/WordPress/wordpress-develop/blob/49a6596d7e2933b940e4c13a4d4986f5a21f823e/src/wp-includes/functions.php#L4495-L4498):

```php
	// Absolute Windows drive paths are not allowed:
	if (':' == substr( $file, 1, 1 ) )
		return 2;
```

I'm not sure why that condition is in there. @christophherr Would you please try changing `0 !== validate_file( $file_path )` to `1 === validate_file( $file_path )` and testing? In other words:

```diff
--- a/includes/sanitizers/class-amp-style-sanitizer.php
+++ b/includes/sanitizers/class-amp-style-sanitizer.php
@@ -502,7 +502,7 @@ class AMP_Style_Sanitizer extends AMP_Base_Sanitizer {
 			$file_path = ABSPATH . 'wp-admin' . substr( $url, strlen( $admin_url ) - 1 );
 		}
 
-		if ( ! $file_path || false !== strpos( '../', $file_path ) || 0 !== validate_file( $file_path ) || ! file_exists( $file_path ) ) {
+		if ( ! $file_path || false !== strpos( '../', $file_path ) || 1 === validate_file( $file_path ) || ! file_exists( $file_path ) ) {
 			/* translators: %s is file URL */
 			return new WP_Error( 'file_path_not_found', sprintf( __( 'Unable to locate filesystem path for %s.', 'amp' ), $url ) );
 		}
```

**Comment by westonruter** [comment]
@christophherr @Stephen-Cronin I've opened a PR with a fix, iterating on the above. There is a plugin build ZIP linked to in the plugin to facilitate installation and testing: https://github.com/Automattic/amp-wp/pull/1311

**Comment by Stephen-Cronin** [comment]
Thanks @westonruter @christophherr - works for me as well. 

Sorry for the confusion over which condition was the cause (I made an error when logging the results of the condition).
