### ISSUE TITLE
 How to process the comment source page is the amp page?

### ISSUE THREAD

**Issue by shangdev** [Automattic/amp-wp#1323]
Now , When I post a comment on the amp page, He still shows that the source page is non-AMP version.

This is obviously problematic. How to fix it?

**Comment by westonruter** [comment]
I don't understand. What is the URL where the issue can be seen?

Sharing screenshots is helpful.

**Comment by shangdev** [comment]
@westonruter 
The page where the comment occurred is this, it amp page:
https://www.trueniu.com/%E7%BD%91%E7%AB%99%E7%9A%84%E8%AE%BE%E8%AE%A1%E9%A3%8E%E6%A0%BC%E9%83%BD%E6%9C%89%E5%93%AA%E5%87%A0%E7%B1%BB%EF%BC%9F/amp/

But the admin shows that the page where the comment occurred is another:
![image](https://user-images.githubusercontent.com/15621520/43756778-c22cfcd8-9a48-11e8-8df3-8eef982bb031.png)

You can see that he is a non-AMP version of the page.

**Comment by westonruter** [comment]
I see you are using a comment form on the legacy post templates. This isn't officially supported so you must have done some custom coding to do it.

I suggest switching to using [AMP theme support](https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support) and [v1.0-beta2](https://github.com/Automattic/amp-wp/releases/tag/1.0-beta2). Try using the new paired template mode.
