### ISSUE TITLE
The amp page shows a incorrect canonical, 

### ISSUE THREAD

**Issue by shangdev** [Automattic/amp-wp#1340]
This is my link:
https://www.chinajgt.com/jin-gu-town-participated-euro-asia-economic-forum/amp/

This caused the search console to give me an error.

**Comment by GitaStreet** [comment]
Yes, your main site points correctly to AMP version, but AMP version points to itself, but should point to the main site. At least in the case where you have 2 versions. 

Try updating your Yoast SEO. You don't have the latest version. Also you might need this "Glue for Yoast SEO&AMP".

https://da.wordpress.org/plugins/glue-for-yoast-seo-amp/

Personally, it looks like I don't need myself when going for Canonical AMP, so no changes needed.

**Comment by shangdev** [comment]
@GitaStreet 
I have update Yoast SEO and Glue for Yoast SEO&AMP latest version.

But the problem still seems to exist.

**Comment by Naren-hybreeder** [comment]
Hi @shangdev , 

I am also getting the same issue.. I have AMP URL https://example.com/blog/blog1/amp/ and the canonical showing https://example.com/blog/blog1/

Once you added the above code,  is it really working? I have tried but not working for me.
