### ISSUE TITLE
Surface AMP mode types to improve Error Validation workflow

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1353]
**As a user, I should know which mode I'm on in the error listings and whether actions I take will affect the pages on my slte.**

Considered as a sub-task to #1006.

Formal ACs to come.

cc: @jwold

**Comment by jwold** [comment]
<img width="1366" alt="notice flow" src="https://user-images.githubusercontent.com/3411173/44549463-044a7200-a6d6-11e8-847e-c6b3179c321b.png">

**Comment by westonruter** [comment]
This is implemented, no?

In paired mode with auto-sanitization I see:

![image](https://user-images.githubusercontent.com/134745/49539037-9b9c9500-f881-11e8-95b2-962c0f5ae2b3.png)

In paired mode without auto-sanitization I see:

![image](https://user-images.githubusercontent.com/134745/49539094-c25acb80-f881-11e8-8495-684aab3abceb.png)

In native mode I see:

![image](https://user-images.githubusercontent.com/134745/49539050-a8b98400-f881-11e8-8e16-53355629d82c.png)

**Comment by kienstra** [comment]
Good point, @westonruter. #1676 implements this. Thanks for moving this into the `v1.0` milestone.
