### ISSUE TITLE
Hide auto-sanitize option when Native theme support is built-in

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1358]
When theme support is not built-in and the user selects the Native template mode, the auto-sanitize checkbox is hidden since it is forced. However, this isn't currently working when theme support is built-in via `add_theme_support('amp')`:

![image](https://user-images.githubusercontent.com/134745/44664211-6dc4cc00-a9c7-11e8-94c5-d27d6794697a.png)

**Comment by westonruter** [comment]
The problem lies here:

https://github.com/Automattic/amp-wp/blob/0401d5e971aa29c3fc2c9981af41ca51e7d807cf/includes/options/class-amp-options-menu.php#L261-L262

When AMP support is built-in the `jQuery( 'input[type=radio][name="amp-options[theme_support]"]' )` result is empty because there are no template mode radio buttons.

**Comment by kienstra** [comment]
**Moving To 'Ready For Merging'**

If it's alright, I'm moving this to 'Ready For Merging,' as I don't think it needs functional testing. Feel free to move it back.
