### ISSUE TITLE
Generate a error taxonomy for AMP error types

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1360]
As XWP, I should have a list of all the possible errors the AMP for WordPress plugin may generate and I should have them organized in a logical taxonomy (by CSS, by HTML attribute, by HTML element, or by Javascript). As a developer using the plugin, I should be able to use these taxonomies to sort and filter in various given views.

- [ ] AC1: Determine all current errors the sanitizer outputs.
- [ ] AC2: Organize this based on the logical taxonomy (by CSS, by HTML attribute, by HTML element, or by Javascript) discussed.
- [ ] AC3: Share this with the documentation for the new product site.
- [ ] AC4: Prepare this for the other views (index by error and single) where this will be used.

**Comment by kienstra** [comment]
**Question About Taxonomy**

Hi @postphotos,
>I should be able to use these taxonomies to sort and filter in various given views.
It sounds like this means a taxonomy in the WordPress sense.

Is there flexibility in implementing this? The `amp_validation_error` is [a taxonomy itself](https://github.com/Automattic/amp-wp/blob/0401d5e971aa29c3fc2c9981af41ca51e7d807cf/includes/validation/class-amp-validation-error-taxonomy.php#L123).

**Comment by kienstra** [comment]
Hi @postphotos,
Building on the question above, would there be a way to somehow filter by error type on the "AMP Validation Errors" page?

<img width="1289" alt="validation-error-page" src="https://user-images.githubusercontent.com/4063887/44685642-8fe33c00-aa11-11e8-940f-0f67c86e27a1.png">

**Comment by postphotos** [comment]
Hi @kienstra, that's the idea here. This ticket explores and implements the data model to allow the other views to have the features we think they need to help a user work with errors.

As a user, I should be able to get to _just the errors of a given type_ (e.g. CSS or Javascript) to be able to see or action on just that subset of errors on both the URL and Error type screens.

On the single page, [the new view](https://github.com/Automattic/amp-wp/issues/1006#issuecomment-415593089) also groups these errors by this typology, also linking to given documentation about how to best resolve it. For example, some markup attributes and CSS properties are just fine to be omitted in AMP, but I'd be wary of blocking some Javascript tags. In short, we want to use this data elsewhere in the tool and first need to make sure we can parse through (or collect it) as the sanitizer and plugin works.

**Comment by postphotos** [comment]
@kienstra The current default post faceting (` All | New | Rejected | Accepted `) would be replaced with [the new interface's dropdown filters](https://sketch.cloud/s/PoWy8/all/page-1/amp-validation-errors). Currently, 

Notes about the current version of the sketch:
- Bulk Action does not appear there, but we intend to keep that feature. 
- At this point, we intend to have two dropdowns (Error `Types` and Error `Status`) and have backlogged template (#1367) and source (#1368). Search, of course, would still work in filtering the layout views as it does now.

cc: @jwold @jillchu

**Comment by kienstra** [comment]
**Non-CSS Error Codes** (that I could find so far)

`'invalid_element'`
(This code also looks to apply when enqueuing scripts or stylesheets.)
`'invalid_attribute'`


**CSS Parser [Error Codes](https://github.com/Automattic/amp-wp/blob/a6f8eae6185f44aefe5123911335957b22a1793f/includes/sanitizers/class-amp-style-sanitizer.php#L233-L242
)**
`'css_parse_error'`
`'excessive_css'`
`'illegal_css_at_rule'`
`'illegal_css_important'`
`'illegal_css_property'`
`'removed_unused_css_rules'`
`'unrecognized_css'`
`'disallowed_file_extension'`
`'file_path_not_found'`

The error codes, like `invalid_attribute`, are [stored in the term description](https://github.com/Automattic/amp-wp/blob/a6f8eae6185f44aefe5123911335957b22a1793f/includes/validation/class-amp-validation-manager.php#L1525). That description is a JSON blob, like:

<img width="395" alt="code-invalid-attribute" src="https://user-images.githubusercontent.com/4063887/44694640-4821dc00-aa34-11e8-8b7a-38f65a99756e.png">

On the 'AMP Validation Errors' page, `invalid_attribute` and `invalid_element` codes also display the `node_name` after:

<img width="681" alt="invalid-attribute" src="https://user-images.githubusercontent.com/4063887/44694760-165d4500-aa35-11e8-9ab5-113efcbbfc61.png">

That `node_name` also look to be in the JSON blob in the term description.

**Comment by westonruter** [comment]
In regards to data model for a taxonomy of taxonomies, see https://github.com/Automattic/amp-wp/issues/1361#issuecomment-416445491 for a discussion of a possible solution.

Nevertheless, it seems that doing a full-text search of the term `description` field (a JSON blob) is going to be the most practical solution here. This would mean that the error `type` (category) should be stored inside the JSON blob itself with the error `code`, and that to filter by this field it would require doing a query like:

```
WHERE description LIKE '%"type":"css_error"%';
```

This would be in addition to the term status query achieved via `term_group`.

This isn't ideal by any means, but I think it will be OK given that the `type` queries would only be done in the admin for these screens.

**Comment by westonruter** [comment]
An important consequence of this implementation is this: we would not be able to readily limit the dropdown of type options to just those which actually exist in the database. Nor would we readily be able to provide a count of the given error types that exist with each option.

**Comment by kienstra** [comment]
@westonruter, thanks a lot for your detailed suggestion for the data model.

**Comment by postphotos** [comment]
Updated title to more clearly explain the intent of the ticket, props @amedina 👍

**Comment by kienstra** [comment]
**Request To Change Text**

 Hi @johnwatkins0,
Could you please change the text here on the 'Invalid AMP Pages (URLs)' page? The screenshot below has the same changes as the [one above](https://github.com/Automattic/amp-wp/issues/1360#issuecomment-419135995). But it's taken from my local environment, using the `develop` branch:

<img width="977" alt="change-text-develop-branch" src="https://user-images.githubusercontent.com/4063887/45170783-599e7d00-b1c6-11e8-8c09-beb75a3ee5fd.png">

**Comment by kienstra** [comment]
**Moving To 'Read For Merging'**

If it's alright, I'm moving this to 'Ready For Merging,' as this will be tested in #1361 and #1362.
