### ISSUE TITLE
Implement Dropdown Facet filters

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1363]
As an developer using the AMP for WordPress plugin, I should have a way to filter errors on each index listing screen (by URL and by Error). 

_Formal AC to come._

**Comment by kienstra** [comment]
**Filtering On "Errors By URL"**

Based on our discussion this morning, it looks like there [aren't filters anymore](https://sketch.cloud/s/PoWy8/all/page-1/amp-validation-urls-tooltip) on the 'Errors by URL' page (previously called 'Invalid Pages').

PR #1373 now [allows filtering](https://github.com/Automattic/amp-wp/pull/1373#issuecomment-417126016) the 'Errors by URL' page (previously called 'AMP Validation Errors') by accepted status and error type.

**Comment by westonruter** [comment]
> Based on our discussion this morning, it looks like there aren't filters anymore on the 'Errors by URL' page (previously called 'Invalid Pages').

Humm, I think this isn't right. There are currently filters in the plugin for selecting invalid URLs that have errors with a given status. There is also a filter for the date and search:

![image](https://user-images.githubusercontent.com/134745/44830609-5bb97800-abd7-11e8-9e05-52dead277136.png)

I don't think these should go away.

But on this invalid URLs screen (errors by URL) should there be a new dropdown for selecting URLs that have errors of a given type? Note that in addition to storing the error attributes in the term `description`, the full error JSON is also stored in the `post_content` for an `amp_invalid_url` post; so a regular search could be done to find such errors here, without having to worry about doing a `join` on the `description` field for `amp_validation_error` terms.

But should the status links get converted into a dropdown?

![image](https://user-images.githubusercontent.com/134745/44830704-f1550780-abd7-11e8-81e4-97b3aa4884b3.png)

**Comment by kienstra** [comment]
**Add Filter Dropdowns**

Hi @westonruter,
Based on our meeting, there will be 2 filter `<select>` elements added to this 'Errors by URL page.

This page should have the same 'All Statuses' and 'All Error Types' dropdowns that exist on the 'Errors by Type' page:

<img width="1114" alt="add-to-errors-by-url" src="https://user-images.githubusercontent.com/4063887/44860544-11b6ad80-ac3c-11e8-924a-49ab7c4379d2.png">

**Comment by westonruter** [comment]
Fixed by #1373.

**Comment by kienstra** [comment]
**'Moving to 'Ready For Merging'**

If it's alright, I'm moving this to 'Ready For Merging,' as the filters should be tested in #1361 and #1362.
