### ISSUE TITLE
Improved “Error Isolation” view

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1364]
*As a developer using the AMP for WordPress plugin, I should have a way to isolate one error's occurrences across multiple URLs on a site and be able to quickly action to suppress or acknowledge it in a listing page.*

- [x] AC1: Continuing to use the table listing view, incorporate the new design linked below.
  - [x] Remove the "Removed Elements" and "Removed Attributes" and replace it with a "Removed" column that also includes occurrences where any other items that are sanitized (e.g. CSS) would be removed as well.
  - [x] Update the "Sources" design to incorporate better organization of information.
  - [x] Rename the "Date" column to "Last Checked."

- [ ] AC2: Surface the error's information so that I can understand the relevance of this drilldown. Reveal the error name, its actioned status, as well as a reported blob of that error so I can understand what this page means. In that same area, I should have a clear place that links me to official documentation that a) explains the error and b) how to best fix it based on my use case (e.g. what to do when I have excessive CSS, a JS-driven script for a menu, etc.) so I, as a developer, have confidence to action quickly here.

- [x] AC3: In the same area where errors are detailed, give me a clear place to action - tell me what I can do (accept/reject) with this error. 

_Based on the "drilldown" screen from ~[here](https://sketch.cloud/s/PoWy8/all/page-1/amp-validation-errors-isolated-error-by-urls) [here](https://sketch.cloud/s/Vow17/all/page-1/isolated-error)~._
~(From Ryan: it looks like [this](https://sketch.cloud/s/VoDKr/all/page-1/amp-validation-errors-for-amp-test-embeds-new) is the latest design)~ Final design: [ [Page 1](https://sketch.cloud/s/xQRzx/all/page-1/isolated-error) ]

**Comment by postphotos** [comment]
As discussed in today's backlog grooming call, this screen's intention is to

- Give clear details for a single error's occurrences across many URLs
- Give them a way to action on that error (accept, reject, etc.)
- Explain what errors happen, when and why so that developers can confidently understand how to action on a given error.

**Comment by kienstra** [comment]
**In Progress**

I'm working on this now, on [this branch](https://github.com/Automattic/amp-wp/compare/add/1365-single-error-url?expand=1).

**Comment by postphotos** [comment]
Hi @kienstra and @jacobschweitzer - Mocks have been updated here.

**Comment by jacobschweitzer** [comment]
This is ready for a review @westonruter

**Comment by jacobschweitzer** [comment]
The "Learn More" button in the design was not included since there isn't a clear definition of how this will work yet. This is being worked on in #1420 .

**Comment by postphotos** [comment]
@jacobschweitzer - the links to "Learn more" would be linking to the product site's docs when they are ready. 😄

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this [single error page](https://paired-ampconfdemo.pantheonsite.io/wp-admin/edit.php?amp_validation_error=4baa52cb0bc235a9c6944358ea112b31&post_type=amp_invalid_url) against this issue's ACs and the [design](https://sketch.cloud/s/xQRzx/all/page-1/isolated-error)?

This section is expected to be different from the design, though we're still discussing it:

<img width="1093" alt="single-error-page" src="https://user-images.githubusercontent.com/4063887/46044530-a2b86180-c0e0-11e8-9930-c532b5060dbd.png">

Please also test the inline and bulk actions:
<img width="1101" alt="bulk-actions-single-error" src="https://user-images.githubusercontent.com/4063887/46044657-0478cb80-c0e1-11e8-8a51-5efbfcbabacb.png">

**Comment by csossi** [comment]
verified in QA

**Comment by kienstra** [comment]
Thanks, @csossi!
