### ISSUE TITLE
Improved “single error” by URL view

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1365]
**As a developer using the AMP for WordPress plugin, I should have improved organization of errors that occur by error type.**

- [x] AC1: Implement the new design linked below. This sunsets the "accordion" layout and introduces a "table" layout for single URL error listings.
  - [x] Allow errors to be collapsable (and expandable).
  - [x] Incorporate the new "Sources" layout.
  - [x] Incorporate the new "Error Type" column.
  - [x] respect "stale" errors as discussed elsewhere.

- [x] AC2: Incorporate facets by "Error Type" so that a developer could see just errors by Javascript for a given single URL, for example.

- [x] AC3: Also Incorporate search to manipulate which errors are shown in the table listing. Search would appear above the table.

- [x] AC4: Allow for bulk actions to accept, reject and delete errors on a per-error basis.

- [x] AC5: Continue to provide a full stack trace information/error dump in the form of a collapsible blob, as shown on the mockups and currently implemented as of `v1.0-beta2`. 

- [x] AC6: Provide extended "status" information 

Based on the new screen described ~[here](https://github.com/Automattic/amp-wp/issues/1006#issuecomment-415593089) [here](https://sketch.cloud/s/Vow17/all/page-1/amp-validation-errors-for-amp-test-embeds-copy) [here](https://sketch.cloud/s/VoDKr/all/page-1/amp-validation-errors-for-amp-test-embeds-notification-message-on-the-top-right)~ Final Designs: [[ Page 1 ]](https://sketch.cloud/s/xQRzx/all/page-1/amp-validation-errors-for-amp-test-embeds) [[ Page 2 ]](https://sketch.cloud/s/xQRzx/all/page-1/amp-validation-errors-for-amp-test-embeds-1), additional actions and an improved UI will allow a developer to better understand what errors occur on a per-URL basis and how to quickly action to suppress errors if they choose to do so. 

The UI includes organizing the error blocks and provides a link to the appropriate place for the given user to understand how to best action to resolve the error long term, likely using the taxonomic data from #1360 to connect to relevant pages from amproject.org or ampbyexample.com or our documentation.

**Comment by postphotos** [comment]
@jwold @jillchu - I'd also like your thoughts on how to surface @kienstra's [comment here](https://github.com/Automattic/amp-wp/issues/1366#issuecomment-416357416) to benefit this ticket as it hasn't been discussed yet and we shouldn't lose this feature in the new version of single error views.

**Comment by postphotos** [comment]
As discussed in today's backlog grooming call, this screen's intention is to
- give clear details for a single URL 
- Give them a way to action on multiple errors
- Give them a way to stage errors in preview (as currently available to a user in the current version of the plugin)

**Comment by kienstra** [comment]
**In Progress**

I'm working on this (1365) now, on [this branch](https://github.com/Automattic/amp-wp/compare/add/1365-single-error-url?expand=1).

**Comment by kienstra** [comment]
**Question About Latest Designs**

Hi @postphotos,
Are these the [latest](https://sketch.cloud/s/xQRzx/all/page-1/amp-validation-errors-for-amp-test-embeds) [designs](https://sketch.cloud/s/xQRzx/all/page-1/amp-validation-errors-for-amp-test-embeds-1) for the single URL page?

Thanks 😄

**Comment by postphotos** [comment]
Hi @kienstra - yes, and I've updated the story! Missed this ticket. 🥇

**Comment by postphotos** [comment]
@kienstra - per our call today, can you sync with @jillchu @jwold for design QA here?

**Comment by kienstra** [comment]
Sure, @postphotos!

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this single error URL page ([like this](https://native-ampconfdemo.pantheonsite.io/wp-admin/post.php?post=435&action=edit)) against this issue's ACs and the [design](https://sketch.cloud/s/xQRzx/all/page-1/amp-validation-errors-for-amp-test-embeds-1)?

Please use [this staging site](https://native-ampconfdemo.pantheonsite.io/wp-admin/post.php?post=435&action=edit), as it has the latest corrections from PR #1462.

Please see [this screencast](https://drive.google.com/file/d/11Zw1PpiFVpR-B8Q3Bttl0Gu6y-H20aa0/view?usp=sharing) for the expected functionality of this page.

**Comment by csossi** [comment]
Verified in QA

Assumption here is that tooltip positioning is a separate issue logged elsewhere
