### ISSUE TITLE
AMP Mode Notice for Index listings

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1366]
As a user, I should be presented with a notice that reveals what mode of AMP I’m using so I understand what each action does based on the current mode. 

Without this notice, a given user may think actions take effect on their site, but when auto-sanitize mode is turned on (either by force for "Native" mode or optionally for "Paired" mode), 

- [ ] AC1: Surface a given notice based on the mode (from the settings page) in each of the views where actions can occur.
- [ ] AC2: Propose copy (and perhaps a suggestion to turn on Auto Suppression) for Native, Paired (non-auto) and Paired (auto) modes. Also, in Paired Mode (non-auto) offer a dismissable notice to help the user turn this on to enable auto sanitization sitewide.

Notes:
- If a user is in Paired Mode with auto-sanitize or in Native AMP mode, each error is but a notice and does not affect the site.
- If a user is in Paired Mode without auto-sanitize, each action might affect which pages are served as AMP. A given user, by not taking action on errors, would prevent AMP from being served on those pages.
- If a user is in Classic Mode, they should know they won't get the index listings (nor the single listings) as the sanitizer does not run in this mode.

**Comment by kienstra** [comment]
**Question About Notice**

Hi @postphotos,
Thanks for opening this issue. 

Did you have in mind a notice like:
<img width="1298" alt="notice-amp" src="https://user-images.githubusercontent.com/4063887/44683973-6cb68d80-aa0d-11e8-935c-01aeef6d0d15.png">

>c) If a user is in Classic Mode, they should know they won't get the index listings (nor the single listings) as the sanitizer does not run in this mode.
In Classic Mode, the validator UI generally doesn't exist, including that screenshot above.

**Comment by kienstra** [comment]
>AC1: Surface a given notice based on the mode (from the settings page) in each of the views where actions can occur.

Maybe there could also be a notice on the "AMP Validation Errors" page:

<img width="1288" alt="notice-template-mode" src="https://user-images.githubusercontent.com/4063887/44685032-18f97380-aa10-11e8-85c2-f1af11bc78ee.png">

**Comment by postphotos** [comment]
Hi @kienstra, what you described [here](https://github.com/Automattic/amp-wp/issues/1366#issuecomment-416362425) is what we have in mind for the scope of this ticket.

In short, currently a user might "accept" an error in Native AMP mode, but (lo and behold) nothing happens. Between showing an icon (i.e. the AMP lightning bolt logo) next to AMP serving URLs, and limited (perhaps dismissable? @jwold) notices on Index Pages we hope to reduce the confusion on what actions mean for index pages. Instead of the click-and-explore method, we want to give them clear notices for what they should expect. I know @jwold has a sketch that explains the possible states. 

I broke apart AC2 here - We've worked on copy a bit already, but you should be unblocked to start AC1 at your leisure.

**Comment by miina** [comment]
@postphotos To confirm:
1. Would the notice be on all index pages (as of now on the Errors page and on the Invalid Pages both)?
2. Is this the notice that the issue involves:
![screen shot 2018-08-29 at 11 30 21 am](https://user-images.githubusercontent.com/3294597/44775769-18cbb600-ab7f-11e8-9e1a-04f8dd98980a.png)

**Comment by westonruter** [comment]
I don't think it needs to be dismissible, does it?

**Comment by miina** [comment]
True, it doesn't. Removed.

**Comment by postphotos** [comment]
Hi @miina, thanks for this [update](https://github.com/Automattic/amp-wp/issues/1366#issuecomment-416871169). I have no issue with the given wording that's been written, and think this is the intention of this ticket. 👍 Looks good to me!

**Comment by kienstra** [comment]
**Request For Testing**

Hi Claudio, 
Could you please test the notices, like the on the [Invalid URLs page](https://paired-ampconfdemo.pantheonsite.io/wp-admin/edit.php?post_type=amp_invalid_url)?

<img width="1427" alt="amp-notice" src="https://user-images.githubusercontent.com/4063887/45699365-2eaa1680-bb40-11e8-98ab-5c2a752be0ea.png">

**Comment by csossi** [comment]
Notices appearing for Invalid URLS index and Error Index
