### ISSUE TITLE
Form Plugins and AMP for WordPress

### ISSUE THREAD

**Issue by RonaldF** [Automattic/amp-wp#1378]
Are there any known Form Plugins that work with the Official AMP for WordPress Plugin? 

I know there are some add-ons created by the AMP for WP guys that work with their AMP Plugin, but I would rather stick with the Official AMP plugin. 

I know hand-coding an AMP Form isn't too difficult, but when you develop many websites, it would be nice to have a form plugin that we could use to develop them faster. 

Thanks,

Ronald

**Comment by westonruter** [comment]
Jetpack's Contact Forms has been tested to work with the plugin successfully. 

If using Gravity Forms, here's a basic shim to get submissions to work as expected: https://gist.github.com/westonruter/b2554073461707a88057bb86b6b603d6

We're planning to engage with form plugins to improve AMP compatibility, but in the mean time hopefully this gets you started.

**Comment by westonruter** [comment]
I've also confirmed that Contact Form 7 will not work with AMP out of the box. See https://github.com/Automattic/amp-wp/issues/1356#issuecomment-417186962

**Comment by westonruter** [comment]
Here is an extension to the AMP plugin which adds basic support for Contact Form 7: https://gist.github.com/westonruter/3501016b0d44af45d878067b1856e023
