### ISSUE TITLE
Settings callout for "view your site as amp" after initial save

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1399]
**As a user on first activation of the plugin, I should have a clear call-to-action after deciding my AMP settings for my site to view my site as AMP or to debug errors.**

 In current form, a user completes the form on the settings page and is presented with a notice that says `Settings Saved.` - this intends to replace this with new copy and directions. While it's important to notify a user that the tool works as expected, a user also needs a clear throughline from activation of the plugin to engagement with the AMP version of their to understand what the point of this tool is and how it works.

As part of the work in #1006, #1288, #1359 it was clear that a new information design for the settings page was needed. By providing a strong CTA after initial save, a user should engage with the AMP site more readily.

- [ ] AC1: Write copy that encourages a user to engage with the site given the condition. Suggestions : `View the AMP version of your site!` or `View the Classic AMP version of your site. (We strongly recommend upgrading to Paired Mode.)` or `View the Native AMP version of your site.`
- [ ] AC2: Based on the outcomes of #1381, implement the ability to surface a call-to-action that would appear after a user "saves" the settings.
- [ ] AC3: Integrate copy from AC1 into the new CTA feature.

**Comment by westonruter** [comment]
Also, there can actually be a direct line from paired/native to “View site as AMP”. If you are logged-in as an admin, which you would be on this screen, you can access your site with `/?amp_validate` in the URL to see it with AMP enabled, even if you are still in _classic_ paired mode. This gives you the ability to preview your site with your own eyes before you do the switch. You don't even need to look at the validation errors.

**Comment by postphotos** [comment]
Just a heads up, I've updated the initial post to write out out a full user story for this ticket.

**Comment by kienstra** [comment]
**Question About Call To Action**

Hi @postphotos,
Thanks for the detailed ACs here.

>AC2: Based on the outcomes of #1381, implement the ability to surface a call-to-action that would appear after a user "saves" the settings.

Would this call to action be a notice, like before?

<img width="1425" alt="amp-version-site" src="https://user-images.githubusercontent.com/4063887/45315814-f29d0300-b4fa-11e8-8b46-8cf6dfd1ca8e.png">

**Comment by postphotos** [comment]
@kienstra Yep, that's the intent! It'd be leveraging the same space as the "settings saved" screen, but it'd be important to still notify the user that the action was completed.

So with that said, in regard to AC1, I think the language should probably be something like:
- Paired Mode activated! _View your site as AMP now_ or _Review Errors_
- Native Mode activated! _View your site as AMP now_ or _Review Errors_
- Classic Mode activated! _View your site as AMP now_. We recommend upgrading to Native or Paired mode.

Seeking feedback and hoping to iterate here.

**Comment by kienstra** [comment]
**Notice Copy Looks Good**

Hi @postphotos,
That copy for notices looks good. 

The first time someone activates Native or Paired mode, there probably won't be any errors to review. But we could add a condition to only output `'or Review Errors'` when there are errors.

**Comment by postphotos** [comment]
**I think we can have that error.**

@kienstra - I think we'd have that information available to us, if not even more.

I don't quite understand when or how the plugin checks for the initial batch of errors, but I know @westonruter talked about trying to surface the number of errors (or at least the existence of) upon initial activation. (And I'd love clarity there if either of you can help.)

For this notice in particular, I don't want to overwhelm the user, but at least drive them onward through to the error flow and compatibility tool if that should be their next steps.

Thoughts? cc: @westonruter

**Comment by kienstra** [comment]
**Reply Regarding Validation**

Hi @postphotos,
Sorry for the delay in replying.

>...how the plugin checks for the initial batch of errors...

There are only 2 ways I know of that this plugin validates a URL without the user explicitly doing so (like clicking 'Re-validate' in the admin bar or 'Recheck' on the 'Invalid URLs' page):

1. On updating a post:
<img width="1190" alt="clicking-save-draft" src="https://user-images.githubusercontent.com/4063887/45669419-6b512000-baf6-11e8-8d3c-31ee40511d0f.png">

2. [After activating any plugin](https://github.com/Automattic/amp-wp/blob/9444a7578474b3ff29810e44d6eada22851bbed7/includes/validation/class-amp-validation-manager.php#L1656)  other than this, it validates [a post that is eligible for AMP](https://github.com/Automattic/amp-wp/blob/9444a7578474b3ff29810e44d6eada22851bbed7/includes/admin/functions.php#L43):
<img width="1204" alt="plugin-notice-amp" src="https://user-images.githubusercontent.com/4063887/45669677-2b3e6d00-baf7-11e8-9200-f5579ddf7a47.png">

Also, there is a WP-CLI script to test for validity in #1183.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this?

1. Go to the [AMP Settings page](https://paired-ampconfdemo.pantheonsite.io/wp-admin/admin.php?page=amp-options)
2. Change the 'Template Mode.' For example, if it's currently 'Native,' change it to 'Paired'
3. Expected: There's a notice that applies to that mode:

<img width="1427" alt="paired-save-changes" src="https://user-images.githubusercontent.com/4063887/46044152-95e73e00-c0df-11e8-8093-ebaf6964813d.png">

4. Repeat step 2, but change it to 'Native' and 'Classic' modes.
5. Expected: There is a separate message for each. The copy could change, so don't worry too much about that.

**Comment by csossi** [comment]
Verified in QA

**Comment by kienstra** [comment]
Thanks, @csossi!
