### ISSUE TITLE
Minimum PHP version should be increased to 5.3.6

### ISSUE THREAD

**Issue by bobbrodie** [Automattic/amp-wp#1406]
In #891, the minimum PHP version is set to 5.3, however http://php.net/manual/en/domdocument.savehtml.php is not available until 5.3.6. While many people will be running on more recent versions of PHP, there are folks out there that are on versions of 5.3 that are lower than 5.3.6. This causes an issue where the post content will not show on AMP pages.

**Comment by westonruter** [comment]
Good catch. Yes, I see that the `$node` parameter was added in 5.3.6:

![image](https://user-images.githubusercontent.com/134745/45170808-a0d04200-b1b5-11e8-88d9-9a6cc5200bbd.png)

Opening a PR…
