### ISSUE TITLE
Problem with amp-iframe

### ISSUE THREAD

**Issue by prolibre** [Automattic/amp-wp#1410]
Hello,

I have an error in the google console for a few pages because of this piece of code in my html :

`<iframe style="min-height: 400px;" src="https://www.geoportail.gouv.fr/embed/visu.html?c=3.9735668054865076,43.90558192721261&z=15&l0=GEOLOGY.GEOLOGY::EXTERNAL:OGC:EXTERNALWMS(1)&permalink=yes" width="100%" height="auto" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" sandbox="allow-forms allow-scripts allow-same-origin" allowfullscreen="allowfullscreen"></iframe>`

that becomes in my amp page:

`<amp-iframe height="400" frameborder="0" sandbox="allow-forms allow-scripts allow-same-origin" allowfullscreen="" layout="fixed-height"><div placeholder="" class="amp-wp-iframe-placeholder"></div></amp-iframe>`

As the <amp-iframe> does not have a **src** it does not work :-( 

Thank you very much for your work!

Anthony

**Comment by westonruter** [comment]
@prolibre A quick workaround is to replace `,` in your URL with `%2C`.

**Comment by prolibre** [comment]
thanks @westonruter. Have a nive day.
