### ISSUE TITLE
Got so many error on pages "'amp-custom"

### ISSUE THREAD

**Issue by jhimli2015** [Automattic/amp-wp#1412]
The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'. , I was installing AMP for WP , am glue for yost , but still showing this error on 87 pages .

http://prntscr.com/krxezg

CAN ANYONE HELP ME TO SOLVE THIS ERROR

MY SITE MILKIO.CO.NZ

**Comment by westonruter** [comment]
This is question for the support forums: https://wordpress.org/support/plugin/amp

I can see that there is indeed this error when looking at the validator: https://validator.ampproject.org/#url=https%3A%2F%2Fmilkio.co.nz%2Fimposing-ban-vanaspati-ghee%2Famp%2F

You have some plugin code that is adding this:

```html
<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
```

There is also a plugin adding illegal JavaScript being added to the page as well. I suggest trying to deactivate plugins until the above validator URL returns no more errors to pinpoint which plugin(s) are causing the errors.

Aside: using the new native and paired modes in v1.0 will prevent errors like this from reaching Google Search Console.
