### ISSUE TITLE
Translate AMP strings

### ISSUE THREAD

**Issue by aminebenkeroum** [Automattic/amp-wp#1421]
Hey all,

I want to translate "AMP" plugin strings, like "Leave a comment" , "Back to top", "%d hours,minutes,days ago.."

Thanks.

**Comment by westonruter** [comment]
You can provide translations at https://translate.wordpress.org/projects/wp-plugins/amp

**Comment by matthewsuan** [comment]
@westonruter i see multiple arabic translations since last year still in the `waiting` stage. 

how can I help to speed up the publication of these translation files?

Ty

**Comment by westonruter** [comment]
@matthewsuan You could circulate this translation link among Arabic speakers: https://translate.wordpress.org/locale/ar/default/wp-plugins/amp/ 

Or do the same for the other Arabic dialects as well: https://translate.wordpress.org/projects/wp-plugins/amp/
