### ISSUE TITLE
Conditional check on Featured Image isn't happening

### ISSUE THREAD

**Issue by leecollings** [Automattic/amp-wp#1430]
At the start of the featured-image.php template file is a check to see if the featured image exists:

```
$featured_image = $this->get('featured_image');
if(empty($featured_image)) {
    return;
}
```

However, on posts that have no featured image, I'm still seeing the rest of the template file being included, and with no src attribute for the image, resulting in validation errors.

Am I expecting the behaviour to be that if there is no featured image, the file will not load past the `return;` line?

**Comment by leecollings** [comment]
So even if there is no featured image, it's the variable is never `empty` is it?

**Comment by westonruter** [comment]
In your case, yes. But in the code that sets the featured image, it will short-circuit if there is no featured image assigned to the post:

https://github.com/Automattic/amp-wp/blob/680a0dbea226390504e2717d479a27787323129d/includes/templates/class-amp-post-template.php#L337-L341

That should then result in the default value being used for `featured_image`, which is `false`:

https://github.com/Automattic/amp-wp/blob/680a0dbea226390504e2717d479a27787323129d/includes/templates/class-amp-post-template.php#L125

Do you have another theme or plugin that is populating `featured_image` via the `amp_post_template_data` filter?

**Comment by leecollings** [comment]
I've just found this in my functions file, I reckon this could be it perhaps?

```
// Set AMP featured image size 'full-width'
add_filter('amp_post_template_data', function($data, $post) {
    if(has_post_thumbnail($post)) {
        $data['featured_image']['amp_html'] =
        '<amp-img
            width="'.wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'full-width')[1].'"
            height="'.wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'full-width')[2].'"
            src="'.wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'full-width')[0].'"
            class="attachment-large size-large wp-post-image amp-wp-enforced-sizes"
            srcset="'.wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'full-width')[0].'"
            layout="intrinsic"
        ></amp-img>';
    }
    return $data;
}, 10, 2 );
```

**Comment by westonruter** [comment]
Try removing it to see if it is the culprit.
