### ISSUE TITLE
amp_post_template_dir using directory inside theme

### ISSUE THREAD

**Issue by anteksiler** [Automattic/amp-wp#1431]
When I pass a directory inside the theme folder, I get an error:
`return get_stylesheet_directory_uri() . '/inc/framework/thb-amp/amp';`

The error is:
`Notice: AMP_Post_Template::verify_and_include was called incorrectly. Path validation for template (...inc/framework/thb-amp/amp/single.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in /localhost/wordpress-goodlife/wp-includes/functions.php on line 4161`

**Comment by westonruter** [comment]
> When I pass a directory inside the theme folder

Please show all the surrounding code.

**Comment by anteksiler** [comment]
Here you go:
`add_filter( 'amp_post_template_dir', 'thb_custom_amp_templates' );
function thb_custom_amp_templates() {
	return get_stylesheet_directory_uri() . '/inc/framework/thb-amp/amp';
}

add_action( 'amp_post_template_head', 'thb_amp_scripts' );`

**Comment by westonruter** [comment]
Here is where the notice is being raised:

https://github.com/Automattic/amp-wp/blob/680a0dbea226390504e2717d479a27787323129d/includes/templates/class-amp-post-template.php#L437-L442

And the `is_valid_template` method itself:

https://github.com/Automattic/amp-wp/blob/680a0dbea226390504e2717d479a27787323129d/includes/templates/class-amp-post-template.php#L459-L479

**Comment by westonruter** [comment]
The problem is that you are using `get_stylesheet_directory_uri()` when you should be using `get_stylesheet_directory()`

**Comment by anteksiler** [comment]
I tried that, but it also returns the same error.

**Comment by anteksiler** [comment]
Just FYI, I do not actually have single.php on that folder, only the ones I would like to override such as header.php and header-bar.php

**Comment by westonruter** [comment]
You should probably use the `amp_post_template_file` filter instead then.
