### ISSUE TITLE
Anyone start getting error 500 on version  0.7.2 since 08/21/2018?

### ISSUE THREAD

**Issue by mauricionr** [Automattic/amp-wp#1432]
I don't know if this is the right place, but since 08/21/2018 the amp pages start getting a lot of errors 500.

Anyone using this plugin is having the same issue?

Thanks

**Comment by westonruter** [comment]
Please share any errors from your PHP error log.

**Comment by westonruter** [comment]
Or try turning on `WP_DEBUG`.

**Comment by westonruter** [comment]
@mauricionr see https://wordpress.org/support/topic/the-latest-amp-plugin-cause-500-error/#post-10252204

> It’s not really a problem with the AMP plugin. Use this fix in the mean time: https://wordpress.org/support/topic/the-latest-amp-plugin-cause-500-error/#post-10247921

Make sure you have the latest version of the AMP Yoast Glue plugin.

**Comment by mauricionr** [comment]
Thanks
