### ISSUE TITLE
Warning: Use of undefined constant INTL_IDNA_VARIANT_UTS46

### ISSUE THREAD

**Issue by kraftbj** [Automattic/amp-wp#1439]
```
( ! ) Warning: Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed
'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP) in
/home/public_html/wp-content/plugins/amp/includes/class-amp-http.php on line 205
```

From looking online, this may be due to a really old version of ICU running on the machine, but something that we may want to account for?

**Comment by westonruter** [comment]
Thank you. The relevant code is:

https://github.com/Automattic/amp-wp/blob/64cad605ee112175f2144df2518ca5a4f11cdfbb/includes/class-amp-http.php#L203-L209

So it seems what we should do is:

```diff
- if ( version_compare( PHP_VERSION, '5.4', '>=' ) ) { 
+ if ( version_compare( PHP_VERSION, '5.4', '>=' ) && defined( 'INTL_IDNA_VARIANT_UTS46' ) ) { 
```

**Comment by kraftbj** [comment]
I'll PR that after testing.

In the meantime, I confirmed that `INTL_IDNA_VARIANT_UTS46` was shipped in http://site.icu-project.org/download/46 ICU 4.6 back in ~2010/2011, but while this particular machine has PHP 7.2.9 installed, ICU is 4.2.1.
