### ISSUE TITLE
How to disable amp option for all the content types and templates using version 0.7.2 via PHP code

### ISSUE THREAD

**Issue by bilal-pp** [Automattic/amp-wp#1445]
Hi,

We are trying to implement AMP on some pages of our website so we are using this plugin.

After installing and activating the plugin and navigating to the AMP >> General option in the WordPress admin dashboard, we have checkboxes next to post types including the custom post types as well. Selecting only the post types we need and after saving the options and after enabling AMP option only on the pages that we need that is by going into pages and editing them and enabling AMP settings in the publisher settings metabox and saving the changes, on the front-end the page picks up the plugin's default theme and not our wordpress theme.

Second method we tried was the PHP code method (after reading the wiki page of this plugin). We added the theme support code as the following:

add_theme_support( 'amp', array(
        'paired' => true,
        'templates_supported' => array(
              'is_singular' => true,
         ),
) );

But this enables AMP on all the post types and templates. I also tried adding the following code but no luck:

add_filter( 'amp_post_status_default_enabled', function( $default, $post ) {

        $default = false;
        return $default;
	
}, 10, 2 );

What my requirement is, I want to use AMP on some of my pages and one custom post type called offers (on certain posts under offers) and also on the singular pages of posts that belong to offers content type and have AMP option enabled for them in the CMS. And on the front-end the output should be rendered using my WordPress theme (only on those pages which have AMP option enabled for them in the CMS) and not the plugin's default theme. Is this possible.

And suppose if I enable amp on all the pages and post types, for the desktop version I checked the pages where not rendering properly (doesn't look same as the original Non-AMP version). Will this plugin affect both the desktop and mobile version.

Thanks,
Bilal Ahmed

**Comment by westonruter** [comment]
I see you just posted this to the forums as well: https://wordpress.org/support/topic/how-to-disable-amp-option-for-all-the-content-types-and-templates-using-version/

Closing this as a duplicate.
