### ISSUE TITLE
Add filters for metadata :)

### ISSUE THREAD

**Issue by jdevalk** [Automattic/amp-wp#145]
I'd like to have filters for:

- the canonical
- the title
- the JSON output
- the Publisher name
- the Publisher logo

So we can override with values from our Yoast SEO settings. Right now we run into cases where the canonical specified on the AMP page is not the canonical specified on the page that AMP specifies as canonical. 

Also, we output similar JSON+LD publisher info on normal pages, but use other images, because they're set in our settings, I'd like to make sure we can use the same images on AMP pages.

**Comment by j3j5** [comment]
I agree, that filter would be really useful.

**Comment by mjangda** [comment]
We already have [`amp_post_template_data`](https://github.com/Automattic/amp-wp/blob/53ba1ee4f3c0a71a84c8523f79ac60825e758668/includes/class-amp-post-template.php#L50) which lets you do this. Alternatively, core hooks (like `post_permalink`) will also work. 

We used to have more granular filters but removed a bunch during the template refactor. Will probably add back a few of them like for the schema.org metadata (just to make it easier to access).
