### ISSUE TITLE
Add a way to specify a non-square publisher logo for schema.org markup (publisher.logo)

### ISSUE THREAD

**Issue by rudygalfi** [Automattic/amp-wp#147]
The Google markup spec (https://developers.google.com/structured-data/rich-snippets/articles) requires this.

**Comment by mjangda** [comment]
Added some docs for this as it can be done at a code-level. Will keep it open to consider adding as a setting.

**Comment by petrchutny** [comment]
How can I add a fixed URL to my logo @mjangda? I feel like your plugin generates the AMP Code, so I can't really inject stuff into it easily.
P.S.: I am not much of a programmer.

**Comment by westonruter** [comment]
Closing in favor of using Custom Logo introduced in WordPress 4.5. See #975.
