### ISSUE TITLE
 Path validation for template (...) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. 

### ISSUE THREAD

**Issue by tamilforce** [Automattic/amp-wp#149]
After the update, I am getting the following error and it's not loading the content:

Notice: AMP_Post_Template::verify_and_include was called incorrectly. Path validation for template (C:\xampp\htdocs\testwp\wp-content\plugins\amp/templates/single.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in C:\xampp\htdocs\testwp\wp-includes\functions.php on line 3792

**Comment by mjangda** [comment]
What is your `WP_CONTENT_DIR` value set to?

**Comment by tamilforce** [comment]
I guess it's just the issue on the WAMP setting. The forward slashes and the backward slashes are causing the issue in the function `is_valid_template( $template )`. I simply did a return true immdiately in that function and it worked.

Single Template: "C:\xampp\htdocs\testwp\wp-content\plugins\amp/templates/single.php" WP_CONTENT_DIR  => "C:\xampp\htdocs\testwp/wp-content"

**Comment by mjangda** [comment]
Ah, okay. We should probably improve the check to handle cases like this.

**Comment by j3j5** [comment]
Probably using `DIRECTORY_SEPARATOR` instead of `/` on the paths would fix it.

**Comment by LiamMcArthur** [comment]
This error seems to be back in 0.4.2.

**Comment by IvanPr** [comment]
All the AMP pages have the following error in the <style amp-custom>:

Notice: AMP_Post_Template::verify_and_include was called incorrectly. Path validation for template () failed. Path cannot traverse and must be located in WP_CONTENT_DIR.
Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in ..../public_html/blog/wp-includes/functions.php on line 4139

**Comment by LiamMcArthur** [comment]
I'm getting the following:

`Incorrect Use of AMP_Post_Template::verify_and_include() Used in wp-includes/functions.php on line 4117. Path validation for template () failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. This message was added in version 0.1.`

**Comment by mcdtech** [comment]
I'm getting the same.  Not sure why this changed, but latest updates have broken AMP for me

**Comment by IvanPr** [comment]
I had started to update the AMPforWP plugins on my Staging servers first and then migrate it to the Live copy only - there are too many bugs in every new update :(
