### ISSUE TITLE
Create new analytics migration document

### ISSUE THREAD

**Issue by davisshaver** [Automattic/amp-wp#1498]
In the existing docs, users are recommend to filter `config_data`, but it looks like actually `config` is checked the custom key values.

Doc: https://github.com/Automattic/amp-wp/wiki/Analytics
Code: https://github.com/Automattic/amp-wp/blob/1.0/includes/amp-helper-functions.php#L568

Another issue is that the filter docs will result in the custom key-values being PHP array, but the filter still runs `json_decode`. A potential patch might be something like, `'config_data' => is_array( $entry['config'] ) ? $entry['config'] : json_decode( $entry['config'] )`.

**Comment by davisshaver** [comment]
https://github.com/Automattic/amp-wp/pull/1499
https://github.com/Automattic/amp-wp/pull/1500

**Comment by westonruter** [comment]
Can you please elaborate on the problem that you're facing? In particular, please share code that you are using which is not working as expected.

**Comment by davisshaver** [comment]
I _think_ I see what’s going on now, could you review https://github.com/Automattic/amp-wp/pull/1499#issuecomment-428385899 and if you agree I can flesh out the docs part?

**Comment by kienstra** [comment]
**Question About Filter**

Hi @davisshaver,
Thanks for bringing this up. You made a [good point](https://github.com/Automattic/amp-wp/pull/1500#discussion_r223864705):

>...that they could use a new section on filtering for native themes?

Like you mentioned, the [Analytics wiki page](https://github.com/Automattic/amp-wp/wiki/Analytics#manually) only documents [an analytics filter](https://github.com/Automattic/amp-wp/blob/469e99213d58d2af83915ca5924657648365bde7/includes/admin/functions.php#L161) for Classic mode (legacy templating).

Would it satisfy this issue and its PRs for me to update the [Analytics wiki page](https://github.com/Automattic/amp-wp/wiki/Analytics#manually) with a section on [how to filter](https://github.com/Automattic/amp-wp/blob/469e99213d58d2af83915ca5924657648365bde7/includes/amp-helper-functions.php#L558) analytics when there's theme support (Native and Paired mode)?

<img width="1058" alt="analytics-wiki-page-manually" src="https://user-images.githubusercontent.com/4063887/48172906-2dd36c80-e2c7-11e8-96dd-eb72f4a4f3ac.png">

Thanks, Davis! It was good to meet you in Chicago at the WordCamp.

**Comment by davisshaver** [comment]
Thanks @kienstra! That sounds good to me, glad to help with the docs update.

**Comment by kienstra** [comment]
**Document To Collaborate On The Wiki**

Hi @davisshaver,
Here's the beginning of a [document for wiki](https://docs.google.com/document/d/1YVZ7_OD3WG_QHJX5585Z7XaIZC6QKdnE3Nx_DXnF9NQ/edit?usp=sharing). It's in a Google Doc so we can collaborate on it better, as the [GitHub wiki pages](https://github.com/Automattic/amp-wp/wiki) don't lend themselves to collaborating very much.

Feel free to suggest any text, or make any comment.

Thanks, Davis!

**Comment by davisshaver** [comment]
@kienstra Thanks so much for including me. I added a few clarifications to the Google Doc, namely that a plugin developer will want to use both filters to ensure that all modes of AMP-WP are supported.

I am using the Parsely plugin as the example for my own tests. Here's the PR I've made adding Native/Paired support to that plugin. https://github.com/Parsely/wp-parsely/pull/116

**Comment by kienstra** [comment]
**Going To Copy Document Into Wiki**

Hi @westonruter,
If it's alright, I'm going to copy the [document](https://docs.google.com/document/d/1YVZ7_OD3WG_QHJX5585Z7XaIZC6QKdnE3Nx_DXnF9NQ/edit?usp=sharing) that @davisshaver and I have been working on into the bottom of the [Analytics wiki page](https://github.com/Automattic/amp-wp/wiki/Analytics).

Also, I'll clarify that the [wiki documentation](https://github.com/Automattic/amp-wp/wiki/Analytics#manually) for `amp_post_template_analytics` is only for 'Classic' mode (legacy templating).

**Comment by kienstra** [comment]
**Thanks, Copied Document Into Wiki**

Hi @davisshaver,
Thanks for your work on the [document](https://docs.google.com/document/d/1YVZ7_OD3WG_QHJX5585Z7XaIZC6QKdnE3Nx_DXnF9NQ/edit?usp=sharing). It's now copied in the [Analytics wiki page](https://github.com/Automattic/amp-wp/wiki/Analytics#filtering-analytics-data-in-native-and-paired-mode).

Also, I [added some sentences](https://github.com/Automattic/amp-wp/wiki/Analytics#manually) in the `amp_post_template_analytics` filter section showing that it should only be used for 'Classic' mode:

>In 'Classic' template mode, you can use the amp_post_template_analytics filter. This template mode is set either from selecting 'Classic' in 'AMP Settings' > 'Template Mode,' or from not calling add_theme_support( 'amp' ).

>See the section below if you're using 'Native' or 'Paired' mode.



How does that look?

**Comment by davisshaver** [comment]
Looks good to me 👍

**Comment by kienstra** [comment]
Thanks, @davisshaver! I'm closing this issue now if that's alright.
