### ISSUE TITLE
Jetpack support for wpcom file

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#15]
Need to remove PHP 5.3-isms like anonymous functions.

Need to also test against Jetpack :)

**Comment by kraftbj** [comment]
Need to `remove_filter` for likes, sharedaddy, and related posts.
Untested on if using this for `remove_filter` works, but function/priority for the add_filters
`array( 'Jetpack_Likes', 'post_likes' ), 30`
`'sharing_display`, 19`
`array( 'Jetpack_RelatedPosts', 'filter_add_target_to_dom' ), 40 )`
