### ISSUE TITLE
How can i add amp-sidebar?

### ISSUE THREAD

**Issue by itsmeevg** [Automattic/amp-wp#1501]
Plugin version 1.0-RC1
Wordpress version 4.9.8
Hello.
How can i add amp-sidebar? Or convert to amp sidebar existing tag?

When I manually add the amp sidebar, I get an error
![image](https://user-images.githubusercontent.com/7571432/46716645-90582f00-cc6d-11e8-8fc2-a471f209f4b9.png)
![image](https://user-images.githubusercontent.com/7571432/46716657-9b12c400-cc6d-11e8-93f1-9f7dc6690b74.png)

**Comment by westonruter** [comment]
@itsmeevg The `amp-sidebar` element must be a direct child of the `body` element (not `header`), as was coincidentally just noted in https://github.com/Automattic/amp-wp/issues/736#issuecomment-428499146
