### ISSUE TITLE
Cannot render AMP version of pages 

### ISSUE THREAD

**Issue by envintus** [Automattic/amp-wp#1506]
I'm using 1.0-RC1 and have AMP configured to run in Classic mode and have my custom templates setup in `my-theme-dir/amp`. Posts, Pages, and a Custom Post Type, `job_site`, I've created are selected to be AMPlified using the plugin.

I have the following AMP template files under `my-theme-dir/amp`:
- front-page.php
- page.php
- single.php
- single-job_site.php (custom post type)

AMPplified version of posts and the custom post type of `job_site` render just fine by appending `/amp/` to their respective URLs. However, pages do not. When I append `/amp/` to the end of a page URL it 404's and when I then attempt to append `?amp` to the URL it just loads the non-AMPlified version of that page.

For each page I do set the canonical amphtml URI using the following code in my `functions.php` file:

```
function pages_amphtml() {
    if (is_page()) {
        $permalink = rtrim(get_permalink(), '/');
        printf('<link rel="amphtml" href="%s?amp">', $permalink);
    }
}
add_action('wp_head', 'pages_amphtml');
```

It's currently set to render a canonical amphtml URI using `?amp`. I have also tried setting it with `/amp/` in hopes that would correct my issue and pages would be rendered AMPlified.

Could someone help me understand where I'm going wrong here? I thought in the latest release of the plugin it was as simple as selecting the post types you want AMPlified and customizing templates based on what mode you are running AMP in.

**Comment by westonruter** [comment]
> For each page I do set the canonical amphtml URI using the following code in my `functions.php` file:

You shouldn't be doing this. The plugin will add this automatically when there is an AMP version of the post/page available.

> Could someone help me understand where I'm going wrong here? I thought in the latest release of the plugin it was as simple as selecting the post types you want AMPlified and customizing templates based on what mode you are running AMP in.

Did you enable post type support for Pages in the AMP settings screen? If you have a custom page template assigned to a page, you'll also need to explicitly opt-in to enabling AMP on each page via this toggle in the publish metabox:

![image](https://user-images.githubusercontent.com/134745/46883054-908b3280-ce05-11e8-9efe-1ce7eb51394c.png)
