### ISSUE TITLE
Updates to Readme for v1.0

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1509]
**As a potential user of the AMP for WordPress plugin, I should have an experience that accurately reflects the features of the tools available to me.**

_Rationale: Since so much has changed since 0.7 (including the spiritual death of the blue bar) we should give this some attention. Note that this readme powers the w.org/plugins/ page for our plugin._ 

- [ ] AC1: Update copy to reflect new features
- [ ] AC2: Update graphic to reflect new tooling

cc: @kienstra @jwold

**Comment by amedina** [comment]
This is an important part of the release. We should have a Readme that is much more readable than the current one. Let's define a good structure and update the content properly.

**Comment by kienstra** [comment]
Thanks for adding this, an update to the `readme` is definitely needed.

**Comment by kienstra** [comment]
**In Progress**

With WIP PR #1561, I'm moving this to 'In Progress.'

**Comment by kienstra** [comment]
Closing this, as #1662 handles this issue's requirements.
