### ISSUE TITLE
Remove schema.org data

### ISSUE THREAD

**Issue by BRoz** [Automattic/amp-wp#1510]
I need to remove all schema.org json data added to my AMP pages, how do i achieve this?

I've tried using functions.php and this:

```
add_filter( 'amp_post_template_metadata', 'amp_remove_json_metadata', 10, 2 );
function amp_remove_json_metadata( $metadata, $post ) {
    remove_action( 'amp_post_template_metadata', 'amp_get_schemaorg_metadata' ); 
}
```
But it doesn't work as expected.

**Comment by westonruter** [comment]
Why do you need to remove it?

**Comment by BRoz** [comment]
> Why do you need to remove it?

I want to implement my own custom data.

**Comment by westonruter** [comment]
Why don't you just add a `amp_post_template_metadata` filter that overrides the default data?

**Comment by BRoz** [comment]
I'd rather remove them before, and integrating my own script into the head of the amp template.

**Comment by westonruter** [comment]
That is not advisable because other themes/plugins may want to augment the Schema.org metadata, and if they can't use the filter then there is no central way to do so.
