### ISSUE TITLE
Use the_author function to retrieve post_author

### ISSUE THREAD

**Issue by mahnunchik** [Automattic/amp-wp#1516]
Hi,

It would be more compatible to use `the_author` function to retrieve `post_author`. Source: https://github.com/Automattic/amp-wp/blob/develop/includes/templates/class-amp-post-template.php#L268

In current implementation I could't override it globally (like in example: https://wordpress.stackexchange.com/questions/158056/change-author-name-to-sitename-on-frontend)

**Comment by westonruter** [comment]
If you switch to using the new paired/native modes in v1.0 (see [RC1](https://make.xwp.co/2018/10/06/amp-plugin-release-v1-0-rc1/?amp)) then you'll be able to re-use the same techniques as you normally do when writing theme templates, like using `the_author()`.

The other alternative is to just override the `meta-author.php` template in your theme: https://github.com/Automattic/amp-wp/blob/develop/templates/meta-author.php
