### ISSUE TITLE
Use the_author function to retrieve post_author

### ISSUE THREAD

**Issue by mahnunchik** [Automattic/amp-wp#1517]
It would be more compatible to use `the_author` function to retrieve `post_author`. Source: https://github.com/Automattic/amp-wp/blob/develop/includes/templates/class-amp-post-template.php#L268

In current implementation I could't override it globally (like in example: https://wordpress.stackexchange.com/questions/158056/change-author-name-to-sitename-on-frontend)

**Comment by westonruter** [comment]
Duplicate of #1516.
