### ISSUE TITLE
gravity forms on 1.0-beta4-built branch

### ISSUE THREAD

**Issue by nodakjones** [Automattic/amp-wp#1521]
I've downloaded the 1.0-beta4-built branch and I'm using a new install of Wordpress (v 4.9.8) with the 2017 theme and the amp plugin and the gravity forms plugin (v2.3.5).  I'm running amp in paired mode and I have the following shim in place in my functions.php:

```php
// Shim support for Gravity Form submissions on AMP pages.
add_action( 'gform_post_submission', function() {
	$location = null;
	foreach ( headers_list() as $header ) {
		if ( preg_match( '/^Location:\s*(.+)/i', $header, $matches ) ) {
			$location = $matches[1];
			break;
		}
	}

	if ( $location ) {
		header_remove( 'Location' );
		header( "AMP-Redirect-To: $location" );
		header( 'AMP-Access-Control-Allow-Source-Origin: ' . home_url() );
		header( 'Access-Control-Expose-Headers: AMP-Redirect-To, AMP-Access-Control-Allow-Source-Origin' );
		exit;
	}
} );

// Use client-side validation UI instead of showing validation errors after page reload. Props Rahul Bansal at rtCamp.
add_filter( 'gform_field_content', function( $content, $field ) {
	if ( $field->isRequired ) {
		return str_replace( 'aria-required=', 'required=', $content );
	}
	return $content;
}, 10, 2 );
```

I have a simple test gravity form with two fields: name and email.  They are both just text fields.  I have the form inserted on a page with the short code not using Ajax.   When I submit a form I get the following error in safari:

>  Failed to parse response JSON: SyntaxError: The string did not match the expected pattern.

In chrome it is a similar error:

> log.js:187 Failed to parse response JSON: SyntaxError: Unexpected token < in JSON at position 0

I actually get this error with the Shim and without the shim.  I've tried multiple themes and I'm still getting the same error.

Strangely I even tried contact form 7 (and disabled gravity forms) and I'm getting the exact same error.

**Comment by westonruter** [comment]
In your network console in DevTools look at the response body of the XHR request. I bet there is a PHP warning that is getting output.

**Comment by nodakjones** [comment]
Good thought, but I’m not seeing any php errors or warnings:  https://pastebin.com/FhUbvKmv



Eric C Jones

Managing Partner
Data Imagery
data-imagery.com
eric@data-imagery.com 
253-461-1110




On October 22, 2018 at 5:33:27 PM, Weston Ruter (notifications@github.com) wrote:

In your network console in DevTools look at the response body of the XHR request. I bet there is a PHP warning that is getting output.

**Comment by westonruter** [comment]
Ok. Well, it is returning a full HTML document to clearly the `gform_post_submission` action is not getting triggered. Perhaps there is some server-side form validation that is failing. You should make sure that all validation is done client-side as well to make sure that invalid forms don't get submitted. Otherwise, if it isn't this, then you'll have to find why that action isn't getting triggered and/or why the `Location` header isn't set. Make sure you have it set to redirect to another page when GF accepts a submission.

**Comment by nodakjones** [comment]
I had set the gf form to redirect, but I must have had the URL incorrect.  I entered an https url and things work perfectly now.  Thanks!

On October 22, 2018 at 7:48:11 PM, Weston Ruter (notifications@github.com) wrote:

Ok. Well, it is returning a full HTML document to clearly the gform_post_submission action is not getting triggered. Perhaps there is some server-side form validation that is failing. You should make sure that all validation is done client-side as well to make sure that invalid forms don't get submitted. Otherwise, if it isn't this, then you'll have to find why that action isn't getting triggered and/or why the Location header isn't set. Make sure you have it set to redirect to another page when GF accepts a submission.

**Comment by pradeep910** [comment]
@nodakjones 

If you want to make the gform ajaxified. 
Here is the gist - https://gist.github.com/pradeep910/b25525034289ab0bc2b7fa0896f4ac90

Hope this helps you.

**Comment by westonruter** [comment]
> Strangely I even tried contact form 7 (and disabled gravity forms) and I'm getting the exact same error.

Here is an extension to the AMP plugin which adds basic support for Contact Form 7: https://gist.github.com/westonruter/3501016b0d44af45d878067b1856e023
