### ISSUE TITLE
Update the border in the AMP Story interface to be more apparent for pages

### ISSUE THREAD

**Issue by alcurrie** [Automattic/amp-wp#1522]
As an editor creating an AMP story, I'd like there to be a more apparent border for pages in the AMP Stories editor
- [ ] AC: Make border more apparent for pages - https://d.pr/i/j9e2Nq
     Design for updated border around the active AMP Story page is shown in this mockup: https://cl.ly/fc36d7797fbb

**Comment by alcurrie** [comment]
@jwold  though this task design change, this doesn't seem like this needs design UX feedback as the screenshot in the AC is fairly straightforward, though it may make sense to include it in the overall look at design/UX changes needed.

**Comment by jwold** [comment]
This has been discussed in https://github.com/Automattic/amp-wp/issues/1564, proposing what the border should look like. Feeling pretty good with where we've landed.

**Comment by alcurrie** [comment]
@mehigh  - for additional clarification I've updated the AC to show the reference to border, but as @jwold notes this is also shown in the latest designs discussed/posted in #1564

**Comment by mehigh** [comment]
The colors have been updated and now the page looks like this: http://cloud.urldocs.com/26f832e554cd
Closing as it was merged this along the fixes for 1524
Moving it on to QA.

**Comment by alcurrie** [comment]
Confirmed: https://cl.ly/8da2559e0382
