### ISSUE TITLE
Blocks > Remove “AMP Story” prefix from the block names since they are only made available when editing an AMP Story post in the first place.

### ISSUE THREAD

**Issue by alcurrie** [Automattic/amp-wp#1525]
As an author/editor building an AMP story, I don't need to see the “AMP Story” prefix in the block names, since I already know that I'm creating an AMP story. 
- [ ] AC1: Remove “AMP Story” prefix from the block names 
![removeampstoriesfromlabels](https://user-images.githubusercontent.com/18579988/47395785-1ce70080-d6f6-11e8-968c-f6d9b6b33db1.jpg)
-  applies to both the labeling when the user adds a new block but also to the display of the block name in the AMP Stories Layers interface.

**Comment by alcurrie** [comment]
@jwold - this is an interface change and so should be included in the overall interface change, but I don't think it requires UX feedback. Does that sound right to you?

**Comment by jacobschweitzer** [comment]
Here is the PR for this change - https://github.com/Automattic/amp-wp/pull/1595

**Comment by miina** [comment]
Fixed within #1595.

**Comment by alcurrie** [comment]
Confirmed working: https://cl.ly/6bd54fac3ae9
