### ISSUE TITLE
Plug in is installed but not active

### ISSUE THREAD

**Issue by wordpressnewbie** [Automattic/amp-wp#153]
Installed plugin, and updated to new one a few days ago, saw the amp additions in the title bar but now they are gone!?

Also with the updated version do we not have to flush the cache like version 1?

Google has some errors it has found, but now it seems like the plugin has stopped working!?

**Comment by mjangda** [comment]
Can you share a screenshot or more details about what isn't working? What do you see when you visit an AMP url for a post?

**Comment by wordpressnewbie** [comment]
Thanks for replying!!!

Yes, yesterday I could clearly see the "amp" in the line in the browser, but today none of my websites have this at all!!??

Here is a link directly from my google search console showing an error, the amp is in the line, but when you click on it you get a 404 error.
http://www.nascarcamping.com/pocono-raceway/amp/

Its almost like the plugin turned itself off!?

**Comment by mjangda** [comment]
Oh, I think I see. We changed the plugin to only work with Posts for now, and it does work in those cases: http://www.nascarcamping.com/uncategorized/welcome-to-our-new-site/amp/

We're going to look at adding support for Pages in the future. For now, you can manually include them following the instructions here: https://github.com/Automattic/amp-wp#custom-post-type-support

**Comment by wordpressnewbie** [comment]
We are neighbours!!!!!
Down the road in Hamilton the City of Waterfalls!!!!
Chris

Date: Fri, 29 Jan 2016 13:40:57 -0800
