### ISSUE TITLE
Using Sabberworm\CSS\CSSList\Document::splice() makes fatal error

### ISSUE THREAD

**Issue by PayteR** [Automattic/amp-wp#1566]
Hi im using dev version of this plugin. When i have  !important ruleset in post_content, then this error occurs

```
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Sabberworm\CSS\CSSList\Document::splice() in /........../plugins/amp-wp-develop/includes/sanitizers/class-amp-style-sanitizer.php:1704
```
splice() method doesn't exists (anymore?), so it needs to be substituted

**Comment by westonruter** [comment]
Have you done `composer install` recently? The `slice` method has been introduced recently in the XWP fork of PHP-CSS-Parser: https://github.com/xwp/PHP-CSS-Parser/commit/30a931eed6d8c014751bc11602648f959771a627

**Comment by PayteR** [comment]
Ok i see, where is the issue now. I use Roots|Bedrock WP installation, so i use composer in root directory and added CSS-Parser there in composer.jsom manually. But when i add repository, i can't update because it wants authentication to github, even when repository is public

```
Could not fetch https://api.github.com/repos/xwp/PHP-CSS-Parser, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+PayterPC+2018-11-02+1617
to retrieve a token. It will be stored in "C:/Users/payte/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden): 
```

**Comment by westonruter** [comment]
You may want to use a `built` tag instead of adding from source. You can install 1.0-RC1 with all of the dependencies resolved and sources built simply by checking out [`1.0-RC1-built`](https://github.com/Automattic/amp-wp/tree/1.0-RC1-built) instead.

For more background on this, see #1167.
