### ISSUE TITLE
The attribute 'rel' in tag 'a' is set to the invalid value

### ISSUE THREAD

**Issue by LePouet** [Automattic/amp-wp#157]
Hi,

i'm testing this plugin and when i try the validator i have this error for all the images which are set to link to their attachment page : 

> The attribute 'rel' in tag 'a' is set to the invalid value 'attachment wp-att-709xx'.

Is this a plugin issue ?

**Comment by mjangda** [comment]
Thanks for the report. This was fixed in #100.
