### ISSUE TITLE
Amp Sidebar Disappears inWordPress theme

### ISSUE THREAD

**Issue by kwesir** [Automattic/amp-wp#1574]
Amp Sidebar Disappears in my WordPress theme using AMP to WP official plugin Version 1.0-RC1-20181005T172737Z-6bf2a1d8

I have added direct child of the body,
I have added AMP component script to the head. The plugin will do this automatically.
Also add_theme_support('amp'); to the function.php

**Comment by westonruter** [comment]
Please share the code you are adding.

Is there a validation error being raised in the plugin, such as when you try to save a post?

**Comment by kwesir** [comment]
> Please share the code you are adding.
> 
> Is there a validation error being raised in the plugin, such as when you try to save a post?

	// Entire site render as Native AMP | function.php
	add_theme_support('amp');

		
		<header class="header-container">

			<div class="header flex-box margin-right-left-auto">	
			
				<div role="button" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger"><i class="material-icons">menu</i></div>
				  <a href="<?php echo esc_url( home_url( '/' ) ); ?>" class="margin-right-left-auto"><amp-img src="<?php bloginfo('stylesheet_directory'); ?>/assets/img/logo.png" width="117" height="50" layout="fixed" title="<?php bloginfo( 'name' ); ?> Logo"></amp-img></a>

					<?php
						wp_nav_menu( array(
							
							'menu_location'		=> 'primary',
							'container'			=> 'nav',
							'container_class'	=> 'nav-menu-container',
							'menu_class'		=> 'nav-menu flex-box'
							
						) );
					?>					
			</div>
			
		</header>
		
		
		<amp-sidebar id="mobile-sidebar" layout="nodisplay">
			<div class="mobile-hamburger-container">
				<div role="button" aria-label="close sidebar" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger">X</div>
			</div>

			<nav class="mobile-nav-container">
				<ul class="mobile-nav-menu">
					<li><a href="index.html">Home</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="portfolio.html">Portfolio</a></li>
					<li><a href="blog.html">Blog</a></li>
					<li><a href="contact.html">Contact</a></li> 	 			
				</ul>
			</nav>			

			<hr>
			<h4 class="text-align-center">Fellow Us</h4>
			
			<ul class="social-follow flex-box">
				<li>
					<a href="https://twitter.com/jKwesiAkuffo" target="_blank" class="twitter-icon">
						<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
						<title>Twitter</title>
						<path fill="#1da1f2" d="M31.939 6.092c-1.18 0.519-2.44 0.872-3.767 1.033 1.352-0.815 2.392-2.099 2.884-3.631-1.268 0.74-2.673 1.279-4.169 1.579-1.195-1.279-2.897-2.079-4.788-2.079-3.623 0-6.56 2.937-6.56 6.556 0 0.52 0.060 1.020 0.169 1.499-5.453-0.257-10.287-2.876-13.521-6.835-0.569 0.963-0.888 2.081-0.888 3.3 0 2.28 1.16 4.284 2.917 5.461-1.076-0.035-2.088-0.331-2.971-0.821v0.081c0 3.18 2.257 5.832 5.261 6.436-0.551 0.148-1.132 0.228-1.728 0.228-0.419 0-0.82-0.040-1.221-0.115 0.841 2.604 3.26 4.503 6.139 4.556-2.24 1.759-5.079 2.807-8.136 2.807-0.52 0-1.039-0.031-1.56-0.089 2.919 1.859 6.357 2.945 10.076 2.945 12.072 0 18.665-9.995 18.665-18.648 0-0.279 0-0.56-0.020-0.84 1.281-0.919 2.4-2.080 3.28-3.397l-0.063-0.027z"></path>
						</svg>
					</a>
				</li> 
				<li>
					<a href="https://www.facebook.com/jKwesiAkuffo/" target="_blank" class="facebook-icon">
						<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
							<title>Facebook</title>
							<path d="M29 0h-26c-1.65 0-3 1.35-3 3v26c0 1.65 1.35 3 3 3h13v-14h-4v-4h4v-2c0-3.306 2.694-6 6-6h4v4h-4c-1.1 0-2 0.9-2 2v2h6l-1 4h-5v14h9c1.65 0 3-1.35 3-3v-26c0-1.65-1.35-3-3-3z"></path>
						</svg>
					</a>	
				</li>
			</ul> 
			
		</amp-sidebar>

**Comment by kienstra** [comment]
**Toggling Sidebar**

Hi @kwesir,
Thanks for bringing this up.

On this line in the snippet above:

```php
<div role="button" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger"><
```

Have you tried changing:
```php
on="tap:mobile-sidebar.toggle"
```
to:
```php
on="tap:sidebar1.toggle"
```

That toggles the sidebar to display. Of course, this example is unstyled:

![toggle-amp-sidebar](https://user-images.githubusercontent.com/4063887/47873946-22200b80-ddd8-11e8-9b9b-cce2183d007c.gif)

**Comment by kienstra** [comment]
**Sorry, My Suggestion Was Wrong**

Hi @kwesir,
Sorry, the suggestion above uses code I copied from the [documentation](https://ampbyexample.com/components/amp-sidebar/). I'll work on another approach.

**Comment by kienstra** [comment]
**Placement Of Snipped**

Hi @kwesir,
Is this on a live site, by chance? If not, could you possibly provide either the full theme, or the HTML from the document (not the PHP template)?

When copying your snippet into the `header.php` of a child theme of Twenty Seventeen, clicking 'menu' expands the `<amp-sidebar>`. Is that the case in your environment?

Here's the `header.php` file:

```php
<?php
/**
 * The header.php file for a child theme of Twenty Seventeen
 *
 * Copied verbatim from header.php of twentyseventeen, with a snippet from kwesir copied verbatim as the first child of <body>.
 * The <header> from twentyseventeen is deleted.
 *
 * @link https://github.com/Automattic/amp-wp/issues/1574#issuecomment-434899308
 *
 * @package TwentySeventeenChild
 * @since 0.1
 * @version 0.1
 */

?><!DOCTYPE html>
<html <?php language_attributes(); ?> class="no-js no-svg">
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">

<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<!-- Main Navbar -->
	<header class="header-container">

		<div class="header flex-box margin-right-left-auto">

			<div role="button" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger"><i class="material-icons">menu</i></div>
			  <a href="<?php echo esc_url( home_url( '/' ) ); ?>" class="margin-right-left-auto"><amp-img src="<?php bloginfo('stylesheet_directory'); ?>/assets/img/logo.png" width="117" height="50" layout="fixed" title="<?php bloginfo( 'name' ); ?> Logo"></amp-img></a>

				<?php
					wp_nav_menu( array(

						'menu_location'		=> 'primary',
						'container'			=> 'nav',
						'container_class'	=> 'nav-menu-container',
						'menu_class'		=> 'nav-menu flex-box'

					) );
				?>
		</div>

	</header>

	<!-- #Mobile Sidebar -->
	<amp-sidebar id="mobile-sidebar" layout="nodisplay">
		<div class="mobile-hamburger-container">
			<div role="button" aria-label="close sidebar" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger">X</div>
		</div>

		<nav class="mobile-nav-container">
			<ul class="mobile-nav-menu">
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About</a></li>
				<li><a href="portfolio.html">Portfolio</a></li>
				<li><a href="blog.html">Blog</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav>

	</amp-sidebar><!-- #End Sidebar -->
<div id="page" class="site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'twentyseventeen' ); ?></a>

	<?php

	/*
	 * If a regular post or page, and not the front page, show the featured image.
	 * Using get_queried_object_id() here since the $post global may not be set before a call to the_post().
	 */
	if ( ( is_single() || ( is_page() && ! twentyseventeen_is_frontpage() ) ) && has_post_thumbnail( get_queried_object_id() ) ) :
		echo '<div class="single-featured-image-header">';
		echo get_the_post_thumbnail( get_queried_object_id(), 'twentyseventeen-featured-image' );
		echo '</div><!-- .single-featured-image-header -->';
	endif;
	?>

	<div class="site-content-contain">
		<div id="content" class="site-content">
```

This looks to work as expected, though of course it's unstyled:

![amp-sidebar-toggle](https://user-images.githubusercontent.com/4063887/47877195-f48b9000-dde0-11e8-900f-526205773ebd.gif)

**Comment by kwesir** [comment]
> **Is There A Live Site Or Theme Available?**
> 
> Hi @kwesir,
> Is this on a live site, by chance? If not, could you possibly provide either the full theme, or the HTML from the front-end document (not the PHP template)?
> 
> When copying your snippet into the `header.php` of a child theme of Twenty Seventeen, clicking 'menu' expands the `<amp-sidebar>`. Is that the case in your environment?
> 
> Here's the `header.php` file:
> 
> ```
> <?php
> /**
>  * The header.php file for a child theme of Twenty Seventeen
>  *
>  * Copied verbatim from header.php of twentyseventeen, with a snippet from kwesir copied verbatim as the first child of <body>.
>  * The <header> from twentyseventeen is deleted.
>  *
>  * @link https://github.com/Automattic/amp-wp/issues/1574#issuecomment-434899308
>  *
>  * @package TwentySeventeenChild
>  * @since 0.1
>  * @version 0.1
>  */
> 
> ?><!DOCTYPE html>
> <html <?php language_attributes(); ?> class="no-js no-svg">
> <head>
> <meta charset="<?php bloginfo( 'charset' ); ?>">
> <meta name="viewport" content="width=device-width, initial-scale=1">
> <link rel="profile" href="http://gmpg.org/xfn/11">
> 
> <?php wp_head(); ?>
> </head>
> 
> <body <?php body_class(); ?>>
> 
> 	<header class="header-container">
> 
> 		<div class="header flex-box margin-right-left-auto">
> 
> 			<div role="button" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger"><i class="material-icons">menu</i></div>
> 			  <a href="<?php echo esc_url( home_url( '/' ) ); ?>" class="margin-right-left-auto"><amp-img src="<?php bloginfo('stylesheet_directory'); ?>/assets/img/logo.png" width="117" height="50" layout="fixed" title="<?php bloginfo( 'name' ); ?> Logo"></amp-img></a>
> 
> 				<?php
> 					wp_nav_menu( array(
> 
> 						'menu_location'		=> 'primary',
> 						'container'			=> 'nav',
> 						'container_class'	=> 'nav-menu-container',
> 						'menu_class'		=> 'nav-menu flex-box'
> 
> 					) );
> 				?>
> 		</div>
> 
> 	</header>
> 
> 	
> 	<amp-sidebar id="mobile-sidebar" layout="nodisplay">
> 		<div class="mobile-hamburger-container">
> 			<div role="button" aria-label="close sidebar" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger">X</div>
> 		</div>
> 
> 		<nav class="mobile-nav-container">
> 			<ul class="mobile-nav-menu">
> 				<li><a href="index.html">Home</a></li>
> 				<li><a href="about.html">About</a></li>
> 				<li><a href="portfolio.html">Portfolio</a></li>
> 				<li><a href="blog.html">Blog</a></li>
> 				<li><a href="contact.html">Contact</a></li>
> 			</ul>
> 		</nav>
> 
> 	</amp-sidebar>
> <div id="page" class="site">
> 	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'twentyseventeen' ); ?></a>
> 
> 	<?php
> 
> 	/*
> 	 * If a regular post or page, and not the front page, show the featured image.
> 	 * Using get_queried_object_id() here since the $post global may not be set before a call to the_post().
> 	 */
> 	if ( ( is_single() || ( is_page() && ! twentyseventeen_is_frontpage() ) ) && has_post_thumbnail( get_queried_object_id() ) ) :
> 		echo '<div class="single-featured-image-header">';
> 		echo get_the_post_thumbnail( get_queried_object_id(), 'twentyseventeen-featured-image' );
> 		echo '</div>';
> 	endif;
> 	?>
> 
> 	<div class="site-content-contain">
> 		<div id="content" class="site-content">
> ```
> 
> This looks to work as expected, though of course it's unstyled:
> 
> ![amp-sidebar-toggle](https://user-images.githubusercontent.com/4063887/47877195-f48b9000-dde0-11e8-900f-526205773ebd.gif)

Please, can the theme to you through email.?

**Comment by kienstra** [comment]
Hi @kwesir, 
Sure, email would be fine.

**Comment by kwesir** [comment]
> Hi @kwesir,
> Sure, email would be fine.

Please, i have sent you the email to download the Theme. Thank you and counting your quick response.

**Comment by kwesir** [comment]
> Please share the code you are adding.
> 
> Is there a validation error being raised in the plugin, such as when you try to save a post?

NO error validation. The whole amp-sidebar disappears. Very confusing.

**Comment by kienstra** [comment]
**Responded To email**

Hi @kwesir,
Thanks for emailing your theme. I responded to the email, and it looks like the `<amp-sidebar>` displays well when it's the first child of `<body>`. 

This [AMP Playground example](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-sidebar%2Fsource%2F) has the `<amp-sidebar>` as the first child of the `<body>`.

Though your implementation doesn't look wrong, per [this document](https://www.ampproject.org/docs/reference/components/amp-sidebar#behavior):

>The amp-sidebar should be a direct child of the <body>.

**Comment by kienstra** [comment]
**Closing**

Hi @kwesir,
Thanks for bringing this up. Based on our conversation via email, your Native AMP theme looks good, and it looks like the `<amp-sidebar>` works, based on the small change of placing it as the first child of `<body>`. 

Even though the [documentation](https://www.ampproject.org/docs/reference/components/amp-sidebar#behavior) only says that:
>The `<amp-sidebar>` should be a direct child of the `<body>`.

I'm closing this now. But feel free to comment on this issue if there's anything else related to this. 

Enjoy the rest of the weekend.
