### ISSUE TITLE
amp-sidebar disappears WordPress Theme Development

### ISSUE THREAD

**Issue by kwesir** [Automattic/amp-wp#1575]
Amp Sidebar Disappears in my Native WordPress theme using AMP to WP official plugin Version 1.0-RC1-20181005T172737Z-6bf2a1d8

I have added direct child of the body,
I have added AMP component script to the head. The plugin will do this automatically.
Also add_theme_support('amp'); to the function.php

Codes 
		
</head>

	<body <?php body_class(); ?>>
	<div id="page" class="site">
	<a class="skip-link screen-reader-text" href="#content"><?php esc_html_e( 'Skip to content', 'amptowordpress' ); ?></a>

		
		<header class="header-container">

			<div class="header flex-box margin-right-left-auto">	
			
				<div role="button" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger"><i class="material-icons">menu</i></div>
				  <a href="<?php echo esc_url( home_url( '/' ) ); ?>" class="margin-right-left-auto"><amp-img src="<?php bloginfo('stylesheet_directory'); ?>/assets/img/logo.png" width="117" height="50" layout="fixed" title="<?php bloginfo( 'name' ); ?> Logo"></amp-img></a>

					<?php
						wp_nav_menu( array(
							
							'menu_location'		=> 'primary',
							'container'			=> 'nav',
							'container_class'	=> 'nav-menu-container',
							'menu_class'		=> 'nav-menu flex-box'
							
						) );
					?>					
			</div>
			
		</header>
		
		
		<amp-sidebar id="mobile-sidebar" layout="nodisplay">
			<div class="mobile-hamburger-container">
				<div role="button" aria-label="close sidebar" on="tap:mobile-sidebar.toggle" tabindex="0" class="hamburger">X</div>
			</div>

			<nav class="mobile-nav-container">
				<ul class="mobile-nav-menu">
					<li><a href="index.html">Home</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="portfolio.html">Portfolio</a></li>
					<li><a href="blog.html">Blog</a></li>
					<li><a href="contact.html">Contact</a></li> 	 			
				</ul>
			</nav>

		</amp-sidebar>

**Comment by kienstra** [comment]
Hi @kwesir,
Thanks for bringing this up. 

Could you please see my response in https://github.com/Automattic/amp-wp/issues/1574#issuecomment-434899308? 

If it's alright, I'm going to close this issue as a duplicate, and we can track this in #1574.
