### ISSUE TITLE
Caching issues with URL change

### ISSUE THREAD

**Issue by pacifier007** [Automattic/amp-wp#1578]
Curious as to why was the AMP url changed to ?amp from /amp/ as in the older versions? The old version was quite fine and it was compatible with all cache plugins.

The new URL makes it incompatible with sn important setting of almost all popular plugins. When you have plugins like WooCommerce and similar, you have to disable cache for query strings as they query strings are supposed to change behavior and be dynamic in nature.

But in the case of AMP, the old static pretty permalink worked great for all caches and it made sense.

**Comment by westonruter** [comment]
The `/amp/` endpoint is not compatible when using AMP across other templates of a site, beyond just posts. It also is not compatible with posts either when you are using custom endpoints that you want to serve as AMP as well. The query parameter is compatible with any permalink structure.

For more info on this, see https://wordpress.org/support/topic/0-6-0-not-working-for-pages/#post-9903766
