### ISSUE TITLE
Native - Image Resolution

### ISSUE THREAD

**Issue by csossi** [Automattic/amp-wp#1579]
https://native-ampconfdemo.pantheonsite.io/
Images appear "squished" on Native site:
![image](https://user-images.githubusercontent.com/16945664/47875311-995f9a80-ddec-11e8-8772-7f676e6e1f74.png)

**Comment by kienstra** [comment]
**Thanks, Will Work On This**

Hi @csossi,
Thanks for opening this. I'm moving this into 'To Do' in the `1.0` project, and I'll work on it.

**Comment by kienstra** [comment]
This is a good catch. It's addressed in PR #1627 with https://github.com/Automattic/amp-wp/pull/1627/commits/c9e0f03b34b423df011e108d5d8c390bcc2630ea. And it's also tracked in #1604.
