### ISSUE TITLE
Native - Content Overlap

### ISSUE THREAD

**Issue by csossi** [Automattic/amp-wp#1581]
https://native-ampconfdemo.pantheonsite.io/

Page has some content overlap re: video and side widget:
![image](https://user-images.githubusercontent.com/16945664/47875960-543c6800-ddee-11e8-8584-4d47c09a4acf.png)

**Comment by kienstra** [comment]
**Thanks, Planning On Addressing**

Hi @csossi,
Thanks for opening this. I'm moving this into 'To Do' in the `1.0` project, and I'll work on it.
