### ISSUE TITLE
Plugin not working on posts either

### ISSUE THREAD

**Issue by wordpressnewbie** [Automattic/amp-wp#160]
I tried a different website and loaded the plugin this site has posts and pages, and once again it does not recognize the posts either.

I tried flushing cache, and going to permalinks and saving again as well, here is a link to a post page, I am stumped....LOL

(http://www.americanheroesracing.com/memorial-race-for-us-army-staff-sergeant-ari-r-cullers/)
[](url)
[http://www.americanheroesracing.com/memorial-race-for-us-army-staff-sergeant-ari-r-cullers/]

**Comment by mjangda** [comment]
AMP versions of posts are rendering (e.g. http://www.americanheroesracing.com/memorial-race-for-us-army-staff-sergeant-ari-r-cullers/amp/) so the plugin is working as expected.

**Comment by wordpressnewbie** [comment]
How did you get that to display like that!?

**Comment by mjangda** [comment]
Add `/amp/` to the end of any post url.

**Comment by wordpressnewbie** [comment]
Okay so we should not be seeing it done automatically then?

So, if I understand the plugin is working, but we dont see it?

Is there something we need to do manually that the plugin does not handle?

**Comment by mjangda** [comment]
Right, so the idea with AMP is that "consumer platforms" (i.e. apps like Twitter, and sites like Google Search) will automatically display the AMP version of a post when someone click through to a link on your site. It's not really implemented anywhere yet though.

You can automatically redirect your users to AMP versions of your content, but that's not something the plugin does.

**Comment by wordpressnewbie** [comment]
How do I know if the plugin is working?

**Comment by mjangda** [comment]
If you can see the AMP template (blue bar at the top) when you add `/amp`/ to any post URL, that means it's working.
