### ISSUE TITLE
WordPress branding for Business Plans

### ISSUE THREAD

**Issue by arcangelini** [Automattic/amp-wp#1601]
When using the AMP plugin on WordPress.com Business plans the "Powered by WordPress" appears in the footer despite whatever is set for "Branding" in the "Site Identity" settings.

Video of testing ⇢ https://cld.wthms.co/hpkhGp
Test site enabled on ⇢ https://business-plan.blog

Ideally this should be disabled when the user hides the branding. It also may be beneficial to update the link to send to WordPress.com for sites that are on WordPress.com rather than WordPress.org

7847130-hc

**Comment by westonruter** [comment]
Hi there. This would be a question better suited for WordPress.com Support.

**Comment by arcangelini** [comment]
Thanks Weston : )

I actually am on WordPress.com Support as an HE and was hoping to submit this as a bug report. Would you have any suggestions where I could submit this instead?

**Comment by westonruter** [comment]
@arcangelini You might want to check with @seanosh, who helped debug another issue with the footer credits being added in https://github.com/Automattic/amp-wp/pull/1066

**Comment by seanosh** [comment]
That would be @jhnstn actually, who worked on/debugged this issue originally :)
