### ISSUE TITLE
Test with WordPress 5.0, bump tested version to 5.0

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#1604]
**As a site owner, wanting to use the AMP plugin site with Wordpress 5.0, I want to know that the AMP plugin works with latest versions of Wordpress (ie. 5.0)  and Gutenberg  4.2.0**
_Acceptance Criteria_
- [ ] AC1. Test this plugin on the [Paired mode staging site](https://paired-ampconfdemo.pantheonsite.io/wp-admin/plugins.php?plugin_status=all&paged=1&s), which is now running WordPress `5.0-beta3`, Gutenberg `4.2.0` (latest), and [Twenty Nineteen](https://github.com/wordPress/twentynineteen) 
- [ ] AC2. Ensure visual and functional parity between AMP and non-AMP pages, using these [guidelines](https://docs.google.com/document/d/1XTnHia3O_nAnB8K5aez4IxfRP8LkMtPbW5Oj6wksYBc/edit?usp=sharing)
- [ ] AC3. Ensure the Compatibility Tool works like before (#1361, #1362, #1364, #1365) (_There's no need to retest every AC on those issues, just confirm existing functionality_)
- [ ] AC4. Once this is tested and the issues are resolved, bump the 'Tested up to' version in `readme.txt` and `readme.md` from `4.9` to `5.0`
https://github.com/Automattic/amp-wp/blob/469e99213d58d2af83915ca5924657648365bde7/readme.txt#L5

**Comment by kienstra** [comment]
**In 'To do'**

Hi @alcurrie,
This is now in the ['To do' column of v1.0](https://github.com/Automattic/amp-wp/projects/6#card-14714880). Feel free to add anything, or ask questions. 

The next step is for me to ask @csossi to test this, using the [Paired mode staging site](https://paired-ampconfdemo.pantheonsite.io/wp-admin/plugins.php?plugin_status=all&paged=1&s).

**Comment by westonruter** [comment]
For the Twenty Nineteen aspects here, see https://github.com/Automattic/amp-wp/pull/1587

**Comment by westonruter** [comment]
Merged PR regarding notice in compatibility tool: #1605.

**Comment by valtermild** [comment]
Fatal error: Uncaught Error: Call to undefined function gutenberg_get_jed_locale_data() in /home/v/valter8x/valter8x.beget.tech/public_html/wp-content/plugins/amp/includes/validation/class-amp-validation-manager.php:1919 Stack trace: #0 /home/v/valter8x/valter8x.beget.tech/public_html/wp-includes/class-wp-hook.php(286): AMP_Validation_Manager::enqueue_block_validation('') #1 /home/v/valter8x/valter8x.beget.tech/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /home/v/valter8x/valter8x.beget.tech/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/v/valter8x/valter8x.beget.tech/public_html/wp-admin/edit-form-blocks.php(383): do_action('enqueue_block_e...') #4 /home/v/valter8x/valter8x.beget.tech/public_html/wp-admin/post.php(160): include('/home/v/valter8...') #5 {main} thrown in /home/v/valter8x/valter8x.beget.tech/public_html/wp-content/plugins/amp/includes/validation/class-amp-validation-manager.php on line 1919

**Comment by valtermild** [comment]
After installing WordPress version 5.0 and the amp plugin
Version 1.0-RC2-20181105T185432Z-049b4cd2 and the activation of the new default Twenty Nineteen theme. When you try to add a new post, this error occurs.

**Comment by alcurrie** [comment]
Thanks for the update

**Comment by kienstra** [comment]
**Good Idea**

Hi @alcurrie,
Good idea. I updated a requirement to include testing on [Twenty Nineteen](https://github.com/wordPress/twentynineteen). That's now the active theme on the 'Paired' site:

https://paired-ampconfdemo.pantheonsite.io/

**Comment by alcurrie** [comment]
@csossi  - this is ready for your testing:
_The following site is set up to test the WP 5.0:_ 
 https://paired-ampconfdemo.pantheonsite.io/  (This site  is running AMP V1.0-RC,  Twenty-nineteen Theme,  Gutenberg 4.2.0  (not the newest) and WP 5.0beta 4

**Comment by kienstra** [comment]
**Thanks For Testing**
*Moving To 'To Do' To Await Developmnet*

Hi @csossi,
Thanks for testing this. I'm moving this to 'To Do' until there's work on the issues here.

**Comment by westonruter** [comment]
@valtermild The issue you identified has been fixed in #1612.
