### ISSUE TITLE
Rename or replace gutenberg_get_jed_locale_data() usage

### ISSUE THREAD

**Issue by swissspidy** [Automattic/amp-wp#1618]
`gutenberg_get_jed_locale_data()` is now `wp_get_jed_locale_data()` in WordPress core.

The plugin currently fatals because of that.

The function should be renamed in the plugin and perhaps even considered to replaced in WP 5.0+ as per https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/.

See also #1604.

**Comment by swissspidy** [comment]
Either way, it doesn't hurt to add some `function_exists()` checks as is already done in `\AMP_Post_Meta_Box`.

**Comment by westonruter** [comment]
And the function has now been removed from core. We need to address this again.

See https://core.trac.wordpress.org/changeset/43910

**Comment by westonruter** [comment]
@swissspidy Can you figure out what needs to be done here for the 1.0-RC3 release tomorrow? /cc @kienstra
