### ISSUE TITLE
Readme: Clarify the goal of the plugin

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#162]
Specifically, that it only creates AMP content and that it's up to apps/consumers to display the content.

**Comment by jillesvangurp** [comment]
The readme currently states: "That is handled by AMP consumers such as Google Search. For more details, see the AMP Project FAQ."

This suggests something that as far as I can see is actually not true. Installing this plugin will have zero affect on how google search handles your blog.  How would google know there is an amp version of content without more work on the cms side to e.g. redirect, expose the amp pages to crawlers, or add some kind of link to the regular content (rel=amp)? As far as I can see there is currently no discovery mechanism in place and the only way for google to know would be if they would opportunistically slap /amp on every url they crawl, which I assume is something they are not doing.

It might be helpful to outline in the readme what the plan here is.

**Comment by mjangda** [comment]
The plugin adds `<link rel=amphtml` tags pointing to the AMP version of the
page (see amp_frontend_add_canonical) to enable discovery.

**Comment by jillesvangurp** [comment]
cool, that wasn't clear to me at all.
