### ISSUE TITLE
Method to filter iframe attributes

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/amp-wp#1623]
We have iframes in some of our posts. (omny studio embeds to be precise) Those iframes specifcy width/height attributes.

Upon AMP transformation, the `amp-iframe` gets the `layout="intrinsic"` attribute because of the width settings in the iframe embed.

This particular iframe doesn't work with responsive heights and needs to have `layout="fixed-height"` set instead.

I see where the `layout="intrinsic"` is being added, but there isn't a filter mechanism available to modify those attributes.

Is there another simple way that this could be achieved? Not sure if this is a feature request, or just a request for a pointer to some existing functionality.

**Comment by westonruter** [comment]
Are you able to add `layout="fixed-height"` to the originally-output `iframe` elements? For example, you could do this with a `the_content` filter:

```php
add_filter( 'the_content', function( $content ) {
	if ( is_amp_endpoint() ) {
		$content = preg_replace(
			 '/(?<=<iframe)(?=[^>]+?omny[^>]+>)/',
			 ' layout="fixed-height"',
			 $content
		);
	}
	return $content;
} );
```

That's somewhat brute-force. It would be better if you could add the `layout` attribute closer to where the `iframe` was originally introduced, for example by filtering oEmbed data or wrapping a shortcode output.

Once you set the `layout` then it will pass through:

https://github.com/Automattic/amp-wp/blob/2938438a61b658c0e2e5ca82b1e8a80bef80c129/includes/sanitizers/class-amp-iframe-sanitizer.php#L158-L160

However, this is only the case as of 1.0. It was not that way in 0.7.2. So I suggest you try with [1.0-RC2](https://github.com/Automattic/amp-wp/releases/tag/1.0-RC2).
