### ISSUE TITLE
Update readme images and heading

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#1631]
AC1. Create a new [banner-772x250.png](https://github.com/Automattic/amp-wp/blob/7b459339d6b23af5e3afd19c2b6b7856ca199c1e/wp-assets/banner-772x250.png) and [banner-1544x500.png](https://github.com/Automattic/amp-wp/blob/7b459339d6b23af5e3afd19c2b6b7856ca199c1e/wp-assets/banner-1544x500.png) (the same image, just different sizes
AC2. Replace the [icon-128x128.png](https://github.com/Automattic/amp-wp/blob/7b459339d6b23af5e3afd19c2b6b7856ca199c1e/wp-assets/icon-128x128.png) and [icon-256x256.png](https://github.com/Automattic/amp-wp/blob/7b459339d6b23af5e3afd19c2b6b7856ca199c1e/wp-assets/icon-256x256.png) with the blue [AMP](https://www.ampproject.org/) logo (also the same, just different sizes)
AC3. Rename the `readme` header from `=== AMP for WordPress ===` to `=== AMP ===`
https://github.com/Automattic/amp-wp/blob/097324be0ba81b2c3011467c57aa7b31db0403c8/readme.txt#L1

<img width="1230" alt="wordpress-org-amp" src="https://user-images.githubusercontent.com/4063887/48798985-a07f1780-eccb-11e8-917f-8ea7a91f2ce4.png">

**Comment by cathibosco** [comment]
Here is a draft for the banner ... feedback is always welcome 
![amp-wordpress-plugin-banner-1544x500](https://user-images.githubusercontent.com/4819761/48842946-aa545980-ed63-11e8-9fc4-3e4d3837f68c.png)

**Comment by cathibosco** [comment]
![mock-up-1](https://user-images.githubusercontent.com/4819761/48843873-61ea6b00-ed66-11e8-8972-e23d488071b7.png)

**Comment by westonruter** [comment]
I don't think we should have the WordPress logo in the banner. Also I think @amedina will suggest the against the diagonal lines.

The white text describing what AMP is should also be excluded because that will be problematic for translation.

**Comment by westonruter** [comment]
For the title of the plugin, it feels super verbose right now. Definitely wouldn't fit in a mobile viewport. I think it should just be plainly "AMP". Everything else could go into the description.

**Comment by cathibosco** [comment]
Let's look at this... 
![mock-up-6](https://user-images.githubusercontent.com/4819761/48858865-848e7b00-ed8a-11e8-8c4b-5bcf8b796e10.png)

**Comment by cathibosco** [comment]
Last one for today - I agree with @westonruter the name is a bit long for mobile and for the product page... how do you like this version? @amedina 

I can refresh this again on Friday... getting closer :)

![mock-up-7](https://user-images.githubusercontent.com/4819761/48867279-b19b5780-eda3-11e8-8452-b38f5d9db05f.png)

**Comment by cathibosco** [comment]
Here are 2 variations to review please:
@westonruter @kienstra @amedina 

![mock-up-8](https://user-images.githubusercontent.com/4819761/48916481-815dc280-ee50-11e8-96a3-f54530737813.png)


or



![mock-up-9](https://user-images.githubusercontent.com/4819761/48916482-815dc280-ee50-11e8-99c4-d8e00d88e7df.png)

**Comment by cathibosco** [comment]
Here is the file for the approved version without the rocket - we will start with that one and rename the plugin  AMP - thanks for all the reviews! 
[Archive- AMP-plugin-page-art.zip](https://github.com/Automattic/amp-wp/files/2608976/Archive-.AMP-plugin-page-art.zip)

**Comment by cathibosco** [comment]
@kienstra 
We have updated the graphics to align with the new product site - these are now the approved graphics - can you add them to the repo for us when you are back?  thank you!! :)

[Plugin Graphics for Repo.zip](https://github.com/Automattic/amp-wp/files/2612550/Plugin.Graphics.for.Repo.zip)
![mock-up-new](https://user-images.githubusercontent.com/4819761/48972460-d2a8b600-eff8-11e8-8c5e-b75c0d9ff2c8.png)

**Comment by cathibosco** [comment]
@kienstra @amedina @westonruter 
Please find the final graphics needed for the plugin repo here 
[Launch with these Graphics.zip](https://github.com/Automattic/amp-wp/files/2620938/Launch.with.these.Graphics.zip)
![mock-up-launch](https://user-images.githubusercontent.com/4819761/49096963-bfd0f400-f239-11e8-80c5-d6785280d94b.png)

 :)

**Comment by postphotos** [comment]
Oooh! I really like this. Nice work, folks! 🥇
