### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by kkranzo** [Automattic/amp-wp#164]
I know you can override the styles by using your own within a theme in the amp/style.php directory, however I only want to override the top nav bar color and that is it. How can I use a custom style to change the bar color but leaver everything else as-is?

**Comment by kkranzo** [comment]
Hmmm.

I added this to my functions.php and there is no change.

`add_action( 'amp_post_template_css', 'xyz_amp_my_additional_css_styles' );

function xyz_amp_my_additional_css_styles( $amp_template ) {
    // only CSS here please...
    ?>
    nav.title-bar {
        background: #000000;
    }
    nav.title-bar .site-icon {
        border-radius: 0;
    }
    <?php
}`

**Comment by mjangda** [comment]
Silly question (but needs to be asked): you're running the latest version from this repo?

**Comment by kkranzo** [comment]
I am using the recently updated 0.2 from the repository. Will that version not work with that method?

**Comment by mjangda** [comment]
No, you'll need the development version from here: https://github.com/Automattic/amp-wp/archive/master.zip

**Comment by kkranzo** [comment]
Okay, cool.

I'll just hold off so I can update my sites via the repository when it gets released.

Thanks!

**Comment by kkranzo** [comment]
Okay, I just updated to the latest development version and the custom styles are still not working.

Here is what I added to my functions.php. Is this correct?

```
//customize AMPL plugin styles
add_action( 'amp_post_template_css', 'xyz_amp_my_additional_css_styles' );

function xyz_amp_my_additional_css_styles( $amp_template ) {
    // only CSS here please...
    ?>
    nav.title-bar {
        background: #000000;
    }
    nav.title-bar .site-icon {
        border-radius: 0;
    }
    <?php
}
```

**Comment by kkranzo** [comment]
Nevermind, got it figured out. The class names were changed.
