### ISSUE TITLE
Should AMP settings panels be open by default

### ISSUE THREAD

**Issue by pacifier007** [Automattic/amp-wp#1645]
I find it distracting that in many Gutenberg blocks, AMP is the first panel. AMP is important and all but it's not the first thing I wish to interact with. It's above block's native Gutenberg controls and it's open by default. Even if it's kept above the native controls, I would suggest having it collapse by default. If someone wishes to interact with AMP settings, they can expand it.

In Gutenberg, `PanelBody` has the prop `initialOpen` which can control this behavior.

**Comment by westonruter** [comment]
Are you referring to the section that contains "Fit text"?

@miina Is it difficult to move the AMP settings down, perhaps before the Advanced section?

**Comment by pacifier007** [comment]
Thanks for the reply.

Yes, I am referring to the panel that contains Fit Text pushing the native controls down. It's more distracting in the in the Image and Gallery blocks as there are many AMP setting fields there overshadowing the native controls which are supposed to be used more often.

**Comment by westonruter** [comment]
This makes sense to me.

@miina Can we move the section down?

**Comment by miina** [comment]
@westonruter I'll look into this today / tomorrow.

**Comment by westonruter** [comment]
Fixed by #1652.
