### ISSUE TITLE
No changes after activated this plugin

### ISSUE THREAD

**Issue by srihari431** [Automattic/amp-wp#171]
Hi!!

Just i activated amp-wp plugin but no changes in my old Wordpress site.
ie, I not find any rel="amphtml..., in(view-source) my site,
Please direct me in right path.

Thanks,
srihari.

**Comment by dougj21** [comment]
Refresh your permalinks. Just go to your permalinks page and hit save. They should show up then.

**Comment by srihari431** [comment]
Thanks for soon response!!

I did whatever you say,But no luck!!!!
I not finding any rel="amphtml..., in(view-source)...

please help!

**Comment by leecollings** [comment]
I'm having exactly the same. There appears to be no change after installing this plugin, refreshing cache or re-saving permalinks.

Whenever I add /amp/ to the end of my URLs, I get Page Not Found, and adding ?amp=1 doesn't make any changes to the source code.

**Comment by dougj21** [comment]
@srihari431 Are you able to access the AMP version of your page? If so, then the rel=amphtml link should be in your original page's source code. See here: view-source:http://thedrivenlifestyle.net/imperfectly-perfect-a-different-s30/ and view source in chrome on line 98

@leecollings All I had to do was activate the plugin, then go to Settings > Permalinks and hit save changes. I didn't change my permalinks at all. This has been done on a few of my sites now with the plugin. You can see that it works here: http://thedrivenlifestyle.net/imperfectly-perfect-a-different-s30/amp/

My plugin version is 0.2

**Comment by kjy112** [comment]
> By default, the plugin only creates AMP content for posts.

Are you guys sure you are looking at a post?

**Comment by srihari431** [comment]
Yes this plugin working good in post.

But we have todo manually  ** domain.com/posttitle/amp**  it cant take auto???

How to redirect in mobile when we type **domain.com/posttitle** too ** domain.com/posttitle/amp** ???

Thanks!!

**Comment by mjangda** [comment]
Yes, the plugin does not automatically redirect to AMP versions of posts. That will be up to consumers of AMP content like Google Search, Nuzzel, etc.
