### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by VisWong** [Automattic/amp-wp#1711]
Fatal error: Class 'DOMDocument' not found in /var/www/html/wordpress/wp-content/plugins/amp-wp/includes/class-amp-wp-html-util.php on line 9

Here is the error while activating the plug-in.

I am using php7 and already installed php-xml module.

Any one encounter the same issue and have solution?

**Comment by kienstra** [comment]
Hi @VisWong,
It looks like that is for another [AMP plugin](https://plugins.trac.wordpress.org/browser/amp-wp/).

For example, here's the [location of that error](https://plugins.trac.wordpress.org/browser/amp-wp/trunk/includes/class-amp-wp-html-util.php?rev=1984423#L9) in its repo.

**Comment by VisWong** [comment]
Thank you for your reply @kienstra 

I just download it from wordpress plug-in market.

I am not so sure what should I do to complete the installation...

I would be very grateful if you could give me more guides.

Thanks a million.

**Comment by kienstra** [comment]
Hi @VisWong,
Would you like to try our plugin instead? 

https://wordpress.org/plugins/amp/

**Comment by VisWong** [comment]
Oh, sorry, i was asking at the wrong place...

**Comment by kienstra** [comment]
No problem, @VisWong. 

Here's the support forum for that plugin:
https://wordpress.org/support/plugin/amp-wp
