### ISSUE TITLE
get_the_excerpt() -  doesn't appear in the amp 0.2 view

### ISSUE THREAD

**Issue by apilatowicz** [Automattic/amp-wp#173]
get_the_excerpt() -  doesn't appear in the amp view - 0.1 and 0.2 version.
It would be nice to see also it.

**Comment by mjangda** [comment]
Not sure I understand. Where do you want the excerpt to be displayed?

**Comment by apilatowicz** [comment]
I'm working now on refreshing my blog, and I used in posts:
the_title (); get_the_excerpt (); the_content ();
And when I try to check an entry? Amp = 1 I only see the title and content
You can check it here http://goo.gl/AwCHva there is missing 'Piękno dzikich...'

**Comment by mjangda** [comment]
That's not usually how WordPress sites handle content; usually you display either the excerpt or the content, not both at the same time.

If you want to include the excerpt before the content, I'd suggest doing something like:

```
add_action( 'pre_amp_render_post', 'xyz_load_my_amp_content_filters' );

function xyz_load_my_amp_content_filters() {
    add_filter( 'the_content', 'xyz_prefix_excerpt_to_content',  );
}

function xyz_prefix_excerpt_to_content( $content ) {
    $excerpt = get_post()->post_excerpt;
    if ( $excerpt ) {
        $content = $excerpt . $content;
    }
    return $content;
}
```

**Comment by apilatowicz** [comment]
Thanks, it's working :)
