### ISSUE TITLE
Support for Pages

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#176]
**[Edited] Refer to the latest [acceptance criteria](https://github.com/Automattic/amp-wp/issues/176#issuecomment-346622268).**
___
At a minimum, they should have:
- slightly different template
- appropriate JSON metadata

We may need to adjust actions/filters to allow targeting posts or pages specifically.

PRs: #188, #619.

**Comment by technosailor** [comment]
I'm working on this now. Are there specific areas regarding the JSON schema that you're thinking about?

FWIW, the template renders fine for pages in the work I've done. Not sure much needs to be done to the template outside of removing displayed meta...

**Comment by dekket** [comment]
How is support for Pages coming along? I feel like Pages-support is mandatory for this plugin to take off. I'm psyched to give it a shot when support comes, since very few sites that I operate actually use posts.
Also, will Pages-support mean that there will also be support for Custom Post Types?

**Comment by ThierryA** [comment]
### Acceptance criteria:
1. WordPress core page post-type support will be added.
2. Similar to how Posts are currently, Pages will be capable of being AMPlified.
3. All pages will default to “enabled” if the “pages” checkbox is selected (enabled) in the AMP post types settings, see #798. The AMP version of the page should not be enabled if the “pages” checkbox is deselected (disabled) in the AMP settings.
4. If a specific page has AMP disabled (see rules in 709), the page will not be AMPlified.

**Comment by westonruter** [comment]
> If a specific page has AMP disabled (see rules in #709), the page will not be AMPlified.

This will be especially important in the case of pages with user-supplied page templates. If a page template has functionality in it that is hard-coded in PHP and showing the page in the AMP template is just not going to be acceptable, then a user would need to disable AMP for the page. We may want to consider defaulting AMP to “disabled” when a custom page template has been selected.

**Comment by westonruter** [comment]
One more thing to note on acceptance criteria: the AMP versions of URLs _may_ include `?amp` even with pretty permalinks enabled. This may turn out to be required to play nicely with rewrite rules generated for pages to disambiguate from pages about someone's favorite guitar amp, for example.

**Comment by ThierryA** [comment]
> One more thing to note on acceptance criteria: the AMP versions of URLs may include ?amp even with pretty permalinks enabled. This may turn out to be required to play nicely with rewrite rules generated for pages to disambiguate from pages about someone's favorite guitar amp, for example.
@westonruter I added that to the ACs.

**Comment by westonruter** [comment]
See PR #825 which is pending merge to resolve this issue.

**Comment by csossi** [comment]
Went to Contact Us page at http://amp-xwp-testbed.pantheonsite.io/contact/?amp which has AMP enabled. I ran an AMP Validator extension and it noted the attached error.
![image](https://user-images.githubusercontent.com/16945664/33807044-e3e6f91c-dd9e-11e7-87e2-29ca364f28b8.png)

**Comment by westonruter** [comment]
@csossi Thanks for that. This is actually something that I had done as part of #819 but deployed to the testbed prior to merging the PR.

I fixed the issue here: https://github.com/Automattic/amp-wp/pull/819/commits/a38d024a8e5dcc82d9bb79b7b2b1a21edad0d7b7

Re-deployed and the issue has been resolved: http://amp-xwp-testbed.pantheonsite.io/contact/?amp#development=1

**Comment by csossi** [comment]
verified in QA
