### ISSUE TITLE
HTTPS protocols full display

### ISSUE THREAD

**Issue by fahmi182** [Automattic/amp-wp#177]
Hi all dev, :)

i used cloudflare and ssl insecure content fixer plugin, and i get error in webmaster amp report, the style and script load with no https protocols, load with "//"

how to displat full https protocols:
    <link rel="stylesheet" href="https://fonts.googleapis.com/
my result display html is no https, with "//" like this:
    <link rel="stylesheet" href="//fonts.googleapis.com/

thanks

**Comment by davidnavia** [comment]
I fixed that by adding this in `amp/includes/sanitizers/class-amp-iframe-sanitizer.php` in line `81`

`	case 'src':
                        $out[ $name ] = preg_match("/^(https|http):/", $value) ? $value : 'https:'.$value;
                    break;
`

**Comment by fahmi182** [comment]
i try and not working, still display non-https/http protocols

**Comment by Satys** [comment]
Hi,

@mjangda This seems to be not yet fixed
