### ISSUE TITLE
Help -- getting google AMP errors which are making them not show up in the index!

### ISSUE THREAD

**Issue by Myth03** [Automattic/amp-wp#1788]
I am getting the following Google Validation errors for my site (SportMuse.net) which are causing them to be excluded. How do I go about fixing these?

Error | A tag on this page requires an AMP component 'script' tag, which is missing. 
Error | Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head.
Error | Tag or text which is only allowed inside the body section found outside of the body section. 
Error | The tag 'BODY' appears more than once in the document. 

I am up to date on AMP Plugin and have not done any customization. (I did recently update this to native, however, I still need to figure out how to correct the existing ones errors.)

Plugins installed:
Ad Inserter
AMP
Antispam Bee
Async JavaScript
AutoptimizeActivate
Fast Share Buttons, Analytics, Related Posts and Mores
Glue for Yoast SEO & AMP
Yoast SEO
Hummingbird
JCH Optimize
Jetpack by WordPress.com
SG Optimizer
Speed Booster Pack
TablePress
Yoast SEO

Specifically on these pages:

- https://sportmuse.net/2018/12/27/promotion-relegation-watch-league-two-midpoint/amp/ 
- https://sportmuse.net/2018/11/22/premier-league-week-13-power-rankings/amp/ 
- https://sportmuse.net/2018/12/26/premier-league-week-18-slate/amp/
- https://sportmuse.net/2018/12/27/camping-world-bowl-syracuse-v-west-virginia/amp/ 
- https://sportmuse.net/2018/12/27/promotion-relegation-watch-championship-version-4/amp/
- https://sportmuse.net/2018/12/25/efl-championship-week-19-power-rankings/amp/ 
- https://sportmuse.net/2018/12/26/servpro-first-responder-bowl-boston-college-boise-state/amp/
- https://sportmuse.net/2018/12/26/premier-league-week-18-power-rankings/amp/ 
- https://sportmuse.net/2018/12/21/epl-wolves-v-liverpool/amp/ 
- https://sportmuse.net/2018/12/14/premier-league-week-16-slate/amp/ 
- https://sportmuse.net/2018/12/19/europa-league-round-of-32-draw/amp/
- https://sportmuse.net/2018/12/20/premier-league-week-17-power-rankings/amp/
- https://sportmuse.net/2018/12/20/nfl-week-16-preview/amp/ 
- https://sportmuse.net/2018/12/17/champions-league-round-of-16-draw/amp/
- https://sportmuse.net/2018/12/16/championship-monday-derby-county-v-nottingham-forest/amp/
- https://sportmuse.net/2018/07/17/welcome-to-sportmuse/amp/ 
- https://sportmuse.net/2018/11/26/efl-championship-week-15-power-rankings/amp/ 
- https://sportmuse.net/2018/08/28/fantasy-sports-premier-league-week-3-recap/amp/

**Comment by westonruter** [comment]
The AMP runtime `v0.js` is getting removed from the page.

Please try deactivating the optimizer plugins, in particular:

* Async JavaScript
* Autoptimize
* JCH Optimize
* SG Optimizer
* Speed Booster Pack

Try deactivating them one-by-one, and after each check if the issue is fixed. Use the AMP validator to check the URL after each plugin is deactivated: https://validator.ampproject.org/ This will tell you which plugin is specifically causing problems.

Also, it is very likely that one or more of these optimization plugins are conflicting with each other.

**Comment by westonruter** [comment]
@Myth03 So what was the resolution? This will be helpful for those in the future who gave this problem.

**Comment by Myth03** [comment]
The error was coming from Speed Booster Pack. It appears that despite them allowing you to pick .js scripts to be excluded from their various speed improvements -- only some of them are actually excluded. Once I disabled this mod -- they all appeared to be working!
