### ISSUE TITLE
Plugin works, but... all content is 1 character wide

### ISSUE THREAD

**Issue by richardaucock** [Automattic/amp-wp#179]
This has me baffled: the tool works, but... all content is displayed 1 character wide. Images don't display either, but galleries do. 

Here's a screengrab... 
<img width="406" alt="screen shot 2016-02-10 at 18 50 30" src="https://cloud.githubusercontent.com/assets/12961614/12957989/3656099a-d027-11e5-9443-0a6e342cedd2.png">

And compare: 
http://www.motoringresearch.com/car-reviews/2016-toyota-prius-review-first-drive/amp
to http://www.motoringresearch.com/car-reviews/2016-toyota-prius-review-first-drive

Any help much appreciated, everyone!

**Comment by mjangda** [comment]
Looks like something else (another plugin?) is injecting other scripts on the page which are most likely breaking things (there are lots of extra scripts and markup added to the bottom of the AMP page).

**Comment by richardaucock** [comment]
Thanks Mohammad - that's a good lead. Not found it yet but will keep trying... appreciated!

**Comment by richardaucock** [comment]
Update - you are correct: deactivating Jetpack cures it. Now to find out what in Jetpack is causing the clash...

Thanks again - I'll keep everyone updated if it helps the developer archive.

**Comment by bcampeau** [comment]
I just set `content_max_width` to work around it, fwiw.

**Comment by richardaucock** [comment]
OK, progress made: appears to be Jetpack's Custom CSS that's causing it to display incorrectly.

With this in mind, can I add some AMP-specific CSS into the tool to work around it?

**Comment by mjangda** [comment]
This should be fixed in 0.3. @richardaucock can you update and let us know?

**Comment by richardaucock** [comment]
Confirming it works! Thanks ever so, all - superb. 

Appreciate your support and help.
