### ISSUE TITLE
Missing confirmation message after posting comment

### ISSUE THREAD

**Issue by swissspidy** [Automattic/amp-wp#1792]
According to #1029 / #936 confirmation messages should be displayed when posting a comment. However, that doesn't seem to be the case (anymore).

To reproduce:

1. Install AMP plugin
2. Activate Twenty Nineteen or any other theme that works well in native or paired mode
3. Enable comment moderation.
4. Write and submit a comment.
5. Note that the name & email fields are filled out, the textarea is emptied, and there is no confirmation message at all.
6. See comment held for moderation in the admin

Screenshot:

<img width="869" alt="screenshot 2019-01-02 at 16 21 39" src="https://user-images.githubusercontent.com/841956/50598360-cabb1c00-0eaa-11e9-894f-3a2dd91a7b16.png">

**Comment by westonruter** [comment]
@swissspidy The message in question for #1029 / #936 only applies to when using `<amp-live-list>` for comments. That is, enabling the `comments_live_list` argument for `amp` theme support. 

I believe that the issue you are noticing here would be reproducible without AMP entirely. I just tried in Twenty Seventeen in a non-AMP page and I saw the same thing.

I believe you are noticing a core bug, namely: https://core.trac.wordpress.org/ticket/43857

If you enable this setting in Discussion then you should see the classic moderation messages:

![image](https://user-images.githubusercontent.com/134745/50604459-e6570000-0e73-11e9-96df-9a95cc21f9e2.png)
