### ISSUE TITLE
Blog Instead of Homepage

### ISSUE THREAD

**Issue by stjohnsdivorce** [Automattic/amp-wp#186]
I installed the AMP plugin for my wordpress site and activated it. Unfortunately, it is pulling my blog page content instead of showing my homepage. Is this what is supposed to happen?

Newbie (so please excuse my lack of knowledge here).
http://www.stjohnsdivorcelawyer.com/?amp=1
Homepage here:
http://www.stjohnsdivorcelawyer.com/

Thanks,

**Comment by samarkandiy** [comment]
I think, the AMP is supposed to work with Blogs (Articles, News posts etc).

**Comment by mjangda** [comment]
Correct, the plugin only works with Posts right now: http://www.stjohnsdivorcelawyer.com/divorce-deposition-questions/amp/

#176 is working on adding support for Pages.
