### ISSUE TITLE
Blank Pages

### ISSUE THREAD

**Issue by sevensoutbill** [Automattic/amp-wp#192]
I have a clean install of WP 4.4.2 with the AMP plugin installed and using the default Twenty-Sixteen theme on a local install of WAMP. When I navigate to and post with /amp or ?amp=1 nothing is returned (IE 11 and Chrome). Completely blank - no html. No other plugins are installed.

Any ideas?

**Comment by sevensoutbill** [comment]
Apologies, this appears to be related to #149 . Fyi, I also returned true on the function is_valid_template( $template ) and it now works.

**Comment by mjangda** [comment]
@sevensoutbill can you check to see if the development version fixes it? https://github.com/Automattic/amp-wp/archive/master.zip

**Comment by wannaphongcom** [comment]
I have install of WP 4.4.2 with the AMP plugin installed and using the default Twenty Fiftee theme. I see post with /amp or ?amp=1 nothing is returned and https://github.com/Automattic/amp-wp/archive/master.zip. it not works.
