### ISSUE TITLE
Error functions.php

### ISSUE THREAD

**Issue by overpress** [Automattic/amp-wp#196]
Hi, 

We have implemented this code to functions.php to show the picture show but he shows us this error.

```
add_action( 'pre_amp_render_post', 'xyz_amp_add_custom_actions' );
function xyz_add_custom_actions() {
    add_filter( 'the_content', 'xyz_amp_add_featured_image' );
}

function xyz_amp_add_featured_image( $content ) {
    if ( has_post_thumbnail() ) {
        $image = sprintf( '<p class="xyz-featured-image">%s</p>', get_the_post_thumbnail() );
        $content = $image . $content;
    }
    return $content;
}
```

This is error -> http://overpress.it/2016/02/11/diego-piacentini-commissario-governo-digitale/amp/

**Comment by j3j5** [comment]
You are missing the `amp` on the function name, it should be `xyz_amp_add_custom_actions` and you have `xyz_add_custom_actions`.

**Comment by overpress** [comment]
Thanks for the reply :) 

Now how can I give a style the image? I would like to resize the image and put it edge to edge if possible.

See this -> 
![421235137_12678478975821115101](https://cloud.githubusercontent.com/assets/17315030/13148522/0a4be256-d65e-11e5-8eda-5d8b2af0f35c.jpg)


How can I do?
