### ISSUE TITLE
Change date format and remove tag

### ISSUE THREAD

**Issue by overpress** [Automattic/amp-wp#209]
Hi, 

how can I change the date format (removing a week ago and put, for example, 19/02/2016). I would also delete the tag. 

How can I do? Thanks :)

<img width="1403" alt="schermata 2016-02-19 alle 09 34 13" src="https://cloud.githubusercontent.com/assets/17315030/13170453/4ea13d6e-d6ec-11e5-8f4b-44e445dc9ae4.png">

**Comment by overpress** [comment]
Up

**Comment by mjangda** [comment]
Details on changing the meta section here:
https://github.com/Automattic/amp-wp/blob/master/readme.md#template-meta-author-date-etc

**Comment by overpress** [comment]
Sorry, I'm not very experienced. 

I edited the file "meta-taxonomy.php" for eliminating tags. How can I avoid that when you update the plugin you will overwrite that file?
