### ISSUE TITLE
Not rendering or removing schema for review schema

### ISSUE THREAD

**Issue by laserjobs** [Automattic/amp-wp#211]
Structured Data Testing Tool Errors
Product
name:
missing and required

reviewRating [Rating]:
Field ratingValue may not be empty.
author:
missing and required
The review has no reviewed item specified.

`<div itemtype="http://schema.org/Review" itemscope=""><div class="ta_rating_container ta_box_right"><div id="ta_rating"><div><div>Review of: <span class="title item fn" itemprop="name"><a href="http://www.amazon.com/gp/product/B015AJ6SSS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B015AJ6SSS&linkCode=as2&tag=godairyfree-20&linkId=RW3XZ5KQL6QNU24B" rel="nofollow" title="Pure Food Probiotic Plant Protein Powder" target="_blank">Pure Food Probiotic Plant Protein Powder</a></span></div><div class="clear"></div><dl><dt>Version:</dt><dd>Raw Cacao</dd><div class="clear"></div><dt>Price:</dt><dd>$39.99 per 19.2-ounce bag</dd><div class="clear"></div><div class="clear_space"></div><div class="hr"><hr></hr></div><div>Reviewed by: <span class="reviewer author byline"><span class="author" itemprop="author"></span></span></div><dl><dt>Rating:</dt><dd><div class="ta_rating result rating" itemtype="http://schema.org/Rating" itemscope="" itemprop="reviewRating"><div class="result" title="5">5</div></div></dd></dl><div class="clear"></div><div class="ta_headline_meta">On <span class="dtreviewed rating_date"><span class="published" title="February 15, 2016">February 15, 2016</span></span></div><div class="ta_headline_meta">Last modified:<span class="dtmodified rating_date" itemprop="dateModified"><span class="updated" title="February 11, 2016">February 11, 2016</span></span></div><div class="clear_space"></div><div class="hr"><hr></hr></div><h3>Summary:</h3><div class="ta_description summary" itemprop="description"><p><span>The packaging alone had me singing hallelujah! The beyond pure, organic ingredient blend is impossible to resist, and fortunately, the product delivered a good smoothie, too. We loved the very creamy consistency and thought the flavor was a solid four stars, just a touch bitter, but still pleasant in our sweet banana preparation. As an added bonus, it has less than 1 gram of sugar per serving, and contains heat-stable probiotics that will survive hot beverages and baking.</span></p></div></dl></div><div class="rating_btn"><a href="http://www.amazon.com/gp/product/B015AJ6SSS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B015AJ6SSS&linkCode=as2&tag=godairyfree-20&linkId=RW3XZ5KQL6QNU24B" itemprop="url" class="ar_button ar_blue" title="Pure Food Probiotic Plant Protein Powder" target="_blank" rel="nofollow">More Details</a></div><div class="clear"></div></div></div><div itemprop="reviewBody"><p>Labeled as a Raw Cacao “Smoothie”, Pure Food Probiotic Plant Protein Powder exceeded our expectations in both nutrition and performance.</p>
`

Original Webpage HTML
```
<div class="review"><div itemtype="http://schema.org/Product" itemscope=""><meta content="Pure Food Probiotic Plant Protein Powder" itemprop="name"><div itemtype="http://schema.org/Review" itemscope=""><div class="ta_rating_container ta_box_right" style="width:300px;"><div id="ta_rating"><div><div>Review of: <span class="title item fn" itemprop="name"><a href="http://www.amazon.com/gp/product/B015AJ6SSS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B015AJ6SSS&linkCode=as2&tag=godairyfree-20&linkId=RW3XZ5KQL6QNU24B" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://www.amazon.com/gp/product/B015AJ6SSS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B015AJ6SSS&amp;linkCode=as2&amp;tag=godairyfree-20&amp;linkId=RW3XZ5KQL6QNU24B', 'Pure Food Probiotic Plant Protein Powder');" rel="nofollow"  title="Pure Food Probiotic Plant Protein Powder" target="_blank">Pure Food Probiotic Plant Protein Powder</a></span></div><div class="clear"></div><dl><dt>Version:</dt><dd>Raw Cacao</dd><div class="clear"></div><dt>Price:</dt><dd>$39.99 per 19.2-ounce bag</dd><div class="clear"></div><div class="clear_space"></div><div class="hr"><hr /></div><div>Reviewed by: <span class="reviewer author byline"><span class="author" itemprop="author">Alisa Fleming</span></span></div><dl><dt>Rating:</dt><dd><div class="ta_rating result rating" itemtype="http://schema.org/Rating" itemscope="" itemprop="reviewRating"><meta content="1" itemprop="worstRating"><meta content="5" itemprop="ratingValue"><meta content="5" itemprop="bestRating"><div class="result" style="width:100%;" title="5">5</div></div></dd></dl><div class="clear"></div><div class="ta_headline_meta">On <span class="dtreviewed rating_date"><span class="published" title="February 15, 2016">February 15, 2016</span></span></div><div class="ta_headline_meta">Last modified:<span class="dtmodified rating_date" itemprop="dateModified"><span class="updated" title="February 11, 2016">February 11, 2016</span></span></div><div class="clear_space"></div><div class="hr"><hr /></div><h3>Summary:</h3><div class="ta_description summary" itemprop="description"><p><span>The packaging alone had me singing hallelujah! The beyond pure, organic ingredient blend is impossible to resist, and fortunately, the product delivered a good smoothie, too. We loved the very creamy consistency and thought the flavor was a solid four stars, just a touch bitter, but still pleasant in our sweet banana preparation. As an added bonus, it has less than 1 gram of sugar per serving, and contains heat-stable probiotics that will survive hot beverages and baking.</span></p></div></div><div class="rating_btn"><a href="http://www.amazon.com/gp/product/B015AJ6SSS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B015AJ6SSS&linkCode=as2&tag=godairyfree-20&linkId=RW3XZ5KQL6QNU24B" onclick="__gaTracker('send', 'event', 'outbound-article', 'http://www.amazon.com/gp/product/B015AJ6SSS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B015AJ6SSS&amp;linkCode=as2&amp;tag=godairyfree-20&amp;linkId=RW3XZ5KQL6QNU24B', 'More Details');" itemprop="url" class="ar_button ar_blue"  title="Pure Food Probiotic Plant Protein Powder" target="_blank" rel="nofollow">More Details</a></div><div class="clear"></div></div></div><div itemprop="reviewBody"><div itemtype="http://schema.org/Thing" itemscope="" itemprop="itemReviewed"><meta content="Pure Food Probiotic Plant Protein Powder" itemprop="name"></div><p>Labeled as a Raw Cacao &#8220;Smoothie&#8221;, Pure Food Probiotic Plant Protein Powder exceeded our expectations in both nutrition and performance.</p>
<p><img class="alignnone wp-image-212250 size-medium" src="http://www.godairyfree.org/wp-content/uploads/2016/02/plant-food-protein-mock-up-300x300.jpg" alt="Pure Food Probiotic Plant Protein Powder - 100% Real Food, No Junk. Dairy-free, vegan, gluten-free, soy-free." width="300" height="300" srcset="http://www.godairyfree.org/wp-content/uploads/2016/02/plant-food-protein-mock-up-150x150.jpg 150w, http://www.godairyfree.org/wp-content/uploads/2016/02/plant-food-protein-mock-up-300x300.jpg 300w, http://www.godairyfree.org/wp-content/uploads/2016/02/plant-food-protein-mock-up.jpg 709w" sizes="(max-width: 300px) 100vw, 300px" /></p>
```

**Comment by mjangda** [comment]
Looks like we're stripping `meta` tags but shouldn't be since they're mostly allowed (https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#html-tags).
