### ISSUE TITLE
Stop using LIBXML_NOEMPTYTAG

### ISSUE THREAD

**Issue by iambz** [Automattic/amp-wp#218]
Hi!

Just have a question about the utility of using `LIBXML_NOEMPTYTAG` in `AMP_DOM_Utils::get_content_from_dom`.
Basically, having it on or off doesn't affect the result on the pages I tested, except for a really annoying issue it brings: it doubles the `<br>`, by transforming a `<br/>` into `<br></br>`, that most browsers will parse as two specific `<br>`.
So yes, does it serves a real purpose here?

**Comment by mjangda** [comment]
Primarily because amp elements need closing tags and if a node doesn't have any content, DOMDocument skips the closing tag. We could probably work around it by adding an empty space (` `) as a child for any amp element nodes that don't have children.

**Comment by iambz** [comment]
Thank you for your answer, i get it now!
For now, I just used a custom template and filtered the content out of the `AMP_Content`. Easy check too for you don't often see `<br></br>`.

**Comment by StarWar** [comment]
Please visit any poetry website, they have many <br> tags inside paragraph tag and currently the behavior of amp plugin to generate closing </br> tag renders the text completely unreadable and useless. 

If you can provide steps I can follow to resolve this I would appreciate it. Thanks

**Comment by mjangda** [comment]
The easiest fix in the plugin is to switch to using `saveHTML( $node )` in `get_content_from_dom`. However, the `$node` param is only available in 5.3.6+.

Alternatively, before calling `saveXML`, we could recurse through the tree and add empty text nodes (`$dom->createTextNode( '' )`) to elements that should have closing tags.

**Comment by StarWar** [comment]
@mjangda I downloaded the zip and added it. It solves this issue. But pagefrog didn't recognize it.
Telling me to download amp plugin. What should I do to customize the look of it and also to embed adsense ads. Can provide custom template for amp?
