### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#219]
The bottom of pages feels a bit...empty. We should add some sort of footer to the default template.

**Comment by HammyHavoc** [comment]
Seems like a good choice.

**Comment by cassianotartari** [comment]
Hi @mjangda and @HammyHavoc !

How do I override/modify the content of this new footer?

My website is in ``pt_BR`` and the sentences ``Powered by WorPress`` and ``back to top`` should be translated. I didn't find a easy way to do it, is there a way as place a file in ``amp`` theme folder, like ``meta-comments-link.php``?

Thanks

**Comment by cassianotartari** [comment]
Got it, I just did the same thing, added ``footer.php`` under ``amp`` theme folder and worked like a charm.

**Comment by mjangda** [comment]
@cassianotartari if the only change you want to the footer is translations, it would be better to submit translations here: https://translate.wordpress.org/projects/wp-plugins/amp

**Comment by mjangda** [comment]
Closing this ticket as the template in 0.4 includes a footer now.

**Comment by cassianotartari** [comment]
Finished all [Development (trunk)](https://translate.wordpress.org/projects/wp-plugins/amp/dev/pt-br/default). I think this the right place for the plugin interface.
