### ISSUE TITLE
Add support for Menus

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#220]
Should we incorporate some sort of menu into the default template? Maybe a primary one if set. Or we can allow people to pick one via the Customizer?

**Comment by rudygalfi** [comment]
Can you tell us about your requirements for menus? We plan on building support soon.

cc @ericlindley-g

**Comment by westonruter** [comment]
Adding a new nav menu location that is specific to the paired mode templates would work well. It would allow for users to opt-in. The main concern would be if users have already customized the builtin templates to add their own menus, then there could be menu controls appearing twice.

See also https://github.com/Automattic/amp-wp/issues/728#issuecomment-361437541

**Comment by westonruter** [comment]
This is obsolete now that 0.7 and 1.0 encourage the use of the active theme's templates when serving AMP.

**Comment by westonruter** [comment]
Here is a basic plugin which can be used to add a nav menu sidebar on Reader mode templates: https://gist.github.com/westonruter/b22cfae13f0862d5b9716c776c60f882
