### ISSUE TITLE
Links to Prev/Next Post

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#221]
AMP posts are pretty much a dead end right now. We should see if it makes sense to provide pathways to other content.. Easiest would be to incorporate core's prev/next posts links.

**Comment by portalzine** [comment]
Just a matter of doing something like this inside a custom theme template:
`global $query_string; 
$posts = query_posts($query_string); if (have_posts()) : while (have_posts()) : the_post(); 
$next_post = get_next_post();

if (!empty( $next_post )): 
 echo '<a class="next" href="'.get_permalink( $next_post->ID ).'amp/"> &#8604; '.$next_post->post_title.'</a>';
endif; 

$prev_post = get_previous_post();

if (!empty( $prev_post )): 
 echo '<a class="next" href="'.get_permalink( $prev_post->ID ).'amp/"> &#8604; '.$prev_post->post_title.'</a>';
 endif; `

**Comment by smhmic** [comment]
If these prev/next links are AMP urls, how would they be handled by Google's AMP UI?  Do they load within the same frame?

**Comment by portalzine** [comment]
Sure, I am doing :
<a class="next" href="'.get_permalink( $next_post->ID ).'amp/">'.$next_post->post_title.'</a>

This makes sure we are staying within the AMP pages offered. Added next post link to the bottom and previous post link to the top of a post.

**Comment by westonruter** [comment]
One implementation is available here: https://github.com/Automattic/amp-wp/issues/507#issuecomment-341936843

**Comment by westonruter** [comment]
This is obsolete now that 0.7 and 1.0 encourage the use of the active theme's templates when serving AMP.
