### ISSUE TITLE
No meta description in AMP urls

### ISSUE THREAD

**Issue by Neil2305a** [Automattic/amp-wp#223]
Hi 

I notice there is no meta description in the Wordpress AMP plugin

is this deliberate?

or how to add the meta description?

**Comment by mjangda** [comment]
We use JSON/structured metadata instead.

**Comment by vijayp4you** [comment]
But semrush audit tool showing no meta description in these pages.
it is also showing no href and lang tags in amp
what about canonical thing in amp
it showing some duplicate content
