### ISSUE TITLE
After uninstall the /amp/ page still exists

### ISSUE THREAD

**Issue by amarillo** [Automattic/amp-wp#229]
I,

I have tried your plugin, but as it doesn't display images, I have removed it.

After uninstall, the amp page still exists, but is the same as the normal page: mywebsite.ext/category/article/ and mywebsite.ext/category/article/amp have the same exact content, which is now pure duplicate content.

As I didn't find a away to remove this, I have been forced to reactivate the plugin in order to get rid of this duplicate issue.

Please tell me how to remove changes made by your plugin to my installation.

Best regards,
Amar

**Comment by laserjobs** [comment]
Do you use a caching or URL find and redirect plugin installed?
Also take a note if you have a canonical URL in the header of the page source and where it points to.

**Comment by amarillo** [comment]
No, I don't use this kind of plugins.
It looks like your plugin writes something in the database, but do not delete it after uninstall.
It would be nice if you check what are the leftovers.
Best regards,
Amar

**Comment by mjangda** [comment]
We do hook into deactivate (https://github.com/Automattic/amp-wp/blob/master/amp.php#L25) but it's possible that might not be working. Will take a look.

**Comment by DoudouMoii** [comment]
Hi, 

I have same problem.

I'm using cache plugin, but i tried on another website who don't use cache, there is same problem.

I tried to add a wp_mail line 27 of amp.php (sorry im on cellphone), i get a mail when deactivate, its ok.

**Comment by jamesabruce** [comment]
@amarillo If you want to manually flush the rewrite rules after changing something, I believe you should be able go to settings -> permalinks, and just hit save.
