### ISSUE TITLE
Images in posts

### ISSUE THREAD

**Issue by amarillo** [Automattic/amp-wp#230]
Hi,

I'm not sure if this should be posted under Issues or Pull requests. Sorry.
The plugin doesn't display images, is this normal?

Here is a page rendered with your plugin, all images have gone:
[http://www.tuttifruttinews.org/formation/se-former-aux-logiciels-et-aux-langages-de-programmation-avec-video2brain/amp/](http://www.tuttifruttinews.org/formation/se-former-aux-logiciels-et-aux-langages-de-programmation-avec-video2brain/amp/)

Best regards,
Amar

**Comment by mjangda** [comment]
It looks like you're using a different AMP plugin.

**Comment by amarillo** [comment]
No, I wasn't. this his ow your amp pages look: [http://awesomescreenshot.com/0895nnv5b4](http://awesomescreenshot.com/0895nnv5b4)
As I also reported another bug, I finally decided to move to another AMP plugin.
You've closed this topic very quickly, IMHO.
