### ISSUE TITLE
Logo is missing

### ISSUE THREAD

**Issue by ThomasKujawa** [Automattic/amp-wp#248]
At https://developers.google.com/structured-data/testing-tool/ the logo is missing.

Screenshot: https://yadi.sk/i/i_LMIfLCpQKRK

How I can add this?

**Comment by mjangda** [comment]
You can either add a site icon or do it via code: https://github.com/Automattic/amp-wp/blob/master/readme.md#schemaorg-json-metadata

**Comment by ThomasKujawa** [comment]
Thank you!
Am 24.02.2016 16:01 schrieb "Mohammad Jangda" <notifications@github.com>:

**Comment by mjangda** [comment]
Happy to help :)
