### ISSUE TITLE
plugin not making compatible AMP pages

### ISSUE THREAD

**Issue by kimusan** [Automattic/amp-wp#249]
I installed the plugin (currently v0.3) but google webmaster tools tell me that the amp pages does not follow the guidelines.
It i.e. still has some script elements in the body element which is not allowed.
An example could be this:
http://www.grillkokkerier.dk/2015/06/18/paneret-valg-flaesk-lchf-style/amp/
Same page also fails with illegal attribute value (type=text/javascript, href=//fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic|Open+Sans:400,700,400italic,700italic, src=//cdn.ampproject.org/v0.js)

other errors exists as well. I through the whole idea was that the plugin took the post input in the clean form and put it into the AMP page skeleton?

**Comment by besttechie** [comment]
@kimusan yeah, I got the same message in Google Webmaster Tools. Would love to have my amp pages indexed by Google.

**Comment by mjangda** [comment]
> I through the whole idea was that the plugin took the post input in the clean form and put it into the AMP page skeleton?

@kimusan Yes, that's the goal but in your case, it looks like another plugin is modifying the output and breaking validation.

For example:

- The following javascript is being injected which is not allowed:

```
<script type="text/javascript">
//<![CDATA[
try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"be9da7c9fe203f5ba3c3dcd04e6ff0ab",petok:"56f5b86587d8fd9370d0fcb421ddc819f88e9520-1456325777-1800",zone:"grillkokkerier.dk",rocket:"a",apps:{"ga_key":{"ua":"UA-60899-8","ga_bs":"2"}},sha2test:0}];document.write('<script type="text/javascript" src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=fb690a32f5/cloudflare.min.js"><'+'\/script>');}}catch(e){};
//]]>
</script>
```

- Something is also removing the scheme from `link` and `script` URLs, which is not allowed either:

```
<link href="//fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic|Open+Sans:400,700,400italic,700italic" rel="stylesheet" type="text/css">
```

- Something is also modifying the AMP script tags and breaking those too (`data-rocketsrc` and `type` are not valid):

```
<script data-rocketsrc="//cdn.ampproject.org/v0.js" async type="text/rocketscript"></script>
```

**Comment by mjangda** [comment]
Looks like it might the Cloudflare Rocket Loader plugin? https://wordpress.org/support/topic/amp-validation-had-errors-1?replies=8

**Comment by kimusan** [comment]
yes indeed. I have now disabled cloudflare functionality for */amp/ and it seems to work much better.

**Comment by mjangda** [comment]
Great!
