### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by wannaphongcom** [Automattic/amp-wp#250]
I have install of WP 4.4.2 with the AMP 0.3.1 plugin installed and using the default Twenty Fiftee theme. I see post with /amp or ?amp=1 nothing is returned and https://github.com/Automattic/amp-wp/archive/master.zip. it not works.
[https://python3.wannaphong.com/2016/01/variable-variables-ในภาษา-python.html/amp/](https://python3.wannaphong.com/2016/01/variable-variables-ในภาษา-python.html/amp/)

**Comment by mjangda** [comment]
Can you please check to see if there are any errors in your PHP error log?

**Comment by wannaphongcom** [comment]
I not see PHP error log.

**Comment by wannaphongcom** [comment]
I am using Red Hat's Openshift online.

**Comment by wannaphongcom** [comment]
I add define('WP_DEBUG_LOG', true);
https://python3.wannaphong.com/2016/01/variable-variables-ในภาษา-python.html/amp

**Comment by kjy112** [comment]
CloudFlare seems to cause issues as of now:

> The following plugins have been known to cause issues with this plugin:
> 
> Cloudflare (Rocket Loader; modifies the output of the AMP page, which breaks validation.)

**Comment by wannaphongcom** [comment]
https://wordpress.org/support/topic/amp-plugin-installed-but-posts-with-amp-are-blank

**Comment by wannaphongcom** [comment]
Now , it working. :+1:
