### ISSUE TITLE
Windows Hosting path issue

### ISSUE THREAD

**Issue by jakeburkart** [Automattic/amp-wp#251]
I am testing on a Windows Server 2008R2.  See the error at: http://wordpress.ecomenterprises.com/python-javascript/amp/
 I get this error:

> Notice:  AMP_Post_Template::verify_and_include was called incorrectly. Path validation for template (C:\wordpress.ecomenterprises.com\wp-content\plugins\amp/templates/single.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in C:\wordpress.ecomenterprises.com\wp-includes\functions.php on line 3792

**Comment by mjangda** [comment]
Removed the broken path validation in #263
