### ISSUE TITLE
AMP-WP Validation Issues

### ISSUE THREAD

**Issue by besttechie** [Automattic/amp-wp#252]
Hey,

I'm having some issues with validation on my site. I'm including the error below (it's the same on all AMP pages). Any help would be greatly appreciated.

Here's an example article: https://www.besttechie.com/turbocharge-your-productivity-with-these-apps/amp/#development=1

![screen shot 2016-02-24 at 2 07 39 pm](https://cloud.githubusercontent.com/assets/1079069/13297402/38c7a664-db00-11e5-8bae-3ccfca3fcd56.png)

**Comment by mjangda** [comment]
Looks like WP Rocket might be injecting some extra javascript and modifying the output of the page. If it's possible I'd suggest disabling it for AMP pages.

**Comment by besttechie** [comment]
@mjangda that's what I thought too. According to the WP-Rocket documentation I can use a regex to exclude pages from being cached, would you be able to help me with the proper regex?

**Comment by mjangda** [comment]
Probably something like this: `/(.*)/amp/?$`

**Comment by mjangda** [comment]
Or actually, `/(.*)/amp/?` (to avoid issues if the URL has a querystring).

**Comment by besttechie** [comment]
Hmm, didn't work. I just disabled WP-Rocket too as a way to double check and I'm still having errors. Any other ideas?

**Comment by mjangda** [comment]
Might be a different plugin then? This is the script being injected:

```
<script type="text/javascript">
//<![CDATA[
try{(function(a){var b="https://",c="www.besttechie.com",d="/cdn-cgi/cl/",e="img.gif",f=new a;f.src=[b,c,d,e].join("")})(Image)}catch(e){}
//]]>
</script>
```

**Comment by besttechie** [comment]
I just went through and disabled a bunch, nothing. I have no idea what that could be from either. It's nothing that seems familiar to me.

**Comment by mjangda** [comment]
Looks like it might be CloudFlare? http://stackoverflow.com/questions/29672254/unknown-img-gif-cloudflare

**Comment by besttechie** [comment]
GOT IT! Thanks! :) :+1: 

Looks like everything is validated now. I had to move my new page rule in CF up to the top.

**Comment by mjangda** [comment]
Great!
