### ISSUE TITLE
The attribute 'align' may not appear in tag 'div'.

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#253]
Not allowed in other elements either so we should probably strip it out.

**Comment by kienstra** [comment]
*Align Is Now An Allowed Attribute*

It looks like since this issue was opened, `align` [was added](https://github.com/ampproject/amphtml/commit/145a033e0c0f5ddeabf8afa7183553e454de6a5e#diff-695a0119f06368dee3ab53e1395ef725R2586) as an allowed attribute of `<div>`.
