### ISSUE TITLE
Blank page on local WAMP setup.

### ISSUE THREAD

**Issue by w33zy** [Automattic/amp-wp#255]
Re: https://github.com/Automattic/amp-wp/issues/149

I am running v0.3.1 on a local WAMP setup and I am getting blank pages when I bring up AMP posts. The PHP error local provides

`[24-Feb-2016 20:50:39 UTC] PHP Notice:  AMP_Post_Template::verify_and_include was called <strong>incorrectly</strong>. Path validation for template (C:\wamp\www\hs.dev\wp-content\plugins\amp/templates/single.php) failed. Path cannot traverse and must be located in WP_CONTENT_DIR. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 0.1.) in C:\wamp\www\hs.dev\wp-includes\functions.php on line 3792`

**Comment by w33zy** [comment]
After further investigation it seems the the ````is_valid_template```` function is failing on the ````validate_file```` condition because the template path contains a colon (:).

The patch added in issue https://github.com/Automattic/amp-wp/issues/149 works so this a new bug in the ````validate_file```` function.

**Comment by mjangda** [comment]
Ah, thanks for tracking that down! We may need to rethink how the file validation works.

**Comment by w33zy** [comment]
Yeah, that ````validate_file```` function seems a bit odd, considering it will always fail in a Windows env. because a colon is always used in file paths.

Now I am off to see if WordPress core validates files and how it handles that function. That may be the solution.

**Comment by trucle** [comment]
+1

**Comment by leecollings** [comment]
I'd like to follow this issue, as I posted the same issue on the Wordpress plugin page. Are there any immediate changes to the files that can be made to resolve it, or are we waiting for a plugin update?

**Comment by gcphost** [comment]
+!

**Comment by espellcaste** [comment]
I tested with @mjangda changes and the error was removed.

**Comment by w33zy** [comment]
I haven't tested this fix but from my understanding of the ````validate_file```` function this fix will work.
