### ISSUE TITLE
Ads on AMP pages

### ISSUE THREAD

**Issue by kkranzo** [Automattic/amp-wp#257]
Where do we specify which ad to use for AMP versions of posts?

**Comment by mjangda** [comment]
See https://github.com/Automattic/amp-wp#custom-sanitizer for an example

**Comment by RobertShippey** [comment]
I get the following warning using the sanitiser code. 

> The tag 'amp-ad extension .js script' is missing or incorrect, but required by 'amp-ad'. This will soon be an error. (see https://www.ampproject.org/docs/reference/amp-ad.html)

How would I go about including the script it suggests through the sanitiser?
