### ISSUE TITLE
Filter template instead of rendering on `template_redirect`

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/amp-wp#26]
See https://markjaquith.wordpress.com/2014/02/19/template_redirect-is-not-for-loading-templates/

**Comment by mjangda** [comment]
So this was somewhat conscious choice. There's a very low chance that anything else should be running on `template_redirect` when our query var is set plus, we avoid all other the unnecessary checks in template-loader.

But in the interest of being a good citizen, we should change the hook to `template_include` instead.

**Comment by mjangda** [comment]
Discussion on this here: https://github.com/Automattic/amp-wp/issues/412#issuecomment-240871878

**Comment by danielbachhuber** [comment]
Fair enough.
