### ISSUE TITLE
Analytics Component Not Being Added

### ISSUE THREAD

**Issue by kkranzo** [Automattic/amp-wp#264]
I have used the below method to make sure the analytics component is added to my AMP pages, however it is not being added and I am still receiving the error that it is not loaded in the AMP validation tool.

```
add_action( 'amp_post_template_data', 'amp_post_template_add_analytics_script' );
function amp_post_template_add_analytics_script( $data ) {
	if ( ! empty( $data['amp_analytics'] ) ) {
	$data['amp_component_scripts']['amp-analytics'] = 'https://cdn.ampproject.org/v0/amp-analytics-0.1.js';
	}
	return $data;
}
```
Is there something else I need to add?

**Comment by mjangda** [comment]
You need to use the development version to use this new filter (https://github.com/Automattic/amp-wp/archive/master.zip). It will be pushed out with the next release.

**Comment by CybMeta** [comment]
Has this component been added to version 0.3.2 realeased today? I'm trying to use `amp_post_template_analytics` filter; I can see the amp-analytics script beeing added to the head but nohting about the analytics template generated in the `amp_post_template_analytics` filter.

**Comment by CybMeta** [comment]
I get it working. The arguments `type`, `attributes` and `config_data` are required. I have not `attributes` arguments, so I had to set it to empty array.
