### ISSUE TITLE
Error in schema.org NewsArticle

### ISSUE THREAD

**Issue by OPPtester** [Automattic/amp-wp#265]
Getting errors in Google WMT saying:

1- Fix the NewsArticle structured data element in your page
Review the documentation for the relevant structured data element.

**I thought the NewArticle markup is covered** http://schema.org/NewsArticle

2- Verify structured data element
Open the structured data testing tool and verify that no errors exist for this page.

This one returns all good not sure why Google is still complaining?

**Comment by OPPtester** [comment]
Although this was last detected on 2/23/2016 according to WMT's. The post actually did not have a featured image until yesterday so maybe the above complain is about the required image?

**Comment by mjangda** [comment]
Possibly. You can test your AMP content for schema validation errors using this tool: developers.google.com/structured-data/testing-tool/

**Comment by OPPtester** [comment]
Yeah, the tool comes back with all good so I guess it's the image that was not there. I think Google needs to ease up a bit on the image requirement, there's going to be posts without images for one reason or another.

**Comment by laserjobs** [comment]
Just and FYI. I got the same error with a post that did not have a image.

**Comment by mjangda** [comment]
The image issue is being tracked in #236
