### ISSUE TITLE
Support YouTube iframes

### ISSUE THREAD

**Issue by jcascon** [Automattic/amp-wp#266]
Hi

With the plugin amp-wp version 0.4 youtube don´t work with amp-youtube. For example

`<iframe width="480" height="300" src="http://www.youtube.com/embed/jROPmvI37kA"></iframe>`

transform to 

 `<amp-iframe width="480" height="300" src="https://www.youtube.com/embed/jROPmvI37kA" frameborder="0" allowfullscreen="" sandbox="allow-scripts allow-same-origin" sizes="(min-width: 480px) 480px, 100vw" class="amp-wp-enforced-sizes"><div placeholder="" class="amp-wp-iframe-placeholder"></div></amp-iframe>`

but not width `<amp-youtube>` tag

**Comment by mjangda** [comment]
`amp-youtube` is currently only generated for the YouTube oEmbed and shortcodes. We could look at adding support for `iframe` as well.

**Comment by OPPtester** [comment]
If this helps in enhancing:

In WMT tools got "Unkown syntax errors:	amp-youtube extension .js script required by amp-youtube"

In dev. mode in Chrome, validation error: 
The 'amp-youtube extension .js script' tag is missing or incorrect, but required by 'amp-youtube'.

The actual line in teh AMP page source is:
<amp-youtube data-videoid="MTL1IXTDH30" layout="responsive" width="600" height="480"></amp-youtube>

Regards,
