### ISSUE TITLE
Adjust default size for carousel

### ISSUE THREAD

**Issue by tobaco** [Automattic/amp-wp#270]
Hi,

is there a way to adjust the default sizes for the amp-carousel?

they seem to be defined here: [class-amp-base-embed-handler.php](https://github.com/Automattic/amp-wp/blob/4ab6503aca69613e2d2cc22719adad1a568a45ac/includes/embeds/class-amp-base-embed-handler.php#L7) 

But i can't finde a way to adjust these values.

Thanks!

**Comment by mjangda** [comment]
You can work with the same snippet I shared in https://github.com/Automattic/amp-wp/issues/261 except update the width and height for `AMP_Gallery_Embed_Handler` instead.

**Comment by tobaco** [comment]
oh, i tried, but it didn't work. guess it was to late for me yesterday. :blush: 
i'll try again and sorry for bothering you. :-)
