### ISSUE TITLE
Main AMP script should be last element in <head>

### ISSUE THREAD

**Issue by smhmic** [Automattic/amp-wp#273]
Plugin does not adhere to this part of the [spec](https://www.ampproject.org/docs/get_started/create/basic_markup.html#required-mark-up):

> AMP HTML documents MUST ... Contain a `<script async src="https://cdn.ampproject.org/v0.js"></script>` tag as the last element in their head (this includes and loads the AMP JS library).

This plugin generates a few tags after the main AMP script.  Anyone know the impact of this?

**Comment by mjangda** [comment]
We haven't seen any issues yet, so I'm not sure if that particular requirement is being enforced.
