### ISSUE TITLE
Plugin missing required amp-boilerplate style

### ISSUE THREAD

**Issue by smhmic** [Automattic/amp-wp#274]
Plugin does not adhere to this part of the [spec](https://www.ampproject.org/docs/get_started/create/basic_markup.html#required-mark-up):

> Contain the following in their `<head>` tag: `<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>`

Instead, this plugin includes: `<style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>` but that seems to have a different purpose.

**Comment by mjangda** [comment]
> Instead, this plugin includes: `<style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>` but that seems to have a different purpose.

That's an earlier version of the boilerplate. Both are valid although we updated to the new boilerplate in d27b04f158c023f23cacfb308a9954294e70b1e2 and was released with 0.3.1.
