### ISSUE TITLE
488 Errors in Search Console

### ISSUE THREAD

**Issue by ThomasKujawa** [Automattic/amp-wp#275]
perhaps http://go.shr.lc/1UpkHCd / http://go.shr.lc/1UplB1H / 

boilerplate (js enabled) is missing

how can i fix it?

I use https://github.com/automattic/amp-wp and https://wordpress.org/plugins/glue-for-yoast-seo-amp/

**Comment by mjangda** [comment]
Most likely due to the `autoptimize` plugin.

**Comment by ThomasKujawa** [comment]
Thank you.

**Comment by lkraav** [comment]
Yes, I also ran into trouble when `plugins/comet-cache-pro` was compressing inline `style`/`script` tags into bundles, unrecognizable to the validator.
