### ISSUE TITLE
Validation warning: Image resolution incorrect value

### ISSUE THREAD

**Issue by tchibomann** [Automattic/amp-wp#277]
I got a warning in Googles AMP validator ([link](https://developers.google.com/structured-data/testing-tool/)), that the values from the featured image or post image are incorrect. I modified the file class-amp-post-template.php  at line 230/231 as followed:

```
		if ( is_array( $post_image_src ) ) {
			$post_image_meta = array(
				'@type' => 'ImageObject',
				'url' => $post_image_src[0],
				'width' => $post_image_src[1]."px",
				'height' => $post_image_src[2]."px",
			);
		}
```

And the warning is gone. I don't know if this is the best solution, but I got the message from Google, that AMP pages with errors are not shown to the public, I even got this message with only THIS one warning.

So maybe this has to be fixed.

**Comment by mjangda** [comment]
The warning is likely because the image dimensions don't meet the guideline ("Images should be at least 696 pixels wide").
