### ISSUE TITLE
Prohibited tags: font

### ISSUE THREAD

**Issue by laserjobs** [Automattic/amp-wp#279]
Not sure if this should be stripped or just corrected in the posts as it shouldn't be there in the first place?

**Comment by mjangda** [comment]
The `font` element was deprecated a long time ago (HTML 4; https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font); I'd suggest not using it anymore.

**Comment by laserjobs** [comment]
Yeah I had a bunch of very old imported posts that need reformatting. Should not have reported this since it was depreciated a long time ago. Closed and thanks.

**Comment by mjangda** [comment]
Not a problem. Thanks for reporting it just in case!
