### ISSUE TITLE
Faux bold and italics in Merriweather text

### ISSUE THREAD

**Issue by mattmiklic** [Automattic/amp-wp#28]
This is the request we're making to Google Fonts:
`https://fonts.googleapis.com/css?family=Merriweather|Open+Sans:400,700,400italic,700italic`
https://github.com/Automattic/amp-wp/blob/master/template.php#L8

I believe we meant to call the 700 weight and italic styles of Merriweather, not Open Sans. I'm seeing faux bold and faux italic when I view an AMP page in a mobile browser.

![img_0059](https://cloud.githubusercontent.com/assets/1396552/10342930/74b6de4a-6ce9-11e5-8bb7-a85f1f36ccb3.PNG)

**Comment by mjangda** [comment]
cc @jasmussen

**Comment by jasmussen** [comment]
Good catch! Fixed.
