### ISSUE TITLE
Google AMP Error with WP Lightbox 2 Plugin

### ISSUE THREAD

**Issue by isaumya** [Automattic/amp-wp#282]
Hi,
I'm not entirely sure whats causing the issues but today I've received an email from Google Console mentioning there are certain issues with some of my AMP Pages. When I looked into it I saw all the pages Google have flagged has some images inside the article.

More over I use [WP Lightbox 2 Plugin](https://wordpress.org/plugins/wp-lightbox-2/) written by [Syed Balkhi](https://profiles.wordpress.org/smub/) and the tag that Google is flagging with error is `rel=lightbox[5020]`. Now I know this rel tag gets added by [WP Lightbox 2 Plugin](https://github.com/wp-plugins/wp-lightbox-2/tree/d776d1c379cf7bae05253404526144844ca1f50c) but I'm not entirely sure whether this is something that needs to be patched on AMP plugin's end or [WP Lightbox 2 Plugin](https://wordpress.org/plugins/wp-lightbox-2/)'s end.

So, I thought it is better to post it here so that everyone can work collaboratively to fix the issue. Here is a screenshot of Google Console Page showing the errors:
![2016-02-29_14-07-49](https://cloud.githubusercontent.com/assets/2124755/13389571/139ba956-deef-11e5-8ede-15a78b1a50f3.jpg)

Moreover here are some of my article link that Google has flagged:

- https://www.isaumya.com/where-to-get-cheap-domain-registration/amp/

- https://www.isaumya.com/boost-your-seo-by-400-with-microdata/amp/

- https://www.isaumya.com/why-you-should-prefer-using-genesis-over-other-themes/amp/

- https://www.isaumya.com/increase-internet-download-speed/amp/

- https://www.isaumya.com/adblock-alternative-content-disable-adsense-account/amp/

- https://www.isaumya.com/access-blocked-websites-isp/amp/

Looking forward to a fix or a snippet of code that can disable this rel thing on the AMP pages or some helpful replies on this matter.

**Comment by portalzine** [comment]
The custom rel attribute is not supported by the AMP spec, only those registered on microformat (http://microformats.org/wiki/existing-rel-values). I created a custom template and cleaned them out of the content for my AMP pages.

**Comment by isaumya** [comment]
can you please share your template so that I can have a look about how to do it.... I was hoping if there is some snippet to remove the rel tas automatically for the amp pages.

**Comment by portalzine** [comment]
Currently summarizing some tweaks here: https://www.portalzine.de/dev/css/amp-wp-tweaks-tips/

**Comment by isaumya** [comment]
Thanks for the code. But do you want us to put 

```
 require('your-libs/phpQuery/phpQuery.php');
 $doc = phpQuery::newDocumentHTML($this->get( 'post_amp_content' )); 
 $doc['.prettyphoto']->removeAttr("rel")->removeAttr("href");
 $doc['*']->removeAttr("align");
 $doc['a[target="new"]']->attr("target","_blank");
 echo  $doc->html(); // amphtml content; no kses
```
 
in the `functions.php` file or custom created template?

**Comment by portalzine** [comment]
This is just a quick fix for now and changes the amp-content output in the custom template.

**Comment by isaumya** [comment]
yah! but do you want me to add them into my child theme's functions.php file pr
where? You haven't mentioned that in your article.

On Mon, Feb 29, 2016 at 8:15 PM Alexander Graef <notifications@github.com>
wrote:
This is just a quick fix for now and changes the amp-content output in the
custom template.

—
Reply to this email directly or view it on GitHub .


Sincerely,
Saumya Majumder
Engineer, Author & Tech Reviewer

Web: www.isaumya.com
Email: mailme@isaumya.com

Confidentiality Notice: The information contained in this email and any accompanying attachment(s) is
intended only for the use of the intended recipient and may be confidential
and/or privileged. If any reader of this communication is not the intended
recipient, unauthorized use, disclosure or copying is strictly prohibited, and
may be unlawful. If you have received this communication in error, please
immediately notify the sender by return email, and delete the original message
and all copies from your system. Thank you.

**Comment by portalzine** [comment]
That is why I referenced the AMP-WP documentation ... https://github.com/Automattic/amp-wp/blob/master/readme.md#custom-template

**Comment by mjangda** [comment]
Dupe #100
