### ISSUE TITLE
Missing Closing Tag

### ISSUE THREAD

**Issue by pakpenyo** [Automattic/amp-wp#284]
I'm using AMP Plugin with Pagefrog.

This is in my html head 

`<link rel="amphtml" href="http://sample.dev/2016/link-to-single-posts/amp/" /`

The `>` is missing at latest Chrome and FF.

**Comment by mjangda** [comment]
We're properly printing the `link` tag here (https://github.com/Automattic/amp-wp/blob/master/includes/amp-frontend-actions.php#L12) so something else might be interfering.

**Comment by pakpenyo** [comment]
Ah yes.... It's my false. I'm using function to trying cleanup indent at wp_head.

`if ( ! function_exists( 'print_indented' ) ) {
	function print_indented( $fn ) {
		ob_start();
		call_user_func( $fn );
		$html = ob_get_contents();
		ob_end_clean();
		echo preg_replace( "/\n/", "\n\t", substr( $html, 0, - 1 ) );
		echo "\n";
	}
}`

Disable it and it's working now.
Btw, that's function works fine with yoast-seo.
