### ISSUE TITLE
404 issues on 'https://cdn.ampproject.org/v0.js'%20defer%20onload='

### ISSUE THREAD

**Issue by jamessinc** [Automattic/amp-wp#285]
I installed AMP-WP for tradefinanceglobal.com and am getting an error when validating using #developer=1 and looking on Google's Dev Console Tool:  Failed to load resource: the server responded with a status of 404 (Not Found).

E.g. https://www.tradefinanceglobal.com/posts/tfg-announces-winners-of-the-currency-awards-for-excellence/amp/#developer=1

I'm not sure what's gone wrong. I've tried deactivating my W3-total cache plugin, reinstalling Amp-wp but I seem to get the same errors. Google Search Console is also reporting a load of errors on my Amp pages:

1	Required tag missing	8
2	Invalid attribute value	8
3	Incorrectly nested tag	5
4	Required attribute missing	5
5	Unknown syntax error	2
6	Prohibited attribute	1

Any ideas?

Cheers

**Comment by portalzine** [comment]
Seems like something is injecting  "defer onload=" into your script src attribute. Not using W3 cache myself , but might be related to that.

**Comment by mjangda** [comment]
Yep, it's likely due to another plugin modifying the AMP output.
