### ISSUE TITLE
Wordpress post embeds fail "wp-embedded-content"

### ISSUE THREAD

**Issue by laserjobs** [Automattic/amp-wp#288]
Posts with Wordpress Embeds fail and give a error of "Unkown syntax errors" in the Search Console. 
`Unkown syntax errors:	src=http://www.godairyfree.org/recipes/smores-ice-cream-sandwiches/embed#?secret=xxxxxxxx`

webpage code:
```
<p><iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" style="display:none;" src="http://www.godairyfree.org/recipes/smores-ice-cream-sandwiches/embed#?secret=xxxxxx" data-secret="xxxxxxxxx" width="600" height="338" title="Embedded WordPress Post" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></p>
```

AMP code:

```
<amp-iframe class="wp-embedded-content amp-wp-enforced-sizes" sandbox="allow-scripts" src="http://www.godairyfree.org/recipes/smores-ice-cream-sandwiches/embed#?secret=xxxxxxx" width="600" height="338" frameborder="0" sizes="(min-width: 600px) 600px, 100vw"><div placeholder="" class="amp-wp-iframe-placeholder"></div></amp-iframe>
```

**Comment by laserjobs** [comment]
here is a link of the problem:
http://www.godairyfree.org/news/dairy-free-super-bowl-recipes/amp

**Comment by laserjobs** [comment]
How can we get around not using https?
https://www.ampproject.org/docs/guides/amp_replacements.html#display-an-iframe

**Comment by mjangda** [comment]
In terms of rendering it, there's not much we can do since `https` is a strict requirement for AMP

We could, however, include a `fallback` element that has a link to the embed though.

**Comment by laserjobs** [comment]
So it looks like it would validate with SSL but I am sure like myself there is many not using https

https://www.godairyfree.org/recipes/smores-ice-cream-sandwiches/embed#?secret=xxxxxxxxxxxFailed to load resource: net::ERR_SSL_PROTOCOL_ERROR

amp-iframe-0.1.max.js:264 GET https://www.godairyfree.org/recipes/healthy-vegan-queso-dip/embed net::ERR_SSL_PROTOCOL_ERRORZ.layoutCallback @ amp-iframe-0.1.max.js:264b.layoutCallback @ custom-element.js:732V.startLayout @ resources-impl.js:1685U.work_ @ resources-impl.js:986U.doPass_ @ resources-impl.js:596(anonymous function) @ resources-impl.js:122(anonymous function) @ pass.js:90

**Comment by mjangda** [comment]
Fallback covered under #354
