### ISSUE TITLE
rel=stylesheet reported as invalid attribute

### ISSUE THREAD

**Issue by meisterwerkmedien** [Automattic/amp-wp#291]
Hi there, 

Google Search Console reported to me that rel="Stylesheet" was an invalid attribute and won't index the posts. It is used by the link tag that the plugin uses to load Googles web fonts for the default amp layout.

`<link href="https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic|Open+Sans:400,700,400italic,700italic" rel="stylesheet" type="text/css">`

Btw, is there any way to remove this automatically created link tag? Because in most cases, when you adapt the layout to your website's style, it becomes superfluous anyway.

Best regards, Alexander

**Comment by mjangda** [comment]
The link tag the plugin was including is very similar to the <a href="https://github.com/ampproject/amphtml/blob/1516f70541ada97ed30b9f765b6199ed2017cbf9/test/manual/amp-img.amp.html#L8">standard AMP examples</a> (with `rel=stylesheet` and all) so the issue may have been something else.

>  is there any way to remove this automatically created link tag?

Agreed. We just moved the font definition to `style.css` instead, so hopefully that works.

**Comment by portalzine** [comment]
I am not  getting any errors from these. The spec allows custom font includes, as long they link to https://fast.fonts.net or https://fonts.googleapis.com

**Comment by meisterwerkmedien** [comment]
It seems the issue resolved itself. There is no further error notice, so it was probably just a Google hiccup. Sorry for bothering, though.
