### ISSUE TITLE
Support for Jetpack Sharing

### ISSUE THREAD

**Issue by kraftbj** [Automattic/amp-wp#293]
An AMP plugin ticket for tracking Automattic/jetpack#3354 and Automattic/jetpack#3483. Personally, I'm leaning toward adding support in this plugin, like what's done with stats.

**Comment by mjangda** [comment]
The amp-social-share extension can be used here: https://www.ampproject.org/docs/reference/extended/amp-social-share.html

**Comment by amedina** [comment]
Closing this; the suggested approach is to add this support on Jetpack's side.
