### ISSUE TITLE
Access custom fields in templates

### ISSUE THREAD

**Issue by kkranzo** [Automattic/amp-wp#294]
How would I access custom fields in templates?

I have a custom field for each user that is their author photo. I am trying to use that instead of the Gravatar setup.

Here is the code I have in my meta-author.php file in the /amp directory in my theme. However, this is not working.

```
<li class="amp-wp-byline">
    <?php
	$post_author = $this->get( 'post_author' );
	$author_icon = get_the_author_meta('author_photo');
	$author_image_src = wp_get_attachment_image_src($author_icon, 'full');
	?>
	<amp-img src="<?php echo $author_image_src[0]; ?>" width="24" height="24" layout="fixed"></amp-img>
	<span class="amp-wp-author"><?php echo esc_html( $post_author->display_name ); ?></span>
</li>
```

**Comment by mjangda** [comment]
You need to pass the author's id into `get_the_author_meta`:

```
$author_icon = get_the_author_meta( 'author_photo', $post_author->ID );
```

Alternatively, you could just filter `pre_get_avatar_data` (see <a href="https://developer.wordpress.org/reference/functions/get_avatar_data/">get_avatar_url</a>) and return the URL and it'll just work as expected without needing the custom template.

**Comment by OtherF** [comment]
@mjangda 
Could you please show how to filter ```pre_get_avatar_data```?
I couldn't get what code should I add to functions.php
