### ISSUE TITLE
 i don´t see the <link rel="amphtml" ... tag in the source of posts

### ISSUE THREAD

**Issue by emaurin** [Automattic/amp-wp#296]
template loadeither when I append /amp/, but i don´t see the <link rel="amphtml" ... tag in the source of posts
http://www.venezuelasinfonica.com/la-sinfonica-municipal-ofrecio-elfinde/amp
http://www.venezuelasinfonica.com/la-sinfonica-municipal-ofrecio-elfinde

**Comment by mjangda** [comment]
It's there in the source for the second URL, although, looks like it's using a shortlink (which might be because another plugin is filtering the permalink)?

```
<link rel="amphtml" href="http://vzls.net/1WTh0DA/amp" />
```

**Comment by emaurin** [comment]
yes, bitly Plugin, 
I will keep my short url for another time. Thank you
