### ISSUE TITLE
Error in Google Search Console

### ISSUE THREAD

**Issue by overpress** [Automattic/amp-wp#298]
Hi, the Google Search Console tells me these errors. 

1. Missing required tag: amphtml engine v0.js script

2. Values of attributes that are not validi: src=//cdn.ampproject.org/v0.js, href=//fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic|Open+Sans:400,700,400italic,700italic, src=//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

3. Attributes are not allowed: rel, style

What should I do?

**Comment by mjangda** [comment]
The most common source of these types of issues have been other plugins (CloudFlare, WP Rocket, Autooptimize) modifying the AMP output. Make sure you're on the latest version of these plugin (if you're using them) and that you disabled them for AMP content.

**Comment by overpress** [comment]
Yes, I'm using the latest version. Of the plugins you mentioned we only use CloudFlare. How can I disable it on AMP?
