### ISSUE TITLE
Link attributes nofollow,noreferrer not handled

### ISSUE THREAD

**Issue by tom1410** [Automattic/amp-wp#299]
It looks like links having attributes rel=nofollow,noreferrer are not AMP-valid. Google webmaster tool indicates those values can't be set to links for AMP pages. 

Perhaps link attributes should be removed when the WP post is AMP-fied?

**Comment by kkranzo** [comment]
I also noticed that target="_top" is not AMP-valid as well.

**Comment by tom1410** [comment]
This issue comes from the preg_replace that does nothing here:

`private function sanitize_a_attribute( $node, $attribute ) {
		$attribute_name = strtolower( $attribute->name );

		if ( 'rel' === $attribute_name ) {
			$old_value = $attribute->value;
			**$new_value = trim( preg_replace( self::PATTERN_REL_WP_ATTACHMENT, '', $old_value ) );**
			if ( empty( $new_value ) ) {
				$node->removeAttribute( $attribute_name );
			} elseif ( $old_value !== $new_value ) {
				$node->setAttribute( $attribute_name, $new_value );
			}

			echo $new_value;
			//echo $attribute->value;
		} elseif ( 'rev' === $attribute_name ) {
			// rev removed from HTML5 spec, which was used by Jetpack Markdown.
			$node->removeAttribute( $attribute_name );
		} elseif ( 'target' === $attribute_name && '_new' === $attribute->value ) {
			// _new is not allowed; swap with _blank
			$node->setAttribute( $attribute_name, '_blank' );
		}
	}`

**Comment by mjangda** [comment]
The `rel` values should have spaces between them, not commas.

This validates:

```
<a rel="nofollow noreferrer">Howdy</a>
```

This does not:

```
<a rel="nofollow,noreferrer">Howdy</a>
```
