### ISSUE TITLE
Attributes without values not supported by DOMElement and causing validation errors

### ISSUE THREAD

**Issue by bcampeau** [Automattic/amp-wp#301]
I'm getting validation errors for amp-video (and there are probably other examples) because the following attributes aren't supposed to have values:

controls
autoplay
loop
muted

AMP is expecting them to appear like:

`<amp-video controls autoplay loop mute>`

Where the plugin currently outputs

`<amp-video controls="true" autoplay="true" loop="true" mute="true">`

As far as I know, `DOMElement` won't allow you to add an attribute with no value, so this is a really tough one to solve.

**Comment by bcampeau** [comment]
You could really argue this could be on Google as I'd expect `controls` and `controls="true"` to both be valid, but it's clearly not set up that way in the spec.

**Comment by mjangda** [comment]
I can't remember why we defaulted the value to `true`. Will just default them to empty values.

**Comment by bcampeau** [comment]
I tried that in testing and it appears that DOMElement makes it an empty quoted value rather than no value at all which I think is still invalid.

**Comment by mjangda** [comment]
Empty values validate in my tests. If not, that's definitely an AMP bug as the HTML spec allows for empty values: https://www.w3.org/wiki/HTML/Elements/video

**Comment by bcampeau** [comment]
My bad. Works for me!
