### ISSUE TITLE
HTML tags in titles

### ISSUE THREAD

**Issue by nicolinuxfr** [Automattic/amp-wp#304]
On my blog, I use some HTML in my titles, mainly to italicize what need to be italicized (titles of movies, books…). 

But on the AMP version, I see the HTML tags in the titles, instead of what I expected : either the raw text, without markup, or (better), the HTML output, like on the regular version. 

Here is an example : 

![capture d ecran 2016-03-03 a 12 20 47](https://cloud.githubusercontent.com/assets/2078386/13492786/69413e50-e13a-11e5-84e2-70360012f57a.png)

And the links : 

- Original : https://voiretmanger.fr/where-is-my-mind/
- AMP version : https://voiretmanger.fr/where-is-my-mind/amp

**Comment by mjangda** [comment]
Thanks for the report!
