### ISSUE TITLE
PHP 5.2 Compat

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#31]
Some PHP5.3+isms have snuck in and we need to remove them.

**Comment by cfinke** [comment]
The first one I noticed is the use of late static bindings in class-amp-kses.php: `static::$allowed_html` and `static::$allowed_protocols`. I think both can be changed to `self::` instead of `static::` without any ill effects.

**Comment by mjangda** [comment]
Should be fine now.

**Comment by cfinke** [comment]
Confirmed; running amp-wp on PHP 5.2.17 on chrisfinke.com with no issues so far.
