### ISSUE TITLE
Connection refused: localhost favicon.ico

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/amp-wp#312]
Ticket: 2570586-t
Chat: 326565-chat

User is receiving emails from Google stating there are errors with the AMP pages on her site. I followed the troubleshooting steps, and received an error attempting to load this page:

http://thewhistlingelk.com/2013/11/19/make-an-entrance-with-paint-couture/amp/#development=1

The error, which flashes quickly, is:

`GET http://localhost/favicon.ico net::ERR_CONNECTION_REFUSED`

You can see this in my screencast at the 5sec mark: http://recordit.co/1BUU1d9uZc

**Comment by jery61007** [comment]
That content doesn't even exist on the site....  I get 404

**Comment by mjangda** [comment]
Fixed the broken URL.

**Comment by mjangda** [comment]
The hotlinked images in the post are causing the errors since they no longer resolve correctly.
