### ISSUE TITLE
Validation error 'amp-iframe extension .js script'

### ISSUE THREAD

**Issue by OPPtester** [Automattic/amp-wp#315]
Seems I'm missing something here, the youtube embedded in the WP post does not show/play:

http://www.opptrends.com/2016/03/apple-supprt-now-available-twitter/amp/:297:7 ****The tag 'amp-iframe extension .js script' is missing or incorrect, but required by 'amp-iframe'.** (see **https://www.ampproject.org/docs/reference/extended/amp-iframe.html)Ex.error @ cdn.ampproject.org/v0/validator.js:330
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://3p.ampproject.net') does not match the recipient window's origin ('http://www.opptrends.com').

**Comment by OPPtester** [comment]
Fixed by adding this to my custom-single.php:

<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>

I can see the video now, but not sure if this solution is ideal I thought the plugin would insert that anyway!

**Comment by OPPtester** [comment]
Just wanted to know if the AMP plugin should insert the script element above.

Thanks,

**Comment by mjangda** [comment]
If you have existing iframes in content that are converted to amp-iframe, then yes, the script is added automatically.

**Comment by OPPtester** [comment]
Thanks,

if I remove the script line I added to the custom-single, the video will not show and obviously the plugin did not add the script.

The actual page source for the embedded video:
`<iframe width="560" height="315" src="https://www.youtube.com/embed/0_v_BtIlH7g" frameborder="0" allowfullscreen></iframe>`

The AMP page source shows:
`<amp-iframe width="560" height="315" src="https://www.youtube.com/embed/0_v_BtIlH7g" frameborder="0" allowfullscreen="" sandbox="allow-scripts allow-same-origin" sizes="(min-width: 560px) 560px, 100vw" class="amp-wp-enforced-sizes"><div placeholder="" class="amp-wp-iframe-placeholder"></div></amp-iframe>`

**Comment by mjangda** [comment]
Are you modifying the template data in any way?

**Comment by OPPtester** [comment]
No not at all, just added the script line to my custom-single.php...this is weird!

**Comment by mjangda** [comment]
Definitely weird. How are you inserting the `amp-analytics` pieces?

**Comment by OPPtester** [comment]
In custom-functions I have:

`* AMP analytics *
 */
function isa_amp_scripts( $data ) {
    $data['amp_component_scripts'] = array(
                        'amp-analytics' => 'https://cdn.ampproject.org/v0/amp-analytics-0.1.js'
                        );
    return $data;
}
add_filter( 'amp_post_template_data', 'isa_amp_scripts' );

/*********************************************************************************************************/

/**
 * Add amp-analytics to the amp post template footer
 */
function isa_amp_analytics( $amp_template ) {
    ?><amp-analytics type="googleanalytics">
    <script type="application/json">
    {
      "vars": {
        "account": "UA-36480166-2" 
      },
      "triggers": {
        "trackPageview": {
          "on": "visible",
          "request": "pageview"
        }
      }
    }
    </script>
    </amp-analytics><?php
}
add_action( 'amp_post_template_footer', 'isa_amp_analytics' );`

**Comment by mjangda** [comment]
Yep, that's what's breaking it.

```
$data['amp_component_scripts'] = array(
'amp-analytics' => 'https://cdn.ampproject.org/v0/amp-analytics-0.1.js'
);
```

should be

```
$data['amp_component_scripts']['amp-analytics'] = 'https://cdn.ampproject.org/v0/amp-analytics-0.1.js';
```

Or better, use the analytics filter: https://github.com/Automattic/amp-wp/blob/master/readme.md#analytics

**Comment by OPPtester** [comment]
hmmm, thanks, do I have to add this part?:

`// https://www.parsely.com/docs/integration/tracking/google-amp.html
    $analytics['xyz-parsely'] = array(
        'type' => 'parsely',
        'attributes' => array(),
        'config_data' => array(
            'vars' => array(
                'apikey' => 'YOUR APIKEY GOES HERE',
            )
        ),
    );

    return $analytics;
}`

have no API key

**Comment by mjangda** [comment]
You can just skip that part unless you're using Parse.ly :)

**Comment by OPPtester** [comment]
Thanks will try that.

Regards,

**Comment by OPPtester** [comment]
Yep, all is working like a charm. Appreciate your help/tips.
