### ISSUE TITLE
Error in Chrome Console

### ISSUE THREAD

**Issue by overpress** [Automattic/amp-wp#317]
These are the errors to the console. How can I solve them?

![schermata 2016-03-06 alle 12 59 48](https://cloud.githubusercontent.com/assets/17315030/13553973/64ef13c8-e39b-11e5-831a-bf6e27cfb450.jpg)

This is the link -> http://overpress.it/2015/12/22/nuovo-macbook-documentario-60-minutes-no/amp/#development=1

**Comment by jery61007** [comment]
You need to remove the 'embed' code , instead, you may use iframe  and also the 'rel' attribute in the  div tag of Multi author ad slot .... and any link in the iframe should be https  , not http,  if you replace the embed video on your post with an iframe  that will look like this 

`<iframe id="sciframe" src="http://www.cbsnews.com/common/video/cbsnews_video.swf" width="100%" height="387" frameborder="0" marginwidth="0" marginheight="0" scrolling="auto"></iframe>`

but if the video doesn't have its https version, it will throw error that the src url should be https in iframe again.....  the plugin does a good job adding https automatically to all urls in the amp version of iframe you add in your post ...

**Comment by overpress** [comment]
OK, if I want to exclude a plugin only Amp versione how can I do?

**Comment by overpress** [comment]
Up

**Comment by overpress** [comment]
No one knows help me?

**Comment by mjangda** [comment]
See this section on how to handle media from other plugins: https://github.com/Automattic/amp-wp#handling-media
