### ISSUE TITLE
Images are compressed vertically

### ISSUE THREAD

**Issue by cfinke** [Automattic/amp-wp#32]
In this blog post: http://www.chrisfinke.com/2015/09/28/and-some-benches/amp/ the images are squished to about 60px tall but are still the full width of the column.

**Comment by mjangda** [comment]
See #14; we weren't able to figure out the width/height for the image and omitted it. The AMP runtime does not like that.

**Comment by kraftbj** [comment]
Probably related/cause: https://github.com/Automattic/jetpack/issues/2281

**Comment by mjangda** [comment]
The raw post source has the width/height attributes so something on Chris' site (likely in `the_content`; maybe Jetpack or another plugin?) is stripping the width/height attribute.

**Comment by cfinke** [comment]
Disabling Photon did indeed make the problem go away.

**Comment by kraftbj** [comment]
Photon needs a bit of thought with the Responsive Images feature plugin merge that happened a couple of days ago and situations like this. Confirmed that Photon strips the html args, adds one for JS to hook to for dynamic recalc of dims: https://github.com/Automattic/jetpack/blob/8d1f95f0043de7d394383983842ace6f58f962c8/class.photon.php#L353

For AMP for the time being, we can remove the filtering of the content ( https://github.com/Automattic/jetpack/blob/8d1f95f0043de7d394383983842ace6f58f962c8/class.photon.php#L55 ) or force `add_filter( 'jetpack_photon_skip_image', '__return_true' );` for all AMP-based images for the immediate time being to force skip Photon.

**Comment by kraftbj** [comment]
The root issue has been corrected (hopefully) in Jetpack, so let's get some Photon love back.Need to reactivate and consider a ver check for 3.8.1.
https://github.com/Automattic/jetpack/issues/2281
