### ISSUE TITLE
Webmaster tools error - need to fix to index

### ISSUE THREAD

**Issue by crystygye** [Automattic/amp-wp#320]
3 error's:
1 Unknown syntax error
2 Prohibited attribute
3 Required tag missing

1 Unkown syntax errors: boilerplate (js enabled) required by boilerplate (noscript)
2. Prohibited attributes: media
3. Required tags missing: boilerplate (js enabled)

what i need to do?

**Comment by espellcaste** [comment]
I've been getting the same error.. Still investigating where it came from.

**Comment by crystygye** [comment]
cool, we have amp enable but google won't index anything because the error's. it's nice to know i have at least one more plugin install for nothing.

**Comment by jdoy1382** [comment]
i have 2.425 pages indexed with 59 errors (checked 1 by 1 and resolved) but nothing in SERP :( my site is on Google news. So i thing at this moment AMP is only working for big sites.

**Comment by BurlesonBrad** [comment]
@crystygye If you run a plugin that's **IN DEVELOPMENT**, _guess what_  
## there might be an error :facepunch: 
> it's nice to know i have at least one more plugin install for nothing

Drop the attitude and contribute! Github is not the water cooler and it's not the kiddie pool.  Report an error / bug / give it a label / things like that but if you need to whine, that's pretty much what happens in the .org/plugins area.
@jdoy1382  AMP works for any site.  The size of the size has nothing to do with the functionality.

**Comment by jdoy1382** [comment]
Yes it,s working for all the sites but in SERP only indexed big sites.

**Comment by LeoKesler** [comment]
I only see AMP pages in news sites. I never saw AMP pages for blogs / normal sites.

**Comment by crystygye** [comment]
@BurlesonBrad if it is in development why i can i find the plugin on official plugin area on my wordpress website? if the plugin can't work , don't put it online, just here for testing.
This is the reason why you need to install, uninstall 100 same type plugin to find 1 plugin that works. 

"Let's test the plugin on people website, because they don't have anything to loose....."

**Comment by mjangda** [comment]
Closing as there aren't enough details on the errors. Please open a new ticket with more details on validation errors.
