### ISSUE TITLE
Prohibited tag  <?xml ..

### ISSUE THREAD

**Issue by jery61007** [Automattic/amp-wp#321]
Prohibited tags:	<?xml   ?>

Is this tag prohibited ? I get this error on Web master Console but the developer console says Validation successful even with this tag.... 

Just take a look at this webpage  http://techprezz.com/2013/09/galaxy-note-3-lg-g2-xperia-z1-vs-lumia-1020/amp/

I am confused if I should remove it or not....   I use the tag to encode the content  as loadHTML() fails to correctly handle the UTF-8 character ....

**Comment by mjangda** [comment]
I don't see any XML tags at the linked URL. If this is still an issue, please re-open with more details. Thanks.
