### ISSUE TITLE
YouTube i-amp-sizer padding is wrong

### ISSUE THREAD

**Issue by corysimmons** [Automattic/amp-wp#324]
YouTube is 16:9 so the padding should be `56.25%`, not `80%`. With `80%` it produces pretty large letterboxing.

![image](https://cloud.githubusercontent.com/assets/224636/13611961/19f09c86-e533-11e5-9b1f-d6f5a2bd8e0c.png)

**Comment by mjangda** [comment]
Maybe a default of 600x338 is better? (right now we're setting 600x480)

Bonus: we could calculate the height based on the `content_max_width` for the 16x9 ratio.

**Comment by corysimmons** [comment]
Might also consider letting people pass their own ratios? https://github.com/corysimmons/intrinsic
