### ISSUE TITLE
author [Person]: Image missing

### ISSUE THREAD

**Issue by nakitadog** [Automattic/amp-wp#325]
How do I inject the specific author's image into the schema data for each AMP page? 

I am receiving errors within the Google search console for missing author images.

Thanks

**Comment by Basilakis** [comment]
Hello,

You can get the gravatar URL with a function and then use imp-img to make it work!

**Comment by nakitadog** [comment]
Could you elaborate on that a bit? Maybe with some example code?

Thanks

**Comment by mjangda** [comment]
See https://github.com/Automattic/amp-wp#schemaorg-json-metadata for updating the structured data.
