### ISSUE TITLE
After installing plugin - A Blank page is displayed

### ISSUE THREAD

**Issue by swaraasolutions** [Automattic/amp-wp#329]
Hi,

I have installed the plugin and a blank page is getting displayed when added /amp/ to the permalink.

I have debugged and found that the following code is creating the issue in single.php

do_action( 'amp_post_template_head', $this ); if i comment out this section it works perfectly.

I am unable to debug further as i am not sure how the amp_post_template_head works.

A Link for the issue with code commented 
http://www.rumournews.in/entertainment/9868/deepika-is-talented-and-i-adore-her-ruby-rose/amp/

Your help is appreciated on this

**Comment by BurlesonBrad** [comment]
ok, lemme see if I've got this straight:
You've got a theme, that does **NOT** have the original theme headers in it:
![amp-jerk](https://cloud.githubusercontent.com/assets/6208757/13724630/a8351b9a-e851-11e5-983f-9e3a8afccbf9.png)

The theme is ** NOWHERE CLOSE** to being **current**
![amp-jerk2](https://cloud.githubusercontent.com/assets/6208757/13724646/0e2e1208-e852-11e5-8507-0b37514cce36.png)

So you **just created** a Github account so that someone **else** could fix your problems?

@mjangda Lock and Limit please :+1: Thank you.

**Comment by swaraasolutions** [comment]
Hi Brad,

Thanks for your excellent response much appreciated. This clearly helps me understand that the issue opening on the github gets such useful answer.

I have never expected anyone to do it for me. However it would have been great if someone would have put me on right track.

Also, this was working fine before the update. 

@mjangda please close this and limit people like me who want to get on correct path.

P.s. I have this github account for a long time however I haven't been too active.

Thanks

Sent from YU

On 13-Mar-2016 12:34 am, Brad Griffin <notifications@github.com> wrote:

ok, lemme see if I've got this straight:
You've got a theme, that does NOT have the original theme headers in it:
 

The theme is ** NOWHERE CLOSE** to being current
 

So you just created a Github account so that someone else could fix your problems?

@mjangda Lock and Limit please   Thank you.

**Comment by swaraasolutions** [comment]
Also to clarify this is an installation done by another developer and has come to my office for restructuring with new theme however till the time it works the client wanted it to work with amp.

Sent from YU

On 13-Mar-2016 12:41 am, varun@swaraasolutions.com wrote:

Hi Brad,

Thanks for your excellent response much appreciated. This clearly helps me understand that the issue opening on the github gets such useful answer.

I have never expected anyone to do it for me. However it would have been great if someone would have put me on right track.

Also, this was working fine before the update. 

@mjangda please close this and limit people like me who want to get on correct path.

P.s. I have this github account for a long time however I haven't been too active.

Thanks

Sent from YU

On 13-Mar-2016 12:34 am, Brad Griffin <notifications@github.com> wrote:

ok, lemme see if I've got this straight:
You've got a theme, that does NOT have the original theme headers in it:
 

The theme is ** NOWHERE CLOSE** to being current
 

So you just created a Github account so that someone else could fix your problems?

@mjangda Lock and Limit please   Thank you.

**Comment by Basilakis** [comment]
Please buy your theme.

**Comment by jdoy1382** [comment]
i am using the plugin on Newspaper theme (original) and it,s working perfect !!!

**Comment by mjangda** [comment]
@swaraasolutions It sounds like a PHP fatal error (or maybe a conflict with another plugin). Best place to start it to check your error log to see if there are any errors there. If you do find a fatal error, please report back so we can investigate.

**Comment by swaraasolutions** [comment]
Hi Mohammad,

 

It was indeed an issue with Plugin for Yoast Glue AMP Seo Plugin. Once removed it worked

 

Regards

 

Varun Varde
