### ISSUE TITLE
URGENT: Plugin not work with simple permalinks due Google bug

### ISSUE THREAD

**Issue by yuratt** [Automattic/amp-wp#330]
Hi.

I spend a lot of time to check why Structured Data Testing Tool always show errors in fields logo and image.

Finally, I find out that google do not like if url contains "&amp".

**You can take ANY url of amp page, add to the end &amp and errors will appear.**

So, in case of using simple permalinks like "?p=123&amp=1" amp pages always show erros and in search conslole too.

So, I fixed the problem by changins &amp to &am_p in amp.php 

I've created topic few days in worpdress plugin page, but seems developers did not check it [https://wordpress.org/support/topic/google-validation-always-show-errors-for-simple-permlinks-like-p123amp1?replies=1](https://wordpress.org/support/topic/google-validation-always-show-errors-for-simple-permlinks-like-p123amp1?replies=1 )

**Comment by mjangda** [comment]
The proper way to encode `&` in URLs is `&amp;` (note the `;`) or even better `%26`. The missing `;` causes URLs to be interpreted differently.
