### ISSUE TITLE
amp-twitter broken because of integer casting of Tweet ID

### ISSUE THREAD

**Issue by mkhatib** [Automattic/amp-wp#334]
AMP Tweet IDs are broken because of integer casting using `intval` [here](https://github.com/Automattic/amp-wp/blob/master/includes/embeds/class-amp-twitter-embed.php#L66) and in other places.

I thought [that ID was pretty familiar](https://en.wikipedia.org/wiki/2147483647_(number)) - It seems that searchengineland is running on [32bit system](http://php.net/manual/en/function.intval.php). 

See ampproject/amphtml#2548 for an example of broken tweets

**Comment by mjangda** [comment]
Ah, thanks. We'll fix this up.

**Comment by maxhartshorn** [comment]
FYI this issue is still occurring

**Comment by mjangda** [comment]
@maxhartshorn can you provide an example?

**Comment by maxhartshorn** [comment]
I don't have a live example I can show you at the moment. I'm running this plugin on a local install:
https://wordpress.org/plugins/amp/ 

This is the tweet:
http://twitter.com/jaypdonovan/status/718556215824019457

This is the output:
<amp-twitter data-tweetid="2147483647" layout="responsive" width="600" height="480"></amp-twitter>

I'm wondering now if the wordpress.org plugin is not up to date with the repo?
