### ISSUE TITLE
Remove Category from meta

### ISSUE THREAD

**Issue by OPPtester** [Automattic/amp-wp#335]
Really sorry this is not an issue, but just a request to maybe add how to remove category from meta in the Readme just like you did for the remove author from meta?

Basically, the AMP page should show the author and publish time, no category.

Thanks,

**Comment by mjangda** [comment]
You can follow the example here https://github.com/Automattic/amp-wp#example-remove-author-from-meta but replace `meta-author` with `meta-taxonomy`.
