### ISSUE TITLE
Facebook Embed doesn't work?

### ISSUE THREAD

**Issue by pratham2003** [Automattic/amp-wp#338]
Hi, I'm using this plugin along with Pagefrog plugin.

I'm trying to add a facebook video to the top of the post content using 'the_content' filter. (The video url is stored in a custom meta). But for some reason the AMP_Facebook_Embed_Handler class doesn't pick this up.

I've inserted the youtube iframe code the same way and its being parsed and embedded as amp-iframe.. What could be going wrong with the facebook embed handler?
If possible can someone give a brief example of what the facebook video url / code should look like to be handled by AMP_Facebook_Embed_Handler ?

**Comment by mjangda** [comment]
What's the URL of the video?

**Comment by pratham2003** [comment]
Video url : https://www.facebook.com/theTruth365film/videos/1242319279129112/

**Comment by pratham2003** [comment]
I just realized that if I add the video link in content it works, but if I use the 'the_content' filter to insert the video link into article it doesn't work.

If I use the same filter and insert a youtube iframe embed, it works. 

So the amp-iframe embeds are working this way but not the amp-youtube and amp-facebook.

**Comment by pratham2003** [comment]
I figured this out.

If anyone else stumbles upon this change the priority of the 'the_content' filter to -1 and also try to not have the video link inside something like a <p style=""></p> .. The oembeds also require a newline character after the video link.
