### ISSUE TITLE
AMP_Gallery_Embed_Handler - add attributes to `embed` function

### ISSUE THREAD

**Issue by paulgibbs** [Automattic/amp-wp#342]
In `AMP_Gallery_Embed_Handler->embed`, please can the two additional argumentes (provided by the `do_shortcode()` callback, `$content` and `$tag`) be added to the function here?

Use case is extending the `AMP_Gallery_Embed_Handler` class but requiring the extra parameters in the `shortcode` method.

**Comment by mjangda** [comment]
Sure, we can add that those params but it's probably better just to write your own handler than extending the built-in one (which is crappy and needs to be overhauled)?
