### ISSUE TITLE
Post permalink structure changed - AMP doesn't see pages

### ISSUE THREAD

**Issue by dsgnr** [Automattic/amp-wp#343]
Hello,
I am using this plugin successfully however, on one website I use a function to add /blog/ to the permalink - when trying to access the amp page it shows the URL with /blog/ as the canocial but it brings up a 404 but does show successfully when removing the /blog/ from the URL.

Here is my function added to functions.php:
```
function add_rewrite_rules( $wp_rewrite )
{
$new_rules = array(
'blog/page/(.+?)/?$' => 'index.php?post_type=post&paged='. $wp_rewrite->preg_index(1),
'blog/(.+?)/?$' => 'index.php?post_type=post&name='. $wp_rewrite->preg_index(1),
);
 
$wp_rewrite->rules = $new_rules + $wp_rewrite->rules;
}
add_action('generate_rewrite_rules', 'add_rewrite_rules');
	 
	 
	 
function change_blog_links($post_link, $id=0){
	 
$post = get_post($id);
	 
if( is_object($post) && $post->post_type == 'post'){
return home_url('/blog/'. $post->post_name.'/');
}

return $post_link;
}
add_filter('post_link', 'change_blog_links', 1, 3);
```

So with this function, I get: www.domain.com/**blog**/post-page but then www.domain.com/**blog**/post-page/amp shows a 404, BUT www.domain.com/post-page/amp does work however it shows /blog/ in the amphtml which is obviously going to cause issues with Google indexing.

By removing this function, thus removing /blog/ from the URL everything works correctly.
Is this something that can be altered from within the plugin or do I need to create another function for URL rewrite?

Hopefully I've made sense

Thanks!

**Comment by mjangda** [comment]
You'll need to add a rewrite rule to make `www.domain.com/**blog**/post-page/amp` work.

Something like:

```
'blog/(.+?)/amp/?$' => 'index.php?amp=1&post_type=post&name='. $wp_rewrite->preg_index(1),
```
