### ISSUE TITLE
How to fix 'wp-caption' container size?

### ISSUE THREAD

**Issue by Berdych** [Automattic/amp-wp#344]
Original page - http://screenshotuploader.com/s/1603tjpuo
AMP page - http://screenshotuploader.com/s/160331bcq

Standard shortcode from WordPress:
`[caption id="attachment_58" align="alignright" width="300"]<img class="wp-image-58 size-medium" src="http://rehub.chernil.com.ua/wp-content/uploads/2016/02/Z5ZVY4FM28-300x200.jpg" alt="Z5ZVY4FM28" width="300" height="200" /> Several dental practitioners recommend using an antimicrobial mouth wash that will help minimize the build-from tartar...[/caption]`

**Comment by westonruter** [comment]
This is fixed in 0.6.x in my testing. Inline styles get converted into style rules.
