### ISSUE TITLE
Invalid attribute: 'clear' in <br>

### ISSUE THREAD

**Issue by SvenSevke** [Automattic/amp-wp#345]
1.) clear is not a valid attribute in a BR tag
<strike>2.) border is not a valid attribute in a TABLE tag</strike>

Would make sense to sanitize them with the help of class-amp-blacklist-sanitizer.php

**Comment by mjangda** [comment]
> 2.) border is not a valid attribute in a TABLE tag

This has since been allowed in the AMP spec.

**Comment by westonruter** [comment]
Whitelist sanitizer will now take care of this.
