### ISSUE TITLE
News Schema Invalid (Missing Image) if no featured/attached 

### ISSUE THREAD

**Issue by sgatz** [Automattic/amp-wp#346]
When a post has neither a featured image nor an attached image the news schema is invalid and google throws an error (Image missing and required).

The plugin should allow for:
* a default image to be set 
* add an action to get_post_image_metadata to be able to pass in an image (we use the Get The Image plugin to find any images in our posts that are not attached, but are embedded), we'd love to use a hook to leverage that plugin. 

Example post where this occurs:
http://www.queerty.com/marti-gould-cummings-orange-is-the-new-black-annie-golden-the-not-so-late-show-interview-20150204/amp

**Comment by sgatz** [comment]
Note that there is a workaround, a filter on amp_post_template_metadata can accomplish the same thing, but IMHO there should still be a default image option and a filter to replace missing images.  The plugin should never return invalid schema data.

**Comment by mjangda** [comment]
No plans to do this currently since it's a Google Webmaster Tools requirement and not an AMP requirement.
