### ISSUE TITLE
Google Webmaster Tools gives me:Fehler in schema.org-Article 

### ISSUE THREAD

**Issue by bpgs** [Automattic/amp-wp#347]
I've recently installed the AMP plugin and now GWT gives on every crawled page the message

> Fehler in schema.org-Article
> Korrigieren Sie das strukturierte Article-Datenelement in Ihrer Seite. AMP-Seiten mit einem ungültigen strukturierten Article-Datenelement können in den Google-Suchergebnissen ohne AMP-spezifische Anzeigefeatures erscheinen.

Sorry for inserting this message in German but I've no idea how to force GWT to use English

**Comment by mkuplens** [comment]
Do the posts on your site have featured images & do you have a site icon set? The AMP plugin adds rich snippet metadata to all posts, which requires both of these to be set.

**Comment by mjangda** [comment]
Likely a site icon issue, see https://github.com/Automattic/amp-wp#site-icon

**Comment by bpgs** [comment]
Greetings! 

I've got that nice stuff for you, it  is awesome. Just take  a  look at it <http://date.rameymusic.net/e8zclvoj>

Rushing, awardfan

**Comment by bpgs** [comment]
Greetings! 


I just wanted to share some great news with you, I'm so happy!  You may read the news  here <http://key.gotwisdom.us/e8jwlhsc>

awardfan
