### ISSUE TITLE
AMP validation errors: amp-audio requires https?

### ISSUE THREAD

**Issue by drewhackney** [Automattic/amp-wp#350]
I’ve got a couple blog posts that are giving AMP errors as reported by the user who received a notification from Google:

http://studio-lu.net/2012/03/19/welcome-home-cowboy-bob/amp/#development=1

"http://studio-lu.net/2012/03/19/welcome-home-cowboy-bob/amp/:314:38 Invalid URL protocol 'http:' for attribute 'src' in tag 'amp-audio > source'. (see https://www.ampproject.org/docs/reference/extended/amp-audio.html)"

http://studio-lu.net/2012/02/19/in-search-of-my-grandfathers-laugh/amp/#development=1

"http://studio-lu.net/2012/02/19/in-search-of-my-grandfathers-laugh/amp/:307:38 Invalid URL protocol 'http:' for attribute 'src' in tag 'amp-audio > source'. (see https://www.ampproject.org/docs/reference/extended/amp-audio.html)"

Thanks!

**Comment by mjangda** [comment]
#310 improved this a bit and we can improve further in #354.
