### ISSUE TITLE
The attribute 'rel' in tag 'a' is set to the invalid value prettyPhoto

### ISSUE THREAD

**Issue by fearles577** [Automattic/amp-wp#351]
Hi,

i'm testing this plugin and when i try the validator i have this error for all the images which are set to link to their attachment page :

The attribute 'rel' in tag 'a' is set to the invalid value 'prettyPhoto[rel-1298242505]'
Is this a plugin issue ?

samplepage: http://beykozrc.com/beykoz-rc-off-road-25-12-2015-hidiv-kasri-bulusmasi/amp/#development=1

Thanks..

**Comment by mjangda** [comment]
Dupe of #237
