### ISSUE TITLE
Using ?amp=1 while using pretty permalink or hooks to use custom amp url

### ISSUE THREAD

**Issue by Asif2BD** [Automattic/amp-wp#353]
For one of my project I need to use url with argument, so ?amp=1 is fine while the project use pretty permalink.

Is there a hook to change amp url? I could edit source in amp.php but need a hook so could remain valid after plugin update. And here canonical url needs to update as well, so hook is best. I could not find a hook so far, please direct me if we already have one, or let'r make it a feature addition, and bring it on.

**Comment by mjangda** [comment]
You can use the `amp_get_permalink` filter: https://github.com/Automattic/amp-wp/blob/master/includes/amp-helper-functions.php#L10

**Comment by Asif2BD** [comment]
Thanks a ton @mjangda for pointing this out. 
Then I just want to have ?amp=1 as my canonical, instead of /amp/. How do I do that with this 'amp_get_permalink' filter. Sorry for bugging, and Thanks in advance!

**Comment by mjangda** [comment]
Just using that filter should do it since we use the function internally to get the AMP URL for each post. If not, it might be a bug.

I guess we could provide another filter in this function that runs before we generate the AMP URL (`amp_pre_get_permalink`) so it's easier to modify (in your case, you have to strip off the `amp/` and replace it with `?amp=`, which seems annoying.)

**Comment by Asif2BD** [comment]
Actually in my case my site has a m.site, for serving mobile traffic automatically, and that filter is done from server. And as our link structure is like domain.com/category/post-title/, so with amp it becomes domain.com/category/post-title/amp/ which I find that very hard to filter from nginx.conf and stop the redirection for mobile device. But if I could use argument like ?amp=1 its easier for me to filter and stop redirection.

And yes this 'amp_get_permalink' happens on the top, and adding filter to modify it does not work on header. I think the plugin should have a option page, very simple one, and we should be able to change amp url as we want, and you could use that on 'amp_pre_get_permalink'.
