### ISSUE TITLE
twitter embed not rendering to amp-twitter and few other issues

### ISSUE THREAD

**Issue by atulkainth** [Automattic/amp-wp#355]
Hi twitter embed are not converting to amp-twitter, they are showing in blockquote

Sample page : http://indianexpress.com/article/entertainment/bollywood/aishwarya-rai-abhishek-bachchan-are-proud-parents-at-aaradhyas-annual-day-see-pic/lite/#development=1

Some other issues I found
1. Attachment urls getting rel inside rel ----> rel="rel="attachment ""
2. Removing align attritube from p tags
3. Giving default width to amp-iframe if width is empty
4. rel="hashtag" in a tags

**Comment by mjangda** [comment]
The amp-twitter handling only works for oembed and shortcode versions of tweets right now.
