### ISSUE TITLE
amp permalinks still active after uninstall

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [Automattic/amp-wp#356]
Sorry to part ways with amp-wp. I don't wish to have gravatars on the site. Ghostery doesn't like it. 

I notice that after uninstall, the amp permalink are still active, although the HTML content is identical to the canonical URL. 

How do I go back to the state before installation?

**Comment by mustafauysal** [comment]
Hi @vijayaraghavanramanan 

Do you still get this problem?
> I don't wish to have gravatars on the site. Ghostery doesn't like it.

You can remove `meta-author` part via filter.

> How do I go back to the state before installation?

AMP flushes rewrite rules during deactivation. Are using an external object cache (memcached, redis etc...) ? If so, make sure to clear cache.

**Comment by Akulavenkatesh** [comment]
@mustafauysal 
I'm also facing the same issue. I tried the this in my local, even after deleting the plugin, canonical links are still there in my posts. 
<link rel="canonical" href="http://127.0.0.1/wp/2016/08/06/lenovo/" />

**Comment by websupporter** [comment]
A quick dropin:
I just tried it on a quite clean install without caching and I couldn't reproduce the problem

**Comment by amedina** [comment]
This is working now.
