### ISSUE TITLE
Autoplay attribute for audio and video is set to invalid value

### ISSUE THREAD

**Issue by dapickboy** [Automattic/amp-wp#360]
Webmaster Tools is reporting that the autoplay is set to autoplay="desktop tablet mobile" ; which is an invalid value. Should be set to an empty value or no value at all.
There was a similar problem with the controls/loop/muted attributes.

**Comment by mjangda** [comment]
Can you share the exact error?

Per the docs, `autoplay` can only be set to the values we already do: "The author may specify values to limit when the animations will autoplay. Allowable values are desktop, tablet, or mobile, with multiple values separated by a space." (via https://github.com/ampproject/amphtml/blob/master/builtins/amp-video.md#attributes)

**Comment by dapickboy** [comment]
Yup! 

The console tells me :
http://www.letagparfait.com/fr/2016/01/03/les-gifs-de-la-semaine-124/amp/:316:3 The attribute 'autoplay' in tag 'amp-video' is set to the invalid value 'desktop tablet mobile'. (see https://www.ampproject.org/docs/reference/amp-video.html)

**Comment by mjangda** [comment]
Opened https://github.com/ampproject/amphtml/issues/3715 for clarification on what's allowed with this attribute.
