### ISSUE TITLE
Image not centered when the 'caption' shortcode is used and center alignment is set

### ISSUE THREAD

**Issue by gnotaras** [Automattic/amp-wp#362]
Image with a caption text are surrounded by the `[caption ...] .... [/caption]` shortcode in the post editor. If those images are set to be aligned, eg center aligned, they still don't appear centered in the AMP page.

It seems that the `aligncenter` class (or other alignment class) is missing from the `<amp-img ... </amp-img>` block.

On the contrary, images without a caption (no `caption` shortcode) appear centered in the AMP page, if that is what has been set in the editor.

**Comment by jiwicky** [comment]
you can hook into 'amp_post_template_css' and set 
```
figure {
  width: 100%;
}
```
That's what worked for me for now, till it's rolled in.

**Comment by mjangda** [comment]
This is fixed.

![image](https://cloud.githubusercontent.com/assets/86105/25546893/f3943afa-2c32-11e7-9612-85479a63d4b2.png)

**Comment by amedina** [comment]
Closing as it is fixed. Thanks @mjangda.
