### ISSUE TITLE
Wordpress Amp Article logo missing while Testing in Google Structured Data Testing Tool

### ISSUE THREAD

**Issue by ustechera** [Automattic/amp-wp#363]
wordpress amp logo missing (only logo) so , can u please guide me how to resolve it

http://ustechera.com/skype-a-once-reliable-communication-tool-is-falling-from-grace/amp/
![c4c49960-fabd-11e5-9503-4b8915c8f57b](https://cloud.githubusercontent.com/assets/18269051/14303813/15cc30d0-fbcb-11e5-9745-bf71c5403845.JPG)

thanks in advance.

(Note: Google won't index our website webpages due to this error)

**Comment by mjangda** [comment]
Please see https://github.com/Automattic/amp-wp#site-icon

**Comment by ustechera** [comment]
Thank you Problem Resolved .

**Comment by abrambailey** [comment]
That link is broken @mjangda... Do we just need to add the site icon?

**Comment by westonruter** [comment]
@abrambailey here's an updated link: https://github.com/Automattic/amp-wp/wiki/Customization-and-Templating#site-icon

Please also note that the Custom Logo is intended to be used in the future. See #975.

**Comment by hkmaly** [comment]
That link works but doesn't show anything about site icon.

Is there some estimate of when that future will be?

**Comment by westonruter** [comment]
Actually the Wiki page seemed to be broken. Please see https://github.com/Automattic/amp-wp/wiki/Legacy-Templating-And-Customization#site-icon

Automatically using the Custom Logo will come in 1.0. In the mean time, you can use filters in this wiki page.

**Comment by hkmaly** [comment]
I've ended up writing plugin adding filter for amp_schemaorg_metadata ... turns out I need different logo anyway, made from custom header ...
