### ISSUE TITLE
"Override Taxonomy Template via filter" not working

### ISSUE THREAD

**Issue by untitledfoldergames** [Automattic/amp-wp#369]
I'm trying to override the taxonomy template, because when a post is in multiple categories or tags, that line in the output breaks down and looks ugly. I am trying to remove tags altogether and only show 1 category.

Your readme says

`This will load the file t/meta-custom-tax.php for the taxonomy section:`

...

`$file = dirname( __FILE__ ) . '/t/meta-custom-tax.php';`

If I make a file called custom-meta-taxonomy.php and place it in the /amp/ folder in my theme and reference it by

`$file = get_stylesheet_directory_uri() .  '/amp/custom-meta-taxonomy.php';`

Or I make a folder called "t" in the plugin directory and reference it by 

`$file = dirname( __FILE__ ) . '/t/custom-meta-taxonomy.php';`

Or I make a folder called "t" in the template directory and reference it by 

`$file = dirname( __FILE__ ) . '/t/custom-meta-taxonomy.php';`

 - none of these approaches show my custom taxonomy file.

Is the README incorrect or missing something?

**Comment by mjangda** [comment]
Can you share the full snippet of code you're using?

**Comment by untitledfoldergames** [comment]
Hey Mohammad

This is the code I have in functions.php

add_filter( 'amp_post_template_file', 'herb_amp_set_custom_tax_meta_template', 10, 3 );

function herb_amp_set_custom_tax_meta_template( $file, $type, $post ) {
    if ( 'meta-taxonomy' === $type ) {
        $file = dirname( __FILE__ ) . '/t/custom-meta-taxonomy.php';
    }
    return $file;
}

And the contents of /wp-content/plugins/amp/templates/t/custom-meta-taxonomy.php are:

<?php $categories = get_the_category_list( _x( ', ', 'Used between list items, there is a space after the comma.', 'amp' ) ); ?>
<?php if ( $categories ) : ?>
	<li class="amp-wp-tax-category">
		<span class="screen-reader-text">Categories:</span>
		<?php echo $categories; ?>
	</li>
<?php endif; ?>

This is just the default template code without the tags section.

I have tried putting custom-meta-taxonomy.php in /wp-content/plugins/amp/templates/ , /wp-content/plugins/amp/t/ , /themes/(my theme/amp/t/ etc but it’s never picked up anywhere.

Can you explain where to put the custom meta taxonomy file, and how to reference that location in the code?

Cheers



On 19 April 2016 at 8:00:45 AM, Mohammad Jangda (notifications@github.com) wrote:

Can you share the full snippet of code you're using?

**Comment by mjangda** [comment]
> I have tried putting custom-meta-taxonomy.php in /wp-content/plugins/amp/templates/ , /wp-content/plugins/amp/t/ , /themes/(my theme/amp/t/ etc but it’s never picked up anywhere.

`custom-meta-taxonomy.php` should go in a `t` folder in your theme, i.e. `themes/{my-theme}/t/`

Or alternatively, you can remove the filter completely, rename your custom file to `meta-taxonomy.php` and put it in `themes/{my-theme}/amp/`
