### ISSUE TITLE
Hide Site Icon on AMP page

### ISSUE THREAD

**Issue by vilav** [Automattic/amp-wp#370]
Hello

The plugin seems to set the site icon by default. I'm trying to hide it on the AMP page only. I'd like for it to appear as it normally would on the non-AMP, regular page.

Any tips on how to get this sorted?

Thanks

**Comment by mustafauysal** [comment]
Hi @vilav ,

You can do it with `amp_post_template_data` filter. 

e.g
```
add_filter( 'amp_post_template_data', function ( $data ) {
	if ( is_amp_endpoint() ) {
		unset( $data['site_icon_url'] );
	}

	return $data;
} );
```

**Comment by mjangda** [comment]
@mustafauysal the `if ( is_amp_endpoint() ) {` check is not necessary there, since `amp_post_template_data` will only ever fire in an AMP context.

**Comment by mustafauysal** [comment]
@mjangda You're right, previous comment updated ;)
