### ISSUE TITLE
Iframe with empty width/height isn't handled well

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#371]
`<iframe src="https://example.com" width="" height=""></iframe>` seems to pass through the width/height sanitization.

**Comment by LanaPummill** [comment]
Seriously, I didn't fix the problem and I was still asking for help and they closed my thread?

I changed my site icon/logo and it still shows 3 errors on these pages: 

https://findinginspirationinthechaos.blog/2018/08/19/im-not-handling-this-well/amp/
https://findinginspirationinthechaos.blog/2018/10/01/words-cut-like-a-knife/amp/ 
https://findinginspirationinthechaos.blog/2018/09/01/every-day-life-struggling-to-find-inspiration/amp/

I am using the google structured data tool and I am getting this error: 
	
A value for the image field is required.
The image field is recommended. Please provide a value if available.
