### ISSUE TITLE
Invalid attribute: 'pw:image' in tag 'div'

### ISSUE THREAD

**Issue by steveHimself1397** [Automattic/amp-wp#372]
For some reason the plugin creates a `<div>` with pw:image, pw:titlem and pw:url attributes.
Doesn't really make sens for me. The pw:image attribute is empty the rest of em is filled with values.

Can someone help?

**Comment by steveHimself1397** [comment]
It appears the cause is the social sharing widgets from the po.st plugin. After I've deactivated this the error went away. Is this a problem you guys should tackle or the po.st devs?

**Comment by amedina** [comment]
This is an interaction issue with the po.st plugin that causes the invalidation of AMP pages. It is very difficult to account for all possible interactions with any other plugin. We are looking into ways in which these situations could be handled.

**Comment by steveHimself1397** [comment]
Why would you close it then, if you are still looking into it? Is there a quick fix available besides "just deactivate the po.st plugin"?

**Comment by amedina** [comment]
@steveHimself1397, there is no quick fix to this situation; it is not an issue of the plugin, but the context where it is used. Ideally it would be solved it for all scenarios. I am going to create a more concrete issue to track this but it is not defined yet. Thanks for raising the issue and for using the plugin.
