### ISSUE TITLE
Facebook not approved (for galleries)

### ISSUE THREAD

**Issue by overpress** [Automattic/amp-wp#373]
Hello, Facebook has not approved the instant article because there is no way to view the gallery. You can see it here on our site -> http://overpress.it/2016/04/15/ikea-bicicletta/

Facebook post this image -> https://scontent-mxp1-1.xx.fbcdn.net/hphotos-xaf1/t39.7075-6/13065845_461104347421905_1792789831_n.jpg

We can show the galleries in any way?

**Comment by mjangda** [comment]
I think you posted this in the wrong repo?
