### ISSUE TITLE
iframe sanitizer doesn't deal with height="100%" that AMP throughs an error for

### ISSUE THREAD

**Issue by dashaluna** [Automattic/amp-wp#374]
According to iframe [sanitizer code](https://github.com/Automattic/amp-wp/blob/master/includes/sanitizers/class-amp-iframe-sanitizer.php#L93) - it allows attribute `height` with any specified value, including `100%`.

However, AMP validator complains about that, as both width and height should be specified in px.

Error quote:
`The attribute 'height' in tag 'amp-iframe' is set to the invalid value '100%'. (see https://www.ampproject.org/docs/reference/extended/amp-iframe.html)`

**Comment by mjangda** [comment]
Related #371
