### ISSUE TITLE
number of Unknown syntax errors in WMT

### ISSUE THREAD

**Issue by jattsaini** [Automattic/amp-wp#377]
I am using this plugin and suddenly it has started showing more than 1000 Unknown syntax errors in WMT. My site: http://www.timesnews.co.uk/

and i am getting this error or number of pages. Some of them are: 
http://www.timesnews.co.uk/7586-zte-announces-zte-nubia-prague-s-with-3gb-ram-priced-at-2499-yuan/amp/

http://www.timesnews.co.uk/3541-motorola-moto-e-4g-2nd-gen-leaked-by-best-buy/amp/

http://www.timesnews.co.uk/8295-lava-grand-2-fcc-passed-images-leaked/amp/

http://www.timesnews.co.uk/8450-oppo-launches-oppo-r9-oppo-r9-plus-4gb-ram-16mp-camera/amp/

and may more.

Any solution for these errors......?

**Comment by mjangda** [comment]
Can you share some examples?

**Comment by mkuplens** [comment]
Per the Google structured data test tool ([sample report](https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fwww.timesnews.co.uk%2F8295-lava-grand-2-fcc-passed-images-leaked%2Famp%2F)), it looks like you don't have a site icon set, so the expected site logo is missing.

Google's rich preview feature requires a site logo; the AMP plugin includes metadata for this for every AMP-formatted post. To resolve the issue, simply set a site icon in the WordPress customizer.

**Comment by jattsaini** [comment]
Thanks mjangda,
I have added the logo yesterday after reading your post. I hope that it will reduce the errors count.

**Comment by jattsaini** [comment]
The Google Structured data test tool now showing the error: A value for the logo field is required.
What to with this error?
