### ISSUE TITLE
Generated AMP URLs are broken - missing URL protocol

### ISSUE THREAD

**Issue by arcivanov** [Automattic/amp-wp#380]
```html
<link rel="canonical" href="//www.ivanov.biz/2011/welcome-arcadiy-ivanov/" />
<script custom-element="amp-analytics" src="//cdn.ampproject.org/v0/amp-analytics-0.1.js" async></script>
<script src="//cdn.ampproject.org/v0.js" async></script>
```

The homepage is here: https://www.ivanov.biz/2011/welcome-arcadiy-ivanov/ and   https://www.ivanov.biz/2011/welcome-arcadiy-ivanov/amp/

**Comment by arcivanov** [comment]
Found the problem - CloudFlare plugin interferes with the URLs in AMPs. Not sure if it's CloudFlare or AMP that is the problem.

**Comment by dknecht** [comment]
@arcivanov it is CloudFlare issue.   We will be putting in automatic fix shortly.   In the short term you can disable all page performance (besides caching) using page rules for */amp/ pattern.

**Comment by arcivanov** [comment]
Actually, I just disabled the CloudFlare plugin without disabling caching, minification or CloudFlare itself and it works like a charm! 

Thanks for your help!

**Comment by RReverser** [comment]
Please see https://github.com/ampproject/amphtml/issues/2380 for a generic issue.

**Comment by mjangda** [comment]
Closing since this is coming from a different plugin.
