### ISSUE TITLE
AMP template gets redirected back to Article page

### ISSUE THREAD

**Issue by amandhare** [Automattic/amp-wp#381]
Hi,

In the current WP Trunk core we are having an issue where the amp template gets redirected back to article page. It was all working fine until WP 4.5. 

After much investigation I have come to the conclusion that the template_redirect hook is getting overridden by one of our plugins and we land back on article page.

A possible solution to this issue can be if we have template_redirect hook in amp plugin at a higher priority, say at priority 9, so that the amp template is loaded at much higher priority than any other template if the URL resolves for amp page.

`function amp_prepare_render() {
	add_action( 'template_redirect', 'amp_render', 9 );
}`

**Comment by mjangda** [comment]
Have you tried modifying your plugins to either 1) hook into `template_redirect` at a higher priority or 2) not run when `is_amp_endpoint()`?

**Comment by amandhare** [comment]
Yeah. Checking on `is_amp_endpoint()` and not redirecting to article page using `'redirect_canonical'` filter worked.

Thanks.
