### ISSUE TITLE
BlogPosting Schema validation errors

### ISSUE THREAD

**Issue by pentago** [Automattic/amp-wp#382]
Just went to Search Console and saw that there's plenty of AMP validation errors.

I Opened page in Google's structured data debugger and saw this: http://image.prntscr.com/image/7d4166545cb44f6089ddf7bb1f5365d6.png

Plugin added that schema itself (I didn't) but it didn't filled it with site name and logo nor it allows user to define those properties.

How do I fix this?

**Comment by mjangda** [comment]
Please see https://github.com/Automattic/amp-wp#site-icon
