### ISSUE TITLE
I enable amp plugin and resaved permlink, but not working

### ISSUE THREAD

**Issue by Waleed7** [Automattic/amp-wp#383]
Hello

Please i want some help, i enable amp plugin and resaved permlink, but not working, i type /amp/ at end of link and not work.
please help me!!

**Comment by mjangda** [comment]
Does adding `?amp=1` to your post URLs work?

**Comment by louisagung** [comment]
Hi,
I tried both ways and they don't work. When I added ?amp=1 nothing changes from the original interface. When I add /amp/, 404 error page appears.
Web address is strong-indonesia.com

Any suggestions? Thank you very much!

**Comment by partounian** [comment]
It was working fine for me before also, but now it seems to have magically broken. printfirm.com/blog

**Comment by amedina** [comment]
Closing this issue for now; this should be working with the latest version of the plugin. Please reopen if needed.
