### ISSUE TITLE
Inline style attr added to amp-img tag throwing validation errors

### ISSUE THREAD

**Issue by andrade1379** [Automattic/amp-wp#385]
I was wondering how I can access the amp-img tag within my template so that I can remove attr "style: 100px" from tag. It causes images to be sized smaller than they should be and throwing errors when passed though validation.

Or how I can fix this from happening.

```
<amp-img style="width: 100px;" id="AMP_4" class="aligncenter size-medium wp-image-3982 amp-wp-enforced-sizes -amp-element -amp-error -amp-layout" src="/wp-content/uploads/second-image-in-body.jpg" alt="second image in body" width="100%" height="auto" srcset="/wp-content/uploads/second-image-in-body.jpg 1920w, /wp-content/uploads/second-image-in-body-569x320.jpg 569w" sizes="(min-width: 100px) 100px, 100vw"><img src="/wp-content/uploads/second-image-in-body-569x320.jpg" class="-amp-fill-content -amp-replaced-content" alt="second image in body" amp-img-id="AMP_4" width="100" height="0"></amp-img>
````
I've also attached a screen shot of what I see when debugging
```
#development=1&filter=AMP_LAYOUT_PROBLEM
```
![screen shot 2016-05-04 at 6 16 08 pm](https://cloud.githubusercontent.com/assets/1234484/15032262/9e98636a-1224-11e6-869f-619ad43298cc.png)

**Comment by mjangda** [comment]
That's odd. The `style` tag should be stripped out when we convert the `img` tag to `amp-img`. Can you share what the img tag looks like in the non-AMP version of the post? Are you making any other modifications to the AMP plugin or using any of its hooks/filters?

**Comment by andrade1379** [comment]
@mjangda thanks for the response.

Yes, here is what that page looks like when not in the AMP layout:

![screen shot 2016-05-06 at 11 03 31 am](https://cloud.githubusercontent.com/assets/1234484/15078735/36ad2ae0-137a-11e6-8cfc-8e790b0ec961.png)

These are the AMP overrides/customization I have in my functions.php file:

```
add_action( 'amp_post_template_head', 'amp_add_google_analytics' );
add_filter( 'amp_post_template_meta_parts', 'cdw_amp_remove_author_meta' );
add_action( 'amp_post_template_css', 'cdw_amp_additional_css_styles' );
add_action( 'pre_amp_render_post', 'cdw_amp_add_custom_actions' );
add_filter( 'the_content', 'cdw_amp_add_featured_image' );
add_filter( 'amp_post_template_data', 'cdw_amp_set_site_icon_url' );
```

**Comment by andrade1379** [comment]
@mjangda I was also wondering how I can check for links within the body that use the email protocol. Like such:
```
<a href="email:sample@sample.com">sample@sample.com</a>
``` 
And possibly remove them when we navigate to the page's /amp version?

**Comment by andrade1379** [comment]
Would like to know if this is something that I can fix on my end or a bug within the plugin?

Thanks!

**Comment by mjangda** [comment]
You'd need to track down where the `style="width: 100px"` is coming from (likely somewhere in your theme or plugins?)

As for removing emails, you can write a custom sanitizer that strips things out (see https://github.com/Automattic/amp-wp#custom-sanitizer for docs on how and https://github.com/Automattic/amp-wp/blob/master/includes/sanitizers/class-amp-blacklist-sanitizer.php as an example)

**Comment by andrade1379** [comment]
@mjangda Hey I know you closed this but I'm still having problems with the plugin forcing 100% width attribute on <amp-img> tag. This is causing errors to be thrown.

Here is the generated source from the <amp-img> tag:

```
<amp-img style="width: 100px;" id="AMP_6" error-message="Invalid width value: 100%​​​" class="aligncenter size-medium wp-image-3983 amp-wp-enforced-sizes -amp-element -amp-error -amp-element-error -amp-layout" src="/wp-content/uploads/third-image-in-body.jpg" alt="third image in body" width="100%" height="auto" srcset="/wp-content/uploads/third-image-in-body.jpg 1920w, /wp-content/uploads/third-image-in-body-569x320.jpg 569w" sizes="(min-width: 100px) 100px, 100vw"><img src="/wp-content/uploads/third-image-in-body-569x320.jpg" class="-amp-fill-content -amp-replaced-content" alt="third image in body" amp-img-id="AMP_6" width="100" height="0"></amp-img>
```

I also see that it's sizing the image to 100px? Is there anyway I can override the <amp-img> tag?
