### ISSUE TITLE
Additional styling and customizations for default template

### ISSUE THREAD

**Issue by ericlindley-g** [Automattic/amp-wp#386]
(pending #199)

Suggested template mocks below, with three variations, based on what the publisher has hypothetically supplied/specified: one with a hero image at the top of the page, one without, and one without a publisher avatar image or logo.

Additional requests not shown in the mocks
- Hide the category if none is specified (so "uncategorized" doesn't show)
- If the publisher can't specify a banner logo at the top of the page, enable specifying a font color and background color for their publication title

![amp-template](https://cloud.githubusercontent.com/assets/16807766/15060505/009342d6-12e0-11e6-83e1-9418f6fd92db.png)

**Comment by westonruter** [comment]
This is obsolete now that the plugin encourages users to re-use their existing active theme in AMP.
