### ISSUE TITLE
amp-twitter tag not rendering

### ISSUE THREAD

**Issue by alvin-milton** [Automattic/amp-wp#388]
Example:
http://thebuilderacademy.nyc/twitter-amp-test/amp/

**Comment by jamesabruce** [comment]
Works fine for me. Are you using the standard wordpress embed, by just posting the link to the tweet? Or have you used the full embed code from twitter? You need to use the former, as AMP is going to strip out all scripts from the content. 

![screen shot 2016-05-23 at 18 20 56](https://cloud.githubusercontent.com/assets/2298025/15478599/24f944f4-2113-11e6-8ba0-a936815d1093.png)

**Comment by alvin-milton** [comment]
@jamesabruce Your assessment is correct. Using the plain link will produce the amp-x equivalent. Main problem is at this point that I have a lot of content that is using the social embed so these are not rendering the amp equivalent for these embeds.

**Comment by mjangda** [comment]
We currently only support the OEmbed and shortcode versions of tweets.
