### ISSUE TITLE
Google Analytics Adsense revenues

### ISSUE THREAD

**Issue by yofisim** [Automattic/amp-wp#393]
Hi,
we successfully installed AMP on our blog, and we are running adsense + revcontent ads, with no errors. We have also linked analytics account, and it's running ok.
 
Nevertheless, we have a problem with the analytics data being sent.
For some reason, we can see all the data, but we can't see adsense revenues from AMP within Analytics, and we are seeing the revenues on the adsense Panel.
 
How are we getting these results inside the analytics?
Is this a bug, or should we do something to get this data on analytics panel?
 
Thanks,
 
Simon

PS: we have also asked Analytics comunity forum [here](https://www.en.advertisercommunity.com/t5/Code-Implementation/Adsense-Revenues-from-AMP-inside-Analytics/m-p/555642)

URL for test:  http://www.instylebuzz.com/the-10-most-expensive-celebrity-divorces/amp

![analytics1](https://cloud.githubusercontent.com/assets/5214009/15467527/a4d4e24a-20e7-11e6-8c29-2d65d465c3c6.png)

**Comment by mjangda** [comment]
You'll need to chat with AdSense as the plugin doesn't have much to do with ads/analytics here.
