### ISSUE TITLE
Support for canonical AMP (AMP only)

### ISSUE THREAD

**Issue by pbakaus** [Automattic/amp-wp#394]
We, the AMP team, recently started to feel confident enough to encourage sites to build their sites directly for AMP. This means that instead of having a 'full' canonical page and an AMP page associated with it, you'd simply build your whole site with AMP.

I have a blog post coming talking in detail about our reasoning and strategy behind this (mostly centered around preventing the problems that m.dot sites bring), but I'd love to see support for it in amp-wp.

This would require the following:

1) Transform the default post output to AMP (i.e. img to amp-img)
2) First-class support for AMP components in the editor

Would love to hear what you think, and if feasible. Happy to work with you on a PR.

**Comment by mjangda** [comment]
Sounds like a logical future path for the plugin. We've chatted about WordPress themes built entirely with AMP, which is a pretty cool idea. Of course, there are some (fun) challenges in the way :)

Would love to hear more about what you have in mind. Want to ping me to chat further? Hangouts (batmoo@gmail.com) or Skype (mjangda) are probably easiest ways to reach me.

**Comment by pbakaus** [comment]
Sure! Send you an invite to chat on Hangouts :)

**Comment by pbakaus** [comment]
@mjangda I just took a stab at adding this functionality and it all seems to be working. Have a look at the PR here: https://github.com/Automattic/amp-wp/pull/425

**Comment by amedina** [comment]
Closing this one (duplicate); see https://github.com/Automattic/amp-wp/issues/425, and https://github.com/Automattic/amp-wp/pull/668
