### ISSUE TITLE
logo bug 

### ISSUE THREAD

**Issue by lubimow** [Automattic/amp-wp#396]
Google just sent a message that an error: Logo Target Missing

how do I fix it?

see: http://bit.ly/1TR6CPQ

**Comment by mjangda** [comment]
Please see https://github.com/Automattic/amp-wp#site-icon

**Comment by lubimow** [comment]
@mjangda 
I did so, but there is no markup logo.
http://screenshot.net/6dd8fq6
Please see this link https://goo.gl/XJztiO
