### ISSUE TITLE
Google Search Console reports illegal prefix being used in classes

### ISSUE THREAD

**Issue by steckinsights** [Automattic/amp-wp#404]
We're seeing errors from Google Search Console regarding our CSS styling.  Apparently, they don't allow the use of any CSS class that begins with the "AMP" prefix.  Because the Automattic AMP plugin has labeled all classes using this prefix (e.g. "amp-wp-title-bar"), we need to modify the plugin to operate within Google's parameters.

If it would be a help, I can go through the plugin and submit a pull requests for updated element classes, but just wanted to see if anyone had any thoughts on this issue.

The error we're receiving in the Google Search Console is:

> The text (CDATA) inside tag 'style amp-custom' contains 'CSS -amp- class name prefix', which is disallowed.

**Comment by mjangda** [comment]
Thanks for flagging. We should update the classes to `wp-amp` (or something similar) instead.

**Comment by mjangda** [comment]
A PR would definitely be appreciated!

**Comment by steckinsights** [comment]
May have found the issue, and potentially isn't the plugin's issue. One of the styles were were referencing was using the "-amp" prefix. We switched the way we were selecting that element and I'm going to watch Google Search Console to see if that changes the way they index the pages and account for errors.

I'll update once I determine that this is the case.
