### ISSUE TITLE
The tag 'script' is disallowed except in specific forms.

### ISSUE THREAD

**Issue by aniskhan001** [Automattic/amp-wp#405]
Google Search Console reports there is some **User-authored JavaScript found on page**.
But I believe currently there is none with my page.
Example url: http://futurism.com/apotd-sharpest-view-of-ngc-1300/amp/

I don't know the exact problem at this moment.
But could be related to this? https://github.com/ampproject/amphtml/issues/2966

**Comment by mjangda** [comment]
It's due to the newrelic script that's being automatically added to the page. I'd suggest disabling it for AMP content.

**Comment by aniskhan001** [comment]
The newrelic script was not included on the reporting date. Added later for some internal testing. I will update the ticket if I found any clue.

**Comment by EmpowHERRyan** [comment]
Having the same issue. Both valid amp scripts in head (ads and analytics), but validator fails. If I remove them, it validates ok. Any luck?

**Comment by ymkjp** [comment]
There is a PHP API [`newrelic_disable_autorum`](https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-api#api-rum-disable) to disable NewRelic by each request. And I found a plugin [***disabled-newrelic-for-amp***](http://wordpress.org/plugins/disabled-newrelic-for-amp/) to do this working with *amp-wp*.

Note that the address above disables all monitorings but not only browser's. According to [New Relic Documentation](https://docs.newrelic.com/docs/agents/php-agent/attributes/php-agent-attributes), browser-only disabling is supposed to be available.
