### ISSUE TITLE
Please help me with Validation Errors?

### ISSUE THREAD

**Issue by anirudhpulikonda** [Automattic/amp-wp#411]
I'm getting these Validation errors when I checked my AMP page:

>   
The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value '//fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic|Open+Sans:400,700,400italic,700italic'. AUTHOR_STYLESHEET_PROBLEM
line 7, column 0
>  
The attribute 'src' in tag 'amp-analytics extension .js script' is set to the invalid value '//cdn.ampproject.org/v0/amp-analytics-0.1.js'. CUSTOM_JAVASCRIPT_DISALLOWED
line 8, column 0
>  
The tag 'script' is disallowed except in specific forms. CUSTOM_JAVASCRIPT_DISALLOWED
line 35, column 0
>  
The mandatory tag 'amphtml engine v0.js script' is missing or incorrect. MANDATORY_AMP_TAG_MISSING_OR_INCORRECT
line 122, column 7
>  
The tag 'amp-analytics extension .js script' is missing or incorrect, but required by 'amp-analytics'. AMP_TAG_PROBLEM
line 122, column 7

I've tried to fix these errors in this Validator : https://validator.ampproject.org/#url=https%3A%2F%2Fwww.watchmetech.com%2Fjetpack-photon-decrease-seo%2Famp%2F

I've observed that all the src and href tags are starting with "//url" format then I've replace those tags with "https://URL" format and boom my errors are fixed in Validator.

Please help to make this change permanent. 
For reference:
canonical URL: [https://www.watchmetech.com/get-backlinks-using-disqus-comments/](url)
AMP URL: [https://www.watchmetech.com/get-backlinks-using-disqus-comments/amp](url)

**Comment by mjangda** [comment]
Sounds like a conflict with another plugin that's modifying the output of AMP pages (maybe a caching plugin?). Best option is to disable it for any URLs that end in `/amp/?`

**Comment by anirudhpulikonda** [comment]
I'm using wp super cache plugin. is this the problem? if it is can you please suggest me how to disable for /amp URL's ?

**Comment by anirudhpulikonda** [comment]
I've fixed them by disabling CloudFlare's HTTPS Rewriting. But I'm unable figure out how to use my CloudFlare SSL

**Comment by anirudhpulikonda** [comment]
I've disabled CloudFlare HTTPS rewriting in plugin settings and I got all my Validation errors fixed. but I'm not getting the Secure connection like Previous due to CloudFlare's disabling please Help

**Comment by mjangda** [comment]
You'll probably have to talk to Cloudflare about that as I'm not familiar with their plugin.

**Comment by rjtamayo** [comment]
Thanks for this tip. I'd encountered this one. Sam issue, caused by a caching plugin which removes schemes from all URL (HTTP and HTTPS).
