### ISSUE TITLE
Prohibited HTML Tag: comments-count

### ISSUE THREAD

**Issue by m0sagal** [Automattic/amp-wp#416]
How to remove html tag from AMP pages , i got that from google webmasters " Prohibited or invalid use of HTML Tag" and the disallowed tag is 'comments-count' , how to fix it?

![amp](https://cloud.githubusercontent.com/assets/7596513/16554593/3001eaee-41d0-11e6-82a7-71fa4aae7170.png)

**Comment by OPPtester** [comment]
Stumbled on something similar:

validator.js:400 http://www.opptrends.com/2016/05/mcdonalds-ceo-doesnt-see-15-hourly-wage-robots-killing-jobs/amp/:319:397 The attribute 'b' may not appear in tag 'a'.

http://www.opptrends.com/2016/05/mcdonalds-ceo-doesnt-see-15-hourly-wage-robots-killing-jobs/amp/#development=1&filter=DISALLOWED_HTML
