### ISSUE TITLE
Invalid CSS stylesheet errors

### ISSUE THREAD

**Issue by jattsaini** [Automattic/amp-wp#421]
Hope there,

Just checked that my wmt tools amp page has suddenly started showing 800+ invalid css stylesheet errors. Why such errors suddenly? 

There was no update to plugin and I also hasn't made any changes to amp codes or theme codes.

Example urls: 

Please help.

**Comment by jattsaini** [comment]
Example urls: http://www.timesnews.co.uk/7151-huawei-honor-7x-now-tenaa-approved-with-3gb-ram-and-5-5-inch-display/amp/

http://www.timesnews.co.uk/2279-kitchen-design-ideas-for-your-home/amp/

And many more.

**Comment by rapidbi** [comment]
I also have this issue - it seemed to start on 19 July. Each day I get an increase in errors.
One example is https://rapidbi.com/swotanalysis/
or more accuratly https://rapidbi.com/swotanalysis/amp

**But when I run the validator -** https://validator.ampproject.org/#url=https%3A%2F%2Frapidbi.com%2Fswotanalysis%2Famp%2F&filter=AUTHOR_STYLESHEET_PROBLEM
I get a pass. This is true on the 500+ pages that now have errors. The pages that error out are increasing daily.

**The actual error message is:**
The author stylesheet specified in tag 'style amp-custom' is too long - we saw 53577 bytes whereas the limit is 50000 bytes.
and yet nothing has changed on the site for weeks.

Does anyone have any ideas on this?

**Comment by pppdog** [comment]
hi

Perhaps you be used firefox detecting  [(view-source:https://rapidbi.com/swotanalysis/)] code source,you will find.

**Comment by mjangda** [comment]
The custom CSS being added pushes the the total size of the CSS beyond what's allowed. I'd suggest removing unnecessary rules to get the size of the CSS down to what's allowed.

**Comment by GalynaCh** [comment]
Hi, guys! 
I've just implemented AMP plugin for the Wordpress (on this website: [https://perfectial.com/](https://perfectial.com/)) for blog articles. But when I'm testing my markup via Google AMP Testing Tool, I see an issue "Invalid CSS stylesheet" ([https://search.google.com/test/amp?id=bIZMZc3Z_AyT1XgyBJZsQQ](https://search.google.com/test/amp?id=bIZMZc3Z_AyT1XgyBJZsQQ)). How can I fix it?
