### ISSUE TITLE
Missing include v0.js from AMP Project

### ISSUE THREAD

**Issue by marcelorodrigo** [Automattic/amp-wp#423]
I got the plugin and installed on my wordpress project.
After next scanning from Google, I received a report complaining about my AMP pages because they don't follow AMP guidelines.

One of them is that my HTML does not contain a <script async src="https://cdn.ampproject.org/v0.js"></script> tag inside head tag.

More info: https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#scrpt

**Comment by mjangda** [comment]
Can you share an example URL?

**Comment by marcelorodrigo** [comment]
If you look at the source, you can see plugin including by this tag:
`<script src="//cdn.ampproject.org/v0.js" async></script>`

But the Google Bot follow specs that demands the use of HTTPS protocol, explicitly:
`<script async src="https://cdn.ampproject.org/v0.js"></script>`

We know that there is no difference - in practice - but the Google bot see that difference :)

Sample URL: http://marcelorodrigo.com/fail-comunicating-private-docker-insecure-registry.html/amp

**Comment by leearmstrong** [comment]
I am having this issue as well where the URL is being changed from https to "//"

I've disable a ton of other plugins and it still happens!  Validation then fails

**Comment by tmac187** [comment]
Same issue here...

**Comment by mjangda** [comment]
The plugin is outputting schemes correctly, so you'll need to track down and turn off whatever is transforming schemes from `http(s)://` => `//` for AMP pages.
