### ISSUE TITLE
Ordered lists not rendering correctly

### ISSUE THREAD

**Issue by ucallrt** [Automattic/amp-wp#424]
Ordered lists are not being rendered correctly by the plugin. 

While the theme displays them correctly, in the render created by the plugin, every list item in the post starts with '1.'
![ordered_list](https://cloud.githubusercontent.com/assets/9826142/17065917/6efa37b0-5012-11e6-87d2-3f8089b0b424.png)

**Comment by mjangda** [comment]
Can you share a URL for the broken post?

**Comment by ucallrt** [comment]
Yes, view tinyurl.com/jrgaz7z on a mobile device.

**Comment by mjangda** [comment]
The AMP version here looks fine: http://www.bikeworldnews.com/2016/07/22/2016-tour-de-france-stage-19-results/amp/

Based on the URL, it might be an issue with Pagefrog?

**Comment by ucallrt** [comment]
What is pagefrog? I don't have a plugin by that name.

**Comment by ucallrt** [comment]
Also, it's rendering incorrectly in Automattic's AMP plugin 'preview' window (as seen in the original screenshot that I attached).

**Comment by mjangda** [comment]
> Automattic's AMP plugin 'preview' window

I'm not really sure what this is. Can you post a full screenshot?

So here's how I'm testing:

- Starting here: http://www.bikeworldnews.com/2016/07/22/2016-tour-de-france-stage-19-results/
- The source shows the `amphtml` link as `http://www.bikeworldnews.com/2016/07/22/2016-tour-de-france-stage-19-results/amp/`
- Visit that AMP URL ^^
- Verify that the ordered list renders correctly.

It also looks fine on the AMP Cache: https://cdn.ampproject.org/c/www.bikeworldnews.com/2016/07/22/2016-tour-de-france-stage-19-results/amp/
