### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by Ciklum-marketing** [Automattic/amp-wp#426]
Hi. We have page which can't pass google search validation:
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.ciklum.com%2Fblog%2Fecommerce-needs-know-personalization-big-data%2Famp%2F&filter=AMP_LAYOUT_PROBLEM
(The mandatory attribute 'height' is missing in tag 'amp-img'.)

The issue is that if you go to this page with #development=1, it says "AMP validation successful.":
https://www.ciklum.com/blog/ecommerce-needs-know-personalization-big-data/amp/#development=1

I've figured out that somehow direct page visit adds height attribute to amp-page, and doesnt on google validation tool.

**Comment by mjangda** [comment]
That's super odd. Do you have anything on your site or server that modifies the output of the page based on user agent?

**Comment by Ciklum-marketing** [comment]
@mjangda yes we have, to show different layout of blog posts to mobile devices (we are using wp_is_mobile()), but it doesnt influence plugin.

Also, can that be a problem, that on mobile devices those problem images are wrapped in <p> tag?

**Comment by mjangda** [comment]
Being wrapped a `<p>` tag shouldn't make a difference. The issue is that something is stripping off attributes based on context and you'll need to track down what that is to fix the issue.
