### ISSUE TITLE
HTTP/1.1 400 Bad Request: failed to open stream: HTTP request failed! 

### ISSUE THREAD

**Issue by shakaran** [Automattic/amp-wp#427]
Hi, I am trying the WP plugin for AMP in the blog http://iberopistacho.com/blog and the original article is http://iberopistacho.com/blog/2016/08/01/el-pistachero-y-la-veceria/

The AMP version is:
http://iberopistacho.com/blog/2016/08/01/el-pistachero-y-la-veceria/amp/

I am getting the following warning in WP header:

```
Warning: fopen(http://i0.wp.com/iberopistacho.com/blog/wp-content/uploads/2016/03/PISTACHO-PORTE-ÁRBOL._con_logo.jpg?resize=1024%2C768): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in /home/iberopis/public_html/blog/wp-content/plugins/amp/includes/lib/class-fastimage.php on line 31
```

The WP image resized is displaying well here:

http://i0.wp.com/iberopistacho.com/blog/wp-content/uploads/2016/03/PISTACHO-PORTE-ÁRBOL._con_logo.jpg

And here with params:
http://i0.wp.com/iberopistacho.com/blog/wp-content/uploads/2016/03/PISTACHO-PORTE-ÁRBOL._con_logo.jpg?resize=1024%2C768

The VPS hosting the website has fully access to resolve i0.wp.com with IP 192.0.77.2, so I don't know if is probably some problem with accents (árbol = tree in spanish) or some kind similar issue. Could you give me a clue for this?

**Comment by mjangda** [comment]
Should be fixed as of #480
