### ISSUE TITLE
Jetpack instagram embed

### ISSUE THREAD

**Issue by jlapitan** [Automattic/amp-wp#428]
When using jetpack shortcode for IG embed and created a post with sample content below:

`[instagram url=https://www.instagram.com/p/BIyO4vXjE6b/?taken-by=natgeo hidecaption=true]`

amp plugin  generates part of the content

data-shortcode="BIyO4vXjE6b/"

i edit class-amp-instagram-embed.php, and on **render function**, i just add rtrim

`	public function render( $args ) {
		$args = wp_parse_args( $args, array(
			'url' => false,
			'instagram_id' => false,
		) );

		if ( empty( $args['instagram_id'] ) ) {
			return AMP_HTML_Utils::build_tag( 'a', array( 'href' => esc_url( $args['url'] ), 'class' => 'amp-wp-embed-fallback' ), esc_html( $args['url'] ) );
		}

		$this->did_convert_elements = true;

		return AMP_HTML_Utils::build_tag(
			'amp-instagram',
			array(
				'data-shortcode' => rtrim($args['instagram_id'],"/"), #remove trailing slash
				'layout' => 'responsive',
				'width' => $this->args['width'],
				'height' => $this->args['height'],
			)
		);
	}`

**Comment by mjangda** [comment]
Thanks for the report. We should probably fix the regex that extracts the shortcode to not include the `/` (although, it looks like it might already, so may need some testing).

https://github.com/Automattic/amp-wp/blob/master/includes/embeds/class-amp-instagram-embed.php#L8
