### ISSUE TITLE
The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.

### ISSUE THREAD

**Issue by spflanag10** [Automattic/amp-wp#429]
My AMP sites are not being validated. How do I fix?
<style type="text/css">img.wp-smiley,img.emoji{display:inline!important;border:none!important;box-shadow:none!important;height:1em!important;width:1em!important;margin:0 .07em!important;vertical-align:-0.1em!important;background:none!important;padding:0!important;}</style>

**Comment by mjangda** [comment]
AMP CSS does not allow the use of `!important`. You'll need to adjust those custom styles accordingly.

**Comment by mariaoneclick** [comment]
use <style amp-custom>
