### ISSUE TITLE
AMP validation fails when using WPML Multilingual CMS plugin

### ISSUE THREAD

**Issue by 50bbx** [Automattic/amp-wp#43]
This is because it adds stylesheet to the head of the page. That can be easily fixed with `define( 'ICL_DONT_LOAD_LANGUAGE_SELECTOR_CSS', true);` when rendering the AMP version of the page.

**Comment by mjangda** [comment]
What hook is the CSS output on (I don't have access to the WPML code)? We don't fire any standard template-related actions, so it's a bit weird that WPML would be outputting stuff.

**Comment by 50bbx** [comment]
This css is not enqueued but is directly printed on page, that's why  you don't see it. This is the code:

    function icl_lang_sel_nav_css($show = true){
        if(defined('ICL_DONT_LOAD_LANGUAGE_SELECTOR_CSS') && ICL_DONT_LOAD_LANGUAGE_SELECTOR_CSS){
            return '';
        }
        $link_tag = '<link rel="stylesheet" href="'. ICL_PLUGIN_URL . '/res/css/language-selector.css?v='.ICL_SITEPRESS_VERSION.'" type="text/css" media="all" />';
        if(!$show && (!isset($_GET['page']) || $_GET['page'] != ICL_PLUGIN_FOLDER . '/menu/languages.php')){
            return $link_tag;
        }else{
            echo $link_tag;
        }
		return $link_tag;
    }

I don't remember why they are not enqueuing the style, but there was a reason for this. So they created the constant `ICL_DONT_LOAD_LANGUAGE_SELECTOR_CSS` to let people control this output.

**Comment by mjangda** [comment]
Closing; this is something WPML should fix.
