### ISSUE TITLE
Images not showing on AMP

### ISSUE THREAD

**Issue by karanbhagat95** [Automattic/amp-wp#431]
I installed AMP by automattic and Glue Yoast plugin.
With Glue plugin installed I get an error : "The tag 'script' is disallowed except in specific forms."

When I uninstall this plugin then it shows no error but still there are two issues:
1.) No adsense ads.
2.) No post images.

I have heard that ads will not show up but why are images not being displayed, it shows empty spaces instead.

Any help over this?
You can check out the website [here](http://www.focusandleap.com/).

**Comment by mjangda** [comment]
I see images showing up here: http://www.focusandleap.com/free-mp3-music-download/?amp=1

If you're still having issues, can you re-open the issue with a broken URL?
