### ISSUE TITLE
AMP work fine with WP Posts and No result for WP Pages

### ISSUE THREAD

**Issue by medilef** [Automattic/amp-wp#433]
here is an exemple : 

Post : http://www.chirurgie-esthetique-sans-intermediaire.com/epilation-laser-tunisie/amp/ ==>Ok
Page : http://www.chirurgie-esthetique-sans-intermediaire.com/clinique/amp/ ==> Nothing

Is there any solution, Thank you.

**Comment by mjangda** [comment]
Dupe #176
