### ISSUE TITLE
AMP pages not showing up...

### ISSUE THREAD

**Issue by TakeMagazine** [Automattic/amp-wp#434]
Hello, We are using your AMP plugin on www.theTakeMagazine.com which is a WP site. Everything seems to be setup OK. When you look at the blog posts with /amp you see an AMP page. I installed a AMP validation extension in my browser and it verifies the AMP page. But when I go to the Google AMP report (https://support.google.com/webmasters/answer/6328309) it says there are no AMP pages on the site. Any insight to this issue would be most helpful.
Thx
Eric Olsson

**Comment by mjangda** [comment]
Everything looks fine with the AMP content on the site. The only thing I can suggest is to try having Google re-crawl your content as noted here: https://support.google.com/webmasters/answer/6065812

Other than that, you'll likely need to talk to Google Webmaster Support.
