### ISSUE TITLE
Navigation menu doesn't appear

### ISSUE THREAD

**Issue by Taig7** [Automattic/amp-wp#435]
Hi!

The navigation menu doesn't appear on my AMP article on my mobile phone. I am only on my article and i can't navigate. Can you help me?

Theme: Fourteenpress.
Website: no communicated (for adults. Ask me in private)

Cordialy,

Vincent

**Comment by mjangda** [comment]
The plugin currently doesn't support nav menus, see #220

**Comment by westonruter** [comment]
Here is a basic plugin which can be used to add a nav menu sidebar on Reader mode templates: https://gist.github.com/westonruter/b22cfae13f0862d5b9716c776c60f882
