### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by shivampaw** [Automattic/amp-wp#441]
A few issues I've found are:

1) `<html amp>` can there be a place for language declaration? 

2) no meta descriptions? I know you have JSON implemented but still, shouldn't you have the meta tag?

3) if a post contains a plain link (no anchor text) the link isn't being linked. Example here: https://www.depressionforteens.com/how-to-explain-your-depression/amp/ Above the "Having The Conversation" heading.

**Comment by mjangda** [comment]
Can you please open a separate Github Issue for each point?

**Comment by mjangda** [comment]
Sorry, I should have also said thanks for reporting these. 1 and 3 sound like things we should fix, however 2 should probably be handled by other plugins but we can discuss further if you want to open a new ticket.
