### ISSUE TITLE
Use constants in AMP_Allowed_Tags_Generated

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4536]
## Feature description

While trying to investigate the reason for #4465, I noticed that the constants being used within the protoascii files are reverted to meaningless scalar values in the generated PHP files.

The PHP files should make use of defined constants like the ones defined in `AmpProject\Layout` or similar, so that it becomes much easier to reason about the generated rules.

#### Example before (extract):

```php
'amp-audio' => array(
array(
    'tag_spec' => array(
        'amp_layout' => array(
            'defines_default_height' => true,
            'defines_default_width' => true,
            'supported_layouts' => array(
                2,
                3,
                1,
            ),
        ),
    ),
),
```

#### Example after (extract):

```php
'amp-audio' => array(
array(
    'tag_spec' => array(
        'amp_layout' => array(
            'defines_default_height' => true,
            'defines_default_width' => true,
            'supported_layouts' => array(
                Layout::FIXED,
                Layout::FIXED_HEIGHT,
                Layout::FILL,
            ),
        ),
    ),
),
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All constants defined in protoascii should translate to constants defined in PHP.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Doing this would be complicated given the current spec generator, which takes a data structure and then just does `var_export()`. This may make most sense to tackle as part of #3875.

**Comment by westonruter** [comment]
Being worked on as part of #3730.

**Comment by westonruter** [comment]
Implemented in https://github.com/ampproject/amp-toolbox-php/pull/100
