### ISSUE TITLE
Avg. Time on Page = 0 in Google Analytics, for organic traffic

### ISSUE THREAD

**Issue by nicopujol** [Automattic/amp-wp#454]
We are able to track AMP pages in google analytics including the main elements/variables when a user goes directly to a given AMP URL on our site. However, for organic search visitors Google caches the AMP pages, which results in Google Analytics reporting the visit itself, however all organic traffic shows Avg. Time on Page = 0. Concerned that this could create negative stats that feed back to SEO and search rankings, with the engines thinking the user left immediately. The fact that a direct visitor to the AMP page reports the correct Avg. Time on Page suggests our tracking code is working. It seems the Google cache for AMP pages loses that data.

We use a mobile child theme with tracking code in the child theme's functions.php file with sample code attached.
[sample AMP page GA tracking code in functions php file.txt](https://github.com/Automattic/amp-wp/files/435761/sample.AMP.page.GA.tracking.code.in.functions.php.file.txt)

**Comment by mjangda** [comment]
Have you tried validating that your pages work correctly with the AMP Cache? https://www.ampproject.org/docs/get_started/about-amp.html#google-amp-cache

Outside of that, this is probably an issue for Google Analytics team?

**Comment by nicopujol** [comment]
Thanks @mjangda, we do use the AMP validation tools which return a PASS result with no error. I suspect the validation tools do not catch edge issues like this. Given AMP is tightly integrated with Google it would be great if the AMP plugin for WordPress could bundle a validated tracking code for Google Analytics given all users need to custom code this tracking today.

**Comment by lkraav** [comment]
I'm also wondering if https://wordpress.org/plugins/amp-analytics/ is the current way to go or...

**Comment by amedina** [comment]
Closing since it is an Analytics issue.

**Comment by saleemkce** [comment]
@nicopujol [time on site](https://saleemkce.github.io/timeonsite/) is what you need to find users data for time spent
