### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by intelezsol** [Automattic/amp-wp#455]
My site is techwhack.com and amp pages are not validating properly.

**Comment by intelezsol** [comment]
#The validator is showing these errors
![screencapture-validator-ampproject-org-1472302953990](https://cloud.githubusercontent.com/assets/20015363/18027578/614e5c56-6c85-11e6-9382-325f47cd1963.png)

  
The attribute 'vocab' may not appear in tag 'div'. DISALLOWED_HTML
line 43, column 25
  
The attribute 'property' may not appear in tag 'div'. DISALLOWED_HTML
line 43, column 72
  
The attribute 'property' may not appear in tag 'div'. DISALLOWED_HTML
line 43, column 187
  
The attribute 'property' may not appear in tag 'span'. DISALLOWED_HTML
line 43, column 244
  
The attribute 'property' may not appear in tag 'span'. DISALLOWED_HTML
line 43, column 292

Please tell me how to fix or please update this plugin.

**Comment by amedina** [comment]
This may be related to the use of another plugin that is adding the attribute to the div tags.
