### ISSUE TITLE
 Cursor Change on Hover for AMP Images

### ISSUE THREAD

**Issue by GiNgesIo** [Automattic/amp-wp#4552]
## Feature description

I am using standard mode so my website is AMP first. It would be nice though if desktop users would se a cursor change on hover for AMP images

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Can you share the URL for your site where this issue can be seen? A quick fix would be to add a CSS rule to add `cursor:pointer`. Otherwise, this may be a better issue for upstream on the amphtml project itself.

**Comment by GiNgesIo** [comment]
paulreno.de is my website. I just felt that a pointer on linked image is common on desktop websites and should be implemented in the plugin for all who use AMP first sites.

**Comment by westonruter** [comment]
Yes, that does make sense. In the meantime, you can add CSS like this:

```css
amp-img[lightbox] {
    cursor: pointer;
}
```

You can add this to the Customizer's Additional CSS section, though as you noted in #4551 the preview is messed up.

**Comment by westonruter** [comment]
I've submitted your feature request upstream: https://github.com/ampproject/amphtml/issues/27646

**Comment by GiNgesIo** [comment]
Thank you!
