### ISSUE TITLE
Deprecate AMP Layout settings

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4554]
## Feature description

The AMP Layout setting is a [source of confusion](https://wordpress.org/support/topic/no-display-images-bug/):

![image](https://user-images.githubusercontent.com/134745/78844309-3b0ff180-79ba-11ea-9aef-bdea4b0a5f4e.png)

Why would anyone want, for example, to set a block to have “no display”? It hides the block from the editor and from the AMP version of the page, but on the AMP version it is visible. That's not helpful. The other layout options are similarly problematic as they would apply to the AMP version of the page, and they won't display properly in the editor either.

Layout is not being exposed here at the right level of abstraction. Rather, there is no abstraction at all. The layout should be managed via the block itself seamlessly with how the block exposes its own layout options.

So I suggest that we remove the toggle entirely, _unless_ the block currently has the setting specified. This will allow existing blocks to manipulate the layout, but for newly-added blocks the setting would go away.

We also want to minimize “AMP” anywhere in the UI. It's not something that authors should need care about at all.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
**Backlog Notes:**

* Too low level for authors, and they get confusing. If you select no display as a display type the block disappears, not helpful. In the chance that someone is still using it we may want to conditionally show it in case they have used it already. Maybe hide it, remove it for new posts, or any post that doesn’t use this, otherwise show it. 
* Maybe say it’s deprecated, but probably overkill. Safer to conditionally remove.

**Comment by pierlon** [comment]
Also seems to be broken in the latest edition of Gutenberg (v8.9.3):

![image](https://user-images.githubusercontent.com/16200219/93235541-3ae7ff00-f76d-11ea-9e0b-cf96e4201fa7.png)

**Comment by westonruter** [comment]
I'm seeing the same breakage:

![image](https://user-images.githubusercontent.com/134745/93251306-dca92500-f748-11ea-91d4-a0d598d7eef9.png)

**Comment by inaikem** [comment]
> * Too low level for authors, and they get confusing. If you select no display as a display type the block disappears, not helpful. In the chance that someone is still using it we may want to conditionally show it in case they have used it already. Maybe hide it, remove it for new posts, or any post that doesn’t use this, otherwise show it.

Agreed. Super confusing, in fact. Especially considering that after you apply the setting and navigate away to another block, 
the only way it can be made visible again is to go into the Code editor and set `"ampLayout"` to `ampLayout:"default"`. 

I recorded a screencast here: https://d.pr/v/d6Eex5

If the plan is to keep the setting, can we please keep the affected block visible in the editor if "No Display" is selected? Even better, reduce the block's opacity if possible?

**Comment by westonruter** [comment]
> If the plan is to keep the setting, can we please keep the affected block visible in the editor if "No Display" is selected? Even better, reduce the block's opacity if possible?

I'm confident we will eliminate the setting entirely.

**Comment by westonruter** [comment]
**QA Passed**

I created a post with the following content when on 2.0.11:

```html
<!-- wp:image {"id":104,"sizeSlug":"large","linkDestination":"none","ampLayout":"responsive","ampNoLoading":true} -->
<figure class="wp-block-image size-large"><img src="https://wordpress-stable.lndo.site/wp-content/uploads/2021/04/American_bison_k5680-1-1200x783-1-1024x668.jpg" alt="" class="wp-image-104"/></figure>
<!-- /wp:image -->
```

When upgrading to 2.1, I saw as expected that the layout a deprecation notice:

![image](https://user-images.githubusercontent.com/134745/115982452-08e31a80-a550-11eb-87ed-8485912abd26.png)

And when I added a new image the layout setting is absent as expected:

![image](https://user-images.githubusercontent.com/134745/115982443-e94bf200-a54f-11eb-817b-108e62990717.png)
