### ISSUE TITLE
Reader Mode Expansion

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4559]
Expand the capabilities of the Reader Mode to provide:

- **Turn-key solution**: publishers (no tech skills required) can leverage AMP content strategies on WordPress with maximum visual/functional parity between AMP and non-AMP content in terms of  proper branding, configurability, and a baseline feature richness

- **Intuitive onboarding flows**, making it easier to install and activate the plugin, and understand the kind of AMP experiences that can be enabled (e.g. reader mode, AMP-first)

- **Effective workflows making it easy to stay AMP-compatible**, helping users to maintain the coverage and quality of their AMP content by providing guidance during plugin and theme installation actions

**Comment by westonruter** [comment]
Closing as resolved
