### ISSUE TITLE
Plugin not using custom filters in function.php

### ISSUE THREAD

**Issue by GavinMannion** [Automattic/amp-wp#456]
I've got some custom filters setup in my functions.php to ensure FTC compliance etc and I just noticed that this plugin is ignoring them.

My filter code is here, http://pastebin.com/LVRrNBSB, you can see it's very straight forward and just adds a disclaimer to the article if it's been sponsored.

Here it is working on a normal article
http://www.lazygamer.net/24/sponsored-post-ten-great-xbox-360-deals-that-you-can-find-right-now/

but if I view the AMP version it doesn't show?
http://www.lazygamer.net/24/sponsored-post-ten-great-xbox-360-deals-that-you-can-find-right-now/amp

Anyway to ensure it picks up my filters?

**Comment by mjangda** [comment]
You need to pass the post object or id as the second param for `in_category`.

**Comment by GavinMannion** [comment]
Changed it to

`if(is_single() && in_category('Sponsored Content', $post)) {`

Still not working
