### ISSUE TITLE
Allow Reader Mode users to chose a theme from a curated list

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4560]
Upon activating the plugin and/or selecting Reader Mode, the user will be provided with a set of pre-defined themes to chose from (a subset of themes in ecosystem page)

**Comment by westonruter** [comment]
@johnwatkins0 Assigning this to you since this is what you built as part of the wizard (#4702) and also what you'll be adding to the admin settings screen (#4704).

The plumbing of actually loading the selected Reader theme is what I'm working on in #4478.

**Comment by westonruter** [comment]
As noted in #4984, when selecting a non-legacy theme in Reader mode, the same UI to “show all templates as AMP” and the ability to select individual templates needs to be offered. These options should be disabled when the Legacy theme is selected.
