### ISSUE TITLE
Add capability to export validation errors for a given URL in JSON format

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4562]
- A user of the plugin can export the validation issues into JSON format

- This could form the basis of a communication mechanisms where users can send validation issues to their webmaster or to support forums

- A possible scenario would  be to add an "Download as JSON" button in the compatibility tool

**Comment by westonruter** [comment]
Yes, this is a good idea. Too often I've had to ask users to create screenshots, when in reality they could just provide a JSON file.

**Comment by schlessera** [comment]
Note that this already works via the CLI command. We should make sure the code used in both scenarios is the same logic, only with different triggers.

**Comment by westonruter** [comment]
Related: #5209
