### ISSUE TITLE
Turn Optimizer into a canonical PHP implementation

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4567]
We currently have a subset of the official AMP Optimizer ported to PHP and directly integrated into the plugin.

The code was set up from the start to be easy to extract into a separate PHP library. In fact, it already is a separate Composer package that is pulled in from a subfolder.

The next step is now to complete the implementation and work on required ecosystem changes so that our `AmpProject\Optimizer` can be the official PHP implementation of the canonical AMP Optimizer library (next to the Go and the Node.JS versions).

This does not only require the missing pieces of code, but also synchronizing testing across implementation in a maintainable and reliable way, clarifying naming and storage principles, and integrating with existing documentation.

**Comment by ravau** [comment]
As a developer, looking forward to it. What's an eta? I managed to extract optimizer and commons libs and publish as my own package and run the code. However it looks like it is not working well with non-wordpress code. Sorry for thrashing the thread, I want to signal that canonical library for amp optimization is very needed and will be a game changer for php devs.

**Comment by westonruter** [comment]
It's mainly a matter of naming and code organization. (Naming is hard.)

One option is to take the two libraries, common and optimizer, and create separate packages called amp-common-php and amp-optimizer-php., respectively. This was originally the plan, but I'm now leaning away from it. 

In the end does it make sense for there to be a separate common/shared/utils package? I also think that "Optimizer" may not even be a great ultimate name for the current Optimizer package. Once we have extracted the sanitizers from the AMP plugin, I think it would make sense for these to be packaged together with the Optimizer transformers. I think it would be very rare that you'd want the Optimizer but not also have the logic for ensuring you have a valid AMP document to start with. 

As such, what about just calling the package "amp-php"? This can include in itself all the classes and functions needed to do AMP processing, from conversions to sanitization to validation to optimization. This would avoid us having to agonize over where we split packages, where again, I expect these packages to always be installed together anyway.

Even if they only want to use the Validator only, they could still just use that subsystem from the one package. I mean, I think the 80% use case is for all 3 of the subsystems to be used. If someone is only interested in validation, they can use the amp-validator CLI command as well.

Also compare with the AMP Optimizer package in amp-toolbox is that it has non-Optimizer transformers as well. For example, it has transformers for `Markdown`, `AutoExtensionImporter`, and `AmpScriptCsp`: these would all be of conversion and sanitization in the the AMP plugin, and not strictly part of optimization. The AMP Optimizer allows you to just invoke the one Transformer for converting Markdown into AMP.

So, in the end I think we'll make things easier for ourselves if we just put them all in one single **amp-php** package. Then we won't have to struggle with deciding whether a transformer belongs in conversion, sanitization, or optimization. I think the reality is that these transformers will often be taking on multiple roles. For instance, an `AutoExtensionImporter` is needed both for conversion and for validation.

cc @amedina

**Comment by amedina** [comment]
+1 on `amp-php` naming convention. It might be still confusing as it may be interpreted as an implementation of the AMP library in PHP, but it is more clearly reflecting the actual functionality encompassed.

**Comment by schlessera** [comment]
If we want to go into the "1 package for everything" direction, but avoid the confusion @amedina is referring to, we could mirror the JS package and call it `amp-toolbox-php`/`amp-php-toolbox` as well.

**Comment by schlessera** [comment]
Also `amp-php` is very close to https://github.com/amphp/amp...

**Comment by westonruter** [comment]
See also `amp-library` which was a related effort on the Drupal front: https://github.com/Lullabot/amp-library

I'm not sure about `amp-toolbox-php` since it's not intended to be a port of `amp-toolbox`, but rather just the Optimizer, but to go beyond just that package to also include Conversion and Sanitization.

We could call it `amphtml-php` to disambiguate from the `ampphp` org.

Or `amp-lib-php`? I like that.

**Comment by westonruter** [comment]
As @schlessera suggested today, another option would be `amp-toolbox-php` (and `amp-toolbox` on Packagist).

**Comment by westonruter** [comment]
I like the semantics of “toolbox” being a collection of tools for AMP in PHP. My only concern would be confusion that the library is intended to be a direct port of the `amp-toolbox` JS project, which isn't the case (although there will be an intersection).

**Comment by amedina** [comment]
+1 on `amp-toolbox-php`

**Comment by schlessera** [comment]
> My only concern would be confusion that the library is intended to be a direct port of the amp-toolbox JS project, which isn't the case (although there will be an intersection).

The way I see it, it _is_ a direct port of the approach of the JS project, using a monorepo to collect all packages that share the JS ecosystem.

**Comment by marco-msg-ferrari** [comment]
From a point of view of a user, it is best to have a monorepo.
Documentation and bugs are centralized and nested repos can be difficult to navigate without investing a lot of time to understand the structure.
Furthermore, if all "components" are separated by namespaces, it will be "easy" in the future to separate them if needed.

**Comment by schlessera** [comment]
Yes, valid points. However, we also should note that an actual monorepo with separate packages is not technically possible with Composer. So while the different "components" will indeed by separated by namespaces, they will _not_ be published as separate packages within Packagist.

**Comment by westonruter** [comment]
> The way I see it, it _is_ a direct port of the approach of the JS project, using a monorepo to collect all packages that share the JS ecosystem.

That's true. It's a direct port of the approach, but not of the codebase.

> Yes, valid points. However, we also should note that an actual monorepo with separate packages is not technically possible with Composer. So while the different "components" will indeed by separated by namespaces, they will _not_ be published as separate packages within Packagist.

I think that's fine. One package with the “submodules” organized by sub-namespaces sounds great to me.

**Comment by westonruter** [comment]
Great. @amedina will request the repo to be created and we can get this going.

**Comment by westonruter** [comment]
https://github.com/ampproject/amp-toolbox-php

**Comment by schlessera** [comment]
I just tagged the very first version for the library: https://github.com/ampproject/amp-toolbox-php/releases/tag/0.1.0
