### ISSUE TITLE
Refactor validation errors

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4568]
The creation, storage, communication and presentation of validation errors has organically grown with the scope of the plugin.

Right now, validation errors are passed around as arbitrarily structured arrays that contain multiple values, and the representation needs to be manually kept in sync with the different types of errors to be able to make sense of the data structure.

The entire system around validation errors needs to be redesigned to provide a sane public interface that we can provide in the future generic PHP libraries for the sanitizer and the validator.

A good first step is the error handling in the optimizer library. This should be extracted into either the `ampproject/common` library or a separate library and expanded to cover all phases of AMP usage.

**Comment by westonruter** [comment]
Related: #3875

**Comment by westonruter** [comment]
Example of how validation error is manipulated by an array via the `amp_validation_error` filter in https://github.com/ampproject/amp-wp/issues/4753:

```php
add_filter( 'amp_validation_error', function ( $error ) {
	if (
		isset( $error['code'], $error['node_name'], $error['text'] )
		&&
		'DISALLOWED_TAG' === $error['code']
		&&
		'script' === $error['node_name']
	) {
		$error['text'] = preg_replace( '/"[0-9a-f]{10}"/', '__HEXSTR10__', $error['text'] );
	}
	return $error;
} );
```
