### ISSUE TITLE
Add performance metrics to CI

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4569]
Performance is one of the main selling points of AMP and the Amp for WordPress plugin.

In order to be able to continually improve the performance of the plugin in all the key areas, we need to define these areas and then ensure that we have continuous monitoring during development to let us know how we're doing.

**Comment by schlessera** [comment]
The key metrics we want to track are:

- [LCP - Largest Contentful Paint](https://web.dev/lcp/)
- [FID - First Input Delay](https://web.dev/fid/)
- [CLS - Cumulative Layout Shift](https://web.dev/cls/)

More info on this metrics can be found at https://web.dev/vitals/.

**Comment by schlessera** [comment]
The Chrome team has provided a library that does the same calculations that their other tooling would do for these key metrics:

https://github.com/GoogleChrome/web-vitals

**Comment by schlessera** [comment]
I'm hitting technical limitations here with the approach I have been using: Using a PHP built-in server within GitHub Actions and running the Lighthouse CI collection against that local server.

The following limitations make collecting useful information hard:
1. The built-in PHP server does not support HTTP/2, which makes all network access slower.
2. The built-in PHP server does not support .htaccess or similar, which makes WebP support impossible.
3. The built-in PHP server cannot serve over HTTPS, which makes a few AMP/PWA features impossible.
4. GitHub Actions does not provide baseline performance reliably. The differences in runtime performance of a server within GitHub Actions can vary drastically between runs, which can produces results like 1.8s performance index as well as 4.2s performance index for the exact same code. This makes the collected results for any time-based metrics unreliable and hardly useful.

As we could ignore 1., 2. & 3. for now (by skipping their respective checks), 4. is the most important limitation right now. The fluctuation between runs is so severe that I think using GitHub Actions to run the actual profiling is not an option.

This is a known issue for `lighthouse-ci`: https://github.com/GoogleChrome/lighthouse-ci/issues/251
However, the most recent release provides a way of using the `PageSpeed Insights` (PSI) tool as runner to collect the Lighthouse metrics instead. This requires for the URL to be profiled to be publicly accessible, though! So we'd have to deploy each PR to a server we can reference via IP address or subdomain instead. This in turn would automatically fix the above issues 1., 2. & 3...

Therefore, I suggest we discuss where we can host deployed versions of the reference site(s) for each PR/commit and then adapt the process so that we deploy to a publicly accessible server and then measure via PSI.

**Comment by schlessera** [comment]
As an alternative (to avoid publicly accessible deployments), we could use our own GitHub Actions runner instead. The way I understand this so far is that we'd provide a machine that runs GitHub Actions job queue and point GitHub to using that one instead of the provided VMs it uses by default.

By doing so, we could reserve a VM where we control the dimensioning, so that we can still run a localhost-based collection but with consistent performance characteristics.

I haven't looked into this in much detail yet, as it would still leave us with problems 1., 2. & 3. above.

**Comment by schlessera** [comment]
Another alternative would be to look into the other CI providers: Travis CI, Circle CI, ...

GitHub Actions seems to fluctuate very heavily, but my guess would be that not all of the CI providers have such a pronounced fluctuation, and using a different one for the Lighthouse collection might solve issue 4. above.

**Comment by amedina** [comment]
Going with Travis would be good.

**Comment by westonruter** [comment]
Maybe this isn't a good idea, but here it is: could we obtain the Lighthouse results and then just subtract the TTFB time from LCP? Or rather, we could take the output of the PHP process and save it to a static HTML file which we can then load with consistent serving time. If we're using Blackfire to test PHP performance, then isn't the Lighthouse result most revealing for what happens _after_ PHP finishes? I do see there being value in getting E2E test data with PHP execution as well, but only if we can have consistent PHP execution timing.

**Comment by amedina** [comment]
I think that is good idea. If we capture the runtime of the AMP plugin as it generates the pages, and also measure the static output, we can subtract the latter from the former we could in principle determine the impact of the generation process on the overall WCVs.
