### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by shivampaw** [Automattic/amp-wp#457]
Hi,

I believe this is broken with PHP 7? I can't confirm this 100% but because I only tested it 3 days before upgrading. 2 days after upgrading I checked AMP page again but it is broken.

https://www.depressionforteens.com/you-should-talk-about-your-depression/amp/

**Comment by shivampaw** [comment]
This was fixed by installig php-xml

**Comment by banago** [comment]
In case the commands come handy to someone, here they go:

Install package:

`sudo apt-get install php7.0-xml`

Restart apache:

`sudo service apache2 restart`
