### ISSUE TITLE
Build reference test site

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4571]
We should work on a reference test site that includes typical website content and try to use or touch most or all of the functionality of the AMP plugin as a real-world website would.

This will either simplify or be a requirement for the following features:

- Add performance metrics to CI [[#4569](https://github.com/ampproject/amp-wp/issues/4569)]
- Add unified sanitizer smoke test [[4549](https://github.com/ampproject/amp-wp/issues/4549)]
- Add automated visual regression testing [[4671](https://github.com/ampproject/amp-wp/issues/4671)]

**Comment by amanintech** [comment]
I will be happy to do that. Can this issue be assigned to me?

**Comment by schlessera** [comment]
Hey @amanintech, thanks for the interest in working on this.

We're currently not sure whether this can be done by an outside contributor, as it might require quite a lot of infrastructural knowledge to pull off. But I guess it depends on how we approach it.

Can you give me a few details about how you intend to work on this and what you'd want to build exactly?

**Comment by amanintech** [comment]
I would do something like exactly as you mentioned with a Wordpress website having the latest AMP plugin. I can add a CI that updates the plugin automatically and send the lighthouse performance report. We can host real content by pulling it from a news website in form of feed. I have worked on a [repo ](https://github.com/twimbit/Feed-Amp-Theme)where I also developed a theme having a feed like a feature. https://kievents.co/sid/

**Comment by westonruter** [comment]
To make this maintainable in the project and usable inside CI builds I think the test site should be in a Docker container.

**Comment by schlessera** [comment]
Yes, or maybe even a docker composer setup (instead of a single container), as we'll want to test persistent object caching as well with different servers like Memcached or Redis.

It should be the "source" version of building such a site, not the end result, so that we can replicate it wherever we need it.

Is this something you can tackle, @amanintech ?

**Comment by amanintech** [comment]
Yes, I surely can try. Where this container should be finally deployed? And will the site have any public visibility ?

**Comment by westonruter** [comment]
I think the point of the container is that it won't be deployed publicly. It would be spun up during and inside CI builds and then destroyed.

**Comment by amedina** [comment]
This is definitely something we need to do to evaluate baseline performance metrics for sites running the plugin on a set of specific conditions in relation to as set of essential metrics. 

Priorities are:

1. Define content of reference test site so that the AMP content generation capabilities of the plugin are fully exercised. 
1. Define tests to measure the performance gains between using or not using the AMP optimizer. 
1. Define tests to measure set of [essential metrics](https://web.dev/what-should-you-measure-to-improve-performance/)
1. Enable the execution of standalone Optimizer tests 
1. Integrate measurement of essential metrics into CI build pipeline

After these are achieved:

1. Document structure of reference test site so that any publisher can set up a similar one and add it to their CI pipeline

**Comment by amanintech** [comment]
> I think the point of the container is that it won't be deployed publicly. It would be spun up during and inside CI builds and then destroyed.

Honestly, I have never done that before. But I am ready to learn and give it a shot if that's ok. Could you share any tutorial to help me get started?

**Comment by schlessera** [comment]
@amanintech I think what @amedina meant to say is that _we_ - as in: the internal AMP plugin team - have to do a lot of work upfront until this is ready for a first implementation. I'm afraid this is not a good issue for now if you are interested in contributing.

**Comment by amanintech** [comment]
Got it

**Comment by schlessera** [comment]
@amedina I'm renaming this issue back to what it is, as this was specifically for defining the reference site, independent of what it will be used for. The title you've changed it into would fall under #4569.
