### ISSUE TITLE
Hosting Google analytics code locally 

### ISSUE THREAD

**Issue by askmeoffers** [Automattic/amp-wp#4572]
Hi , 

Currently when we ad analytics code in amp plugin then it calls 2-3 external resources which slows website . 

It will be better if  google analytics code is added locally .
our aliexpress coupons and aliexpess promo code store is best 
https://askmeoffers.com/coupon-deal-offer-promo-store/aliexpress-com/

Thanks
https://askmeoffers.com/

**Comment by westonruter** [comment]
I believe this is captured in #4530.
