### ISSUE TITLE
Link to “Exit Reader Mode” conflicts with long site names

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4573]
## Bug Description

As reported in [support forum topic](https://wordpress.org/support/topic/exit-reader-mode-conflict-with-long-site-names/), when a site has a long title it can overlap with the Exit Reader Mode link:

> See the screenshot of our AMP page when we enabled “Exit Reader Mode” in the AMP design settings:
> ![image](https://user-images.githubusercontent.com/134745/79055307-ee6a2780-7c00-11ea-9325-d1af15104e92.png)

## Expected Behaviour

Overlaps should not occur.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
We could remove the "Exit Reader Mode" and have only an "[exit dashicon](https://iconify.design/icon-sets/dashicons/exit.html)".

**Comment by westonruter** [comment]
Yeah, that could work. It might be a bit obscure for users to understand what they would be exiting though.

**Comment by westonruter** [comment]
Closing in favor of removing the Exit Reader Mode link entirely in #4796.
