### ISSUE TITLE
Links in pull request template are broken

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4575]
## Bug Description

The three links in the pull request template are all broken:

https://github.com/ampproject/amp-wp/blob/1.4.4/.github/PULL_REQUEST_TEMPLATE.md#L8-L10

We should update them to point towards meaningful documentation.

Props to @hansschuijff via https://github.com/ampproject/amp-wp/issues/4525#issuecomment-612588325

## Expected Behaviour

The links in the pull request should point to existing documentation.

## Steps to reproduce

Go to https://github.com/ampproject/amp-wp/blob/1.4.4/.github/PULL_REQUEST_TEMPLATE.md and click on any of the links.

## Additional context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Let's fix this with moving the contributing docs to the wiki. See #4473.
