### ISSUE TITLE
Load or Use only required portion of AMP Library Framework

### ISSUE THREAD

**Issue by askmeoffers** [Automattic/amp-wp#4577]
Hi Team , 

I noticed that many amp libraries are loaded by default and chrome inspector reports that most of the CSS/js of AMP library are unused. 

I am sure if we load only required portion of AMP libraries instead of the entire framework 
during rendering then this will speed up the website further .
For instance, chrome inspector reports that 80% of CSS and js are unused from below library 
https://cdn.ampproject.org/v0.js 

Example link is our oyo coupons store
https://askmeoffers.com/coupon-deal-offer-promo-store/oyorooms-com/
https://askmeoffers.com/coupon-deal-offer-promo-store/aliexpress-com/

Thanks 
Team askmeoffers.com

**Comment by westonruter** [comment]
Hi. This is out of scope for the AMP plugin. I suggest opening this as an issue upstream on the AMP project: https://github.com/ampproject/amphtml/
