### ISSUE TITLE
Fatal errors are not exposed when they occur during validation requests

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4580]
## Bug Description

Given a plugin like this:

```php
add_action( 'wp_footer', function() {
	for ( $i = 0; $i < 8; $i++ ) {
		if ( $i >= 4 && AMP_Validation_Manager::$is_validate_request ) {
			throw new Exception( 'FAIL' );
		}
		echo "<script>// bad: $i</script>";
	}
} );
```

On the frontend of the site, the admin bar will show 8 validation errors:

![image](https://user-images.githubusercontent.com/134745/78631610-b0ac7e00-7851-11ea-9cd7-a67effc2c7be.png)

However, when clicking “Validate” the user will only see 4:

![image](https://user-images.githubusercontent.com/134745/78631677-d89be180-7851-11ea-8a99-78fe79a7648a.png)

This is confusing. There was a fatal error that occurred but this is not exposed in any way. In fact, #4533 further hid the fatal error by forcing validation responses to have a 200 status code. Therefore, what is needed is a way to capture any fatal error which occurred during validation and display it to the user. Such a fatal error may indicate a bug in the AMP plugin with how source stacks are obtained, so this is important for the user to be able to relay to the support forums. This PR allows for this by capturing the fatal error and displaying it on the validated URL screen in an admin notice:

![image](https://user-images.githubusercontent.com/134745/78632586-434e1c80-7854-11ea-9819-02b0210587c8.png)

This came up in the course of helping to debug a [support topic](https://wordpress.org/support/topic/unable-to-validate-urls/). In that particular case, the issue turned out to be due to conflict with the [Widget Options](https://wordpress.org/plugins/widget-options/) plugin (which is actually a [known issue](https://wordpress.org/support/topic/standard-template-mode-internal-error/#post-12547136)). So given a site where the Widget Options plugin is installed as well as this [Old-Style Single Widget with Wide Control](https://gist.github.com/westonruter/7141599) gist plugin with the widget being added to the sidebar, even if the above `wp_footer` plugin code is active to emit validation errors in the footer, they will be completely hidden from the validation results because of the fatal error happening when rendering the sidebar:

![image](https://user-images.githubusercontent.com/134745/78632916-1bab8400-7855-11ea-92a2-3e6caf952c90.png)

However, with the changes in this PR checked out, an error is shown to explain why the frontend has validation errors being reported in the admin bar but they aren't showing up on the validated URL screen:

![image](https://user-images.githubusercontent.com/134745/78633012-531a3080-7855-11ea-8cbc-c3724a94b8eb.png)

## Expected Behaviour

Fatal errors should be indicated in some way.

## Steps to reproduce

See above.

## Screenshots

See above.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA testing instructions:**

1. Download, install, and activate the following gist plugin: https://gist.github.com/pierlon/cb3dc7e78ae99ba48e377d8256de5cb5
2. On the frontend of the site, the admin bar should be showing 8 validation errors:
    ![image](https://user-images.githubusercontent.com/134745/78631610-b0ac7e00-7851-11ea-9cd7-a67effc2c7be.png)
3. When clicking on the "Validate" link above, an admin notice should appear displaying the stacktrace for the fatal error that occurred, along with that location of the file that caused the error:

    ![image](https://user-images.githubusercontent.com/16200219/82277593-c72d1580-9977-11ea-874e-f3928ce19fd0.png)

4. Additionally, 8 new validation errors should appear for the page:

    ![image](https://user-images.githubusercontent.com/16200219/82277607-d44a0480-9977-11ea-99a0-41ae95a6f3ee.png)

**Comment by schlessera** [comment]
**QA Failed!**

![#c5f015](https://via.placeholder.com/10/c5f015/000000?text=+) The validation errors are correctly announced in the admin bar:

![Image 2020-05-19 at 3.47.59 PM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/452e2b50-65e6-4313-bc26-ae37dc0d4842)

![#c5f015](https://via.placeholder.com/10/c5f015/000000?text=+) The error message is correctly displayed in the admin backend:
![Image 2020-05-19 at 3.48.18 PM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/c40a7694-c4c4-4005-af1b-1425a8fc2854)

![#f03c15](https://via.placeholder.com/10/f03c15/000000?text=+) The validation screen does not show 8 validation errors, but rather 10!
![Image 2020-05-19 at 3.48.26 PM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/a187ecad-be8c-479c-a54b-324a2435d899)

Do note that the screenshot in the QA instructions already shows 9 errors instead of 8.

**Comment by westonruter** [comment]
@schlessera I'm not seeing this. I see 8 validation errors in the admin bar and then 4 when looking at the validated URL screen. 

![image](https://user-images.githubusercontent.com/134745/82359504-d3879180-99bc-11ea-9032-82329f74d086.png)

I'm not seeing the `font` validation errors. 

Actually, I think the reason for this discrepancy is that Xdebug is outputting the `font` tags perhaps for you to display the fatal error. In my testing I don't have that enabled. So that makes sense that those additional validation errors would only appear when a validation request has a fatal error, as the error is only displayed when a validation error occurs.

The only area for improvement here I can see is to force `display_errors` to be turned off during validation requests. Does that suppress the `font` validation errors from being raised?

**Comment by pierlon** [comment]
> The only area for improvement here I can see is to force display_errors to be turned off during validation requests. Does that suppress the font validation errors from being raised?

Yes, turning off `display_errors` does suppress the `font` validation errors. I'll open a PR for this.

**Comment by westonruter** [comment]
Given that #4747 has been opened, I'm moving this issue to QA Passed.
