### ISSUE TITLE
Preview AMP tooltip displays incorrectly in editor 

### ISSUE THREAD

**Issue by ernee** [Automattic/amp-wp#4590]
## Bug Description

In the editor, the tooltip to _Preview AMP_  displays incorrectly (hidden behind another element). 

## Expected Behaviour

The tooltip should be fully visible.

## Steps to reproduce

1. Edit a post or page (using WordPress Core or Gutenberg plugin)
2. Hover over the AMP preview icon at the top right
3. See the _Preview AMP_ tool tip display incorrectly (hidden)

## Screenshots

**WordPress Core**

<img width="358" alt="tooltip in WP Core" src="https://user-images.githubusercontent.com/8108643/79396638-36ef5100-7f31-11ea-965e-5d6e3ce5d4d3.png">

**Gutenberg plugin**

<img width="295" alt="tooltip in Gutenberg plugin" src="https://user-images.githubusercontent.com/8108643/79396651-3f478c00-7f31-11ea-987e-f0253d5f4531.png">

## Additional context

 - WordPress version: 5.4
 - Plugin version: 1.5.3
 - Gutenberg plugin version (if applicable): 7.9.0
 - AMP plugin template mode: Transitional, Reader
 - PHP version: 7.3.5
 - OS: MacOS
 - Browser: Chrome
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kienstra** [comment]
Hi @ernee!
Hope you've been doing great!

Yeah, this is definitely an issue. In my local, the tooltip is cut off below:

![tooltip-here](https://user-images.githubusercontent.com/4063887/79400746-afafd680-7f4c-11ea-9042-a39ee2d9e2c3.png)

I'll work on this.

**Comment by kienstra** [comment]
If it's alright, I'll come back to this tomorrow.

There doesn't look to be a quick fix, though I'm not good at CSS.

For example, simply changing the `z-index` or `position` of the `<Popover>` in the `<Tooltip>` didn't fix this.

**Comment by westonruter** [comment]
It appears the `Tooltip` component can't be nested inside that button in the DOM. No amount of `z-index` will help apparently. The element containing the tooltip that appears for the Settings icon is located elsewhere in the DOM somehow.

**Comment by kienstra** [comment]
Yeah, there might not be a way to keep the tooltip.

**Comment by westonruter** [comment]
I'd look into how the Setting button has integrated the tooltip in Gutenberg.

**Comment by kienstra** [comment]
## 1. Tooltip might not be feasible 

Hi @westonruter,
Sorry for the delay.

I couldn't find a way to prevent the `<Tooltip>` from being cut off. The problem looks to be that tooltips need to be further away in the DOM. 

But this button is [rendered into a single element in the DOM](https://github.com/ampproject/amp-wp/blob/85e45e895629bddf674e8ca2181128a1bcc6ad8c/assets/src/block-editor/helpers/index.js#L932-L935), and that element isn't aware of the block editor's React components. It's rendered like this because there wasn't a Slot/Fill or filter to render it properly.

So the tooltip [renders inside the Button](https://github.com/WordPress/gutenberg/blob/f152a28c5331d56230b716ee8b948b9a56590929/packages/components/src/popover/index.js#L628), and looks bad.

For example, with the 'Preview AMP' button, the tooltip is inside the button:

![amp-closepi](https://user-images.githubusercontent.com/4063887/79507084-b0a04100-7ffc-11ea-8dbe-d9949bc872ce.png)

But for the 'More tools & options' button, which looks good, the tooltip is pretty far away from the button in the DOM:

![tooltip-button-](https://user-images.githubusercontent.com/4063887/79506648-f4df1180-7ffb-11ea-9500-43f519ab68d3.png)

**Comment by kienstra** [comment]
## 2. Suggestion
What do you think about simply removing the `<Tooltip>`?

```diff
diff --git a/assets/src/block-editor/components/amp-preview.js b/assets/src/block-editor/components/amp-preview.js
index dfbace46e..ed8a4fa1e 100644
--- a/assets/src/block-editor/components/amp-preview.js
+++ b/assets/src/block-editor/components/amp-preview.js
@@ -236,25 +236,22 @@ class AMPPreview extends Component {
 
                return (
                        isEnabled && ! errorMessages.length && ! isStandardMode && (
-                               <Tooltip text={ __( 'Preview AMP', 'amp' ) } >
-                                       <Button
-                                               className="amp-editor-post-preview"
-                                               href={ href }
-                                               label={ __( 'Preview AMP', 'amp' ) }
-                                               isSecondary
-                                               disabled={ ! isSaveable }
-                                               onClick={ this.openPreviewWindow }
-                                               ref={ this.buttonRef }
-                                       >
-                                               { ampFilledIcon( { viewBox: '0 0 62 62', width: 18, height: 18 } ) }
-                                               <span className="screen-reader-text">
-                                                       {
-                                                       
        /* translators: accessibility text */
-                                                       
        __( '(opens in a new tab)', 'amp' )
-                                                       }
-                                               </span>
-                                       </Button>
-                               </Tooltip>
+                               <Button
+                                       className="amp-editor-post-preview"
+                                       href={ href }
+                                       isSecondary
+                                       disabled={ ! isSaveable }
+                                       onClick={ this.openPreviewWindow }
+                                       ref={ this.buttonRef }
+                               >
+                                       { ampFilledIcon( { viewBox: '0 0 62 62', width: 18, height: 18 } ) }
+                                       <span className="screen-reader-text">
+                                               {
+                                                       /* translators: accessibility text */
+                                                       __( '(opens in a new tab)', 'amp' )
+                                               }
+                                       </span>
+                               </Button>
                        )
                );
        }
```

That's probably not great for usability.

But there's [screen reader text inside the Button](https://github.com/ampproject/amp-wp/blob/ab653495e56f306da1341efd18de1aa363751763/assets/src/block-editor/components/amp-preview.js#L250-L255).

And the [documentation for Button says](https://github.com/WordPress/gutenberg/tree/bed7e0c6a6dff04409c883a0cf7f00fa6560b2db/packages/components/src/button#text-label):

>All button types use text labels to describe the action that happens when a user taps a button. If there’s no text label, there should be an icon to signify what the button does (e.g. an IconButton component).

...and this does have an icon.

**Comment by westonruter** [comment]
There's a difference between the Settings button and the AMP Preview button in terms of the React components.

With React Dev Tools this is what the Settings tooltip looks like when it is open:

![image](https://user-images.githubusercontent.com/134745/79514618-77b39c80-7ffb-11ea-9e9c-f50eaba81c3e.png)

Compare with the AMP Preview button:

![image](https://user-images.githubusercontent.com/134745/79514856-fdcfe300-7ffb-11ea-9e19-8876b6a614e1.png)

We're missing a `Fill` construct here.

Nevertheless, the “Settings“ button doesn't show a `Tooltip` being used here ([source](https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/header/index.js#L89-L96 )):

```jsx
				<Button
					icon={ cog }
					label={ __( 'Settings' ) }
					onClick={ toggleGeneralSidebar }
					isPressed={ isEditorSidebarOpened }
					aria-expanded={ isEditorSidebarOpened }
					shortcut={ shortcut }
				/>
```

I'm not sure how the tooltip is being wired up for the Settings element, but it's being done differently than the AMP Preview button. I suspect that changing the tooltip to be added in the same way will fix the issue with the positioning.

**Comment by kienstra** [comment]
Hi Weston,
Thanks for your ideas. I tested something like you suggested, but I'll try it again.

The 'Settings' button has a `Popover` via its [label prop](https://github.com/WordPress/gutenberg/blob/4f12cf306f9b306ba4f2bf0d33a6f78ea134bc2d/packages/edit-post/src/components/header/index.js#L91). It [renders a Tooltip](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/index.js#L125-L131) using that `label` prop passed to it.

Then, the `<Tooltip>` [renders](https://github.com/WordPress/gutenberg/blob/4f12cf306f9b306ba4f2bf0d33a6f78ea134bc2d/packages/components/src/popover/index.js#L621) `<Fill>`. I don't think there's a Slot that the fill can use, because this 'Preview AMP' button is [rendered into a single DOM element](https://github.com/ampproject/amp-wp/blob/85e45e895629bddf674e8ca2181128a1bcc6ad8c/assets/src/block-editor/helpers/index.js#L932-L935), and doesn't have access to any of the block editor.

**Comment by kienstra** [comment]
Here's something pretty similar to the [Settings button](https://github.com/WordPress/gutenberg/blob/4f12cf306f9b306ba4f2bf0d33a6f78ea134bc2d/packages/edit-post/src/components/header/index.js#L89-L96), and the tooltip is still covered.

![tooltip](https://user-images.githubusercontent.com/4063887/79518942-f0c0ed00-8017-11ea-869f-efa6eb2243f4.png)


```diff
diff --git a/assets/src/block-editor/components/amp-preview.js b/assets/src/block-editor/components/amp-preview.js
index dfbace46e..3b28af0e0 100644
--- a/assets/src/block-editor/components/amp-preview.js
+++ b/assets/src/block-editor/components/amp-preview.js
@@ -236,25 +236,17 @@ class AMPPreview extends Component {
 
                return (
                        isEnabled && ! errorMessages.length && ! isStandardMode && (
-                               <Tooltip text={ __( 'Preview AMP', 'amp' ) } >
-                                       <Button
-                                               className="amp-editor-post-preview"
-                                               href={ href }
-                                               label={ __( 'Preview AMP', 'amp' ) }
-                                               isSecondary
-                                               disabled={ ! isSaveable }
-                                               onClick={ this.openPreviewWindow }
-                                               ref={ this.buttonRef }
-                                       >
-                                               { ampFilledIcon( { viewBox: '0 0 62 62', width: 18, height: 18 } ) }
-                                               <span className="screen-reader-text">
-                                                       {
-                                                       
        /* translators: accessibility text */
-                                                       
        __( '(opens in a new tab)', 'amp' )
-                                                       }
-                                               </span>
-                                       </Button>
-                               </Tooltip>
+                               <Button
+                                       icon={ ampFilledIcon( { viewBox: '0 0 62 62', width: 18, height: 18 } ) }
+                                       label={ __( 'Preview AMP', 'amp' ) }
+                                       className="amp-editor-post-preview"
+                                       href={ href }
+                                       label={ __( 'Preview AMP', 'amp' ) }
+                                       isSecondary
+                                       disabled={ ! isSaveable }
+                                       onClick={ this.openPreviewWindow }
+                                       ref={ this.buttonRef }
+                               />
                        )
                );
        }
```

**Comment by westonruter** [comment]
OK, how about just using a classic `title` attribute instead?

**Comment by kienstra** [comment]
Good idea, that works locally.

**Comment by amedina** [comment]
The tooltip is showing properly, but the styling of the buttons changed. The way they were styled before looked better (see screenshots at the beginning of this issue; and see attachments in this comment). Now the `Preview` and the `AMP Preview` look disconnected.


![Screen Shot 2020-05-18 at 5 28 51 PM](https://user-images.githubusercontent.com/506089/82271642-3a5d6a00-992d-11ea-8a1b-ade6971e9db8.png)
![Screen Shot 2020-05-18 at 5 28 44 PM](https://user-images.githubusercontent.com/506089/82271645-3af60080-992d-11ea-84af-fa6f40de2588.png)

**Comment by westonruter** [comment]
@amedina this is expected. The button is required to be disconnected in current versions of Gutenberg because the Preview dropdown component is not extendable.

**Comment by amedina** [comment]
I see. It looks weird disconnected because the semantics of the `AMP` symbol is not conveyed as clearly. 

Let's ship it and we will revise during UX review.
