### ISSUE TITLE
Add ability to look up spec by name

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4597]
## Feature description

We need to more efficiently walk over the generated spec data, in particular to be able to find tag spec by a spec name. This will allow fleshing out validation errors in the UI with the full context and provide the user with information on amp.dev for more details.

Relates to #1420 and #4566.

* Separate extension specs from tag specs. This eliminates having to look up extension specs from among tag specs.
* Add ability to get a specific spec by name for a given tag, and use in the style sanitizer.
* Add assertion that `link rel=stylesheet for fonts` spec is present.
* Include `extension_type` in generated spec data in order to determine if an extension is a `custom-template` rather than `custom-element`.
* Remove obsolete/unused `AMP_Rule_Spec::$additional_allowed_tags`.
* Eliminate duplicate copies of spec in memory (e.g. `$allowed_tags`, `$DEFAULT_ARGS['amp_allowed_tags']`, and `$args['amp_allowed_tags']`).

Relates to #3080 and #4570.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
https://github.com/ampproject/amp-wp/issues/5585

Knowledge path admin umbrella. Want a little widget in the dashboard. Would like a little widget with info about latest news about AMP plugin and a set of links to twitter, amp blog, plugin site, YouTube channel.

**Comment by westonruter** [comment]
Dependency for #1401.

**Comment by westonruter** [comment]
Resolved by https://github.com/ampproject/amp-toolbox-php/pull/100
