### ISSUE TITLE
Add Comments Link

### ISSUE THREAD

**Issue by tieguy** [Automattic/amp-wp#46]
Makes sense not to include comments in the amp version, of course, but if comments are on, at least a *link* to them seems like it would be a good idea?

**Comment by mjangda** [comment]
Sounds like a good idea.

**Comment by andyforsberg** [comment]
+1

**Comment by jamminjames** [comment]
+1

**Comment by mjangda** [comment]
Being added as part of #464

**Comment by tieguy** [comment]
Appears to be fixed to me in latest pull so going ahead and closing. Thanks for the hard work, everyone involved!
