### ISSUE TITLE
Add support for Mautic tracking script

### ISSUE THREAD

**Issue by nisiwi** [Automattic/amp-wp#4603]
## Feature description

AMPforWP supports Matomo open-source analytics, however, no provision for open source marketing automation tools like Mautic (and their tracking scripts) has been included.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I don't know anything about Mautic, but the AMP plugin provides an Analytics screen within which you can put any `amp-analytics` configuration. Nevertheless, I don't see that Mautic has specific AMP compatibility for analytics. What I do see that Mautic supports a tracking pixel: https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring#tracking-pixel-tracking

Therefore, if you can determine what the tracking pixel URL should be for Mautic then you could use [`amp-pixel`](https://amp.dev/documentation/components/amp-pixel/) to add it.

For example:

```php
add_action( 'wp_footer', function() {
	if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
		?>
		<amp-pixel src="http://example.com/mtracking.gif" layout="nodisplay"></amp-pixel>
		<?php
	}
} );
```

I don't know what `http://example.com/mtracking.gif` should be in your case.
