### ISSUE TITLE
Discontinue removing sizes attribute when converting img to amp-img

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4606]
## Feature description

In #4548 the validator was updated to introduce new [`disable-inline-width` layout attribute](https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/#disable-inline-width). This will allow us to discontinue removing the `sizes` attribute on `amp-img` which the image sanitizer is currently doing:

https://github.com/ampproject/amp-wp/blob/014bbbba04bea102387f6faaa6b56ab8bf0e1e0a/includes/sanitizers/class-amp-img-sanitizer.php#L333-L334

This was confirmed in https://github.com/ampproject/amphtml/pull/27083#issuecomment-610767867.

The `sizes` attribute was removed to fix long-standing issues with images:

* https://github.com/ampproject/amp-wp/issues/1237
* https://github.com/ampproject/amphtml/issues/17053
* https://github.com/ampproject/amp-wp/issues/1086
* https://github.com/ampproject/amp-wp/issues/1305
* https://github.com/ampproject/amp-wp/pull/1939
* …

It was removed as part of a PR to “definitively” fix the issues: #2036. 

However, now that the `disable-inline-width` attribute is available to disable AMP's `sizes` behavior, we can add it automatically when converting `img` into `amp-img` (or `amp-anim`), and persist the `sizes` attribute as well.

This will involve re-checking the above issues for regressions!

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This should be done early in the 1.6 release to give time for bugs to shake out.

**Comment by amedina** [comment]
@schlessera Please add QA/Testing criteria for this issue and associated PRs.

**Comment by schlessera** [comment]
**QA passed**

The blocking attributes were correctly removed, the boilerplate was removed as a consequence of that, and none of the resulting images were distorted.

![Image 2020-08-25 at 4 12 46 AM](https://user-images.githubusercontent.com/83631/91115051-9d2b7380-e689-11ea-868d-97b40ed4f918.png)

There was one bug that was already discovered here but hasn't been fixed yet. I split that issue out into a new bugfix PR (#5263) so that this one can pass QA.
