### ISSUE TITLE
Some TailwindCSS class names are being removed

### ISSUE THREAD

**Issue by JuanJavier1979** [Automattic/amp-wp#4609]
## Bug Description

Some TailwindCSS class names such as `.w-1/3` are being removed.

## Expected Behaviour

Classes with `/` should be kept.

## Additional context

This is happening since the update on composer.lock here
https://github.com/ampproject/amp-wp/commit/ab513d451c2d1602a56576ac909ce59f7073dd24#diff-1da2c7edc898c70e5a79a9997c98cecc

**Comment by westonruter** [comment]
Humm. That doesn't seem to be valid CSS. Consider:

```css
.w-1/3 {
  width: 33.333333%
}
```

![image](https://user-images.githubusercontent.com/134745/79793632-c0be6600-8305-11ea-8bbc-890f7b26518d.png)

I can see in [tailwind.min.css](https://unpkg.com/tailwindcss@1.2.0/dist/tailwind.min.css) the selector is indeed being escaped:

```css
.w-1\/3 {
  width: 33.333333%
}
```

So given a Custom HTML block that contains:

```html
<style>
.w-1\/3 {
  outline: solid 3px lime;
}
</style>
<div class="w-1/3">one third width</div>
```

The result in AMP and non-AMP is:

![image](https://user-images.githubusercontent.com/134745/79794077-83a6a380-8306-11ea-83a2-c88c946f8e9f.png)

So indeed, the selector is getting tree-shaken.

**Comment by westonruter** [comment]
The problem seems to be with PHP-CSS-Parser. I've opened #4610 to test this case. But it currently handles selectors like `.lg\:w-full:hover` as expected. There's just something about the selector parsing in PHP-CSS-Parser that does not like `.w-1\/3`.

**Comment by westonruter** [comment]
It appears specifically that `\Sabberworm\CSS\Property\Selector::isValid()` is failing to return `true` for `w-1\/3`:

```
wp> \Sabberworm\CSS\Property\Selector::isValid('lg\:w-full:hover')
=> int(1)
wp> \Sabberworm\CSS\Property\Selector::isValid('w-1\/3')
=> int(0)
```

It looks like this was fixed in https://github.com/sabberworm/PHP-CSS-Parser/pull/162 so we may just need to update PHP-CSS-Parser to fix the problem.

**Comment by westonruter** [comment]
@JuanJavier1979 build with a fix for testing: https://github.com/ampproject/amp-wp/pull/4610#issuecomment-616821059

**Comment by JuanJavier1979** [comment]
Thanks @westonruter, that is working now as expected.

**Comment by pierlon** [comment]
**QA Testing instructions:**

1. Add a Custom HTML block with the following content:
    ```
    <style>
    .w-1\/3 {
      outline: solid 3px lime;
    }
    </style>
    <div class="w-1/3">one third width</div>
    ```
2. On the AMP page, verify that the following CSS rule exists in the page source:
    ```
    .w-1\/3{outline:solid 3px lime}
   ```
3. Verify that the non-AMP and AMP page are the same :
![image](https://user-images.githubusercontent.com/16200219/82274977-29cee300-9971-11ea-82a2-b9c10a7c4e38.png)

**Comment by schlessera** [comment]
**QA Passed**

The class can be found in the source of the AMP page:

![Image 2020-05-19 at 3.22.14 PM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/62085a07-4161-4c9a-82d6-1336e09acc4b)

Both non-AMP and AMP page look identical:

![Image 2020-05-19 at 3.21.51 PM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/ecc60c45-e1cd-4b5f-8f5d-4f18309e775f)

**Comment by schlessera** [comment]
This also works correctly with the type of notation used in Atomic CSS (acss.io):

![Image 2020-05-19 at 3.26.45 PM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/0053d24e-2a4a-4ba9-b788-710f64e669b7)

In the above screenshot, the second green box uses the following:
```html
<style>
.w\(50\%\) {
  width: 50%;
  outline: solid 3px lime;
}
</style>
<div class="w(50%)">width 50%</div>
```
