### ISSUE TITLE
The new update has some bugs.  Version 1.5.3

### ISSUE THREAD

**Issue by Jennifer7597** [Automattic/amp-wp#4617]
## Bug Description

I installed the plugin update and then all the blogs were put into trash and then all my images were removed.  I had to do a backup restore.

## Expected Behaviour

I have been using the AMP plugin for about 2 months with no issues.  Just wanted to use the most recent version.

## Additional context

 - WordPress version: WordPress 5.4 running Salient theme.
 - 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by Jennifer7597** [comment]
![Coaches corner page](https://user-images.githubusercontent.com/64101433/79904820-4ebc4e80-83e3-11ea-85e9-6480e328e3f9.PNG)

**Comment by westonruter** [comment]
I don't know about “all the blogs were put into trash” but it appears you are using W3 Total Cache. There is a known compatibility issue with that plugin, a bug that they need to fix: https://github.com/W3EDGE/w3-total-cache/issues/162

In the meantime, you can use this plugin to work around the the problem: https://gist.github.com/westonruter/8d52c0b807e6dfbbdf2219622d0f4a7e

Installation instructions: https://gist.github.com/westonruter/6110fbc4bef0c4b8c021a112012f7e9c

That should fix the issue for you.

**Comment by Jennifer7597** [comment]
Thank you!  So helpful!!!
