### ISSUE TITLE
Introduce is_amp_available() mechanism to go along with is_amp_endpoint()

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4619]
## Feature description

To detect whether AMP is available for a given post, we have a couple places where logic like this is being used:

https://github.com/ampproject/amp-wp/blob/28a33fbd3372cb14453f6c3c819d5b516407bc97/includes/amp-helper-functions.php#L501-L507

First of all, not good to have this logic duplicated (including this special check for `is_posts_page`). What is needed is for this logic to be encapsulated into a new helper function like `is_amp_available()` which can tell you whether AMP should be available for the the current request (also factoring in [whether there is kept invalid markup](https://github.com/ampproject/amp-wp/blob/28a33fbd3372cb14453f6c3c819d5b516407bc97/includes/amp-helper-functions.php#L514-L535)). This function would be similar to `is_amp_endpoint()` in its usage, namely that it must be called after the `wp` action.

It's also not good that we have two separate code paths for Reader mode and non-Reader mode. It should be that Reader mode is the same as having theme support but just the only supported template is `singular`. This restriction could be put in place inside of `AMP_Theme_Support::get_template_availability()`.

The harmonization of the code paths here will make most sense to be done once there is a normalized way to construct AMP URLs per #2204.

I've created an initial PR with some quick changes that start to implement this: #4620.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
**QA passed**

The `is_amp_available()` function is present and works.

It also lets the user know if it is called at the wrong time within the WordPress lifecycle:

![Image 2020-07-15 at 2 26 28 PM](https://user-images.githubusercontent.com/83631/87544851-66843580-c6a7-11ea-8d15-5c99a37eb0d1.png)
