### ISSUE TITLE
Provide direct details of validation issue(s) within Paired Mode

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4623]
## Feature description

**When I'm comparing my AMP page to my regular page in Paired Mode, as a developer, I'd like to be able to examine what the current validation issues are without leaving paired mode.**

Right now, when I'm in Paired Mode, I can see the count of validation issues, but when I click on them to see them, I'm brought into the admin backend. This causes the Paired Mode to stop working, and show me a modal where I can either leave Paired Mode or get back to the actual page.

I'd like to have the ability to examine the validation issue details (at least an overview) directly from the Paired Mode without leaving it. This could be done by either adding a nested list to the admin bar submenu, or opening a modal within the AMP iframe when clicking on the validation issue warning.

## Screenshots

![Image 2020-04-24 at 9.48.32 AM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/8eae0c4a-ea76-4cbb-9566-080583583504)

![Image 2020-04-24 at 9.48.46 AM.png](https://images.zenhubusercontent.com/57bd4612e40e5714b16dc08b/dc7d98ef-fdb2-40a1-8cd6-8e7e5228c7b3)
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Yeah, we should be working toward surfacing as much validation results in the admin bar as possible. Users should be able to make decisions about whether to remove or keep invalid markup from the context of the frontend where markup is shown. A complication here is that applying a change to remove/keep markup needs to result in a full-page reload, so the UI for managing the validation errors would itself need to be in a parent window in the same way that paired browsing has a UI outside of iframed windows. I've mentioned this before in https://github.com/ampproject/amp-wp/issues/2316#issuecomment-537166767. 

In the meantime, to address the specific issue here I think we should just automatically cause clicks in the admin bar to open in the top-level browsing context as opposed to navigating inside the iframe. Clicking a link in the admin bar would be an implicit exit of paired browsing.
