### ISSUE TITLE
Default arg and actual arg key mismatch in comment sanitizer

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4624]
## Bug Description

The default argument for enabling or disabling the comments live list in the comments sanitizer is set here:

https://github.com/ampproject/amp-wp/blob/1.4.4/includes/sanitizers/class-amp-comments-sanitizer.php#L23

The actual value of the argument after filtering is then supposed to be used here:

https://github.com/ampproject/amp-wp/blob/1.4.4/includes/sanitizers/class-amp-comments-sanitizer.php#L48

Note that the two use different keys, so no default value is actually set for the argument that is being used, and the condition just happens to resolve in the same way by coincidence:
```
'comment_live_list'  // <= key of the default argument being set
'comments_live_list' // <= key of the actual argument being used
```

Bugs like this are why I advocate using constants for pretty much any magic string we use throughout the code, as they are very hard to detect otherwise.

## Expected Behaviour

The default argument should be set to the same key as the actual value being used.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by dhaval-parekh** [comment]
**Passed**

I have checked the current code in the `develop` branch and confirm that this is no longer the case and key of the default argument is updated and there is no other instance where a different key is being used. [reference](https://github.com/ampproject/amp-wp/blob/5ab441284a529c3c535e0145e1b869ecd2f3a03f/includes/sanitizers/class-amp-comments-sanitizer.php#L35)
