### ISSUE TITLE
Update Reader Mode Settings message

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4625]
In an upcoming version (e.g. 1.6) the description of the Reader mode in the Setting page should be updated to define the clear purpose and value of the mode, and remove a reference to the classic mode.

**Comment by kmyram** [comment]
Copy doc: https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit#

**Comment by westonruter** [comment]
@amedina Is this still valid? There's also this PR which may also be obsolete: #5007.

**Comment by amedina** [comment]
Yeah; I think both of these can be closes as they were addressed already.
