### ISSUE TITLE
Prevent automatically redirecting AMP to non-AMP for administrative users

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4626]
## Feature description

When a site is in Transitional mode and a user accesses Paired Browsing, if the user ends up navigating to a page that is not available in AMP then a notice is displayed:

![image](https://user-images.githubusercontent.com/134745/80267939-8849bf80-8658-11ea-9b03-23e6393f6f30.png)

That's intentional but it's somewhat annoying because the user may want to see how that URL looks even though it is not available in AMP (by toggling a AMP off for a post or disabling the template).

What's more, if a post has some invalid markup that is marked as “kept” the behavior in Transitional mode is to redirect from the AMP version to the non-AMP version. I've seen this result in infinite redirects occurring in paired browsing.

In both these cases, I think what is needed is discontinue redirecting AMP to non-AMP when the user is logged-in (if the user has administrative capabilities, including the ability to access paired browsing). 

Instead of redirecting from AMP to non-AMP, the admin bar can show the disabled icon in the AMP icon:

![image](https://user-images.githubusercontent.com/134745/80268065-66047180-8659-11ea-9ca3-b03cf06c465f.png)

Hovering over the icon can show an explanation for why AMP is disabled for the URL, including kept invalid markup (the only reason it is currently shown), or else if AMP is disabled for a post or disabled for the current template (which is basically exposing the errors returned by `AMP_Post_Type_Support::get_support_errors()` and those returned by `\AMP_Theme_Support::get_template_availability()`). 

Users who do not have access to AMP Dev Tools should continue to get redirected to the non-AMP version. (Such users would not see the validation screens, the AMP admin bar menu item, or paired browsing.)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Only do this for logged-in users, who also have DevTools turned on. Or, for users who have the Customizer open (especially in the new Reader mode, wherein we may need to have some message when navigating to a URL that has AMP disabled on it).

**Comment by westonruter** [comment]
This is also related to Reader Mode Expansion in that we'll need to allow every URL to be accessible in the Customizer, regardless of whether AMP is enabled for the post type or the template. We'll need to show some notice saying AMP is not available for visitors, but otherwise the user still needs to be able to navigate around the site in the Customizer preview.

**Comment by westonruter** [comment]
> Or, for users who have the Customizer open (especially in the new Reader mode, wherein we may need to have some message when navigating to a URL that has AMP disabled on it). ¶ This is also related to Reader Mode Expansion in that we'll need to allow every URL to be accessible in the Customizer, regardless of of whether AMP is enabled for the post type or the template. We'll need to show some notice saying AMP is not available for visitors, but otherwise the user still needs to be able to navigate around the site in the Customizer preview.

Actually, redirection is already prevented in the Customizer preview:

https://github.com/ampproject/amp-wp/blob/0391d505fc21c35e7095bc910966b85bad252318/includes/class-amp-theme-support.php#L2113-L2126

**Comment by pierlon** [comment]
> Or, for users who have the Customizer open (especially in the new Reader mode, wherein we may need to have some message when navigating to a URL that has AMP disabled on it).

@westonruter Would you still deem the message informing the user of AMP being disabled for the page necessary?

**Comment by pierlon** [comment]
**QA passed**

- Paired browsing is available even though kept errors are on the page
- The disabled icon is shown as the status for AMP
- Redirection does not occur to the non-AMP page
- Redirection does occur for a person without dev tools
- Brief summary shown for validation errors to indicate why AMP is disabled

![image](https://user-images.githubusercontent.com/16200219/87587683-f343e900-c6d1-11ea-9a02-51e37510c716.png)

**Comment by westonruter** [comment]
> Would you still deem the message informing the user of AMP being disabled for the page necessary?

It would be a good enhancement. The legacy reader mode has this in that the AMP toggle becomes disabled if AMP is not available for the URL being previewed. We could do something similar when a Reader theme is selected, though we'd have to figure out where to place that notice. Not important for now though.
