### ISSUE TITLE
Issue with youtube playlist embed urls & liveblog plugin data

### ISSUE THREAD

**Issue by k-atul** [Automattic/amp-wp#463]
Hi facing issue in AMP pages with embeding of youtube playlist. The AMP plugin renders the url as below two given cases and in one case it is not returning any video id also.

<amp-youtube data-videoid="videoseries" layout="responsive" width="600" height="338"></amp-youtube>
<amp-youtube data-videoid="videoseries?list=PLrDg7LoYgk9wv_QK-mHWFxTf8Y52LVsNB" layout="responsive" width="600" height="338"></amp-youtube>

Even though we added filter to remove above shown "videoseries?list=" & "videoseries" even though it works on local but it is not working on VIP and in first case there will be no video id after filter and so it is an amp validation error. 

http://indianexpress.com/article/india/india-news-india/porbandar-dalit-murder-family-claim-body-bury-him-in-burial-ground-2905107/lite/

LIVEBLOG Plugin:
We are facing a issue with Liveblog plugin on amp pages, as the below tags are not coming in proper amp formats and this is causing issues in google it shows AMP implementation error.
Current Showing:
< amp data-videoid="TFRZMdKwKN8" layout="responsive" width="600" height="338" >< /amp >
< amp data-tweetid="772071910188298240" layout="responsive" width="600" height="480" >< /amp >

Should be:
< amp-youtube data-videoid="TFRZMdKwKN8" layout="responsive" width="600" height="338" >< /amp-youtube >
< amp-twitter data-tweetid="772071910188298240" layout="responsive" width="600" height="480">< /amp-twitter >

**Comment by mjangda** [comment]
I've moved the playlist issue to #465.

For the liveblog issue, I'd suggest opening a ticket with the VIP team to help debug. It's likely due to the use of kses in the liveblog plugin.
