### ISSUE TITLE
TikTok embeds should use amp-embedly-card not amp-iframe

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4633]
## Bug Description

In #4357 support for TikTok embeds (#4326) was implemented using `amp-iframe`. The implementation was not perfect (https://github.com/ampproject/amp-wp/pull/4357#issuecomment-596247030) but it was the best we thought we could do. An issue was filed in AMP to support TikTok directly: https://github.com/ampproject/amphtml/issues/27080. Nevertheless, it turns out that the `amp-embedly-card` supports embedding TikTok videos! Therefore, we can just drop the use of `amp-iframe` and use this instead.

Cheers to @carloshhr for the discovery: https://github.com/ampproject/amp-wp/issues/4326#issuecomment-620975833.

Note we already use `amp-embedly-card` for embedding Reddit.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* Update `\AMP_TikTok_Embed_Handler::make_embed_amp_compatible()` to create an `amp-embedly-card` element instead of `amp-iframe`. 
* Give it `layout=responsive`, `height=700`, and `width=340`. When the embed loads, it will be resized for its contents. 
* Pass the original URL for the TikTok video in the `data-url` param for `amp-embedly-card` as opposed to passing just the ID.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
My concern here is deferring the embed to the third party service, [Embedly](https://embed.ly). Their branding will be in the embed (unless you use their paid plan), and analytics tracking for the original embed does not seem to be guaranteed.

**Comment by westonruter** [comment]
> My concern here is deferring the embed to the third party service, [Embedly](https://embed.ly). Their branding will be in the embed (unless you use their paid plan)

That's a good point. But we have precedent for this with Reddit. See #2339.

It seems better to have a properly-sized embed with some Embedly branding, than to have a missized embed without any branding. 

> analytics tracking for the original embed does not seem to be guaranteed.

What tracking?

**Comment by pierlon** [comment]
> That's a good point. But we have precedent for this with Reddit. See #2339.

The Reddit embed uses Embedly behind the scenes, as mentioned in https://github.com/ampproject/amp-wp/pull/2339#issuecomment-498366068, so there is no visual difference when comparing AMP and Non-AMP:

![image](https://user-images.githubusercontent.com/16200219/80568370-6056b500-89e6-11ea-89ad-3a89dbd8032f.png)

When used with TikTok however, there are a few differences:

![image](https://user-images.githubusercontent.com/16200219/80569599-ccd2b380-89e8-11ea-9219-c5cebd65785c.png)

By comparison, here's how it looks with the `amp-iframe` being used with a `fixed-height` layout:

![image](https://user-images.githubusercontent.com/16200219/80570989-57b4ad80-89eb-11ea-9ee7-03f0f396833c.png)

Thoughts?

> What tracking?

No worries, I misunderstood the Embedly docs and thought they would not be loading analytics from the original embed, but I can confirm that for TikTok embeds the UTM referral and source are being sent as expected.

**Comment by westonruter** [comment]
The text overlaying the video seems unfortunate for the Embedly implementation. Nevertheless, the rest of it seems fine. Since TikTok isn't sending the `amp-iframe` resize messages, it seems that that the `amp-embedly-card` will generally have better results? I suppose that's somewhat subjective and not a clear-cut decision.

**Comment by westonruter** [comment]
QA Passed

`amp-embedly-card` is used:

![image](https://user-images.githubusercontent.com/134745/87254342-d2139c00-c436-11ea-93e2-5e20a2e1584b.png)

The Good: It looks better than the non-AMP version.
The Bad: It's not 1:1 visual parity and there is a “Powered by embedly” caption.
The Ugly: It involves iframes nested 4 levels deep.

Overall, it's better than before.
