### ISSUE TITLE
Site Health styles for re-enabling transient caching appear in Customizer

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4643]
## Bug Description

When looking at the Customizer source, I unexpectedly saw these styles added to the page:

https://github.com/ampproject/amp-wp/blob/2798605ccac1da90d8199d5996f8464524ac7e9f/src/Admin/SiteHealth.php#L549-L577

The issue is that the styles are added at the `admin_print_styles` action regardless of the current screen.

## Expected Behaviour

Styles should only be added on the Site Health screen.
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
QA passed.

On Site Health page:
![Image 2020-06-17 at 3 41 07 PM](https://user-images.githubusercontent.com/83631/84905534-11a5cd00-b0b1-11ea-86bd-0113ae6e5071.png)

On Dashboard page:
![Image 2020-06-17 at 3 41 32 PM](https://user-images.githubusercontent.com/83631/84905568-1d918f00-b0b1-11ea-88b2-75096a82ef33.png)
