### ISSUE TITLE
Add opt-in for users to share diagnostic information

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4651]
## Feature description

In order to start building up a database of themes and plugins which are AMP-compatible, we need to get user consent to share that information. Sharing validation errors with amp-wp.org will be very useful not only to discover themes/plugins which are unintentionally AMP-compatible so in that they only make changes to the admin or they only output AMP-compatible markup on the frontend, but will also reveal issues with themes/plugins which we thought were AMP-compatible but actually aren't (and we should report the issue to the theme/plugin author or take down the entry from the ecosystem page).

Once we have the database, we can do much more to direct users to install themes/plugins which are AMP-compatible: https://github.com/ampproject/amp-wp/issues/2313#issuecomment-542307376

Site Kit exposes this as the following setting:

![image](https://user-images.githubusercontent.com/134745/80992411-540b9700-8dee-11ea-829b-bbe3a5ab77e0.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Should we add this as a checkmark in the onboarding wizard?

**Comment by westonruter** [comment]
Yes we should.

**Comment by amedina** [comment]
Since we must provide details on what will be shared, etc., one possibility is to add a full step to the onboarding flow, similar to what is done in plugins like Yoast. 
<img width="1155" alt="Screen Shot 2020-08-05 at 1 11 40 PM" src="https://user-images.githubusercontent.com/506089/89459944-58fa2280-d71e-11ea-8bb9-58fa495e1257.png">

We need to think this feature thoroughly.

**Comment by jwold** [comment]
Took an initial stab at what this could look like.

![Data](https://user-images.githubusercontent.com/3411173/107434621-d775b980-6adf-11eb-906f-46ffd3261111.png)

Figma [link](https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=1808%3A0).

**Comment by westonruter** [comment]
I like that. However, I think we'd want to lean toward “anonymized” rather than “anonymous”. Some of the validation data and site health data will not be anonymous. But any usage of it would be anonymized. Tricky balance.

**Comment by westonruter** [comment]
We'll also need to design this for the settings screen.

**Comment by jwold** [comment]
Good point. I'm thinking something like this:

<img width="856" alt="Screen Shot 2021-02-10 at 2 49 59 PM" src="https://user-images.githubusercontent.com/3411173/107583079-4a019a80-6baf-11eb-88c0-de116ff815bc.png">

**Comment by westonruter** [comment]
We will restrict this user opt-in to sharing site details when opening a support request.
