### ISSUE TITLE
Enable AMP toggle doesn't work when custom fields advanced panel is enabled

### ISSUE THREAD

**Issue by ernee** [Automattic/amp-wp#4659]
## Bug Description

The [Enable AMP](https://jumpshare.com/v/lcjZ4P1kp8dqmfVuo20g) toggle in the editor does not retain the state chosen when the custom fields advanced panel option is enabled:

<img width="386" alt="custom fields advanced panels option" src="https://user-images.githubusercontent.com/8108643/81112848-2567ec00-8ed4-11ea-9468-fec7723476ff.png">

After updating the post, the value for  _amp_status_  does not change in the custom fields panel: 

<img width="1109" alt="amp_status value does not change" src="https://user-images.githubusercontent.com/8108643/81113279-d2daff80-8ed4-11ea-967d-4eb629ebedf2.png">

## Expected Behaviour

The toggle option should retain the state chosen after updating the post/ page in the editor.

## Steps to reproduce

1. Go to the editor for a page/ post with the custom fields panel enabled
2. Toggle [Enable AMP](https://jumpshare.com/v/lcjZ4P1kp8dqmfVuo20g) either on or off
3. Update the page/ post
4. View the page/ post and notice that it is not in the state chosen (AMP enabled or disabled) 
5. Go back to the editor and see the toggle has not retained the state chosen 

## Screenshots

Video: https://recordit.co/A46veHk7wZ

## Additional context

 - WordPress version: 5.4.1
 - Plugin version: 1.5.3
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: All
 - PHP version: 7.3.5
 - OS: MacOS
 - Browser: Chrome, Firefox
 - Device: MacBook Air

Workaround mini plugin: https://gist.github.com/westonruter/392c3042ede361dd3cd5089733356649

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
QA Passed

I can show show the custom fields, add a custom field, and then toggle AMP off, save, reload and the toggle remains off. I can then turn AMP on, save, reload, and the toggle remains on.

![image](https://user-images.githubusercontent.com/134745/87256670-98985c00-c449-11ea-9184-0c9052581821.png)
