### ISSUE TITLE
Use Lullabot's amp-library as sanitizer to simplify code base

### ISSUE THREAD

**Issue by pbakaus** [Automattic/amp-wp#466]
Probably worth investigating if https://github.com/Lullabot/amp-library can be used instead of the sanitizer in the plugin. Would simplify this code base. Thoughts?

**Comment by mjangda** [comment]
It's a really cool library and we looked it over when it first came out. Unfortunately, the PHP requirements don't match up (our min is `5.2` -- following WordPress' min requirements -- and `amp-library` is `5.5`).

**Comment by mustafauysal** [comment]
Hi, 

I wrote a plugin which is using `amp-library`, as @mjangda mentioned above it requires at least PHP 5.5

https://github.com/mustafauysal/simple-amp

**Comment by amedina** [comment]
Thanks @mustafauysal; will take a look at your implementation.

Closing this issue and taking this as a task to investigate and incorporate if possible.
