### ISSUE TITLE
Make it easy for users to submit support requests and review the plugin

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4664]
## Feature description

As a user I would like to: **have easy access to submit a support requests or feedback** to the plugin authors. I would also like to have  easy access to provide a review of the plugin if I chose to do so.

As plugin authors we would like to **get feedback from users that can be used to improve the plugin** and better satisfy their needs. 

To achieve these complementary goals, it would be great to provide an entry point to the support forum to request support and/or provide a review for the plugin. 

The user should not be prompted to leave a review, but making it easier for them to do so would increase the chance they decide to do it. 

As a reference, we can look and part of this feature implemented in Newspack. This can be extended to add a "Provide a review" access point. 

![Screen Shot 2020-05-06 at 2 30 10 PM](https://user-images.githubusercontent.com/506089/81231361-e73bfc80-8fa7-11ea-986c-4606ee2cad80.png)
![Screen Shot 2020-05-06 at 2 30 19 PM](https://user-images.githubusercontent.com/506089/81231368-e86d2980-8fa7-11ea-9e47-f3b3545ac550.png)

**Comment by westonruter** [comment]
As pointed out by @milindmore22, Site Kit has recently done this via plugin row links: https://github.com/google/site-kit-wp/blob/ce582d1910bdf0104792da6f3975a19586ed186d/includes/Core/Admin/Plugin_Row_Meta.php

![image](https://user-images.githubusercontent.com/134745/108405767-5b156180-71d6-11eb-9acf-b04db39b2ebd.png)

This has been filed as #5893.

**Comment by ThierryA** [comment]
Something important to consider is that this will be gradually rolled out on Site Kit (behind a remote controlled flag) to prevent sudden support load and manage the load.

**Comment by westonruter** [comment]
The support screen was added in v2.2.
