### ISSUE TITLE
Missing @type in schema (ld+json) in archive templates

### ISSUE THREAD

**Issue by HelaGone** [Automattic/amp-wp#4666]
## Bug Description

The schema is malformed and missing the `@type` field in the archive templates (archive, tag, taxonomy, etc) therefore they have errors in the structured data

## Expected Behaviour

The schema for archive templates should be well formed with all its required fields. Namely, it should have a `@type` of `collection`.

## Steps to reproduce

1. Install the plugin and activate it
2. Register a custom taxonomy 
3. Create some posta and assign the taxonomy created to them
4. Go to the [validation tool](https://search.google.com/structured-data/testing-tool/u/0/)
5. Perform a test and see the error:  Unspecified Type (The @type is required and cannot be an empty string.)

## Additional context

 - WordPress version: 5.4.x
 - Plugin version: 1.4.2
 - Gutenberg plugin version (if applicable): NONE
 - AMP plugin template mode: 
 - PHP version: 7.1.x
 - OS: 
 - Browser: ALL
 - Device: ALL

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@HelaGone Note that AMP Validation is not what is in question here. The Structured Data Testing Tool is not related to AMP. Nevertheless, the AMP plugin is outputting structured data so it should be valid as well.

Try adding this code to a custom plugin or your custom theme's `functions.php`:

```php
add_filter( 'amp_schemaorg_metadata', function( $data ) {
	if ( is_archive() && ! isset( $data['@type'] ) ) {
		$data['@type'] = 'Collection';
	}
	return $data;
} );
```

**Comment by HelaGone** [comment]
@westonruter Of course!. That hook solved the issue. Thanks for sharing. Also, I want to note that the bug is also affecting the plugin's newest version (1.5.3)

**Comment by westonruter** [comment]
We should be adding this `@type` as the default for archives.

**Comment by schlessera** [comment]
QA passed.

![Image 2020-06-17 at 3 10 23 PM](https://user-images.githubusercontent.com/83631/84902738-7e1ecd00-b0ad-11ea-8273-a428f60ce824.png)
![Image 2020-06-17 at 3 14 58 PM](https://user-images.githubusercontent.com/83631/84902753-824aea80-b0ad-11ea-8a4b-c64d434a6497.png)
