### ISSUE TITLE
Discontinue disabling Optimizer SSR when WP_DEBUG is enabled

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4667]
## Feature description

Optimizer SSR is currently disabled by default when `WP_DEBUG` is enabled:

https://github.com/ampproject/amp-wp/blob/845ba0994e14ecd73a84d2a16c79fa2db479b8d8/includes/class-amp-theme-support.php#L2164-L2166

It seems more sites have `WP_DEBUG` enabled in production than I expected, so this is causing SSR to be disabled on sites when it doesn't need to be. Also, the decision to use `WP_DEBUG` as a signal to turn off SSR was not set in stone and I've wavered as to whether it should be used (and perhaps `is_user_logged_in()` would be better signal). In any case, we can just default to having it enabled always.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
@westonruter For QA purposes, is there an easy way for me to look at a WP post and confirm that it was generated via Optimizer SSR?

**Comment by pierlon** [comment]
@johnwatkins0 One way is to check the page source for `i-amphtml-` attributes, or seeing if the `<html>` element has the `transformed` attribute, which is required for optimized AMP.

**Comment by johnwatkins0** [comment]
Thanks, @pierlon . Moving this to QA Passed because `WP_DEBUG` does not seem to have an effect on SSR.
