### ISSUE TITLE
Highlight the theme/plugins responsible for validation errors and direct to their support forums

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4668]
## Feature description

When a validation error is raised, the editor currently lists out what the errors are without any indication of the theme/plugin that is responsible. Here I created a plugin called “Bad Shortcode” but there is no indication that this plugin is responsible here for the problem:

![image](https://user-images.githubusercontent.com/134745/81325046-aba73e00-904c-11ea-9e6d-4e55a2153e55.png)

Aside: There should be a link from the warning in the block to the specific error(s) on the validated URL screen, with the validation error pre-expanded. See also #3821.

When navigating to review the issues on the validated URL screen, we do there indicate the theme/plugin responsible (here the “Bad Shortcode” plugin)

![image](https://user-images.githubusercontent.com/134745/81324728-3fc4d580-904c-11ea-907e-388768ac6de4.png)

However, we do not provide any encouragement for the user to contact that theme/plugin's author for support. This should be done as the first step before the user reports the issue to the AMP plugin forum, which we seek to facilitate with #4664. If we can determine that the theme/plugin is on WordPress.org, we should directly link to the appropriate support forum.

Relates to #3821, #2673, #4480, #4664.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
This is great as will make it easy for user to notify plugin and theme makers of AMP compatibility issues and compel them to make their ecosystem components fully AMP compatible.

**Comment by westonruter** [comment]
We also need to integrate Plugin Suppression here, providing a way for users to suppress the plugin on AMP pages.

**Comment by jwold** [comment]
Could we also combine this with the work on #3821 from a UI perspective? It feels like the two could go together. 

![Screen Capture on 2020-08-27 at 10-03-41](https://user-images.githubusercontent.com/3411173/91472663-a6b10900-e84c-11ea-90dd-a5df78844acd.gif)

**Comment by westonruter** [comment]
Yeah, #3821 is basically increasing the scope of this to improve the UX. 

The issue here is more of a short-term scoped issue to address the gap without going the next step of improving the overall design.

**Comment by jwold** [comment]
There are three basic criteria for this issue, and I'll address them below based on our discussion last week:

![1](https://user-images.githubusercontent.com/3411173/91870162-8e196800-ec2b-11ea-8e5e-78a72dff2e80.png)

A. While there is more we will do to improve the user experience in Gutenberg, this is an initial start to help users dig in a bit and find out details of what is going on with the error. This link to `Learn More` will direct them to the validated URL screen, where they can find out what plugin caused the issue. We can also add a note directly in the notice about which plugin is causing the error. 

-----------------------------------

![2](https://user-images.githubusercontent.com/3411173/91870237-a4272880-ec2b-11ea-844f-40d518f82a4b.png)

B. This page is rather busy, so I'm concerned that the new button will get lost. This is worth discussing. 

-----------------------------------

![3](https://user-images.githubusercontent.com/3411173/91872166-68d92980-ec2c-11ea-97d1-9ccbb9605ca9.png)

C. In our last call the suggestion was to pause on this for now, and revisit. If we do want to proceed here's an idea of what this could look like:

**Comment by jwold** [comment]
(Updated based on additional discussion)

![A](https://user-images.githubusercontent.com/3411173/92140649-3d8a4200-edc6-11ea-9141-abf256ca078e.png)

-------

![B](https://user-images.githubusercontent.com/3411173/92140662-40853280-edc6-11ea-91a5-c521c2b788af.png)

**Comment by westonruter** [comment]
As noted in https://github.com/ampproject/amp-wp/issues/3821#issuecomment-742736936:

> the important thing for non-technical users is to highlight incompatible theme/plugins. For users with DevTools turned off, we should probably still show the AMP plugin sidebar to alert them of issues. However, listing all of the validation errors is probably too much information.
>
> So here's an idea. When DevTools are turned off, validation errors could be hidden by default in the plugin sidebar. Instead there could be a list of the theme/plugins identified as the sources for those errors in the first section of the sidebar. This could even be relevant when DevTools are enabled: the list of theme/plugins above could serve as a way to _filter_ the list of errors that appear below.

This applies not only to the AMP plugin sidebar, but also to showing a digest in the admin bar (#5166). The list of incompatible themes/plugins would also probably be what is surfaced on the AMP settings screen resulting from cron validation (#1756), theme scanning (#4795) and plugin scanning (#4719). It may even be a part of the proposed notification center: #5671.

**Comment by westonruter** [comment]
This has largely been addressed as part of the Site Scanning update: https://github.com/ampproject/amp-wp/pull/6835#issuecomment-1062243293
