### ISSUE TITLE
Plugin's results are failing AMP Project's validation

### ISSUE THREAD

**Issue by JayHoltslander** [Automattic/amp-wp#467]
**Errors**

1. The tag 'script' is disallowed except in specific forms.

	````
	<script src="//cdn.ampproject.org/v0.js" async></script>
	````

2. Conflict with [Facebook Comments](https://wordpress.org/plugins/facebook-comments-plugin/) plugin for Wordpress
3. The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.

**Live validator result:** <https://validator.ampproject.org/#url=https%3A%2F%2Fjay.holtslander.ca%2F2015%2F05%2Fwhy-you-must-establish-content-before-designing-something%2Famp%2F>

**Comment by mjangda** [comment]
> The tag 'script' is disallowed except in specific forms.
> The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.

Protocol-relative URLs are not allowed in the spec. You need to disable whatever is modifying the URL to remove the protocol/scheme (Cloudflare is a common culprit).

> Conflict with Facebook Comments plugin for Wordpress

Can you open a new Issue with specific details on what the conflict is?

**Comment by JayHoltslander** [comment]
I guess it's the "Always use https" option within @cloudflare that's doing this. Hmm

**Comment by JayHoltslander** [comment]
In case other people find this thread in the future. I received this from CloudFlare's support staff.

>I have seen in the past with AMP making a page rule to bypass CloudFlare resolves most issues:

>You can create a page rule in your dashboard to disable CloudFlare for certain URLs, like so:

>``http://www.example.net/review/*/amp/``

>You will need to make sure all CloudFlare features have been disabled in the page rule.

>Best Regards,

>Kirk D. Washington II - Support Engineer, CloudFlare

The downside here is that if you are running Wordpress on the free plan of CloudFlare you are limited to 3 page rules. Which will probably already be used up as

1. domain.com* = Do stuff
2. domain.com/wp-admin* = Bypass
3. http://domain.com = Always use https

Meaning Wordpress on CloudFlare with AMP will require a paid CloudFlare account to get a fourth page rule. (Doh.)
