### ISSUE TITLE
Extend meta generator tag to include "Official AMP Plugin"

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4672]
Since other plugins are also using a similar meta generator tag, it would be great to make it clear in the tag (for general users) that a given page was generated by the official amp plugin. The proposal is for it to look like:

`<meta name="generator" content="Official AMP Plugin v1.5.3; mode=standard">`

**Comment by westonruter** [comment]
Note this will break the pattern matching in Wappalyzer: https://github.com/AliasIO/wappalyzer/pull/2713

**Comment by amedina** [comment]
Yeah; we can easily fix that with Wappalyzer
