### ISSUE TITLE
Getting Errors in Google Search Console

### ISSUE THREAD

**Issue by singhdeepender891** [Automattic/amp-wp#4675]
I am getting some errors.

URL https://www.filmistory.com/bollywood-news/karan-johar-and-zoya-akhtar-put-together-a-fundraiser-for-the-covid_19-frontline-workers/?amp

Could you please check it.

One Error More (An AMP component ‘script’ tag is present, but unused.)

URL https://www.filmistory.com/bollywood-news/amitabh-bachchan-madhuri-dixit-and-other-celebrities-wish-fans-on-buddha-purnima/?amp

Thanks

The page I need help with: https://www.filmistory.com/bollywood-news/karan-johar-and-zoya-akhtar-put-together-a-fundraiser-for-the-covid_19-frontline-workers/?amp

**Comment by pierlon** [comment]
Hi @singhdeepender891 ,

Please post your [Site Health](https://wordpress.org/support/wordpress-version/version-5-2/#site-health-check) information here. This information should help us in identifying the cause of your issue.

**Comment by amedina** [comment]
It appears you’re using the Newspaper Theme which provides a mobile theme with its own AMP templates. Read more [here](https://forum.tagdiv.com/tagdiv-amp-plugin-tutorial/).

Please follow up with their support forums.
