### ISSUE TITLE
Conflict with Facebook Comments plugin for Wordpress

### ISSUE THREAD

**Issue by JayHoltslander** [Automattic/amp-wp#468]
I've noticed a conflict with [Facebook Comments](https://wordpress.org/plugins/facebook-comments-plugin/) plugin for Wordpress which uses Facebook's commenting system and embeds it in Wordpress posts rather than Wordpress' default commenting system.

The plugin creates `<comments-count>...</comments-count>`

```
The tag 'comments-count' is disallowed.
```

**Live validator result:** https://validator.ampproject.org/#url=https%3A%2F%2Fjay.holtslander.ca%2F2015%2F05%2Fwhy-you-must-establish-content-before-designing-something%2Famp%2F

**Comment by adelporte** [comment]
I also have an issue with the plugin Digg Digg which uses two tags that are seen as errors by the AMP validator : <plusone></plusone> (for Google Plus +1 votes) and <like></like> (for Facebook likes). I turned off the plugin and my posts pass the validator without any issue...
These tags are don't seem HTML5 compliant...

**Comment by amedina** [comment]
This is an interaction issue with the FB Comments plugin which causes the invalidation of AMP pages. It is very difficult to account for all possible interactions with any other plugin. We are looking into ways in which these situations could be handled.
