### ISSUE TITLE
Improve Copy of AMP Settings page

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4684]
- The wording of the Settings page is loaded with technical jargon that could be rephrased in a more accessible and clear way.
- The structure of the page should be revised

/cc @aarondruck @jwold

 
![review-settings-page-copy](https://user-images.githubusercontent.com/506089/81731075-4fc12880-9443-11ea-88fc-788d06d77a68.png)

![enhace-settings-page-2](https://user-images.githubusercontent.com/506089/81731462-cf4ef780-9443-11ea-9e4e-7ee7f1049314.png)

**Comment by westonruter** [comment]
As part of this, I think we should perhaps change the order of the template modes. The Reader mode should perhaps come first since it's the mode that users will most often have success with, and it it is selected by default anyway.
