### ISSUE TITLE
Wide width alignment of videopress block is not respected in AMP mode.

### ISSUE THREAD

**Issue by deepaklalwani97** [Automattic/amp-wp#4692]
## Bug Description

The videopress block does not respect the wide width alignment in the AMP mode. This happens only with the videopress block because the videopress block uses the amp-iframe and the intrinsic layout for all alignments except for the full width alignment. The solution to this could be using the responsive layout for blocks with wide width alignment.

## Expected Behaviour

The videopress block with wide width alignment should have a wide width in the AMP mode.

## Steps to reproduce

1. Create a videopress block from the Gutenberg editor and change alignment to wide width.
2. Check the post in frontend with AMP mode the video does not respect the wide width alignment.

## Screenshots

Wide width aligned Videopress block in Non AMP mode

![image](https://user-images.githubusercontent.com/32839217/81783469-fdead200-9518-11ea-86ac-b8810aa4b7c7.png)

Wide width aligned Videopress block in Non AMP mode

![image](https://user-images.githubusercontent.com/32839217/81783500-0ba05780-9519-11ea-8eac-379c05e93511.png)

## Additional context

 - WordPress version: 5.4.1
 - Plugin version: 1.5.3
 - AMP plugin template mode: Transitional
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed:**

The embed is visually the same as the non-AMP counterpart and has the right layout applied when the "wide width" alignment is applied to the embed block:

![image](https://user-images.githubusercontent.com/16200219/84849770-95c26b00-b045-11ea-8f99-fb62300cc21e.png)
