### ISSUE TITLE
Regarding AMP installation for custom theme

### ISSUE THREAD

**Issue by asmitarane** [Automattic/amp-wp#4696]
HI,

How to install AMP for custom wordpress custom theme?

How to create AMP pages for AMP custom theme?
Thank you!

**Comment by pradeep910** [comment]
@asmitarane I think you can try [amp plugin](https://wordpress.org/plugins/amp/) with `Transitional` mode (formerly `paired`) as described in the documentation here - [https://amp-wp.org/documentation/developing-wordpress-amp-sites/how-to-develop-with-the-amp-plugin/](https://amp-wp.org/documentation/developing-wordpress-amp-sites/how-to-develop-with-the-amp-plugin/)

Your existing site pages should convert to AMP pages automatically, however some javascript related features won't work out of the box. You will need to handle such things via WordPress theme codes. Theme Development part is also explained in [the document](https://amp-wp.org/documentation/developing-wordpress-amp-sites/how-to-develop-with-the-amp-plugin/).
