### ISSUE TITLE
Imgur post embed gives 404 error

### ISSUE THREAD

**Issue by dharmin** [Automattic/amp-wp#4697]
## Bug Description

The Imgur post embed generates AMP tag, it uses post id as data-imgur-id, and it creates incorrect embed URL: `https://imgur.com/2q6AS6i/embed?pub` so it’s not displayed on the AMP page.

```html
<amp-imgur
    data-imgur-id="2q6AS6i"
    layout="responsive"
    width="540"
    height="633"
  >
  </amp-imgur>

```
In the official AMP documentation, there is no information available for Imgur post embed.
https://amp.dev/documentation/components/amp-imgur/

And there is a merged PR to add the support for Imgur posts:
https://github.com/ampproject/amphtml/pull/23829

## Expected Behaviour

The Imgur post embed should generate `data-imgur-id` as `a/<post_id>`. It generates the correct embed URL `https://imgur.com/a/2q6AS6i/embed?pub`.

```html
<amp-imgur
    data-imgur-id="a/2q6AS6i"
    layout="responsive"
    width="540"
    height="633"
  >
  </amp-imgur>

```

## Steps to reproduce

1. Edit/Create WordPress post.
2. Add an Imgur post URL. eg. https://imgur.com/gallery/2q6AS6i
3. Submit the post.
4. View it on AMP mode

## Screenshots

![C3r0URGdKN](https://user-images.githubusercontent.com/6830654/81811953-0eb03d80-9543-11ea-9d3c-be0e8d11d26c.gif)

## Additional context

 - WordPress version: 5.4
 - Plugin version: 1.5.3
 - AMP plugin template mode: Standad
 - PHP version: 7.4
 - OS: Windows 10
 - Browser: Google Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Hi @dharmin,

Thanks for raising this issue. This will be accounted for in #4650.

**Comment by pierlon** [comment]
When embedding the URL https://imgur.com/gallery/2q6AS6i, it does correctly show on the AMP page:

![image](https://user-images.githubusercontent.com/16200219/96030074-0d18d780-0e4b-11eb-946f-a0d1785e21a4.png)
