### ISSUE TITLE
Wizard step: Reader mode > choose mobile theme

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4702]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 
Display screen with headline, paragraph explaining how to choose a reader mode theme
* Display grid list of compatible themes for reader mode
* Allow user to select a theme
* Display legacy theme, with warning of sorts that it's only for specific use cases
* Next button and back button"

**Assumption:** A config list exists with the themes, and this phase does not have anything to do with onboarding to the list. Basically, the wizard shows existing list and you choose from it, that's all the functionality that would exist at the moment in this issue.

* 

## Implementation brief

- New REST endpoint for available reader themes. Each theme will be available for download from wordpress.org. Each will have a title, description, and a featured image, and a link to learn more. Each theme will also have a `downloadable` boolean. This will be true for all themes on sites where the themes directory is writeable; on sites where the themes directory is not writeable, it will be false for all except those that are already installed on the site. The themes will be copied from the data amp-wp.org but hardcoded into the plugin for now. 
- A new helper class providing reader themes. This will be where the theme data is hardcoded, but later can be iterated on to retrieve themes more dynamically. This class can also handle downloading the selected theme from wordpress.org.
- A new option `reader_theme` will be created, storing the slug of the theme the user selects in the wizard. It will be `classic` by default. This setting will need to be integrated into the plugin to show the selected theme on AMP pages. 
- The option will be updated at the end of the setup wizard. At the time the option is updated, if the theme hasn't been installed on the site, it will be downloaded.

## QA testing instructions

1. Inside your local copy of the repo, fetch the latest updates: `git fetch`
2. Clear any uncommitted changes: `git checkout -- .`
3. Check out this branch with `git checkout feature/4702-choose-reader-theme`
4. Rebuild: `composer install && npm install && npm run build`
5. Start your environment: `./bin/local-env/start.sh`
6. Navigate to the wizard page: http://localhost:8890/wp-admin/admin.php?page=amp-setup&amp-new-onboarding=1
7. Navigate to "Reader themes" by clicking "Next step" several times. Choose a theme that you don't have on your site.
8. Navigate to the last page of the wizard. 
9. Return to the Reader Theme page. Verify that your theme is still selected.
10. Refresh the page, return to Reader Theme, and verify your theme is still selected.
11. In the WordPress admin, verify that the theme you selected is available at http://localhost:8890/wp-admin/themes.php

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
Related to #4478 and #4560.

**Comment by johnwatkins0** [comment]
@westonruter Is there any reason we shouldn't make the following request within the plugin to get Reader-friendly themes? https://amp-wp.org/wp-json/wp/v2/ecosystem?ecosystem_types=245&_fields=id,link,title,content,featured_media,meta&per_page=99

I'd like to do one of:

1. Within a REST endpoint in the plugin, fetch that data from amp-wp.org, fetch the featured media, clean up the data a bit, and send it to the screen in the setup wizard listing the mobile themes. I'd probably cache the result for a little while.
2. Copy the result of the above request once and paste it in the plugin, and just use that.

Option 1 is not much more work or code than option 2, but if the list of themes on amp-wp.org doesn't change much or there is an alternative way of cataloging these themes coming along in the near future, then hard-coding the theme data would be simpler and would save the need to make those REST requests to amp-wp.org.

**Comment by johnwatkins0** [comment]
I have updated the implementation brief on this issue covering discussions today, including the above question.

**Comment by westonruter** [comment]
Also, based on chatting today, we may need to supply mobile viewport screenshots of the themes we provide in Reader mode. That adds weight to the need to draw from a curated list and not just pull down from an endpoint. We'll not be able to show a list of themes based on theme slugs alone, as we'll also need to provide the mobile viewport screenshot. True these screenshots could be served by amp-wp.org, but then we'd need to add a new mobile screenshot field to the REST API there.

**Comment by westonruter** [comment]
> * Each theme will also have a `downloadable` boolean. This will be true for all themes on sites where the themes directory is writeable; on sites where the themes directory is not writeable, it will be false for all except those that are already installed on the site.

For themes that are _not_ already installed, shouldn't there rather be an `available` field? For themes which are not installed but where a site allows them to be installed, then it could be `true` as well. Then there could be another field for `installed`. When `installed` and `available` are both false, then the theme would need to be disabled from being selected.

**Comment by johnwatkins0** [comment]
> Also, based on chatting today, we may need to supply mobile viewport screenshots of the themes we provide in Reader mode. 

@jwold Is working on the screenshots. Joshua, let me know if you need help gathering a list of the themes that are on wordpress.org. Note that we also need a screenshot of the classic theme.

**Comment by johnwatkins0** [comment]
> For themes that are already installed, shouldn't there rather be an available field? For themes which are not installed but where a site allows them to be installed, then it could be true as well. Then there could be another field for installed. When installed and available are both false, then the theme would need to be disabled from being selected.

With the current approach, the user isn't going to need to know whether the theme has been installed already. When they reach the last step, the plugin will determine whether it needs to be downloaded or not, which will all happen under the hood.

Unless there's a reason we should surface to the user that they don't have the theme installed, like text to the effect of "This theme will be installed." I'm not sure if that's useful information for the user. cc @jwold

**Comment by jwold** [comment]
So we have a potential issue. When you go to preview a theme, the demo content shown is simply a list of all the elements in the theme, it is not a "designed" version of the theme. 

So, a mobile preview of the theme is nothing like the screenshot shared. We'd need to recreate each theme to look somewhat decent on mobile. That's a bit of a lift. 

<img width="1109" alt="Screen Shot on 2020-05-27 at 10-50-14" src="https://user-images.githubusercontent.com/3411173/83054872-f1ca3e80-a007-11ea-9226-f1623585ef2f.png">

**Comment by westonruter** [comment]
To gather mobile screenshots, you'd have to activate the theme and perhaps reset some settings so the default header image is used, or else supply a header image. So yes, there's a bit of work to get the theme configured for a good mobile screenshot, but not more than a few minutes per theme I'd think.

**Comment by jwold** [comment]
Just tested out the activation theme. There were a few weird settings with this one (some stuff in widgets, some stuff in Customizer), as well as needing to hunt down where the original image was, and re-writing the headlines/taglines, etc. Took 30 minutes, but I'm mostly happy with the results. 

<img width="1051" alt="Screen Shot 2020-05-27 at 12 19 23 PM" src="https://user-images.githubusercontent.com/3411173/83062989-5390a580-a014-11ea-8871-6cc8a0d93fd2.png">

**Comment by johnwatkins0** [comment]
@jwold In case it's useful, here's are the themes I'm working with (their slugs and parent slugs). 

```PHP
Array
(
    [0] => Array
        (
            [slug] => classic
            [parent] => 
        )

    [1] => Array
        (
            [slug] => activation
            [parent] => primer
        )

    [2] => Array
        (
            [slug] => velux
            [parent] => primer
        )

    [3] => Array
        (
            [slug] => scribbles
            [parent] => primer
        )

    [4] => Array
        (
            [slug] => ascension
            [parent] => primer
        )

    [5] => Array
        (
            [slug] => uptown-style
            [parent] => primer
        )

    [6] => Array
        (
            [slug] => go-godaddy
            [parent] => 
        )

    [7] => Array
        (
            [slug] => memory-2
            [parent] => 
        )

    [8] => Array
        (
            [slug] => twentytwenty
            [parent] => 
        )

    [9] => Array
        (
            [slug] => primer
            [parent] => 
        )

    [10] => Array
        (
            [slug] => twenty-fourteen
            [parent] => 
        )

    [11] => Array
        (
            [slug] => twenty-thirteen
            [parent] => 
        )

    [12] => Array
        (
            [slug] => twenty-eleven
            [parent] => 
        )

    [13] => Array
        (
            [slug] => twenty-ten
            [parent] => 
        )

    [14] => Array
        (
            [slug] => zakra
            [parent] => 
        )

    [15] => Array
        (
            [slug] => neve
            [parent] => 
        )

    [16] => Array
        (
            [slug] => astra
            [parent] => 
        )

    [17] => Array
        (
            [slug] => twenty-twelve
            [parent] => 
        )

    [18] => Array
        (
            [slug] => twenty-nineteen
            [parent] => 
        )

    [19] => Array
        (
            [slug] => twenty-seventeen
            [parent] => 
        )

    [20] => Array
        (
            [slug] => twenty-sixteen
            [parent] => 
        )

    [21] => Array
        (
            [slug] => twenty-fifteen
            [parent] => 
        )

)
```

**Comment by westonruter** [comment]
Per our conversation over chat, only the core themes should be included. So that is specifically this list of themes:

* twentytwenty
* twentynineteen
* twentyseventeen
* twentysixteen
* twentyfifteen
* twentyfourteen
* twentythirteen
* twentytwelve
* twentyeleven

This does not include twentyten since it is not responsive.
