### ISSUE TITLE
Make the settings screen more visually appealing and reuse React components

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4704]
## Feature description

Updating the UI of the settings screen to match the look and feel of the onboarding, as well as allow for changing the template mode. 

## Acceptance criteria

![Settings](https://user-images.githubusercontent.com/3411173/86269275-63088e80-bb7e-11ea-835e-d9a9791dc121.png)

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
@jwold @westonruter @amedina 

Question that has come up around the admin notice. Currently the AMP plugin has this notice that shows on the plugin options screen until the user dismisses it:

<img width="860" alt="Screen Shot 2020-06-02 at 11 38 17 AM" src="https://user-images.githubusercontent.com/9020968/83546551-76b0ce80-a4c6-11ea-97bf-f36abc3d5868.png">

I think our options for this new notice are:

1) Have two dismissible notices on the AMP options screen. The new notice will be the same both on AMP options and on the plugins screen.
2) Update the existing notice and display the same notice on the plugins screen as well.
2) Update the existing notice on the AMP options screen, and display a different (probably simpler) notice on the plugins screen.

Another option that would be a heavier lift mainly from the design standpoint would be to add more branding to the AMP options screen that is not in the form of a dismissible notice. Some of the existing dismissible notice could be repurposed for this. Then we could have a simple dismissible notice directing users to the setup wizard, and the same notice could be used on the plugin screen.

**Comment by jwold** [comment]
I like this direction. Exploring it now in design.

**Comment by jwold** [comment]
<img width="1458" alt="Screen Shot 2020-06-23 at 9 12 34 AM" src="https://user-images.githubusercontent.com/3411173/85428179-b0a74a80-b531-11ea-816a-86ca5f06b675.png">

**Comment by jwold** [comment]
Took a stab at what the settings page could look like for the wizard onboarding notice. Also ended up giving a treatment of the entire settings page to see how it would feel. 

![Exploration](https://user-images.githubusercontent.com/3411173/85461921-caf51e80-b559-11ea-9a79-bbad878aa939.png)

cc @amedina, @westonruter, @johnwatkins0

**Comment by amedina** [comment]
I like it! 

Modulo the copy (this needs work), it looks good.

**Comment by jwold** [comment]
Awesome! Agree on tweaking the copy. 
GitHub <notifications@github.com> wrote:
“I like it!

Modulo the copy (this needs work), it looks good.”

**Comment by johnwatkins0** [comment]
@jwold I think we'll need to include this:

<img width="700" alt="Screen Shot 2020-06-24 at 10 48 06 AM" src="https://user-images.githubusercontent.com/9020968/85588509-5dec9200-b608-11ea-9975-1e6e96c0af24.png">

**Comment by westonruter** [comment]
Yes, that will be displayed when the “Serve all templates as AMP” toggle is off.

**Comment by jwold** [comment]
Here's a stab at the remaining content:

![Group 3058](https://user-images.githubusercontent.com/3411173/85621525-46b6a000-b61a-11ea-8271-96ebae105501.png)

**Comment by westonruter** [comment]
The Content Types and Templates should go _inside_ that Supported Templates box. They are conditionally shown if the toggle is off. Also note that the templates are presented as a hierarchy, so there will necessarily be indentations.

**Comment by johnwatkins0** [comment]
Since we have built most of this UI already, I think it would make sense to build this page using the React components we already have (with a small amount of refactoring to ensure everything is reusable). It will work the same from a user standpoint, except for the small difference that the interface will be rendered client-side.

**Comment by johnwatkins0** [comment]
I'm breaking the plugin screen notice into a separate issue and keeping this one focused on the settings screen because the two updates are functionally separate.

**Comment by westonruter** [comment]
Also need to incorporate the Plugin Suppression section: https://github.com/ampproject/amp-wp/pull/4657
