### ISSUE TITLE
Update copy for identifying when a user is in the AMP version of Customizer

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4708]
## Feature description

This is specifically for when the site is in Reader mode and a Reader theme has been selected. So this doesn't apply in Classic Reader mode.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* ~In the Customizer have pointers showing how to make header color changes as well as fonts, etc.~
* ~AMP toggle in bottom should have pointer to make sure user is aware it's on and can be toggled.~

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Need a discussion about: 

* Whether we split functional from presentation options in Customizer
* Design toggle to switch between AMP and non AMP versions of site: https://d.pr/i/iOxZAk

**Comment by westonruter** [comment]
> * In the Customizer have pointers showing how to make header color changes as well as fonts, etc.

I don't think we actually need to worry about this. If we try too hard to add pointers, we'll have trouble as we start allowing more themes which have their own unique settings. 

> * AMP toggle in bottom should have pointer to make sure user is aware it's on and can be toggled. […] Design toggle to switch between AMP and non AMP versions of site: https://d.pr/i/iOxZAk

The AMP toggle in the Customizer today's Reader mode won't apply in the new Reader mode when a theme is selected. So yes, the question is how we can be more explicit that the user is editing the AMP version of the site which is currently indicated here:

![image](https://user-images.githubusercontent.com/134745/82089198-0887a180-96a8-11ea-8b36-65d70e7e8ba0.png)

> * Whether we split functional from presentation options in Customizer

The key thing to be wary of here is identifying which settings are theme-specific and which are not. If there is a setting which is not theme-specific (e.g. the Site Title), changing it will affect both the AMP and non-AMP version of the site. This may need some explicit indication. Conversely, if a setting is theme-specific but the non-AMP theme has a corresponding theme-specific setting (e.g. Custom Logo), there should be a facility to copy over the settings on a setting-by-setting basis. Perhaps a copy button could appear next to such controls.

**Comment by amedina** [comment]
@jwold Can we fill out the Feature Description?

**Comment by jwold** [comment]
Sure thing!

**Comment by amedina** [comment]
Related to: https://github.com/ampproject/amp-wp/issues/4784

**Comment by jwold** [comment]
Thinking the main thing we could do is a small illustration and tweak the copy. 

![export 2](https://user-images.githubusercontent.com/3411173/85465289-7784cf80-b55d-11ea-94b4-b17fe957b9f3.png)

**Comment by westonruter** [comment]
Implemented in #4984.
