### ISSUE TITLE
Wizard step: Transitional mode

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4709]
## Feature description

The transitional mode will need to be represented in the onboarding wizard to clearly help users choose it, as well as present them with a summary of what they've chosen. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

~No change in Phase 1. If user chooses this mode, selecting `next` takes them out of the wizard, back to the AMP Settings screen, and from there they see which mode they're in, and can retrigger the wizard.~

Transitional mode can be chosen as an option on the `template modes` screen. When that happens the following screens will update as a result of this choice. 

* The `reader themes` page will be skipped
* The `please wait` page will be skipped (need verification on this)
* The summary page will be present with different visuals. 
  * The description paragraph will be updated. 
  * Redirect to mobile checkmark is present
* The visuals will show screenshot of their parent theme, and a generic illustration of the mobile site indicating that it's an AMP site. 
* The `done` page will also be updated, exact copy TBD. 
* They'll be then taken to the settings page with an updated getting started module. 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
See also https://github.com/ampproject/amp-wp/issues/4707#issuecomment-629433953:

> Alternatively, if they selected Transitional mode, instead of providing the user with the site embedded in an iframe or to go to the Customizer, the call to action can be to open paired browsing to navigate around the site.

**Comment by jwold** [comment]
I'm good with exploring either of those options. Thanks!

**Comment by jwold** [comment]
Updated based on our discussing earlier this week for how the wizard will change if this mode is selected.

**Comment by westonruter** [comment]
> * The `reader themes` page will be skipped
> * The `please wait` page will be skipped (need verification on this)
> * The summary page will be present with different visuals.
>   * The description paragraph will be updated.
>   * Redirect to mobile checkmark is present
> * The visuals will show screenshot of their parent theme, and a generic illustration of the mobile site indicating that it's an AMP site.

See https://github.com/ampproject/amp-wp/issues/4710#issuecomment-642953907.

> * They'll be then taken to the settings page with an updated getting started module.

For all three modes, there should be a call to action to browse the site (in the new AMP version whichever that is). In Standard mode, this is just browsing the site as normal since there is only one version. In Transitional and Reader modes, this means browsing the AMP version.

In addition to these, Reader mode will also have a call to action to open the Customizer.

Lastly, there should also be a call to action to go to the admin Settings screen.
