### ISSUE TITLE
Propose a new design for the Compat Tool

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4712]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Make the tool to operate in a conversational way
* * Microcopy and design for mult-journey path
* Minimize validation errors for amp reader users
* Where compatibility tool data is uses (admin bar, posts, wp-admin, and anywhere else it appears: gutenberg, classic editor)
* Designer: screenshot all the places it's happening

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
cf. #2316
