### ISSUE TITLE
Propose a new design for the admin/settings screens

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4713]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Plugin tour on command button needs to be accounted for here. 
* Microcopy and design for mult-journey path
* Design settings screen to match wizard (Woo inspiration)

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> * Design settings screen to match wizard (Woo inspiration)

Yes, this is key. Consistency between the stepping wizard and the full settings screen.

**Comment by jwold** [comment]
This is now redundant and copies #4704
