### ISSUE TITLE
Error handling in Reader Mode

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4715]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Error suppression and notifications for reader mode

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is already captured in #2673.

**Comment by westonruter** [comment]
Also, it's not just about Reader mode but whenever the user has Dev Tools disabled, regardless of the template mode.

**Comment by amedina** [comment]
@jwold we need to fill out the Feature Description and make the issue titles more descriptive. `Error Handling in Reader Mode` offers little perspective on what the feature is about.

**Comment by jwold** [comment]
I propose we close this issue. It is no longer accurate since #2673 captured the intent. And I agree with Alberto that it's not a good example of a ticket. :)
