### ISSUE TITLE
Goals with site questions

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4720]
## Feature description

![Screen Shot 2020-05-13 at 3.25.33 PM.png](https://images.zenhubusercontent.com/56fb18016caf56c9d38eea1d/9f7c239f-17a6-41de-b42b-13867223a14a)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
Closing this, as it was decided we wouldn't need this screen.
