### ISSUE TITLE
Raise PHPStan level for the `AmpProject\AmpWP` package to 4

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4733]
## Feature description

The plugin package (`AmpProject\AmpWP`) is currently sitting at and enforcing level 3 of PHPStan static analysis.

There are 27 errors that need to be fixed so that we can raise the level to 4 and enforce this new quality level in Travis CI.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHPStan does not show any detected errors when run on level 4.

## Implementation brief

* Change the level to `4` in the file `phpstan.neon.dist`.
* Run `composer analyze`.
* Fix detected errors until no more are found.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
### includes/admin/class-amp-post-meta-box.php
|Line|Error|
|---:|---|
|136|Property WP_Screen::$is_block_editor (bool) in isset() is not nullable.|
|268|Property WP_Post::$ID (int) in isset() is not nullable.|
### includes/amp-helper-functions.php
|Line|Error|
|---:|---|
|1703|Strict comparison using === between false and string will always evaluate to false.|
### includes/class-amp-theme-support.php
|Line|Error|
|---:|---|
|423|Call to function method_exists() with (int|string) and 'add_buffering_hooks' will always evaluate to false.|
### includes/cli/class-amp-cli-validation-command.php
|Line|Error|
|---:|---|
|698|If condition is always true.|
### includes/embeds/class-amp-facebook-embed-handler.php
|Line|Error|
|---:|---|
|109|Strict comparison using === between null and string will always evaluate to false.|
### includes/embeds/class-amp-playlist-embed-handler.php
|Line|Error|
|---:|---|
|98|Property AMP_Playlist_Embed_Handler::$removed_shortcode_callback (callable) in isset() is not nullable.|
### includes/embeds/class-amp-tiktok-embed-handler.php
|Line|Error|
|---:|---|
|53|Left side of &amp;&amp; is always true.|
### includes/options/class-amp-options-manager.php
|Line|Error|
|---:|---|
|322|Property WP_Post_Type::$label (string) in isset() is not nullable.|
|554|Call to function is_array() with bool will always evaluate to false.|
### includes/sanitizers/class-amp-base-sanitizer.php
|Line|Error|
|---:|---|
|228|Strict comparison using === between null and string will always evaluate to false.|
### includes/sanitizers/class-amp-core-theme-sanitizer.php
|Line|Error|
|---:|---|
|1012|Negated boolean expression is always false.|
|1706|Instanceof between DOMElement and DOMComment will always evaluate to false.|
### includes/sanitizers/class-amp-iframe-sanitizer.php
|Line|Error|
|---:|---|
|384|Result of &amp;&amp; is always false.|
### includes/sanitizers/class-amp-img-sanitizer.php
|Line|Error|
|---:|---|
|401|Strict comparison using === between 'figure' and 'a' will always evaluate to false.|
### includes/sanitizers/class-amp-meta-sanitizer.php
|Line|Error|
|---:|---|
|318|If condition is always true.|
### includes/sanitizers/class-amp-style-sanitizer.php
|Line|Error|
|---:|---|
|476|Property AMP_Style_Sanitizer::$used_class_names (array) in isset() is not nullable.|
|697|Property AMP_Style_Sanitizer::$used_tag_names (array) in isset() is not nullable.|
|2658|Negated boolean expression is always false.|
### includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php
|Line|Error|
|---:|---|
|2646|Left side of &amp;&amp; is always true.|
|2646|Right side of &amp;&amp; is always true.|
### includes/templates/class-amp-post-template.php
|Line|Error|
|---:|---|
|190|Property AMP_Post_Template::$data (array) in isset() is not nullable.|
### includes/utils/class-amp-image-dimension-extractor.php
|Line|Error|
|---:|---|
|146|If condition is always false.|
### includes/validation/class-amp-validation-error-taxonomy.php
|Line|Error|
|---:|---|
|464|Call to function in_array() with arguments string, array(0, 1, 3, 2) and true will always evaluate to false.|
|464|Result of &amp;&amp; is always false.|
### includes/validation/class-amp-validation-manager.php
|Line|Error|
|---:|---|
|1830|If condition is always true.|
### src/Admin/SiteHealth.php
|Line|Error|
|---:|---|
|325|Right side of &amp;&amp; is always true.|

**Comment by pooja-muchandikar** [comment]
Performed smoke testing on the plugin and the features are working as expected ✅ 
No blockers found so far.
