### ISSUE TITLE
AMP page for image attachment has wrong alignment for image

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#4735]
## Bug Description

The AMP page for an image attachment displays the image as centered, while the image non-AMP counterpart is left-aligned.

## Expected Behaviour

AMP and non-AMP page for an image attachment should have the same alignment.

## Steps to reproduce

1. View the page for an image attachment.
2. Compare the non-AMP and AMP version of the page

## Screenshots

![image](https://user-images.githubusercontent.com/16200219/82115820-b3ee3000-9754-11ea-9114-a457ca61b22a.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Somehow this issue is caused by this rule:

```css
amp-img:not([_]) {
    display: block;
}
```

This was added in #4421 to fix #4419:

https://github.com/ampproject/amp-wp/blob/2bfb9bb9450d11a652827da39533746bc6e5357c/includes/sanitizers/class-amp-core-theme-sanitizer.php#L778-L803
