### ISSUE TITLE
Videos without cover is not visible in AMP if "preload:none" attribute is added in "video" shortcode

### ISSUE THREAD

**Issue by itowhid06** [Automattic/amp-wp#4740]
## Bug Description

In the WordPress Block Editor, if a video shortcode with `preload=”none”` attribute is added then video does not appear in AMP version until we click on the blank space of Video. Though the video element is visible if it has a cover. This is happening presumably because of this block of code https://github.com/ampproject/amphtml/blob/master/extensions/amp-video/0.1/amp-video.js#L361

## Expected Behaviour

Video element should be visible regardless of preload attribute value.

## Steps to reproduce
1. Create a post with video shortcode, add `preload="none"` attribute
2. Open the AMP version of the post or open the post in Paired browsing mode
3. See video element is completely hidden if it doesn't have a cover.

## Screenshots

**Initially Video element is hidden**

![image](https://user-images.githubusercontent.com/12055657/82209490-24e93f80-992f-11ea-979e-09bea5bc9fed.png)

**Video appears when clicked on the blank space**

![captured (3)](https://user-images.githubusercontent.com/12055657/82211242-62030100-9932-11ea-9555-f19e289d42d4.gif)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Humm. That seems almost like a bug in AMP. There's no indication that clicking the `amp-video` element will cause it to load. It's not even keyboard-accessible. What's more is that it seems like clicking the `amp-video` should then cause the video to start playing immediately, rather than requiring a second click. I think this warrants an AMP issue.

However, in practice, such shortcodes with `preload=none` should be required to supply a `poster` as otherwise there is no indication it is playable, no?

**Comment by westonruter** [comment]
Humm, actually I'm not seeing the issue I described now. When I add a video block that has `preload=none` the result is:

![image](https://user-images.githubusercontent.com/134745/82386796-2b88bd00-99ea-11ea-950c-8fb1650f9836.png)

I get the same result when adding a video in a Classic block (which is a `video` shortcode).
