### ISSUE TITLE
Create documentation for AMP Optimizer (inside the plugin)

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#4743]
As a developer I would like to be in the know regarding the capabilities and benefits brought by the AMP optimizer library. Also, any configuration options available and how to calibrate the use of this plugin feature according to my needs,.

**Comment by schlessera** [comment]
I've written up a first draft of the docs here: https://amp-wp.org/?p=6541&post_type=documentation&preview=1&_ppp=e792aba45a

**Comment by schlessera** [comment]
The formatting is totally off for the second column header of the table:
![Image 2020-06-13 at 1 32 16 AM](https://user-images.githubusercontent.com/83631/84553909-d3598800-ad15-11ea-8d1f-c8bfa69f56ab.png)

Is this something we need to fix with CSS, or is there a markup hack I should use?

**Comment by westonruter** [comment]
> Is this something we need to fix with CSS, or is there a markup hack I should use?

I've seen this elsewhere on the site. @jamesozzie Did you have a fix for that? 

Short answer, I don't know. Maybe you could add `&nbsp;` characters?

**Comment by schlessera** [comment]
It doesn't include any spaces at all.

**Comment by westonruter** [comment]
OK, then apparently we need to fix it with CSS.

**Comment by Krapulat** [comment]
Is there any documentation to implement AMP Optimizer?

**Comment by pierlon** [comment]
@Krapulat The documentation for the AMP Optimizer can be found [here](https://github.com/ampproject/amp-toolbox-php#amp-optimizer-for-php).

**Comment by pierlon** [comment]
Closing since the documentation for the AMP Optimizer is [now available](https://github.com/ampproject/amp-toolbox-php#amp-optimizer-for-php), and configuring it for use in the plugin can be done through the [`amp_optimizer_config` filter](https://github.com/ampproject/amp-wp/blob/06c9b9531874174facfa805cad683c73617360a8/docs/hook/amp_optimizer_config.md).
