### ISSUE TITLE
Twentyfifteen: Sidebar has unexpected scrollbar

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4744]
## Bug Description

The sidebar in the `twentyfifteen` Core theme has an unexpected scrollbar in the sidebar.

## Expected Behaviour

The sidebar should just be integrated into the page and not scroll separately.

## Steps to reproduce

1. Install and activate the `twentyfifteen` theme
2. Make sure you have multiple widgets in the main sidebar to fill more than one scree.
3. Go to the AMP version of a page.
4. **Verify:** The sidebar has its own scrollbar and scrolls independently from the page.

## Screenshots

![Image 2020-05-19 at 8 07 26 AM](https://user-images.githubusercontent.com/83631/82290907-3cb0da00-99a8-11ea-8209-64c002c99ab3.png)

## Additional context

 - WordPress version: 5.4.1
 - Plugin version: 1.6.0-alpha at commit 2bfb9bb94
 - AMP plugin template mode: Transitional
 - PHP version: 7.2.30
 - OS: Mac OS X
 - Browser: Google Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is expected, actually. The only way I could figure out how to emulate the theme's sidebar behavior in AMP was to use `position:sticky` with overflow scrolling.

**Comment by schlessera** [comment]
If you use `position: sticky; top: 32px` without any `max-height`, it's already closer to the original theme and doesn't add a scrollbar. The only difference is that it starts to scroll later than the original theme, but that's already an improvement over now.

With `position: sticky; bottom: x?` we could probably replicate the original behavior completely, but that would require a markup change, and so could break existing styling.

**Comment by schlessera** [comment]
The original theme weirdly enough only uses the sticky on the largest breakpoint, but not on the intermediate one - which has the same overall layout.

**Comment by westonruter** [comment]
OK, it's been a couple years since I worked on this (see #1074). 

The code in question is:

https://github.com/ampproject/amp-wp/blob/b48aba3980239bd883c4623ece9bd227fa4d4b8e/includes/sanitizers/class-amp-core-theme-sanitizer.php#L1203-L1212

If your approach works better then I'm all for it!
