### ISSUE TITLE
Suppress validation errors that may occur from fatal errors being displayed

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#4747]
## Bug Description

While performing QA on #4580, @schlessera brought to light an issue with the number of validation errors that should be displayed when validating a page with fatal errors. It was found that the number of validation errors being reported for a page with fatal errors being displayed can differ, depending on the environment the plugin is in (see https://github.com/ampproject/amp-wp/issues/4580#issuecomment-630835233).

To prevent this discrepancy, we can set the PHP configuration value `display_errors` to `false` before the validation occurs, as suggested by @westonruter in https://github.com/ampproject/amp-wp/issues/4580#issuecomment-630976083.

Related: #4580.

## Expected Behaviour

Validation errors should not be reported for fatal errors being displayed on a page.

## Steps to reproduce

1. Set the `display_errors` PHP configuration value to `true`
2. Download, install, and activate the following gist plugin: https://gist.github.com/pierlon/cb3dc7e78ae99ba48e377d8256de5cb5
3. On the frontend of the site, the admin bar should be showing 8 validation errors:
![image](https://user-images.githubusercontent.com/16200219/82393474-fc983880-9a35-11ea-9443-df565005224c.png)
4. When viewing the validation errors for the screen, more than 4 validation errors should be reported, instead of the 4 actual errors on the page:
![image](https://user-images.githubusercontent.com/16200219/82393520-281b2300-9a36-11ea-9bd6-224309f76473.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
To reproduce the issue, I had to enable Xdebug and turn on the `html_errors` PHP setting.

**Comment by westonruter** [comment]
One side effect of this is if I have a non-fatal error with Xdebug enabled, I will get validation errors reported on the frontend but _not_ when validating a URL.

For example, with this plugin code:

```php
add_action( 'wp_footer', function() {
	trigger_error('oops', E_USER_WARNING);
} );
```

And with Xdebug running and the `wp-config.php` containing:

```php
define( 'WP_DEBUG_DISPLAY', true );
ini_set( 'html_errors', '1' );
ini_set( 'xdebug.cli_color', '1' );
```

The frontend shows:

> ![image](https://user-images.githubusercontent.com/134745/87254507-10f62180-c438-11ea-9161-3af88b947510.png)

But the Validated URL screen shows:

> ![image](https://user-images.githubusercontent.com/134745/87254512-1c494d00-c438-11ea-8e88-5310ec7e26c0.png)

We could work around this by explicitly sanitizing the markup that Xdebug outputs as part of its colorized error messages:

> ![image](https://user-images.githubusercontent.com/134745/87254593-78ac6c80-c438-11ea-839f-d39c032a7baf.png)

The style sanitizer could be tasked with rewriting `font` elements to be `span` with the appropriate styles added.

We can actually fix the discrepancy from warnings being output during page generation to rather _move_ the turning off of `display_errors` from `AMP_Validation_Manager::init_validate_request()` to rather be right before sanitization happens in `AMP_Theme_Support::prepare_response()`:

```diff
diff --git a/includes/class-amp-theme-support.php b/includes/class-amp-theme-support.php
index 646b19ef1..d1276bedb 100644
--- a/includes/class-amp-theme-support.php
+++ b/includes/class-amp-theme-support.php
@@ -1912,6 +1912,11 @@ class AMP_Theme_Support {
 		$dom = Document::fromHtml( $response );
 
 		if ( AMP_Validation_Manager::$is_validate_request ) {
+			// Suppress the display of fatal errors that may arise during validation so that they will not be counted as actual validation errors.
+			if ( '1' === (string) ini_get( 'display_errors' ) ) {
+				ini_set( 'display_errors', 0 ); // phpcs:ignore WordPress.PHP.IniSet.display_errors_Blacklisted
+			}
+
 			AMP_Validation_Manager::remove_illegal_source_stack_comments( $dom );
 		}
 
diff --git a/includes/validation/class-amp-validation-manager.php b/includes/validation/class-amp-validation-manager.php
index 50cbec5a0..e5700b119 100644
--- a/includes/validation/class-amp-validation-manager.php
+++ b/includes/validation/class-amp-validation-manager.php
@@ -537,12 +537,6 @@ class AMP_Validation_Manager {
 		if ( true === $should_validate_response ) {
 			self::add_validation_error_sourcing();
 			self::$is_validate_request = true;
-
-			if ( '1' === (string) ini_get( 'display_errors' ) ) {
-				// Suppress the display of fatal errors that may arise during validation so that they will not be counted
-				// as actual validation errors.
-				ini_set( 'display_errors', 0 ); // phpcs:ignore WordPress.PHP.IniSet.display_errors_Blacklisted
-			}
 		} else {
 			self::$is_validate_request = false;
```

However, this wouldn't then fix the issue of an error being raised during output buffering which is what #4580 was all about.

So there's room for improvement here, _somehow_, but the issue as reported is resolved by the PR.

QA passed.
