### ISSUE TITLE
Webmaster tools errors: ld+json

### ISSUE THREAD

**Issue by R3dRidle** [Automattic/amp-wp#475]
If I run my website via the structured data testing tool from Google I get 2 errors.
1. logo 
   A value for the logo field is required.
   How to set the logo?
2. image
   A value for the image field is required.
   I don't have an image in the specific post, so where is this error comming from?

https://search.google.com/structured-data/testing-tool?url=https%3A%2F%2Fwww.llowlab.nl%2Fsupersnelle-3d-printer-breekt-alle-records%2Famp%2F#url=https%3A%2F%2Fwww.llowlab.nl%2Fsupersnelle-3d-printer-breekt-alle-records%2Famp%2F

**Comment by R3dRidle** [comment]
I found that to fix issue 1 the metadata for the Organization has to have a logo property.
I hardcoded this now, but would be nice to have a filter/action to extend this.

```
'logo' => array(
	'@type' => 'ImageObject',
	'url' => 'https://www.llowlab.nl/wp-content/uploads/logo1.png',
),
```

Still looking for the cause of issue 2.

**Comment by R3dRidle** [comment]
Nobody has anything to help me with? On how to do this via filters or actions?

**Comment by rposbo** [comment]
To get around the hard-coding of the logo, have you tried explicitly defining the `site_icon_url`, since this is what this plugin uses to set the "logo" value?

You can find it under: Admin -> Appearance -> Customize -> Site Identity -> Site Icon

Agreed about the default image. Looks like this bit needs an `else`:

```php
		$image_metadata = $this->get_post_image_metadata();
		if ( $image_metadata ) {
			$metadata['image'] = $image_metadata;
		}
```

**Comment by R3dRidle** [comment]
Well yes the Site Icon works, but than it allso uses this as my logo. Wich I can ofcouse hide with CSS.
The other part does need an else statement for default image yes.

**Comment by pppdog** [comment]
$metadata['publisher']['logo'] = array(
    '@type' => 'ImageObject',
    'url' => 'https://www.llowlab.nl/wp-content/uploads/logo1.png',
     'height' => 60,
        'width' => 600,
    ),

**Comment by R3dRidle** [comment]
Thank you pppdog

**Comment by pppdog** [comment]
@R3dRidle 
^^

**Comment by sjukunte** [comment]
@pppdog My code is not working.

Please check my code. waiting for positive reply.

add_filter( 'amp_post_template_metadata', 'xyz_amp_modify_json_metadata', 10, 2 );

function xyz_amp_modify_json_metadata( $metadata, $post ) {
$metadata['@type'] = 'NewsArticle';
$metadata['publisher']['logo'] = array(
'@type' => 'ImageObject',
'url' => 'http://www.unseenbollywood.com/wp-content/uploads/2017/03/Unseen-Bollywood-Amp-Logo.png',
'height' => 60,
'width' => 600,
);
return $metadata;
}
