### ISSUE TITLE
Script translations lack source attribution 

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4750]
## Bug Description

Given a plugin that enqueues a script and adds script translations:

```php
add_action(
	'wp_enqueue_scripts',
	function () {
		wp_enqueue_script( 'foo', plugin_dir_url( __FILE__ ) . 'foo.js', [], false, true );
		wp_set_script_translations( 'foo', 'foo' );
	}
);
```

This results in `i18n.js` being enqeued from core, but the plugin is properly attributed. The `foo.js` file is also properly attributed to the plugin. The translations `script` however is not properly attributed:

![image](https://user-images.githubusercontent.com/134745/82493607-19b42200-9a9d-11ea-805d-ea1d5f1832a3.png)

The plugin is currently accounting for inline scripts added via `wp_localize_script()` and `wp_add_inline_script()` but it is not for `wp_set_script_translations()`.

## Expected Behaviour

Scripts output via `wp_set_script_translations()` should be attributed to the plugin/theme that added it.

## Steps to reproduce

1. Create a plugin with the above PHP code.
2. Validate a page.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by delawski** [comment]
**QA Passed**

After adding the sample snippet with `wp_set_script_translations()` to a theme/plugin, the AMP validation error was properly attributed (no longer to Core).

| Theme causing an error | Plugin causing an error |
| --- | --- |
| ![Screenshot 2021-11-29 at 23 57 40](https://user-images.githubusercontent.com/478735/143956316-31198315-4e6e-4462-8dd5-d6b0d6c1a110.png) | ![Screenshot 2021-11-29 at 23 59 30](https://user-images.githubusercontent.com/478735/143956328-faa929ca-0298-46d6-9fdc-782c1fe1962e.png) |

_Tested on AMP Version 2.2.0-alpha-20211123T020732Z-5405daa_
