### ISSUE TITLE
Store revision history for validation error statuses

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4752]
## Feature description

When someone changes the status of a validation error, such as to keep some invalid markup, there is currently no history of this change being made. Therefore, some author who has access to developer tools could decide to keep some invalid markup that actually occurs on every page (see #4751), and the result would be turning off AMP for the entire site. (See #2673 for restricting access to dev tools by user role.) There should be revision history for changes to the validation error statuses so that there is an audit trail of such changes being made to the site.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* The user ID that changed the status of the error as well as the datetime at which the change was made could be stored in `term_meta` for the `amp_validation_error` taxonomy term. Alternatively, the revision history could be stored as post revisions of the `amp_validated_url`, but this this wouldn't be as useful to see who changed the status of an error that occurs across multiple URLs.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Copied from Slack:
> AS: For the auditing trail, a quick solution might be to hook into an existing solution like Stream if available.
> WR: Yes, that's true. However the person who made a change should also be shown in AMP's own screens, not just in Stream's logs.
> AS: Not everyone will need audit trails, though, and they can have nefarious impacts on site health.
> If you request site owners that need audit trails to install Stream, it makes everything easier and less risky for us.
> And maybe we could even read from the Stream database to surface this information...?
> If you need audit trails, you don't need them only for AMP, and having AMP-only audit trails in one place while the rest is somewhere else doesn't make much sense, I think.

**Comment by westonruter** [comment]
I realized that we actually are already storing some data in `term_meta` right now: the timestamp on which the term is created.

https://github.com/ampproject/amp-wp/blob/68873f367ff92ffaf71d18ba64fc53acdbcf3efe/includes/validation/class-amp-validated-url-post-type.php#L759-L764

This is used to populate the “Last Seen” column in the Error Index screen. In reality, this data could be obtained by querying for the most recently-published `amp_validated_url` post that has the term. This could involve a lot of `JOIN` queries.

In any case, if we wanted to add `term_meta` for revisions, that would be simple to add here as well. It still stands whether or not this is needed information in the core.
