### ISSUE TITLE
Normalize script contents that contain nonces

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4753]
## Feature description

A common source of validation errors is a script that is enqueued along with a call to `wp_localize_script()` which contains a nonce. For example:

```php
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_script( 'foo', 'https://example.com/foo.js' );
	wp_localize_script( 'foo', '_foo', [
		'nonce' => wp_create_nonce( 'foo' ),
	] );
} );
```

This results in two validation errors:

![image](https://user-images.githubusercontent.com/134745/82514074-89d89d00-9ac9-11ea-8aa4-d080b685129a.png)

The validation error for the inline script, however, will continually keep appearing as new even after it has been reviewed repeatedly. This is because the `nonce` will change on a daily basis. For this reason, it may be a good idea to default to normalize the `text` value of such validation errors to normalize them, for example to replace the nonce string with `__NONCE__`:

```php
add_filter( 'amp_validation_error', function ( $error ) {
	if (
		isset( $error['code'], $error['node_name'], $error['text'] )
		&&
		'DISALLOWED_TAG' === $error['code']
		&&
		'script' === $error['node_name']
	) {
		$error['text'] = preg_replace( '/"[0-9a-f]{10}"/', '__HEXSTR10__', $error['text'] );
	}
	return $error;
} );
```

Note that we're already doing this for the `ver` URL parameters for enqueued scripts and styles:

https://github.com/ampproject/amp-wp/blob/9886b99469155b192e0a9c7769f84d8ea2f254b9/includes/sanitizers/class-amp-base-sanitizer.php#L600-L605

However, it is much easier to correctly normalize a `ver` parameter than to normalize a string that looks like a nonce. But the worst case is that we replace a non-nonce string with a placeholder, which isn't the end of the world.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We should also normalize numbers (e.g. timestamps and random numbers) as well as datetime strings.

**Comment by westonruter** [comment]
This issue was also caused by the Newspaper theme which outputs scripts containing strings like `'.td_live_css_uid_1_6018435401047'`. See support topic: https://wordpress.org/support/topic/clean-amp-validation-errors/

This string comes from [this code](https://github.com/madun92/helloworld/blob/a8c47d2e99721ab86841408a20580cf65f1893ee/wp-content/plugins/td-composer/plugins/css-live/includes/td_live_css_util.php#L11-L14):

```php
    static function td_generate_unique_id() {
        self::$td_unique_counter++;
        return 'td_uid_' . self::$td_unique_counter . '_' . uniqid();
    }
```

and used in [this code](https://github.com/JoeWrightNC/jwtestdomain/blob/b687b5073fe87e55a4aaae4cd99b6b202d4658b9/wp-content/plugins/td-composer/css-live/css-live.php#L323-L332):

```php
var editor_textarea = jQuery('.<?php echo $new_editor_uid ?>');
```

So if we were to normalize any single-quoted strings by replacing them with something like `__SINGLE_QUOTED_STRING__`, then these brand new errors be created every time a URL is revalidated.

**Comment by pierlon** [comment]
(QA confirmation was done [in the linked PR](https://github.com/ampproject/amp-wp/pull/5836#issuecomment-793218126))
