### ISSUE TITLE
Embedding VideoPress video causes validation error

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4754]
## Bug Description

When embedding a VideoPress video such as https://videopress.com/v/kUJmAcSf in a VideoPress block, the result is a validation error:

![image](https://user-images.githubusercontent.com/134745/82612486-d5e21b00-9b77-11ea-9cdb-2b8bfaa1cd2b.png)

The fix for this was partially implemented in #3542 because WordPress.tv also uses VideoPress architecture. So it just needs to be extended.

## Expected Behaviour

No validation error should be raised when embedding videos from VideoPress.

## Steps to reproduce

1. Enable Standard mode.
2. Embed a VideoPress block with the URL https://videopress.com/v/kUJmAcSf
3. Save draft
4. See validation error

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed:**

There are no validation errors for VideoPress embeds.
