### ISSUE TITLE
Allow single-line docblocks for typehints in PHPCS

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4756]
## Feature description
Right now, when we need to add a type-hinting docblock to the code for the IDE or one of the code quality tools to better interpret our code, PHPCS forces us to use multi-line docblocks with a description:
```php
/**
 * Element.
 *
 * @var DOMElement $element
 */
```

This usually produces a lot of noise that is unnecessary.

PHPCS should be configured to allow for single-line docblocks that we can use for type-hinting:
```php
/** @var DOMElement $element */
```

These could then even be used inline (TBD if wanted):
```php
foreach ( $elements as /** @var DOMElement $element */ $element ) {}
```

Originally discussed in https://github.com/ampproject/amp-wp/pull/4738#issuecomment-630794359.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* PHPCS does not enforce the need for description on type-hinting docblocks.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This issue is also discussed at https://github.com/WordPress/WordPress-Coding-Standards/issues/403.

**Comment by westonruter** [comment]
This was done in 7a2902118e0443fe6452d4137a3935370e003975 as part of #4877.
