### ISSUE TITLE
Can't pass validation

### ISSUE THREAD

**Issue by JayHoltslander** [Automattic/amp-wp#476]
Almost identical to the [earlier issue](https://github.com/Automattic/amp-wp/issues/467) I was having but with a different website...

For this site I upgraded to a paid CloudFlare account in order to gain the [page rules required](https://github.com/Automattic/amp-wp/issues/467#issuecomment-246499478) to totally shut off CloudFlare's features for any amp pages.

![](http://cdn.skunkworks.ca.s3.amazonaws.com/temp-screenshots/page-rule.jpg)

CloudFlare confirmed via support ticket these settings were correct. Still unable to pass validation.

**Errors**
1. The attribute 'src' in tag 'amp-analytics extension .js script' is set to the invalid value '//cdn.ampproject.org/v0/amp-analytics-0.1.js'.
2. The tag 'script' is disallowed except in specific forms.
3. The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.
4. The tag 'amp-analytics extension .js script' is missing or incorrect, but required by 'amp-analytics'.

**Live validator result:** https://validator.ampproject.org/#url=https%3A%2F%2Fwww.skunkworks.ca%2Fclient-news-august-2016-edition%2Famp%2F

I asked CloudFlare in a support ticket if there's some kind of conflict between their Wordpress plugin (pictured) and the "ignore" page rule defined in their web dashboard. I experimented with turning this option off and it completely breaks the website in question.

![](http://cdn.skunkworks.ca.s3.amazonaws.com/temp-screenshots/Screen_Shot_2016-09-15_at_10.18.26_AM.jpg)

CloudFlare's response was:

> Looking at our own internal bug reports, it looks like we encountered this issue with rewriting previously, and now disable our rewrite if `<html amp>` is present, which is the case in that page's source, so it should be okay to leave our rewriter enabled.

Any insight from the Automattic folks?

**Comment by mjangda** [comment]
I'm not sure what the question is? Can you please clarify?

**Comment by amedina** [comment]
Closing for now as no follow up.
