### ISSUE TITLE
Create a plugin to allow for easy switching of plugin builds

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#4767]
Once plugin builds for branches and PRs are possible (see #4766), we should take advantage of this novelty by creating a separate plugin to allow for easy switching between versions of the plugin. This would enhance the QA process, for example, as one would no longer have to setup a developer environment to build the plugin.

**Comment by westonruter** [comment]
Wiki page has been updated with section about the QA Tester plugin: https://github.com/ampproject/amp-wp/wiki/Development-Builds
