### ISSUE TITLE
AMP version of posts not visible in the Customizer

### ISSUE THREAD

**Issue by ataylorme** [Automattic/amp-wp#477]
# Description

The Customizer seems to create a new iframe for the AMP version of the post when navigated to but the old frame containing the standard version of the post persists.
# Steps to reproduce
1. Start with a fresh install of WordPress `4.6.1`
2. Install and activate the [amp-wp] plugin
3. Add a link to the _Hello World_ post pointing to the AMP version of the post
4. Open the Customizer
5. Click the link to the AMP version of the _Hello World_ post
# Screen capture

This screen capture shows:
1. The AMP link added to the _Hello World_ post in the WordPress admin
2. The _Hello World_ post in the WordPress Customizer
3. The AMP version of the _Hello World_ post outside of the Customizer, for reference
4. Navigating to the AMP version of the _Hello World_ post inside the Customizer
5. The duplicate iframe in Chrome dev tools
6. Removal of the duplicate iframe

![customizer-amp-posts-fail](https://cloud.githubusercontent.com/assets/2133004/18592757/0c871770-7bfe-11e6-8a27-b497296259a3.gif)

**Comment by westonruter** [comment]
I _am_ seeing the Ajax request to fetch the amp version of the post coming through:

<img width="1369" alt="customize__andrew-amp-customizer_ _just_another_wordpress_site_and_slack" src="https://cloud.githubusercontent.com/assets/134745/18597443/f0e91dec-7c02-11e6-95ee-6ae5952bd06d.png">

Looking at the elements panel I can see that there are two copies of the iframe unexpectedly:

<img width="703" alt="customize__andrew-amp-customizer_ _just_another_wordpress_site" src="https://cloud.githubusercontent.com/assets/134745/18597598/8c58b774-7c03-11e6-93dd-850fdc914651.png">

If I delete the first (old) one then I can see the AMP version appearing as expected:

<img width="1279" alt="customize__andrew-amp-customizer_ _just_another_wordpress_site_and_xwp_wp-customize-nav-menu-item-custom-fields" src="https://cloud.githubusercontent.com/assets/134745/18597652/c8961ce0-7c03-11e6-95eb-f0591c0a971e.png">

So the reason for this is that `customize-preview.js` isn't getting included in the AMP version of iframe and so the Customizer doesn't know when to tear down the old iframe and recognize the new iframe as being fully loaded. So the fix should be simply to make sure that you do something like the following in the AMP footer:

```php
if ( is_customize_preview() ) {
    global $wp_customize;
    $wp_customize->customize_preview_settings();
    wp_print_scripts( array( 'customize-preview' ) );
}
```

**Comment by westonruter** [comment]
This can be closed per https://github.com/Automattic/amp-wp/pull/479#issuecomment-315458381
