### ISSUE TITLE
Gallery shortcodes unexpectedly show as carousels by default in Transitional/Standard mode

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4774]
## Bug Description

When a site has galleries in Classic blocks, these are always getting displayed as carousels unless the author goes into the code editor and adds `amp-carousel=false` to the `[gallery]` shortcodes. This was done back at a time before the block editor existed and at a time in which the gallery block styles couldn't be rendered in Reader mode safely. Both of these are no longer the case, however. As of #4204 via #4299, core block styles are now enqueued in the classic post templates. 

For sites in Standard/Transitional mode, the Shortcode block was augmented to inject `amp-carousel=false` into the block behind the scenes, while also exposing a new carousel toggle in the block settings. (This was not being done for shortcodes in Classic blocks however.) In hindsight, this seems irrelevant because when a Classic block is converted to blocks, the `gallery` shortcodes are not converted into Shortcode blocks but rather Gallery blocks. Therefore, all that logic to extend the Shortcode block in the block editor should just be removed. 

👉  The `gallery` shortcode should _not_ display as a carousel in Standard/Transitional mode unless explicitly requested via the `amp-carousel=true` shortcode attribute.

Also, it may make sense for the Gallery block to keep the carousel enabled by default when in Reader mode. Nevertheless, when the `[gallery]` shortcode does have `amp-carousel=false`, we should make sure that the required gallery styles are enqueued in classic Reader mode (or else create such basic styles).

Reported in [support forum topic](https://wordpress.org/support/topic/no-gallery-column-but-carousel/).

## Steps to reproduce

1. Create a Classic block.
2. Add a gallery. 
3. View the post in non-AMP, and see it is displayed as a grid.
4. View the post in AMP Reader mode: see a carousel.
4. View the post in AMP Transitional mode: also see a carousel (but this is not expected).

### Editor

> ![image](https://user-images.githubusercontent.com/134745/82948331-7066a380-9f56-11ea-902e-23aef2434e6c.png)

### Non-AMP ✅ 

> ![image](https://user-images.githubusercontent.com/134745/82948485-b7549900-9f56-11ea-91c4-4f9969b78533.png)

### AMP Reader Mode ✅ 

> ![image](https://user-images.githubusercontent.com/134745/82948401-90966280-9f56-11ea-8bcf-da27ad90d103.png)

### AMP Transitional mode ❌ 

> ![image](https://user-images.githubusercontent.com/134745/82948433-9f7d1500-9f56-11ea-9b66-dfe91d817675.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Here's a workaround plugin to prevent `gallery` shortcodes from rendering as carousels by default: https://gist.github.com/westonruter/98e2e6559389840111b430ab4db2075d

**Comment by johnwatkins0** [comment]
Confirming this is fixed and passes QA. 

1. Created a gallery in a Classic block
2. It showed as a grid in all non-AMP or Standard versions of the post
3. It showed as a carousel in the legacy theme in Reader mode
