### ISSUE TITLE
Garbage-collect validated URL posts which have all validation errors reviewed, and remove empty validation error terms

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4779]
## Feature description

When a URL is validated, an `amp_validated_url` post type instance is created to capture the results of validating the page for AMP validation issues. Other data is stored in postmeta as well, including the queried object, the stylesheets, and details for any validation error that occured. At present, these validated URLs remain in perpetuity until a user manually selects validated URLs to “forget” (that is, delete). And with #1756 the validated URLs will be created in the background on an ongoing basis. This isn't great because as was [reported on the support forum](https://wordpress.org/support/topic/big-increase-in-postmeta-size/), these posts and their postmeta actually consume a lot of storage. What's more is that the validated URLs actually serve no real purpose once all of the validation errors on them have been reviewed (or if they have no validation errors in the first place). 

Therefore, we should introduce a WP Cron task which goes through on a daily basis to forget (delete) all `amp_validated_url` posts which are older than 1 week and which also have no unreviewed validation errors. Whenever a URL is validated (or re-validated) its `post_date` is set to the current datetime, so this process will only delete URLs that haven't been touched in a week. 

This means of garbage collection is similar to how `auto-draft` posts are deleted after a week. See [`wp_delete_auto_drafts()`](https://developer.wordpress.org/reference/functions/wp_delete_auto_drafts/). The difference for our purposes here is that we will skip any posts that have unreviewed validation errors. Note that this can be done by simply joining the `wp_posts` table with the `amp_validation_error` taxonomy terms which have the `term_group` set to `0` (unreviewed kept) or `1` (unreviewed removed).

~Additionally, during the same process we also need to delete `amp_validation_error` terms in the _reviewed_ state (reviewed removed and reviewed kept) that have zero URLs associated with them.~

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Note a related issue for garbage-collecting `amp_validation_error` taxonomy terms that don't have any associated `amp_validated_url` posts (i.e. the terms which are empty). This was originally suggested in #1415 but I decided against it because it can mask something important about the validation errors being reported, namely ones which have variable script content in them (e.g. nonces, per #4753). Therefore, it is important for site owners to manually clear out on their own. See https://github.com/ampproject/amp-wp/issues/1415#issuecomment-492878512.

**Comment by westonruter** [comment]
> Note a related issue for garbage-collecting `amp_validation_error` taxonomy terms that don't have any associated `amp_validated_url` posts (i.e. the terms which are empty). This was originally suggested in #1415 but I decided against it because it can mask something important about the validation errors being reported, namely ones which have variable script content in them (e.g. nonces, per #4753). Therefore, it is important for site owners to manually clear out on their own. See [#1415 (comment)](https://github.com/ampproject/amp-wp/issues/1415#issuecomment-492878512).

Actually, we _should_ do this for `amp_validation_error` terms that are in the **reviewed** state. This will address the concern I had about masking validation errors that occur only once, since such validation errors would almost always be in the new state.

**Comment by westonruter** [comment]
Actually, humm, this could still be problematic. Consider this scenario:

1. I validate a URL.
2. I evaluate the validation validation errors and decide to leave all as _removed_. I mark all as _reviewed_.
3. After a week, the validated URL is post gets garbage-collected since all of its validation errors have been reviewed.

If at this point, the reviewed validation errors are _also_ deleted, then this will have a negative effect: the next time the URL is validated, new validation errors will be created which appear as unreviewed, even though the user had previously marked them as reviewed.

So we can't actually automatically delete validation errors after all, regardless of their status.

**Comment by amedina** [comment]
Makes sense.

Alternatively, we could consider having a separate screen for Validated URLs which have been "fully reviewed". The goal would be to declutter the information handling for the user, while still keep the validation errors would be kept until they become stale. 

Another (related) aspect we have discussed before (I think): could we automatically delete "Empty" validation errors (Clear Empty)?

**Comment by westonruter** [comment]
> Alternatively, we could consider having a separate screen for Validated URLs which have been "fully reviewed". The goal would be to declutter the information handling for the user, while still keep the validation errors would be kept until they become stale.

We could default to showing validated URLs with unreviewed errors:

![image](https://user-images.githubusercontent.com/134745/84430989-647a1300-abdf-11ea-923b-f5a8d94a9e79.png)

But still, the underlying need for the issue here is to reduce the database size. So we still should remove the reviewed validated URLs regardless.

> Another (related) aspect we have discussed before (I think): could we automatically delete "Empty" validation errors (Clear Empty)?

Yes, that's what we discussed in #1415 but I don't think we can do so because of the reason I closed the issue, and for the reason I outlined in https://github.com/ampproject/amp-wp/issues/4779#issuecomment-642386526: once a validated URL was forgotten after all its validation errors were reviewed, then the result would be validation errors which would now be empty. The next time a URL is validated, there would then be unreviewed validation errors all of a sudden. 

This would also happen if the user clicked Clear Empty after garbage-collection of reviewed Validated URLs, however. So that's something to consider further.

**Comment by westonruter** [comment]
Two users recently have reported issues with the `_amp_stylesheets` postmeta being particularly huge:

* https://wordpress.org/support/topic/huge-_amp_stylesheets-postmeta/
* https://wordpress.org/support/topic/database-increasing-fast-because-full-css-for-each-post/

As a first step to mitigate this, as opposed to auto-deleting the `amp_validated_url` posts after a week, what we can do is just purge the `_amp_stylesheet` postmeta. When this is done, the stylesheets metabox can just say something like “re-validate to obtain latest stylesheet data” (it already does). In practice users will rarely see this because the “Validate” link in the admin bar already does this re-validation.

**Comment by westonruter** [comment]
Filed issue for stale stylesheet purging: https://github.com/ampproject/amp-wp/issues/5132

**Comment by westonruter** [comment]
We could consider deleting the validation errors automatically after a month perhaps, of no longer having associated validated URLs.

**Comment by westonruter** [comment]
> We could consider deleting the validation errors automatically after a month perhaps, of no longer having associated validated URLs.

Er, only if the validation errors are unreviewed and removed, or rather, in their default state. We don't want to delete validation errors that have been reviewed as then the next time the validation error crops up, the user would have to review it all over again. 

I'm not feeling confident that this issue is fully baked yet. I'm pulling from 2.1 for now.

**Comment by westonruter** [comment]
Let's revisit this with moving to custom DB tables in #5553. As pointed out by @schlessera, we may want to store the status independently of the error object itself. If this were done, the statuses could be retained even after the objects are garbage collected.

**Comment by westonruter** [comment]
I think we need to seriously consider this for 2.1 if we retain the `SavePostValidationEvent` introduced in #5515, since it will result in a validated URL post being created for every post being edited, regardless of whether a user has DevTools enabled.

Garbage collection will also alleviate the need for resetting all the validation data (#5826), including upon uninstallation (#3210).

**Comment by westonruter** [comment]
We may not even need to store the validation data for each URL based as part of the validation REST API revamp (#5552) and DevTools redesign (#2316). We can fetch the validation information from a URL on demand to display in the UI. The only thing we need to store are validation errors _when_ their status is changed from the default (e.g. marking something as reviewed or kept).

**Comment by westonruter** [comment]
A downside to not storing the validated URL is that we wouldn't be able to keep track of the validation errors that are no longer present on the site (i.e. empty), like we do now.

**Comment by westonruter** [comment]
We could store a list of URLs that an error occurs on with the error itself. But that's still not great because when validating a URL, we'd still have to do a query for all validation errors associated with that URL in order to be able to remove the URL from being associated with the errors if they are no longer occurring. So yeah, we need to maintain our current overall scheme for storing validated URLs, the validation errors that occur on them, and the ability to query both URLs by error and errors by URL.

**Comment by westonruter** [comment]
OK, I think I got it. We should automatically garbage collect the validated URLs that have _never been touched_. This could mean:

1. Validated URLs on which all errors are unreviewed or which have no errors on them.
2. Validated URLs on which the status of their validation errors have not been directly mutated. (Errors have not been examined in the context of this URL.)

For 2, we'd need to store some flag to capture how many times a user has updated a Validated URL to change the status of its validation errors. Since users can only change the status of validation errors in the context of a validated URL, we can use this fact to keep tabs on which validated URLs have been touched by users. This also means that in the REST API validation endpoints that validation errors should not be directly modifiable. They should remain only mutable via the `/validated-urls/:url` endpoint.

**Comment by westonruter** [comment]
> For 2, we'd need to store some flag to capture how many times a user has updated a Validated URL to change the status of its validation errors. Since users can only change the status of validation errors in the context of a validated URL, we can use this fact to keep tabs on which validated URLs have been touched by users. This also means that in the REST API validation endpoints that validation errors should not be directly modifiable. They should remain only mutable via the `/validated-urls/:url` endpoint.

It's simpler than this. In #6763 I'm just checking if the current sanitized status is the same as what `AMP_Validation_Manager::is_sanitization_auto_accepted()` return. If so, the errors are safe to delete since they'd be re-generated with the same status.

**Comment by milindmore22** [comment]
**QA Passed**

Observed Cron event for garbage collection `amp_validation_data_gc` of validated URL running daily and Stylesheet running hourly `amp_validated_url_stylesheet_gc` 

```
 wp cron event list
+------------------------------------+---------------------+-----------------------+---------------+
| hook                               | next_run_gmt        | next_run_relative     | recurrence    |
+------------------------------------+---------------------+-----------------------+---------------+
| wp_privacy_delete_old_export_files | 2021-12-09 13:00:03 | now                   | 1 hour        |
| amp_validate_urls                  | 2021-12-09 13:00:04 | now                   | 1 hour        |
| amp_validated_url_stylesheet_gc    | 2021-12-09 13:04:44 | now                   | 1 hour        |
| amp_monitor_css_transient_caching  | 2021-12-09 14:04:44 | 46 minutes 24 seconds | 1 day         |
| wp_https_detection                 | 2021-12-09 14:49:43 | 1 hour 31 minutes     | 12 hours      |
| wpseo-reindex                      | 2021-12-09 16:33:55 | 3 hours 15 minutes    | 1 day         |
| wp_version_check                   | 2021-12-09 22:00:03 | 8 hours 41 minutes    | 12 hours      |
| wp_update_plugins                  | 2021-12-09 22:00:03 | 8 hours 41 minutes    | 12 hours      |
| wp_update_themes                   | 2021-12-09 22:00:03 | 8 hours 41 minutes    | 12 hours      |
| recovery_mode_clean_expired_keys   | 2021-12-10 10:00:03 | 20 hours 41 minutes   | 1 day         |
| wp_scheduled_delete                | 2021-12-10 10:00:22 | 20 hours 42 minutes   | 1 day         |
| delete_expired_transients          | 2021-12-10 10:00:22 | 20 hours 42 minutes   | 1 day         |
| wp_scheduled_auto_draft_delete     | 2021-12-10 10:00:25 | 20 hours 42 minutes   | 1 day         |
| amp_validation_data_gc             | 2021-12-10 10:19:42 | 21 hours 1 minute     | 1 day         |
| wp_site_health_scheduled_check     | 2021-12-14 10:00:03 | 4 days 20 hours       | 1 week        |
| wpseo_ryte_fetch                   | 2021-12-14 16:33:56 | 5 days 3 hours        | 1 week        |
| publish_future_post                | 2030-01-01 12:00:18 | 8 years               | Non-repeating |
+------------------------------------+---------------------+-----------------------+---------------+
```

Screenshot Before running garbage collection showing total of **89 URL's**

![image](https://user-images.githubusercontent.com/1132541/145404294-0972b046-263c-4e0e-aa87-ce2f2e215a62.png)

```
wp cron event run amp_validation_data_gc
Executed the cron event 'amp_validation_data_gc' in 1.02s.
Success: Executed a total of 1 cron event.
```
Screenshot Before running garbage collection showing total of**24 URL's** remains
![image](https://user-images.githubusercontent.com/1132541/145404554-4996581a-f618-43e6-95dd-f247a9d0b7ce.png)
