### ISSUE TITLE
Filtering Schema.org metadata to empty value results in empty JSON added to page

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4783]
## Bug Description

In a [support topic](https://wordpress.org/support/topic/remove-schema-markup/) a user needed to disable the Schema.org metadata from being added to the page. I was going to advise using this:

```php
add_filter( 'amp_schemaorg_metadata', '__return_empty_array' );
```

However, this results in this being added to the page:

```html
<script type="application/ld+json">[]</script>
```

So I had to instead do this which is much more verbose:

```php
add_filter( 'amp_optimizer_config', function( $config ) {
	$config['transformers'] = array_diff(
		$config['transformers'],
		[ 'AmpProject\AmpWP\Transformer\AmpSchemaOrgMetadata' ]
	);
	return $config;
} );
```

## Expected Behaviour

If the Schema.org metadata has been filtered to be an empty array or some other falsy value, then it should not output anything.

## Steps to reproduce

1. Add a plugin that does `add_filter( 'amp_schemaorg_metadata', '__return_empty_array' );`
2. See the empty JSON script being added to the page unexpectedly. 

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

I think this will do the trick:

```diff
diff --git a/src/Transformer/AmpSchemaOrgMetadata.php b/src/Transformer/AmpSchemaOrgMetadata.php
index 15a9557a5..1be1a7ed7 100644
--- a/src/Transformer/AmpSchemaOrgMetadata.php
+++ b/src/Transformer/AmpSchemaOrgMetadata.php
@@ -59,11 +59,15 @@ final class AmpSchemaOrgMetadata implements Transformer {
 			return;
 		}
 
+		$metadata = $this->configuration->get( AmpSchemaOrgMetadataConfiguration::METADATA );
+		if ( empty( $metadata ) ) {
+			return;
+		}
+
 		$script = $document->createElement( Tag::SCRIPT );
 		$script->setAttribute( Attribute::TYPE, Attribute::TYPE_LD_JSON );
 
-		$metadata = $this->configuration->get( AmpSchemaOrgMetadataConfiguration::METADATA );
-		$json     = wp_json_encode( $metadata, JSON_UNESCAPED_UNICODE );
+		$json = wp_json_encode( $metadata, JSON_UNESCAPED_UNICODE );
 		$script->appendChild( $document->createTextNode( $json ) );
 
 		$document->head->appendChild( $script );
diff --git a/src/Transformer/AmpSchemaOrgMetadataConfiguration.php b/src/Transformer/AmpSchemaOrgMetadataConfiguration.php
index aaf682bbf..53352d7a8 100644
--- a/src/Transformer/AmpSchemaOrgMetadataConfiguration.php
+++ b/src/Transformer/AmpSchemaOrgMetadataConfiguration.php
@@ -35,8 +35,9 @@ final class AmpSchemaOrgMetadataConfiguration extends BaseTransformerConfigurati
 	 * @return array Associative array of allowed keys and their respective default values.
 	 */
 	protected function getAllowedKeys() {
+		$metadata = amp_get_schemaorg_metadata();
 		return [
-			self::METADATA => (array) amp_get_schemaorg_metadata(),
+			self::METADATA => is_array( $metadata ) ? $metadata : [],
 		];
 	}
```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
QA passed.

The schema is properly produced when no filter is active.
![Image 2020-06-17 at 3 45 01 PM](https://user-images.githubusercontent.com/83631/84906069-bfb17700-b0b1-11ea-8337-9e29b567ebd3.png)

When a filter reduces the schema to an empty array, we don't get a useless schema entry, but rather no schema entry at all:
![Image 2020-06-17 at 3 46 08 PM](https://user-images.githubusercontent.com/83631/84906147-d5bf3780-b0b1-11ea-967b-15ef89a15188.png)
