### ISSUE TITLE
Description for AMP panel in Customizer is outdated

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#4784]
The description for the AMP panel in the Customizer is outdated and needs to be updated. Currently, it is:

https://github.com/ampproject/amp-wp/blob/b4d13f255e33d9935343067970fa6e1c2f01a902/includes/admin/class-amp-customizer.php#L97

And a screenshot of the description:

![image](https://user-images.githubusercontent.com/16200219/83445273-37d63680-a43c-11ea-8bd9-2dd9b4e82908.png)
---------------

## Changelog entry

*

**Comment by amedina** [comment]
@pierlon Please add a screenshot depicting the message to be update.

**Comment by pierlon** [comment]
@amedina I've added a screenshot to the original comment as requested.
