### ISSUE TITLE
Wizard Step: Theme compatibility scanning

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4795]
## Feature description

Alongside plugin compatibility scanning (#4719), scanning is also needed for the active theme. In particular, if the theme is not generating validation errors, then Standard or Transitional modes may be good choices. If the theme is generating validation errors, however, then Reader mode may be the best bet especially if the user does not have technical ability to fix the issues or evaluate whether the invalid markup can be removed.

There's one big caveat here for recommending Reader mode, and specifically a Reader theme. In particular, it may not be advisable if the active theme is violating a best practice of registering post types, taxonomies, post types, blocks, and widgets in _plugins_ rather than in theme. If the active theme is registering a post type, for example, and a Reader theme is selected, then this post type will be absent entirely.

What we need to do is get a list of all registered blocks, widgets, post types, and taxonomies when the active theme is running. Then we need need to do it again with the active theme switched to an empty one. If there is a difference, then the missing entities were registered in the theme and will not be available in the new Reader mode. In such a mode, only Classic theme would be recommended. And we will need to list out what will not be available if a Reader theme is selected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The user is guided to choose the best template mode based on their active theme/plugins.

## Implementation brief

1. Add a new Onboarding Wizard step for Site Scanning as well as an area on the Settings Screen to initiate a scan.
1. Obtain validation results for URLs representative of the site, using key WP templates (homepage, single post, search results, category archive, etc. as returned by `\AmpProject\AmpWP\Validation\ScannableURLProvider::get_urls()`). Important: The list of URLs to validate should be returned and then each URL should be scanned. This must be done instead of scanning all URLs with loopback requests in one request to avoid timeouts.
1. Gather list of theme-registered entities (post types, shortcodes, blocks, taxonomies, etc.) which are (erroneously) registered in the theme. See #5751.
1. Based on the above results, in the Onboarding Wizard and Settings Screen:
   1. If there are no validation errors reported at all (neither from the theme nor plugins), recommend Standard mode.
   2. If there are validation errors coming exclusively from plugins, recommend Transitional mode.
   3. If there are validation errors coming from the theme, recommend Reader mode. 
1. If there are theme-registered entities (step 2 above), inform them in the Reader theme selection that AMP Legacy is the only theme available. Otherwise, any Reader theme can be chosen.
1. Make sure template mode warnings are displayed on mobile. See https://github.com/ampproject/amp-wp/issues/4795#issuecomment-670817644.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
**From John:**

So we’ll need something that says “Here are the features of your site that will be missing in Reader mode.” Some of this could end up being opaque, e.g., if post types, taxonomies, or blocks are registered with nonexistent or untranslatable labels. We might have to keep the language vague (e.g., “Four registered post types will be missing in Reader mode.“). Also, blocks can be registered in JS only, so that part could be challenging.

Although I guess JS-only blocks would end up being rendered and saved in the database, so would likely still work. The dynamic blocks rendered in PHP, which would be lost, can be checked in the scanner. 

**From Weston:**

Correct. Only dynamic blocks would be a problem.

Well, other than the CSS that a theme may enqueue for JS-only blocks.

**Comment by jwold** [comment]
Is this an issue that needs copy to display what's happening to the user, or would this be a background task?

**Comment by westonruter** [comment]
The site compatibility scan involves checking URLs representative of the various templates and post types. So let's say that there are a dozen such URLs. There should be a progress bar that shows the status of checking each. The overall screen would say: “Checking Site Compatibility” with perhaps a description:

> Now checking various pages of your site to see if there are any AMP compatibility issues with your active theme and plugins. This will be used to provide you with a recommendation for how to use the AMP plugin with your site.

The site compatibility scan step of the wizard should have a progress bar that shows which template is currently being checked.

**Comment by johnwatkins0** [comment]
@westonruter I've begun thinking about this as part of #4706. For #4706 I'll just be building the UI and persisting the user selection, but the recommendation engine will come out of this and plugin scanning, along with what the user chooses for the technical question.

We should sketch out the algorithm for the degree to which we recommend each mode.

E.g., just thinking out loud -- this is probably nowhere near final:

### If the scan finds no issues

Standard is most recommended for all users. Other modes are not recommended.

### If the scan finds serious issues

#### Technical user
**Most recommended:** Standard
**Not recommended:** Transitional, reader

#### Nontechnical user
**Most recommended:** Reader
**Also good:** Transitional (if there are identifiable ways a nontechnical user can remediate the issues)
**Not recommended:** Standard

### If the scan finds few or nonserious issues

#### Technical user
**Most recommended:** Transitional
**Also good:** Standard
**Not recommended:** Reader

#### Nontechnical user
**Most recommended:** Transitional
**Also good:** Standard, reader

**Comment by westonruter** [comment]
Here's the logic that WP-CLI uses to prevent a theme from being loaded when `--skip-themes` is supplied:

https://github.com/wp-cli/wp-cli/blob/cb7a8af075edf8a83d3a273e03ceb5716f15eb34/php/WP_CLI/Runner.php#L1339-L1341

https://github.com/wp-cli/wp-cli/blob/cb7a8af075edf8a83d3a273e03ceb5716f15eb34/php/WP_CLI/Runner.php#L1633-L1677

**Comment by westonruter** [comment]
Note: In https://github.com/ampproject/amp-wp/pull/5192#issuecomment-670817538 I hid the template mode warnings on mobile. This should be revisited when theme scanning is implemented, figuring out a way to make warnings show on small viewports. cc @jwold @johnwatkins0

**Comment by westonruter** [comment]
@johnwatkins0 One key aspect of this issue that is distinct from #4719 is the need to scan the theme for this bit:

> There's one big caveat here for recommending Reader mode, and specifically a Reader theme. In particular, it may not be advisable if the active theme is violating a best practice of registering post types, taxonomies, post types, blocks, and widgets in _plugins_ rather than in theme. If the active theme is registering a post type, for example, and a Reader theme is selected, then this post type will be absent entirely.
> 
> What we need to do is get a list of all registered blocks, widgets, post types, and taxonomies when the active theme is running. Then we need need to do it again with the active theme switched to an empty one. If there is a difference, then the missing entities were registered in the theme and will not be available in the new Reader mode. In such a mode, only Classic theme would be recommended. And we will need to list out what will not be available if a Reader theme is selected.

There needs to be a REST API endpoint that lists out these entities (post types, shortcodes, blocks, etc), along with a parameter for whether the active theme should be short-circuited. When that same request is made without the active theme short-circuited, then if there is a difference in the registered entities, then we know that the theme is responsible for registering something and we need to warn that those entities will not be available when using a Reader theme. Users will need to move the entity registration logic into a custom plugin, which is a best practice anyway.

**Comment by johnwatkins0** [comment]
Thanks for calling that out @westonruter. Yes, I think that's the main sizable new piece of the site scan work, and I'll make that the focus of this issue.

**Comment by westonruter** [comment]
If post types are defined in a theme, we should consider automatically disabling AMP for those post types when a Reader theme is selected, if we don't altogether block them from selecting a Reader theme in the first place. See https://github.com/ampproject/amp-wp/issues/5249#issuecomment-677915998.

**Comment by westonruter** [comment]
New [support topic](https://wordpress.org/support/topic/shortcodes-are-not-being-executed-in-amp-pages/) that would have been prevented by theme scanning. The user found that their shortcodes weren't working on AMP pages. It was because they selected a Reader theme and the shortcodes were defined in the active theme.

**Comment by westonruter** [comment]
Here's another support topic that we should be accounted for: https://wordpress.org/support/topic/edit-amp-page-footer/#post-13919589

In particular, the active theme defines a function and an active plugin is trying to use that function. When a reader theme is activated, then a fatal error ensues because the function doesn't exist. 

This is another case that should prevent reader themes from being made available.

**Comment by jwold** [comment]
> This is another case that should prevent reader themes from being made available.

Want to make sure I'm tracking correctly. If we solve this would the theme compatibility scanner look through the reader themes available and only present ones that would work correctly with the installed plugins?

**Comment by westonruter** [comment]
Rather, only the AMP Legacy theme would be made available. It would be similar to the situation we have now where a site is (mis-)configured to customize the AMP slug too late. 

For example, with this plugin code:

```php
<?php
/**
 * Plugin Name: AMP Define Query Var Early with Constant
 */

add_action(
	'after_setup_theme',
	function () {
		add_filter(
			'amp_query_var',
			function() {
				return 'too-early-with-constant';
			}
		);
	},
	~PHP_INT_MAX
);
```

The Reader themes section in the Onboarding Wizard looks like this:

> ![image](https://user-images.githubusercontent.com/134745/105098015-4e2e1280-5a5e-11eb-924d-71b0b575d7bc.png)

Aside: I just found that that the carousel on the Settings screen fails to show the same:

> ![image](https://user-images.githubusercontent.com/134745/105098086-6b62e100-5a5e-11eb-82a8-80b4f8afb7a4.png)

It does, nevertheless, show a warning when there are themes unavailable due to not being uninstallable:

> ![image](https://user-images.githubusercontent.com/134745/105098224-9c431600-5a5e-11eb-86cb-0edf1ab9963c.png)

This is consistent with the Onboarding Wizard:

> ![image](https://user-images.githubusercontent.com/134745/105098312-bbda3e80-5a5e-11eb-91fa-e892fb40a780.png)

It seems the cause is that it was implemented when the Onboarding Wizard was available but before the Settings screen had been updated. See #4999. I'll open an issue for that.

**Update:** See #5789.

**Comment by westonruter** [comment]
There would be 4 conditions which would prevent a non-legacy Reader theme from being available to select:

1. Themes cannot be installed on the environment (either due to filesystem permissions or user capabilities).
2. ~The AMP query var was defined too late (after `plugins_loaded` action with priority 8, per #4999 and #5789.)~
3. A fatal error occurs when attempting to load an AMP page with a Reader theme selected (what we're discussing now).
4. The theme is registering custom post types, shortcodes, taxonomies, etc which would not be available when the Reader theme is loaded.

In all ~4~ 3 cases, the same yellow warning box should be displayed. 

Also, in the 3rd case we should try to detect the plugin that is causing the fatal error so that we can then mention to the user in the notice which plugin specifically is causing the fatal error. With that information in hand, we can advise that they have the option to suppress that plugin, which may allow them to then select the desired Reader theme.

We have the `LikelyCulpritDetector` service which can be used to analyze the error backtrace to determine the theme/plugin (which we use when `amp_is_available()` is called too early per #5289). We should be using this as well for the error screen shown when an exception happens during post-processing (#5320).

Communicating the error back to the Settings screen and/or Onboarding Wizard will be a bit tricky. We'll have to actually load the site with a Reader theme active (e.g. with some query var that forces a Reader theme to be loaded prior to updating the settings) and then pass back the error details. For the latter part, perhaps the error screen added in #5320 could be modified to return a JSON object when `wp_is_json_request()`.

**Comment by westonruter** [comment]
(Updated my comment to note the 4th case in which Reader themes would not be available.)

**Comment by jwold** [comment]
**Notes from a recent team call:**

At the end of the site scanning, we should have a message: "Please verify that everything is correct." 

Site Scanning could then report findings in a user friendly way, and essentially do the Site Review for the user (deprecating #6071 when complete), and have a message, "Some parts of your site may or may not be available, please verify."

So for 2.2 we'll launch the `Review` Section, and for 2.3 (or later) we'll hook into site scanning to help users with the review. This could be done async, so users get a notification later, when the site scanning site review is ready.

**Comment by delawski** [comment]
@westonruter Do you think we can close it via #6610 just like the Plugin compatibility scanning issue (#4719)?

**Comment by westonruter** [comment]
@delawski Almost. I think the outstanding piece here is to incorporate #6516. Namely, we need to determine if the theme is registering any custom post types, taxonomies, shortcodes, blocks, etc. This is captured in this point above:

> 3\. Gather list of theme-registered entities (post types, shortcodes, blocks, taxonomies, etc.) which are (erroneously) registered in the theme.

If so, we cannot rightly recommend recommend a Reader theme since doing so would cause the user to lose their custom functionality on AMP pages.
