### ISSUE TITLE
Unused Java Script Issue on Page Speed Tool

### ISSUE THREAD

**Issue by askmeoffers** [Automattic/amp-wp#4797]
Hi Team , 

Thanks  in advance for building and working on such a great AMP framework and helping us with easy to use wordpress plugin . 

Recently I noticed that all AMP java scripts are being flagged as unused for our oyo coupons stores and all other stores as well 

https://askmeoffers.com/coupon-deal-offer-promo-store/oyorooms-com/

on google page speed tool 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Faskmeoffers.com%2Fcoupon-deal-offer-promo-store%2Foyorooms-com%2F

Any insight into this ?

Thanks
Team - [askmeoffers.com]

**Comment by westonruter** [comment]
Hello, this would be a question for the AMP core project. Please file your issue upstream: https://github.com/ampproject/amphtml/issues

**Comment by askmeoffers** [comment]
Hi Weston ,

Thanks for pointing this out.

But that team never reply to any tickets

Thanks

**Comment by westonruter** [comment]
Something which should help with unused JS is this issue which will split the scripts into modern JS and then legacy JS that includes polyfills. See https://github.com/ampproject/amphtml/issues/28310.
