### ISSUE TITLE
Setup Wizard: Visual/style polish

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#4811]
## Feature description

I'm creating this issue to track overall CSS/style around the setup wizard UI. This will allow us to keep moving forward with functionality while visual design is in flux.

Current work for this issue:

- Bringing design more in line with amp.dev while keeping some continuity with the WP admin
- Visual improvements to the Reader theme selection screen

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
Relevant comment from @pierlon on #4800:

https://github.com/ampproject/amp-wp/pull/4800/files#r436900881

**Comment by pierlon** [comment]
Some other suggestions:

- Allow for the direct navigation to a a page by clicking on the title in the stepper

- Show a "disabled" state for the steps that have not been visited yet. For example:

    Before | After
    ---|---
    ![image](https://user-images.githubusercontent.com/16200219/84079909-ddece800-a9ca-11ea-971c-d6ff3fc7357a.png) | ![image](https://user-images.githubusercontent.com/16200219/84079869-c57ccd80-a9ca-11ea-8e31-4758a078e04d.png)

**Comment by johnwatkins0** [comment]
We'll need a way to handle long theme descriptions, some of which may be provided via filter and hence out of our control:

<img width="239" alt="Screen Shot 2020-06-10 at 9 17 52 AM" src="https://user-images.githubusercontent.com/9020968/84279247-5c48a780-aafb-11ea-863b-324158cde99a.png">

I'm thinking one of two options:

1. Use CSS to truncate the text with an ellipsis after a single line or multiple lines (the latter requires hackier CSS).
2. Hide/fade out text below, say, 50px, and provide a "Show more" button to expand

**Comment by jwold** [comment]
I kind of like on AMPWP how they truncate it, I'm ok with that personally: https://d.pr/i/D6e0wd

The `show more` may not be necessary because we have the learn more link already.

**Comment by johnwatkins0** [comment]
Got that working with a bit of JS:

<img width="994" alt="Screen Shot 2020-06-10 at 3 57 22 PM" src="https://user-images.githubusercontent.com/9020968/84317918-35a66300-ab33-11ea-930c-5b542429f7af.png">

Limiting the word count to 20.

**Comment by jwold** [comment]
Love it!

**Comment by amedina** [comment]
Very nice.

**Comment by johnwatkins0** [comment]
@jwold With the latest design updates, I could use your guidance on fonts. I see some Poppins and some Noto Sans. I see those are being used on amp.dev and can be easily included with Google Fonts, which would be great.

But I also a couple of variations of SF Pro, which isn't available via Google. Do you plan to include that one in the final designs, or can I assume one of the Google Fonts can be used in those cases?

I also see [Fira Mono](https://fonts.google.com/specimen/Fira+Mono#standard-styles) on amp.dev but haven't come across that in the designs yet, so not including it for now.

**Comment by johnwatkins0** [comment]
@jwold Will we be updating the active state background color for the stepper component?

<img width="427" alt="Screen Shot 2020-06-12 at 9 57 57 AM" src="https://user-images.githubusercontent.com/9020968/84516350-4ff75280-ac93-11ea-9b4e-c5d138d0dc96.png">

Not sure this blue is looking quite right.

**Comment by jwold** [comment]
Should I archive this one on the board?

**Comment by westonruter** [comment]
Archiving is done once the release is done. If it passes QA, then it gets moved to “QA Passed” on the board.

**Comment by westonruter** [comment]
Or if QA is not relevant, straight to Done.
