### ISSUE TITLE
Setup Wizard: Error messaging

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#4812]
## Feature description

When an unrecoverable error occurs somewhere in the setup wizard -- particularly if the device loses connectivity between the start and end of the process -- further advancement through the wizard should be prevented, and the user should see an error message informing them of the issue.

## Acceptance criteria

* User doesn't see cryptic error messages
* Error messages are as helpful as possible

## Implementation brief

* Will use an error boundary: https://reactjs.org/docs/error-boundaries.html
* Can likely be simple. Will look at what Gutenberg does.

## QA testing instructions

* Navigate to the setup wizard
* Switch to offline in the Browser
* Navigate to the last page of the setup wizard (where options are saved via a web request), changing at least one option along the way
* Verify that the error screen shows

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Should I archive this issue on the board?

**Comment by westonruter** [comment]
It needs QA still no? Once QA'ed then it would move right to the next column, eventually to Done.

**Comment by jwold** [comment]
I saw that you `closed` it. Maybe that was an accident?

**Comment by westonruter** [comment]
It was closed because the linked PR was merged. A closed issue is then moved to “Ready for QA”. It only gets reopened if it needs more work.

**Comment by amedina** [comment]
@johnwatkins0  The QA instructions do not apply to local testing.
