### ISSUE TITLE
Odnoklassniki

### ISSUE THREAD

**Issue by mmprep** [Automattic/amp-wp#4815]
Friends,

it seems that in order for you to somehow move to correct bugs I need to remind you of them repeatedly.

I have already contacted your technical support service: the button to share within Odnoklassniki does not work. 
Click and see for yourself. It is easy.

Thank you.

**Comment by westonruter** [comment]
The AMP plugin has no social sharing functionality. It integrates with other plugins that provide that functionality, like Jetpack. You'll need to reach out to the plugin (or theme) that adds that button to the page.
