### ISSUE TITLE
The AMP plugin doesn´t work with Domain Mapping?

### ISSUE THREAD

**Issue by gaizkot** [Automattic/amp-wp#482]
Hi,

I am using the AMP plugin with the Domain Mapping plugin and it seems that it doesn´t work. It shows a blank page or an 404.

I have it installed the AMP plugin in a web without DM and it works well.

Could you help me?

Thank you very much!

**Comment by mjangda** [comment]
No reason I can think of why it shouldn't work. Can you force refresh your rewrite rules (Settings > Peramlinks > Save) and see if that fixes things?

**Comment by gaizkot** [comment]
I did it again and nothing happened. I decided to uninstall the Domain Mapping and installing a different WP to the second domain.

Anyway, thanks for answering!

**Comment by chuckreynolds** [comment]
also if you have wp-cli: `wp rewrite flush`
ref: http://wp-cli.org/commands/rewrite/flush/

**Comment by amedina** [comment]
Closing as it seems a workaround solution found.
