### ISSUE TITLE
Spec tests need to be version-locked on 1.5 branch

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4824]
## Bug Description

We are currently always pulling the latest spec files from the [`ampproject/amp-toolbox`](https://github.com/ampproject/amp-toolbox project) to run the language-agnostic spec tests against our optimizer implementation.

This also happens in the separate 1.5 branch that we have open for bug fixes. However, while this causes the 1.5 branch to always run against the latest spec file tests, this branch does not get the latest updates to the Optimizer that would fix the code to make updated tests pass if behavior has changed upstream.

## Expected Behaviour

The 1.5 branch (and any future release branch that is split off of `develop`) should be version-locked into a specific set of spec files to test against that is known to work.

## Steps to reproduce

1. Check out commit https://github.com/ampproject/amp-wp/commit/6f0ed6fe2519309719d2ba85e5e44e34946689a0
2. Run `composer install` within `lib/optimizer` folder
3. Run `composer test` within `lib/optimizer` folder

## Screenshots

![Image 2020-06-09 at 6 25 13 AM](https://user-images.githubusercontent.com/83631/84105908-018b4f00-aa1a-11ea-9b98-bdb89ce9520d.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Fixed by #4825 and #4826.
