### ISSUE TITLE
REST endpoint for plugin options

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#4827]
As discussed over chat, this issue resulted in `amp-options` being `null` in the response for me.

Something to consider is adding a new AMP endpoint specific for its options, rather than re-using core's options endpoint. Then we'll have more flexibility possibly. Similar to how @pierlon created a new rest field for storing the `amp_enabled` state for a given post, rather than rely on the core-provided postmeta field.

_Originally posted by @westonruter in https://github.com/ampproject/amp-wp/pull/4800_

**Comment by schlessera** [comment]
**QA passed**

The REST API endpoint is discoverable:

![Image 2020-07-15 at 12 06 39 PM](https://user-images.githubusercontent.com/83631/87534616-8e1ed200-c696-11ea-9789-4b96419b918d.png)

It cannot be used by an unauthenticated user:

![Image 2020-07-15 at 12 17 44 PM](https://user-images.githubusercontent.com/83631/87534650-98d96700-c696-11ea-849a-4058d4353f6d.png)

It returns the correct information when called with an appropriate cookie:

![Image 2020-07-15 at 12 27 04 PM](https://user-images.githubusercontent.com/83631/87534674-a4c52900-c696-11ea-9422-93c4ec621fe8.png)

POST requests to store changes work as well:

![Image 2020-07-15 at 12 32 25 PM](https://user-images.githubusercontent.com/83631/87535183-5f552b80-c697-11ea-85bc-5590d9ec91b7.png)
