### ISSUE TITLE
Missing URL for attribute 'src' in tag 'amp-img'

### ISSUE THREAD

**Issue by trevorbroaddus** [Automattic/amp-wp#483]
There is an issue in the AMP_Img_Sanitizer::sanitize() method where it only checks the existence of a 'src' attribute and does not verify it contains a URL, causing a validation error.  A potential fix is replacing this if logic :
`if ( ! array_key_exists( 'src', $old_attributes ) ) {
	$node->parentNode->removeChild( $node );
	continue;
}`
within the for() loop to the following:
`if ( ! array_key_exists( 'src', $old_attributes )  || empty($old_attributes['src']) {
		$node->parentNode->removeChild( $node );
		continue;
}`

**Comment by mjangda** [comment]
Thanks! We can actually just simplify it to `empty( $old_attributes['src'] )` which covers both cases. Would you be interested in opening a PR?

**Comment by trevorbroaddus** [comment]
Sure can, I l will try and have it up today.

**Comment by trevorbroaddus** [comment]
Changing this solution to 
`$srcVal = (array_key_exists('src', $old_attributes)) ? trim($old_attributes['src']) : '';
            if (empty($srcVal)) {
                $node->parentNode->removeChild($node);
                continue;
            }`
The old fix causes issues on php versions prior to 5.5, due to the fact the 'empty()' (prior to 5.5) could only take variables as a parameter.

**Comment by trevorbroaddus** [comment]
@mjangda Would you mind giving me permission on the repo so that I can set up a PR?
