### ISSUE TITLE
Switch from Renovate to Dependabot for dependency updates

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4831]
## Feature description

We've seen that Dependabot does better at updating PHP dependencies in the `composer.json`.

Also, now that we have a GitHub action which does ZIP builds for PRs, this is restricted to PRs not coming from forks, which is another benefit that Dependabot provides.

Therefore, we should decommission Renovate and switch instead to Dependabot.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
FYI: Renovate has now been disabled for `amp-wp`.

@schlessera It has also been disabled for `amp-toolbox-php`.

**Comment by kristoferbaxter** [comment]
Please let me know if you see any issues following disable.

**Comment by westonruter** [comment]
Only outstanding issue is needing to add `dependabot-preview` to the CLAassistant allowlist:

![claassistant](https://user-images.githubusercontent.com/134745/97909537-3e275200-1cfd-11eb-9c57-3307ca8bcc15.png)

**Comment by swissspidy** [comment]
^ Coincidentally just asked about this in the #wg-infra Slack channel.

**Comment by westonruter** [comment]
Thanks to @kristoferbaxter and @rsimha, dependabot is now in the allowlist for the CLA.

The check is passing: 

![image](https://user-images.githubusercontent.com/134745/98858696-e6cc6480-2415-11eb-9ca4-800f1f9e61c4.png)

https://github.com/ampproject/amp-wp/pulls/app%2Fdependabot-preview
