### ISSUE TITLE
Instruct users to flush page cache when changing template modes

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4843]
## Feature description

If the `WP_CACHE` constant is enabled or if a site is detected to have page caching (#4386), when the user switches the Template mode (or the Reader theme) they should be prompted to flush their page cache.

We should also consider firing an action like `amp_page_cache_flush_needed` when such a setting is changed. This would facilitate third party plugins integrating with the AMP plugin, or for there to be compatibility plugins that bridge the AMP plugin with a page caching plugin.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kenrodriguesdesign** [comment]
Hi @westonruter 

I have taken this issue up for UI and came up with the following design as a prompt to encourage the user to flush all cache. There will not be any CTA present here. It will just be a notification.

<img width="1135" alt="Screenshot 2021-07-23 at 6 39 49 PM" src="https://user-images.githubusercontent.com/61531990/126786399-d8de50da-f044-4ff6-a8ba-28a2b576b2f7.png">


I had another idea in mind in which a CTA is present after switching template modes, and I wanted to know advice/feedback on it.

After checking the plugins listed [here](https://amp-wp.org/documentation/getting-started/amp-site-setup/page-caching-with-amp-and-wordpress/#what-page-caching-plugins-should-i-use) , I noticed something all of these have in common; A “purge all cache/ flush all cache/ delete all cache” option. 

So my question is this:
As shown in the design below,
<img width="1022" alt="Screenshot 2021-07-21 at 5 02 47 PM" src="https://user-images.githubusercontent.com/61531990/126785529-4e832c93-ae86-4376-96c3-4b3a1002a111.png">

When the user clicks the “Save and flush cache” CTA, is it possible to trigger the “purge all” cache option, present in the plugin that the user has installed? Is this feasible? If not, then we will go ahead with a simple prompt message.

**Comment by westonruter** [comment]
It would be nice if we could programmatically flush the cache, but since there is no standardized page caching API (especially when page caching is done remotely via Varnish) the best we can do is provide the prompt to tell the user to seek out the cache purge option with their respective plugin/platform.

In terms of placement of the notification, would it make more sense to add to the "Saved" notification?

https://user-images.githubusercontent.com/134745/126820471-f061363b-c188-4d2e-9c56-2457b5fdaecf.mov

Otherwise, if the notice were a banner then it would cause layout shifting, right?

**Comment by kenrodriguesdesign** [comment]
Hey @westonruter, unfortunate that the CTA isn't possible, so we will continue working on it being just a promo for now.

I will take into consideration the placement of the prompt to be added into notification along with a couple more variations.

**Comment by kenrodriguesdesign** [comment]
Hey @westonruter, the team has confirmed this design 

<img width="1024" alt="#4843" src="https://user-images.githubusercontent.com/61531990/129898148-fd3caf92-8b3d-428c-bb09-b09407fd4e9b.png">

The "Learn More" link will lead to a section in [this page](https://amp-wp.org/documentation/getting-started/amp-site-setup/page-caching-with-amp-and-wordpress/) to inform the user why they need to flush their cache. 

Do let me know if you have any questions in regards to this.

**Comment by westonruter** [comment]
Yes, that looks good.

**Comment by kenrodriguesdesign** [comment]
Added a small tweak to the design, by introducing a dismiss option.
<img width="1024" alt="Screenshot 2021-08-26 at 10 37 43 PM" src="https://user-images.githubusercontent.com/61531990/131005889-8b121e13-23aa-41c1-ad3f-c672b688496c.png">

**Comment by dhaval-parekh** [comment]
Hey @kenrodriguesdesign 

I have updated the UI of the notice. However, didn't add dismiss button. since that will automatically remove once use make any other change or refresh the page.

**Comment by delawski** [comment]
**QA not passed**

Here's a video of the QA process:

https://user-images.githubusercontent.com/478735/142615825-648a1d71-8074-44ad-b316-82519f44ce45.mp4

Note that the user is asked to purge caches after switching a template mode even though a caching plugin has just been deactivated. It's because the page caching is currently detected only when visiting the Site Health page. I think the page caching detection should be also done when deactivating plugins (and probably when they get activated, too).

See: #6731

**Comment by delawski** [comment]
**QA Passed**

✅ The bug report #6731 has been closed. Since I found no other issues with this feature, this ticket can now safely land in the "QA Passed" lane.
