### ISSUE TITLE
Remove categories and tags from meta

### ISSUE THREAD

**Issue by jamminjames** [Automattic/amp-wp#486]
You give an example function of how to remove the Author from display on the post, in a section you titled: "Example: Remove Author from meta"

How can I use that to remove the categories and tags listed instead? I tried just replacing 'meta-author' with 'meta-tags' for example, but that doesn't work.

Thanks for any help.

**Comment by steioria** [comment]
Try to use:

```
function amp_remove_taxonomy_meta( $meta_parts ) {
    foreach ( array_keys( $meta_parts, 'meta-taxonomy', true ) as $key ) {
        unset( $meta_parts[ $key ] );
    }
    return $meta_parts;
}
add_filter( 'amp_post_article_footer_meta', 'amp_remove_taxonomy_meta' );
```

**Comment by shaneonabike** [comment]
This doesn't work because the template doesn't verify if the categories are empty and simply outputs them regardless
