### ISSUE TITLE
Revert converting decimal image sizes to integers for sizer SVG generation

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4863]
## Feature description

For the issue with decimal image sizes described at https://github.com/ampproject/amp-wp/issues/4493, we resorted to a workaround while the validator was being adapted, by truncating the image sizes to integer values for the SVG generation.

As https://github.com/ampproject/amphtml/issues/27528 has been fixed upstream, we should revert this work-around.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Decimal sizes are used as-is for sizer generation.

## Implementation brief

* Remove code & tests introduced by https://github.com/ampproject/amp-wp/issues/4493

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
Moving this to QA Passed now, as I was able to add an AMP image with a decimal dimension locally, and no validation errors appeared.

<img width="826" alt="Screen Shot 2020-06-16 at 4 55 15 PM" src="https://user-images.githubusercontent.com/9020968/84832126-4d2d9200-aff2-11ea-9dd7-645497c159af.png">

<img width="769" alt="Screen Shot 2020-06-16 at 4 55 35 PM" src="https://user-images.githubusercontent.com/9020968/84832135-50c11900-aff2-11ea-972b-c6859daeb55b.png">
