### ISSUE TITLE
Replace deprecated PHPStan autoload_files option

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4865]
## Bug Description

PHPStan has deprecated the `autoload_files` option and is now throwing a warning. This is because it can now parse PHP code without executing it.

To get rid of this warning, we need to removethe `autoload_files` option in the plugin and both libraries, and if the scan then fails, replace it as needed with the corresponding alternatives:

```
1) scanFiles - PHPStan will scan those for classes and functions
   definitions. PHPStan will not execute those files.
2) bootstrapFiles - PHPStan will execute these files to prepare
   the PHP runtime environment for the analysis.
```

## Expected Behaviour

PHPStan analysis runs without warnings.

## Steps to reproduce

1. **Verify**: PHPStan is installed at version 0.12.26+.
2. Run `composer analyze`.
3. **Verify**: PHPStan throws a warning: `⚠️  You're using a deprecated config option autoload_files. ⚠️️`

## Screenshots

![Image 2020-06-16 at 7 08 12 AM](https://user-images.githubusercontent.com/83631/84734025-28103380-afa0-11ea-9881-dadb8f376725.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Reopening, as this is still needed for the main plugin analysis.

**Comment by westonruter** [comment]
This was done in #6673 via c6fabaadfbfca16e8b4cfe9d52aacbfc6bf635fd.
