### ISSUE TITLE
Setup wizard: Final copy for all screens

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#4871]
## Feature description

Creating this issue to track the creation of copy for the setup wizard. Having this handled separately will allow us to avoid having design and engineering held up by wording concerns until the finished product is ready. At that time we can put in all the hard-coded text in one sitting.

## Acceptance criteria

* Clear, translatable, user-friendly text on all screens

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
Related: https://github.com/ampproject/amp-wp/issues/5046

**Comment by amedina** [comment]
- Center notice and icon.
- May use a smaller notice box proportional to the message to avoid excessive blank space

<img width="880" alt="Screen Shot 2020-07-14 at 5 43 18 PM" src="https://user-images.githubusercontent.com/506089/87490302-37fc5100-c5fa-11ea-9674-5250010a75ca.png">
