### ISSUE TITLE
Prevent GHA build workflow from being run on external PRs

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#4872]
## Feature description

We should prevent running the GHA build workflow on external PRs as they will not have receive the secret tokens necessary to carry out actions such as uploading built zips to GCS and commenting on PRs.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
**QA passed**
![Image 2020-07-15 at 12 41 57 PM](https://user-images.githubusercontent.com/83631/87535949-9415b280-c698-11ea-9bee-4903758b746f.png)
