### ISSUE TITLE
Specifying query parameters with default data using AMP autocomplete

### ISSUE THREAD

**Issue by kishanugc** [Automattic/amp-wp#4878]
### We can't bind SRC using AMP Autocomplete with a query parameter.
We have been created different endpoints for default results & search results.
We try to bind different JSON endpoints for default results & search results but it's not working in amp autocomplete with query parameters.
Right now, we print JSON endpoints for testing. Please check below URL & Screenshot for more detail.
URL : https://devlop.wpengine.com/ 

![image](https://user-images.githubusercontent.com/60003727/84905953-f8137e00-b0ce-11ea-91d4-6480204ca5df.png)

Please check below code Screenshot for more detail.

![image](https://user-images.githubusercontent.com/60003727/84906871-22197000-b0d0-11ea-8805-1a9692b968ab.png)

The below link is a content amp autocomplete code.
https://devlop.wpengine.com/code.txt

**Please help me as soon as possible.**

**Comment by westonruter** [comment]
Is this a problem with the WordPress plugin or an issue with AMP itself? Are you able to accomplish what you want when creating a static HTML page? If so, you should inquire via https://amp.dev/support/
