### ISSUE TITLE
Accelerated Mobile Pages (AMP) Validation Errors

### ISSUE THREAD

**Issue by romanolawpc** [Automattic/amp-wp#488]
Greetings.

Google emailed me over the weekend to report I had errors on one of my AMP pages created with the WordPress AMP plugin. It seems the errors are only on one page (which is odd, because I have several AMP pages created with the plugin). Maybe I'll get more errors later?

The page (technically a "post") is: [Forensic Felons: Criminals in the Oregon Crime Labs](https://romanolawpc.com/criminals-in-the-oregon-crime-labs/amp/)

The errors are:
- AMP markup missing or incorrect
- Prohibited HTML Tag with AMP equivalent
- Prohibited or invalid use of HTML Tag
- Info: Missing structured data element
- User-authored JavaScript found on page
- Invalid CSS stylesheet
- Syntax error

Given that the plugin has so few customization options, I'm not sure how-- or if-- I can fix these errors. Any ideas?

**Comment by adelporte** [comment]
Hey Roman,
Using the offical AMP Validator, your post seems to meet the requirements:
[Your page](https://validator.ampproject.org/#url=https%3A%2F%2Fromanolawpc.com%2Fcriminals-in-the-oregon-crime-labs%2Famp%2F&filter=DISALLOWED_HTML.)

Best regards,

Augustin

**Comment by amedina** [comment]
Page is validating.
