### ISSUE TITLE
Onboarding wizard: Scrolling mobile images on reader themes screen

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4881]
## Feature description

<img width="1086" alt="Screen Shot 2020-06-18 at 07 59 23" src="https://user-images.githubusercontent.com/3411173/85036993-a6540d80-b139-11ea-8ebd-ffed78f81cf8.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
@jwold I believe this is a duplicate of #4822. Should we close one?

**Comment by jwold** [comment]
Good catch. Thanks!
