### ISSUE TITLE
Disable DI filtering by default

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4898]
> * The dependency injector is currently filterable. This will allow a site owner, for example, to replace a caching mechanism with another or decorate a piece of code to adapt its output. We should discuss whether we want to keep this filterable, or whether we want to keep the code closed by default and only open up parts individually.

**@westonruter:** In a subsequent PR, yes, I would say we should keep it closed for now. This will reduce the maintenance burden for backwards-compatibility until we are more comfortable allowing site owners to hook into plugin internals.

(_Originally posted in https://github.com/ampproject/amp-wp/pull/4877#issuecomment-645553721_)

**Comment by amedina** [comment]
Agree. Keeping it filterable could be, in principle, a maintenance problem. Let's discuss.
