### ISSUE TITLE
Three Plugin Conflicts I Noticed

### ISSUE THREAD

**Issue by andyforsberg** [Automattic/amp-wp#49]
I noticed that this plugin causes both the Floating Social Bar and the Sexy Author Bio plugin's CSS code to be rendered on the page as text. Also, there is a JavaScript conflict with the WP Tab Widget plugin. I had to disable the plugin in order to get the JavaScript code to not render on the page as text. My site is hosted on WP Engine, but it doesn't appear to be anything specific to their services (at least that I can tell). For now I'm just hiding the display of the CSS text using display: none in CSS, ironic and horrible so if anyone knows a better way to fix this please let me know. I can then update my Sexy Author Bio plugin accordingly.

**Comment by mjangda** [comment]
Thanks @andyforsberg! I think the CSS/JS rendering issue should be fixed now. Can you test again with the latest code on Github and let us know?
