### ISSUE TITLE
Massive spike in AMP errors in Google Search Console

### ISSUE THREAD

**Issue by Stockypotty** [Automattic/amp-wp#490]
Hi there,

We suddenly got a load of errors in GSC for our AMP links: http://puu.sh/rpDAu/e255b56275.png

An example URL being: http://thesetpieces.com/features/the-match-you-missed-sporting-gijon-0-0-real-madrid/amp/

It's a Wordpress site, with this AMP plugin installed along with pagefrog: http://puu.sh/rpDFm/0b6f2c816b.png

I noticed a fair few people in the Wordpress reviews in the last month saying it's not working. Just wanted to see if there was any issue that might have caused the AMP pages not to work via this plugin?

Thanks

**Comment by Stockypotty** [comment]
Hi again,

Tried to look into it. One potential issue could be due to W3 total cache plugin not being able to write to .htaccess file:http://puu.sh/rqB6h/1950e03763.png

Which some people have said that when the server tries to request a cache version of the /amp page, it doesn't exist.

Sound like this could potentially be the issue?

Thanks

**Comment by amedina** [comment]
Closing as not related to a plugin issue.
