### ISSUE TITLE
Validator uses Service container when it is not yet populated

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4906]
## Bug Description

Hook timings can throw a fatal error in the validation manager when the hook wrapping callback is triggered while the service container hasn't been populated yet.

## Expected Behaviour

The service container should always be populated as soon as the "sourcing" is active.

## Steps to reproduce

1. Install and activate 'wpforms-lite'.
2. Refresh the validation of a page.
3. **Verify:** The validation throws an error.
4. Look into the log file.
5. **Verify:** Validation failed because of an `InvalidService` exception while looking for `plugin_registry` service.

## Screenshots

Example with `wpforms-lite` installed:
![Image 2020-06-23 at 6 30 17 PM](https://user-images.githubusercontent.com/83631/85430767-db6cbf80-b580-11ea-9b10-ea0b59bd61e2.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Installing a plugin with very early hooks should not break validation.

## Implementation brief

* Remove the container's `REGISTRATION_ACTION` and register the services as soon as it is loaded, as that is also when the "sourcing" becomes active.

## QA testing instructions

1. Install and activate 'wpforms-lite'.
2. Refresh the validation of a page.
3. **Verify:** The validation succeeds.

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
QA Passed

Re-checking a validated URL succeeds and no error appears in the error log.
