### ISSUE TITLE
Validate filtered services in service container

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4914]
## Bug Description

If filtering of services for the service container is enabled, we currently don't validate the result.

In a current case with PHPStan, this leads to a PHP warning. The reason for the warning is that PHPStan executes the code (to be changed), which triggers the filter. As `global $wp_filter` is `null` though, the result of `apply_filters()` is also `null`.

## Expected Behaviour

PHP notices should not be thrown, even under misuse.

## Steps to reproduce

1. Run `composer analyze`
2. **Verify:** PHPStan triggers a PHP warning: `Invalid argument supplied for foreach() in /amp/src/Infrastructure/ServiceBasedPlugin.php on line 176`

## Screenshots

![Image 2020-06-24 at 9 57 49 AM](https://user-images.githubusercontent.com/83631/85519028-2cbc9380-b601-11ea-878a-cd32a4005dce.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Verified in QA:

PHPStan does not trigger a warning when `composer analyze` is run:

![image](https://user-images.githubusercontent.com/16200219/87565118-c03d2d80-c6b0-11ea-837e-b7750ec1afce.png)
