### ISSUE TITLE
Dashicon used to denote valid AMP is not available on WP < 5.1

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#4940]
## Bug Description

Regression introduced in #4382.

The Dashicon used to denote valid AMP for a page (`yes-alt`) is not available in WordPress 5.1 and below. Because of this, a "square box" is shown:

![image](https://user-images.githubusercontent.com/16200219/85627145-9a96a880-b65d-11ea-90b6-b70f786dbd7f.png)

The Dashicon `yes` is available in WordPress 5.1, however, and could be a used as a possible alternative:

![image](https://user-images.githubusercontent.com/16200219/85627323-df224400-b65d-11ea-8a2e-1175f566fc9b.png)

## Steps to reproduce

1. Install and activate AMP v1.6-alpha on WP 5.1
2. Go to a valid AMP page
3. See that the valid icon is not rendered as expected

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Do you have a recommended alternative? What about the non-alt version?

**Comment by pierlon** [comment]
We could use the Dashicon `yes` as an alternative, or provide a polyfill for `yes-alt` glyph by loading its [SVG](https://github.com/WordPress/dashicons/blob/master/sources/svg/yes-alt.svg) counterpart.

**Comment by westonruter** [comment]
QA Passed.

WP 5.0:

![image](https://user-images.githubusercontent.com/134745/87255029-0b9ad600-c43c-11ea-846b-f160ffa1c5e1.png)
![image](https://user-images.githubusercontent.com/134745/87255037-1d7c7900-c43c-11ea-9857-81081d6a9774.png)

WP 5.4:

![image](https://user-images.githubusercontent.com/134745/87255060-4f8ddb00-c43c-11ea-95fc-9ffbf67758d2.png)
![image](https://user-images.githubusercontent.com/134745/87255046-41d85580-c43c-11ea-8955-c03850db3ebd.png)
