### ISSUE TITLE
Error index does not identify kept errors in filter

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4941]
## Bug Description

If you have a validation error which is _unreviewed_ and _kept_, it will not be listed via the status filter:

![image](https://user-images.githubusercontent.com/134745/85638720-817d0000-b63b-11ea-91a1-b6b6ef745eab.png)

![image](https://user-images.githubusercontent.com/134745/85638757-9a85b100-b63b-11ea-9b94-7eab587d2e3b.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Note that it works as expected if the kept validation error is reviewed:

![image](https://user-images.githubusercontent.com/134745/85638846-dcaef280-b63b-11ea-90a1-f3789df1817a.png)

![image](https://user-images.githubusercontent.com/134745/85638859-e46e9700-b63b-11ea-901f-fe513610c250.png)

**Comment by schlessera** [comment]
**QA passed**

This works as expected:
![Image 2020-07-15 at 6 39 37 PM](https://user-images.githubusercontent.com/83631/87573127-ce00ac00-c6cc-11ea-856f-078a48f77533.png)
