### ISSUE TITLE
Implement register_theme_feature function

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/amp-wp#4952]
## Feature description

As for WordPress 5.5 and [[48171]](https://core.trac.wordpress.org/changeset/48171), there is a new function called `register_theme_feature`. This method defines expected values of  `theme_support` and weather or not to show theme supports value in the theme REST API. As this plugins uses `add_theme_support( 'amp', [ 'paired' => false ] )`, the AMP plugin should register it's theme_supports. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Explainer: https://make.wordpress.org/core/2020/07/15/register-theme-feature-api/
