### ISSUE TITLE
Plugin activation notice on plugins and AMP settings screens

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#4961]
## Feature description

When activating the plugin on the plugins screen, the user should be encouraged to set up the plugin immediately without having to go and look for where to start.

## Acceptance criteria

Screenshot:
 
<img width="1458" alt="Screen Shot 2020-06-23 at 9 12 34 AM" src="https://user-images.githubusercontent.com/3411173/85428179-b0a74a80-b531-11ea-816a-86ca5f06b675.png">

On plugin activation, the user will see the above notice on the plugins and settings screens. The notice will persist until the user closes it or the onboarding flow has been completed.

## Implementation brief

Will use the option created for the setup wizard to indicate whether onboarding has been completed. If the option is true, the notice won't show anymore. We'll also persist whether they have manually closed it via user meta (following how the plugin currently treats notices).

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
Test:
Upon activating the plugin on a new site, a notice should appear in the Plugins screen with a link to the onboarding.
Created a new site in Local by Flywheel, notice did not appear. 
Wizard notice in Settings screen shows `Reopen Wizard` button the first time is accessed.

**Comment by westonruter** [comment]
I deleted my `amp-options` and then activated the AMP plugin. I saw the notice as expected:

![image](https://user-images.githubusercontent.com/134745/87613383-06e75380-c6c2-11ea-9234-4e93f03f8e6e.png)

The settings screen also prompts me to open the wizard:

![image](https://user-images.githubusercontent.com/134745/87613426-29796c80-c6c2-11ea-8add-891fff734566.png)

**Comment by amedina** [comment]
QA passed.
