### ISSUE TITLE
Onboarding wizard UI polish for Version 1.6

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4962]
## Feature description

Throughout the onboarding wizard there are a few UI issues we should tackle, spit and polish sort of work. There are also a few more that we should discuss and decide how we would like to proceed. I'll list them out below. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**Welcome step:**
1. An icon is cut off slightly, should I supply a new SVG? https://d.pr/i/q22VFw

**Technical background step:**
1. Make previous gray lines blue: https://d.pr/i/oomIfm. Also applies to the remaining steps.
2. Add `previously selected` to the technical question as well.

**Template modes step:**

1. Make previous gray lines blue and previous steps blue checkmarks: https://d.pr/i/6MqjRK.
2. Previously selected: Shrink text and remove icon. https://d.pr/i/MovZlG
3. Can we make the left-padding on this info icon the same as the padding-top and padding-bottom? https://d.pr/i/Nle6jX

**Summary steps:**

1. Should we turn this on by default? https://d.pr/i/ZPQCx9. First time through wizard turn on by default. 
2. Update the padding-bottom to match the padding-top: https://d.pr/i/Tn12UX
3. Remove icon for `redirect mobile users`

**Saving settings step:**

1. Set a minimum for the “Saving settings” screen to appear.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
@amedina, @johnwatkins0, @westonruter a few of these might be worth discussing in our meeting.

**Comment by johnwatkins0** [comment]
@jwold Here's the simplified "Previously selected" on the technical question screen. It does make sense that we might want to do something more with this visually, but this works for now (text aside).

<img width="946" alt="Screen Shot 2020-06-30 at 1 27 09 PM" src="https://user-images.githubusercontent.com/9020968/86163214-8a575100-bad5-11ea-92f7-197f48533c1d.png">

**Comment by jwold** [comment]
Perfect. Agreed we’ll want to revisit later. But for now I think we ship it. 
GitHub <notifications@github.com> wrote:
“@jwold Here's the simplified "Previously selected" on the technical question screen. It does make sense that we might want to do something more with this visually, but this works for now (text aside).”


[Screen Shot 2020-06-30 at 1 27 09 PM]
“ —

**Comment by johnwatkins0** [comment]
Fixed by #4966
