### ISSUE TITLE
“Leave a Comment” link in Legacy Reader mode fails to take user to non-AMP version

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4968]
## Bug Description

Regression introduced in #4796.

When mobile redirection is enabled, clicking the “Leave a Comment” just causes the user to be redirected back to the AMP page:

> ![image](https://user-images.githubusercontent.com/134745/86176739-41ee6200-bada-11ea-8e80-4986ac5da4dc.png)

The “Leave a Comment” link in Legacy Reader mode needs the `noamp=mobile` query parameter added to it.

## Expected Behaviour

In legacy Reader mode, a comment link should always link to the non-AMP version.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* It's important that the `noamp=mobile` query parameter be injected via the `get_comments_link` filter when in legacy Reader mode. This will ensure that customized Reader mode templates will have the proper link added. The conditions to add the filter are: (1) mobile redirection is enabled, (2) `is_amp_endpoint()` is `true`, (3) the legacy Reader mode is enabled.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
This is passing QA.

1. Activated Reader mode with the legacy reader theme
2. Visited a single post
3. Clicked the "Leave a comment" link
4. Was sent to the comment form on the non-AMP version of the post.
5. Submitted a comment
