### ISSUE TITLE
plugin doesn't doesn't sanitize iframe in native WP custom field

### ISSUE THREAD

**Issue by sistercylon** [Automattic/amp-wp#497]
I have a post that has iframes that have been added in the main editor field of the post, as well as an iframe that has been added via native WP custom field. The plugin sanitizes the former iframes, but not the latter (from the custom field). Do I need to make my own sanitizer? If so, how to do I call it? I'm creating a custom amp template, btw.

**Comment by mjangda** [comment]
I'd suggest going with either a Custom Embed handler or a Sanitizer as described here: https://github.com/Automattic/amp-wp#handling-media
