### ISSUE TITLE
Add Server-Timing metrics to backend code

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4970]
## Feature description

To be able to measure, track and improve on backend AMP generation and optimization, we should add [`Server-Timing` HTTP header entries](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) that measure the processing time of each of the important subsystems.

These metrics can then be read via the [`PerformanceServerTiming` interface](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceServerTiming) from within our JS-based automated tests as well as from any statistical tracking that is done for field measurements.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Each AMP page generated via the AMP plugin provides the needed `Server-Timing` metrics via its HTTP header.

## Implementation brief

* The following `Server-Timing` entries should be collected when `WP_DEBUG` is off:
	* `Sanitization`
	* `Validation`
	* `Optimization`
* When `WP_DEBUG` is on, the following `Server-Timing` entries should be collected in addition to the above, to help pinpoint issues:
	* each individual Sanitizer
	* each individual Optimizer

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
There is already server-timing code in place, actually: `AMP_HTTP::send_server_timing()`, however, it is disabled by default.

I suggest:
- adapting the code so that only 1 single header is sent;
- enabling a limited amount of data by default for gathering field data;
- enabling all data ~by default when WP_DEBUG is true~ when `?amp_verbose_server_timing=1` is set.

**Comment by westonruter** [comment]
The reason why `Server-Timing` is disabled by default is captured in #2268.

**Comment by westonruter** [comment]
I think we should capture these entries:

1. Output buffering (before the AMP plugin is starts processing)
2. Style sanitizer
3. Tag and attribute sanitizer
4. Other sanitizers (including custom ones)
5. Optimizer

**Comment by pierlon** [comment]
**QA Passed**

- When logged in, the server timing metrics are sent:

Without `amp_verbose_server_timing` query var | With `amp_verbose_server_timing` query var
---|---
![image](https://user-images.githubusercontent.com/16200219/87714968-1f2ba100-c79c-11ea-85b2-d4489772623c.png) | ![image](https://user-images.githubusercontent.com/16200219/87715019-379bbb80-c79c-11ea-8962-52c944c962fc.png)

- When not logged in, the verbose server timing metrics are not sent even when the `amp_verbose_server_timing` query var is specified:

![image](https://user-images.githubusercontent.com/16200219/87715174-7467b280-c79c-11ea-8a23-1ca9aa36ed7a.png)
