### ISSUE TITLE
Wizard: Improve layout of Done screen

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#4972]
## Feature description

The layout of the final screen can be improved a bit by reducing the second border around the iframe and moving the heading over the iframe to instead be a caption:

Before | After
-------|-----
![image](https://user-images.githubusercontent.com/134745/86320317-76057800-bbeb-11ea-9d8c-318dc3bbadf6.png) | ![image](https://user-images.githubusercontent.com/134745/86320330-7f8ee000-bbeb-11ea-808f-56bf02844991.png)

Also, let's change “Visit in Customizer” to be just “Customize“.

The “Browse AMP Version” could be changed to just “Browse” as well.

It's likely that these buttons will not fit on the same line when translated.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Great suggestions. I like these changes.
