### ISSUE TITLE
amp-experiment not supported

### ISSUE THREAD

**Issue by alehl** [Automattic/amp-wp#498]
https://ampbyexample.com/components/amp-experiment/ - not supported by plugin

**Comment by mjangda** [comment]
Not sure I understand. You should be able to insert amp-expirment using one of the various filters/actions in the plugin. Can you please clarify?

**Comment by alehl** [comment]
Oh, amp-experiment was recently added by google so I assumed it was just not part of the plugin. I also assumed amp-experiment should've been handled by the plugin. I can edit myself.
