### ISSUE TITLE
Google ads AMP Analytics Issue 

### ISSUE THREAD

**Issue by askmeoffers** [Automattic/amp-wp#4981]
Hi , 

I want to add google Ads global Tracking code into my 100% AMP WordPress site : 

below is code I want to add in amp analytics but After i Add I see 404 error for ads.json file 

Please help me with this 

Code snippet for ads 

```
<amp-analytics type="gtag" data-credentials="include">
<script type="application/json">
{
  "vars" : {
    "gtag_id": "AW-71tt58888",
    "config" : {
      "AW-7153tttt75": { "groups": "default" }
    }
  }
}
</script>
</amp-analytics>
```

![image](https://user-images.githubusercontent.com/55142548/86486961-7da75700-bd7a-11ea-8925-418d45c35e10.png)

![image](https://user-images.githubusercontent.com/55142548/86487076-bfd09880-bd7a-11ea-991d-9675d46575a8.png)

Thanks
Team - https://askmeoffers.com/

**Comment by westonruter** [comment]
You provided a type of `ads` when you should provide the type as `gtag`. 

Also, the `data-credentials="include"` attribute is not added via this interface. 

It is preferable for you to add this `amp-analytics` markup via plugin code like the following:

```php
function my_amp_analytics() {
	if ( ! function_exists( 'is_amp_endpoint' ) || ! is_amp_endpoint() ) {
		return;
	}
	?>
	<amp-analytics type="gtag" data-credentials="include">
		<script type="application/json">
			{
				"vars" : {
					"gtag_id": "AW-71tt58888",
					"config" : {
						"AW-7153tttt75": { "groups": "default" }
					}
				}
			}
		</script>
	</amp-analytics>
	<?php
}
add_action( 'wp_footer', 'my_amp_analytics' );
add_action( 'amp_post_template_footer', 'my_amp_analytics' ); // For legacy Reader mode template.
```
