### ISSUE TITLE
Onboarding wizard: improve Reader mode and Transitional mode recommendations

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#4990]
From @westonruter in https://github.com/ampproject/amp-wp/pull/4980#discussion_r449695131.
____________________

We should export to JS this logic from PHP:

```php
$has_amp_support = current_theme_supports( 'amp' ) || in_array( get_stylesheet(), AMP_Core_Theme_Sanitizer::get_supported_themes(), true );
```

Note I'm intentionally using `get_stylesheet()` here as opposed to `get_template()` because child themes of core themes are often not AMP-compatible.

Nevertheless, we may want to hold off on doing this until I finish my work on the Reader theme loading because this changes how the `amp` theme support is mutated (or not).

There's also a case to do something similar for Reader mode, for themes that _don't_ have `amp` theme support and yet have an `amp` directory, which is captured by this logic at the moment:

https://github.com/ampproject/amp-wp/blob/a8a4d4d05f9727aad2304db103a3ab97817aafa6/includes/class-amp-theme-support.php#L349-L366

We may want to mention that the active theme has special legacy Reader mode support, and also indicate that in the list of Reader themes.

**Comment by pierlon** [comment]
**QA failed**

Template mode recommendations are not improved and does not factor in whether the current theme is AMP compatible:

![image](https://user-images.githubusercontent.com/16200219/87717822-8d726280-c7a0-11ea-91d6-5233bb8f431a.png)


The AMP settings page does seem to make note of the current theme being AMP compatible, however:

![image](https://user-images.githubusercontent.com/16200219/87717921-b1ce3f00-c7a0-11ea-8690-7a4e2836b1ff.png)
