### ISSUE TITLE
Illegal string offset warning in plugin suppression table

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#4996]
## Bug Description

While working on #4704, I saw the following:

<img width="959" alt="Screen Shot 2020-07-07 at 1 36 42 PM" src="https://user-images.githubusercontent.com/9020968/86826945-fea26f00-c056-11ea-9711-d9279a02a67e.png">

This is the plugin I used to generate the error for testing: https://gist.github.com/westonruter/6880918d45deb39c89e17f3b76583521

I briefly tried fixing it on my branch but I think I messed something up, so I undid it.

## Steps to reproduce

1. Turn on WP_DEBUG
2. Activate the plugin linked above.
3. Create a plugin validation issue by saving a shortcode on a post.
4. See the warning on the settings screen

Note that the screenshot shows my in-progress branch. The table looks different on `develop`.

## Additional context

 - WordPress version: Latest
 - Plugin version: Branched off `develop`
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version: 7.3
 - OS:
 - Browser: Chrome
 - Device: Macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
@johnwatkins0 The branch you were working on was `feature/4704-settings-screen-updates`, right?

**Comment by johnwatkins0** [comment]
Actually this might be a false alarm because I'm no longer seeing it. I'll assign this to myself and report back if it comes again.

<img width="1114" alt="Screen Shot 2020-07-07 at 4 16 20 PM" src="https://user-images.githubusercontent.com/9020968/86844141-39170680-c06d-11ea-9aa8-3298eb939a63.png">

**Comment by pierlon** [comment]
Ah OK. I wasn't able to replicate the issue locally, but I'll keep an eye on it still.

**Comment by johnwatkins0** [comment]
I haven't seen this again. Going to close it.
