### ISSUE TITLE
Convert YouTube shortcode and oEmbed to <amp-youtube>

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#5]
See https://github.com/ampproject/amphtml/blob/master/extensions/amp-youtube/amp-youtube.md

**Comment by corysimmons** [comment]
When I replace the thumbnail with a featured video it puts the video on top of the entire webpage (immediately inside `<body>`) whereas with just the featured image it puts it at the top of the content appropriately (after the post's header).

https://github.com/Automattic/amp-wp/blob/master/readme.md#featured-image

**Comment by mjangda** [comment]
@corysimmons Can you share the code you were using?
