### ISSUE TITLE
AMP Frontpage SEO Error

### ISSUE THREAD

**Issue by okupdatenumber** [Automattic/amp-wp#5004]
Our WordPress website has a home page frontpage set up.  Everything is going well without the AMP, but as soon as the AMP activates, a lot of problems arise that is happening to all WordPress users. 

Error List 🧐👨‍💻

1. page published & page modified details was missing on opengraph. 
2. AMP live list is not Update on Google.

**Comment by westonruter** [comment]
Please share the URL for your site.
