### ISSUE TITLE
Unable to preview customizing the color scheme in Twenty Nineteen when AMP page loaded

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5006]
## Bug Description

When customizing the Twenty Nineteen theme and previewing an AMP page (either because the site is in Transitional mode and you clicked “Customize” while on an AMP page, or you have Twenty Nineteen selected as the Reader theme and you are customizing the AMP page), if you try changing the Primary Color:

![image](https://user-images.githubusercontent.com/134745/86955902-2e13b300-c10d-11ea-8d8f-1a4638f690ea.png)

Then no change is shown in the preview. Normally the changes are applied live via JS as the settings have the `postMessage` transport.

The issue is that the `twentynineteen_colors_css_wrap()` function Twenty Nineteen is supposed to be outputting a `style` element like:

```html
<style type="text/css" id="custom-theme-colors" data-hue="117">...</style>
```

And then the theme's `customize-preview.js` targets this element to dynamically update the stylesheet. However, since the CSS is getting processed and concatenated into `style[amp-custom]`, the original element is no longer present to target.

The quick fix is to target the `style` element to be part of dev mode, as the style sanitizer will then skip it from processing:

```php
add_filter( 'amp_dev_mode_element_xpaths', function( $xpaths ) {
	if ( is_customize_preview() ) {
		$xpaths[] = '//style[ @id = "custom-theme-colors" ]';
	}
	return $xpaths;
} );
```

This is a regression introduced by #4977, although not because that PR was doing something incorrect.

Two possible resolutions to this:

1. Update the core theme sanitizer to make sure that any such `style` elements get included in dev mode. (easy)
2. Update the style sanitizer to prevent concatenation of all style elements, leaving them all in their original placements. (hard)

## Expected Behaviour

Color changes should be live previewable!

## Steps to reproduce

1. Switch to Reader mode and select Twenty Nineteen as the Reader theme.
2. Visit an AMP page and click Customize in the admin bar.
3. Try changing the Primary color.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
**QA passed**

The theme's primary color can be changed and reflects changes in realtime on the AMP version of a page:

![Image 2020-07-16 at 6 23 07 PM](https://user-images.githubusercontent.com/83631/87696732-81cb6f80-c791-11ea-928b-3c42f5734291.png)

The style to make this possible is marked with `data-ampdevmode`:

![Image 2020-07-16 at 6 23 29 PM](https://user-images.githubusercontent.com/83631/87696778-960f6c80-c791-11ea-9797-eed5391577bc.png)
