### ISSUE TITLE
Indicate which controls in the AMP Customizer for a Reader theme are shared with the non-AMP active theme

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5008]
## Feature description

When a Reader theme has been selected for Reader mode, the Customizer opened from an AMP page will be distinctly for the theme that was chosen for Reader mode. It will have the theme-specific settings for the Reader theme instead of the settings for the active theme. Additionally, the Themes panel and Widgets panels are removed from the AMP Customizer:

Non-AMP Customizer | AMP Customizer
----------------------|------------------
![Twenty Twenty Customizer](https://user-images.githubusercontent.com/134745/86974848-e2bccd00-c12b-11ea-95ee-548c6da0aadd.png) | ![Twenty Fifteen AMP Customizer](https://user-images.githubusercontent.com/134745/86976028-798a8900-c12e-11ea-9e1a-2d981f84e8d4.png)

Nevertheless, there _are_ settings which are common to both versions of the Customizer: any which are not tied to `theme_mod` settings.

Section/Panel | Shared | Not Shared
--------------|--------|-------------
Site Identity | Site Title, Tagline, Site Icon | Logo, Retina Logo (in Twenty Twenty), Display Site Title and Tagline (in Twenty Fifteen, etc)
Colors | None | Primary color, header color, background color, etc
Header Media/Image | None | Video, image, etc
Background Image | None | Selected image, Position, Size, etc
Menus | Nav Menus, Nav Menu Items | Menu location assignments
Homepage Settings | Static front page and page for posts | None
Additional CSS | None | Theme-specific!

Themes may add/remove controls to each of these sections or even add new sections. Plugins may also add/remove controls to any of these sections.

When in the AMP Customizer, there should be some indication for the controls that will impact the non-AMP version of the site.

* **Menus:** A general notice may make sense in the Menus panel to explain that the menus and menu items are shared, and that if they want to have an AMP-specific menu they should create a new menu and assign it to the desired location in the Reader theme.
* **Homepage Settings:** Since this is entirely shared between AMP and non-AMP, perhaps this should just be removed entirely from the AMP Customizer. Otherwise, it should get a notice in the panel (if any of the controls have non-option settings).
* **Site Identity:** Since the site title, tagline, and site icon are all shared, but the other settings are not, the shared controls should probably get individual notifications to say they are shared. This should probably go for _every_ such control in sections other than Menus and Homepage Settings.

The Customizer API for adding notifications to controls can be seen here: https://make.wordpress.org/core/2016/07/05/customizer-apis-in-4-6-for-setting-validation-and-notifications/

![image](https://user-images.githubusercontent.com/134745/86977127-c707f580-c130-11ea-927f-8988c9045642.png)

The Customizer API for adding notifications to sections and panels can be found here: https://make.wordpress.org/core/2017/11/01/improvements-to-the-customize-js-api-in-4-9/#notification-improvements

![image](https://user-images.githubusercontent.com/134745/86977097-ba839d00-c130-11ea-93fb-39a826df73cf.png)

The notifications should be added with JS as opposed to PHP to account for dynamically-created controls.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed**

When customizing a Reader theme:

- AMP notice is shown in root panel

![image](https://user-images.githubusercontent.com/16200219/87712060-aaeefe80-c797-11ea-8fb4-e3b452bb803b.png)

- Notice is shown in Menus panel:

![image](https://user-images.githubusercontent.com/16200219/87712212-e12c7e00-c797-11ea-9206-b6c754eef9e1.png)

- Notices are shown for shared options:

![image](https://user-images.githubusercontent.com/16200219/87712421-2355bf80-c798-11ea-8543-a55e155ae947.png)
