### ISSUE TITLE
Choosing a dark colour scheme can result in very low-contrast colour combos

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/amp-wp#501]
To replicate, choose "Dark" next to "Color Scheme."

The mid-grey colour for elements like post author and post meta against the black background is extremely difficult to read.

The accent colour used for links can also be very hard to read, depending on the colour selected. 

Since we probably don't want to get into applying contrast rules to users' selected colours at this stage, could we at least consider choosing a grey shade that has more contrast against black, since that grey will be the same no matter what header/link colour the user chooses?

![customize_ hello world coherent 1 0 5 by automattic-5](https://cloud.githubusercontent.com/assets/7662449/19091602/51e228ee-8a51-11e6-9326-023fb88cf091.png)

**Comment by allancole** [comment]
I lightened up the grey colors and borders to add more contrast for the dark background. Let me know what you think, @kathrynwp 

![image](https://cloud.githubusercontent.com/assets/709581/19094215/f5f62cd6-8a5c-11e6-833c-eab51f472387.png)

Fixed here: https://github.com/Automattic/amp-wp/tree/fix/dark-bg-contrast

**Comment by kathrynwp** [comment]
That looks much better to my eye. I ran the new grey/black combo through a c[olour-contrast checker](http://www.thinkoutsidetheslide.com/color-contrast-calculator/) to be sure it meets minimum accessibility specs, and this is what it found:

> Color Brightness Test (>125 is a passing score): 128
> Passed!
> 
> Color Difference Test (>500 is a passing score): 384
> Failed - see suggestions below

> Suggestions for Improving the Color Difference

> Some commentators suggest that the pass value should be 400 instead of the 500 that the W3C has in their documentation. If your test value is close to 500, it is probably fine. If you need to improve your color contrast, increase the difference between any of the pairs of attributes. Increasing the difference between the Green attributes will have the same impact on this test as increasing the difference between the Red attributes or the difference between the Blue attributes. Increase the difference between each pair of attributes to improve the result of this test.

@davidakennedy - interested to know what you think.

**Comment by allancole** [comment]
Interesting, @kathrynwp  

The text colors should all pass that spec now. See the commit above.

![image](https://cloud.githubusercontent.com/assets/709581/19122409/55fd3412-8af8-11e6-8537-06ddc2ca28bd.png)

**Comment by kathrynwp** [comment]
Text color `dedede` on black gets a passing grade on both tests:

> Color Brightness Test (>125 is a passing score): 222
> Passed!
> Color Difference Test (>500 is a passing score): 666
> Passed!

Muted text color `b1b1b1` on black also gets a passing grade for both:

> Color Brightness Test (>125 is a passing score): 171
> Passed!
> Color Difference Test (>500 is a passing score): 513
> Passed!

👍
