### ISSUE TITLE
Move Analytics Options submenu into "Advanced" section of settings page 

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5013]
## Feature description

Mentioned by @westonruter here: https://github.com/ampproject/amp-wp/pull/4998#discussion_r452433011

## Acceptance criteria

- No more Analytics Options menu
- Form exists on settings page in a section that can be expanded/collapsed

## Implementation brief

* Handle fetching, updating data via the AMP Options REST endpoint

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Also referenced in https://github.com/ampproject/amp-wp/issues/2317#issuecomment-644517692, which may or may not be resolved by whatever PR closes this.

**Comment by westonruter** [comment]
While not as important as #5014 or #5015, this would be great to include in 1.6 because then we can eliminate all of the old form-based options processing in favor of exclusively using the REST API.

**Comment by westonruter** [comment]
Note that with this and #5100 there will no longer be a need for `\AMP_Options_Manager::add_settings_error()`. It can be deleted.
