### ISSUE TITLE
Plugin settings page: Handle post type/template selection via REST/React

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5015]
## Feature description

Following up on #4998, which rebuilt the plugin settings screen using REST endpoints and components built for the setup wizard. One part that was largely left out of the updates due to its potential size and complexity was this:

<img width="876" alt="Screen Shot 2020-07-09 at 4 57 13 PM" src="https://user-images.githubusercontent.com/9020968/87094955-76160100-c205-11ea-80ea-d91e6cedf0b1.png">

Currently this is wrapped in the new settings page but handled the traditional way with settings saved on the backend via form submission.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Options make sense in the context of the page
* Saving doesn't require a full page refresh

## Implementation brief

* Details for for the various conditions will need to be ironed out
* Can probably use the AMP options endpoint.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
@westonruter Just confirming as I translate this bit into React, is this user_supported thing obsolete now? 

```
<?php if ( ! empty( $option['user_supported'] ) ) : ?>
							<input type="hidden" name="<?php echo esc_attr( $element_name ); ?>" value="<?php echo esc_attr( $id ); ?>">
						<?php endif; ?>
```

**Comment by westonruter** [comment]
Correct! The `user_supported` is gone.

**Comment by westonruter** [comment]
I mean, it's just redundant now with `supported`.

**Comment by pierlon** [comment]
**QA Passed**

- Supported Templates options are correctly saved via a REST request
- The Templates section is hidden when Reader mode is chosen
- Toggling the "Pages" content type shows an alert and hides the Homepage template if all templates are not being served AMP
