### ISSUE TITLE
Minor UI updates on settings screen

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5018]
## Feature description

Copying from Slack.

1.
> Can you reduce the bottom margin on the headings? It's 1rem on bottom but 0 on the top:
![image (1)](https://user-images.githubusercontent.com/9020968/87106310-c9e31300-c222-11ea-80c7-205cdd572d5d.png)

2. 
> There's also excessive margin at the bottom of toggles:

![image (2)](https://user-images.githubusercontent.com/9020968/87106367-ed0dc280-c222-11ea-80d9-70dcb4b772db.png)

3. 
> The approach to highlight selected boxes, could be made so that the gray area does not show when boxes are not selected. Boxes that are not "selectable" would not have the gray side, and only the one selected will have the blue side.  Would that make the UI sleeker?

4. 
> The title of the settings screen should be bold (?) and there should be a bit more space from the title to the first box:

5.
> WDYT about a bit less space between the boxes? [in the mode selection section]

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
@jwold Interested in your input on any of these items before I work on them.

**Comment by jwold** [comment]
@johnwatkins0 my thoughts :)



> 1. Can you reduce the bottom margin on the headings? It's 1rem on bottom but 0 on the top:

This should be fine. 

> 2. There's also excessive margin at the bottom of toggles:

Agreed, let's remove the margin. 

> 3. The approach to highlight selected boxes, could be made so that the gray area does not show when boxes are not selected. Boxes that are not "selectable" would not have the gray side, and only the one selected will have the blue side. Would that make the UI sleeker?

I think it would look imbalanced. Not a fan of this, but ok if we want to try it. Screenshot of what it would look like: https://d.pr/i/z40Y8q

> 4. The title of the settings screen should be bold (?) and there should be a bit more space from the title to the first box:

I think that's a good idea. 

> 5. WDYT about a bit less space between the boxes? [in the mode selection section]

I was actually thinking the same! :)

**Comment by johnwatkins0** [comment]
While working on this today I'm going to explore placing the plugin suppression and template sections into an "Advanced" panel. If it's not simple, I will save that for later.

**Comment by johnwatkins0** [comment]
I'm also going to switch to WP 5.0 and test everything.

**Comment by westonruter** [comment]
@johnwatkins0 Here's another issue that can be easily addressed here. The toggles don't feel the same as the radio buttons in two ways:

1. The outline is different. Radio button is 2px whereas toggle is 1px.
2. The color is different. Radio button is medium gray but toggle is dark gray.

Radio Unselected | Radio Selected
------------|----------
![radio-unselected](https://user-images.githubusercontent.com/134745/87575166-5b6bde00-c684-11ea-838f-2634845b28d1.png) | ![radio-selected](https://user-images.githubusercontent.com/134745/87575196-6757a000-c684-11ea-975f-9aaf03465a98.png)

Suggestion:

When | Toggle Unchecked | Toggle Checked
------|--------------------|-----------------
Before | ![toggle-unchecked-before](https://user-images.githubusercontent.com/134745/87575319-9837d500-c684-11ea-9686-055e26dba0bc.png) | ![toggle-checked-before](https://user-images.githubusercontent.com/134745/87575328-9c63f280-c684-11ea-993d-abbfabcd87e6.png)
After | ![after-toggle-unchecked](https://user-images.githubusercontent.com/134745/87575576-f82e7b80-c684-11ea-93aa-09db586f1e8b.png) | ![after-toggle-checked](https://user-images.githubusercontent.com/134745/87575620-07adc480-c685-11ea-9a8f-f178f58ef17d.png)

(These screenshots aren't quite right.)

Maybe as opposed to making the toggle medium gray, the radio should be made darker gray. 

Humm, maybe the radio button should be made 1px instead as well. I see core uses 1px:

> ![image](https://user-images.githubusercontent.com/134745/87575778-45125200-c685-11ea-89b1-7ef56dd3c1e6.png)

In any case, let's just make the two controls consistent! 😄  /cc @jwold

**Comment by johnwatkins0** [comment]
I'll make those adjustments. I might be imagining things, but I updated to the WP 5.5 nightly this morning and I think the switch was changed. I'll make sure 5.5 isn't having any other unwanted effects.

**Comment by jwold** [comment]
Agreed with all Weston's feedback except, I would lean toward 2px widths, just because we're trying to copy amp.dev with all their icons being 2px. Not a hill I'd die on, but a preference for now.

**Comment by johnwatkins0** [comment]
Updated the borders for radios, toggles, and checkboxes to be consistent in 3fba71ac9:

<img width="42" alt="Screen Shot 2020-07-15 at 1 25 39 PM" src="https://user-images.githubusercontent.com/9020968/87581587-d04c1180-c69e-11ea-81e1-770f1482d530.png">
