### ISSUE TITLE
Settings screen fields are empty when first activating the plugin

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5020]
## Bug Description

When first accessing the admin screen after activating the plugin (and not going through the wizard), all of the settings are blank (e.g. the template mode is not selected). While this is correct for the Wizard, it cannot be correct for the admin screen as for users who have upgraded to the this version of the plugin need to have all their previously-saved settings shown.

## Expected Behaviour

All saved settings should always be reflected on the settings screen.

## Steps to reproduce

1. Run `wp option delete amp-options`
2. Access the AMP Settings screen
3. See non-selected template mode.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/87116648-3104c580-c22b-11ea-86cf-9f626a2ea6ac.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
Yes, good point. Currently when `plugin_configured` (a new option) is `false` we unset the default template mode and reader theme in the React state to force the user to make choices. This was intended for the wizard but it's applying to the settings screen as well. For this fix we can: 

1. Pass a prop into the React options context provider to indicate we're on the settings page and not to unset anything
2. Do something to set `plugin_configured` to true at some point in the execution if `amp-options` is already in the database.

I'm inclined toward 1 just because it is a clearer path, but I'm sure 2 could be done as well with a little figuring out.

**Comment by westonruter** [comment]
It depends on what we want existing users of the plugin to be presented with the wizard as blank or using the values they previously have been using.

If we don't want that, then 1 is the correct approach.

If we don't, then we could do something in `\AMP_Options_Manager::get_options()` where we make the `plugin_configured` key `true` if `$options` was not empty. So something like:

```diff
--- a/includes/options/class-amp-options-manager.php
+++ b/includes/options/class-amp-options-manager.php
@@ -89,6 +89,8 @@ class AMP_Options_Manager {
                $options = get_option( self::OPTION_NAME, [] );
                if ( empty( $options ) ) {
                        $options = []; // Ensure empty string becomes array.
+         } else {
+                 $options[ Option::PLUGIN_CONFIGURED ] = true;
                }
```

I kinda think 2 is preferable because I'm sure I'd be annoyed if I upgraded the plugin and was prompted to go through the wizard only to find all of my existing settings not reflected.

**Comment by pierlon** [comment]
**QA Passed**

A default set of options is set and persisted if the `amp-options` option does not exist:

![image](https://user-images.githubusercontent.com/16200219/87694330-930a8100-c77d-11ea-9067-9d40f58b72fc.png)

**Comment by techgarageblog** [comment]
Hi, I don't like to open a new issue, but the problem is there again.

Installed the Plugin new on my staging site and live project. Both sites (staging without any plugins active) doesn't have any settings.

Best Kevin
