### ISSUE TITLE
CSS sanitizer removes classes with a slash (/)

### ISSUE THREAD

**Issue by sboerrigter** [Automattic/amp-wp#5021]
## Bug Description

Classes with slashes (such as `.w-1/4`) are not included in the CSS output on AMP pages. 

## Expected Behaviour

If the HTML marktup contains a CSS class with a slash (such as `class="w-1/4"`) the styling for that class should be included in the CSS output.

## Steps to reproduce

1. Edit a template file (such as `single.php`).
2. add a CSS class with a slash (such as `<h1 class="w-1/4">Blah...</h1>`).
3. add styling for that CSS class (such as `.w-1/4 { width: 25%; }`) or load [Tailwind CSS ](https://tailwindcss.com/docs/installation/#using-tailwind-via-cdn).
5. Visit the regular version of the page and see that the styling is applied.
6. Visit the AMP version of the page and see that the styling is not applied.

## Additional context

 - WordPress version: 5.4.2
 - Plugin version: 1.5.4
 - AMP plugin template mode: Transitional

Classes with slashes is a common practice in the popular [Tailwind CSS framework](https://tailwindcss.com/docs/width).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
This seems to be a duplicate of #4609. We do have a fix for this ( see #4610), which is set to be available in v1.6 of the plugin.

**Comment by sboerrigter** [comment]
@pierlon thanks for the quick reply and sorry that I didn't see #4609. 

I just tried the development version of the plugin and it seems like version 1.6 indeed fixes this issue 😄. I'll wait for that to be released. Thanks!
