### ISSUE TITLE
Onboarding wizard: Next button sometimes incorrectly disabled

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5024]
## Bug Description

As brought up on Slack:

<img width="400" alt="Screen Shot 2020-07-10 at 12 07 58 PM" src="https://user-images.githubusercontent.com/9020968/87191024-36a8ec80-c2b9-11ea-91b3-5ad6ab61cb81.png">

Bug is probably somewhere in here: 

https://github.com/ampproject/amp-wp/blob/develop/assets/src/onboarding-wizard/pages/template-mode/index.js#L32-L46

## Expected Behaviour

If the user has completed the wizard previously, their mode should be preselected and they should be able to move forward immediately.

## Steps to reproduce

1. Complete the onboarding wizard
2. Revisit the onboarding wizard
3. Change your answer to the technical question and move forward
4. Next button is incorrectly disabled

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
QA Passed.
