### ISSUE TITLE
Theme mods (including nav menu locations) are not copied from active theme to reader theme

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5039]
## Bug Description

When selecting a Reader theme, the theme mods from the active theme are not copied. This leaves the nav menus empty (or else the theme fallback of listing all pages is done) and other customizations are also left out. For non-menus, this is actually normal core behavior when switching themes. Core does not copy theme mods when switching themes, since the theme mods may not be appropriate. Nevertheless, it doesn't even do so when switching between child themes of the same theme (see [wp-trac#27177](https://core.trac.wordpress.org/ticket/27177)). The exception to this is Nav Menus, where nav menus from the old theme will attempt to automatically get assigned to their corresponding nav menu locations in the new theme (see [wp-trac#39692](https://core.trac.wordpress.org/ticket/39692)). However, not even this is being done when enabling an AMP Reader theme.

Related: #5008

## Expected Behaviour

Theme mods from the active theme should be copied _if_ they do not already exist. 

The `nav_menu_locations` theme mod should be copied by default. Other theme mods should not be copied by default, but there should be a button to easily copy them when in the Customizer preview in order to see the changes to make sure they are correct.

## Steps to reproduce

1. Set AMP template mode to Reader with legacy theme
1. Activate Twenty Sixteen as main theme
1. Open Customizer and customize Twenty Sixteen:
    1. Set menu locations
    1. Set Custom Logo
    1. Set Custom Background Color
    1. Set Custom Background Image
1. Make sure Twenty Twenty is in a clean state by deleting any existing theme mods via: `wp option delete theme_mods_twentytwenty`
1. Update AMP template mode to switch from legacy theme to Twenty Twenty.
1. Open the AMP version of the site and see none of the customizations from the active theme are applied, requiring the user to do them all themselves from scratch.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

This function in core normally runs at `after_setup_theme`:

```php
/**
 * Handle menu config after theme change.
 *
 * @access private
 * @since 4.9.0
 */
function _wp_menus_changed() {
	$old_nav_menu_locations    = get_option( 'theme_switch_menu_locations', array() );
	$new_nav_menu_locations    = get_nav_menu_locations();
	$mapped_nav_menu_locations = wp_map_nav_menu_locations( $new_nav_menu_locations, $old_nav_menu_locations );

	set_theme_mod( 'nav_menu_locations', $mapped_nav_menu_locations );
	delete_option( 'theme_switch_menu_locations' );
}
```

We need to emulate the same behavior when activating a Reader theme.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
This passes QA.

1. Activated the Twenty Sixteen theme
2. Made modifications in the customizer
3. Set Twenty Twenty as my reader theme
4. Saw my customizations applied to my reader theme
