### ISSUE TITLE
Wizard should direct users in Reader mode to Customizer at Done screen rather than Settings screen

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5045]
## Feature description

Based on https://github.com/ampproject/amp-wp/issues/5039 what we really want is for users in Reader mode to be directed to the AMP Customizer to ensure the proper customizations are in place. Because if they don't do this, the nav menus probably won't be assigned and the colors won't be reflecting the active theme. 

So in reality, I'd probably say we should make “Customize Design” take the place of the “Finish” button when Reader mode is selected.

Before | After
-------|-------
![image](https://user-images.githubusercontent.com/134745/87484447-0334cd80-c5eb-11ea-8aa7-480c5ee771a9.png) | ![image](https://user-images.githubusercontent.com/134745/87484554-5444c180-c5eb-11ea-84bd-bfebb55fcbd4.png)

👉  Once in the Customizer, clicking the Close button should then take the user to the AMP Settings Screen.

A site in Standard/Transitional mode would continue to say just Finish, as there is no “Customize AMP” button:

> ![image](https://user-images.githubusercontent.com/134745/87484611-79d1cb00-c5eb-11ea-87c2-0d6f4aa2e867.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Now that we have a Customizer link at the top of the settings screen this is less important, but I think it's still a good change to make.

**Comment by amedina** [comment]
Yeah; this is important still to complete the flow nicely.
