### ISSUE TITLE
Refine copy of `Supported Templates` section in admin screen

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#5046]
- Both sections heading must be **bold**
-  Make first-column heading concise: `Content types available as AMP`
-  In second column, make the Singular template non-selectable when it is required by other templates (e.g. Posts)
- Remove notice `Required...`

<img width="1250" alt="Screen Shot 2020-07-14 at 4 12 34 PM" src="https://user-images.githubusercontent.com/506089/87485575-f9609980-c5ed-11ea-9395-0c987d99288a.png">

**Comment by westonruter** [comment]
> * Both sections heading must be **bold**

Fixed in 32b1dd1c9c57ed5a4caa1f233ca592463a3c4359

**Comment by westonruter** [comment]
> * Remove notice `Required...`

Fixed in 9105286f9

**Comment by westonruter** [comment]
> * Both sections heading must be **bold**
> * Make first-column heading concise: `Content types available as AMP`

What appears here is actually not intended to be a heading. It's a description. The heading got hidden accidentally. Now it appears as:

![image](https://user-images.githubusercontent.com/134745/87587093-7fd0b600-c696-11ea-92b7-c595fe9aee3a.png)

When in legacy mode, the heading is hidden since only the post types are shown in the first place:

![image](https://user-images.githubusercontent.com/134745/87587210-aa227380-c696-11ea-8592-c956583b79b1.png)

**Comment by westonruter** [comment]
> * In second column, make the Singular template non-selectable when it is required by other templates (e.g. Posts)

How about this as an alternative: When unchecking the Singular template, throw up a `confirm()` dialog:

![image](https://user-images.githubusercontent.com/134745/87588044-dd193700-c697-11ea-96c9-033a76c6846f.png)

Done in 0a6df8c9a6f7f8d1ec00ea9b4af70d8db4c2b297.

**Comment by amedina** [comment]
Love those changes. Very much aligned with the rest of the UI.

**Comment by westonruter** [comment]
One other thing I noticed missing is a description paragraph to go under the Templates heading. So in 1084e1899 I've added a paragraph that has a link to the [template hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/) handbook page:

![image](https://user-images.githubusercontent.com/134745/87589042-7f85ea00-c699-11ea-948f-a5018724b7aa.png)

**Comment by amedina** [comment]
Oh yes; that is needed. 

The copy: `Serve all templates as AMP regardless of what is being queried` can be calibrated as well. We will do that on the copy overall pass.
