### ISSUE TITLE
Wizard: Uninstallable reader theme incorrectly listed as available

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5048]
## Bug Description

From @amedina in Slack. 

________________

1. With `define( 'DISALLOW_FILE_MODS', true );` in wp-config.php.
2. Delete all themes except 2015, 2016, including 2020 which was the active theme. Rerun wizard:
<img width="1228" alt="Screen Shot 2020-07-14 at 6 02 58 PM" src="https://user-images.githubusercontent.com/9020968/87563095-763e5280-c684-11ea-96f0-f6df50602a85.png">

The wizard is determining the availability of 2020 differently from the others.
And 2020 is selectable although the flag disallowing the install is on (and the other themes appear on the Unavailable section).

Which results in this if choosing 2020:
<img width="916" alt="Screen Shot 2020-07-14 at 6 08 11 PM" src="https://user-images.githubusercontent.com/9020968/87563203-93732100-c684-11ea-8d35-5546be4412e4.png">

## Expected Behaviour

With `DISALLOW_FILE_MODS` turned on and Twenty Twenty deleted (but previously set as active reader theme), Twenty Twenty should not be available.

I.e., when the active reader theme is not available and not installable, we should revert the setting to legacy by default.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
On a related note, we should probably update the logic in `ReaderThemeLoader` to abort `override_theme` if the provided `reader_theme` is not available.

Actually, I thought this would have been accounted for already per:

https://github.com/ampproject/amp-wp/blob/7dc643bfcae164963f3244596944fa04998698f8/src/ReaderThemeLoader.php#L147-L155

The `$reader_theme` variable here should be `null` if the theme does not exist.

We could also consider preventing a user from uninstalling a theme if it is selected as the Reader theme. This would largely prevent this from happening.

**Comment by jwold** [comment]
I'm not sure I'm tracking the logic on this one. I went through it, but am unsure if the results are expected.

1. Ran through the wizard and set Twenty Twenty as my reader theme
2. Added `define( 'DISABLE_FILE_MODS', true );` to wp-config.php.
3. Installed Twenty Sixteen and Twenty Fifteen
4. Deleted Twenty Twenty manually
5. Ran through wizard and selected Twenty Twenty as reader theme.
6. Got a congratulations notice:

<img width="1311" alt="Screen Shot on 2020-08-25 at 10-18-57" src="https://user-images.githubusercontent.com/3411173/91206715-6de22a00-e6bc-11ea-9381-ddd69e1704b2.png">

**Comment by jwold** [comment]
Re-ran with `define( 'DISALLOW_FILE_MODS', true );`

This issue appears to be resolved.

- Fresh WP install
- Update themes to only: 2020, 2016, 2015.
- Set 2016 as active. 
- Install AMP plugin
- In onboarding wizard set to Reader: Twenty Twenty 
- Set `define( 'DISALLOW_FILE_MODS', true );` in wp-config
- Manually delete Twenty Twenty theme from directory (in Finder with Local by Flywheel)
- Get a notice that Twenty Twenty not found, and Legacy template used for AMP pages (https://d.pr/i/kBebJc). 
- Re-run wizard
- In onboarding wizard look for Twenty Twenty. It now appears disabled:

![Screen Shot 2020-08-25 at 10 44 35](https://user-images.githubusercontent.com/3411173/91209149-22ca1600-e6c0-11ea-80d8-79988b0224b0.png)
