### ISSUE TITLE
amp_get_current_url() broken in CLI context (on broken sites)

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5051]
## Bug Description

`amp_get_current_url()` is broken in CLI contest. If it tries to parse a broken home URL and needs to guess the domain, it just assumes that `$_SERVER['HTTP_HOST']` exists, which is not true outside of the webserver context, like when running WP-CLI commands via the `cli` SAPI. This causes PHP to throw a notice.

## Expected Behaviour

It should not throw any PHP notices, regardless of the context.

## Steps to reproduce

1. Change the home URL into something `wp_parse_url()` fails to parse, like `:`. Depending on the environment, this can be done via a filter, by adapting the DB or by adapting the `wp-config.php` file.
2. Use WP-CLI to execute the following command:
```php
wp eval 'echo amp_get_current_url();'
```
3. **Verify:** A PHP notice `Undefined index: HTTP_HOST in ...` is thrown.

## Screenshots

![Image 2020-07-15 at 11 58 43 AM](https://user-images.githubusercontent.com/83631/87569733-d9050d80-c6c7-11ea-9dc9-b2c0a953afe8.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> 1. **Verify:** A PHP notice `Undefined index: HTTP_HOST in ...` is thrown.

I don't believe this occurs if your `wp-cli.yml` has a `url` field already supplied.

Also, my `wp-config.php` has `WP_HOME` and `WP_SITEURL` set. So I'm not seeing it here either.

The issue will only occur if `home_url()` does not return a URL with a `host` in it. Why is this occurring for you?

**Comment by schlessera** [comment]
My bad, I forgot an important step in the replication instructions. This issue only happens if you have a bad home URL that `wp_parse_url()` cannot properly parse to begin with.

I've adapted the description and instructions above.

**Comment by westonruter** [comment]
So this would be very unusual to encounter, yeah?

**Comment by schlessera** [comment]
Yes, but the entire point of the other PR I QAed where I detected this issue was to make it robust against edge cases.

**Comment by schlessera** [comment]
**QA passed**

I couldn't find a way now to produce a PHP notice.
