### ISSUE TITLE
Disconnected foreach in core block handler

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5066]
In the Core block embed handler, there's a `foreach` loop that seems out of place and is a probable bug:

https://github.com/ampproject/amp-wp/blob/b51629b407f74f99521e69fc6c080a57552b7068/includes/embeds/class-amp-core-block-handler.php#L347-L355

Note that this `foreach` loop runs for every `$text_widget` that is found by the wrapping `foreach` loop, but doesn't seem to have any relation to said `$text_widget`.

**Comment by westonruter** [comment]
The origin of that code is #4515 and my commit here: edf3d5d37be6d3ae3b1385f0ead8a0f7320667d5

The relation to the Text widget is `video` shortcodes that occur _inside_ the Text widget. Does that make sense?

**Comment by schlessera** [comment]
The _inside the text widget_ part is missing, it's just doing the same
operation over the entire document _for each text widget_.

**Comment by westonruter** [comment]
Ah, I see. I neglected to include the `$text_widget` element as the XPath query context. Fix in #5074.

**Comment by schlessera** [comment]
**QA passed**
The `width` style can be seen on the non-AMP version and is gone on the AMP version.

![Image 2020-08-25 at 1 32 31 AM](https://user-images.githubusercontent.com/83631/91106774-d6f17f80-e673-11ea-9795-fde032aea7e4.png)

![Image 2020-08-25 at 1 33 04 AM](https://user-images.githubusercontent.com/83631/91106805-f25c8a80-e673-11ea-9b2b-a25461914d63.png)

However, I noticed that in cases like these, we leave cruft around in the form of `data-amp-original-style` which still has the `width` attribute that was removed in the main style. It doesn't break anything here, but this might be an opportunity for further reducing the HTML size.

**Comment by westonruter** [comment]
> However, I noticed that in cases like these, we leave cruft around in the form of `data-amp-original-style` which still has the `width` attribute that was removed in the main style. It doesn't break anything here, but this might be an opportunity for further reducing the HTML size.

It turns out that this must be retained because surprisingly there are some _meta_ style rules that actually target the `style` attribute value itself in selectors. See #4105.
