### ISSUE TITLE
Need Support for Pagination

### ISSUE THREAD

**Issue by ActionCoding** [Automattic/amp-wp#507]
I have many articles that are very long and on the desktop and responsive versions of my site I am using pagination using the  comment block available in wordpress. According to this link:

https://www.ampproject.org/docs/reference/components/amp-live-list

pagination is available on AMP pages. Can we get this implemented using the nextpage comment?

**Comment by ActionCoding** [comment]
Is there a reason this is not marked a as a high priority? It affects almost every serious blogger!

**Comment by ActionCoding** [comment]
Can someone please help me figure out how to get the plugin to recognize the built in Wordpress nextpage comments? This is vital to my blog.

**Comment by ActionCoding** [comment]
Is there anyone that can point me in the right direction as to where I would start. I have no problem working on it myself. Thanks!

**Comment by AdityaNayak** [comment]
+1 Same issue. 

Going with a custom solution at the moment.

**Comment by theendfear1** [comment]
@AdityaNayak may i know your custom solution?

**Comment by AdityaNayak** [comment]
Found a plugin instead on codecanyon. I haven't moved to AMP yet but was able to find a working solution.
https://codecanyon.net/item/wp-amp-accelerated-mobile-pages-for-wordpress-and-woocommerce/16278608/support

Let me know if you decide to buy, we can split the costs.

**Comment by westonruter** [comment]
Here's how nesxt/previous pagination support can be supported in your theme.

In your theme, add a file named `amp/post-pagination.php` that contains:

```php
<?php the_post_navigation(); ?>
```

Then in your `functions.php` add the following snippet:

```php
add_filter( 'amp_post_article_footer_meta', function( $parts ) {
	array_unshift( $parts, 'post-pagination' );
	return $parts;
} );
```

You'll need to add the desired styling separately.

And you'll probably also want something like this to ensure that the links point to the AMP versions:

```php
add_filter( 'post_link', function( $url, $post ) {
	static $recursing = false;
	if ( $recursing ) {
		return $url;
	}
	$recursing = true;
	if ( ! function_exists( 'post_supports_amp' ) || ! post_supports_amp( $post ) ) {
		return $url;
	}
	if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
		$url = amp_get_permalink( $post->ID );
	}
	$recursing = false;
	return $url;
}, 10, 2 );
```
