### ISSUE TITLE
Choosing custom reader theme does not show its info when said info is no longer supplied

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#5070]
## Bug Description

To summarize the overly complex title, if I activate a plugin that adds a custom reader theme like so:

```php
add_filter( 'amp_reader_themes', function ( $reader_themes ) {
	$reader_themes[] = [
		'name' => 'Neve',
		'slug' => 'neve',
		'preview_url' => 'https://wp-themes.com/neve',
		'screenshot_url' => 'https://i0.wp.com/themes.svn.wordpress.org/neve/2.7.5/screenshot.png?w=1144&strip=all',
		'homepage' => 'https://themeisle.com/themes/neve/',
		'description' => 'This is a non-core theme.',
	];
	return $reader_themes;
} );
```

Then deactivate said plugin, the following can be seen in the Reader themes section on the Settings page:

![image](https://user-images.githubusercontent.com/16200219/87976197-3c25e400-cabc-11ea-9374-0fef9388d428.png)

Notice that the theme name is not being shown. The reasoning for this makes sense, but as a user I would like to think that the currently activated theme information would persist since the theme is currently installed and active as the Reader theme.

## Expected Behaviour

The theme name and details should still be retained if it's the currently selected Reader mode theme.

## Steps to reproduce

1. Create and activate a plugin with the above filter
2. Choose the `Neve` theme as the Reader theme
3. Deactivate said plugin
4. See that the name of the theme is not shown in the Reader themes section, and is also not shown in the themes list

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I suppose we should force the current reader theme to be among the list. If the active reader theme is not in the list after filtering, then we should ensure it gets included.

**Comment by jwold** [comment]
Here's an updated SVG


[Group 3320.svg.zip](https://github.com/ampproject/amp-wp/files/4991413/Group.3320.svg.zip)

**Comment by westonruter** [comment]
@jwold We need the two desktop and mobile illustrations separated out into separate images, without the Desktop/Mobile labels.

**Comment by westonruter** [comment]
Here's what I propose:

1. As we discussed earlier, move move the invocation for `ReaderThemes::get_classic_mode()` to append _after_ the `amp_reader_themes` are filtered. Aside: We need to translate `'AMP Legacy'` here.
2. If the filtered output does _not_ include the currently-selected `reader_theme`, then obtain the necessary Reader theme data from `wp_get_theme( $reader_theme )` and `unshift` it onto the list of Reader themes.
3. The data obtained from `wp_get_theme()` will not include a `screenshot_url` so we should default to showing the `screenshot.png` from the theme, even though it will be a desktop screenshot. Set the background color of the `img` to be `black` and add `object-fit:contain` so that it is letter-boxed top and bottom.
4. If there is not even a `screenshot.png` then use the placeholder SVG for the mobile screenshot (and the desktop screenshot on the “Review” step).

**Comment by jwold** [comment]
@westonruter here you go, happy to make any changes if needed!

[Archive.zip](https://github.com/ampproject/amp-wp/files/4995439/Archive.zip)

**Comment by westonruter** [comment]
@jwold Please remove the device frame. So it should be just these rects:

![image](https://user-images.githubusercontent.com/134745/88840904-08b91880-d192-11ea-9e83-d3a79179be7c.png) 
![image](https://user-images.githubusercontent.com/134745/88840973-225a6000-d192-11ea-81ae-1c50ed13c745.png)

**Comment by jwold** [comment]
[Icons2.zip](https://github.com/ampproject/amp-wp/files/4996922/Icons2.zip)

Here you go! @westonruter

**Comment by westonruter** [comment]
I just realized an important implication for this. A theme can now add an `amp_reader_themes` filter to allow another theme to be used for Reader mode, and that theme can be used for Reader mode even when serving the Reader theme.

**Comment by johnwatkins0** [comment]
This is passing QA.

1. Set twentytwenty as my reader theme
2. Deleted twentywenty via the command line
3. Refreshed AMP settings. My reader theme was the legacy theme and I saw this notice:

<img width="1186" alt="Screen Shot 2020-08-24 at 8 30 25 PM" src="https://user-images.githubusercontent.com/9020968/91112445-c546b280-e648-11ea-9d17-25c6e2807a68.png">
