### ISSUE TITLE
Generator meta tag unexpectedly indicates reader mode when transitional mode applied

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5093]
## Bug Description

When in Reader mode, if the selected Reader theme at any time becomes the same as the active theme, the active template mode automatically transitions to Transitional mode. This is because Reader mode using the same theme as the active theme _is_ Transitional mode; Reader mode entails using a _different_ theme in AMP.

The logic which forces Transitional mode to be used when the active theme and Reader theme are the same can be found here:

https://github.com/ampproject/amp-wp/blob/363de34f57c2f096e24123bff62cbfd3cae2d388/includes/options/class-amp-options-manager.php#L165-L184

The logic is admittedly not ideal as there is a `@todo`.  The problem is the `! isset( $_GET[ amp_get_slug() ] )` check is preventing that block from running when serving an AMP page. The result is that the generator tag is:

```html
<meta name="generator" content="AMP Plugin v2.0.0-beta1; mode=reader; theme=twentytwenty">
```

## Expected Behaviour

The generator tag should rather be:

```html
<meta name="generator" content="AMP Plugin v2.0.0-beta1; mode=transitional">
```

## Steps to reproduce

1. Switch the active theme to Twenty Nineteen.
2. Switch to Reader mode and select Twenty Twenty as the Reader theme.
3. Switch the active theme to now be Twenty Twenty.
4. Navigate to an AMP page and look at generator tag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We could eliminate the special condition in `get_options` to instead listen for the `switched_theme` action, and if the theme is the same as the Reader theme then update the option to be transitional. That would mean the mode would not automatically switch back to Reader of the active theme is switched, but it would be simpler and maybe less magical.

**Comment by jwold** [comment]
Stuck on Step 3 of testing. Can't set the active theme to the same one as the Reader theme: https://v.usetapes.com/F7daxvvSgo

**Comment by westonruter** [comment]
Yeah, I think the only way is to switch the active theme using WP-CLI since the UI prevents the user from doing so. I'll verify this one.

**Comment by westonruter** [comment]
I set my primary theme to be Twenty Twenty-One and my Reader theme to be Twenty Twenty. Then via WP-CLI I did: `wp theme activate twentytwenty`. Upon doing so, my generator meta tag went from:

```html
<meta name="generator" content="AMP Plugin v2.1.0-beta2-20210425T015344Z-107e8c3; mode=reader; theme=twentytwenty">
```

to:

```html
<meta name="generator" content="AMP Plugin v2.1.0-beta2-20210425T015344Z-107e8c3; mode=transitional">
```

This is similarly reflected on the settings screen:

![image](https://user-images.githubusercontent.com/134745/115980241-f3fe8b00-a53f-11eb-9ec7-d919fa8af519.png)

QA passed
