### ISSUE TITLE
Missing .editorconfig file

### ISSUE THREAD

**Issue by mitogh** [Automattic/amp-wp#51]
Maybe you should consider the option to add a `.editorconfig`, that should be helpful for somebody else to stick to the same standard you are using for this project and `*.php` files.  

Thank you ! :hand:

**Comment by mjangda** [comment]
I've never used an `. editorconfig` config file but happy to add one if you want to send in a PR.

We're just following <a href="https://make.wordpress.org/core/handbook/best-practices/coding-standards/">WordPress coding standards</a>.
