### ISSUE TITLE
Images breaking out of viewport because of "width:100vw" rule

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/amp-wp#510]
One issue we've noticed is that our images break out of the viewport because of a "width: 100vw" rule assigned:

![image](https://cloud.githubusercontent.com/assets/36432/19163803/482ed93e-8bb2-11e6-94ad-621daddf7202.png)

If I disable the inline style on the image, then the gutter appears as expected:

![image](https://cloud.githubusercontent.com/assets/36432/19163824/5a4116fa-8bb2-11e6-8fa2-0366de539dfa.png)

Because we're using a grid system to provide the gutters uniformly, our markup looks like this:

```
<div class="row">
	<div class="columns">
		<div class="featured-image">
			<?php the_post_thumbnail( 'single-featured-mobile' );
				echo bgr_get_image_caption( get_the_ID() );
			?>
		</div>
	</div>
</div>
```

I don't really want to refactor our AMP styles because we're using the same styles for AMP and mobile, and the styles work as expected on mobile.

What's the best way to disable the `"width:100vw"` rule?

**Comment by mjangda** [comment]
Try `max-width: 100%` on the `amp-img`?

**Comment by danielbachhuber** [comment]
> Try `max-width: 100%` on the `amp-img`?

Huh. I could've sworn I had tried that. Works for me, thanks!
