### ISSUE TITLE
Activating a theme that is also the formerly-chosen Reader theme results in unexpected Reader themes UI

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5102]
## Bug Description

When the active theme ends up being switched to be the same as the Reader theme, the Reader theme section unexpectedly still shows that theme still being chosen for the Reader theme.

## Expected Behaviour

A Reader theme should always be selected when expanding the Reader themes list. Or, if the previously 

The currently active theme should not be the one that is selected. Nor should the currently active theme appear as the chosen theme. Either no theme should be selected or the _Legacy_ reader theme should be selected.

## Steps to reproduce

1. Activate Twenty Twenty as the main theme.
2. Enable Reader mode and select Twenty Nineteen as the Reader theme. Save.
3. Now switch to Standard mode.
4. Activate Twenty Nineteen as the main theme.
5. Access the AMP Settings screen and see that “Twenty Nineteen” is the chosen reader theme, but there is a notice saying it is not available. Also, none off the themes in the list are selected, but in spite of that the "Save Changes" button is not disabled.

## Screenshots

![image](https://user-images.githubusercontent.com/134745/88474377-910d9400-ceda-11ea-9152-001d454dda4a.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed**

With Twenty Nineteen set as the active and Reader theme, when Reader mode is selected, the Legacy theme is set as the default, and the user can save the updated option:

![image](https://user-images.githubusercontent.com/16200219/91239616-99522c80-e72f-11ea-9609-b95fcdb24cee.png)
