### ISSUE TITLE
Selective refresh in AMP Customizer breaks with tree-shaken styles

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5104]
When Twenty Twenty is selected as the Reader theme, and the AMP Customizer is opened, upon first selecting a Custom Logo the image looks large in in the Customizer preview. Upon saving and refreshing, the logo looks smaller as expected. The reason for this is the styles that made the logo smaller were not part of the tree-shaken CSS that were present when the page was first loaded, thus when the `amp-img` for the logo is added, it doesn't get sized properly. The same is true when the logo is removed: the styles for the site title does not have the right styling applied until the preview is manually reloaded.

State | Actual | Expected
------|-------|----------
Once Logo Selected | <img width="1140" alt="logo-added-actual" src="https://user-images.githubusercontent.com/134745/88474691-f8791300-cedd-11ea-9768-cbd123b461ff.png"> | <img width="1140" alt="logo-added-expected" src="https://user-images.githubusercontent.com/134745/88474693-029b1180-cede-11ea-963d-4428ac9fc1bf.png">
Once Logo Removed | <img width="1176" alt="logo-removed-actual" src="https://user-images.githubusercontent.com/134745/88474699-0fb80080-cede-11ea-883d-ab19489ad302.png"> | <img width="1175" alt="logo-removed-expected" src="https://user-images.githubusercontent.com/134745/88474702-147cb480-cede-11ea-8ee2-23deab8b9ae5.png">

The quick fix here is to just force the `custom_logo` setting to use the `refresh` transport as we're already doing for the Custom Header:

```diff
--- a/includes/admin/class-amp-template-customizer.php
+++ b/includes/admin/class-amp-template-customizer.php
@@ -116,6 +116,7 @@ class AMP_Template_Customizer {
                }

                $setting_ids = [
+                       'custom_logo',
                        'header_video',
                        'external_header_video',
                ];
```

However, this issue is going to arise for others as well.

This is in part a regression introduced by #4977. In particular the removal of `allow_dirty_styles` and the introduction of CSS processing in the Customizer. Actually, @pierlon suggested that we should be preventing tree shaking when in the Customizer preview (see https://github.com/ampproject/amp-wp/pull/4977#issuecomment-653264708): and this is what we should do.

When in the Customizer preview, tree shaking should be prevented _and_ the CSS size limit should be suspended (as if the site is in Standard mode).

<del>Also, we may need to do special handling of selectively refreshed partials which contain inline `style` attributes. We should probably skip processing those entirely and allow `!important` to be used.</del> <ins>The sanitized `style[amp-custom]` CSS from the rendered partial just needs to be passed back in the partial.</ins>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed**

With a Reader theme enabled, when a custom logo is set in the AMP Customizer preview:

- The correct styles are not tree-shaken and the styles in the selective refresh partial are retained
- A manual reload of the page is not required to preview the changes
- The preview is styled the same way when selectively and fully refreshing the page
