### ISSUE TITLE
Serve all REST API responses with the HTML response for the settings screen

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5114]
## Bug Description

Currently when accessing the Settings screen, there is a loading spinner while waiting for these two REST API requests to complete:

![image](https://user-images.githubusercontent.com/134745/88603347-80b7ff00-d029-11ea-8b08-ba893bfd8a49.png)

There is then also a momentary flicker where the Reader theme is blank and then populated once the `reader-themes` request completes:

![image](https://user-images.githubusercontent.com/134745/88603379-99281980-d029-11ea-9969-0aa576bfd50a.png)

We can avoid all of this if all three requests are dispatched with the initial response of the settings screen page. This will drastically reduce the page load time and will eliminate the need for the spinner.

This is also what WordPress core does to increase the speed of loading the editor. See the logic it uses to "preload common data":

https://github.com/WordPress/wordpress-develop/blob/9ed92faaca92f66ec9e2979c9d896ddab3e4e993/src/wp-admin/edit-form-blocks.php#L41-L87

See in particular the use of the [`rest_preload_api_request()`](https://developer.wordpress.org/reference/functions/rest_preload_api_request/) function.

## Expected Behaviour

No `fetch` requests should be required to render the initial page.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
**QA passed**

When loading the settings screen, we can see that the initial page load includes the preload middleware with the needed content:

![Image 2020-08-25 at 12 16 59 PM](https://user-images.githubusercontent.com/83631/91162880-fcf73e00-e6cc-11ea-9b46-f78a07c3bba0.png)

We can also see that no additional AJAX request is needed to fully populate the page:

![Image 2020-08-25 at 12 17 06 PM](https://user-images.githubusercontent.com/83631/91162950-15675880-e6cd-11ea-8e43-d04d571d8ed0.png)
