### ISSUE TITLE
Avoid fetching image dimensions over HTTP when possible

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5115]
## Feature description

Fetching an image's dimensions via `FasterImage` over HTTP is resource-intensive. When possible, the AMP plugin should be fetching the dimensions by examining the file from the filesystem. 

We should check to see whether it is more expensive to obtain the dimensions of the image at runtime from the filesystem versus obtaining the dimensions of the image via a transient.

Additionally, when the image actually contains the dimensions in the filename (e.g. `foo-100x200.png`) then this should serve indicate the dimensions without necessitating the request.

Related: #4838.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We also need to verify that images that end up with a `fill` layout (such as images in a Gallery carousel) do not end up getting their dimensions fetched.

**Comment by westonruter** [comment]
The user who most recently [raised the problem](https://wordpress.org/support/topic/image-dimension-creating-problems-in-amp-version/) of images having the fallback dimensions in the page was running WordPress 5.4. I've asked them to upgrade to 5.5 to see if that fixes the issue. If that fixes the issue, I'll bump this down to P2.

**Comment by dhaval-parekh** [comment]
From WordPress 5.5, width and height attributes are automatically added into images in the content by default ([reference](https://core.trac.wordpress.org/ticket/50367)). And already inheriting those that. 

However, for sites with an earlier version than 5.5 or Site as disabled that feature. like,
```
add_filter( 'wp_img_tag_add_width_and_height_attr', '__return_false' );
```
We have to explicitly fetch image dimensions.

Regarding, the performance impact of transient versus runtime from the filesystem or from attachment metadata. below is the time that took to perform a thousand iteration. (Time is in microsecond)

| -                                                           | Run 1    | Run 2    | Run 3    | Average
|-------------------------------------------------------------|----------|----------|----------|-----
| File system.                                                | 0.016174 | 0.014674 | 0.015157 | 0.0153350
| Filesystem with transient ( without object cache )          | 0.044387 | 0.040966 | 0.035533 | 0.0402953
| Filesystem with transient ( with object cache )             | 0.011188 | 0.007476 | 0.007379 | 0.0086810
| Attachment metadata                                         | 0.012651 | 0.013327 | 0.015283 | 0.0137537
| Attachment metadata with transient ( without object cache ) | 0.039617 | 0.035004 | 0.039139 | 0.0379200
| Attachment metadata with transient ( with object cache )    | 0.007282 | 0.007986 | 0.007637 | 0.0076350

**Comment by westonruter** [comment]
I added averages of the 3 runs to the table.

So it looks like the filesystem is 3x faster than transients w/o external object cache is present, but is half the speed of transients with an external object cache. 

Therefore, it seems the best way forward is to fetch the dimensions from the filesystem when `wp_using_ext_object_cache()` is `false`, but continue to use transients when a persistent object cache is being used. This would give the best of both worlds, and it solves the underlying problem of image dimensions filling up the `wp_options` table, at least for images which are not located on remove servers. 

One more consideration comes to mind and that is the speed of accessing images from the filesystem on servers that are using network-attached storage. This could potentially cause filesystem retrieval to be even slower.

**Comment by bartoszgadomski** [comment]
**QA passed**

To test this, I created a simple plugin that inserted two images right after the `<body>` tag:

```
<?php
/**
 * Plugin Name: Test plugin
 */
add_action( 'wp_body_open', function() {
    ?>
    <img src="http://localhost.develop/wp-content/uploads/2021/10/fd5fd028-9e92-34ac-a390-7d1cf53e6cc7.jpg" />
    <img src="http://localhost.develop/wp-content/uploads/2021/10/fd5fd028-9e92-34ac-a390-7d1cf53e6cc7-300x200.jpg" />
    <?php
});
```

Dimensions for both images has been extracted in `extract_by_filename_or_filesystem` method, as expected.
Output of this method was also valid and as expected:

```
[
    "http://localhost.develop/wp-content/uploads/2021/10/fd5fd028-9e92-34ac-a390-7d1cf53e6cc7-300x200.jpg": [
        "width": 300,
        "height": 200,
    ],
    "http://localhost.develop/wp-content/uploads/2021/10/fd5fd028-9e92-34ac-a390-7d1cf53e6cc7.jpg": [
        "width": 1203,
        "height": 802,
    ]
]
```

Well done 👍
