### ISSUE TITLE
Update onboarding wizard stepper design elements

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#5127]
## Feature description

There are a number of small changes we'd like to make to the UI. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

A. Shrink width between letters and convert `AMP` text to font instead of SVG
B. Shorten text to `Official WordPress Plugin` and shrink text to 16px
C. Shrink spacing between heading and logo
D. Shrink width and make border 2px
E. Left-align all elements

<img width="971" alt="Screen Shot 2020-07-29 at 11 35 22 AM" src="https://user-images.githubusercontent.com/3411173/88839220-9e06dd80-d18f-11ea-8454-37c1a64d8b33.png">

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
@amedina and @westonruter and @johnwatkins0 this is a bit different then we discussed. Can you review the changes and let me know if we should tweak further?

**Comment by westonruter** [comment]
This looks great to me.

**Comment by amedina** [comment]
Yeah; looks good!

**Comment by jwold** [comment]
Validated in QA. Good to go.
