### ISSUE TITLE
Delete parsed stylesheets from amp_validated_url posts once stale

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5132]
## Feature description

Originally raised in https://github.com/ampproject/amp-wp/issues/4779#issuecomment-666419703.

Two users recently have reported issues with the `_amp_stylesheets` postmeta being particularly huge:

* https://wordpress.org/support/topic/huge-_amp_stylesheets-postmeta/
* https://wordpress.org/support/topic/database-increasing-fast-because-full-css-for-each-post/

In #4779 I proposed deleting the `amp_validated_url` posts once they become stale (i.e. a week after they have been generated). This can be problematic, however, when there are `amp_validation_error` terms which have a status assigned for removed/kept and reviewed, since once no associated `amp_validated_url` posts exist, the terms can then be deleted when doing “Clear Empty”.

So a middle ground here is this: as opposed to auto-deleting the `amp_validated_url` posts after a week, what we can do is just purge the `_amp_stylesheet` postmeta. When this is done, the stylesheets metabox can just say something like “re-validate to obtain latest stylesheet data” (it already does). In practice users will rarely see this because the “Validate” link in the admin bar already does this re-validation.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
We may save a summary of the last CSS state (e.g. percentage of CSS budget used), indicate that the results are stale (i.e. purged) and ask for revalidate to obtain the full information again.

**Comment by westonruter** [comment]
We could, but since the results are stale it's likely the percentage is no longer accurate. I think it's better to just ask them to re-validate.

**Comment by westonruter** [comment]
Importantly, the CSS percentage in the admin bar is “live” so it is not impacted here.

**Comment by pierlon** [comment]
**QA Passed**

- Stylesheets metabox on Validated URL post page shows an appropriate message encapsulating the reason for the deleted stylesheet postmeta
- In the Validated URLs list, `n/a` is shown in the CSS Usage column when there is no accompanying stylesheet postmeta
- Stale stylesheet postmeta older than a week is set to be garbage collected once every hour
