### ISSUE TITLE
Currently active theme is used if Reader theme is deleted

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#5136]
## Bug Description

When Reader mode is activated along with a Reader theme and said theme is deleted (for whatever reason), the currently active theme is used to serve AMP pages (essentially operating as if in Transitional mode). This potentially unwanted behavior should be made aware to the user through an admin notice and the Reader legacy theme should be used as a fallback when such cases occur.

Related: #5048

## Expected Behaviour

- The user should be made aware that the chosen Reader theme cannot be found via an admin notice
- The legacy Reader theme should be used as a fallback, instead of using the currently active theme

## Steps to reproduce

1. Open the AMP settings page
2. In a separate tab, delete the Twenty Twenty theme
3. Back in the tab with the AMP settings, choose Twenty Twenty as the Reader theme and save settings
4. Browse to an AMP page and see that the currently active theme is used to serve the page

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Milestoning for 2.0 just in case we can handle the hardening for the big release.

**Comment by jwold** [comment]
Taking a stab at the notification to kickoff the conversation. 

<img width="1309" alt="Screen Shot 2020-08-05 at 10 20 21 AM" src="https://user-images.githubusercontent.com/3411173/89443576-50e1b900-d705-11ea-94e6-40fbdde95da7.png">

cc @amedina and @westonruter

**Comment by amedina** [comment]
Where is this notice going to be displayed? Main dashboard?

**Comment by westonruter** [comment]
Humm. Maybe on the Themes screen and the AMP Settings screen? Showing it everywhere would probably be excessive.

**Comment by westonruter** [comment]
Aside: It should say “Legacy” rather than “Classic”

**Comment by amedina** [comment]
Agree on both counts.

**Comment by johnwatkins0** [comment]
This is passing QA. In this scenario, when the reader theme is deleted, the site falls back to the legacy theme, which is the expected behavior.
