### ISSUE TITLE
Active theme setting importing fails for “Display Site Title and Tagline”

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5137]
## Bug Description

Discovered when testing #5041 for #5039. When importing the setting for “Display Site Title and Tagline” so that the title and tagline are hidden (`blank`), they cannot be re-displayed in the Customizer during that Customizer session.

The issue is likely due to core Customizer logic here: https://github.com/WordPress/wordpress-develop/blob/6d3207d564c6eb19de5d0f0532b30903a97a533a/src/js/_enqueues/wp/customize/controls.js#L9031-L9051

## Expected Behaviour

The title and tagline should be able to be re-shown after doing an import that undisplayed them.

## Steps to reproduce

1. Set the active theme to Twenty Sixteen and the Reader theme to Twenty Fifteen
2. In the primary Customizer, uncheck the "Display Site Title and Tagline" control in the Site Identity section. Publish changes.
3. Open the AMP Customizer (for the Twenty Fifteen theme).
4. Click Import, including “Display Site Title and Tagline”
5. Notice the title and tagline disappear from the preview.
6. Open the Site Identity section and now try re-checking the checkbox.
7. Notice that the Title and Tagline do not re-appear.

To regain the ability to toggle the Title and Tagline, you have to publish changes and reload the Customizer.

## Screenshots

<img width="928" alt="twentysixteen-active-theme-no-display-title-and-tagline" src="https://user-images.githubusercontent.com/134745/89001233-8114fc00-d2ae-11ea-9601-53ecc8ca8d90.png">

<img width="707" alt="twentyfifteen-reader-initial-yes-display-title-and-tagline" src="https://user-images.githubusercontent.com/134745/89001284-a1dd5180-d2ae-11ea-8d3f-533caa176bc7.png">

<img width="705" alt="twentyfifteen-reader-import-display-none-title-tagline" src="https://user-images.githubusercontent.com/134745/89001257-8ffbae80-d2ae-11ea-934c-64ca9f16dcb7.png">

<img width="705" alt="twentyfifteen-reader-imported-display-none-now-cannot-reenable" src="https://user-images.githubusercontent.com/134745/89001304-af92d700-d2ae-11ea-8f99-32460ca28762.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed**

After importing the unchecked "Display Site Title and Tagline" control from the primary theme, the Title and Tagline settings do appear after rechecking the control. The changes do not have to be published and the page refreshed to see the updated preview.
