### ISSUE TITLE
Tighten up styling of Plugin Suppression table

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5145]
Given this screenshot of the Plugin Suppression table in 2.0.0-beta2:

![image](https://user-images.githubusercontent.com/134745/89094029-c3a10c00-d374-11ea-9f6a-0af964e2ba17.png)

There is room for improvement. Namely:

1. A suppressed plugin should have the blue background styling like active plugins do on the plugin list table. Only plugins which have not been suppressed which also have validation errors reported should be shown with an orange background.
2. The `line-height` currently being used for text margins (and vertical centering) is not working as seen here when the line wraps. This issue is particularly grave on a mobile viewport.
3. There is a 4px gap in the row borders (technically `box-shadow`) when an orange border is not present. That should be removed.

For reference, the suppressed plugin rows should be styled with colors like the active Gutenberg plugin here:

![image](https://user-images.githubusercontent.com/134745/89094106-84bf8600-d375-11ea-8744-0ae68f8a62a1.png)

**Comment by schlessera** [comment]
**QA Passed**

![Image 2020-08-25 at 1 57 53 AM](https://user-images.githubusercontent.com/83631/91107799-7283ef80-e676-11ea-9d44-6027b706f617.png)

We should at a later point discuss the color palette, as it is not consistent. For this particular PR, for example, we're combining the highly saturated blue from the AMP brand colors with the muted, earthy orange from the WP color palette, which is not a proper combination.

Not a blocker for v2 release now, though.

**Comment by westonruter** [comment]
> We should at a later point discuss the color palette, as it is not consistent. For this particular PR, for example, we're combining the highly saturated blue from the AMP brand colors with the muted, earthy orange from the WP color palette, which is not a proper combination.

You're right. I kinda mashed together AMP branded colors with WP List Table colors.
