### ISSUE TITLE
JS error on settings screen due to _.find not being a function

### ISSUE THREAD

**Issue by PaolaBozhilova** [Automattic/amp-wp#5147]
## Bug Description

Can't select Reader mode, either through the Onboarding Wizard or the Settings Screen.

## Steps to reproduce

**Onboarding Wizard**
1. Go to AMP
2. Click on AMP configuration wizard
3. Click next button until the mode selection appears. Choose the Reading mode
4. See error "The setup wizard has experienced an error.
_.find is not a function Return to AMP settings."

## Screenshots

![image](https://user-images.githubusercontent.com/12434611/89094349-9df32180-d3cb-11ea-84e2-db09cb820612.png)

**Settings Screen**
1. Go to AMP
2. Click on Settings
3. Click on Reader radio button
4. See error the settings screen disappears and the default mode remains selected - Transitional mode

## Screenshots

![image](https://user-images.githubusercontent.com/12434611/89094488-2b834100-d3cd-11ea-9ae8-e98790aaae8b.png)

## Additional context

 - WordPress version: Версия 5.4.2
 - Plugin version: 2.0.0-beta2

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@PaolaStoyanova Thank you for testing! 

Please share your Site Health info with us. You can do so privately via this form: https://forms.gle/PySNjhhxPLrJU6F1A

There appears to be a plugin compatibility issue and the Site Health info will help us to identify it.

**Comment by felixarntz** [comment]
Potentially related is this problem we had in Site Kit: https://github.com/google/site-kit-wp/issues/1141#issuecomment-588556520

**Comment by westonruter** [comment]
@PaolaStoyanova would you please test a fix in the build linked here: https://github.com/ampproject/amp-wp/pull/5164#issuecomment-668677729.

**Comment by PaolaBozhilova** [comment]
@westonruter no problem of course! The problem is the same, only the message is different.
-  development build
![image](https://user-images.githubusercontent.com/12434611/89507947-e187ca00-d7d5-11ea-8f33-6e194ba818b3.png)
-  production build
![image](https://user-images.githubusercontent.com/12434611/89508670-eac56680-d7d6-11ea-979b-5e30a7dee6e4.png)

**Comment by westonruter** [comment]
@PaolaStoyanova Thank you for the update. For some reason the [`Array#find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) is not defined. Are you by chance using Internet Explorer?

**Comment by westonruter** [comment]
Given that you're seeing `M.find` as not being defined here, it could be that minification just by chance resulted in `_` being the variable reported when you first reported the issue, and so the problem may not be due to Lodash being incorrectly polyfilled but rather because `Array.prototype.find` is not defined.

**Update:** Actually, I see that `wp-polyfill.js` does actually polyfill `Array.prototype.find`. So it may indeed by a polyfill problem.

**Comment by westonruter** [comment]
Update: We believe to have found the issue. Commit: https://github.com/ampproject/amp-wp/pull/5164/commits/55e297f480fca48b749ba61778f1fe413308b5fb.

Updated build available: https://github.com/ampproject/amp-wp/pull/5164#issuecomment-668677729

**Comment by westonruter** [comment]
@PaolaStoyanova Are you filtering `amp_reader_themes` by chance?

**Comment by westonruter** [comment]
I've merged the pull request with what we believe will fix issue. 

Please download the [latest development build](https://github.com/ampproject/amp-wp/wiki/Development-Builds) from the `develop` branch to re-test: https://storage.googleapis.com/ampwp_github_artifacts/refs/heads/develop/dev/amp.zip

If the issue is still not fixed, we'll re-open this issue.

**Comment by PaolaBozhilova** [comment]
@westonruter  I don't use Internet Explorer and I don't filtering by amp_reader_themes, but the good news is that it works! The problem is solved! Thanks!

**Comment by westonruter** [comment]
That is very great to hear! Thank you so much for testing and reporting this issue.
