### ISSUE TITLE
Services initialize even when amp_is_enabled is filtered to false

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5152]
## Bug Description

As discovered in https://github.com/ampproject/amp-wp/issues/2817#issuecomment-667851927, when `amp_is_enabled` is filtered to be `false`, the services will still be initialized.

For example, on a site in Reader mode with Mobile Redirection enabled, if I add this plugin code:

```php
add_filter( 'amp_is_enabled', function ( $is_enabled ) {
	if ( isset( $_GET['geo_mashup_content'] ) ) {
		$is_enabled = false;
	}
	return $is_enabled;
} );
```

When I try accessing a post with a mobile user agent when the URL has `?geo_mashup_content=1`, I will unexpectedly get redirected to `?geo_mashup_content=1&amp=1`. Once redirected, however, the page is _not_ AMP since it has been disabled.

Notice that this filter is applied at `after_setup_theme` action:

https://github.com/ampproject/amp-wp/blob/b8661f309e7e9f0f35df739bcc3993e8dd5a0e86/includes/amp-helper-functions.php#L219-L234

The fix here, although not fully backwards-compatible, is to move the `amp_is_enabled` filter to apply in `amp_bootstrap_plugin`. In order to ensure that plugins have a chance to filter `amp_is_enabled`, then `amp_bootstrap_plugin` would also need to run at `plugins_loaded`.

## Expected Behaviour

Filtering `amp_is_enabled` should be respected by the services.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@douglasvb FYI: The aforementioned [gist plugin](https://gist.github.com/westonruter/c3d4d73418b310f12d3cba7245fccebc) I wrote for you last year (ref. your [support topic](https://wordpress.org/support/topic/shortcodes-for-geo-mashup-not-working/)) has been updated to make use of the `amp_is_enabled` filter. This will need to be changed when updating the AMP plugin to v2.0.

**Comment by westonruter** [comment]
Update: Using the `amp_is_enabled` filter will not be strictly required here. With #5202, AMP processing will not happen if the rendered template does not trigger standard template actions (e.g. `wp_head` and `wp_footer`).

**Comment by pierlon** [comment]
**QA Passed**

The list of services are not registered nor initialized when `amp_is_enabled` is filtered to `false`.
