### ISSUE TITLE
Boolean attributes erroneously flagged as validation errors when name copied as value

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5156]
## Bug Description

In HTML boolean attributes can leave off the value entirely, for example `noloading`: 

```html
<amp-img src="https://amp.dev/static/img/icons/icon-512x512.png" width="200" height="200" noloading></amp-img>
```

For compatibility with XHTML, as I recall, the XML-compatible way to achieve the same thing (where values are required) is just to copy the attribute name as the value, like so: 

```html
<amp-img src="https://amp.dev/static/img/icons/icon-512x512.png" width="200" height="200" noloading="noloading"></amp-img>
```

This is [valid AMP](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzdHlsZSBhbXAtY3VzdG9tPgogICAgaDEgewogICAgICBtYXJnaW46IDFyZW07CiAgICB9CiAgPC9zdHlsZT4KPC9oZWFkPgo8Ym9keT4KICA8YW1wLWltZyBzcmM9Imh0dHBzOi8vYW1wLmRldi9zdGF0aWMvaW1nL2ljb25zL2ljb24tNTEyeDUxMi5wbmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIiBub2xvYWRpbmc9Im5vbG9hZGluZyI+PC9hbXAtaW1nPgo8L2JvZHk+CjwvaHRtbD4=):

![image](https://user-images.githubusercontent.com/134745/89216659-a1c7a500-d57f-11ea-9437-46c9799d15d9.png)

Nevertheless, the AMP plugin is flagging it as an error:

![image](https://user-images.githubusercontent.com/134745/89216581-7e045f00-d57f-11ea-9ab9-aba35658c35d.png)

For more see [§Boolean attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) in the HTML spec:

> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

See also the [JS code](https://github.com/ampproject/amphtml/blob/60c34f6742e1f9aca148a2a23b9c82825e0b2833/validator/engine/validator.js#L5448-L5453) in the AMP Validator:

```js
    // Special case for foo=foo. We consider this a match for a dispatch key
    // of foo="" or just <tag foo>.
    if (attrName === attrValue) {
      tagSpecIds.push.apply(
          tagSpecIds, this.matchingDispatchKey(attrName, '', mandatoryParent));
    }
```

This came up when trying to improve AMP-compatibility for the Web Stories plugin. See https://github.com/google/web-stories-wp/pull/3621.

## Expected Behaviour

Boolean attributes with a value matching the name should not be flagged as a validation error.

## Steps to reproduce

1. Enable Developer Tools
2. Add a Custom HTML block containing: `<amp-img src="https://amp.dev/static/img/icons/icon-512x512.png" width="200" height="200" noloading="noloading"></amp-img>`
3. Save draft.
4. See validation error.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed**

Given the following HTML snippet

```html
<amp-img src="https://amp.dev/static/img/icons/icon-512x512.png" width="200" height="200" noloading="noloading"></amp-img>
```

A validation error is not raised for the `noloading` attribute when the value is the same as the attribute name.
