### ISSUE TITLE
Comments link in AMP endpoint, if off in WP

### ISSUE THREAD

**Issue by neotrope** [Automattic/amp-wp#516]
Kind of a bug; not sure if already reported. in v0.4 comments box link shown at bottom of AMP endpoint, even if "comments" are not enabled in WP settings under 4.6.1.  (e.g., 'unchecked' = 'off' in WP, obviously)

Why have link to comments if there are no comments?

Perhaps check WP setting for that, or add option for on/off on AMP template.

**Comment by mjangda** [comment]
Good catch! Can you see if #517 fixes the issue?
