### ISSUE TITLE
Provide counterpart to view with AMP disabled link

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#5171]
In standard mode there is a link that allows user to see the page with AMP disabled. That is achieved via a query parameter. However, there is no way for the user to go back to the AMP version other than removing the query parameter manually. 

The admin bar should keep an AMP "entry point" with a link to switch back.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Video showing behavior from @jwold: https://v.usetapes.com/3IAmwnfXZ5
