### ISSUE TITLE
amp_post_template_meta_parts filter is missing

### ISSUE THREAD

**Issue by finalhit** [Automattic/amp-wp#519]
Filter "amp_post_template_meta_parts" existed in version 0.3.

**Comment by mjangda** [comment]
The 0.4 template replaced the existing filter with `amp_post_article_header_meta` and `amp_post_article_footer_meta` (as the meta parts were moved around)

**Comment by finalhit** [comment]
Please update https://github.com/Automattic/amp-wp/blob/master/readme.md
