### ISSUE TITLE
Update to validator with usability improvements

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#5191]
## Feature description

---------------

Did an initial review of the validation screen, and wanted to open an issue with a number of smaller changes that we could review.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update the arrows to the default WordPress style (color and size) https://d.pr/i/g69Bbe
* These buttons don't dynamically update: https://d.pr/i/wB86G0
* Update "removed" statuses to be green: https://d.pr/i/ca0Elg. Note: I’m also considering an option that is more accessibility friendly, what do you think? https://d.pr/i/BEAqxW
* Sort button not sorting: https://d.pr/i/EWEzXW
* Consider updating these notifications to the kind that toggle on/off based on just pressing the info button: https://d.pr/i/XjuXHj
* Consider removing "sources", since it's not a sort type: https://d.pr/i/KKIk12. 

Related to #2316 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
cc @kmyram on feedback for accessibility

**Comment by jwold** [comment]
cc @amedina and @westonruter for validation on the validator issues 😀

**Comment by westonruter** [comment]
@delawski This could serve as a guide for what aspects should be adjusted while porting the Validated URL screen over to use React components (#2316).
