### ISSUE TITLE
Not enough space for buttons in onboarding wizard

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5193]
In the onboarding wizard, there is not enough space for the Close, Previous, and Next/Customize buttons. On the mobile viewport, the “Close” button should be moved to the top-right corner of the UI. This would even allow for showing the SVGs:

Before | After
-------|------
![congrats-mobile-before](https://user-images.githubusercontent.com/134745/89593627-773a4e00-d804-11ea-918b-c2022552ce25.png) | ![congrats-mobile-after](https://user-images.githubusercontent.com/134745/89593878-25de8e80-d805-11ea-9dd5-cf0ba7726101.png)

The “Customize Theme” button text will be replaced with “Customize” in #5192.

The media query could be removed from:

https://github.com/ampproject/amp-wp/blob/2ffc6609fdb9bf74cdd4b1b772816eef7860ae71/assets/src/css/core-components.css#L13-L23

## Steps to reproduce

1. Open DevTools and set device to Moto G4
2. Open onboarding wizard
3. Select Reader theme
4. Go to Done screen
5. Notice constrained buttons

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
I like this change, simplifies and makes it easier to read.
