### ISSUE TITLE
allow amp-story-player

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#5205]
## Bug Description

I'm testing the Web Stories plugin, I'm not sure if I should raise the issue here or at the Web Story repo but I'm getting a validation error DISALLOWED_TAG  for amp-story-player when I add a web story on my posts.

## Expected Behaviour

AMP story should be a valid tag?

## Steps to reproduce

1. Create a new web story
2. Add a web story in a post
3. Try to validate the post

## Screenshots

![Screen Shot 2020-08-10 at 08 51 53](https://user-images.githubusercontent.com/330792/89761666-cfb06a80-dae6-11ea-8c7a-253825a758ba.png)

## Additional context

 - WordPress version: 5.4.2
 - Plugin version: 1.5.5
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Standard
 - PHP version: 7.3
 - OS: Mac
 - Browser: chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Hey @fellyph !

Thanks for the bug report. This is a known issue and should be resolved in the latest v2.0 beta release. See https://github.com/ampproject/amp-wp/pull/5075

**Comment by schlessera** [comment]
Fixed via https://github.com/ampproject/amp-wp/pull/5075

**Comment by schlessera** [comment]
@fellyph If you want to test with the new beta, you can find the latest release here:
https://github.com/ampproject/amp-wp/releases/tag/2.0.0-beta3

**Comment by fellyph** [comment]
Hi @schlessera  

I read the v2.0 milestone looks great I will test it.
 
Thanks!
