### ISSUE TITLE
Generate documentation reference markdown by parsing source code

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5206]
## Feature description

The reference documentation should be generated from source code, instead of manually maintained, to ensure it is always up-to-date.

This can be done using https://github.com/WordPress/phpdoc-parser, which produces JSON output. Turning the JSON output into templated markdown should then be relatively straight-forward.

This depends on https://github.com/ampproject/amp-wp/issues/5119 to make sure we clearly communicate what the scope of the public API of the plugin is.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
In #5218 the source code (contained in the `src` and `includes` directories) has been tagged with the necessary `@internal` tags to identify what should be omitted from the generated documentation reference.
