### ISSUE TITLE
Request: clipboard-friendly validation errors

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5209]
### The problem

While debugging an AMP issue on a client site, I was able to reproduce the error using the validation tools. I wanted to share the error with a colleague in a comment on GitHub, so I copied everything from the "Information" details list heading through the "Source Stack" content. When I pasted it, it came out looking like this:

```

InformationAMP allows a specific set of elements and attributes on valid AMP pages. Learn about the AMP HTML specification. If an element or attribute is not allowed in AMP, it must be removed for the page to be cached and eligible for prerendering.If all invalid markup is “removed” the page will be served as AMP. However, the impact that the removal has on the page must be assessed to determine if the result is acceptable. If any invalid markup is “kept” then the page will not be served as AMP.Error codeATTR_REQUIRED_BUT_MISSINGMissing attributessrcElement attributesclassyoutube-embedwidth780height439data-srchttps://www.youtube.com/embed/[redacted];Node nameiframeParent elementspanSources Source stack (2)#1Filter:the_contentPost ID:2229Post Type:Post (post)Sources: Source stack (13)#2Block Name:Custom HTML (core/html)Post ID:2229Block Index:0 | class | youtube-embed | width | 780 | height | 439 | data-src | https://www.youtube.com/embed/[redacted] | allowfullscreen | true | style | border:0; | #1 | Filter: | the_content | Post ID: | 2229 | Post Type: | Post (post) | Sources: | Source stack (13) | #2 | Block Name: | Custom HTML (core/html) | Post ID: | 2229 | Block Index: | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
youtube-embed
780
439
https://www.youtube.com/embed/[redactetd]
true
border:0;
the_content
2229
Post (post)
Source stack (13)
Custom HTML (core/html)
2229
0
Select All


```

### Proposed feature

For the next iteration of AMP validation tools, I suggest adding a "Copy to Clipboard" button that provides a clipboard-friendly version of this error detail to make the info more shareable across dev teams. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User can copy one or more errors
* Errors are copied in a shareable format (pretty-printed JSON for human readability)

## Implementation brief

* 

## QA testing instructions

* Create a post with one or more validation errors
* Visit the AMP Validated URL screen for the URL
* Click the "Copy to clipboard" button that appears in a single error row when you hover over the title and paste the output into a document to verify the JSON object
* Select one or more posts and in the bulk edit row of buttons click "Copy error details to clipboard." Paste the result into a document and verify the JSON array of objects.

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Agreed! This is closely related to #4562, and may be one and the same.

**Comment by westonruter** [comment]
There needs to be two buttons: one to copy an individual error details to the clipboard, and another to copy all the error details for a given validated URL.

**Comment by westonruter** [comment]
Should we have the format be just pretty-printed JSON?

**Comment by jwold** [comment]
Discussion from our call:

"Copy error details" button, discuss format of that error. Maybe a JSON representation that's the same as the underlying representation stored in the database. We need some representation that the user can paste into support forum. Site health has Markdownesque representation that's somewhat helpful.

**Comment by westonruter** [comment]
Given this validation error:

![image](https://user-images.githubusercontent.com/134745/91882348-abecca00-ec37-11ea-8958-d7e4d5c729a5.png)

The internal JSON representation is:

```json
{
    "node_name": "script",
    "parent_name": "body",
    "code": "DISALLOWED_TAG",
    "type": "js_error",
    "node_attributes": [],
    "text": "document.write(\"Bad action!!!\");",
    "node_type": 1,
    "sources": [
        {
            "type": "plugin",
            "name": "bad-hooks",
            "file": "bad-hooks.php",
            "line": 13,
            "function": "Bad\\Hooks\\add_script_to_footer",
            "hook": "wp_footer",
            "priority": 10
        }
    ]
}
```

This seems like a perfectly acceptable format for users to copy and share.

**Comment by pierlon** [comment]
Would we also want to include the state of the error (kept, reviewed etc.)?

**Comment by westonruter** [comment]
Great point. Yes it should.

**Comment by westonruter** [comment]
We should probably have a button with each error, perhaps in the row actions for each could have a "Copy to clipboard". Then there should be a button to copy all validation errors to the clipboard as well, which will then satisfy #4562.

**Comment by johnwatkins0** [comment]
Screenshot of where I am placing the two elements currently.

<img width="560" alt="Screen Shot 2020-10-09 at 12 28 03 PM" src="https://user-images.githubusercontent.com/9020968/95613695-f7f70f80-0a2a-11eb-9351-e9f2a0103c19.png">

Debating with myself whether the phrase "to clipboard" needs to be there.

**Comment by westonruter** [comment]
> Debating with myself whether the phrase "to clipboard" needs to be there.

Yes, I think “to clipboard” is needed.

> Screenshot of where I am placing the two elements currently.

I think the button to copy all errors might be problematic there, especially given the bulk action buttons can appear:

![image](https://user-images.githubusercontent.com/134745/95616290-6b465480-0a1e-11eb-9750-e97d178ed834.png)

Perhaps the button could be placed _under_ the validation errors table, or else inside of the Status metabox?

![image](https://user-images.githubusercontent.com/134745/95616704-16570e00-0a1f-11eb-9da5-fb62ae894b8e.png)

I think instead of “Copy error details to clipboard”, this button can say “Copy all errors to clipboard”

**Comment by johnwatkins0** [comment]
<img width="892" alt="Screen Shot 2020-10-12 at 12 53 24 PM" src="https://user-images.githubusercontent.com/9020968/95776451-ff682400-0c89-11eb-8f2c-2eb7ed4706df.png">

@westonruter What do you think about adding the "Copy all" button to the bulk actions, as shown above? It does add more clutter but makes it possible to selectively copy any subset of errors on the page, which I think is useful.

**Comment by westonruter** [comment]
Yes, I like that. Good one. Also, the clutter will be reduced with #5431. So it would make sense to do those both in the same PR.

**Comment by westonruter** [comment]
**QA passed**

I activated Contact Form 7, added a form to a post, and published. AMP validation errors were reported. When going to the validated uRL screen, I was able to copy one error to the clipboard:

![image](https://user-images.githubusercontent.com/134745/115980337-e4cc0d00-a540-11eb-91f1-97e6bf6fbb93.png)

```json
{
	"node_name": "script",
	"parent_name": "body",
	"code": "DISALLOWED_TAG",
	"type": "js_error",
	"node_attributes": {
		"id": "contact-form-7-js-extra"
	},
	"text": "\nvar wpcf7 = [];\n",
	"node_type": "ELEMENT",
	"sources": [
		{
			"type": "core",
			"name": "wp-includes",
			"file": "script-loader.php",
			"line": 2004,
			"function": "wp_print_footer_scripts",
			"hook": "wp_footer",
			"priority": 20
		},
		{
			"type": "core",
			"name": "wp-includes",
			"file": "script-loader.php",
			"line": 1994,
			"function": "_wp_footer_scripts",
			"hook": "wp_print_footer_scripts",
			"priority": 10
		},
		{
			"type": "plugin",
			"name": "contact-form-7",
			"file": "includes/controller.php",
			"line": 36,
			"function": "{closure}",
			"hook": "wp_enqueue_scripts",
			"priority": 10,
			"dependency_type": "script",
			"extra_key": "data",
			"text": "var wpcf7 = [];",
			"handle": "contact-form-7"
		},
		{
			"type": "core",
			"name": "wp-includes",
			"file": "script-loader.php",
			"line": 2021,
			"function": "wp_enqueue_scripts",
			"hook": "wp_head",
			"priority": 1,
			"dependency_type": "script",
			"extra_key": "data",
			"text": "var wpcf7 = [];",
			"handle": "contact-form-7"
		}
	],
	"removed": true,
	"reviewed": false
}
```

And I was able to select all and copy all to the clipboard:

![image](https://user-images.githubusercontent.com/134745/115980350-f6151980-a540-11eb-8195-182e328b980a.png)

```json
[
	{
		"node_name": "script",
		"parent_name": "body",
		"code": "DISALLOWED_TAG",
		"type": "js_error",
		"node_attributes": {
			"id": "contact-form-7-js-extra"
		},
		"text": "\nvar wpcf7 = [];\n",
		"node_type": "ELEMENT",
		"sources": [
			{
				"type": "core",
				"name": "wp-includes",
				"file": "script-loader.php",
				"line": 2004,
				"function": "wp_print_footer_scripts",
				"hook": "wp_footer",
				"priority": 20
			},
			{
				"type": "core",
				"name": "wp-includes",
				"file": "script-loader.php",
				"line": 1994,
				"function": "_wp_footer_scripts",
				"hook": "wp_print_footer_scripts",
				"priority": 10
			},
			{
				"type": "plugin",
				"name": "contact-form-7",
				"file": "includes/controller.php",
				"line": 36,
				"function": "{closure}",
				"hook": "wp_enqueue_scripts",
				"priority": 10,
				"dependency_type": "script",
				"extra_key": "data",
				"text": "var wpcf7 = [];",
				"handle": "contact-form-7"
			},
			{
				"type": "core",
				"name": "wp-includes",
				"file": "script-loader.php",
				"line": 2021,
				"function": "wp_enqueue_scripts",
				"hook": "wp_head",
				"priority": 1,
				"dependency_type": "script",
				"extra_key": "data",
				"text": "var wpcf7 = [];",
				"handle": "contact-form-7"
			}
		],
		"removed": true,
		"reviewed": false
	},
	{
		"node_name": "script",
		"parent_name": "body",
		"code": "DISALLOWED_TAG",
		"type": "js_error",
		"node_attributes": {
			"src": "https://wordpress-stable.lndo.site/wp-content/plugins/contact-form-7/includes/js/index.js?ver=__normalized__",
			"id": "contact-form-7-js"
		},
		"node_type": "ELEMENT",
		"sources": [
			{
				"type": "plugin",
				"name": "contact-form-7",
				"file": "includes/controller.php",
				"line": 36,
				"function": "{closure}",
				"hook": "wp_enqueue_scripts",
				"priority": 10,
				"dependency_type": "script",
				"handle": "contact-form-7"
			},
			{
				"type": "core",
				"name": "wp-includes",
				"file": "script-loader.php",
				"line": 2021,
				"function": "wp_enqueue_scripts",
				"hook": "wp_head",
				"priority": 1,
				"dependency_type": "script",
				"handle": "contact-form-7"
			},
			{
				"type": "core",
				"name": "wp-includes",
				"file": "script-loader.php",
				"line": 2004,
				"function": "wp_print_footer_scripts",
				"hook": "wp_footer",
				"priority": 20
			},
			{
				"type": "core",
				"name": "wp-includes",
				"file": "script-loader.php",
				"line": 1994,
				"function": "_wp_footer_scripts",
				"hook": "wp_print_footer_scripts",
				"priority": 10
			}
		],
		"removed": true,
		"reviewed": false
	}
]
```
