### ISSUE TITLE
Infrastructure: allow setting priority level for registration actions

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5215]
## Feature description

Currently when a service implements `Registerable` it must have a `get_registration_action` method to to tell the plugin when to load the class. Ideally we would also be able to set a registration priority. We're able to work around this by registering the service on an earlier action and using `add_action` to kick things off on the later action, but it would be nice to be able to set the priority with `get_registration_action` -- e.g. perhaps `get_registration_action` could have the option of returning an array, with the action at index 0 and the priority at index 1. 

Example use case:
- My service class needs to do something that's usually done on the `admin_menu` hook, but it needs to run after another class has already done its work on the `admin_menu` hook.
- Currently I don't think we can guarantee that the new class will run after the old class, so I return `admin_init` from `get_registration_action`, and in the `register` method I add an `admin_menu` action hook callback with my desired priority level.
In this case, if my class were able to return the priority level along with the action from `get_registration_action`, then my class could have one or two fewer methods.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Also a `get_registration_priority` method could be used, but that would require updating all `Delayed` services to add this.
