### ISSUE TITLE
Facilitate themes marking themselves as AMP-compatible

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5222]
## Feature description

Currently we have `add_theme_support('amp')` as the method by which a theme indicates it is AMP-compatible. There's a big problem with this, however: it requires that the theme first be activated to determine if it is AMP-compatible. It's an imperative way to indicate AMP support rather than a declarative way to do so. This is most problematic now with the introduction of Reader themes: we can't easily list all installed themes which are AMP-compatible. We instead provide a `amp_reader_themes` filter for plugins to add themes to the list. 

However, what if there was a way for a theme to declaratively indicate it is AMP-compatible? Then no `amp_reader_themes` filter would be needed. 

One way this could be done is via a theme tag in the `style.css` metadata. This is problematic, however, because the allowed theme tags are a [fixed set](https://make.wordpress.org/themes/handbook/review/required/theme-tags/).

As an alternative to this, we could introduce recognition of a separate `AMP` metadata field in `style.css` to go alongside [standard fields](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/#explanations) such as `Theme Name`, `Author`, and `Description`. 

If someone wanted to use the [AMP-compatible Noto Simple](https://gist.github.com/westonruter/b904977a296da091584a7a2264df2882) child theme, they could merely install the parent theme along with the child theme, and if the child theme had `AMP` meta field in its `style.css`, then it could automatically be included in the list of Reader themes.

For prior art here, the [GitHub Updater plugin](https://github.com/afragen/github-updater) also introduces a custom theme metadata field for `GitHub Theme URI`. So we could do the same. Even though this field is not standard, it is apparently allowed by themes submitted to the directory, since 24 themes have it: https://wpdirectory.net/search/01EFG0A4FEWJDDJS7XWXVSRD15

What remains to be seen, however, is how efficiently we can query themes that have this AMP field.  I think we'd have to get all themes via `wp_get_themes()` and then for each one, parse the `style.css` to obtain the new field, and then filter out the ones that lack the field.

What also remains to be seen is what the field should be called and what its value should be. It could be as simple as:

```
AMP: true
```

This would be the same as if a theme had done `add_theme_support('amp')`. It means that the theme works in _either_ Standard or Transitional modes.

Or we could provide some hints as to what kind of compatibility it has. For example, certain themes only have support for legacy Reader mode. So perhaps in that case:

```
AMP: legacy
```

I don't think anything more is needed than that.

When a theme has this flag, then it should behave the same as if the theme had `add_theme_support('amp')`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
+1 On this. Let's add it.

**Comment by westonruter** [comment]
We'd need to support probably three flavors of the key: `AMP Compatibility`, `AMP Compatible`, and `AMP`. This is important given the lack of type checking.

For the value of the field, both `theme-support` and `true` can be synonymous, with `legacy` being the other option.

This meta key could also be eventually used in plugins as well to indicate AMP-compatibility, where currently there is no plugin equivalent to `add_theme_support('amp')`. In a plugin context, the value of `legacy` would indicate the plugin only has hooks for legacy Reader mode post templates (which should not be common).
