### ISSUE TITLE
Paragraph Block with Custom Background Color Not Displaying Text in Contrasting Color

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/amp-wp#5229]
## Bug Description

In Reader mode, when a Paragraph block is using a custom background color, the background color remains for the Paragraph block, but the text is displayed using whatever theme is 

## Expected Behaviour

The background color would be stripped, or the text would be shown in a contrasting color.

## Steps to reproduce
1. Set AMP to Reader mode
2. Create a new post that has a Paragraph block
3. In the block settings, set a custom background color for the Paragraph block
4. View the post in AMP

## Screenshots

How the post appears in the editor:

![Post in Editor](https://user-images.githubusercontent.com/4000628/90199763-a7a15f80-dda3-11ea-9938-2404e6cfcde8.png)

How the post appears in AMP:

![Post in AMP](https://user-images.githubusercontent.com/4000628/90199780-aff99a80-dda3-11ea-9e89-c7fbb4bf4ad7.png)

## Additional context

 - WordPress version: 5.5
 - Plugin version: 1.5.5
 - Gutenberg plugin version (if applicable): Deactivated for testing, but same results with 8.7.1
 - AMP plugin template mode: Reader
 - PHP version: 7.3
 - OS: macOS 10.15.6
 - Browser: Firefox
 - Device: MacBook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Unfortunately, I'm not able to replicate the issue you are experiencing. With Reader mode active, I can set a custom background and foreground color for the paragraph block in the editor and see it reflected on the AMP page without issue. Do you have any plugins enabled that could affect the output of the page?


In the editor:

![image](https://user-images.githubusercontent.com/16200219/90300638-01c92000-de8b-11ea-89d3-5535a1602662.png)
 
And when viewed on the AMP page:

![image](https://user-images.githubusercontent.com/16200219/90300582-ac8d0e80-de8a-11ea-97e2-2506e22ff486.png)

---

On a unrelated note, with v2.0 of the plugin you will be able to use any AMP-compatible theme as your Reader theme. Feel free to try our [latest beta](https://github.com/ampproject/amp-wp/releases/tag/2.0.0-beta3) to test it, along with many new features documented in the release notes.

**Comment by edequalsawesome** [comment]
> Unfortunately, I'm not able to replicate the issue you are experiencing. With Reader mode active, I can set a custom background and foreground color for the paragraph block in the editor and see it reflected on the AMP page without issue. Do you have any plugins enabled that could affect the output of the page?

Just to double-check it (since it was the end of my day and there was a strong chance that I *did* miss a plugin that could be causing an issue!), I re-ran the test on a local test site I set up that only has the default WordPress installation and the AMP plugin installed, and I'm still seeing the same issue:

Here's the post in the editor:

 ![Post - Editor](https://user-images.githubusercontent.com/4000628/90319435-329a6b00-df06-11ea-8831-30e45b0e8f78.png)

And the post in AMP:

![Post - AMP](https://user-images.githubusercontent.com/4000628/90319450-4cd44900-df06-11ea-9c05-392e4a6879d2.png) 

Same thing when I try it with a Page, too -- here's the editor:

![Page - Editor](https://user-images.githubusercontent.com/4000628/90319465-7db47e00-df06-11ea-894f-169282bac977.png)

And here's the page in AMP:

![Page - AMP](https://user-images.githubusercontent.com/4000628/90319469-860cb900-df06-11ea-97d4-263c3cff8aa9.png)

I'm not sure if there's a setting or some other thing I might be missing somewhere, though! If you have any thoughts and want me to test them, let me know, I'll be happy to do what i can :)

**Comment by westonruter** [comment]
I'm seeing the same problem, in both 1.5.5 and 2.0-RC1:

Non-AMP | AMP
----------|------
![image](https://user-images.githubusercontent.com/134745/90319875-14764000-def1-11ea-9923-b95571e2d855.png) | ![image](https://user-images.githubusercontent.com/134745/90319889-1dffa800-def1-11ea-9c74-fcfd4d98475f.png)

**Comment by westonruter** [comment]
I've found the problem. The issue is that the active theme's stylesheet is not included on the legacy Reader mode templates. For this reason, these style rules from Twenty Twenty are not included on the AMP page:

https://github.com/WordPress/wordpress-develop/blob/dddddc47f4f89b9136865bf34506fcb99cfc2302/src/wp-content/themes/twentytwenty/style.css#L2743-L2788

I also see the same issue if I switch from Twenty Twenty to another theme like Twenty Sixteen. So it seems to be a basic block portability problem.

To solve the problem for Twenty Twenty specifically, it appears we may need to copy these styles to print as part of the core theme sanitizer when serving a legacy reader template, as well as print styles returned by `twentytwenty_get_customizer_css( 'front-end' )`.

Nevertheless, this approach will not address the issue when a Reader theme is active. I'm not sure if those class names like `has-subtle-background-background-color` are standard. They seem to be theme-specific. So I don't know if we can solve this block color portability problem in the general case.

@edequalsawesome Here is some workaround mini plugin you can use to fix the problem in the time being: https://gist.github.com/westonruter/85135e6d9e0d61865f3a63cc3ab5929e

**Comment by pierlon** [comment]
Thanks for the analysis and temporary workaround @westonruter. Twenty Seventeen seems to not be affected, which is what I was using initially.

**Comment by westonruter** [comment]
@edequalsawesome There is a plugin build available for testing which should definitively fix this issue for any theme when using Reader mode: https://github.com/ampproject/amp-wp/pull/6042#issuecomment-824422138.

**Comment by jwold** [comment]
Based on my reading of the ticket, and the screenshots below, this passes QA.

<img width="1510" alt="Screen Shot 2021-04-23 at 12 39 32 PM" src="https://user-images.githubusercontent.com/3411173/115921896-ff16c580-a430-11eb-811f-c24d624dd71d.png">
