### ISSUE TITLE
In Reader mode gives an invalid amp page

### ISSUE THREAD

**Issue by PaolaBozhilova** [Automattic/amp-wp#5232]
Hi, I'm using a Twenty Seventeen theme in Reader mode. The amp plugin indicates that it is a valid amp page (in green), but when I test at https://search.google.com/test/amp it gives "Not a valid AMP page". What is the reason for this?

Thank you!

**Comment by westonruter** [comment]
@PaolaStoyanova Please provide the URL for the AMP page that is being reported as invalid.

**Comment by westonruter** [comment]
Actually, I think I see the the URL from the Site Health info you provided previously.

There appears to be a conflict with W3 Total Cache. Make sure you have the latest version installed. Also, there appears to be a conflict in its minification logic. In the General Settings, try turning off the Minify feature:

![image](https://user-images.githubusercontent.com/134745/90284157-600fe780-de26-11ea-8655-366d62ed9572.png)

**Comment by westonruter** [comment]
Actually, instead of this I can see the only thing you need to do is go into the "Extensions" screen for W3 Total Cache and enable their AMP extension:

![image](https://user-images.githubusercontent.com/134745/90285206-4bccea00-de28-11ea-9914-5bb6eb553c05.png)

**Comment by PaolaBozhilova** [comment]
Thank you, when I installed the extension everything was fine!
