### ISSUE TITLE
Add AMP Bodymovin animations support

### ISSUE THREAD

**Issue by HardeepAsrani** [Automattic/amp-wp#5244]
## Feature description

Any plans on adding Bodymovin support to the plugin? It's already a part of AMP and would be great to have it on AMP-WP: https://amp.dev/documentation/examples/components/amp-bodymovin-animation/?format=websites

Also, how can one register a script from AMP components which aren't part of the plugin?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
The `amp-bodymovin-animation` component is already supported by the plugin so there should be no problems with using it.

> Also, how can one register a script from AMP components which aren't part of the plugin?

Registering a script for an AMP component not supported by the plugin is quite trivial. For example, if the `amp-bodymovin-animation` component was not supported you could register the script like so:

```php
add_action(
    'wp_default_scripts',
    function ( WP_Scripts $scripts ) {
        $scripts->add(
            'amp-bodymovin-animation', // Name of AMP component
            'https://cdn.ampproject.org/v0/amp-bodymovin-animation-0.1.js', // Script URL for AMP component
            [ 'amp-runtime' ], // Add the AMP runtime as a required dependency
            null
        );
    }
);
```

**Comment by pierlon** [comment]
I noticed when the `loop` attribute is used for the `amp-bodymovin-animation` component, a validation error is raised. I've filed a separate issue for that in https://github.com/ampproject/amp-wp/issues/5245, and I've also reported it as a bug in https://github.com/ampproject/amphtml/issues/29890.

**Comment by westonruter** [comment]
> Registering a script for an AMP component not supported by the plugin is quite trivial.

Nevertheless, if the AMP plugin isn't already registering the script then it's likely that the plugin will flag it as being a validation error since it doesn't recognize it.

So if a script isn't currently being registered by the plugin, then that generally means the plugin is overdue for a validator spec update.

**Comment by HardeepAsrani** [comment]
Thanks! @westonruter and @pierlon

I think it might not be working because I was using a JSON which was stored in localhost and I see AMP uses an iFrame to ampproject.net which might was probably why it wasn't loading. I will close this. 👍
