### ISSUE TITLE
Validation error occurs when a number is used for loop attribute in amp-bodymovin-animation component

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#5245]
## Bug Description

While looking into #5244 I noticed when a number is used for the `loop` attribute a validation error occurs. For example, with the following markup:

```html
<amp-bodymovin-animation layout="responsive"
  width="1920"
  height="1080"
  src="https://amp.dev/static/samples/json/bodymovin_happy_2016.json"
  loop="5">
</amp-bodymovin-animation>
```

The validation error is:

![image](https://user-images.githubusercontent.com/16200219/90584964-47efed80-e1c3-11ea-98e6-d5d9ea454a0a.png)

I also notice the same error when using the AMP Validator:

![image](https://user-images.githubusercontent.com/16200219/90585127-a4eba380-e1c3-11ea-9f59-78ae30586da3.png)

So the issue lies within the AMP Validator and not in the plugin. I've filed an upstream bug (https://github.com/ampproject/amphtml/issues/29890) to have this resolved.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
I don't think this will be resolved before the upcoming v2.0 release, so I think the milestone should be removed here and the issue marked as "Blocked".

**Comment by pierlon** [comment]
@westonruter opened https://github.com/ampproject/amp-wp/pull/5267 that cherry-picks the fix from upstream, so it should be fine.

**Comment by pierlon** [comment]
**QA passed**

A validation error is not reported when the `loop` attribute is a positive integer, excluding 0:

Before | After
---|---
![image](https://user-images.githubusercontent.com/16200219/91240362-5b560800-e731-11ea-9c17-482b0eb5c7cb.png) | ![image](https://user-images.githubusercontent.com/16200219/91240308-2e095a00-e731-11ea-8ecf-be237036d8ed.png)
