### ISSUE TITLE
Twenty Twelve Theme compatibility: Menu Issues

### ISSUE THREAD

**Issue by ernee** [Automattic/amp-wp#5246]
## Bug Description

Prompted by a [forum support topic](https://wordpress.org/support/topic/twenty-twelve-main-menu-bounces/), it appears the AMP version of the [Twenty Twelve theme ](https://wordpress.org/themes/twentytwelve/) is currently displaying a few issues with the _Primary Menu_: 

a) When using a custom menu, the menu shifts/ jumps to the center after clicking menu items: https://recordit.co/pL2WmekDOl

b) When using the default menu, the mobile version does not work/ expand: https://recordit.co/yUTPpiGoyB

## Expected Behaviour

a) The custom menu does not shift / jump when clicking on menu items 

b) The default menu opens in the mobile view 

## Steps to reproduce

1. Install the Twenty Twelve theme
2. Go to _Appearance > Menu_ 
3. Under _Menu Locations > Primary Menu_, select a) custom menu or b) default menu (no menu selected)
4. a) see menu shift when selecting menu items or  b) see mobile menu does not expand 

Gists: 

a) https://gist.github.com/ernee/eee82c9632bd970a0dbaaab3e92e0b07
b) https://gist.github.com/ernee/fbd6991074ecb40e57a7c4c7f7bf3357

## Additional context

 - WordPress version: 5.5
 - Plugin version: 2.0.0-RC1
 - AMP plugin template mode: Standard/ Transitional/ Reader (Theme)
 - PHP version: 7.3.5
 - OS: MacOS
 - Browser: Chrome
 - Device: MacBook air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@pierlon I haven't been able to see the issue myself yet, but if it can be fixed for 2.0 it would probably be ideal given that core themes will be more commonly used as Reader themes.

**Comment by pierlon** [comment]
Did a `git bisect` and found that https://github.com/ampproject/amp-wp/commit/445798298649476d096cb7af2cd18e8cc9b5b456 seems to be the origin of the bug. Will open a PR with a fix in the morning.

**Comment by StephenThiam629** [comment]
My website used the GeneratePress theme to have the same issue. The Menu on mobile is not working. Is there any solution?

**Comment by pierlon** [comment]
@StephenThiam629 the issue you describe is not related to this bug. I see you've opened a [support topic](https://wordpress.org/support/topic/home-page-not-appear-in-mobile/) for your issue so feel free to continue the discussion over there.
