### ISSUE TITLE
Legacy toggle close to hide menu button at appearance menu

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#5252]
## Bug Description

At the appearance menu the toggle component responsible to preview the AMP version is overlapping the hide menu button. At small screens and other languages, for example, Portuguese there is no space between the toggle and the text. 
 
## Steps to reproduce

1. Select legacy mode
2. Go to appearance menu
3. Click on AMP
4. See the design issue at bottom left 

<img width="339" alt="Appearance menu small screen" src="https://user-images.githubusercontent.com/330792/90857378-efb01b80-e37b-11ea-8b36-ed4c3e0d5030.png">

![Appearance menu large screen](https://user-images.githubusercontent.com/330792/90857421-ffc7fb00-e37b-11ea-8d44-5f6767432a0e.png)

## Additional context

 - WordPress version: 5.5
 - Plugin version: 2.0 RC1
 - Gutenberg plugin version (if applicable): no
 - AMP plugin template mode: Reader / Legacy template
 - PHP version: 7.3
 - OS: Mac
 - Browser: Chrome 84
 - Device: Macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I think the text should just be hidden in this case. In practice this collapse button is likely never used. The text should be moved to a tooltip.

**Comment by pierlon** [comment]
Hmm well the text is from core. Should we hide it/make it a tooltip, or see if the toggle can be positioned better?

**Comment by westonruter** [comment]
Yes, I recall hiding the text in some Customizer extension I wrote in the past. Hiding the label would also be necessary when a user filters the device previews to add more devices. I don't think there is much value in the collapse button having a dedicated label on screen.

**Comment by fellyph** [comment]
@westonruter yes the label in that case doesn't bring enough value an alt or aria property is enough. If the toggle align to the right will sort on big screens but not in a 13" screen.

**Comment by westonruter** [comment]
Oh, so there's the issue of the position on large displays. And then there's the overlap issue on smaller ones. So on smaller displays the text can be hidden, but on all displays the toggle should be properly positioned just to the left of the device previews. I think the positioning was hard-coded for simplicity. We may need to nest the toggle inside the device previews container of that's possible.

**Comment by westonruter** [comment]
@fellyph Please test the changes in #5284

**Comment by fellyph** [comment]
@westonruter Looks great, I've install the build 

<img width="754" alt="Screen Shot 2020-08-27 at 14 09 09" src="https://user-images.githubusercontent.com/330792/91446140-f30d4080-e86e-11ea-9d6e-2594b9c6324e.png">
