### ISSUE TITLE
Sitekit integration

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#5254]
## Feature description

I've installed the AMP plugin and later installed Sitekit and setup Google Analytics. After install I went to AMP settings and the plugin still suggesting install the plugin when I try to setup analytics via AMP Settings. 

Would be better instead suggesting the installation verify if the plugin is already installed and notify the user that google analytics configuration is not necessary.
 
![AMP Settings Analytics configuration](https://user-images.githubusercontent.com/330792/90860936-d363ad00-e382-11ea-8de9-66c143da349f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Yes that makes sense. Thanks for reporting the issue.

**Comment by westonruter** [comment]
Technically, the notice doesn't say that the user should install Site Kit. It says they should _consider using_ Site Kit instead. So it is written in a way that it could apply to sites that already have the plugin installed and active.

**Comment by pierlon** [comment]
Yep, I suppose another notice could be shown instead to let the user know that Site Kit is already handling analytics.

**Comment by westonruter** [comment]
Site Kit may not yet be handling analytics if that module hasn't been configured.

**Comment by westonruter** [comment]
I think we're OK here. We're directing users to Site Kit if they try adding `gtag` or `googleanalytics`.

Note: If there are other AMP-compatible plugins for other analytics providers, we should absolutely provide similar helpers.
