### ISSUE TITLE
0.4 wp_footer introduction break everything

### ISSUE THREAD

**Issue by bactisme** [Automattic/amp-wp#527]
Hi,

The new 0.4 version call wp_footer. 
Many of my plugins are not made to be on AMP because they prints things in the footer (scripts).
I have to blacklist them one by one with remove_action ...
Even some jQuery dependencies are coming.

Is it only me?

**Comment by mjangda** [comment]
`wp_footer` only fires when viewing an AMP post in the Customizer. There may be a different issue here.
