### ISSUE TITLE
Cache "Error Index" count

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5271]
## Feature description

Currently the count that is shown next to the `Error Index` submenu entry in the AMP admin menu is uncached and computed dynamically on every single admin page request (that includes the admin menu, so AJAX requests should not be affected).

Strangely enough, the count directly above it for the `Validated URLs` entry is already being cached.

![Image 2020-08-25 at 10 52 12 PM](https://user-images.githubusercontent.com/83631/91227689-39578800-e727-11ea-9c11-a048f322ae52.png)

We should add caching for the `Error Index` cache as well, and combine these into a single transient.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The query counting the number of errors needing attention no longer runs on every admin page. 
* The number shown in the admin menu and in the select input on the error index screen stays up to date

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We should also add caching for the At a Glance widget while we're at it.

**Comment by westonruter** [comment]
A [support topic](https://wordpress.org/support/topic/duplicate-queries-15/) was just raised about this as well:

> Hello
> in /wp-admin/admin.php?page=amp-options
> I find this: 
> 
> ![image](https://user-images.githubusercontent.com/134745/91645356-44e1d200-e9f9-11ea-8ed7-085956354bb9.png)
> 
> and for example in my custom plugin, all these unnecessary queries are made on the administration page
> 
> ![image](https://user-images.githubusercontent.com/134745/91645360-49a68600-e9f9-11ea-83d7-1a97dbc6ee16.png)

May be the same issue or an area for additional query reductions to be made.

**Comment by westonruter** [comment]
Two more related/similar support topics:

* https://wordpress.org/support/topic/very-slow-loads-and-long-query-times-on-dashboard/
* https://wordpress.org/support/topic/slow-admin-7/

**Comment by westonruter** [comment]
Related: #5336.

**Comment by schlessera** [comment]
**QA passed**

The values are stored in the transients and reused for both the menu construction as well as the "At a glance" widget.

![Image 2020-09-18 at 12 37 41 AM](https://user-images.githubusercontent.com/83631/93535607-953cb780-f947-11ea-8f44-05686321cdbf.png)
