### ISSUE TITLE
Disable the AMP validation inside WP

### ISSUE THREAD

**Issue by Mte90** [Automattic/amp-wp#5286]
## Feature description
As we have editors and writers we don't want that see these warnings (happenings also with article not yet published so in draft).
There is an option to suppress plugins but is not clear if this means that will disable the plugin or suppress the errors of that plugins.
Maybe ad an option to disable at all those errors as we are using google search console to track AMP issues, it is possible? I don't see any option and I don't know if there are filters or constants.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@Mte90 This is a feature as of 2.0.0. Non-admin users will all have the validation errors hidden. For admin users, there is an option to also turn off the validation errors. This is exposed as a preference on the user profile screen:

![image](https://user-images.githubusercontent.com/134745/91472604-8e40ee80-e84c-11ea-8d0c-1663b8ab7484.png)

You can read more about this in the [v2.0.0](https://github.com/ampproject/amp-wp/releases/tag/2.0.0) release notes. See the [Developer Tools section](https://github.com/ampproject/amp-wp/releases/tag/2.0.0#tag-select-menu-7467b062-e887-11ea-8a81-2c0f45c9f97a:~:text=Before%20v2.0%2C%20the%20AMP%20plugin%20Developer,who%20have%20permission%20to%20edit%20posts.).

> There is an option to suppress plugins but is not clear if this means that will disable the plugin or suppress the errors of that plugins.

The plugins themselves will be suppressed from running on AMP pages.

**Comment by Mte90** [comment]
In this way I need to ask to all the users to disable it, there is no way to disable for everyone that feature?

**Comment by westonruter** [comment]
Are all of the users administrators?

**Comment by Mte90** [comment]
No, we have some users that are also administrators, but they are also writers, basically they need that for other plugins, widgets and settings (we cannot change that policy for various reasons).
We are the technical team, so we have our tools to track and manage errors, and they don't need to know about them or they will go in panic like now.

**Comment by westonruter** [comment]
Non-administrators do not even have the option to enable Developer Tools, so for them they do not need to turn off Developer Tools. How many administrator users do you have who need developer tools turned off? You can turn it off for them by editing their user as well.

**Comment by Mte90** [comment]
Well I have 5 but I have to do the same to 10 websites of the same customer, and I have other customers with the same issues for other reasons.
So a global way to disable that feature it will be better, usually WP plugins doesn't do this kind of things by users but global to enable and in case the user can disable.  
Not like opt-in for everyone I mean, but a global option so it is more easy to manage when you have to manage a lot of websites.

**Comment by westonruter** [comment]
There is no global UI currently to turn off Developer Tools by default, but you can use WP-CLI to do so in bulk:

```bash
for user_id in $( wp user list --role=administrator --format=ids ); do wp user meta update $user_id amp_dev_tools_enabled false; done
```

There is a todo to consider adding a filter to change the default value:

https://github.com/ampproject/amp-wp/blob/aec847235a1b75ee8c53efb6814927e6cb019b57/src/Admin/DevToolsUserAccess.php#L77

But that is not yet implemented.

**Comment by Mte90** [comment]
Uhm I will see if I can do a filter that change the capabilities or remove it to disable it.
I don't have a wp-cli access to all the websites and a snippet is easiest way (I know that is not the optimal way but I cannot change all the installation easily).

**Comment by Mte90** [comment]
I think that with a code like:
```
add_filter( 'user_has_cap', "remove_amp_validate_cap",  10, 4 );
function remove_amp_validate_cap( $caps, $cap, $args, $user ) { 
  $caps['amp_validate'] = false;
  return $caps;
} 
```

I should be able to remove on the fly that capability to all the users.

**Comment by westonruter** [comment]
Yes, that should also turn off DevTools for all users. However, it will force them to be disabled without the option to turn them back on.

**Comment by westonruter** [comment]
Let's go ahead with adding the filter to change the default value.

**Comment by westonruter** [comment]
Also, given that the block editor integration is not yet ideal (#3821, #2069), let's default the value to be `false` when Reader mode is selected (which will be for the majority of users).

**Comment by westonruter** [comment]
Following the pattern of `amp_post_status_default_enabled`, let's call this new filter: `amp_dev_tools_user_default_enabled`. 

Let's pass two arguments: 

* `$enabled` (defaults to `false` when Reader mode is active)
* `$user_id`

**Comment by pierlon** [comment]
**QA Passed**

When the `amp_dev_tools_enabled` user meta key is not set:

![image](https://user-images.githubusercontent.com/16200219/92181904-e1610580-ee39-11ea-97e0-c84719e93686.png)

- When Standard or Transitional mode is active, dev tools is enabled by default:

  ![image](https://user-images.githubusercontent.com/16200219/92181947-fdfd3d80-ee39-11ea-9a02-91a293321e8c.png)

- When Reader mode is active, dev tools is not enabled by default:

  ![image](https://user-images.githubusercontent.com/16200219/92182139-78c65880-ee3a-11ea-987a-02fca0467336.png)

---

Given that the `amp_dev_tools_enabled` user meta is not set for a user:

- the following filter enables dev tools for all users:

```php
add_filter( 'amp_dev_tools_user_default_enabled', '__return_true' );
```

- the following filter only enables dev tools for the user with ID 1:

```php
add_filter( 'amp_dev_tools_user_default_enabled', function ( $enabled, $user_id ) {
	return 1 === $user_id;
}, 10, 2 );
```
