### ISSUE TITLE
Make sure that AMP_QUERY_VAR gets defined

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5290]
## Bug Description

A couple support forum topics have reported a warning:

> Warning: Use of undefined constant AMP_QUERY_VAR – assumed ‘AMP_QUERY_VAR’ (this will throw an Error in a future version of PHP) in /home/horoscopezodaic/public_html/wp-content/plugins/snax/includes/plugins/amp/amp.php on line 26

See:

* https://wordpress.org/support/topic/version-2-0-0-killed-my-websites-backup-first/
* https://wordpress.org/support/topic/showing-warning-after-the-update/

I thought this was limited to the Snax plugin referencing `AMP_QUERY_VAR` when it should have rather called `amp_get_slug()`. So the workaround I provided was to add to the `wp-config.php`:

```php
define( 'AMP_QUERY_VAR', 'amp' );
```

Nevertheless, there are 30 plugins on WordPress.org which are referencing this constant: https://wpdirectory.net/search/01EGSQZSB96VWEETBH09SXW82D

For example, Calculated Fields Form does:

```php
if(defined('AMP_QUERY_VAR')) return is_amp_endpoint();
```

And Super Progressive Web Apps does:

```php
return defined( 'AMP_QUERY_VAR' ) ? AMP_QUERY_VAR . '/' : 'amp/';
```

And PageSpeed Ninja does:

```php
|| (defined('AMP_QUERY_VAR') && get_query_var(AMP_QUERY_VAR, 0))
```

And Permalink Manager Lite does:

```php
		// 2. AMP
		if(defined('AMP_QUERY_VAR')) {
			// Detect AMP endpoint
			add_filter('permalink_manager_detect_uri', array($this, 'detect_amp'), 10, 2);
			add_filter('request', array($this, 'enable_amp'), 10, 1);
		}
```

So bottom line, I think we need to make sure that `AMP_QUERY_VAR` gets defined at the same point that 

## Expected Behaviour

Plugins that reference `AMP_QUERY_VAR` should not issue warnings.

Previously the AMP plugin would define `AMP_QUERY_VAR` the first time that `amp_get_slug()` is called. This has changed in 2.0, however. Originally `AMP_QUERY_VAR` was defined at the `after_setup_theme` action priority 5:

https://github.com/ampproject/amp-wp/blob/bdb0ec8f081faa36182279b7130aac1162d343eb/includes/amp-helper-functions.php#L147

## Steps to reproduce

1. Install the [Calculated Fields Form](https://wordpress.org/plugins/calculated-fields-form/) plugin and add a CFF block to a post:

![image](https://user-images.githubusercontent.com/134745/91609993-480f8c00-e92d-11ea-92c5-f6432c41eed6.png)

2. On the non-AMP page it should look like the following:

![image](https://user-images.githubusercontent.com/134745/91610079-6c6b6880-e92d-11ea-8bfd-1ad4a5c8edcf.png)

3. Now look at the AMP version and notice the form is absent:

![image](https://user-images.githubusercontent.com/134745/91610129-82792900-e92d-11ea-82d4-15e8faedbdbd.png)

4. It should rather look like this:

![image](https://user-images.githubusercontent.com/134745/91610197-a2a8e800-e92d-11ea-994c-1266f7f843e6.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Plugins should be able to read from `AMP_QUERY_VAR` in addition to `amp_get_slug()`.

## Implementation brief

Beware of [`AmpSlugCustomizationWatcher`](https://github.com/ampproject/amp-wp/blob/324caa45a2ae2fd2305a16d65b6a9663285223bd/src/AmpSlugCustomizationWatcher.php) which calls `amp_get_slug()` at `after_setup_theme` priority 4.

There appears to be some dead code now here:

https://github.com/ampproject/amp-wp/blob/324caa45a2ae2fd2305a16d65b6a9663285223bd/includes/amp-helper-functions.php#L237-L238

We can replace that line with:

```php
if ( ! defined( 'AMP_QUERY_VAR ) ) {
    define( 'AMP_QUERY_VAR', amp_get_slug() );
}
```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed**

When the `AMP_QUERY_VAR` const is not defined manually, it is set by the plugin:

![image](https://user-images.githubusercontent.com/16200219/92162056-0e54ee80-ee21-11ea-8dd6-1e89030d4bd1.png)
