### ISSUE TITLE
PageSpeed Ninja - Incompatible Configurations

### ISSUE THREAD

**Issue by jamesozzie** [Automattic/amp-wp#5292]
## Bug Description

As reported in the [WordPress support forums](https://wordpress.org/support/topic/not-an-amp-page-error-after-new-update/) some users may encounter the amphtml link changing to only `?amp` when using the [PageSpeed Ninja plugin](https://wordpress.org/plugins/psn-pagespeed-ninja/) in the "Ultra" preset configuration, or when switching the plugins HTML parser option to "Use Fast simple HTML parser". 

![image](https://user-images.githubusercontent.com/41326532/91582740-21128380-e948-11ea-9bd7-c195b691e780.png)

![image](https://user-images.githubusercontent.com/41326532/91582255-7306d980-e947-11ea-8cca-dd43dfe73257.png)

While none of these options are set by default users who have switched may encounter their AMP URLs not accessible (even when accessing the correct AMP URL directly in the address bar. 

While this may not be something we can address from our side let's investigate this further. 

## Steps to reproduce

1. Install & activate the [PageSpeed Ninja plugin](https://wordpress.org/plugins/psn-pagespeed-ninja/)
2. Switch to the "Ultra" configuration option (Advanced > Presets > Ultra)
3. Visit a non AMP URL (which has an AMP version) and check the amphtml link

## Additional context

- The default configuration of PageSpeed Ninja does not result in any rendering errors
- Switching to the "Ultra" preset option or enabling the "Use Fast simple HTML parser" results in the issue
- Tested using plugin version 2.0 & PageSpeed Ninja v0.9.41

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I don't think this is actually an issue with the AMP plugin. It's a bug with PageSpeed Ninja. Their output buffer processing on non-AMP pages is corrupting the `amphtml` link. Specifically, I can see the issue happens when the `urlminify` option is enabled. I've ported your issue here over to a support topic for PageSpeed Ninja: https://wordpress.org/support/topic/url-minification-breaks-amphtml-links-when-fast-simple-html-parser-used/
