### ISSUE TITLE
Non-singular URLs remain able to be validated after switching to legacy reader mode

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5295]
## Bug Description

This is an issue which was discovered by @ernee.

With this setup:

1. You are in Transitional mode (or Standard mode or Reader mode with a Reader theme).
2. You have AMP enabled for all templates.
3. You have set the homepage to show the latest posts.
4. You validate the homepage to create a validated URL for the homepage.

In the Validated URLs screen you'll see this entry:

![image](https://user-images.githubusercontent.com/134745/91629954-43c18e00-e982-11ea-843f-9e3ab1e57565.png)

Now with this, switch to the AMP Legacy Reader theme. Remember that in legacy Reader mode, only singular AMP pages should be able to served as AMP. In spite of this, however, you can still recheck that validated URL for the homepage.

When you do this, you get this unexpected result:

![image](https://user-images.githubusercontent.com/134745/91630013-df52fe80-e982-11ea-9f93-d7b13fddf76b.png)

There are also PHP notices in the PHP error log:

```
[29-Aug-2020 06:04:28 UTC] PHP Notice:  Trying to get property 'post_content' of non-object in /app/public/content/plugins/amp/includes/templates/class-amp-post-template.php on line 339
[29-Aug-2020 06:04:28 UTC] PHP Notice:  Trying to get property 'post_author' of non-object in /app/public/content/plugins/amp/includes/templates/class-amp-post-template.php on line 280
[29-Aug-2020 06:04:28 UTC] PHP Notice:  Trying to get property 'post_type' of non-object in /app/public/content/plugins/amp/includes/templates/class-amp-post-template.php on line 301
```

What's going on here? Granted, this is somewhat of an edge case because the validated URL results for the homepage would not normally be stored in Reader mode, except when you switch from legacy to a Reader theme, validate the homepage, and then switch back to legacy theme.

Normally, AMP requests for non-singular templates are prevented from being served with this logic:

https://github.com/ampproject/amp-wp/blob/324caa45a2ae2fd2305a16d65b6a9663285223bd/includes/amp-helper-functions.php#L511-L540

The exception to this is that when doing validation requests, the `amp_is_available()` function is forced to return `true`:

https://github.com/ampproject/amp-wp/blob/324caa45a2ae2fd2305a16d65b6a9663285223bd/includes/amp-helper-functions.php#L501-L509

The idea there originally was to allow for a site to have AMP validation checked even before AMP is made generally available. I think that this is no longer valid, however, and it should be removed. Attempting to validate a URL on which AMP is not available should instead result in an error.

The effect of forcing a singular post template to try to render the blog index is the following:

> ![image](https://user-images.githubusercontent.com/134745/91630055-38229700-e983-11ea-88f4-4ec628e80d0a.png)

The validation errors are due to the template having:

```html
<link rel="canonical" href="">
```

That could be fixed with this patch:

```diff
--- a/includes/templates/class-amp-post-template.php
+++ b/includes/templates/class-amp-post-template.php
@@ -116,7 +116,7 @@ class AMP_Post_Template {
  'content_max_width'     => $content_max_width,
 
  'document_title'        => wp_get_document_title(),
- 'canonical_url'         => get_permalink( $this->post ),
+ 'canonical_url'         => $this->post ? get_permalink( $this->post ) : amp_remove_endpoint( amp_get_current_url() ),
  'home_url'              => home_url( '/' ),
  'blog_name'             => get_bloginfo( 'name' ),
```

But this isn't really that helpful because this singular template is not supposed to be rendering the blog index page anyway, so it is expected to be broken. 

## Expected Behaviour

A previously-stored Validated URL which is no longer available as AMP should not be able to be re-validated. An error message should be shown instead saying the URL is not an AMP page.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
Interesting the edge-case surface touch points related to the reader mode expansion. Although an edge case, it may happen relatively often during the initial adoption phase of 2.0 the switching from legacy to reader, back to legacy.

**Comment by jwold** [comment]
* WR > Drafted PR, Pierre is looking into this. Basically if AMP disabled for given URL because template no longer available, or AMP disabled for it, but you have old validated URL post referencing this, and you try to revalidate it, then it should show a message to say "AMP no longer available for this URL, it can be trashed."

**Comment by westonruter** [comment]
**QA Passed**

I went to `/2021/` year archive and validated it while in Transitional mode. 

Then I switched from Transitional mode to Reader mode with the legacy theme. I then tried re-validating, and I got the expected error message: 

![image](https://user-images.githubusercontent.com/134745/115981886-01217700-a54c-11eb-9221-fe107c275dc6.png)
