### ISSUE TITLE
URL validation CLI script contains logic that should be made available outside the CLI script

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5307]
## Feature description

The CLI script provides methods for getting different types of URLs to validate, and for iterating through these URLs. Instead of re-creating this logic for new plugin features, we can mostly extract it into separate classes for use elsewhere, e.g., in a REST endpoint or a WP Cron task.

## Acceptance criteria

* CLI script works exactly as before.

## Implementation brief

Create new classes -- one for providing URLs and one for validating them -- that can be consumed by new features. Provide a locking mechanism to allow features to opt out of running if there is already a process validating URLs.

## QA testing instructions

Run the CLI script (1) on small batches of URLs, (2) on large batch of URLs, and (3) with conditionals (e.g, `is_single`).

`URLValidationProvider` provides a locking mechanism that can be used to prevent two process from validating URLs at the same time. The CLI script uses this, so another test would be to attempt to run the script in two tabs and verify that the second one isn't allowed to run.

## Changelog entry

* Extract URL validation CLI script functionality into new classes for sharing with new plugin features.

**Comment by schlessera** [comment]
**QA passed**

Testing a default run on a site populated with the theme unit test data (255 URLs), a run filtered by templates and a run that was `--force`d.

The runs all completed successfully.
