### ISSUE TITLE
Error while saving plugin options

### ISSUE THREAD

**Issue by nonsintetic** [Automattic/amp-wp#5309]
## Bug Description

While trying to change any settings I receive an error "Error: An error occurred. You might be offline or logged out.".  Looks like it's making a request to the json-api ```/wp-json/amp/v1/options?_locale=user```. The response to the request is:

```[{"code":"json_cookie_invalid_nonce","message":"Nonce cookie is invalid"}]```

Relogging, using a different browser, trying other settings doesn't make any difference.

## Expected Behaviour

Settings save normally.

## Steps to reproduce

1. Go to Amp > Settings
2. Change any settings
3. Click "Save changes"
4. Error pops up: "Error: An error occurred. You might be offline or logged out."

## Additional context

 - WordPress version: 5.5
 - Plugin version: 2.0.0 
 - AMP plugin template mode: any
 - PHP version: 7.4
 - OS: Windows
 - Browser: Firefox, Chrome (latest)
 - Device: Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We have not experienced this issue. Please share your Site Health info so we can investigate and try to replicate your environment. You can do so by commenting here or via our [private submission form](https://docs.google.com/forms/d/e/1FAIpQLSfHk32DRaYLgYO3MMg002_wYKqeWJAvHvj-EoSFWOFyDH6ncw/viewform?usp=sf_link).

**Comment by nonsintetic** [comment]
Seems like it's a generalized issue with the json-api on this install. Not related to AMP
