### ISSUE TITLE
As a user I would like to see a notice explaining what the plugin suppression area does when empty

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#5310]
## Feature description

Currently the plugin suppression area shows as empty when there are no plugins installed on the site (excluding the AMP plugin of course). It looks like this:

<img width="1451" alt="Screen Shot 2020-09-01 at 7 48 25 AM" src="https://user-images.githubusercontent.com/3411173/91866955-efd7d300-ec27-11ea-987e-5be472cd2ada.png">

We discussed either removing this area or adding empty state copy, and opted for the second option.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Recommendation for copy:

1. ~"When a plugin adds markup that is not allowed in AMP you may let the AMP plugin remove that markup, or you may suppress the plugin from running on AMP pages. There are no plugins site doesn't have any plugins that can be suppressed."~
2. "This list contains the plugins active in your site that you can suppress, currently there are no suppressible plugins."

Note: Review copy in instance where plugins **are** available.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Another idea is to just show a notice in place of the table:

![image](https://user-images.githubusercontent.com/134745/91878665-7c888e00-ec34-11ea-829c-bf31a0c04413.png)

**Comment by johnwatkins0** [comment]
@jwold Does Weston's suggestion above seem all right to you?

**Comment by jwold** [comment]
@johnwatkins0 and @westonruter that looks good to me. Thanks!

**Comment by schlessera** [comment]
**QA passed**
This is now shown when no suppressible plugins are active:
![Image 2020-09-17 at 9 36 50 PM](https://user-images.githubusercontent.com/83631/93519040-f8215500-f92d-11ea-823c-56b6a593edd5.png)

**Comment by schlessera** [comment]
Note: The copy is different than the one from the issue, and I couldn't find a reference to where another copy was decided upon.

**Comment by schlessera** [comment]
@amedina Can you quickly confirm that copy is good here?

**Comment by amedina** [comment]
Yeah; it is good. Let's ship it.
