### ISSUE TITLE
Images with captions in post content are not responsive

### ISSUE THREAD

**Issue by HelaGone** [Automattic/amp-wp#5318]
## Bug Description
The images in the post's content are not responsive when they are enclosen in the `[caption]` shortcode.

## Expected Behaviour
All the images within the post's content should be responsive no matter if they have captions or not. 

## Steps to reproduce

1.- Login to Wordpress and create a new post or edit an existing one. 
2.- Insert an image to the post's content and add a caption to it so, the post editor encloses the `<img>` tag within the `[caption]` shortcode
3.- Publish the post and see how the images are not responsive in a mobile device or resizing the browser's screen.

## Screenshots
<img width="1537" alt="Screen Shot 2020-09-02 at 12 30 09" src="https://user-images.githubusercontent.com/5982932/92017995-29890680-ed1a-11ea-86c0-8973b3153879.png">
<img width="1501" alt="Screen Shot 2020-09-02 at 12 20 42" src="https://user-images.githubusercontent.com/5982932/92018002-2c83f700-ed1a-11ea-97f5-d503426837af.png">

## Additional context
 - WordPress version: 5.5
 - Plugin version: 1.5.5
 - Gutenberg plugin version (if applicable): N/A
 - AMP plugin template mode: Standard
 - PHP version: 7.2
 - Browser: All
 - Device: Mobile devices

Here is an example:

https://www.viviendoencasa.mx/mascotas/perros-tienen-nocion-tiempo-pueden-adivinar-hora-estuido-ciencia-inteligencia-mascotas/

Is there any way to ensure the images within the post content are displayed as responsive images?

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
When inserting the caption there there is a `width=1280` which is causing this.

You as a quick workaround you can add the following to the Additional CSS in the Customizer:

```css
.wp-caption {
    max-width: 100%;
}
```

I'm not able to reproduce this issue in the WordPress core theme Twenty Nineteen which has [this CSS](https://github.com/WordPress/wordpress-develop/blob/164b22cf6ac87ecd757deb54f38c0d750301b83f/src/wp-content/themes/twentynineteen/style.css#L5243-L5249):

```css
.entry .entry-content > * {
    margin: 32px 0;
    max-width: 100%;
}
```

> ![image](https://user-images.githubusercontent.com/134745/92020971-da3cd900-ed0d-11ea-9472-e238485ccce8.png)

However, I _am_ able to reproduce the issue in the Twenty Twenty core theme:

![image](https://user-images.githubusercontent.com/134745/92021044-fb052e80-ed0d-11ea-9cb2-993c68e240b2.png)

It doesn't have the same CSS rule as Twenty Nineteen.

Nevertheless, I also get this same behavior on the non-AMP version. 

Therefore, I think what you are experiencing is a bug with the theme, not with the AMP plugin.

I suggest putting in place a CSS rule like the above to fix the issue, and contact the theme author to add the required CSS to prevent this from happening.
