### ISSUE TITLE
remove author or date from meta with provided examples doesn't work anymore

### ISSUE THREAD

**Issue by steioria** [Automattic/amp-wp#532]
Hi, 
with the previous template I used to remove author and date from meta to don't show them on amp pages. Now the same filters on the new template 0.4.1 doesn't work anymore.

Can you plese verify and update the documentation?

> Example: Remove Author from meta
> 
> This will completely remove the author section:
> 
> ```
> add_filter( 'amp_post_template_meta_parts', 'xyz_amp_remove_author_meta' );
> 
> function xyz_amp_remove_author_meta( $meta_parts ) {
>     foreach ( array_keys( $meta_parts, 'meta-author', true ) as $key ) {
>         unset( $meta_parts[ $key ] );
>     }
>     return $meta_parts;
> }
> ```

PS:

Also filter that affects `amp_post_template_meta_parts` doesn't work right now.

**Comment by steioria** [comment]
Digging a little bit I've found that replacing `amp_post_template_meta_parts` with `amp_post_article_header_meta` fixed the problem. Better to update the documentation

**Comment by troyxmccall** [comment]
filed a PR here to update the docs https://github.com/Automattic/amp-wp/pull/533

**Comment by amedina** [comment]
The docs ix has been merged: https://github.com/Automattic/amp-wp/pull/533
