### ISSUE TITLE
AMP with the Divi theme

### ISSUE THREAD

**Issue by jamiegrichards** [Automattic/amp-wp#5321]
Hello,

The latest version of Amp is crashing the Divi builder. As soon as I deactivate it, I can get into the builder. I've gone through the Amp settings (there's a LOT of new stuff in there) and I put back on reader mode but it still crashes the builder.

Please let me know what info you need me from in order to troubleshoot. My domain is:
https://blackspot.design

If you need a login, shoot me an email - jamie@blackspot.design.

I really appreciate any help you can give.

Thanks,
Jamie

**Comment by westonruter** [comment]
We can't log-in to your site.

Can you please share details about how specifically Divi is crashing? 

You may be experiencing #5308. If so, there is a pre-release build available to try: https://github.com/ampproject/amp-wp/issues/5308#issuecomment-685150562.
