### ISSUE TITLE
Widget Blocks in Gutenberg 8.9 are not disabled for Reader themes

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5322]
## Bug Description

In Gutenberg 8.9, the the Widget Blocks feature was enabled by default (https://github.com/WordPress/gutenberg/pull/24843, https://github.com/WordPress/gutenberg/pull/24087). The result is that now when a Reader theme is active, a Widget Blocks section appears even though widgets are supposed to be disabled in Reader mode:

![image](https://user-images.githubusercontent.com/134745/92049188-9615fc80-ed3e-11ea-8944-5e9b7a7711c8.png)

![image](https://user-images.githubusercontent.com/134745/92049297-df664c00-ed3e-11ea-9ca0-ff0d2302f88c.png)

## Expected Behaviour

Gutenberg's Widget Blocks functionality should be disabled in Reader themes.

## Steps to reproduce

1. Enable Reader mode and select a Reader theme other than Legacy.
2. Activate Gutenberg 8.9.0
3. Open the AMP Customizer.
4. See the Widget Blocks section.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Widget Blocks section should not be shown in the AMP Customizer.

## Implementation brief

* We should perhaps empty out the `$wp_registered_sidebars` global in `\AmpProject\AmpWP\ReaderThemeLoader::disable_widgets()`, though this method may get called to early. We may need a new `disable_sidebars()` method that run the latest that `register_sidebar()` and `register_sidebars()` may be called.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Note to make tests pass in #5319, I had to `remove_filter( 'customize_loaded_components', 'gutenberg_remove_widgets_panel' )` in a test: 521737d.

**Comment by westonruter** [comment]
There is also a filter and theme support which may be used. See https://make.wordpress.org/core/2020/09/03/whats-new-in-gutenberg-2-september/

**Comment by jwold** [comment]
QA passed.

I setup Local with with 8.9 Gutenberg plugin and latest DEV build of AMP.

I'm *not* seeing the Widget section in Customizer: https://d.pr/i/u3ckqb

**Comment by jwold** [comment]
QA passed passed. (Needed to run off the [2.0 branch](https://storage.googleapis.com/ampwp_github_artifacts/refs/heads/2.0/prod/amp.zip))
