### ISSUE TITLE
Custom post type template support not working

### ISSUE THREAD

**Issue by allancole** [Automattic/amp-wp#534]
Looking at the instructions in the README, I should be able to build my own CPT’s and templates by with the following code:

``` php
add_action( 'amp_init', 'xyz_amp_add_review_cpt' );
function xyz_amp_add_review_cpt() {
    add_post_type_support( 'xyz-review', AMP_QUERY_VAR );
}
```

This part works correctly and when I add `/amp` to the end of my single post CPTs, it displays my CPT in the AMP posts template, correctly ie: https://cloudup.com/cHfTJfhvDKZ

However, when adding templates for my CPT’s, I’m running into trouble related to this code:

```
add_filter( 'amp_post_template_file', 'xyz_amp_set_review_template', 10, 3 );

function xyz_amp_set_review_template( $file, $type, $post ) {
    if ( 'single' === $type && 'xyz-review' === $post->post_type ) {
        $file = dirname( __FILE__ ) . '/templates/my-amp-review-template.php';
    }
    return $file;
}
```

When I try to add my own CPT templates to the plugin, I get a blank screen on the `/amp` URL, ie: https://cloudup.com/cvcyUMieKYU

This happens whether I add the template file to the plugin directly or to the `/amp` directory in my theme. ( `$file = get_template_directory_uri() . '/amp/my-amp-review-template.php';` )

Also note that the `my-amp-review-template.php` at this point, is just a copy of the `single.php` template file.

**Comment by amedina** [comment]
The only thing I see it could be happening here is that WP is not finding the template files. Try to debug the output of "dirname( __FILE__ ) . '/templates/my-amp-review-template.php'" and make sure that it actually points to where the templates are.
