### ISSUE TITLE
Jetpack stats pixel not being added

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/amp-wp#535]
I'm having an issue where the Jetpack stats pixel is not being added.

I think it is related to this bit from jetpack-helper.php:
`	if ( ! has_action( 'wp_footer', 'stats_footer' ) ) {
		return;
	}`
I'm not entirely sure what that is checking for. The AMP template contains neither the `wp_footer` action, nor a `stats_footer` action. Is there something here that I am missing?

@mjangda I think you added this back in February when the Jetpack pixel was added.

**Comment by mjangda** [comment]
> if ( ! has_action( 'wp_footer', 'stats_footer' ) ) { return; }
> I'm not entirely sure what that is checking for.

It's checking to see if that Jetpack had hooked in to actually output necessary stats pixels on a non-AMP pageload. We use that as a cue to decide if we should output for AMP as well.

What versions of WordPress and Jetpack are you using? And I'm assuming the stats module is active? It's working for me on WP 4.6 + Jetpack 4.3.1.

**Comment by kevinlisota** [comment]
Thanks @mjangda. Turns out I was logged in with a role that doesn't fire the stats footer, which is as you described. Thanks for the clarification. I'll close the issue.
