### ISSUE TITLE
Improve discoverability of “Save Changes” button on AMP settings screen

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5353]
## Feature description

Given a viewport sized as following when looking at the AMP settings screen:

> ![image](https://user-images.githubusercontent.com/134745/92501543-92a5c980-f1b3-11ea-8adc-61dff779bed6.png)

Notice there is no Save button visible. This is even worse when a Reader theme is selected.

In the same way that there is a fixed bar at the bottom in the onboarding wizard, there may need to be something similar for the settings screen so that users can discover that they need to click “Save Changes”, without having to scroll all the way down the page.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
So something like this?

![Settings](https://user-images.githubusercontent.com/3411173/92529529-85063900-f1df-11ea-9c77-35369cbd0f13.png)

In addition to our own onboarding, I found a few other examples from [Yoast](https://d.pr/i/Ecx9NH) and [WooCommerce](https://d.pr/i/p3ILy8) that are similiar.

**Comment by westonruter** [comment]
Yes, like that.

**Comment by jwold** [comment]
Right now the gray `Save changes` button stays at the bottom of the screen. Users may miss it as they open the panels and interact with settings. 

Before: https://d.pr/i/70O8mw

After: https://d.pr/i/ncOO9D

Similar to the onboarding wizard, this would make the gray button float along the footer, so that a user could see it at all times.

This follows patterns that other major plugins are using, and could simplify the settings page as users expand the larger panels. 

cc @amedina

**Comment by westonruter** [comment]
Nice thing about this is the user can hit save, then switch to a different tab to see the result. If they don't like it, they can switch back to the first tab and change the selection and re-save, all without changing the vertical scroll position.

**Comment by amedina** [comment]
I love that approach. 

When I was creating the video content, that trip to the basement of  the page was painful.

**Comment by johnwatkins0** [comment]
@jwold How about the save success notice? Right now it flies in from the side. Should we instead work that information (and the rarer save failure notice) into this fixed bottom bar somehow?

**Comment by westonruter** [comment]
Yes +1

**Comment by jwold** [comment]
Ok, here's an idea I've been playing with. 

<img width="1116" alt="Screen Shot 2020-09-22 at 1 28 53 PM" src="https://user-images.githubusercontent.com/3411173/93934188-9ff4a500-fcd7-11ea-9f61-e9cf3c9eb541.png">

1. The initial state is blue and just has the word `Save`
2. During the save process (similar to Gutenberg) it will switch to say `Saving`
3. When save is complete it will say `Save`, until changes are made on the page
4. If an error occurs it will say `Save Error`, and display text beside that describes the error

Figma: https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/AMP-Design?node-id=1089%3A13117

**Comment by westonruter** [comment]
@jwold I don't think the button should become the notice, as otherwise what will the user click to retry? Clicking “Save Error” seems to indicate that the error would be saved. I think the success and error notices should be floated to the right.

**Comment by jwold** [comment]
You're right! That makes more sense, and it follows with the pattern above with notices above the template modes. 

<img width="599" alt="Screen Shot 2020-09-24 at 9 07 59 AM" src="https://user-images.githubusercontent.com/3411173/94170941-85403e80-fe45-11ea-8481-2e111f22b9df.png">

**Comment by johnwatkins0** [comment]
👍 This will work. I _can_ use the "Saved" state, which will revert back to "Save changes" once the user makes additional changes.

**Comment by jwold** [comment]
Confirmed in QA! Tested online and offline states.
