### ISSUE TITLE
When a site admin selects `view with AMP disabled` from the admin bar, there is no way to get back

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#5357]
## Bug Description

When I go to view with AMP disabled, I can’t get back to the AMP enabled state unless I delete the URL.

## Expected Behaviour

There should be an action in the admin bar that allows you to return to the AMP enabled state. 

## Steps to reproduce

Video showing behavior: https://v.usetapes.com/3IAmwnfXZ5

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Duplicate of https://github.com/ampproject/amp-wp/issues/5171

**Comment by jwold** [comment]
Closing in place of #5171
