### ISSUE TITLE
Discovery of improvements in release management

### ISSUE THREAD

**Issue by kmyram** [Automattic/amp-wp#5363]
## Feature description

The vision is to have a more streamlined release process where the role of release manager can rotate and we reduce risk and exposure.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Related to deployment of new releases, for instance automating 2.0.2
