### ISSUE TITLE
Result of themes_api in ReaderThemes class is not always as expected

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5367]
## Bug Description

Bug came up on the support forum here: https://wordpress.org/support/topic/issue-during-activating-the-updated-plugins/#post-13383737

The issue is stemming from one or both of:

1. It's possible, though I haven't been able to verify, that the `themes_api` function can in some situation return an invalid result (an object or array lacking a "themes" property) while not returning a `WP_Error`, which would cause issues with `array_filter` further down in the `ReaderThemes::get_default_reader_themes` method.
2. `get_default_reader_themes` was checking if the class property `$default_reader_themes` is null before running. Further down in the method, if `themes_api` returns `WP_Error`, it bails early (returning an empty array) without ever setting the class property. Never having this class property set is one possible vector for the "Allowed memory size" error (indicating an infinite loop, maybe) in the support ticket, although I was not able to replicate anything like this.

## Expected Behaviour

There should always be at least one reader theme -- the legacy theme at minimum -- displayed to the user, regardless of whether there is an error fetching reader themes. When there is an error fetching reader themes, it should fail silently. Alternatively, we can also surface this to the user as an error message, but I think that would be a separate issue.

## Steps to reproduce

1. Set the `WP_DEBUG` constant to `true`
2. In ReaderThemes.php, around line 230, (before the `array_filter`) set `$response->themes` to null.
3. Load the AMP settings screen and see the errors.

## Additional context

 - WordPress version: Latest
 - Plugin version: Latest
 - Gutenberg plugin version (if applicable): Latest from wp.org
 - AMP plugin template mode: Reader
 - PHP version: 7.3 
 - OS: Mac OS
 - Browser: Chrome
 - Device: Macbook

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If reader themes are not returned from the API, the user sees a notice informing them of the situation.

## Implementation brief

* Ensure `get_default_reader_themes` returns an array and the array is set as the  `$default_reader_themes` class property.
* Set a header on the reader themes REST controller response to indicate there was a problem.

## QA testing instructions

1. Add the following somewhere on your site: `add_filter( 'themes_api_result', '__return_null' );`
2. If you've recently viewed the reader themes, delete the transient that stores them for a day: `delete_transient( 'amp_themes_wporg' );` or `wp transient delete amp_themes_wporg`
3. Load the settings screen. 
4. Switch to reader mode and open the themes carousel. 
5. See the notice.
6. Go to the onboarding wizard and move through the wizard, selecting reader mode, to the theme selection screen.
7. See the notice.
8. Remove the filter from step one and repeat. You should not see the notice this time.
9. Re-add the filter and repeat. Now that the themes are in the transient, you should not see the notice (for a day).

## Demo

* 

## Changelog entry

* Handle an invalid response from the WordPress.org themes api when retrieving reader themes.

**Comment by westonruter** [comment]
> * In ReaderThemes.php, around line 230, (before the `array_filter`) set `$response->themes` to null.

A better way to test would perhaps be adding a plugin that does:

```php
add_filter( 'themes_api_result', '__return_null' );
```
