### ISSUE TITLE
WordPress MediaUpload component does not select files when AMP plugin is active.

### ISSUE THREAD

**Issue by ThatStevensGuy** [Automattic/amp-wp#5379]
## Bug Description

I noticed that the value prop of the MediaUpload Gutenberg component, when it is used for other components, does not select the file in the Media Library.

So I posted the issue into the Gutenberg issues: https://github.com/WordPress/gutenberg/issues/25129

I have had no response from WordPress, but user @tony47 identified that disabling the AMP plugin resolves the issue, which I also confirmed.

@tony47 also identified that commenting out the following line resolves the issue:

https://github.com/ampproject/amp-wp/blob/d0cceb54d60f3a7cfaf68ad4584be4ced2d5d50e/assets/src/block-editor/index.js#L35

## Expected Behaviour

AMP plugin should not cause a conflict with other MediaUpload components, breaking the Media Library.

## Steps to reproduce

Make a duplicate of the Post Featured Image Gutenberg component in your own custom sidebar panel. Remove unstableFeaturedImageFlow prop and rely on just the value prop to select the file in the Media Library.

## Additional context

 - WordPress version: 5.5.1
 - Plugin version: 2.0.1
 - AMP plugin template mode: Reader
 - PHP version: 7.4.2
 - Browser: Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Hi @ThatStevensGuy and @tony47, the issue has been fixed and will be available in our upcoming v2.0.4 release. In the meantime, feel free to try a plugin build with the fix incorporated: https://github.com/ampproject/amp-wp/pull/5412#issuecomment-696032545.

**Comment by westonruter** [comment]
I recommend using the 2.0.4-alpha release linked to here: https://github.com/ampproject/amp-wp/wiki/Development-Builds

**Comment by westonruter** [comment]
QA Passed.

I added an audio block, an image block, and set the featured image.

When clicking “replace” for the audio block, the previously-selected audio file was automatically selected:

![image](https://user-images.githubusercontent.com/134745/93945541-fcfa5600-fceb-11ea-81b5-fafd168bf2c6.png)

The same was true for the featured image and image blocks.
