### ISSUE TITLE
rel="stylesheet" - Validation: FAIL

### ISSUE THREAD

**Issue by lubimow** [Automattic/amp-wp#539]
i have problem:

```
<link rel="stylesheet" href="https:https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic">
The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 'https:https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic'.
```

how to fix duplicate https?

**Comment by designsimply** [comment]
I'm not sure if it will help but wanted to post just in cased. I noticed similar (but not exactly the same) errors for sites running the Cloudflare plugin for WordPress and saw that someone suggested turning off the "HTTPS Protocol Rewriting" setting in the Cloudflare plugin in case that helps! See https://github.com/Automattic/amp-wp/issues/180#issuecomment-188872062
