### ISSUE TITLE
Version 2.0.2 broke my navigation menus because of CSS sanitizer

### ISSUE THREAD

**Issue by Netzberufler** [Automattic/amp-wp#5401]
## Bug Description

I'm a theme developer and have added AMP support to several of my themes. I'm using `tap:AMP.setState()` to set a `toggled-on` class for multiple mobile dropdown menus and dropdown search fields.

Example CSS:
```
.main-navigation ul.menu {
	display: none;
}

.main-navigation.toggled-on > ul.menu {
	display: block;
}
```

My issue is that the `.main-navigation.toggled-on` class is missing in the AMP CSS since version 2.0.2 and seems to be removed by the Sanitizer. I guess that happens because the `toggled-on` class is not actually used by default in the HTML markup, only interactively added later.

Because of the missing class, mobile menus are broken with AMP active.

## Expected Behaviour

I would like to manually control the CSS sanitizer so my `toggled-on` class is included in the AMP CSS. I did not find any filter or action hook, but maybe I missed it.

## Steps to reproduce

Example of the implementation used:
https://github.com/ThemeZee/harrison/blob/master/template-parts/header/site-navigation.php
https://github.com/ThemeZee/harrison/blob/master/inc/addons.php#L93

Theme Demo with AMP active: https://preview.themezee.com/harrison/
When inspecting, you can see the `toggled-on` class is added, but has no effect because it is missing in the CSS.

## Additional context

 - WordPress version: 5.5.1
 - Plugin version: 2.0.2
 - AMP plugin template mode: Standard / Traditional

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by Netzberufler** [comment]
Btw not sure if this is really a bug, or if I'm doing things wrong. Any input on how I can solve that is highly appreciated :)

**Comment by westonruter** [comment]
@Netzberufler Thank you for reporting! You have correctly identified a bug. I've created a fix here: #5403. Can you test to confirm it fixes the issue?

**Comment by Netzberufler** [comment]
@westonruter Yes everything works fine now. Thanks so much for fixing this so quickly

**Comment by westonruter** [comment]
Excellent. I also just sent you a follow-up email.
