### ISSUE TITLE
Phantom AMP page attached to site in google search

### ISSUE THREAD

**Issue by Healthinnovations** [Automattic/amp-wp#5406]
Hi, 
The site I need help with is health-innovations.org.
I downloaded the AMP Project contributors plugin and chose the 2018 theme for my wordpress.com site. However, the plugin updated yesterday 18/09/2020, and a phantom AMP page has attached itself to my home page in the search string ‘healthinnovations’ on google search. The search must be done on a mobile to exhibit the AMP pages.

The AMP landing page is full of broken links, using the incorrect theme from 2020 and pages I haven’t built, and it looks absolutely awful. I have since deleted said plugin but the AMP phantom page with broken links, phantom pages, and the incorrect theme is still my landing page, having taken the place of my homepage.

I’ve been in touch with WordPress all day but no joy, they can’t get rid of it.

Can you help please?

Many thanks,

Healthinnovations

**Comment by westonruter** [comment]
Duplicate of #5407.
