### ISSUE TITLE
Phantom AMP page attached to site in google search

### ISSUE THREAD

**Issue by Healthinnovations** [Automattic/amp-wp#5407]
## Bug Description

The site I need help with is health-innovations.org.
I downloaded the AMP Project contributors plugin and chose the 2018 theme for my wordpress.com site. However, the plugin updated yesterday 18/09/2020, and a phantom AMP page has attached itself to my home page in the search string ‘healthinnovations’ on google search. The search must be done on a mobile to exhibit the AMP pages.

The AMP landing page is full of broken links, using the incorrect theme from 2020 and pages I haven’t built, and it looks absolutely awful. I have since deleted said plugin but the AMP phantom page with broken links, phantom pages, and the incorrect theme is still my landing page, having taken the place of my homepage.

I’ve been in touch with WordPress all day but no joy, they can’t get rid of it.

I cannot contact you on WordPress as I'm on wordpress.com, not wordpress.org
## Expected Behaviour

 
There should not be a faulty AMP page attached to my site acting as a landing page and containing broken links on google search

## Steps to reproduce

use the search string 'healthinnovations' on google search to reach faulty AMP page

## Additional context

 - WordPress version: 5.5.1
 - Plugin version: 2.0.3
 - Gutenberg plugin version (if applicable): n/a
 - AMP plugin template mode: 
 - PHP version:
 - OS: 12.4.8
 - Browser: [e.g. chrome, safari] safari
 - Device: [e.g. iPhone6] iPhone 6

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
When tapping on:

> ![search result](https://user-images.githubusercontent.com/134745/93687789-40975a80-fa75-11ea-87be-376ac010327c.png)

I see this:

> ![www google com_amp_s_health-innovations org_(Pixel 2 XL)](https://user-images.githubusercontent.com/134745/93687780-29586d00-fa75-11ea-8c12-8d5157f478c6.png)

It appears you had the AMP plugin active with Reader mode selected and the Twenty Twenty chosen as the Reader theme.

If the homepage specifically was not working properly, then you could have configured the plugin to only be active for singular blog posts:

> ![supported-templates](https://user-images.githubusercontent.com/134745/93687876-3f1a6200-fa76-11ea-9198-445aaccd8b2f.png)

As for why Google Search is still showing the AMP pages in search results, the reason is that the pages have been cached. Once they are recrawled then the AMP results will go away.

You can ask Google to re-recrawl your site using the information provided here: https://support.google.com/webmasters/answer/6065812?hl=en

**Comment by Healthinnovations** [comment]
Hi Weston, unfortunately the faulty AMP page url is :
https://www.google.co.uk/amp/s/health-innovations.org/

I cannot ask google to recrawl this url as it is not my property.

Any ideas on how to get this recrawled by google or removed from google
search results altogether?

Do you know of any third party recrawl systems that can reindex this page?

Thanks Michelle

**Comment by westonruter** [comment]
That URL is for Google's AMP viewer. The actual URL the viewer is pointing to is https://health-innovations.org/

So ask Google to re-crawl that URL.

**Comment by Healthinnovations** [comment]
Already done, thank you for your help.

Enjoy the rest of your weekend.
