### ISSUE TITLE
Validation requests fail due to infinite recursion when Reader theme is selected

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5409]
## Bug Description

I noticed that when a Reader theme is selected, attempting to validate a URL will fail:

![image](https://user-images.githubusercontent.com/134745/93721486-7f94e100-fb45-11ea-81db-cd48eecd6d60.png)

The PHP error log includes:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 978944 bytes) in /app/public/content/plugins/amp/includes/validation/class-amp-validation-manager.php on line 1328

The issue is that there is either infinite recursion or infinite loop happening here:

https://github.com/ampproject/amp-wp/blob/27718b00bfbaacd4013f1cdbb590dc3f4371b4bf/includes/validation/class-amp-validation-manager.php#L1313-L1323

When the hook is one of:

* `template`
* `stylesheet`
* `pre_option_template`
* `pre_option_stylesheet`
* `pre_option_template_root `
* `pre_option_stylesheet_root`

This function loop will continue on infinitely and PHP will run out of memory.

These hooks are added by the `ReaderThemeLoader`:

https://github.com/ampproject/amp-wp/blob/27718b00bfbaacd4013f1cdbb590dc3f4371b4bf/src/ReaderThemeLoader.php#L321-L346

I believe this is a regression introduced by #5289. Specifically, the issue is with `FileReflection` in these methods:

https://github.com/ampproject/amp-wp/blob/27718b00bfbaacd4013f1cdbb590dc3f4371b4bf/src/DevTools/FileReflection.php#L216-L270

We need to avoid calling `get_template_directory()` and other such functions 

## Expected Behaviour

Validation should succeed.

## Steps to reproduce

1. Activate Reader mode.
2. Select a Reader theme.
3. Validate a page.
4. See error.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA passed**

With Reader mode active and when the legacy theme or a Reader theme is selected, validating a URL does not throw an error:

![image](https://user-images.githubusercontent.com/16200219/93946001-a7dc3580-fd27-11ea-8eac-5f535d82f8ab.png)
