### ISSUE TITLE
Automatically add Google Analytics (and others?) when they are already enabled

### ISSUE THREAD

**Issue by gibrown** [Automattic/amp-wp#541]
From https://www.alexkras.com/google-may-be-stealing-your-mobile-traffic/ there is a general concern about traffic not being reflected in a sites stats.

Can the plugin detect when the major analytics engines have been added already and just hook them in by default. The user already took the time to set them up, would be good to respect those wishes.

**Comment by amedina** [comment]
We are working on facilitating the addition of analytics options using the Options API: https://github.com/Automattic/amp-wp/pull/714
