### ISSUE TITLE
Enqueued block scripts and styles show as coming from AMP instead of actual plugin

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5411]
## Bug Description

In legacy Reader mode, I noticed that when Jetpack is active and I add a block that enqueues a stylesheet, the stylesheet shows as the AMP plugin being the source as opposed to Jetpack:

> ![image](https://user-images.githubusercontent.com/134745/93722996-cb4c8800-fb4f-11ea-8e2b-5f118b60e763.png)

When a Reader theme is selected, it shows Gutenberg as the source:

> ![image](https://user-images.githubusercontent.com/134745/93722978-b1ab4080-fb4f-11ea-92bc-f6bc33c85bb1.png)

When Gutenberg is deactivated, it shows `wp-includes` as the source:

> ![image](https://user-images.githubusercontent.com/134745/93722966-96d8cc00-fb4f-11ea-9d35-57abad181ce6.png)

The same happens for scripts which are enqueued from a block.

When a script is enqueued due by a block, make sure it is attributed as the source. The [Bad Block plugin](https://gist.github.com/westonruter/e4331b3f6d03aac075b86b226acd3ba5) is an example of this, specifically for a script which is registered _and_ enqueued in the `render_callback`:

![image](https://user-images.githubusercontent.com/134745/122611514-4dfa6900-d036-11eb-82c3-e804f0ac782d.png)

Interesting, if it is registered beforehand then its attribution is correctly identified.

## Expected Behaviour

The plugin responsible for enqueueing a block should be shown as the source.

## Steps to reproduce

1. Activate Jetpack.
1. Add the Eventbrite block.
1. Validate the AMP page.
1. Look at the Stylesheets metabox.

And:

1. Activate the Bad Block plugin
2. Add the block to a post
3. Save and validate
4. See that the script source is not shown to be bad-block.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by dhaval-parekh** [comment]
Currently, the Issue is not able to reproduce with the current version of the Jetpack plugin along with previous versions of it (First scenario). However, the Issue is able to reproduce with the "Bad Block" plugin (second scenario), But in the stylesheet meta, It shows AMP and Bad Block as source plugins.

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/8168027/129690607-280a1825-4859-4291-aa96-a5767c99f721.png">

@westonruter @pierlon

**Comment by westonruter** [comment]
Another issue which may actually be the same as this one: #6231.

**Comment by delawski** [comment]
**QA In Progress**

⚠️ After activating the Bad Block plugin, adding a block to a post and revalidating the post, the Sources contains both Bad Block and AMP:

![Screenshot 2021-12-03 at 15 04 14](https://user-images.githubusercontent.com/478735/144616065-28681571-945c-4322-8aef-ea0f41ee500f.png)

As far as I understand, the Sources should attribute those issues to Bad Block only. Is that correct?

**Other notes:**
- I got the same result no matter if Gutenberg was activated or not.
- The Jetpack Eventbrite Checkout block doesn't cause any AMP validation issues for me so I skipped this test.

**Comment by westonruter** [comment]
Hummm. I'm not seeing that:

![image](https://user-images.githubusercontent.com/134745/144653557-3eb53ba8-dfab-42dc-ae84-9e2cd29b1e06.png)

**Comment by delawski** [comment]
**QA Passed**

✅ I've downloaded the latest 2.2-alpha production build of the and reinstalled the plugin on my local environment. When I repeated the QA process, the Sources column correctly stated that the "Bad Block" is the only source of the validation errors:

![Screenshot 2021-12-06 at 12 50 49](https://user-images.githubusercontent.com/478735/144841609-79862404-cf3e-49bb-a941-a6c32b2dd425.png)
