### ISSUE TITLE
Increase clarity and improve placement of featured image size recommendation

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5416]
## Feature description

While reviewing #5412, I came across a feature of the plugin that I've never noticed before. When you select a featured image that is less than 1200 pixels wide, you see this message at the bottom of the media upload modal:

<img width="696" alt="Screen Shot 2020-09-22 at 8 43 47 AM" src="https://user-images.githubusercontent.com/9020968/93890578-1bdaf700-fcb0-11ea-9b60-891d2e8d194b.png">

I have a few suggestions around this notice:

1) Since this image looks like a core notice and doesn't mention anything about the AMP plugin, if I hadn't just reviewed #5412 I might assume it's a core notice (and would wonder when this change was made, as I have gone against that recommendation thousands of times in the past). The reason for the recommendation should be made clear. If I understand correctly, it derives from the recommendations here: https://developers.google.com/search/docs/data-types/article#article_types But valid structured data might not be important to all users. 
2) Since there are use cases for smaller featured images for templating purposes (e.g., if the image is used in a small card in an archive but never in the single-post template), we might consider a separate UI for the structured data image. It could include a "Override featured image in structured data" toggle which would use the article featured image when on and, when off, would allow a different image to be set. This could be in the AMP plugin sidebar and could include a brief description of why it matters.
3) Regardless of whether we do anything with # 2, this notice is buried and should be displayed more prominently. Otherwise, it might as well not exist. 
4) On a technical level the notice's current implementation is heavily reliant on core functionality that tends to be in flux. Hence the feature is prone to additional bugs like the one addressed in #5412. I suggest working out an approach that doesn't override or filter anything from core (the plugin sidebar option would help with this).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> 1. The reason for the recommendation should be made clear. If I understand correctly, it derives from the recommendations here: https://developers.google.com/search/docs/data-types/article#article_types But valid structured data might not be important to all users.

That is correct. The reason it doesn't mention AMP specifically, is that it is a general Google Search recommendation/requirement. Nevertheless, you're right that some users won't care. It's just that when Google Search Console complains about missing structured data or an image that is too small, we want to be able to say that we warned them.

**Comment by turtlepod** [comment]
@westonruter Is there a way/filter to remove this featured image notice?

**Comment by pierlon** [comment]
@turtlepod That can done by removing the `ampEditorBlocks/withMediaLibraryNotice` filter:

```js
import { removeFilter } from '@wordpress/hooks';

removeFilter( 'editor.MediaUpload', 'ampEditorBlocks/withMediaLibraryNotice' );
```

Or alternatively,

```js
wp.hooks.removeFilter( 'editor.MediaUpload', 'ampEditorBlocks/withMediaLibraryNotice' );
```
