### ISSUE TITLE
Add "visit site" link to top of AMP content

### ISSUE THREAD

**Issue by gibrown** [Automattic/amp-wp#542]
A general concern is that it is not possible for users to get back to the original site. The header does do this, but is not very clear. (https://www.alexkras.com/google-may-be-stealing-your-mobile-traffic/)

A similar issue exists in the WP.com Reader, and we're adding more prominent visit links into the display: https://github.com/Automattic/wp-calypso/issues/8791

Though I admit, maybe this should not be implemented within the AMP page.

Showing recent/related content maybe solves the same problem: https://github.com/Automattic/amp-wp/issues/124#issuecomment-254360266

**Comment by amedina** [comment]
I think you are correct: this should be implemented as part of the AMP page and not inserted by the plugin.

**Comment by gibrown** [comment]
@amedina should we keep this open to track it? This seems to be a constant thing that comes up with sites in Google search. 

![2017-07-06 07 33 18](https://user-images.githubusercontent.com/820871/27913576-cd2a4c9e-621d-11e7-955e-03e6867e5a12.png)

The header gets hidden, and even if you can see the header, then it is not immediately obvious that it is a link. To some extent this is Google's problem, but I think our default page could be a lot better and address this.

**Comment by amedina** [comment]
Hi @gibrown; I agree this is an important issue. It falls into the more general goal of improving the quality of the templates used by the plugin in paired mode (i.e. AMP vs. non-AMP). I opened an issue for that and referenced this one there. Let's track both together there.

**Comment by gibrown** [comment]
Sounds great, thanks!
