### ISSUE TITLE
Helper function assertSimilarMarkup() strips attributes instead of normalizing them

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5420]
## Bug Description

The helper function `assertSimilarMarkup` in the `MarkupComparison` trait is supposed to normalize all of the HTML that would cause a strict string comparison to fail but not actually have an effect on how the HTML is interpreted, like the presence or absence of an attribute's empty value (`foo` <=> `foo=""`).

However, the code to normalize the attributes within each element is broken and actually fails to return the attributes. Therefore, only the element itself is compared, and attributes are just ignored even if completely different.

This has caused a few proper test failures to slip through that need to be fixed.

## Expected Behaviour

`assertSimilarMarkup()` should flag anything that is an actual difference in how HTML is interpreted.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
I'm not able to come up with a test case to QA this. Any insight @westonruter or @schlessera?

**Comment by schlessera** [comment]
I would adapt a test so that it changes an attribute value of an element only. The previous behavior did not catch these, as all attributes were just stripped. The new behavior should notice this discrepancy.

**Comment by pierlon** [comment]
**QA Passed**

Before this change, assertions would fail if element attributes were not in the same order. For example, given the test case:

```php
<?php

use PHPUnit\Framework\TestCase;
use AmpProject\AmpWP\Tests\Helpers\MarkupComparison;

class Test_5420 extends TestCase {

	use MarkupComparison;

	public function test_markup_comparison() {
		$this->assertSimilarMarkup( '<p foo bar></p>', '<p bar foo></p>' );
	}
}
```

Before this the result would be:

```
There was 1 failure:

1) Test_5420::test_markup_comparison
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    1 => '<p foo bar>'
+    1 => '<p bar foo>'
     3 => '</p>'
 )
```

And after this change the test now passes:

```
.                                                                   1 / 1 (100%)

Time: 2.1 seconds, Memory: 66.50MB

OK (1 test, 1 assertion)
```
