### ISSUE TITLE
amp-youtube validate fail

### ISSUE THREAD

**Issue by amandacatraca** [Automattic/amp-wp#543]
The alert 'The attribute 'rel' may not appear in tag 'amp-youtube'.' show to me but have this hell in amp-youtube tag : rel="nofollow" .

help please.

**Comment by mjangda** [comment]
Can you provide an example post URL? How is the YouTube video being added to the post?

**Comment by amandacatraca** [comment]
This for exemple: https://catracalivre.com.br/geral/inusitado/indicacao/justin-bieber-sai-do-palco-apos-ser-vaiado-por-fas-veja-video/amp/#development=1

**Comment by amedina** [comment]
The provided link is validating successfully.
