### ISSUE TITLE
Hide bulk action buttons when all selected validation errors are already in given state

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5431]
## Feature description

In #5427, two new buttons for “Mark reviewed” and “Mark unreviewed” were added to go alongside “Remove” and “Kept” when selecting one for more validation errors on the validated URL screen. 

Something that I realized is that if you have selected validation errors which are already removed, should the "Remove" button even be shown? Similarly, once you select all and click the "Mark reviewed" button so that all validation errors go into the reviewed state, should not the "Mark reviewed" button be hidden? 

For example, with all validation errors being removed and reviewed, the Remove and Mark reviewed buttons now do _nothing_ when clicked:

![image](https://user-images.githubusercontent.com/134745/94309941-b5630c80-ff2d-11ea-95df-e21e4dd34126.png)

Either such buttons should be disabled or else hidden. This should should take into account the validation errors which have currently been selected, so the Remove and Mark reviewed buttons should be hidden here:

![image](https://user-images.githubusercontent.com/134745/94310086-f0654000-ff2d-11ea-8220-c88ab0319391.png)

In these cases, the available buttons could be just:

![image](https://user-images.githubusercontent.com/134745/94310316-505be680-ff2e-11ea-8a31-284f42cf95fa.png)

All 4 bulk action buttons would only be shown if all 4 (inverse) states states are currently selected, like so:

![image](https://user-images.githubusercontent.com/134745/94310448-7e412b00-ff2e-11ea-8b5a-2c3d15ea3588.png)

The available buttons should be updated whenever any change is made to a validation error in the table.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by amedina** [comment]
This makes sense. It will improve the experience by making the UI more intuitive.
