### ISSUE TITLE
Error in required structured data element

### ISSUE THREAD

**Issue by rith423** [Automattic/amp-wp#5432]
I have received the notification today "Error in required structured data element"  How to solve this issue?

error link - https://www.percentageformula.com/blog/best-eyeliner-brands-in-india/amp/
https://www.percentageformula.com/blog/best-speaker-brands-in-india/amp/
https://www.percentageformula.com/blog/mamaearth-wow-wednesday-offer/amp/

**Comment by westonruter** [comment]
I'm seeing an error:

> ShoppingCenter is not a known valid target type for the publisher property.

But this is happening on your non-AMP page as well. The Schema.org markup here is not coming from the AMP plugin but some other plugin. You'll need to report the issue elsewhere.

**Comment by rith423** [comment]
For deals and coupon websites which property you preferred?

**Comment by westonruter** [comment]
I don't have any recommendations nor preferences.
