### ISSUE TITLE
the conflict between the "AMP" plugin and 	 "WP Google Search" plugin

### ISSUE THREAD

**Issue by papyon2016** [Automattic/amp-wp#5439]
When I activate the AMP plugin, the WP Google Search" plugin is not visible.
In the first image,  the AMP plugin is activated.
![the AMP is activ](https://user-images.githubusercontent.com/28312311/94377932-8b743a80-0125-11eb-9016-42ec2512ad29.PNG)
In the second image, the AMP plugin is not active.
![the AMP is not activ](https://user-images.githubusercontent.com/28312311/94377933-8e6f2b00-0125-11eb-8dfa-888c0a047d44.PNG)
what should I do?
This search engine is very important to us.
Please guide me on what can I do?
Best regards.

**Comment by westonruter** [comment]
Are you referring to this plugin? https://wordpress.org/plugins/wp-google-search/

**Comment by papyon2016** [comment]
Yes sure.
As I mentioned yesterday.
Can you tell me what's wrong?
Thanks

*Papyon*

**Comment by westonruter** [comment]
It appears that the search box is added with JavaScript. If I go to your site currently without AMP and turn off JavaScript in my browser, it is also missing. 

The plugin is adding JS widget code that is incompatible with AMP. Apparently there is an alternative to just put a plan `form` into the page. See:

* https://stackoverflow.com/a/62068893
* https://support.google.com/programmable-search/thread/22437013?hl=en

**Comment by papyon2016** [comment]
Hello.
Thanks for your tips.
It was a good tutorial and I used the code you gave me and the problem was solved.
But another contradiction has arisen for me
This is my site address:
https://www.iranntv.com/
Menus are not visible on mobile.
And couldn't click on the menu.
Also on mobile on the following page:
https://www.iranntv.com/livestream/
Live audio LiveStream does not work. But LiveStream works as well.
![Audio LiveStream not work properly](https://user-images.githubusercontent.com/28312311/94745636-611bba80-037b-11eb-9732-ca7a41cbe52c.PNG)
![Audio LiveStream work as well without AMP](https://user-images.githubusercontent.com/28312311/94745641-6416ab00-037b-11eb-9ca9-b7d3c43919e3.PNG)
It is clear that at one point the JavaScript function was taken.
Can you help?
Thank you.

**Comment by westonruter** [comment]
The menu probably doesn't work because it also relies on JavaScript. You can find a guide for how make this work in AMP here: https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/
