### ISSUE TITLE
amp-next-page theme styles removed due to CSS Tree Shaking 

### ISSUE THREAD

**Issue by rickalee** [Automattic/amp-wp#5444]
## Bug Description

amp-next-page default separator styles are removed because markup is not in HTML. 

amp-next-page-links
amp-next-page-link
amp-next-page-image
amp-next-page-text

## Expected Behaviour

Styles should not be removed for templates using amp-next-page

**Comment by westonruter** [comment]
Are you referring to this [styling](https://amp.dev/documentation/components/amp-next-page/?format=websites#styling)?

> ![image](https://user-images.githubusercontent.com/134745/94470655-d40b1280-017c-11eb-936b-002935ef43b2.png)

Are you saying that any style rule with a selector that refers to one of those classes are getting tree-shaken?

**Comment by westonruter** [comment]
@rickalee Please test the changes in this PR: https://github.com/ampproject/amp-wp/pull/5445.

**Comment by westonruter** [comment]
@rickalee Please confirm the PR fixes your issue and we'll include in 2.0.5.

**Comment by rickalee** [comment]
@westonruter Confirmed. Removed dummy markup with same classes and styles still persist with tree shaking. Thank you for the quick turnaround.

**Comment by pierlon** [comment]
@westonruter Not related to this issue, but while doing QA I noticed the pages being loaded were not AMP; you would have to use the canonical AMP URL when specifying the URL for the page. Do we want to sanitize this component to allow for AMP-to-AMP navigation, or should we leave as is?

**Comment by westonruter** [comment]
Wouldn't it be up to the developer providing the `amp-next-page` configuration to use paired AMP URLs if not in Standard mode?

**Comment by pierlon** [comment]
Hmm yea that's true. Given that you would have to provide the config manually, you'd might as well use the paired AMP URL. It was just a bit unexpected to see the non-AMP page loaded and not the AMP counterpart, with AMP-to-AMP linking being a thing.

**Comment by westonruter** [comment]
It's a good question. Beyond being unexpected, doesn't AMP require the next pages to be AMP pages anyway? Does it even work if they aren't AMP pages? If it's not an AMP page, I should think that the component should actually navigate to the page or abort entirely.

**Comment by pierlon** [comment]
> Does it even work if they aren't AMP pages?

Yes, as soon as a non-AMP page is loaded the page is no longer valid AMP:

![image](https://user-images.githubusercontent.com/16200219/95503222-98e9ba00-099a-11eb-9913-1838c96d8105.png)

The AMP Validator and the errors in the web console warns the developer about the issue so I'd say that's sufficient in that regard.

**Comment by pierlon** [comment]
Oh wait, after taking a second look, the AMP Validator is validating each page separately, and not the whole page itself.

**Comment by pierlon** [comment]
**QA Passed**

Styling the appearance of the recommendation box is not tree-shaken. For example, with this markup:

```html
<style>
.amp-next-page-text {
   border: dotted;
}
</style>

<p>Post content.</p>

<amp-next-page>
  <script type="application/json">
    [
      {
        "image": "https://qa-wordpress.lndo.site/wp-content/uploads/2020/10/fire.jpeg",
        "title": "Hello World",
        "url": "https://qa-wordpress.lndo.site/2020/10/08/hello-world/"
      },
      {
        "image": "https://qa-wordpress.lndo.site/wp-content/uploads/2020/10/squirrel.jpg",
        "title": "Sample Page",
        "url": "https://qa-wordpress.lndo.site/sample-page/"
      }
]
  </script>
</amp-next-page>
```

The style is correctly applied to the `amp-next-page-text` element and is not tree shaken:

![image](https://user-images.githubusercontent.com/16200219/95511117-85dce700-09a6-11eb-9280-358fb093c295.png)
