### ISSUE TITLE
Previews: date is incorrect

### ISSUE THREAD

**Issue by jeherve** [Automattic/amp-wp#5449]
## Bug Description

In pre-publish previews, the post date does not appear to be correct. It is set to "51 years ago".

## Steps to reproduce

1. Go to Posts > Add New
2. Write a bit of content, and click on the AMP icon to preview your post.
3. In the window that opens, the post date is incorrect.

## Screenshots

![image](https://user-images.githubusercontent.com/426388/94676206-4154aa00-031b-11eb-98a0-1a5bc28e38b6.png)

**Comment by pierlon** [comment]
I'm able to replicate the bug on v2.0.4 with Reader mode active using the Legacy Reader theme.

**Comment by westonruter** [comment]
This is probably an issue going back to the beginning of the plugin. The issue is that a draft post has a `post_date` of `0000-00-00 00:00:00`. We probably just need to add a condition for that and use `time()` instead.

**Comment by johnwatkins0** [comment]
QA is passing on this.

1. Switched to Reader mode with legacy theme
2. Started creating a post
3. Clicked the AMP preview button
4. Saw "1 second ago" instead of something like "51 years ago"
