### ISSUE TITLE
AMP Developer Tool Missing

### ISSUE THREAD

**Issue by Elvisfrog** [Automattic/amp-wp#5453]
## Bug Description

I can't see the AMP Developer Option - I am Admin, I have been using AMP from early on and upgraded along the way, I have enabled WP troubleshooting mode with just the AMP installed and still don't see it, I even tried the code to Enable for all users: https://amp-wp.org/documentation/getting-started/developer-tools/adjustable-dev-tools/#enabling-dev-tools-for-non-admin-users but nothing, I even uninstalled ran the delete script: 
1. Remove AMP settings data: wp option delete amp-options
2. Remove all amp_validated_url posts: wp post delete $(wp post list --post_type='amp_validated_url' --format=ids)
3. Remove all amp_validation_error terms: wp term list amp_validation_error --field=term_id | xargs wp term delete amp_validation_error
4. In case you’re using AMP Stories: Remove all amp_story posts: wp post delete $(wp post list --post_type='amp_story' --format=ids)
Though Number 3 gave me an error saying "amp_validation_error" did not exists and then: xargs: wp: Permission denied
Part of the issue is when AMP is enabled "Updates" on pages or post take forever long and can't figure out why, so was going to use the Developer Tools to find out more.  

## Expected Behaviour

Developer Tool to show, does not list in admin bar or settings options.

## Steps to reproduce

Can't reproduce as it does not produce, uninstall, delete database still nothing,

## Additional context

 - WordPress version:5.5.1
 - Plugin version:2.0.4
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Transitional
 - PHP version:7.4.10
 - OS: Apache/2.4.46 (cPanel) OpenSSL/1.1.1h mod_bwlimited/1.4 mod_fcgid/2.3.9
 - Browser: [e.g. chrome, safari] Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Have you enabled AMP Developer Tools in your user profile?

![image](https://user-images.githubusercontent.com/134745/94941719-29e7ff00-048a-11eb-91d8-506cd406c5b5.png)

**Comment by Elvisfrog** [comment]
Didn't know to check but looked and:
[cid:5003f1dd-402e-4854-9b28-e7fe6d972988]
That is from my profile.

Joseph

Director of Digital Operations
Fort Worth Business Press
fortworthbusiness.com<https://outlook.office.com/mail/options/mail/fortworthbusiness.com>

________________________________

**Comment by westonruter** [comment]
I can't see your screenshot.

**Comment by Elvisfrog** [comment]
Oh, sorry, well yes enabled it was already.

Joseph

Director of Digital Operations
Fort Worth Business Press
fortworthbusiness.com<https://outlook.office.com/mail/options/mail/fortworthbusiness.com>

________________________________

**Comment by westonruter** [comment]
You've opened a few support topics in addition to this issue, so I'm going to close this in favor of your existing support topic you have open: https://wordpress.org/support/topic/amp-enabled-slow-post-update-or-publish/
