### ISSUE TITLE
Core Web Vitals Score Issues

### ISSUE THREAD

**Issue by fthead9** [Automattic/amp-wp#5457]
I'm testing our latest theme https://cbdserenity.sitedistrict.com/ for Core Web Vitals scores using Lighthouse. The results and suggestions are puzzling. 
https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fcbdserenity.sitedistrict.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext

https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fcbdserenity.sitedistrict.com%2Fshop%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext

The theme incorporates the AMP plugin but for improving (Elminate render blocking resources) we're getting a suggestion to use AMP Optimizer, which to my understanding is now built into the AMP plugin. Is that incorrect? 

We're also getting a suggestion to remove unused JavaScript, which is all related to the AMP plugin. Any suggestions on what can be done to improve that? 

Just overall I'm trying to make a case for AMP as a great solution for getting high Core Web Vitals scores but we're getting a poor score for Largest Contentful Paint and only moderate scores for FCP and Time to Interactive. Is there anything we can do to improve those scores? 
Thanks
Toren

**Comment by westonruter** [comment]
> We're also getting a suggestion to remove unused JavaScript, which is all related to the AMP plugin. Any suggestions on what can be done to improve that?

For this, please see https://github.com/ampproject/amphtml/issues/28638

> The theme incorporates the AMP plugin but for improving (Elminate render blocking resources) we're getting a suggestion to use AMP Optimizer, which to my understanding is now built into the AMP plugin. Is that incorrect?

This is misleading. See https://github.com/GoogleChrome/lighthouse/issues/10045. Yes, the Optimizer is part of the AMP plugin now, and I can see that your page is successfully server-side rendered.

> Just overall I'm trying to make a case for AMP as a great solution for getting high Core Web Vitals scores but we're getting a poor score for Largest Contentful Paint and only moderate scores for FCP and Time to Interactive. Is there anything we can do to improve those scores?

The LCP is going to be drastically improved by prerendering the hero image which is coming in v2.1. See https://github.com/ampproject/amp-wp/pull/5350.

Additionally, AMP intends to deprecate `amp-img` in favor of `img`, which will further improve LCP generally since the AMP JS won't have to load to build those images.

**Comment by fthead9** [comment]
Thanks @westonruter I'm glad there are some core improvements in the works for improving LCP and understand the issues with Lighthouse suggestions after reading those threads. Any suggestions/updates for improving FCP and TTI?

**Comment by westonruter** [comment]
Make sure you have a good page caching plugin in place. For example, WP Super Cache, WP Rocket, etc.
