### ISSUE TITLE
JS strings are not translated

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5459]
As reported in a [support topic](https://wordpress.org/support/topic/cannot-be-translated-the-initials-settings-page/), the strings in JS are not being translated, or at least they aren't getting loaded properly.

When I activate `es-MX`, I see the admin screen as:

> ![image](https://user-images.githubusercontent.com/134745/95049364-799f1400-069e-11eb-8c61-101dd2ee6726.png)

This is in spite of this language being supposedly 100% translated:

> ![image](https://user-images.githubusercontent.com/134745/95049401-89b6f380-069e-11eb-8a10-b9870a8f91b5.png)

Either the strings aren't getting translated, or we're not loading the translations properly.

**Comment by swissspidy** [comment]
String extraction and actual loading of translations works fine, as can be tested by typing `wp.i18n.__( 'Reopen Wizard', 'amp')` in the console. The problem is that the settings page is bundling `@wordpress/i18n` and not actually using `wp.i18n`.

`@wordpress/i18n` needs to be added as an external in the webpack config, so that calls to `__()` in the code base are mapped to `window.wp.i18n.__()`. Then it will work.

In my quick testing, this change to the settings page config worked:

```diff
diff --git webpack.config.js webpack.config.js
index aab58f6ab..d4571c6ea 100644
--- webpack.config.js
+++ webpack.config.js
@@ -234,6 +234,7 @@ const setup = {
 					case '@wordpress/dom-ready':
 					case '@wordpress/html-entities':
 					case '@wordpress/url':
+					case '@wordpress/i18n':
 						return defaultRequestToHandle( handle );
 
 					default:
@@ -247,6 +248,7 @@ const setup = {
 					case '@wordpress/dom-ready':
 					case '@wordpress/html-entities':
 					case '@wordpress/url':
+					case '@wordpress/i18n':
 						return defaultRequestToExternal( external );
 
 					default:
@@ -293,6 +295,7 @@ const settingsPage = {
 				switch ( handle ) {
 					case 'lodash':
 					case '@wordpress/api-fetch':
+					case '@wordpress/i18n':
 						return defaultRequestToHandle( handle );
 
 					default:
@@ -303,6 +306,7 @@ const settingsPage = {
 				switch ( external ) {
 					case 'lodash':
 					case '@wordpress/api-fetch':
+					case '@wordpress/i18n':
 						return defaultRequestToExternal( external );
 
 					default:
```

This needs to be checked for all other places too.

**Comment by westonruter** [comment]
Hummm. I tried applying that patch and did `npm run dev` but I'm still seeing:

![image](https://user-images.githubusercontent.com/134745/95101258-cd355000-06e6-11eb-8468-cfcd389a5359.png)

Calling `wp.i18n.__( 'Reopen Wizard', 'amp')` returns `'Reopen Wizard'`, not an expected Spanish translation.

**Comment by westonruter** [comment]
cc @johnwatkins0

**Comment by swissspidy** [comment]
Did you update the translations under Dashboard -> Updates?

I tested with the German translation this morning without issues

**Comment by westonruter** [comment]
¡Éxito! 

![image](https://user-images.githubusercontent.com/134745/95103179-2a320580-06e9-11eb-8593-b0c3c16ec554.png)

Gracias.

**Comment by westonruter** [comment]
**QA Passed**

I changed my language to Spanish:

![image](https://user-images.githubusercontent.com/134745/96029405-7b3fa900-0e0f-11eb-90c7-ab79eedabfc1.png)

And the settings screen now shows Spanish translations:

![image](https://user-images.githubusercontent.com/134745/96029451-8f83a600-0e0f-11eb-83d1-30d669f6c5ec.png)

**Comment by davidperezgar** [comment]
Ok! I’ll check it out!

**Comment by westonruter** [comment]
@davidperezgar You'll need to check 2.0.5 which we will be releasing today, or else use 2.0.5-alpha which can be downloaded from: https://storage.googleapis.com/ampwp_github_artifacts/refs/heads/2.0/prod/amp.zip

**Comment by davidperezgar** [comment]
I'll see when you update to wordpress repo trunk...
