### ISSUE TITLE
HTML5 doctype not enforced

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5462]
## Bug Description

Originally discovered in a [support topic](https://wordpress.org/support/topic/the-attribute-public-may-not-appear-in-tag-html-doctype/).

If you edit Twenty Twenty's `header.php` as follows:

```diff
--- a/src/wp-content/themes/twentytwenty/header.php
+++ b/src/wp-content/themes/twentytwenty/header.php
@@ -9,7 +9,7 @@
  * @since Twenty Twenty 1.0
  */
 
-?><!DOCTYPE html>
+?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 
 <html class="no-js" <?php language_attributes(); ?>>
 ```

Then when viewing an AMP page using Twenty Twenty, validation errors are leaked to the frontend:

> ![image](https://user-images.githubusercontent.com/134745/95105929-b09c1680-06ec-11eb-9411-214db4929fe5.png)

## Expected Behaviour

The HTML5 doctype should be enforced when the `Document` is serialized.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
QA is passing on this. I modified the header.php file in the Twenty Twenty theme as Weston describes above and am not seeing any trace of these validation errors.
