### ISSUE TITLE
Aren't inline styles banned via the AMP spec? 

### ISSUE THREAD

**Issue by badfeather** [Automattic/amp-wp#548]
In the [AMP Supported CSS documentation](https://www.ampproject.org/docs/guides/responsive/style_pages), the first banned style that's listed is "Inline style attributes", with the description: "All styles must be defined in the <head> of the page, within a `<style amp-custom>` tag". 

I'm seeing inline styles on all of the inserted images, and on the `<i-amp-sizer>` element. Shouldn't these throw potential validation errors, and is this something that can be overridden in some way? I'm also wondering what the purpose of the sizer and absolute positioning of the image is in general.

**Comment by mjangda** [comment]
`<i-amp-sizer>` is adding by the AMP runtime (i.e. the AMP javascript code) not the plugin.

Can you share an example post where you're seeing the inline styles on images?

**Comment by badfeather** [comment]
Oh, that makes more sense. Explains why I couldn't find any functions inserting that markup in the plugin code. Yes, I was seeing it on the `<i-amp-sizer>` and `<amp-anim>` elements when viewing the source. Thanks for clarifying.
