### ISSUE TITLE
Ensure PHP 8 compatibility of plugin

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#5480]
## Feature description

Given that WordPress 5.6 will be supporting PHP 8, we should ensure that the plugin will be compatible with PHP 8 as well.

As a first step towards that goal we should ensure that our test suites pass without errors when run against PHP 8.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Started QA on this, but not sure what to test for. This looks like some UI bug:

https://v.usetapes.com/Zua3OCs3j0

And here are my Local env settings: https://d.pr/i/ocZ69Z

**Comment by westonruter** [comment]
See also this support forum topic which reports there may be PHP 8 compatibility issues: https://wordpress.org/support/topic/amp-not-compatible-with-php-8/

But this is not entirely surprising given that WP core is considered “beta compatible” with PHP 8 per https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/

**Comment by pierlon** [comment]
Hmm I'm not seeing anything like that on PHP 8:


https://user-images.githubusercontent.com/16200219/115950029-5451e600-a4c8-11eb-92ea-1d06730ebdcc.mp4


I'm running the latest AMP plugin beta (b85f07e8ab219ebf8112b99a8ac9c4b43ea44293) and on the latest nightly WP version (https://github.com/WordPress/wordpress-develop/commit/e4bda140d4437f5bd5690e18bc12a0eb70bb92c9), if that helps.

**Comment by schlessera** [comment]
Just a thought: Given the nature of PHP 8 breakage, our best bet for full compatibility would probably be mutation testing against anything that interfaces with Core or other extensions.

**Comment by schlessera** [comment]
**QA passed**

- Workflow for PHP 8 tests is being executed.
- Workflow for PHP 8 tests does actually use PHP 8:
![Merge pull request #6121 from ampproject_fix_amp_enable_ssr-filter-priority  2021-04-27 at 10 37 18 AM](https://user-images.githubusercontent.com/83631/116220552-b0c13980-a744-11eb-9108-9c704428ca2a.jpeg)
- Workflow for PHP 8 tests does actually run all the tests and they pass:
![Merge pull request #6121 from ampproject_fix_amp_enable_ssr-filter-priority  2021-04-27 at 10 36 33 AM](https://user-images.githubusercontent.com/83631/116220539-adc64900-a744-11eb-8f4c-0c5056656f8b.jpeg)
