### ISSUE TITLE
[amp-imgur] Some Imgur urls are not supported by AMP-WP plugin

### ISSUE THREAD

**Issue by maciejmackowiak** [Automattic/amp-wp#5482]
## Bug Description

AMP WP plugin doesn't account for urls like this one:
https://imgur.com/a/rAG6Q2w

## Expected Behaviour
Account for https://imgur.com/a/{imgur_id} Imgur url format.

How about just replacing:
```
if ( ! isset( $pieces[1] ) ) {
```
with:
```
if ( ! isset( $pieces[1] ) ) {
	$pieces     = explode( '/a/', $parsed_url['path'] );
}
if ( ! isset( $pieces[1] ) ) {
```
in this method:
https://github.com/ampproject/amp-wp/blob/develop/includes/embeds/class-amp-imgur-embed-handler.php#L134

## Steps to reproduce

1. Embed https://imgur.com/a/rAG6Q2w 
2. Go to AMP version of the page

## Additional context

 - WordPress version: Any
 - Plugin version: 2.0.4
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Related: #4697.

**Comment by pierlon** [comment]
**QA Passed**

When embedding the URL https://imgur.com/a/rAG6Q2w, the embed does show on the AMP page:

![image](https://user-images.githubusercontent.com/16200219/96029886-caef9600-0e4a-11eb-9d5e-a0c89c342fed.png)
