### ISSUE TITLE
TwentyTwenty Paired Browsing rem font size discrepancy on mobile

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5495]
## Bug Description

In Paired Browsing on TwentyTwenty, smaller mobile viewports have a discrepancy of the font size for `rem` sizes. Desktop views of the same content don't seem to exhibit the same behavior, so I assume it is related to a media query in some form.

The `font-size` in `rem` units applied by the CSS seems to be the same at first glance, but the resulting pixel size is different.

## Expected Behaviour

Font sizes should be the same for both sides of paired browsing across all devices.

## Steps to reproduce

1. On a site with TwentyTwenty, enter Paired Browsing mode.
2. Enter the Developer Tools.
3. Toggle the device toolbar.
4. Choose a small mobile device.

## Screenshots

![Image 2020-10-10 at 10 00 50 AM](https://user-images.githubusercontent.com/83631/95649825-e28fed00-0adf-11eb-85c8-c620c65db36f.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Strange. I'm not seeing any difference in styling.

Non-AMP | AMP
----------|-------
![image](https://user-images.githubusercontent.com/134745/95664222-956d4480-0afa-11eb-855d-0e06e0b01cd7.png) | ![image](https://user-images.githubusercontent.com/134745/95664215-87b7bf00-0afa-11eb-8479-b76c62b5d207.png)

**Comment by schlessera** [comment]
As I mentioned, the generated CSS is the same, but the computed pixel values differ, probably because of a change in the inheritance tree and its effect on the relative nature of the `rem` unit.

**Comment by schlessera** [comment]
### Computed `font-size` of a `<p>` for non-AMP:

![Image 2020-10-19 at 10 13 45 AM](https://user-images.githubusercontent.com/83631/96419034-def11a00-11f3-11eb-863b-fcc733618f7c.png)

### Computed `font-size` of a `<p>` for AMP:

![Image 2020-10-19 at 10 13 57 AM](https://user-images.githubusercontent.com/83631/96419064-e7e1eb80-11f3-11eb-831d-18842009d859.png)

(Note the difference in computed pixel size for these two)

**Comment by westonruter** [comment]
I found the cause. It's `ampshared.css`:

![image](https://user-images.githubusercontent.com/134745/96519417-d0b9f280-1221-11eb-9b28-ae32b2933741.png)

Here's the source: https://github.com/ampproject/amphtml/blob/292dc66b8c0bb078bbe3a1bca960e8f494f7fc8f/build-system/tasks/create-golden-css/css/main.css#L54-L59

Explanation:

> Text adjust is set to 100% to avoid iOS Safari bugs where the font-size is sometimes not restored during orientation. See https://github.com/ampproject/amphtml/issues/449.

This is 5 years old. It may be time to revisit whether that code is still necessary.

**Comment by westonruter** [comment]
If this is exclusively an issue with paired browsing where text is made unnaturally small, then it may not be something we should worry about fixing.
