### ISSUE TITLE
Request: standardized local dev and test environments with out-of-the-box testing/linting

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5499]
### Ideal

If I'm a newcomer to this repo and hoping to contribute, I will:

1. Find the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines).
2. Find the "Local Development" section. I'll follow those steps to get an environment set up with the latest develop branch.
3. Follow the remaining sections of the Engineering Guidelines to learn how to build assets, run linting, and run tests, or I will check the `package.json` file to see what commands are available. In an ideal scenario, everything works out of the box, even if I'm a beginning developer with no Docker knowledge and no familiarity with the common WP development practices.

### Reality

As a new developer on the project, steps 1 and 2 above work. I'm able to clone the repo and run a few commands to get an environment at http://localhost:8890 with login credentials displayed in my terminal window. Several of the commands related to linting and JS testing work.

There are two main problems, however.

#### 1. PHPUnit doesn't work

The engineering guidelines say:

```
To run the full test suite, you can use the following command:

npm run test:php
```

When I run this having only followed the Engineering Guidelines, it doesn't work because I'm running it in my Mac OS environment. I might not have PHPUnit installed globally on my system, and even if I did, the PHPUnit bootstrap file is going to look for a test environment that I don't have on my local file system, so `phpunit` will fail. 

Personally, in order to run the PHPUnit tests locally, I have set up the repo in my preferred Docker-based local environment, I've modified the `install-wp-tests.sh` and `bootstrap.php` files, I've installed PHPUnit in the repo with Composer, and I run tests from inside the Docker environment. It works, but I always have to be careful not to commit the several files I've modified to get tests to work, and I have to clear those modifications frequently when changing branches. It's not the most developer-friendly approach.

#### 2. The E2E tests use the local dev environment

The e2e test command (`npm run test:e2e`) runs inside the same environment that the Engineering Guidelines have instructed me to set up for local development. While the test command works, do I really want to have the Puppeteer bot changing things in the environment where I'm also doing my own in-browser testing? Also, doesn't the e2e test suite need to be able to make assumptions about the environment? If I'm working within the environment, I could be adding/creating posts, adding/removing plugins, etc., so the test suite can't reliably start in a known state.

## Suggested approach

1. Provide a command to install a local environment meant as a sandbox for the developer as a user, untouched by any automated test process.
2. Provide a command to install a test environment that is not meant to be accessed by a human. This is where PHPUnit and e2e tests can run. This environment would need to be reset between e2e runs.
3. Ensure that all commands available in package.json run out of the box. I should be able to clone this repository and run `composer install && npm install && npm run test:php` to see the PHPUnit test suite run successfully, with no other steps required.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Done in #6802
