### ISSUE TITLE
YouTube Videos not working

### ISSUE THREAD

**Issue by luckycabarlo** [Automattic/amp-wp#55]
Iframes and links from youtube are not working in my amp post. Showing this console error
"Expected width to be available and be an integer/length value: null"
"Blocked script execution in '**youtube link**' because the document's frame is sandboxed and the 'allow-scripts' permission is not set"

**Comment by mjangda** [comment]
Thanks for the report @luckycabarlo. YouTube support has not been added to the plugin yet, see #5
