### ISSUE TITLE
Using ?amp=1 with pretty link enabled

### ISSUE THREAD

**Issue by doodirock** [Automattic/amp-wp#550]
Hey all, 

I've come across a need to use **?amp=1** instead of **/amp** while having pretty link still enabled on the site.  I'm using a ton of custom rewrites and would rather just force my rel to use the param and not figure out rewrites.  Any easy way to do this?

**Comment by mjangda** [comment]
You could hook into `amp_pre_get_permalink`: https://github.com/Automattic/amp-wp/blob/master/includes/amp-helper-functions.php#L4

```
add_filter( 'amp_pre_get_permalink', 'doodirock_amp_force_querystring_permalink' );

function doodirock_amp_force_querystring_permalink( $permalink, $post_id ) {
    return add_query_arg( AMP_QUERY_VAR, 1, get_permalink( $post_id ) );
}
```

**Comment by doodirock** [comment]
Hey thanks @mjangda but it looks like /amp still shows up in the <rel="amphtml"> tag

**Comment by doodirock** [comment]
I just saw https://github.com/Automattic/amp-wp/issues/438 so it looks like this was even accounted for by you.  I wondering if maybe my version is out of date.  Was this added into the latest version?

**Comment by doodirock** [comment]
Yep, that was my issue.  Thanks again for the help!
