### ISSUE TITLE
The code to add nav_menu_dropdown in the AmpForWordpress page has a bug

### ISSUE THREAD

**Issue by pauloemicada** [Automattic/amp-wp#5518]
## Bug Description

In the "Navigation Sub-menu Buttons" section there is a code to add_theme_support, the 'expand_text ' has a space at the end. Should be 'expand_text'. That's important because the custom expand text will not work.

## Expected Behaviour

'expand_text'                 => __( 'expand', 'domain' ),

## Steps to reproduce

1. Go to https://amp-wp.org/documentation/playbooks/navigation-sub-menu-buttons/

## Screenshots

![image](https://user-images.githubusercontent.com/53063924/96372911-a7c13100-113f-11eb-92b1-d6d8fbd6b93e.png)

## Additional context
I know it is not a project code problem, actually before discovering the error I checked the plugin code and saw that it was all correct. It is only in the code to activate the 'nav_menu_dropdown' in the 'add_theme_support'

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Thank you. Fixed.
