### ISSUE TITLE
Automate release management tasks

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5520]
## Feature description

As previously discussed, we should automate most of the tasks that are involved in creating a (major or minor) release.

The following document describes the plan of attack for doing so:
https://docs.google.com/document/d/1Co8Ik4DTPGk_8B8_aJvcArRaMHituyrZszICeQ4v2TE/edit?usp=sharing

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All release chores that don't require human decision-making are automated away via one or more script files.

## Implementation brief

* Create a `prepare-release` script that generates a draft release with collected release notes and a built ZIP file, after doing a series of sanity checks.
* Create a `post-release` script that deploys the updated docs to `amp-wp.org` and completes all administrative tasks to move to the next WIP release in the git repository.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
See also what @swissspidy has been doing for Web Stories: https://github.com/google/web-stories-wp/pull/6343, https://github.com/google/web-stories-wp/issues/6424

**Comment by swissspidy** [comment]
Yay someone noticed it! :-)

I plan on documenting my setup over the next days, but those are good starting points.

**Comment by jwold** [comment]
* PG > Working with Github CLI to find out how best to automate recurring tasks that we have been doing. 
* PG > On the toolbox repo I see Alain has a workflow for checkin. Runs a chron to check if there's a sync for the spec PR; if a PR is open. You can use Github CLI to auto merge an open PR if all checks pass. Once checks pass it immediately merges itself rather than wait an hour to recheck if open PRs. One suggestion so far. 
* PG > Putting together notes to get in sync with Weston and Alain to see if I'm on the right track. Should get those to you by end of day. Making good progress. Just want to share that update before working on the actual issue at hand.

**Comment by swissspidy** [comment]
> * PG > On the toolbox repo I see Alain has a workflow for checkin. Runs a chron to check if there's a sync for the spec PR; if a PR is open. You can use Github CLI to auto merge an open PR if all checks pass. Once checks pass it immediately merges itself rather than wait an hour to recheck if open PRs. One suggestion so far.

There's a built-in GitHub feature for auto-merges: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

**Comment by pierlon** [comment]
@swissspidy Yep that's what I was alluding to. One could add a step to enable auto merge for a PR:

```yaml
steps:
  - name: Enable auto-merge for PR
    run: gh pr merge --auto --merge "$PR_URL"
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Comment by swissspidy** [comment]
Not exactly the same thing, but also possible 👍

**Comment by pierlon** [comment]
Some release steps that can be automated independently in the interim:

- [ ] Creating draft release
    - [ ] Generate changelog
    - [ ] Attach the `amp.zip` build to the release
- [ ] Generating documentation for release branch

**Comment by westonruter** [comment]
Closing in favor of #2741
