### ISSUE TITLE
WP CLI not bootstrapped in PHPUnit environment

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5523]
## Bug Description

In a currently open PR, PHPUnit tests are failing because WP CLI utils are not loaded in the environment. Here's a failing build https://travis-ci.org/github/ampproject/amp-wp/jobs/735392022

## Expected Behaviour

All WP CLI functions and classes should be loaded in the PHPUnit environment for testing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* With WP CLI loaded in the environment, PHPUnit tests should continue to pass just as they do now.

## Implementation brief

* Create a new bootstrap.php file for the plugin's PHPUnit environment
* Load the wp-dev-lib bootstrap file from there
* Also load the WP CLI test bootstrap file

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
**QA passed**

The tests are correctly bootstrapped. However, most of this has been superseded by changes in https://github.com/ampproject/amp-wp/pull/5528
