### ISSUE TITLE
<iframe> elements do not have a title in Lighthouse

### ISSUE THREAD

**Issue by Zabi09** [Automattic/amp-wp#5532]
Added just a youtube video on one of my posts- https://monosnap.com/file/XIXggJgslnAxcMnNLBtHpwA3LXJluT and I am getting this error inside the amp-youtube tag that <iframe> elements do not have a title in Lighthouse - https://monosnap.com/file/0R4ehteXwmLk517l2sp0yKq2vNQw1E

**Comment by westonruter** [comment]
Hi there. This is actually an issue with `amp-youtube` component in AMP core and not the AMP plugin. 

I made this example to show the difference between `amp-youtube` and `amp-iframe`, where the former does not copy the `title` attribute but the latter does: https://amp-iframe-title-attribute-iframe-copying.glitch.me/

For the former, I also see the accessibility audit failure:

> ![image](https://user-images.githubusercontent.com/134745/96917908-50cc9c00-145e-11eb-8835-282153520a14.png)

This is a known issue which is being worked on in AMP. See https://github.com/ampproject/amphtml/issues/29874.
