### ISSUE TITLE
Admin Bar and AMP Standard Mode

### ISSUE THREAD

**Issue by rickalee** [Automattic/amp-wp#5533]
## Feature description

We recently launched a full AMP-first site in Standard Mode. 

One of the other plugins we use requires jQuery and additional JS to power a feature within admin bar. Is there a way to opt into these scripts without them being stripped for logged in editors/admins i.e. we don't need site to validate for logged in users?

**Comment by westonruter** [comment]
@rickalee Yes, please see my blog post: [Integrating with AMP Dev Mode in WordPress](https://weston.ruter.net/2019/09/24/integrating-with-amp-dev-mode-in-wordpress/). There are many such examples found in Site Kit and Jetpack.

This will be further facilitated by #4001.

**Comment by rickalee** [comment]
Thank you @westonruter Exactly what I was looking for.
