### ISSUE TITLE
Cloudinary Plugin Conflict - Can't add new post or page 

### ISSUE THREAD

**Issue by jamesozzie** [Automattic/amp-wp#5534]
## Bug Description

As reported in the WordPress support forums when using the AMP plugin along with the Cloudinary plugin it's not possible to create a new page or post, with the below error appearing:

![image](https://user-images.githubusercontent.com/41326532/97000212-585b7600-152e-11eb-8bde-14d40e7f36ad.png)
As soon as Cloudinary is activated the below console error appears (regardless of whether AMP plugin is active):
```
common.min.js?ver=5.5.1:2 tagsSuggestL10n.tagDelimiter is deprecated since version 5.5.0! Use wp.i18n instead.
a @ common.min.js?ver=5.5.1:2
```

The below console errors appear when editing a post (without the AMP plugin active) - featured images can be accessed

![image](https://user-images.githubusercontent.com/41326532/97001133-c81e3080-152f-11eb-9ba0-6d673f18cb65.png)

As soon as the AMP plugin is active the error occurs as per the initial screenshot above - _The editor has encountered an unexpected error._ The "Attempt recovery" button fails to resolve the issue. 

## Steps to reproduce

1. Install the latest AMP and [Cloudinary](https://wordpress.org/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/) plugins
2. Try to create a new post or page (with the default WordPress editor) 
3. If the editor opens open the Featured image panel and click to open an image 
4. Error appears & it's no longer possible to create a new post or page (or edit existing content)

## Screenshots
![consoleerror](https://user-images.githubusercontent.com/41326532/97002439-e6852b80-1531-11eb-92a8-a0dd4f35baad.gif)

![featuredimg](https://user-images.githubusercontent.com/41326532/97002436-e4bb6800-1531-11eb-8abd-9f3c934547a1.gif)

![image](https://user-images.githubusercontent.com/41326532/97003434-53e58c00-1533-11eb-8dd8-b6016da22bd5.png)

[Full log file here
](https://gist.github.com/jamesozzie/6dd5256a929b93876f5563c6cd0eb118)
## Additional context

 - WordPress version: 5.5.1
 - AMP plugin 2.0.5
 - Cloudinary plugin 2.3.0 
 - Doesn't occur with classic editor, only Gutenburg. Initial report mentions issues with WP Bakery
 - Issue initially didn't occur until clicking feature image button

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by johnwatkins0** [comment]
I'm submitting a fix for this on the Cloudinary plugin repo.

**Comment by westonruter** [comment]
@jamesozzie Thanks for the excellent bug report.
