### ISSUE TITLE
Fatal error resulting from missing request_filesystem_credentials function on settings screen

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5537]
## Bug Description

Bug reported here: https://wordpress.org/support/topic/error-you-might-be-offline-or-logged-out/

## Expected Behaviour

Settings screen should load without an error.

## Steps to reproduce

1. On the `develop` branch
2. Add this Gist as a plugin and activate it: https://gist.github.com/johnwatkins0/993c0e350e2bf7d473d38c7ba3b1598a
3. Go to the AMP settings screen and select Reader mode
4. See the error

## QA testing instructions

* No more errors when the above reproduction steps are followed on the new branch.

## Changelog entry

* Fix fatal error resulting from a skipped core file import.

**Comment by pierlon** [comment]
**QA Passed**

Activated the gist plugin provided by @johnwatkins0 is activated, then went to the AMP settings screen and selected Reader mode and saved the changes. No fatal errors occurred in the process.
