### ISSUE TITLE
Not recognising SSL

### ISSUE THREAD

**Issue by LARAMediaGroup** [Automattic/amp-wp#5544]
## Bug Description

Have installed the AMP plugin on a new site we are setting up (https://thevou.com) and it keeps throwing a message stating that there's no SSL. We have installed and reinstalled the plugin several times, from different computers and different browsers, it is still unable to recognise the SSL.

## Expected Behaviour

Recognise the SSL

## Steps to reproduce

Not sure, see the pics below:

## Screenshots

<img width="1321" alt="11" src="https://user-images.githubusercontent.com/70020782/97299563-075cc200-184d-11eb-8d59-903099046954.png">
<img width="1331" alt="22" src="https://user-images.githubusercontent.com/70020782/97299570-0a57b280-184d-11eb-9224-35c98758f124.png">

## Additional context

Version 2.0.5, same issue on different browsers on different devices.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
The site does seem to have SSL issues though. Although the frontpage shows a secure connection, the "About Us" page (just as an example) is not properly secured.

![Image 2020-10-27 at 4 28 44 PM](https://user-images.githubusercontent.com/83631/97324080-c034f800-1871-11eb-84a7-50f2a02d2be8.png)

![Image 2020-10-27 at 4 30 26 PM](https://user-images.githubusercontent.com/83631/97324095-c32fe880-1871-11eb-998b-809030768265.png)

**Comment by westonruter** [comment]
Make sure that the WordPress Address and Site Address in the site's General Settings both have HTTPS URLs.
