### ISSUE TITLE
is_amp_endpoint() early call warnings during cron & WP CLI command processes

### ISSUE THREAD

**Issue by roborourke** [Automattic/amp-wp#5546]
## Bug Description

Cards on the table this isn't strictly a bug but it didn't fit neatly into any other categories.

The functions like `is_amp_endpoint()` etc log notices when they are used too early however this is assuming the context is always a front end request - except for REST requests it looks like. There are legitimate reasons to run the `the_content` filter in non request contexts, one example being while indexing content in [ElasticPress](https://github.com/10up/ElasticPress), a popular way to use Elasticsearch with WordPress.

In my own personal case indexing is only done via CLI however it can occur during background and even shutdown tasks too.

## Expected Behaviour

The `is_amp_endpoint()` used early notices should not be output during:

- Cron / background tasks
- WP CLI commands

The function would ideally just return `false` in these known scenarios as it does for REST requests.

## Steps to reproduce

1. Install both this plugin and ElasticPress and activate them (alternatively create a basic WP CLI command that runs `the_content` filter on some text.
2. Run the `wp elasticpress index --setup` command (or your custom one)
3. See error log output

## Additional context

 - WordPress version: 5.5.1
 - Plugin version: develop
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version: 7.2
 - OS: Alpine Linux (Docker container running on Mac)
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Got it. It looks like we just need to augment the logic here:

https://github.com/ampproject/amp-wp/blob/125d06d39f533d2ebc98396dd544071ee100657f/includes/amp-helper-functions.php#L412-L415

Would you like to open a PR?

**Comment by roborourke** [comment]
@westonruter ace thanks for the reference - yeah if you're amenable to the change I can do that.

**Comment by johnwatkins0** [comment]
QA passed.

Before this change, when I run a CLI command with `apply_filters( 'the_content', 'test' );`, I get:

> Notice: amp_is_available was called <strong>incorrectly</strong>. `amp_is_available()` (or `amp_is_request()`, formerly `is_amp_endpoint()`) was called too early and so it will not work properly.

After this change, I don't see that warning and the CLI command runs as expected.
