### ISSUE TITLE
Composer 2 Support

### ISSUE THREAD

**Issue by swissspidy** [Automattic/amp-wp#5551]
## Feature description

Looks like some dependencies need to be updated to fully support Composer 2.

For example `cweagans/composer-patches` added support in version 1.7. There's a PR for updating it: #5474. But it fails because of a seemingly unrelated issue with Facebook's oEmbed changing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
cf. https://github.com/google/web-stories-wp/pull/5082

**Comment by pierlon** [comment]
The two dependencies that prevent us from upgrading to Composer v2 are `civicrm/composer-downloads-plugin` and `cweagans/composer-patches`. Of those two, `civicrm/composer-downloads-plugin` still does not support Composer v2 as yet, but https://github.com/civicrm/composer-downloads-plugin/pull/1 should hopefully take care of that soon.

> There's a PR for updating it: #5474. But it fails because of a seemingly unrelated issue with Facebook's oEmbed changing.

That should finally be resolved via #5548. Now that is in we can re-run the tests in #5474 to see if they pass.

**Comment by seamuslee001** [comment]
Just FYI civicrm/composer-downloads-plugin now has a new version 3.0.0 which includes that PR mentioned

**Comment by pierlon** [comment]
Thanks @seamuslee001!

**Comment by seamuslee001** [comment]
just FYI i found a small php issue and fixed it so have pushed up 3.0.1 which should be used
