### ISSUE TITLE
REST endpoints for AMP validation errors and validated URLs

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5552]
## Feature description

For some planned plugin features, we will need data about validation errors and validated URLs to be fetched and updated over REST endpoints.

Although this data is currently represented in the database via the `amp_validation_error` taxonomy and the `amp_validated_url` post type, we should not use or extend`WP_REST_Taxonomy_Controller` and `WP_REST_Post_Controller` because the underlying data structure (which Weston has documented elsewhere) does not neatly map to these core WP object types. A longer-term goal is to move away from the workarounds that have been used to store this data in WP objects and potentially migrate the data into custom tables. So the endpoints should be built to the underlying data schema rather than to the `WP_Post`/`WP_Term` schemas. Then when we're ready to change how the data is stored, we'll just need to update the methods that query the database.

### Summary

- [ ] Endpoint for validation errors
- [ ] Endpoint for validated URLs
- [ ] Both endpoints support reading, ~updating, and creating items~ (see below)
- [ ] All request methods should require authentication
- [ ] Methods interacting with the database should be decoupled to ease transition to a different way of storing the data in the future

Copying this from Weston's comment below for visibility:

> For the endpoint for validation errors…
> - They should not allow creation (as it is the creation of a validated URL which causes validation errors to be created).
> - The only update should be for the removed and reviewed flags. Everything else must be readonly.
> - A validation error can only be deleted if it has no associated validated URLs.

### Related

- #2316 Redesign validation screens
- #3077 Build abstraction layer
- #2069 Eliminate synchronous validation

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> * Both endpoints support reading, updating, and creating items

For the endpoint for validation errors…

* They should _not_ allow creation (as it is the creation of a validated URL which causes validation errors to be created). 
* The only update should be for the `removed` and `reviewed` flags. Everything else must be `readonly`. 
* A validation error can only be deleted if it has no associated validated URLs.

**Comment by pierlon** [comment]
This will be resolved as part of the work on #5772, which will use REST API calls to get information on validation errors and URLs.

**Comment by westonruter** [comment]
@pierlon The scope for #5772 is much reduced, however. For the admin menu, the only thing needed is the _counts_ for the validation errors and validated URLs which are not reviewed. There is no need to expose individual validated URLs nor validation errors. Therefore I think the efforts are related but not directly overlapping.

**Comment by pierlon** [comment]
Yes you're right. I'll revert this back to the original milestone for now.

**Comment by westonruter** [comment]
I have a design doc that lays out what endpoints are needed. I believe everyone has access on the team.

**Comment by westonruter** [comment]
Work in progress via https://github.com/ampproject/amp-wp/pull/6442.

**Comment by westonruter** [comment]
Punting this since we now have what we need for 2.2 via #6615.
