### ISSUE TITLE
0.4 upgrade and custom templates

### ISSUE THREAD

**Issue by smerriman** [Automattic/amp-wp#557]
In the changelog the fact 0.4 has a breaking change to the template is mentioned, but that fully custom templates are not affected.

This isn't quite the case. `amp_post_template_head` is a required hook in custom templates, but 0.4 now adds in a Merriweather Google font request, which is unnecessary in a custom template.

I might be able to hook into the data and remove this somehow, but is this the only fix required? Theme-related changes like fonts should ideally be tied to the template, not a global setting that a custom theme needs to disable.

**Comment by smerriman** [comment]
(Having the font request there doesn't *break* the theme, but it shouldn't be there.)

**Comment by dennisroethig** [comment]
Would be also interested to get some ideas around this? Loading the font is not an option in my case. Any nice solutions for this?

Thanks

**Comment by smerriman** [comment]
@dennisroethig I ended up using the following workaround:

```
add_filter('amp_post_template_data','custom_amp_post_template_data',10,2);
function custom_amp_post_template_data($data, $post) {
	unset($data['font_urls']['merriweather']);
	return $data;
}
```

**Comment by dennisroethig** [comment]
@smerriman ah, thanks a lot for that quick response 👍 I found another issue with a similar solution so I guess that's the way to go for now 😎
