### ISSUE TITLE
Update AMP settings to include additional options

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#5578]
## Feature description

- Remove "redirect mobile visitors to AMP" toggle from onboarding
- Add new section in AMP Settings under Advanced Settings to "redirect mobile visitors to AMP". Turn on by default. 
- Add new "dev tools" toggle in advanced settings. Make note that it's user role specific (not site wide)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
See also https://github.com/ampproject/amp-wp/issues/5386.

**Comment by jwold** [comment]
<img width="865" alt="Screen Shot 2020-11-05 at 9 17 47 AM" src="https://user-images.githubusercontent.com/3411173/98274096-df094d80-1f47-11eb-87b3-0bb2ec26caec.png">

**Comment by westonruter** [comment]
@jwold IMO, the headings under the Other section for “Redirects” and “Dev Tools” are too similarly-sized to the toggles they are for. Maybe the headings are redundant?

**Comment by jwold** [comment]
@westonruter that's a good point. That heading level has always been a bit weird. I just submitted an attempted fix. Feel free to remove it if my code was incorrect; figured I'd try! 😀

Screenshot of what I'm trying to do: https://d.pr/i/CPtRce
- [Commit 1](https://github.com/ampproject/amp-wp/commit/344a98b0611fc279ec46db4a072eff621b3df072)
- [Commit 2](https://github.com/ampproject/amp-wp/commit/ad294fab9a628adcf6e7d62b94afa266a0c4afc5) [fixing tab issue]

**Comment by bartoszgadomski** [comment]
**QA passed**

#### ✅  &nbsp; Add new section in AMP Settings under Advanced Settings to "redirect mobile visitors to AMP". Turn on by default.

The "redirect mobile visitors to AMP" toggle is found under the "Other" section **when site is in "Transitional" or "Reader" mode:**

![Screenshot 2021-12-8 at 17 35 33](https://user-images.githubusercontent.com/4476915/145246891-209f3427-eaef-42ef-974c-b6f3baa99708.png)

I can also see that `mobile_redirect` option is set to `true` by default.

![Screenshot 2021-12-8 at 16 55 44](https://user-images.githubusercontent.com/4476915/145241609-25d7cb23-47bd-46b5-9cd6-fe0b92dd925d.png)

#### ✅  &nbsp; Remove "redirect mobile visitors to AMP" toggle from onboarding

All good, I did not found this option in onboarding wizzard.

#### ✅  &nbsp; Add new "dev tools" toggle in advanced settings. Make note that it's user role specific (not site wide)

All good, "Enable developer tools" toggle found under "Other" section:

![Screenshot 2021-12-8 at 16 55 59](https://user-images.githubusercontent.com/4476915/145241271-19978450-7121-49c0-aaac-78f2d8412bfe.png)
