### ISSUE TITLE
Transformer: Implement self-hosting of AMP scripts

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5581]
## Feature description

Depends on https://github.com/ampproject/amphtml/issues/25873.

Self-hosting will need to rely on fetching the required scripts from the AMP CDN to then serve locally via new rewrite rules that render out the cached responses. The AMP plugin would serve essentially as a proxy.

Some key benefits to doing this include:

* Fewer HTTP connections to obtain the JS critical for the page to load.
* Elimination of dependency on CDN which can be a seen as a privacy concern (nevertheless, see ampproject/amp-wp#4403).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We'll make this an opt-in transformer. The concern is that a majority of users will be negatively impacted by serving assets from the origin rather than the AMP CDN. So it would be off by default.

**Comment by jonoalderson** [comment]
> "The other solution to implement this would be to actually write the JS files out to the filesystem inside of wp-content. Could we create a wp-content/uploads/amp-assets which is configured to be the base URL for all self-hosted AMP assets? Would this be a best practice? I suppose optimization plugins often concatenate and minify scripts and dump them inside of wp-content/uploads as well. Any drawbacks to this approach?"

Sounds good. Only risks I've come across are folder creation permissions, and, collision with existing folder names.

> "One thing that comes to mind is that if we serve from the filesystem, we'll need to make sure that we put each day's AMP CDN assets into a separate directory, if a new version of AMP has been released. This will ensure that the web server can serve the scripts with far-future expires for optimal performance."

Can't we just serve the current/latest file with a query-busting param, based on the lastmod timestamp? E.g., `v0.js?timestamp=1234567`

**Comment by westonruter** [comment]
> Can't we just serve the current/latest file with a query-busting param, based on the lastmod timestamp? E.g., `v0.js?timestamp=1234567`

Good question. I've requested that: https://github.com/ampproject/amphtml/issues/25873#issuecomment-812086561.
