### ISSUE TITLE
Add AMP updates module to WordPress Dashboard

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#5585]
## Feature description

![Group 8](https://user-images.githubusercontent.com/3411173/98565725-cad49180-2262-11eb-9325-a4b0fee3db84.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Here's an initial take on what the AMP News section could look like. It's not necessarily doing much to standout. A few ideas we could try:

1. Having favicons or icons to represent each link. 
2. Showing the ampwp.org featured images beside each link
3. Having an icon at the top of the module.

**Comment by amedina** [comment]
This is part of what we are calling "Knowledge Paths", which are entry points from the plugin experience that make it easy for users to get information such as YT series, documentation, news, etc.  In  tandem with this we want to integrate such knowledge path entry points in different places of the plugin UI.
