### ISSUE TITLE
Turn AMP off for select posts

### ISSUE THREAD

**Issue by mterenzio** [Automattic/amp-wp#56]
I'm implementing a way to turn AMP off for select posts. Default would be on, but a check that a meta value of 'amp_enabled' exists and that value is false will result in a pass.

What do y'all think?

https://github.com/Automattic/amp-wp/compare/master...mterenzio:mterenzio-patch-1?expand=1

**Comment by mjangda** [comment]
We would probably want to use a filter instead of meta and let sites handle it however they want.

**Comment by mterenzio** [comment]
Excellent, thanks!
