### ISSUE TITLE
The upgraded AMP Plugin from last week is negatively affecting site ranking - it blocks Alexa code

### ISSUE THREAD

**Issue by schikanza** [Automattic/amp-wp#5606]
The upgraded AMP Plugin from last week is negatively affecting site ranking - it blocks Alexa.com code which is the site header. Alexa can no longer read the AMP pages. Most likely there are other codes residing in the header affected. PLEASE HELP FIX THIS

**Comment by westonruter** [comment]
Please submit this as a support topic and we'll help you there: https://wordpress.org/support/plugin/amp/#new-topic-0
