### ISSUE TITLE
Filter for "amp_is_enabled" added too late.

### ISSUE THREAD

**Issue by coolrecep** [Automattic/amp-wp#5615]
## Bug Description

This error appears on WP admin panel after updating to 2.0.7 in WP debug mode:

Notice: add_filter hatalı çağırıldı. Filter for "amp_is_enabled" added too late. To disable AMP, this filter must be added before the "plugins_loaded" action. Daha fazla bilgi için lütfen WordPress hata ayıklama adresine bakın. (Bu mesaj 2.0 sürümünde eklendi.) in /home/technopa/public_html/wp-includes/functions.php on line 5229

Warning: Cannot modify header information - headers already sent by (output started at /home/technopa/public_html/wp-includes/functions.php:5229) in /home/technopa/public_html/wp-includes/functions.php on line 6274

Warning: Cannot modify header information - headers already sent by (output started at /home/technopa/public_html/wp-includes/functions.php:5229) in /home/technopa/public_html/wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at /home/technopa/public_html/wp-includes/functions.php:5229) in /home/technopa/public_html/wp-admin/admin-header.php on line 9

## Expected Behaviour

No error.

## Screenshots

![image](https://user-images.githubusercontent.com/13221472/99771490-47485980-2b1a-11eb-89f5-a6886ae457bf.png)

## Additional context

 - WordPress version: 5.5.3
 - Plugin version: 2.0.7
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Transitional
 - PHP version: 7.4
 - OS: Centos 7.9
 - Browser: [e.g. chrome, safari] Chrome 87
 - Device: [e.g. iPhone6] Desktop
**NewsMag Theme**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
To try and determine if it's a theme or plugin is calling `amp_is_enabled` too late can you install the [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin? 

When you enable the plugins "Troubleshooting" mode it will switch to a core WordPress theme and deactivate all plugins for you only, as a logged in administrator. You can then activate the amp plugin while in troubleshooting mode. From there you can activate your current theme and check for the same issue, or alternatively check your plugins by enabling one by one. 

The issue also came up previously in the [plugins support forums](https://wordpress.org/support/topic/issue-with-amp-added-too-late/), from a user who had another TagDiv theme active. Let us know once you check.

**Comment by coolrecep** [comment]
This is the result in Troubleshooting mode with all the 3rd party themes and plugins disabled. 

`Notice: add_filter hatalı çağırıldı. Filter for "amp_is_enabled" added too late. To disable AMP, this filter must be added before the "plugins_loaded" action. Daha fazla bilgi için lütfen WordPress hata ayıklama adresine bakın. (Bu mesaj 2.0 sürümünde eklendi.) in /home/technopa/public_html/wp-includes/functions.php on line 5229

Warning: Use of undefined constant TDC_PATH_LEGACY - assumed 'TDC_PATH_LEGACY' (this will throw an Error in a future version of PHP) in /home/technopa/public_html/wp-content/plugins/td-composer/td-composer.php on line 114`

I think it is a TagDiv issue. TD Composer is theirs AFAIK.

**Comment by coolrecep** [comment]
Found the culprit: TagDiv Mobile Theme

https://github.com/phanthanhgit/kungfuweb/blob/982e9108912dc6aa240899bd30d7a8fcc8eadd06/wp-content/plugins/td-mobile-plugin/td_mobile_theme.php#L288-L293

**Comment by westonruter** [comment]
Good find. I also identified TagDiv Mobile Theme as being the cause in a support topic: https://wordpress.org/support/topic/issue-with-amp-added-too-late/

We should help facilitate this in the same way we did for calling `is_amp_endpoint()` too early. We did this in #5289. I've also used that logic in #5558 to identify the theme/plugin responsible for adding a custom URL structure.

**Comment by coolrecep** [comment]
After being told that TagDiv themes cause the isseue, I disbaled TagDiv Mobile Theme and the issue was fixed. After that I found the thread with your reply and pasted here. Credit is yours. Thanks.
