### ISSUE TITLE
amp-base-carousel loop="true" doesnt work

### ISSUE THREAD

**Issue by mainframeai** [Automattic/amp-wp#5616]
Hello Team… 

I can't get the amp-base-carousel  to work. The AMP-Plugin keeps deleting loop="true" as an argument....

Element attributes:
id: carousela
loop
class: col-12 max-width-6
layout: responsive
width: 4
height: 2
snap-align: center
visible-count: 1

**Comment by mainframeai** [comment]
The source code in the template is like:                  

` <amp-base-carousel id="carousela"   class="col-12 max-width-6 border" layout="responsive" width="4" height="2" snap-align="center"  visible-count="1" loop="true" >`

**Comment by jamesozzie** [comment]
If you open the [amp-carousel playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-carousel.example.1.html%3Fformat%3Dwebsites&format=websites) and paste in the below content you'll find a working example with a loop. Without knowing your full markup the loop doesn't function if the number of slides is less than 3 times the visible count:

```
  <amp-base-carousel
  layout="responsive"
  width="3"
  height="1"
  heights="(min-width: 600px) calc(100% * 4 * 3 / 2), calc(100% * 3 * 3 / 2)"
  visible-count="(min-width: 600px) 4, 3"
  advance-count="(min-width: 600px) 4, 3"
      loop="true"
>
  <amp-img src="/static/inline-examples/images/image1.jpg" width="450"  height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image1.jpg" width="450"  height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image1.jpg" width="450"  height="300"></amp-img>
    
  <amp-img src="/static/inline-examples/images/image2.jpg" width="450"  height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image2.jpg" width="450"  height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image2.jpg" width="450"  height="300"></amp-img>

  <amp-img src="/static/inline-examples/images/image3.jpg" width="450"  height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image3.jpg" width="450"  height="300"></amp-img>
  <amp-img src="/static/inline-examples/images/image3.jpg" width="450"  height="300"></amp-img>
    
</amp-base-carousel>
```

If the above doesn't assist please share the full markup and we can check. Note also that this is not specific to AMP plugin, with the amp-base-carousel documentation found [here](https://amp.dev/documentation/components/amp-base-carousel/#auto-advance-loops). Eitherway let us know whether that help's identify the issue in your case. Using the playground can also be useful for testing your own component markup.

**Comment by mainframeai** [comment]
Yes you are absolutely right. This was not the plugin. This was my amp-base-carousel itself. I deactivated the amp-plugin and there was just the loop attribute left without any associated value. 

There are 5 Slides in the Carousel though.

**Comment by mainframeai** [comment]
This was just (again) my own stupidity. :) I am sorry to have bothered you … thanks @jamesozzie

**Comment by jamesozzie** [comment]
@mainframeai No problem at all, I checked the plugin myself, the `loop="true"` attribute remains. But glad to hear you found a solution. 

Be sure to also share your [thoughts on the plugin](https://wordpress.org/support/plugin/google-site-kit/reviews/#new-post), we'd love to hear your feedback. Or if you're developing sites with the plugin submit [them for consideration](https://docs.google.com/forms/d/e/1FAIpQLSeE0IqW2Xm4_AvLIhRuloyNAhZyWW-gMf7PJ23Ew8R0sf4mLA/viewform?usp=sf_link) in our plugin site showcase.
