### ISSUE TITLE
Facebook Audience Network

### ISSUE THREAD

**Issue by OtherF** [Automattic/amp-wp#563]
Hi,
Is it possible to add placement of Facebook Audience Network to AMP Pages?
Facebook gives me this block:
```
<figure class="op-ad">
  <iframe width="300" height="250" style="border:0; margin:0;" src="https://www.facebook.com/adnw_request?placement=1154470671289906_1244440755626230&adtype=banner300x250"></iframe>
</figure>
```
I couldn't find any information about successful Audience Network implementation.

**Comment by amedina** [comment]
This is not possible at this time.
