### ISSUE TITLE
Avada+WooCommerce theme,main menu+footer menu are unresponsive,help !

### ISSUE THREAD

**Issue by theGreaterBayArea** [Automattic/amp-wp#5630]
Avada+WooCommerce theme,main menu+footer menu are unresponsive,help !
![Screenshot_2020-11-28-00-53-09-136_com android chrome](https://user-images.githubusercontent.com/5503064/100471253-e4a41e80-3114-11eb-8245-cc0460b2087c.jpg)
![Screenshot_2020-11-28-00-53-15-306_com android chrome](https://user-images.githubusercontent.com/5503064/100471282-f08fe080-3114-11eb-9b7c-0096cccb761b.jpg)

**Comment by theGreaterBayArea** [comment]
Avada+WooCommerce theme,main menu+footer menu are unresponsive,help !

**Comment by milindmore22** [comment]
There may be some features of WooCommerce that are not fully AMP compatible although most aspects should work as expected.

You may need to configure [redirection](https://imgur.com/wvms46N.png) for any item added to the cart and apply a workaround for some features such as the gallery, but overall most aspects should work fine.
Please note that your theme may override WooCommerce templates also You need to contact your theme provider for AMP compatibility.

if you have a further question please submit this as a support topic and we'll help you there: https://wordpress.org/support/plugin/amp/#new-topic-0
