### ISSUE TITLE
how to remove canonical from all pages

### ISSUE THREAD

**Issue by joshm33333** [Automattic/amp-wp#5633]
literally spent the last 5 hours looking for anything about this to no avail

how to i remove <link rel="canonical" ... from all pages and posts in standard mode

some things ive tried

remove_action('wp_head', 'amp_add_amphtml_link');
remove_action( 'wp_head', 'amp_add_generator_metadata' );
remove_action( 'wp_head', 'amp_post_template_add_canonical' );
remove_action('amp_post_template_head', 'amp_add_amphtml_link');
remove_action( 'amp_post_template_head', 'amp_add_generator_metadata' );
remove_action( 'amp_post_template_head', 'amp_post_template_add_canonical' );

as you can see im pretty much just guessing, please help, this is absolutely critical to making my clients happy

**Comment by pierlon** [comment]
Is there any particular reason for removing the `canonical` link? It is a requirement for having a valid AMP page, per the [docs](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#required-markup).

**Comment by joshm33333** [comment]
> Is there any particular reason for removing the `canonical` link? It is a requirement for having a valid AMP page, per the [docs](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#required-markup).

**Edited:**
I want to create two separate pages, one AMP and one normal, the same way transitional mode does it, except I want to explicitly design each page (with javascript turned off it looks terrible). Since the plugin doesn't offer any built in way to do this, I was hoping to just make two pages and modify the canonical urls.

**Comment by milindmore22** [comment]
You may find [this](https://gist.github.com/westonruter/56e96c7a9eacf51d0db256b00c46f002) plugin useful, which adds substitutionary content from the`private child page`.
The installation and usage instructions are also mentioned in the same gist

Usage.
1) Create Child Page for an existing page
2) Prefix it with `AMP:`
3) Mark it as `Private`
4) it will serve content from a private page when the request is made for the AMP page.


Also, As explained in the previous comment, `canonical` link is required to have a valid AMP page. we should not remove them.
if you are looking to modify canonical URLs please check [get_canonical_url](https://developer.wordpress.org/reference/hooks/get_canonical_url/) filter.
eg:
```php

add_filter( 'get_canonical_url', 'modify_amp_canonical_url', 10, 2 );

/**
 * Modify Canonical URL for AMP pages.
 *
 * @param string $canonical_url Canonical URL.
 * @param object $post WP_Post object.
 */
function modify_amp_canonical_url( $canonical_url, $post ) {
	if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
		$canonical_url = $canonical_url . '?amp';
	}

	return $canonical_url;
}
```

**Comment by joshm33333** [comment]
**EDIT: Problem Possibly Resolved**
I may have just needed to lower the priority at which I called the hook. EG:
```
add_filter( 'get_canonical_url', 'my_get_canonical_url', 2, 1 );
function my_get_canonical_url( $url, $post ){return '';}
```

This seems to be working. Have to wait a few days to see if Search Console likes it. I will update this post when I know.
Leaving everything below for interests sake.

Thanks so much for the help!

**UPDATE:**
Search Console is happy, filtering get_canonical_url works. Clearly my use case is not common, but I feel like how the AMP plugin fundamentally works is not well documented, or not clearly explained. The fact the it uses output buffering is A: unusual, B: is highly likely to conflict with other plugins, and C: completely prevents other plugins from modifying the final output. I mean, at the very least, I wish the output buffer didn't hook into WordPress with PHP_INT_MIN to ensure that it is absolutely impossible to make changes AFTER the plugin finishes it's work.


**--------**

> You may find this plugin useful, which adds substitutionary content from the private child page.

Looked into it, and I see what's happening there. Interesting solution but seems more tedious than what I had in mind. With my idea I'm generating the second version automatically, so the content creators on my team don't have to even think about AMP. The plugin you suggest would require them to make both pages every time.

> As explained in the previous comment, `canonical` link is required to have a valid AMP page. we should not remove them.

I understand this, I'm using the AMP Validator and Search Console to verify everything so I do know what I'm doing.

> if you are looking to modify canonical URLs please check [get_canonical_url](https://developer.wordpress.org/reference/hooks/get_canonical_url/) filter.

This is SO close! Unfortunately it allows modifying the URL, but, it won't allow removing it. In the Wordpress core, an empty return value would completely remove the entire `<link>` element, but it appears that the AMP plugin is ignoring any false or empty return value.

**Comment by westonruter** [comment]
Closing as I believe this was resolved with https://github.com/ampproject/amp-wp/pull/5204#issuecomment-740156642.
