### ISSUE TITLE
amp_post_template_css not called

### ISSUE THREAD

**Issue by BatLozano** [Automattic/amp-wp#5634]
## Bug Description

Action "amp_post_template_css" never called

## Expected Behaviour
This code is not called anymore
function a4aff_wp_enqueue_style_amp() {
	die("here");
}
add_action( 'amp_post_template_css', 'a4aff_wp_enqueue_style_amp', 11 );

**Comment by swissspidy** [comment]
The `amp_post_template_css` is only used in the legacy Reader mode templates, and is not available in other modes.

See https://amp-wp.org/documentation/how-the-plugin-works/amp-and-css/#adding-css-to-your-amp-urls for how to add CSS for your AMP templates.
