### ISSUE TITLE
Remove obsolete NPM dev dependencies

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5636]
## Feature description

I think there are few dev dependencies in package.json that are not used directly in the plugin. Removing them would save dependabot work and may slightly improve build times. A little investigation might be needed to determine which are not being used. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Dependencies in package.json only contain what's needed.
* All scripts still work.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Moving this to the "QA Passed" column since there's nothing here to QA.
