### ISSUE TITLE
Maximum font size not working with Heading block

### ISSUE THREAD

**Issue by priethor** [Automattic/amp-wp#5658]
## Bug Description

The maximum font size settings set to a Heading block are not applied

## Expected Behaviour

When browsing the edited page from a mobile device, the text should fit in the screen, with a font size smaller than the maximum specified in the AMP settings.

## Steps to reproduce

1. Select a Heading block
2. Enable AMP Settings
3. Set a max font size smaller than the normal font size
4. The AMP max font size doesn't apply and the Heading block spans two lines, as in the following screenshot

## Screenshots

![image](https://user-images.githubusercontent.com/27339341/101168079-37149c00-363b-11eb-94b5-037e9e7890da.png)

## Additional context

 - WordPress version: 5.5.3
 - Plugin version: 2.0.7
 - Gutenberg plugin version (if applicable): 9.5.0
 - Browser: Chrome, Firefox

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Are you referring to the “Automatically fit text to container” setting, like:

> ![image](https://user-images.githubusercontent.com/134745/101209037-f0697680-3627-11eb-88f6-895c26e6266d.png)

If so, we're actually planning on deprecate and remove this feature due to it not currently working on non-AMP pages and also that it is too low-level. It's more relevant when the text is programmatically supplied rather than being manually entered. See https://github.com/ampproject/amp-wp/issues/4557#issuecomment-726539373.

**Comment by priethor** [comment]
>Are you referring to the “Automatically fit text to container” setting, like:

Yes, that's the one I was referring to.

**Comment by westonruter** [comment]
OK, please disregard that feature for now. We'll be deprecating/removing it.

**Comment by westonruter** [comment]
Closing in favor of #4557.
