### ISSUE TITLE
The anchor can not be parsed.

### ISSUE THREAD

**Issue by silantw** [Automattic/amp-wp#566]
https://www.guitar.com.tw/guitar-teacher-in-kaohsiung/amp/

The anchor can not be parsed.
This doesn’t happen in the non-AMP version either.
Can the next update be resolved?
Thank you

**Comment by pppdog** [comment]
about HTML Links (Anchor link) #562

**Comment by amedina** [comment]
Th e link provided validates successfully. 
<img width="1252" alt="screen shot 2017-07-05 at 6 51 56 pm" src="https://user-images.githubusercontent.com/506089/27892193-0c8d1eb8-61b3-11e7-92b3-39a7b50cbadd.png">
