### ISSUE TITLE
Introduce AMP notification center for action items

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5671]
## Feature description

There is a need for a unified way to surface action items for site admins to take in relation to a site's AMP status:

1. With ongoing site scanning for themes and plugins (#4795 and #4719), validation errors will be discovered which necessitate a user to review. Actions include suppressing the offending plugins, switching to a different plugin/theme, reporting the issue to the plugin/theme author,  or fixing the underlying code.
2. Critical Site Health test failures related to AMP. Currently we show an admin notice for lacking object caching,  HTTPS, or (as of #5120) a Site Icon or Custom Logo. Instead of relying on admin notices, we should put them into a proper action item list.
3. Results from the AMP Page Experience Guide checks (#5679) and what they can do to improve the PX.
4. Suggesting key ecosystem plugins for them to succeed. This includes a Schema.org metadata plugin like Yoast SEO instead of relying on our rudimentary metadata and installing Site Kit for the features it provides.

When there are pending action items, they can be shown as a number bubble on the Settings menu item in the same way as we do for unreviewed Validated URLs and validation errors. Consider also how Yoast SEO has a notice in the admin bar:

![image](https://user-images.githubusercontent.com/134745/101521540-d3d88180-393a-11eb-915d-534b3b6a4456.png)

Consider also the Yoast SEO Dashboard:

![image](https://user-images.githubusercontent.com/134745/101521635-f4a0d700-393a-11eb-8490-5a94a34f699c.png)

This may make sense as a new Dashboard widget for AMP updates (#5585).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Also consider renaming the Settings screen to Dashboard, per @jwold.

**Comment by jwold** [comment]
Related to: https://github.com/ampproject/amp-wp/issues/5679

* Alberto: We could put all the pieces together for the brain center. 3.0 material. Site scan, more powerful onboarding, optimizer stuff, dashboard, performance info, maybe Bento AMP. 
* Guard rails and info to help users know what's good and what is part of a good AMP system for them.
* Shining milestone for this year if we could target a release like this. 
* Let's spend time seeing what we can do for 2.2, then beyond onto 3.0 to end up there.

**Comment by jwold** [comment]
Goal is to have the guardrails for users. AMP can provide a comforting and safe experience for users.

**Comment by westonruter** [comment]
The notification center and/or Site Health test for AMP validation issues should also supercede the entry on the "At a Glance" dashboard widget:

![image](https://user-images.githubusercontent.com/134745/108286194-81d38980-713d-11eb-9e88-c0fd59b086b7.png)

This is redundant with the information currently shown in the admin menu with the Validated URLs item:

![image](https://user-images.githubusercontent.com/134745/108286306-b21b2800-713d-11eb-859a-37b73ef9d6cf.png)

**Comment by westonruter** [comment]
There should be a Site Health test for “unreviewed validation errors” which takes the user to the list the validated URLs with unreviewed errors to review.
