### ISSUE TITLE
Incorporate AMP Page Experience Guide

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5679]
## Feature description

There is an [AMP Page Experience Guide](https://amp.dev/page-experience/) which analyzes an AMP page for opportunities for page experience improvements. The AMP plugin should be able to invoke the tests remotely and then surface the results inside of WordPress to then provide site-specific recommendations for how to resolve the issues. For example, if issues are reported for images and the user has Jetpack active, we may suggest that they turn on Photon. The PX test results can be surfaced along with site scanning results as part of the proposed notification center (#5671).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
* WR > We could integrate PX guide, which has Rest API endpoints. We could leverage those to integrate the results into the plugin and provide more info to users in context of WordPress, and with WordPress specific guidance. If they're not using optimized images we can recommend Jetpack Photon module, or another image CDN plugin. 
* WR > If slow time to first bite, we can recommend page cache. We can give page guidance for site health. 
* AM > Could be entry point to drive home area of roadmap that talks about integration of CWV into plugin. We could provide guidance for what's missing, and we could tell them what's happening and how plugin is helping them and current state for what plugin is supposed to do to help. Those should be shaped into angle of plugin or value proposition of what plugin brings to user. 
* AM > I have AMP site, could have dashboard with status, how plugins helping, things missing, what you can do. User has centralized - not sure how it will happen, we need to think holistically about three areas. Then we avoid fragmented narrative. This is Alain's work with performance, it ties with this part and @jwold is looking at how to bring this together in a cohesive way.
* AM > AMP page experience guide, performance analysis, impact of optimizer modules, and how AMP is helping. Need to figure out how to tackle coherently.

**Comment by jwold** [comment]
@jwold and @schlessera can look how to merge things together.

* AM > This could touch on compatibility database, if we're going to provide guidance one element is use compatible stuff. 
* AM > Want to think about having a dashboard, command and control center for AMP. Then we can incorporate SiteKit CWV metrics.
