### ISSUE TITLE
Add PR check to require an assigned milestone prior to merging

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5683]
## Feature description

One of the suggestions in #2741 is:

> Automatically assign the correct milestone to newly opened pull requests

This would not work so well for us because we'll have the next major milestone (x.y) along with the next minor milestone (x.y.z) that we need to decide between. Therefore, the most important thing is that a milestone needs to be specified. So a new check could be introduced that blocks merging of a PR until a milestone is assigned.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by thelovekesh** [comment]
@westonruter Do we still need this?

**Comment by westonruter** [comment]
It's not important, nah.
