### ISSUE TITLE
amp-social-shares social-logos.eot file not found

### ISSUE THREAD

**Issue by nabtron** [Automattic/amp-wp#5693]
## Bug Description

The amp-wp plugin calls the file social-logos.eot in amp version of page without giving full path to the file and this leads to a file not found error on each page in logs

## Expected Behaviour

the path should be complete

## Steps to reproduce

wp: 5.6
php: 7.4
amp:2.0.8
jetpack: 9.2.1

**Comment by westonruter** [comment]
Please share the URL of an AMP page where this can be seen. 

Are you testing in Internet Explorer?

**Comment by westonruter** [comment]
@nabtron please advise

**Comment by westonruter** [comment]
Closing due to lack of response.

**Comment by amyuki** [comment]
Same here.

**Comment by westonruter** [comment]
@amyuki Same then for you. Please share the URL of an AMP page where this can be seen.

**Comment by amyuki** [comment]
Hm, it’s odd. When I open the amp url manually it doesn’t trigger any file not found error, but when I look at the NGINX error log file, it shows some error logs like below. It looks like some crawler will trigger this error. I will keep looking this issue.  Thanks.
```
2021/04/12 06:30:26 [error] 9853#9853: *348118 open() "/var/www/sample/amp/social-logos.eot" failed (2: No such file or directory), client: 221.103.224.207, server: s01, request: "GET /sample/amp/social-logos.eot?5d3b4da4f6c2460dd842dbf9e0992ea6 HTTP/2.0", host: "xxx.org", referrer: "https://xxx.org/sample/amp/"
```

**Comment by westonruter** [comment]
It's only going to be an issue if you're testing in an old version of IE that supports the EOT font format, namely [Internet Explorer 11 and older](https://caniuse.com/eot).

**Comment by westonruter** [comment]
This code in Jetpack is likely where the issue is coming from: https://github.com/Automattic/jetpack/blob/99ea6be4a3d54af93483c4373f6080192c9f05d1/projects/plugins/jetpack/_inc/social-logos/social-logos.css#L13-L16

Notice the `url("social-logos.eot?5d3b4da4f6c2460dd842dbf9e0992ea6")`. It could be the AMP plugin is not converting this relative URL into an absolute one.

**Comment by westonruter** [comment]
I found this is a bug with Jetpack. I've opened a PR to fix: https://github.com/Automattic/jetpack/pull/19503.
