### ISSUE TITLE
Links direct to other AMP posts in site

### ISSUE THREAD

**Issue by altonius** [Automattic/amp-wp#570]
Similar to #221 AMP pages can be dead ends.  I.e. if you click on a link to another post, in an AMP post within the site, it provides a link to the standard post (not the AMP version).

Could you consider adding an enhancement that allows you to enable some sort of automated AMP to AMP links within a site when you link to another post?

**Comment by jimmy-espace-musculation** [comment]
looking for this too.. Did you have an answer somewhere ?

**Comment by altonius** [comment]
Unfortunately not yet

**Comment by jery61007** [comment]
Do you mean like this [http://techprezz.com/howto/how-to-add-social-media-buttons-to-accelerated-mobile-pages-without-plugin/amp/](http://techprezz.com/howto/how-to-add-social-media-buttons-to-accelerated-mobile-pages-without-plugin/amp/) where all the links within the content and related posts direct to another AMP page instead of usual non-amp version of the site??

**Comment by jimmy-espace-musculation** [comment]
yess !! :)

**Comment by jery61007** [comment]
Good.. Then here is a post  [how to convert all the links on Accelerated Mobile Pages to its AMP version](http://techprezz.com/howto/how-to-convert-all-the-links-in-wordpress-accelerated-mobile-pages-to-amp-version/)  

Hope this helps....

Thanks!

**Comment by altonius** [comment]
Thanks Jerry, now we just need something similar included in the AMP
plugin.

**Comment by jery61007** [comment]
Actually Some bloggers want to direct them to non-amp version of the blog, so if they include the feature in the plugin itself then they should give two options, convert or keep it default non-amp.

**Comment by altonius** [comment]
Sounds good,  can you add your code as a pull request somewhere so they can
decide how / whether to include it?

**Comment by amedina** [comment]
Closing for now; if you would like contribute an approach to achieve this, please create a PR for it to be considered.
