### ISSUE TITLE
Undefined index in OnboardingWizardSubmenu.php:64

### ISSUE THREAD

**Issue by ghostintranslation** [Automattic/amp-wp#5700]
## Bug Description
In the admin, at the top of the page an error is showing "Undefined index" leading to `\Admin\OnboardingWizardSubmenu->Register()` in `/OnboardingWizardSubmenu.php:64`

The error seems to be cause by the fact that `add_submenu_page` wordpress function is called with an empty string in first argumenet, but that first argument is supposed to be the parent to which the submenu attach. It should be set to `amp-options` instead.

## Expected Behaviour
No error and the Wizard submenu attached to the Amp menu.

## Steps to reproduce
Install the plugin and go in the admin.

## Additional context

 - WordPress version: 5.3
 - Plugin version: 2.0.8

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
@ghostintranslation passing an empty string as parent_slug will hide the menu from top-level navigations. can you please share a complete stack trace of your error

**Comment by ghostintranslation** [comment]
@milindmore22 

Here is 2 screenshots to show the whole stack I get:
<img width="1439" alt="wp-amp-undefined-index-1" src="https://user-images.githubusercontent.com/50341468/102233004-27604780-3ec6-11eb-80ed-573d56cd3ff7.png">
<img width="1438" alt="wp-amp-undefined-index-2" src="https://user-images.githubusercontent.com/50341468/102232997-26c7b100-3ec6-11eb-8f71-4a25c59248cd.png">

According to the Wordpress documentation, the first argument is required:
https://developer.wordpress.org/reference/functions/add_submenu_page/

When I set it to `amp-options` then all the warnings and notice messages go away, but the menu displays in the sidebar then yes. There is a proper way with Wordpress to hide a submenu if that's what is intended I believe, without setting this argument to an empty string.

**Comment by milindmore22** [comment]
There seem to be another warnning "headers already sent", can you please share your site health information along with complete PHP debug log using [this](https://docs.google.com/forms/d/1JTQmphDlk9YgHpDoFRbHXpkDqv8-QmzTT7MDR4AstyQ/) form so we can investigate it further.

**Comment by westonruter** [comment]
The headers already sent error I think is just a byproduct of displaying errors.

**Comment by westonruter** [comment]
Nevertheless, please do share the Site Health info as there may be a plugin conflict that is causing this issue. If you can deactivate other plugins to isolate any conflict that would be helpful.

**Comment by westonruter** [comment]
@ghostintranslation What version of PHP are you running?

**Comment by ghostintranslation** [comment]
- I deactivated all plugins and still getting the warnings
- PHP is 7.2.24

Here is a screenshot of the site health:
<img width="757" alt="site-health" src="https://user-images.githubusercontent.com/50341468/102264072-81273880-3eeb-11eb-9bb7-e6ffcd6b5ca6.png">

**Comment by westonruter** [comment]
I can reproduce the issue in WordPress 5.3.0. I cannot reproduce it in WordPress 5.3.1, however. This was a core bug that was fixed. See https://core.trac.wordpress.org/ticket/48599

So please update to the latest on the 5.3 branch (currently 5.3.4), or better update to 5.6.

**Comment by ghostintranslation** [comment]
@westonruter It does work now that I have updated to 5.6 .
Thanks
