### ISSUE TITLE
Add PHPUnit test workflow for multisite

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5701]
## Feature description

Some relatively recent additions to the plugin have involved small customizations related to multisite environments ([example](https://github.com/ampproject/amp-wp/blob/5ee474c9de85de8a15494669f92e926b45755ddb/src/BackgroundTask/CronBasedBackgroundTask.php#L103)). Currently we only run PHPUnit tests in single-site environments, so there's no easy way to write tests for these features. 

Potentially useful for reference: 

https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/multisite.xml
https://github.com/WordPress/wordpress-develop/blob/master/.github/workflows/phpunit-tests.yml#L257

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by thelovekesh** [comment]
@westonruter I am planning to add multisite tests workflow using wp-env.  Which WP and PHP versions it should cover?  or it should be the same as current test workflows. In this case, we will be having 2x test workflows.

**Comment by westonruter** [comment]
Just adding one additional test with the latest WP version and PHP 7.4 should be good, as that corresponds to the [majority of installs](https://wordpress.org/about/stats/).

**Comment by westonruter** [comment]
As part of this, could you also add a local development command using the Docker environment to test multisite? Maybe you're planning to do that anyway for debugging the current failures anyway.

**Comment by thelovekesh** [comment]
I have added it as a command and it uses the wp-env.

https://github.com/ampproject/amp-wp/blob/ac70da52a6aa245b53d5e7661b1fa7920df027e3/package.json#L146

**Comment by thelovekesh** [comment]
QA Passed ✅ 

PHPUnit tests workflow for multisite is up and running with PHP 7.4 and WP latest.

See [job](https://github.com/ampproject/amp-wp/actions/runs/4086817005/jobs/7046788957) or explore the action runs for the[ `Build Test & Measure`](https://github.com/ampproject/amp-wp/actions/workflows/build-test-measure.yml) workflow in the [Actions](https://github.com/ampproject/amp-wp/actions) tab.

![image](https://user-images.githubusercontent.com/54371619/216694168-b1461800-0be0-44fe-bb8c-60f13e3b3b75.png)
