### ISSUE TITLE
Elementor Popup not working after installing AMP.

### ISSUE THREAD

**Issue by jagadeesh2425** [Automattic/amp-wp#5706]
For general, technical and product help requests, please post it on the [AMP Plugin support forum](https://wordpress.org/support/plugin/amp/). Support will not be provided on GitHub.

Thank you!

**Comment by jagadeesh2425** [comment]
I have Elementor Pro in my website. I used popup. I installed AMP and activated Standard mode. After that Elementor popup is not working.
Can you please help me about this.

**Comment by milindmore22** [comment]
@jagadeesh2425 Please create a support topic [here](https://wordpress.org/support/plugin/amp/#new-topic-0)
The Elementor plugin is not fully AMP compatible so some features may not work, our [FAQ](https://amp-wp.org/documentation/frequently-asked-questions/) has more info on it.

**Comment by jagadeesh2425** [comment]
Thanks for the Reply.
 I choosed Reader mode or Transitional mode in AMP. GTM not firing in Desktop versions.It is firing in Mobile Versions only. Can you please guide me about this.

**Comment by westonruter** [comment]
@jagadeesh2425 please open a topic in the support forum: https://wordpress.org/support/plugin/amp/#new-topic-0
