### ISSUE TITLE
Twenty Twenty: Mobile Menu does not close when tapping on anchor links

### ISSUE THREAD

**Issue by swissspidy** [Automattic/amp-wp#5719]
## Bug Description

I use AMP + Twenty Twenty on a one-page landing page, with the nav menu containing anchor links to the individual sections on that page.

When I click on such a link in the mobile menu, it scrolls to that section, but the menu doesn't close. So as a user I don't see that anything is actually happening.

In the non-AMP version of Twenty Twenty this works as expected.

## Expected Behaviour

When clicking on an anchor link (or any link, I suppose) in the mobile menu, the menu should close.

## Steps to reproduce

1. Create a new navigation menu with anchor links in it
1. View site on small viewport to see mobile menu
2. Toggle mobile menu and click on anchor link
3. See that menu does not close

## Additional context

 - WordPress version: 5.6
 - Plugin version: 2.0.9
 - Gutenberg plugin version (if applicable): 9.5.2
 - AMP plugin template mode: Standard
 - PHP version: 7.4
 - OS: macOS / iOS
 - Browser: Chrome / Safari
 - Device: MacBook Pro / iPhone

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Good find. This is probably an issue with _every_ core theme that has a mobile menu modal. 

This is the non-AMP behavior (_shoot_, I don't have video upload yet enabled for this repo!):

https://youtu.be/_8CZwMjEu_U

And the AMP behavior:

https://youtu.be/r8B-23CYWx4

There are two problems with the AMP version:

* When the anchor link is clicked, the page is scrolling down while the menu is open. Once you click the toggle to close the menu, then it scrolls back up to the top. Either this is a problem with `amp-lighbox` or focus is incorrectly being added back to the menu button.
* The mobile version switcher link makes an appearance when the scrolling down happens while the menu is open. In Twenty Twenty-One, we force the mobile switcher link to be hidden when the mobile menu is open. Perhaps we need to do the same thing here.

Note that Twenty Twenty-One also has this problem, but the issue happening in the non-AMP _and_ AMP versions alike.

**Comment by ghost** [comment]
Has this already been fixed? I'm trying to get it to work in the Twentytwentyone theme but the menu still doesn't close after clicking a link with an anchor.

**Comment by swissspidy** [comment]
Yeah this has been fixed a while ago and it still works fine for me. A link to `#colophon` in the menu closes the menu and scrolls down to the footer.

If it doesn't for you, I recommend opening a new issue

**Comment by ghost** [comment]
Thank you for getting back to me so quickly. I managed to get it to work. It conflicted with another plugin called Easy Smooth Scroll Links. Fixed now!
