### ISSUE TITLE
301 from amp links (pages)  

### ISSUE THREAD

**Issue by johnico** [Automattic/amp-wp#573]
Hi  i have page template that not a regular one but for sure is not a blog 
the url is   url.com/parentPage/page 
all those pages with 2 level  are redirect with 301 when add amp and google think that they are page of amp instead of 404

url.com/parentPage/page/amp  ->redirect to url.com/parentPage/page/ -> error
url.com/parentPage/amp  -> 404  - good

thx

**Comment by onur-celik** [comment]
@johnico do you have any other rule just like url.com/*/*/* >> url.com/$1/$2 ?
