### ISSUE TITLE
Add to the cart button

### ISSUE THREAD

**Issue by arazzistco** [Automattic/amp-wp#5740]
In our website,arazzistco.ir, when press the "add to the cart" button, the product fails to be added to the cart, and it reports " (it seems like your request was successful. Even though the server responded well, the request may not be processed.)
 I will leave a link of a similar link here for you to check out.
https://www.google.com/amp/s/www.arazzistco.ir/product/cryo-box-spl/%3famp

**Comment by westonruter** [comment]
Hello! Please open a support topic on the forum: https://wordpress.org/support/plugin/amp/#new-topic-0

That's a better place for this question.
