### ISSUE TITLE
AMP Validation Failed on all pages 

### ISSUE THREAD

**Issue by askmeoffers** [Automattic/amp-wp#5744]
Respected Weston Sir Good Day,

Recently I moved my site to a different server ( migrated) configuration and everything is the same and only difference is the IP address and the hosting provider is also the same.

But I am getting AMP validation issue on all pages 

And what I see the error is :
On Aliexpress Coupon Store 

https://askmeoffers.com/coupon-deal-offer-promo-store/aliexpress-com/

script>document.addEventListener( "DOMContentLoaded", function() { document.write = function( text ) { throw new Error( "[AMP-WP] Prevented document.write() call with: "  + text ); }; } );</script></head>

The same code runs and fine with everything same and is AMP valid on the dev server

https://dev-askmeoffersomsairam.pantheonsite.io/coupon-deal-offer-promo-store/aliexpress-com/

I tried a lot to resolve this issue from my end but unable to understand 

Below things I tried 

1) Purged Cloudflare cache
2) disabled all plugins ( jetpack) 
3) plugin suppression enabled for all plugins ( in amp plugin settings)
4) Also tried manually adding powered by AMP in header <html> but it did not worked so removed 

Please guide me 

Thanks
Team - askmeoffers.com
4)

**Comment by westonruter** [comment]
You appear to have a validation error whose invalid markup is "kept". Try clicking "Validate URL" in the admin bar for a page that has that issue. Make sure no validation errors have "kept" invalid markup.

**Comment by askmeoffers** [comment]
The issue is resolved with suggested changes 

Thanks, Weston Sir

Team - askmeoffers.com
