### ISSUE TITLE
Remove e2e test utils now available from @wordpress/e2e-test-utils

### ISSUE THREAD

**Issue by johnwatkins0** [Automattic/amp-wp#5746]
## Feature description

The following e2e test utility functions created for this plugin have since been added to [`@wordpress/e2e-test-utils`](https://github.com/WordPress/gutenberg/tree/master/packages/e2e-test-utils/src):

`activatePlugin`
`activateTheme`
`deactivatePlugin`
`deleteTheme`
`installTheme`
`themeInstalled` (renamed `isThemeInstalled` in the core package)

I suggest these functions be removed from the plugin and loaded from the `@wordpress` package.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Re-opening to track cherry-pick to `2.0`.

**Comment by pierlon** [comment]
Weirdly the issue didn't close when #5755 was merged. Closing since it has been.

**Comment by westonruter** [comment]
Ah, because it was merged into the non-default branch.

**Comment by pierlon** [comment]
Moving to Done as there's nothing to QA here.
