### ISSUE TITLE
amp-pixel for Jetpack stats loading too late

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/amp-wp#577]
There is an [issue](https://github.com/ampproject/amphtml/issues/6246) in the amphtml repo about the behavior of amp-pixel. Specifically it appears that the amp-pixel is not being fired until the viewport reaches it.

The Jetpack stats function in the amp-wp plugin uses `amp_post_template_footer` to render an amp-pixel for Jetpack stats. This could lead to a lot of under reporting in Jetpack stats if readers' viewports don't actually reach the pixel.

There are two potential solutions here. 

1. Wait for AMP team to change implementation of amp-pixel to fire on page load, if that is indeed what they plan on doing.
2. Load jetpack stats pixel earlier in template in a spot where it will always render.

**Comment by westonruter** [comment]
Is this still an issue? I presume not, but we can reopen if it is.
