### ISSUE TITLE
First tap on any <a> element on iOS >=13 does not work

### ISSUE THREAD

**Issue by BartoszJanowski** [Automattic/amp-wp#5770]
## Bug Description

When entering the website for the first time in a session (typing an address directly / going from search results) on iPhone (**iOS 13.x, 14.x**), a first tap on any `<a>` does not result in going to a page from the link. The tap results only in a standard visual confirmation that element was taped (iOS short link "blink"). 
A second tap on the same `<a>` element or any other anchor works as expected, redirecting to the page from link. From that moment links start to work normally during the session. After leaving and re-entering the website (for example by closing the tab), the situation repeats itself from the beginning
It seems that some JS from AMP plugin prevents the first click event from working correctly - **deactivating AMP plugin fixes the problem.**

## Expected Behaviour

The first tap on `<a>` link on iOS should result in going to the page from that link.

## Steps to reproduce

1. Go to https://codeandpepper.com on iPhone / XCode iPhone simulator **iOS 13.x, 14.x**
2. Tap on a hamburger icon in the top right corner of the screen
3. Tap on any link in a opened menu ("Services" is not a link)
4. Link only "blinks" confirming a tap, does not redirect to a new page
5. Tap the same link or any other - link works as expected, redirecting to a new page

## Screenshots

Video presenting the problem: https://www.youtube.com/watch?v=rYpRKIkoWGc

https://user-images.githubusercontent.com/9989233/103866712-7e70cb00-50c6-11eb-95ed-0fcda96e533b.mp4

## Additional context

 - WordPress version: 5.6
 - Plugin version: 2.0.9
 - AMP plugin template mode: standard
 - PHP version: 7.4.2
 - OS: **iOS 13.x, 14.x**. everything works as expected on iOS 12.x
 - Browser: Safari & Chrome
 - Device: every iPhone & XCode iPhone simulator with iOS >= 13
 - Several pretty standard and popular plugins installed including PWA v0.5.0

Only deactivating AMP plugin fixes the problem. We tested deactivating all the other except the AMP and the problem remained.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is most likely a bug with either the AMP runtime or iOS Safari itself, not the AMP plugin. We'll see if we can identify where the bug lies.

**Comment by milindmore22** [comment]
I am not able to reproduce the issue on my local or test site, but the possible conflict was between amp-carousel and amp-user-notification components.

**Comment by westonruter** [comment]
@bartesn I recommend opening this issue on the AMP core repo directly: https://github.com/ampproject/amphtml/issues

The AMP plugin generates AMP pages. If the generated AMP page is valid, as yours is, then any further problems with its behavior must lie either in the AMP runtime or in a browser bug.

**Comment by BartoszJanowski** [comment]
@westonruter @milindmore22 the problem is definitely caused by the conflict between amp-carousel and amp-user-notification components, removing the carousel from a page fixes the problem. I will open issue directly on the AMP core repo. Thanks for help!
