### ISSUE TITLE
Detect available object caching backend(s) to guide users toward persistent object caching plugins

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5780]
## Feature description

When persistent object caching is not enabled on a WordPress site, we provide the following Site Health test recommendation:

![image](https://user-images.githubusercontent.com/134745/104645374-d168f600-5663-11eb-9f44-3dfc840c247b.png)

This is not very helpful because the only call to action is to a link to [Learn more about persistent object caching (opens in a new tab)](https://make.wordpress.org/hosting/handbook/handbook/performance/#object-cache), and the information on that handbook page is not very helpful for non-technical users. It's also not helpful because it doesn't provide specific plugins that should be used for implementing a persistent object cache.

In #1216 we explored attempting to detect the host running to then link off to host-specific instructions. However, determined that was not feasible: https://github.com/ampproject/amp-wp/issues/1216#issuecomment-661994626.

What we can do, however, is detect if the PHP extensions are installed for Redis, Memcached, and APC/APCu. With that information, we can inform the user what persistent object caching backend they appear to have available and then we can perhaps provide some plugin suggestions for that backend. (Note we may need to also try to connect to Redis and Memcached to see that the servers are available.)

Instead of mentioning the specific plugins in the Site Health info recommendation, the list of backend-specific plugins can be in a documentation page on amp-wp.org. This documentation page can pull together the various pieces of information about object caching spread out across WordPress.org, including:

* https://make.wordpress.org/hosting/handbook/handbook/performance/#object-cache
* https://developer.wordpress.org/reference/classes/wp_object_cache/#persistent-caching

Ultimately, the user should ask their host for the recommended way to enable object caching first before they do it themselves. So our recommendation should be to first contact the host, and then continue with our guidance to try the plugins we've identified which may work with their site.

See support topics about object caching:

* https://wordpress.org/support/topic/how-enable-persistent-object-in-amp-plugin/
* https://wordpress.org/support/topic/amp-error-25/
* https://wordpress.org/support/topic/persistent-object-cache-is-not-enabled-2/
* https://wordpress.org/support/topic/persistent-object-caching-is-not-enabled-2/
* https://wordpress.org/support/topic/persistent-object-cache-is-not-enabled-amp/

Anything we can do to make it easier for users to enable object caching the better.

This is part of encouraging users to use page caching (#4386).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Per @pierlon, note that W3 Total Cache allows for multiple backends:

> ![image](https://user-images.githubusercontent.com/134745/104648373-e2b40180-5667-11eb-884f-d2a35aefd5ad.png)

It even supports writing to disk. We should avoid recommending that, however, since using the disk for object cache storage would be very slow. The recommendations we provide should be in descending order of precedence:

1. Redis
2. Memcached
3. APCu
4. disk

(Using the disk could even be worse than not having object caching at all, if the MISS rate is too high.)

**Comment by milindmore22** [comment]
A suggestion from the user from [support topic ](https://wordpress.org/support/topic/turn-off-persistent-object-cache-notification/#post-14845941)using varnish cache to suppress the recommendation, as varnish eliminates the need for persistent object caching @westonruter your thoughts on this one?

**Comment by westonruter** [comment]
That's a good question. I've [proposed](https://wordpress.org/support/topic/turn-off-persistent-object-cache-notification/#post-14847767) the following:

<blockquote cite="https://wordpress.org/support/topic/turn-off-persistent-object-cache-notification/#post-14847767"><p>Even though page caching like Varnish does reduce the need for persistent object caching, it is still recommended because it reduces the amount of data that is put into the <code>wp_options</code> database table (from transients).</p>
<p>One feature we’re going to be including in the next version (v2.2) is detection for whether or not page caching is enabled via a new Site Health test. See <a href="https://github.com/ampproject/amp-wp/issues/4386" rel="nofollow ugc">amp-wp#4386</a>. </p>
<p>So a compromise I see here is that when we detect page caching is enabled, we can reduce the severity of not having persistent object caching from the current <code>recommended</code> status to something lesser. I suppose the only option there is <code>good</code>, which isn’t technically right but I guess it’s as <em>good</em> as we can get, but we can differentiate between the two with a color difference (green for actual good, and blue for info). There could be three states for this test then:</p>
<ol>
<li><code>recommended</code> w/ orange: “Persistent object caching is not enabled”</li>
<li><code>good</code> w/ green: “Persistent object caching is enabled”</li>
<li><code>good</code> w/ blue: “Persistent object caching is not enabled, but you have page caching.”</li>
</ol>
<p>The latter two would both be included among “passed tests”.</p>
<p>How does that sound?</p>
<p>Note you can also remove site health tests with PHP filters. There’s a <a href="https://wordpress.org/plugins/site-health-tool-manager/" rel="nofollow">Site Health Tool Manager</a> plugin which allows you to disable certain tests, although it has become a bit out of date.</p>
</blockquote>

**Comment by bartoszgadomski** [comment]
**QA passed:**

Caching services not available:
![Screenshot 2021-11-22 at 11 33 10](https://user-images.githubusercontent.com/4476915/142846517-093318c7-3307-402e-aabb-e4751cbcc4c9.png)

Memcached available:
![Screenshot 2021-11-22 at 11 32 49](https://user-images.githubusercontent.com/4476915/142846520-e1e81271-c81c-431b-8377-ca5b4b485e46.png)

Memcached and Redis available:
![Screenshot 2021-11-22 at 11 33 30](https://user-images.githubusercontent.com/4476915/142846512-4c61ce9e-d633-4366-8ce1-f927f805405e.png)
