### ISSUE TITLE
Add WP-CLI commands for managing AMP settings

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5783]
## Feature description

As demonstrated by #5782, there is a need for WP-CLI commands to manipulate the AMP settings, including:

* Setting the template mode.
* Setting the Reader theme.
* Toggling mobile redirection.
* Updating the supported post types (see https://github.com/ampproject/amp-wp/issues/5782#issuecomment-761877633).
* Toggling whether all templates are supported, and otherwise toggling individual templates.
* Updating suppressed plugins
* Setting the Paired URL structure (as of #5558) 

I'm specifically not including the manipulation of Analytics here, as we want to discourage it from being used.

In addition to updating the settings, we also need to be able to query the existing settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@milindmore22 What settings are the most important to be included in the CLI interface? We won't likely need to include every possible setting (e.g. toggling specific templates). We should prioritize what will actually be useful (e.g. switching template mode).

**Comment by milindmore22** [comment]
I will suggest including the following which seems essential 

- Setting the template mode.
- Setting the Reader theme. 
- Toggling mobile redirection.
- Updating suppressed plugins.

Good to have but not essential 
- Updating the supported post types
- Toggling whether all templates are supported, and otherwise toggling individual templates.

**Comment by pavanpatil1** [comment]
QA passed ✅ 

Cross-checked the issue, Verified the WP-CLI command added related to AMP settings those are working fine. 

![image](https://user-images.githubusercontent.com/44057535/216935253-6e0c40f7-ad93-4cad-9538-742c9b7e6a50.png)
