### ISSUE TITLE
No longer compatible with AIOSEO

### ISSUE THREAD

**Issue by arnaudbroes** [Automattic/amp-wp#5784]
## Bug Description

From v4.0.0 onwards, AIOSEO is rewritten and uses different filter hooks. AMP for WP still hooks into the old filters and options and is therefore no longer compatible.

## Expected Behaviour

AMP for WP should add support for the new version while preserving backwards compatibility with the old version.

## Steps to reproduce

N/A

## Additional context

I'm one of the developers of AIOSEO so I'll be happy to work with you on this if you need any help.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
@arnaudbroes did you mean https://github.com/ahmedkaludi/accelerated-mobile-pages

**Comment by arnaudbroes** [comment]
Oops, yes. Feel free to close this. My bad!
