### ISSUE TITLE
Cannot enter text in form

### ISSUE THREAD

**Issue by constellationcon** [Automattic/amp-wp#5790]
Hi! I am having an issue with the genesis enews extended plugin. Every time I go to enter text in the form to test it out, it redirects me to a page and I can't enter anything in the text box.

**Comment by milindmore22** [comment]
Hello @constellationcon 

For general, technical, and product help requests, please post them on the [AMP Plugin support forum](https://wordpress.org/support/plugin/amp/). Support will not be provided on GitHub.

Thank you!
