### ISSUE TITLE
Eliminate readme.txt in favor of just readme.md

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5791]
## Feature description

Surprise surprise, it turns out that the WordPress plugin directory supports `readme.md` in addition to `readme.txt`: https://twitter.com/johnbillion/status/1351969604961243136

More details: https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/

Eliminating the `readme.txt` will eliminate the need to synchronize the two versions.

Caveat: The `readme.md` needed by WordPress.org seems to be slightly less pretty than the version we use. 

Compare: 

https://github.com/johnbillion/user-switching/blob/develop/readme.md
https://github.com/ampproject/amp-wp/blob/develop/readme.md

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Aside: I like how Web Stories has the `wp-assets` in a `.wordpress-org` directory: https://github.com/google/web-stories-wp/tree/main/.wordpress-org (which is also what User Switching is doing: https://github.com/johnbillion/user-switching/tree/develop/.wordpress-org)

**Comment by westonruter** [comment]
Also realized that we don't have an `icon.svg`.

**Comment by jwold** [comment]
Not sure how to test this one. I can confirm that the final output is `readme.txt` as intended, but can't see how to differentiate whether its the result of transforming from markdown to text.

**Comment by westonruter** [comment]
@jwold You can look at the `amp.zip` to find the `readme.txt`

**Comment by westonruter** [comment]
Upon extracting the ZIP I can see it:

![image](https://user-images.githubusercontent.com/134745/115922608-fa064600-a431-11eb-94a3-924e7114bdce.png)

**Comment by jwold** [comment]
Agreed. I saw that, but wasn't sure if that was proof of the transformation. If so, all good. Will pass :)!
