### ISSUE TITLE
Conflict with AddThis Sharing Buttons plugin

### ISSUE THREAD

**Issue by tottaz** [Automattic/amp-wp#58]
I just wanted to let you know that, I been testing the amp-wp plugin, and that the only conflict that I have noticed so far is with the AddThis Sharing Buttons plugin - when the AddTis plugin is active the amp page will include the javascript code - as can bee seen here - http://torbjornzetterlund.com/wordpress-plugin-for-google-accelerated-mobile-pages-project/amp/

Scroll down to the end and javascript code is shown on the page.

**Comment by mjangda** [comment]
Thanks for the report! The javascript bits should hopefully be stripped as of 8d0840e8a03624153909dd38a867e78d2d706b2f. Can you try the latest version from github and let us know if it's fixed?
