### ISSUE TITLE
Customizer: Use Theme's Color Scheme

### ISSUE THREAD

**Issue by BFTrick** [Automattic/amp-wp#580]
Love the plugin. 

It doesn't make much sense to force site owners to redo all of their colors under Appearance -> AMP.

My site's main color is purple. There has to be some way to get that color into this plugin automatically. Is there something the theme developer can do? Or the plugin can do?

<img width="318" alt="customize__my_first_mistake_-_patrick_s_programming_blog" src="https://cloud.githubusercontent.com/assets/1065372/20860221/fc84f902-b940-11e6-828b-d6951f0cb4c0.png">

**Comment by mjangda** [comment]
Yep, this would be nice :) The challenge is that there is not standard across themes on how colours are handled which makes the task a bit challenging. It would be good to do it for the default themes at least though and maybe some docs for theme developers to integrate as well (it's not particularly hard).

**Comment by amedina** [comment]
Thanks Patrick; we are working on an approach to address this. Stay tuned. 

Closing this for now; feel free to reopen if you want to discuss further.
