### ISSUE TITLE
Jetpack amp contact form redirect issues

### ISSUE THREAD

**Issue by rsmith4321** [Automattic/amp-wp#5803]
Recently I can't get redirects to work with the Jetpack contact form in amp. They used to work fine but now seem to just reload the same page instead of redirecting.  Since it used to work fine and has recently stopped without any changes I can think of, I assume it must be a bug. The redirect also works correctly with amp disabled. Thanks for the help.

Example url
https://www.ryansmithphotography.com/please-get-in-touch/

**Comment by westonruter** [comment]
I am seeing that submitting the form is resulting in a redirect that contains `contact-form-id`, `contact-form-sent`, `contact-form-hash`, and `_wpnonce` query parameters added. But these parameters are not causing any change to the content on the success page.

This may be a regression in Jetpack. We'll try to confirm that.

**Comment by westonruter** [comment]
I've identified this as a bug with Jetpack. Fix submitted here: https://github.com/Automattic/jetpack/pull/18516

While waiting for that fix to land in a release, here is a workaround plugin that will have the same effect: https://gist.github.com/westonruter/020dcab1545f24706cb34b1978c8708e

**Comment by rsmith4321** [comment]
Great thanks, that fixed it!

**Comment by westonruter** [comment]
The fix will be part of Jetpack v9.4.
