### ISSUE TITLE
Missing logo field & missing publisher field

### ISSUE THREAD

**Issue by NawarHisso** [Automattic/amp-wp#5805]
Please I need your help,
Recently, I have the below errors in AMP structure data test, and here is the link:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.popsci.ae%2F%25D8%25A3%25D9%2581%25D8%25B6%25D9%2584-9-%25D8%25AA%25D8%25B7%25D8%25A8%25D9%258A%25D9%2582%25D8%25A7%25D8%25AA-%25D9%2584%25D9%2584%25D9%2587%25D9%2588%25D8%25A7%25D8%25AA%25D9%2581-%25D8%25A7%25D9%2584%25D8%25B0%25D9%2583%25D9%258A%25D8%25A9-%25D9%258A%25D9%2585%25D9%2583%25D9%2586%25D9%2583-%25D9%2585%25D9%2586-%25D8%25AE%2F%3Famp

![image](https://user-images.githubusercontent.com/26778101/105636734-59c07580-5e72-11eb-9d18-23b256d7b7f5.png)

![image](https://user-images.githubusercontent.com/26778101/105636756-6e047280-5e72-11eb-95ac-1cd9ca62c230.png)

Please your help ASAP.

**Comment by westonruter** [comment]
Please use the support forum such questions: https://wordpress.org/support/plugin/amp/

You should be able to find some existing topics that may answer your question already.
