### ISSUE TITLE
Google AMP Test: Not a valid AMP page

### ISSUE THREAD

**Issue by Herzogdb** [Automattic/amp-wp#581]
I installed the plugin according to the instructions but just keep getting this result. If I add /amp at the end of a URL it just shows me the same URL. If I turn off the plugin, adding /amp returns a 404 error, so I know it's doing something. But when I run it through the Google AMP test, it just says this:

Not a valid AMP page
Invalid AMP pages will not have AMP-specific features in Google search results

**Comment by jery61007** [comment]
There can be several reasons why this happens in AMP test, so you need to be specific, or post your AMP page here .....     this article [about customizing amp page](http://techprezz.com/2016/02/wordpress-amp-customize-accelerated-mobile-pages-add-google-analytics-adsense-code/) might also help.

Thanks!
