### ISSUE TITLE
 Is amp-wp abandoned?

### ISSUE THREAD

**Issue by jimmy-espace-musculation** [Automattic/amp-wp#582]
(Hello sorry for my english I'm French)

## **It has been weeks since there has been no update.** 
It would be necessary to add **AMP pages for the categories** and if possible the home page. I am not an encoder, but I do not think this is difficult because many other plugins allow it. Also it would be interesting if one could only navigate with AMP URLs in the AMP version?

**Comment by jd440** [comment]
this weuld be interesting

**Comment by aimarv** [comment]
any news for the next (much needed) update?

**Comment by amedina** [comment]
Hi Jimmy, amp-wp is not abandoned. Support for pages (such as Categories) is coming. No ETA yet.  Thanks for reporting it and participating.
