### ISSUE TITLE
Logo has been removed and replaced with text

### ISSUE THREAD

**Issue by digitalhop** [Automattic/amp-wp#585]
Hi

Great plugin that has so far saved me numerous hours.

I have an issue now where the logo that I used has been replaced with text again. In the beginning I used the amp_post_template_css hook that you have in your readme notes. But unfortunately now it doesn't seem to be working any more. 

One of the other things that happened was that I noticed that the plugin was pulling two header images into the page. I removed the code that pulls in the featured image, also mentioned in your readme notes and it fixed the problem.

I am thinking the logo readme notes might be a little out of date now. 

Thanks for the effort you have put into this plugin

**Comment by bhhaskin-noble** [comment]
I have also had this issue.

**Comment by bhhaskin-noble** [comment]
So it looks like at some point `nav.amp-wp-title-bar` was changed to `header.amp-wp-header`.

**Comment by digitalhop** [comment]
Thank you. The updated code in the readme file did the trick and is now calling the logo and replacing the text. Nice job
