### ISSUE TITLE
Support for Categories / Tags

### ISSUE THREAD

**Issue by dikeii** [Automattic/amp-wp#5852]
Good morning, the categories/tags pages have amp support for reader mode? since I have tried to visualize them but I do not get it in any way, it just redirects me to the page no amp.

Example url : 
http: //xxx.xx/category/my-category/

http: //xxx.xx/tag/my-tag/

thanks. Greetings.

**Comment by westonruter** [comment]
Yes, if you choose a Reader theme other than "AMP Legacy". Please ask such questions on the support forum: https://wordpress.org/support/plugin/amp/
