### ISSUE TITLE
Copy Entire Template Folder and Make Editable Version

### ISSUE THREAD

**Issue by casbboy** [Automattic/amp-wp#586]
So we have this to give url for new style.php:

```
add_filter( 'amp_post_template_file', 'xyz_amp_set_custom_template', 10, 3 );

function xyz_amp_set_custom_template( $file, $type, $post ) {
    if ( 'style' === $type ) {
        $file = dirname( __FILE__ ) . '/amp/style.php';
    }
    return $file;
}
```

What if I also wanted to move header-bar.php, footer.php, single.php, meta-time.php, meta-author.php, featured-image.php and all the rest of the files in the "template" folder so I can edit them without risk of overwrite.

I'm just guessing but something like: 

```
add_filter( 'amp_post_template_file', 'xyz_amp_set_custom_template', 10, 3 );

function xyz_amp_set_custom_template( $file, $type, $post ) {
    if ( 'single' === $type ) {
        $file = dirname( __FILE__ ) . '/amp/single.php';
    }
    return $file;
}
```

and then

```
add_filter( 'amp_post_template_file', 'xyz_amp_set_custom_template', 10, 3 );

function xyz_amp_set_custom_template( $file, $type, $post ) {
    if ( 'footer' === $type ) {
        $file = dirname( __FILE__ ) . '/amp/footer.php';
    }
    return $file;
}
```

Something like that? Would like to just reference the editable directory in my functions file for all these template files.

Can I just edit something to point to change location of entire template folder, to point to the same files that I'm editing?

Cheers!
Ryan

**Comment by jery61007** [comment]
Actually you could install earlier version of the AMP plugin and create custom template... in the older version the plugin doesn't use several templates for each part of the page like footer and header, instead, almost all main codes are in single file.... here is a [tutorial on customizing wordpress AMP pages](http://techprezz.com/2016/02/wordpress-amp-customize-accelerated-mobile-pages-add-google-analytics-adsense-code/) ... just follow the tutorial and you can update the plugin to the latest version once you finish the customization with the early version ...

Thanks

**Comment by mjangda** [comment]
> Can I just edit something to point to change location of entire template folder, to point to the same files that I'm editing?

Two options (remove any existing filters for template overrides you already have first):

- In your theme, add a folder called `amp` and put your templates there.
- Hook in to the `amp_post_template_dir` filter and pass in a path of your choice where your template files live.
