### ISSUE TITLE
show highest price for variable product

### ISSUE THREAD

**Issue by amir3065** [Automattic/amp-wp#5860]
## Feature description

hi, i use wp amp in my site but i have a problem in [fusion_woo_shortcodes]
I dont want the price of variable products displayed as "from 10 to 20" in category page.
i want to show highest price for variable product

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
@amir3065 This is not AMP plugin related issue, please ask this question in theme fusion support
