### ISSUE TITLE
is_amp_endpoint Not Working to Output Custom Shortcode

### ISSUE THREAD

**Issue by casbboy** [Automattic/amp-wp#587]
Here is my custom shortcode. It makes the youtube embed responsive and 16x9.

```
if (!function_exists('youtube')) {
		function youtube_function($atts, $content = null) {
		$content = trim(str_replace('//youtu.be/','//www.youtube.com/watch?v=',$content));
		$contentarray = explode("/",$content);
		if($contentarray[3] != "embed") {
			$ytvar_array = explode("?v=",$content);
			$ytvar = $ytvar_array[1];
			$newcontent = "https://www.youtube.com/embed/". $ytvar;
		} else {
			$newcontent = $content;
		}
		if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
			$breaknewcontent = explode("/",$newcontent);
			$youtube_id = $breaknewcontent[4];
			$output = "<amp-youtube width=\"480\"
      height=\"270\"
      layout=responsive
      data-videoid=\"$youtube_id\">
  </amp-youtube>";

		} else {
			$output = "<div class='embed-container'><iframe src='";
			$output .= do_shortcode($newcontent) ."' ";
			$output .= "frameborder='0' allowfullscreen></iframe></div>";
		}
		return $output;
		}
		add_shortcode('youtube', 'youtube_function');
	}
```

As you can see, I am using is_amp_endpoint in hopes of outputting amp-ready code for youtube, but it's not working. This is in my function.php file. Not sure what I'm missing.

All feedback appreciated.

Cheers!
Ryan

**Comment by jahvi** [comment]
Any reason why you need a custom shortcode for this? WP-AMP [already supports this](https://github.com/Automattic/amp-wp/blob/master/includes/embeds/class-amp-youtube-embed.php) using oEmbed so you can just paste the link from youtube and it'll be converted to the amp version for you.

**Comment by casbboy** [comment]
Hello! Well, the oembed look for youtube is terrible. It stretches the youtube player high and is not responsive. So we created our own youtube shortcode to fix that. Surrounding the page url with [youtube] to automatically create a responsive, 16x9 player size.

My thought is that....

if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
//remove [youtube] and [/youtube] from page to allow oembed to take over for amp
}

So thinking remove custom youtube shortcode from the post before shortcodes are executed.

Cheers
Ryan

**Comment by casbboy** [comment]
Was hoping adding this to functions.php would work but no success:

```
if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
		function replace_content($content)
		{
			$content = str_replace('[youtube]', '',$content);
			$content = str_replace('[/youtube]', '',$content);
			return $content;
		}
		add_filter('the_content','replace_content',0);
	}
```

But amp-wp doesn't seem to work with $content, and uses its own pull. I need to figure out how to remove the shortcode for amp-wp to use.

**Comment by casbboy** [comment]
I ended up fixing the issue. 

I went into class-amp-post-template.php and removed this line:

//require_once( AMP__DIR__ . '/includes/embeds/class-amp-youtube-embed.php' );

and then remove this line

//'AMP_YouTube_Embed_Handler' => array(),

Then, in the amp/single.php, I have this up top:

if (strpos($this->get( 'post_amp_content' ), 'amp-youtube') !== false) {
    	echo '<script src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js" async></script>';
	}  

Now the youtube video shows up in amp pages just fine.

Cheers!
Ryan
