### ISSUE TITLE
Featured Image not hiding

### ISSUE THREAD

**Issue by matiasnoriega** [Automattic/amp-wp#5891]
## Bug Description

I want to hide featured images from post before certain date, the problem is that when I use the code snippet from the [docs](https://amp-wp.org/documentation/playbooks/classic-templates/#featured-image) it only works on the AMP Legacy Theme and not on my main theme (newsmag). 

I've tried [this](https://github.com/ampproject/amp-wp/issues/838) solution on Newsmag's `functions.php` and neither it worked.

Created a custom plugin in wich worked for AMP Legacy Theme but not for the newsmag theme with AMP enabled.

I do exactly what the docs say but can't get it to work in other themes. I'm testing on [this site](https://mnng.com.ar)

Thank you in advance.

## Expected Behaviour

Not show the featured image on the single post view header.

## Steps to reproduce

This code works on AMP Legacy Theme as spected, but not with other themes with AMP enabled.
```php
add_filter( 
	'amp_post_template_data', 
	function ( $data ) {

		$post = get_post();

		/* Fecha del Post en formato Time */
		$post_date = strtotime($post->post_date);
		
		/* Fecha límite (en formato YYYY-MM-DD) que se pasa a formato Time */
		$date = strtotime("2021-02-10");

		if($post_date < $date){

			$data['featured_image'] = false;

		}
		return $data;
	} 
);
```
## Additional context

 - WordPress version: 5.6.1
 - Plugin version: 2.0.10
 - AMP plugin template mode: Standard
 - PHP version: 7.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
The `amp_post_template_data` filter is only applicable to the Legacy AMP templates. If you want to hide something in another theme, you'll need to use that theme's own filters or standard WordPress ones.

**Comment by westonruter** [comment]
This is general WordPress theme template code which works in a theme like Twenty Twenty-One and should also work in Colormag assuming it uses the template tag `the_post_thumbnail()` :

```php
add_filter(
	'post_thumbnail_html',
	function ( $html, $post_id ) {
		if (
			function_exists( 'amp_is_request' )
			&&
			amp_is_request()
			&&
			strcmp( get_post( $post_id )->post_date, '2021-02-10' ) < 0
		) {
			$html = '';
		}
		return $html;
	},
	100,
	2
);
```
