### ISSUE TITLE
Disable tap delay by reducing meta viewport to just width=device-width

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5894]
## Feature description

While being valid AMP, it turns out that a meta viewport like this causes a tap delay (impacting FID):

```html
<meta name="viewport" content="width=device-width, initial-scale=1" />
```

A page experience guide check was added for this (https://github.com/ampproject/amp.dev/pull/5108):

> ![amp dev_page-experience_](https://user-images.githubusercontent.com/134745/108409737-7040bf00-71db-11eb-8003-391053fcfc32.png)

There is a [Blink issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1108987) to disable tap-to-zoom when `initial-scale=1`, but it hasn't landed yet. More information is available in [300ms tap delay, gone away](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away).

This is included in 5 core themes:

```
twentyseventeen/header.php:19: <meta name="viewport" content="width=device-width, initial-scale=1">
twentysixteen/header.php:16:   <meta name="viewport" content="width=device-width, initial-scale=1">
twentyeleven/header.php:26:    <meta name="viewport" content="width=device-width" />
twentythirteen/header.php:23:  <meta name="viewport" content="width=device-width">
twentynineteen/header.php:17:  <meta name="viewport" content="width=device-width, initial-scale=1" />
twentyfifteen/header.php:15:   <meta name="viewport" content="width=device-width">
twentytwentyone/header.php:19: <meta name="viewport" content="width=device-width, initial-scale=1" />
twentyfourteen/header.php:23:  <meta name="viewport" content="width=device-width">
twentytwelve/header.php:23:    <meta name="viewport" content="width=device-width" />
twentytwenty/header.php:19:    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
```

Since we have the core theme sanitizer which is fixing up the core themes to make them AMP-compatible, we should probably also go ahead and remove everything but `width=device-width` from the meta viewport as well.

I'm wary of doing it for _every_ theme since maybe a theme author intends to use a different value, although maybe a compromise would be to go ahead and strip out `initial-scale=1`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I don't see how `initial-scale=1` is impacting the appearance of the page in either Chrome for Android, Firefox for Android, or Safari on iOS. The text size is the same in both portrait and landscape:

* https://viewport-with-and-without-initial-scale.glitch.me/viewport-with-initial-scale.html
* https://viewport-with-and-without-initial-scale.glitch.me/viewport-without-initial-scale.html

**Comment by delawski** [comment]
**QA passed.**

---

I've verified that for core themes `twentyten` through `twentytwentyone` running the following in the dev tools:

```js
document.querySelector( 'meta[name="viewport"]' ).content;
```

returns only: 

```
"width=device-width"
```

which is as expected.
