### ISSUE TITLE
Use default filter content

### ISSUE THREAD

**Issue by luckycabarlo** [Automattic/amp-wp#59]
Why don't we just use the default content filter from WordPress core instead of using remove filters?

**Comment by mjangda** [comment]
It's a tempting idea and may be something we are forced to do (even though, we end up stripping out useful user content). Will keep this open and come back to it.

**Comment by mjangda** [comment]
Might have to revisit this as I'm seeing more and more cases where things break pretty badly (e.g. lazy load plugins).
