### ISSUE TITLE
Photon & AMP: image not showing!

### ISSUE THREAD

**Issue by willsmith7** [Automattic/amp-wp#590]
Hello, with Photon and AMP by Automattic i can't see the images in the AMP version of my pages anymore.

Example: https://goo.gl/sEGqpo

EDIT: even by disabling Photon, still images are not shown in AMP by Automattic (version 0.3.3)

This is the URL of images: data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

**Comment by mjangda** [comment]
That looks like an issue with whatever lazyload plugin you're using.

**Comment by willsmith7** [comment]
You are a legend. Thanks a lot, you resolved a big problem with 2 words.
