### ISSUE TITLE
How to make images stretch to full width?

### ISSUE THREAD

**Issue by DiamondNL** [Automattic/amp-wp#5908]
Hi,

I've been looking for a way to make images stretch to full width (100%), but I can't seem to figure out how.

The reason for this is because some text will display on the right of each image. E.g. https://pasteboard.co/JPHKbhYB.jpg

What code should I add/edit in amp/includes/sanitizers/class-amp-img-sanitizer.php ?

I found this piece of code (credits to @janvitos), but I'm not quite sure where to add it:

add_filter('the_content','new_content');
function new_content($content) {
    $content = str_replace('<img','<img data-amp-layout="responsive"', $content);
    return $content;
}

Your help is much appreciated!

- David

**Comment by DiamondNL** [comment]
@kienstra @janvitos

**Comment by pierlon** [comment]
@DiamondNL please open a topic in the support forum: https://wordpress.org/support/plugin/amp/#new-topic-0


Do note that it is not recommended to edit files within plugins or themes as you will lose your changes when it updates.

**Comment by pierlon** [comment]
If you are using Gutenberg to edit posts, setting the image alignment to full width should make the image full width on the page:

![image](https://user-images.githubusercontent.com/16200219/108874510-20eff980-75f4-11eb-9fce-fa287ddf746d.png)
