### ISSUE TITLE
Cover block issue with Wordpress 5.7

### ISSUE THREAD

**Issue by rsmith4321** [Automattic/amp-wp#5914]
## Bug Description

The 5.7 cover block now uses an img tag instead of background image. This causes problems with  amp  object-fit: contain, image does not fill background.

## Expected Behaviour

Image should cover entire background. I think object-fit: cover would be better.for the cover block

## Steps to reproduce

Create a cover block in wordpress 5.7 with a background image. You can check out an example here.  https://www.ryansmithphotography.com/myrtle-beach-real-estate-photography/

## Additional context

 - WordPress version: 5.7 RC1
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This is the code in question that is causing the problem:

https://github.com/ampproject/amp-wp/blob/7429a18a2103ff8ee5942120707091f18165fe51/assets/css/src/amp-default.css#L2-L12

I think we need to add another style rule to `amp-default.css` like so:

```css
.wp-block-cover > amp-img.wp-block-cover__image-background > img {
    object-fit: cover;
}
```

You should be able to add this to the Additional CSS in the Customizer as a quick fix for this issue.

**Comment by westonruter** [comment]
Or rather we should add `object-fit=cover` to the `img` that is being added to this block, perhaps in `AMP_Block_Sanitizer`. See also https://github.com/studiopress/atomic-blocks/pull/292.

**Comment by rsmith4321** [comment]
Great, that css worked for now. I didn't think it would because amp adds things inline but it did. One issue I noticed, where you put the focus point doesn't seem to have any effect now on the image position, since it's not a background image now I don't know if this is even possible.

**Comment by westonruter** [comment]
Another report: https://wordpress.org/support/topic/gutenberg-cover-block-image-loses-focus-point-with-amp-plugin/

**Comment by westonruter** [comment]
Here's a workaround plugin that fixes the issue with `object-fit` while also handling `object-position`: https://gist.github.com/westonruter/2d8ac828f48b43803852e26c5af274ff

**Comment by westonruter** [comment]
There were a couple bugs in that workaround plugin which I just fixed in the Gist.

**Comment by jwold** [comment]
@westonruter found one issue so far: https://v.usetapes.com/E5qW0ekdBa

1. Installed latest version of Gutenberg + WordPress
2. Created cover block with video and video block
3. Neither are working

**Comment by jwold** [comment]
Weston suggested it was HTTPS error, and that appears to be correct. Everything else is behaving as expected.

I'm not able to test `left` and `right` focal points, as the images fill the width of the page; I think that's how it's supposed to work. Confirmed top and bottom are working.

Also confirmed that nesting the cover block in a container block behaves as expected.
