### ISSUE TITLE
AMP disables menu. unable to uninstall

### ISSUE THREAD

**Issue by MultipliedByOne** [Automattic/amp-wp#5915]
Website = thebagsystem.com

Installing AMP added an html error, affecting url's and menu, which could be a connection there with the menu not working because the urls that the menu's would link to are faulty now? 
Analysis indicated a json inability to connect? I was only able to get my menu options to appear again while selecting to view the page with the AMP disabled. The menu worked. I removed AMP (disabled and deleted) but though the plugin no longer shows up as installed in my options, it is still somehow active at the top of the page when I view the webpages. The icon is still in the options bar, but the dropdown options are inactive. 
The menu bar for my website pages works in Safari desktop, but not on Opera or Chrome. The tab to click is there for the menu dropdown, but it's inactive.

The plugin is no longer accessible. Options unavailable.

SEO html analysis indicates that the AMP code is still on the website. It highlights code and states that this is not allowed on the html at that point in the code. I'm no dev, but what it looks like is that the start and end points of the prior code are connected at a > < point. Maybe the codes being connected to an html from another plugin caused the glitch, as well as made it unable to uninstall while connected to a still existing plugin code?
I use the free version.
I also downloaded AIOSEO on the same day, so unsure if it was a combinations issue, but the url errors and menu error started with the AMP. 
URL validation indicated I had, and now still have invalid urls?

This is a new issue. The website was slow, but functional prior.

**Comment by kristoferbaxter** [comment]
Transferred issue to `amp-wp`.

**Comment by westonruter** [comment]
@MultipliedByOne I don't see the plugin active on your site. Can you share a URL to an AMP page on your site?

**Comment by MultipliedByOne** [comment]
> @MultipliedByOne I don't see the plugin active on your site. Can you share a URL to an AMP page on your site?

I removed the AMP prior to reporting to fix the issue, but the amphtml strings are still in the code, despite deactivation and deletion. The icon is still on the backend view of the web page, but access to the dropdown is gone after I uninstalled.

The issue may be in combination with the theme. I use Euphonie pro, but that was one of the options in choosing on setup.

**Comment by milindmore22** [comment]
@MultipliedByOne It may be your site's cache or your browser cache, we are not able to see any AMP pages or AMP reference on your site. please let us know if you are planning to use the AMP plugin and we will be happy to assist you further.

I will also recommend going through our [getting started ](https://amp-wp.org/documentation/getting-started/) guide for a better understanding of the AMP plugin.

**Comment by MultipliedByOne** [comment]
Purging the sites cash did fix part of the issue. Thank you. 
I figured out that the menu disappearance was to do with a reset of the theme after installing the AMP. I had to rebuild it because the default had none.
I can probably re-install the AMP with the expectation that it will wipe the theme and just set it right away. 
thanks for looking into this.

**Comment by milindmore22** [comment]
Glad to know purging site cache fixed your issue, I will close this issue, If you re-install AMP plugin and run into issues feel free to reach us on [WordPress Support Forums ](https://wordpress.org/support/plugin/amp/#new-topic-0) and we will more than happy to assist you further.
