### ISSUE TITLE
Create a alternative permalink for AMP pages

### ISSUE THREAD

**Issue by edwarddekker** [Automattic/amp-wp#592]
Hi folks,

Would it not be nice to have a alternative permalink to your AMP Pages. Most of the times do i use %postid%/postname.html. Now do i want to use %postID%/amp only.

I feel that you want to make a choice too. Hopefully are there some people who wants to program this.

Regards,
@edwarddekker

**Comment by mjangda** [comment]
You could just do something like:

```
add_filter( 'amp_pre_get_permalink', function( $amp_url, $post_id ) {
    $permalink = get_permalink( $post_id );
    $amp_url = add_query_arg( AMP_QUERY_VAR, 1, $permalink );
    return $amp_url;
}, 10, 2 );
```

which would give you AMP URLs like `%postid%/postname.html?amp=1`.

**Comment by edwarddekker** [comment]
@mjangda,

Can you give me some example where i'll add the code.

Regards,
@edwarddekker

**Comment by edwarddekker** [comment]
Hi @mjangda,

I have add the code into `wp-config.php`. And it seems to work.

Thanks!
