### ISSUE TITLE
'Close' button on Onboarding Wizard creates re-auth loop when referrer is login page

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#5925]
## Bug Description

The 'Close' button in the Onboarding Wizard creates a re-authentication loop if the referrer to the page was the login page.

The link for the 'Close' button is retrieved from `wp_get_referer()`, or if that returns `false` the link to the settings page is used instead:

https://github.com/ampproject/amp-wp/blob/6fcd6cdfa75027c1f863f937fb0557daa39d0d3b/src/Admin/OnboardingWizardSubmenuPage.php#L235

## Expected Behaviour

I should not be expected to re-login after clicking the 'Close' button on the Onboarding Wizard page.

## Steps to reproduce

1. Go to Onboarding Wizard page
2. Forcefully end login session by removing the login cookie for the site
3. Refresh page and login
4. Click 'Close' button and see that it redirects back to login page

## Demo

https://user-images.githubusercontent.com/16200219/109102611-2a2ab480-7721-11eb-8ff4-1d478b8d00b4.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Good catch.

The logic in `WP_Customize_Manager::get_return_url()` could be incorporated here:

https://github.com/WordPress/wordpress-develop/blob/f2b56883f099b971ebde6c60f32ef9c66f90e78a/src/wp-includes/class-wp-customize-manager.php#L4668-L4679

**Comment by westonruter** [comment]
QA passed

1. I went directly to the Onboarding Wizard in a new tab: `/wp-admin/admin.php?page=amp-onboarding-wizard`
2. In another tab I signed-out of WP.
3. I then reloaded the tab with the Onboarding Wizard
4. I was redirected to the login screen, with the Onboarding Wizard as the return URL: `/wp-login.php?redirect_to=%2Fwp-admin%2Fadmin.php%3Fpage%3Damp-onboarding-wizard&reauth=1`
5. When being returned to the Onboarding Wizard, the close button linked to the Settings screen, not the Login screen: `/wp-admin/admin.php?page=amp-options`

Also:

1. I went to the Settings screen with a custom query parameter added: `/wp-admin/admin.php?page=amp-options&foo=bar`
2. I went to the Onboarding Wizard
3. I clicked Close
4. I was taken back to the original URL with the custom query parameters added: `/wp-admin/admin.php?page=amp-options&foo=bar`. This shows that the user isn't necessarily returned to the Settings Screen.

Aside: When in the Onboarding Wizard and I sign-out in another tab, the re-auth lightbox is shown at the next heartbeat and I am able to proceed without reloading the page.
