### ISSUE TITLE
Add support request flow

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5939]
## Feature description

When someone encounters issues with AMP, regardless of whether they have DevTools enabled, there needs to be a way to facilitate them getting support, beyond just adding links to the support forum (#5893 & #4664):

1. Highlight the themes/plugins causing the plugins and direct the users to their respective support forums (#4668).
2. Suggest plugin suppression as a way to deal with AMP issues for plugins.
3. Suggest alternate template modes especially Reader mode to deal with theme compatibility issues.
6. Gather up the validation data for the URL from which they encounter errors.
6. Obtain the Site Health information.
7. Present the gathered information to the user and allow them to omit/modify information as desired before submitting.
4. Ask if they want to be contacted regarding the issue. 
    1. Ask if they have searched the support forum for topics related to their issue, as there may be a resolution already available.
    2. Ask them what the problem is that they encountered.
    3. (Optional) Surface support topics from WordPress.org support forum based on the issue.

In order to dialog with the user, I suppose there would need to be contact info included in the support request. Nevertheless, it would be preferable if that conversation happened on the support forum like it is today. So perhaps we should require that the user first open a support topic before proceeding with an internal request? That may add unnecessary friction, however. If this support is handled privately, then the support team should post a summary of the (anonymized) issues and how the issue was resolved so that other users can find a resolution without opening a support topic.

The submitted information would then go to a private backend which our support team can then refer to.

Support request prompts should be available from:

1. Settings screen
2. Validated URL screen
3. Edit post screen (in the AMP plugin sidebar)
4. AMP admin menu dropdown on frontend
5. Plugin row action (cf. #5893)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
We should also allow users to submit debugging information without necessarily wanting a support response.

**Comment by westonruter** [comment]
As pointed out by @amedina, this is like on your OS when a program crashes. You can opt to send diagnostic information back to Microsoft, Apple, etc so that the development teams can improve the project even though you don't expect a response. In the case of the AMP plugin, this could be captured by a checkbox that says, “Please contact me about how this issue can be resolved.” When that checkbox is checked, the user would have to provide their email address (or we could require that they then open a support topic when a given reference ID).

I think we have three different areas of concern we're trying to solve for:

1. Making it easy for the user to report a problem.
2. Making it easy for users to find existing solutions to their problem reported by other users.
3. Collecting debugging information for the AMP plugin to identify problems for us to address in the plugin ourselves, even if the user isn't necessarily expecting a response to an issue they encountered.
4. Facilitating the support team in triaging and assigning work.

**Comment by westonruter** [comment]
The support page should:

* Request user to go to the page that has the problem and then click the support link from there so that the relevant information is sent. This will be most helpful for support, to have the data for a page that is actually having a problem as opposed to a sample set of URLs. Perhaps there could be a URL field that allows the user to paste the site URL that is having a problem.
* Have a way to preview the diagnostic information before it is sent.
* The reference ID does not need to be saved locally in the site. If they neglected to copy the reference ID, they can just re-submit the diagnostic information.
* Provide link to support forum and inform how to open a topic, and how to copy/paste the reference ID.
* Inform the user they should first search the support forum to see if there is any existing topic that addresses their issue.
* Highlight that errors related to a specific theme/plugin should be directed to their respective support forum first.
* Inform the user they do not have to submit diagnostic information to open a support topic, but they may get better support if they do so.
* Include documentation links to amp.dev, GitHub, and other support resources.

(Not exhaustive, but just what has come to mind today.)

**Comment by westonruter** [comment]
Reopening to address code review feedback: https://github.com/ampproject/amp-wp/pull/6147#pullrequestreview-753206599

**Comment by mxbclang** [comment]
Had a chance to run through this today and it's looking good! Some suggested copy changes for the Support page, just make things crystal clear:

_In order to best assist you, please click the Send Data button below to send the following site information to our private database. Once you have done so, copy the the resulting Support UUID in the blue box that appears and include the ID in a new support forum topic. You do not have to submit data to get support, but our team will be able to help you more effectively if you do so._

**Comment by milindmore22** [comment]
I am not sure if we only capture plugin and themes validation errors, I noticed few things

**Support flow didn't send data/capture content validation errors**

1.  Create page/post add custom HTML block and add `<script>` tag. 
2.  Create post add custom HTML block and add `div` with invalid attribute eg: `<div color="blue">I am red deal with it</div>`

Once you see a validation error in the validation tool, send data and copy UUID, and check-in AMP insights you won't be able to see those records.

**Comment by jamesozzie** [comment]
Great work on this all. A couple of suggestions from testing:
- Would the "[Server Information](https://i.imgur.com/zThYYWE.png)" from a users Site Health information be a useful addition, given it would include additional PHP information and .htaccess rules?
- Is there documentation planned on the plugin website for this new feature? This could include a quick demo showing the steps involved and an overview of what's collected and why.

**Comment by pierlon** [comment]
One other thing that should be addressed is to prevent the output of the AMP data summary when the [`AmpProject\AmpWP\Tests\Support\SupportCliCommandTest::test_send_diagnostic()`](https://github.com/ampproject/amp-wp/blob/5889868cf4f3336e7928aa98a765bc0fe94d9f67/tests/php/src/Support/SupportCliCommandTest.php#L114-L130) test is executed. Currently it looks like:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/16200219/134750506-24404976-5f10-461c-9b20-57382c3e9ec9.png">

**Comment by schlessera** [comment]
I want to mention here that tests should be written for the CLI command(s) as `feature` files like this one: https://github.com/ampproject/amp-wp/blob/develop/tests/features/optimize-transformer-config-command.feature

**Comment by dhaval-parekh** [comment]
Hey @jamesozzie,

> Would the "Server Information" from a users Site Health information be a useful addition, given it would include additional PHP information and .htaccess rules?

Currently, We are not storing that information in PX insight.

--- 

@schlessera I have updated the test case and added the feature file in the new PR. #6627

**Comment by Abncrew** [comment]
My name is Stian Morch and i am an investor that has used over 25 million dollars and i would like to se the paperwork pre IPO at 30cent. My email adresse is stianmorch77@gmail.com please help me out
With this matter and 25 million dollars aint pocketchange! Please assistanse i belive 25 million dollars make me credible

**Comment by Abncrew** [comment]
I invested 25 million dollars in mode mobile system

**Comment by Abncrew** [comment]
I invested 25 million dollars in mode mobile system
