### ISSUE TITLE
AMP errors on Search Console

### ISSUE THREAD

**Issue by willsmith7** [Automattic/amp-wp#594]
Hello, i'm desperate! 

I am getting many 404 errors with your plugin. Seems like it's putting AMP pages link for image pages (attachments pages) too, and not for posts only.

An example of error is this page, if you remove amp from the end of the link you find the original page: 
https://goo.gl/os0YLB

Code generating the error (i paste it because the page may be modified during my attempts to solve the problem): <link rel="amphtml" href="http://www.tech4d.it/2016/11/recensione-inateck-mercurybox-uno-speaker-bluetooth-raffinato/9-11/amp/" />

**Comment by amedina** [comment]
Will, did you resolve your issues? 

Closing this for now. Please feel free to re-open if you are still encountering the issues.
