### ISSUE TITLE
AMP creates incorrect url in "pingbacks"

### ISSUE THREAD

**Issue by linusrees** [Automattic/amp-wp#5949]
## Additional context

 - WordPress version: 5.6.2
 - Plugin version: 2.0.10
 - Gutenberg plugin version (if applicable): 10.1.0
 - AMP plugin template mode: 
 - PHP version: 7.4
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
What URL is being created? Please share more details, like a screenshot.

**Comment by linusrees** [comment]
It changes the linked url to the same url as the post. For example. If **Post A** links to **Post B**, then **Post B** would have a Pingback link to **Post A** if notifications are turned on for the page under normal circumstances. In the bug **Post B** displays the post title of **Post A** but with the url of **Post B** and appended with the two characters: #! 
This bug had the effect of changing every Pingback link across the site for every post through the entire 12 year archive of posts.

**Comment by linusrees** [comment]
Weston

Wordpress.com should have a record of the problem as I resolved it by following their instructions.

Linus

WordPress.com(Automattic)

Mar 5, 2021, 13:19 UTC

Hi there!

I'm Victor, a Happiness Engineer with WordPress.com.

We were on the live chat earlier discussing the pingback issue you are facing on the site.

As discussed on the chat, I'll share the troubleshooting steps below which should help us identify if any plugin/theme conflict is causing the pingback issue on the site.

- Install Health Check Plugin -https://wordpress.com/plugins/health-check

- Go to Tools > Site Health > Troubleshooting
- Select Enable Troubleshooting Mode.
- Once in Troubleshooting Mode, you can control which theme and plugins are enabled in the troubleshooting session. Initially, all plugins are disabled.
- Check if you can see the issue on the site right now. With all the plugins deactivated if you still see the issue, you should try to switch the theme to the WordPress.com default theme and see if the issue persists.
- At this point, if you do not see any issue, continue with the next steps. If you see the issue on the site, switch the theme and check again. If the issue still persists, please let us know.
- Go to Plugins, and activate plugins one by one by clicking "Enable while Troubleshooting" on each plugin and keep checking which plugin causes the issue you are facing right now.

📌 Please note: The troubleshooting mode only switches off the plugins for you (the admin or the users logged into the site) and not the site visitors. Once done, you can Disable Troubleshooting Mode from Tools > Site Health > Troubleshooting.

Please let us know if you have any other questions, and we'd be happy to help!

Cheers!

Victor

Happiness Engineer @ WordPress.com

For free daily live demos on how to get started with your[WordPress.com](http://wordpress.com/)site, including audience Q&A, visit[wordpress.com/webinars](https://wordpress.com/webinars/)for details on webinar topics, schedule, and registration.

**Comment by westonruter** [comment]
> Wordpress.com should have a record of the problem as I resolved it by following their instructions.

Their instructions seem to be generic troubleshooting steps. In any case, I wouldn't have access to such records since I don't work at Automattic.

> It changes the linked url to the same url as the post. For example. If **Post A** links to **Post B**, then **Post B** would have a Pingback link to **Post A** if notifications are turned on for the page under normal circumstances. In the bug **Post B** displays the post title of **Post A** but with the url of **Post B** and appended with the two characters: #!
> This bug had the effect of changing every Pingback link across the site for every post through the entire 12 year archive of posts.

Can you please share a screenshot of the link you're seeing? I'm still not clear on what the issue looks like. It may not be an issue with the AMP plugin per se but with how WordPress.com is extending it.

**Comment by linusrees** [comment]
I cannot screen shot it as... well it won't reveal the problem. (I can't hover over the link to reveal the url and take the screen shot)

Here are clumsy shots with my smartphone with the cursor hovering over the link and the status at the bottom of the screen.

Incorrect url 

![IMG_20210305_181626000](https://user-images.githubusercontent.com/12773284/110157019-9cfdf480-7ddf-11eb-8b9f-2401f88fd1ba.jpg)

Correct url

![IMG_20210305_181811638](https://user-images.githubusercontent.com/12773284/110157258-e2222680-7ddf-11eb-9093-6719bb91eef7.jpg)

**Comment by westonruter** [comment]
I'm not able to reproduce the issue myself. I did this:

0. I turned on “Attempt to notify any blogs linked to from the post” in Discussion Settings.
1. I published “Post B”.
2. I created “Post A” with a link to “Post B”.
3. I approved the pingback that appeared.
4. When I visit Post B on the frontend, I see this:

![image](https://user-images.githubusercontent.com/134745/110157359-ec6f0100-7d9c-11eb-8f6f-939fdd0ee6ce.png)

The link is to `/2021/03/05/post-a/` not the AMP version of the page.

That being said, if I enable the “Transitional” template mode and I go to the AMP version of “Post B” then at that point the pingback link does link over to `/2021/03/05/post-a/?amp` and this is part of AMP-to-AMP linking, which is normal. 

In any case, whether on an AMP page or not, I see no `#!` in the pingback URLs.

In fact, it appears that this could rather be a bug with Jetpack. I think I see the [problematic code in question](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/gravatar-hovercards.php#L133-L147), in fact:

```php
/**
 * In AMP, override the comment URL to allow for interactivity without
 * navigating to a new page
 *
 * @param string $url The comment author's URL.
 *
 * @return string The adjusted URL
 */
function grofiles_amp_comment_author_url( $url ) {
	if ( class_exists( 'Jetpack_AMP_Support' ) && Jetpack_AMP_Support::is_amp_request() ) {
		return '#!';
	}

	return $url;
}
```

You have Gravatar Hovercards enabled, yes? And are you only seeing the issue on the AMP version of a page?

**Comment by linusrees** [comment]
I'll leave it active with the bug for 30 minutes for you to see https://fitzrovianews.com/2021/02/27/westminster-council-allows-more-outdoor-eating-and-drinking-for-summer/

Linus

**Comment by westonruter** [comment]
Got it. I see, yes.

Instead of turning off the AMP plugin, you can alternatively try deactivating Gravatar Hovercards. This setting is exposed in Jetpack as follows:

![image](https://user-images.githubusercontent.com/134745/110159908-27266880-7da0-11eb-856d-9984515e452a.png)

**Comment by linusrees** [comment]
Yes, turning off hovercards works. Thanks. So is that a bug of Jetpack or AMP?

Linus

**Comment by westonruter** [comment]
It's a bug in Jetpack. I've filed this bug: https://github.com/Automattic/jetpack/issues/19052. I believe I see the issue and I'm going to open a pull request to fix.

**Comment by linusrees** [comment]
Well done. I'd spent hours trying to resolve this. Thanks for your help.

Linus
