### ISSUE TITLE
Notice: Undefined index: global.css in {…}critical-css.class.php on line 578

### ISSUE THREAD

**Issue by samkatakouzinos** [Automattic/amp-wp#596]
> Notice: Undefined index: global.css in {…}critical-css.class.php on line 578

Above occurs when a theme; 
* does not yet have a {theme-dir}/abovethefold/css/global.css created 
* define('WP_DEBUG') = true;

When define('WP_DEBUG') = true visitors will see notice until an administrator visits {…}/wp-admin/admin.php?page=abovethefold&tab=criticalcss and saves at least once.

**Comment by mjangda** [comment]
`critical-css.class.php` is not a part of the AMP plugin so this is likely an issue with another plugin or theme that you're using.

**Comment by samkatakouzinos** [comment]
You are correct. 
I misplaced this issue here. 
I apologise for the mistake.
