### ISSUE TITLE
Support proxy.

### ISSUE THREAD

**Issue by jkroepke** [Automattic/amp-wp#597]
Hi!

We have an environment without a direct internet access. A proxy is required. While all wordpress works with a proxy, amp use fopen without an proxy. Got error messages like this:

```
2016/12/27 01:00:25 [error] 6542#6542: *1183 FastCGI sent in stderr: "PHP message: PHP Warning:  fopen(http://csgo-stats.com/graphic.png): failed to open stream: No route to host in /htdocs/wp-content/plugins/amp/includes/lib/class-fastimage.php on line 31" while reading response header from upstream, client: , server: , request: "GET /member/amp/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:"
```

Its possible to use an proxy with fopen. For example:

```
$context = stream_context_create(array(
    'http' => array(
        'proxy' => 'tcp://192.168.10.10:80' // The proxy server address and port
    ),
));

$file = fopen($url, 'r', false, $context)
```

**Comment by jkroepke** [comment]
Switching to curl is awesome! 

I have not try it, but the FastImage class still using fopen instead curl. Doesn't Wordpress provide a HTTP fetch API?

**Comment by mjangda** [comment]
We use a different library for environments on PHP5.3 and above that uses `curl_multi`.
