### ISSUE TITLE
Dark Mode background is overridden by custom background color for Twenty Twenty One theme.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#5975]
## Bug Description
A user reported this in [support forums ](https://wordpress.org/support/topic/words-are-unreadable-after-installing-default-wordpress-theme/)

When using the Twenty twenty-one theme with custom background color and system is set to dark mode the background is overriding background resulting in unreadable text. the issue is not producable with the theme default background color.

## Expected Behaviour

It should use the background global variable for dark mode.

## Steps to reproduce

1. Switch your system to dark mode (Mac Dark Mode)
2. Visit Customizer
3. Enable Dark Mode.
4. Change the background color to something else than the default. (white)
5. Visit the AMP page.

## Screenshots
https://user-images.githubusercontent.com/1132541/110802225-00869700-82a4-11eb-9b01-946a5370ec45.mp4

## Additional context

 - WordPress version: 5.7
 - Plugin version: 2.0.11
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Transitional 
 - PHP version: 7.4
 - OS: Mac OS Catlina 
 - Browser: chrome
 - Device: Macbook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
**QA Passed.**

Steps I took:
1. Set website to AMP Standard
2. Switched Mac to dark mode
2. Went to Customizer and enabled dark mode
3. Chose a dark brown
4. Saw that the text switched
5. Visited page with AMP checkmark in WordPress toolbar

<img width="962" alt="Screen Shot 2021-04-26 at 7 55 58 AM" src="https://user-images.githubusercontent.com/3411173/116103927-e4c52d80-a664-11eb-93fe-95a186ddd98c.png">
