### ISSUE TITLE
Server infrastructure for PSI requests

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#5976]
## Feature description

To fetch performance metrics from the PageSpeed Insights API, you need a PageSpeed Insights API key. Shipping the plugin with an API key is a bad idea, as it will lead to problems with rate-limiting as well as potential abuse. But asking the user to provide an API key is not a good idea either, as they'd need to create a Google Cloud Platform project first (which requires a GCP account). This is a very big hurdle, and most users will feel intimidated or won't want to create such an account.

I propose building a simple piece of infrastructure to get around this:

![Overview](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuShBJqbLKFB9JqnHS4hCISnBJYrIKaWiLiX9Wag5vnTbfnOf6895omqLghaK51JICdDI5GA2FUCT0ppZlLqZumsvQb7L6q7K6-5GRuIkFW-YFaz1EISpBrKl9R-a93K5XsO_e6Qkd2G5NLqxa8ki59GKbE1y8pH-7fJla9gN0lGm0000)

Each worker would be a simple API endpoint that accepts a URL and returns a PSI report for that URL. The worker loads the markdown of the URL and checks the generator tag to make sure the page was generated by the AMP plugin, as a form of abuse prevention. Then it uses its attributed PSI API key to fetch the PSI report and forwards it back to the requesting client.

If a Worker triggers rate-limiting, it responds to the load balancer as being unavailable, so that the load balancer redirects the request to the next available worker.

To avoid churning through the keys too quickly, we can add basic rate-limiting to the plugin.

We can also use an IP hash algorithm for the load balancer and use a simple local cache in the workers to add basic rate-limiting at an IP level.

This type of infrastructure will allow fetching PSI reports from any server having the AMP for WordPress plugin installed without requiring the site owner to deal with the API key. It also keeps us in control of the server resources used and the API keys used.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
As an alternative to cycling through API keys, could we not just ensure that our API key for PSI has a sufficient rate limit? the AMP Page Experience guide is using the same API key for all requests AFAIK, so it seems we could do the same.
