### ISSUE TITLE
Add AMP status notification to the pre-publish panel and to the AMP panel in the document sidebar

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#5997]
## Feature description

As proposed in #5304, the AMP validation status notifications have been revamped in the AMP sidebar in #5929.

A similar notification should be now added to the editor pre-publish panel and to the AMP panel in the document sidebar.

<img width="1008" alt="Screenshot 2021-03-19 at 16 29 51" src="https://user-images.githubusercontent.com/478735/111804450-642a4900-88d0-11eb-9d83-64ef02bd805f.png">

<img width="956" alt="Screenshot 2021-03-19 at 16 30 02" src="https://user-images.githubusercontent.com/478735/111804462-668ca300-88d0-11eb-9792-5027da91a29b.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jwold** [comment]
Tested all the states mentioned above. Looks great!
