### ISSUE TITLE
Reduce impact of third party code

### ISSUE THREAD

**Issue by rsmith4321** [Automattic/amp-wp#6000]
## Bug Description

Most of the time when I test with Pagespeed Insights I don't have any issues. I also use a tool called StatusCake that does automatic testing. Occasionally Pagespeed insights will report a long blocking time for the AMP scripts, and I can see large spikes in the load time on StatusCake as well.  If I disable amp, my website always loads in under 400ms and there are no spikes in load time, so it is an amp specific issue. I can't figure out what is causing this issue, but over a second just to load the amp scripts seems too long. 

## Expected Behaviour

AMP scripts should not cause long blocking times.

## Steps to reproduce

Test website with Pagespeed Insights

## Screenshots

https://drive.google.com/file/d/1_ZelBbkrfRbL4watjFgUdV6VjBStacix/view?usp=sharing

## Additional context

 - WordPress version: 5.7
 - Plugin version: 2.0.11
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: standard
 - PHP version: 7.4
 - OS:
 - Browser: chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Hello @rsmith4321, this would be a question for the AMP core project. Please file your issue upstream: https://github.com/ampproject/amphtml/issues.

You also might be interested in https://github.com/ampproject/amphtml/issues/28310, which intends to help with unused JS by splitting the scripts into modern JS and legacy JS that includes polyfills.
