### ISSUE TITLE
$wp_query->in_the_loop is empty

### ISSUE THREAD

**Issue by webzunft** [Automattic/amp-wp#601]
$wp_query->in_the_loop is empty on the AMP version of a single post page and hence the `in_the_loop()` tag not working either.

Is this a known limitation or a bug?

If this is known, how can we do a similar check?

**Comment by webzunft** [comment]
I found the template file now and see that the loop is not used when creating AMP pages. I let the developers decide whether this might still be an improvement to consider or not.

**Comment by amedina** [comment]
Thanks for participating in the project; currently the plugin supports only single posts; the loop is used in pages, such as the index page. Support for pages is in the roadmap. Stay tuned!
