### ISSUE TITLE
Validating a URL that has a massive number of validation errors causes validation request to fail

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#6011]
## Bug Description

While in Transitional mode I attempted to validate my homepage (which is set show the latest posts). Doing so resulted in the following error:

![image](https://user-images.githubusercontent.com/16200219/112102950-f10b2600-8ba0-11eb-9b9d-6ba1c16b573d.png)

After verifying that there were no errors being logged and the error was not due to any project files being changed recently, I went ahead to do some debugging and found that the validation request was indeed fetching the validation errors successfully, but for some reason the URL validation still was failing. As it turns out, the reason for this was due the validation response becoming `null` after stripping HTML comments from it:

https://github.com/ampproject/amp-wp/blob/2de8936d48d6180c9cdfc6e2424b3cd54c271536/includes/validation/class-amp-validation-manager.php#L1850-L1851

A regex catastrophic backtracing error was occurring whenever the JSON object containing a massive number of validation errors was attempting to be stripped of any possible HTML comments. For testing purposes that JSON object can be found [here](https://gist.github.com/pierlon/cffc667733eb5943182ba0e949a3a4d7).

## Expected Behaviour

Validating a URL with a massive number of validation errors should not lead to a regex catastrophic backtracing error when attempting to strip HTML comments from the response.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
After further analysis of this issue, I've determined the catastrophic backtracing error is caused by the massive amount of characters that is being consumed in between the _first_ HTML comment detected. For example, given the current regex being used and the text `{"text":"<!--a-->"}<!-- An appended comment -->`, [here is what would be matched](https://regex101.com/r/rrUha0/1):

![image](https://user-images.githubusercontent.com/16200219/112374537-236c6e80-8cda-11eb-97d7-253fba6e0b19.png)

As you can see the match starts from within the JSON object, which is not what is expected here as we only want to match the appended HTML comment. Now here's the same text, but with the character `a` in the first HTML comment being [repeated 100,000 times](https://regex101.com/r/4PSeEE/1):

![image](https://user-images.githubusercontent.com/16200219/112381450-7ea25f00-8ce2-11eb-92c4-792cf7c65f3e.png)


Now the match fails due to regex not being able to continue consuming characters after a certain limit (which I haven't found out why as yet). The solution here would be to optimize the regex so that it ignores the JSON object, and only focuses on the text _after_ it.

**Comment by westonruter** [comment]
**QA Passed**

I added a mu-plugin that does:

```php
ob_start( function ( $content ) {
	return $content . '<!-- Comment at end!!! -->';
} );
```

I can see this comment at the end of AMP and non-AMP pages. When I try validating an AMP page, no error occurs. So the comment is being successfully stripped out.
