### ISSUE TITLE
AMP static page

### ISSUE THREAD

**Issue by michaelvdberg** [Automattic/amp-wp#602]
Maybe this is already answered in an earlier issue but I got the following problem. I use the latest version, but Google Webmaster Tools couldn't find the AMP version of a static page. For example the contact page or homepage.

Did anybody now how to resolve this issue or how I could deactivate the area for the static pages AMP?

**Comment by amedina** [comment]
Pages are not supported by the plugin, yet. Coming! 

Closing for now; feel free to re-open if you need to discuss further.
