### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by vnahalpara** [Automattic/amp-wp#603]
my url is like this

https://abc.com/index.php/admin/sales_order/view/order_id/10959/info.phtml?salesorderproducthidden=%23%23%231%C2%A0perper+pack%C2%A0X%C2%A0Indian+Sandstone+Paving+-+Raj+Green+-+Patio+Pack%C2%A0%2848%C2%A0per+pack%29%C2%A0%28code+%3D%C2%A0hs.raj.pp.14.72.uncal%29%C2%A0%C2%A0%C2%A3%40%40%40160.13%C2%A0%C2%A0%24%24%24Buy+from+Hardcores+at+%C2%A310.50%2Fm%2C+if+not+in+stock+buy+from+RF+%40+%C2%A312.75%2Fm%0D%0A%0D%0ACurrently+selling+at+%C2%A312.42+%28%C2%A31%2Fm+extra+for+Split+Pack%29%0D%0A%0D%0Aspecial+price+was+224.41%26%26%26%5E%5E%5E%0D%0A%23%23%231%C2%A0perper+pack%C2%A0X%C2%A0Indian+Sandstone+Paving+-+Raj+Green+-+3+sq+m%C2%A0%2811%C2%A0per+pack%29%C2%A0%28code+%3D%C2%A0hs.raj.pp.3m.uncal%29%C2%A0%C2%A0%C2%A3%40%40%4036.00%C2%A0%C2%A0%24%24%24Buy+from+Hardcores+at+%C3%82%C2%A312.00%2Fm%2C+if+not+in+stock+buy+from+RF+%40+%C3%82%C2%A312.75%2Fm%0D%0A%0D%0ACurrently+selling+at+%C3%82%C2%A314.00++%28%C3%82%C2%A31%2Fm+extra+for+Split+Pack%29%26%26%26%5E%5E%5E%0D%0A&salesorderproducthidden_id=100008967&salesorderproducturl=https%3A%2F%2Flsd.co.uk%2Findian-sandstone-paving-raj-green-patio-pack***%0D%0Ahttps%3A%2F%2Flsd.co.uk%2Findian-sandstone-paving-raj-green-3m2***%0D%0A&salesorderproducthidden_qty=0000&salesorderproduct_cost_note=Buy+from+Hardcores+at+%C2%A310.50%2Fm%2C+if+not+in+stock+buy+from+RF+%40+%C2%A312.75%2Fm%0D%0A%0D%0ACurrently+selling+at+%C2%A312.42+%28%C2%A31%2Fm+extra+for+Split+Pack%29%0D%0A%0D%0Aspecial+price+was+224.41%0D%0ABuy+from+Hardcores+at+%C3%82%C2%A312.00%2Fm%2C+if+not+in+stock+buy+from+RF+%40+%C3%82%C2%A312.75%2Fm%0D%0A%0D%0ACurrently+selling+at+%C3%82%C2%A314.00++%28%C3%82%C2%A31%2Fm+extra+for+Split+Pack%29%0D%0A&purchase_submit=Purchase+Products

and I am using nginx server my  large_client_header_buffers 8 16k;

how can i solve this issue how much value required for large_client_header_buffers

**Comment by mustafauysal** [comment]
Hi @vnahalpara,

What's the problem with amp plugin? 

This problem looks irrelevant, but anyway http://stackoverflow.com/a/1067462/1942303 and http://stackoverflow.com/a/417184/1942303 could help you.
