### ISSUE TITLE
Provide mechanism to prevent noscript unwrapping

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6030]
## Feature description

As noted in a [support topic](https://wordpress.org/support/topic/support-420/), the `noscript` element is allowed. The AMP spec [states](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#:~:text=Can%20be%20used%20anywhere%20in%20the%20document.):

> Can be used anywhere in the document. If specified, the content inside the `<noscript>` element displays if JavaScript is disabled by the user.

Nevertheless, in our script sanitizer we unwrap all `noscript` elements so that its contents will become the baseline AMP version while any adjoining scripts are stripped out. In general the most helpful behavior for existing plugins which aren’t built to support AMP is to unwrap the noscript elements so that their contents become the fallback on the AMP page. 

We don't currently provide a way for developers to _intentionally_ serve a `noscript` element on a page. This could be done via a data attribute, like `data-amp-wp-preserve`:

```html
<noscript data-amp-wp-preserve>
    <p>Sorry, you have JS turned off!</p>
</noscript>
```

The logic would be incorporated here:

https://github.com/ampproject/amp-wp/blob/302cb042c511660022a1f949626105d06531d1af/includes/sanitizers/class-amp-script-sanitizer.php#L41-L47

```php
if ( 
    'amp-' === substr( $noscript->parentNode->nodeName, 0, 4 ) 
    ||
    $noscript->hasAttribute( 'data-amp-wp-preserve' )
    ||
    DevMode::hasExemptionForNode( $noscript ) 
) {
```

Actually, now that I look at this, there _is_ a way to prevent the `noscript` from being removed at present: just add the `data-ampdevmode` attribute. This, however, is not very intuitive. It also seems to somewhat be a mistake because it should not only be checking of the element has `data-amodevmode` but _also_ that the root `html` element also has this attribute. This may have been something that was missed in bf80642a939effd70aec4be24012c6378f6d4ccd. It should be checking if `hasExemptionForNode` _and_ `isActiveForDocument`—in other words, it should be using `isExemptFromValidation`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by bartoszgadomski** [comment]
**QA passed**

I tested this with below plugin:

```
<?php
/**
 * Plugin name: Test noscript unwrapping
 */
add_action(
    'wp_body_open',
    function() {

        ?>
        <noscript data-amp-no-unwrap><span>I'm for no-js only</span></noscript>
        <noscript><span>Hey there</span></noscript>
        <?php
    }
);
```

![Screenshot 2021-12-8 at 17 13 06](https://user-images.githubusercontent.com/4476915/145243266-506a64c7-2ce9-448b-bf46-2c5847b02334.png)
![Screenshot 2021-12-8 at 17 12 57](https://user-images.githubusercontent.com/4476915/145243268-fccdd5b0-b375-49b3-96ba-4a982e40811a.png)
