### ISSUE TITLE
CSS syntax error in tag 'style amp-custom' - bad url.

### ISSUE THREAD

**Issue by k-atul** [Automattic/amp-wp#604]
Plugin is not creating background url for inline amp-wp styling for Instagram embed, the inline style code is breaking due to no image url, please add a fallback or fix for the same. Broken style "background:url(", we are on wordpress VIP.

Please check below url:
http://indianexpress.com/article/entertainment/bollywood/jennifer-lopez-nicole-scherzinger-add-star-power-to-sanjay-hinduja-anu-mahtanis-udaipur-wedding/lite/
http://indianexpress.com/article/lifestyle/fashion/lily-cole-flaunts-dress-made-of-plastic-bottles-on-the-oscars-2016-red-carpet/lite/

.amp-wp-inline-6b058bf4d14bfd6100311e6b5d86d8fe{background:url(data:image/png;display:block;height:44px;margin:0 auto -44px;position:relative;top:-22px;max-width:44px;}

**Comment by maxhartshorn** [comment]
Any updates here? Our amp-validation is breaking because of this issue

**Comment by amedina** [comment]
The links provided validate successfully; are you still experiencing this issue?

**Comment by k-atul** [comment]
@amedina its fixed. thanks

**Comment by amedina** [comment]
Thanks @k-atul; glad to hear. Thanks for using the plugin reporting the issue.
