### ISSUE TITLE
Return value of amp_is_request() with AMP Legacy in Reader template mode

### ISSUE THREAD

**Issue by pewgeuges** [Automattic/amp-wp#6055]
## Bug Description

The `amp_is_request()` function returns `false` in Reader template mode when the endpoint is `?amp` and the **AMP Legacy** theme is used. As a result, the AMP markup is not added by the plugin calling `is_amp_endpoint()`, and the page doesn’t work. 

In Transitional mode, these functions work as designed, and the markup is added when the endpoint is AMP, not when not.

## Expected Behaviour

The return value of `is_amp_endpoint()` and `amp_is_request()` is always true when the page should be rendered in AMP mode, regardless of the template mode.

In Transitional mode, these functions already work as designed, and the markup is added when the endpoint is AMP, not when not. In Standard mode they also work as intended.

## Steps to reproduce

Apply @milindmore22’s [fix](https://github.com/markcheret/footnotes/issues/48#issuecomment-814193614) to the [WordPress Testing Playground](https://plugins.dev6.rt.gw), switch to Reader mode and open [Footnotes test in AMP](https://plugins.dev6.rt.gw/2021/04/footnotes-test/?amp).

## Screenshots

It happens just nothing, neither expanding the footnotes list nor scrolling to the footnote in the list, because both the tap event and the hard link are missing as for jQuery mode without hard links enabled.

## Additional context

 - WordPress version: 5.7
 - Plugin version: 2.1beta
 - Gutenberg plugin version (if applicable): N/A
 - AMP plugin template mode: Reader
 - PHP version: 
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
This doesn't seem to be the case. For example, given this plugin code:

```php
add_action('amp_post_template_body_open', function () {
	printf( '<p>amp_is_request() === %s</p>', json_encode( amp_is_request() ) );
});
```

I get this:

> ![legacy-reader](https://user-images.githubusercontent.com/134745/113917146-b2c35880-9795-11eb-852a-4e36c9734c9a.png)

So you can see that `amp_is_request()` is returning `true` in the AMP Legacy Reader template.

Your issue is likely that you were calling `amp_is_request()` too early. If you have `WP_DEBUG` enabled, you'd probably be seeing `_doing_it_wrong()` warnings.

**Comment by pewgeuges** [comment]
@westonruter 

Thanks for testing. 

> So you can see that `amp_is_request()` is returning `true` in the AMP Legacy Reader template.
> 
> Your issue is likely that you were calling `amp_is_request()` too early. If you have `WP_DEBUG` enabled, you'd probably be seeing `_doing_it_wrong()` warnings.

It doesn’t give me the warning. The problem is that it must be called before enqueuing the scripts. Else the libraries would be enqueued only for AMP-WP to remove them. But I will test this and call `amp_is_request()` again for the markup part.

**Comment by pewgeuges** [comment]
It does not work in Reader mode, even when `amp_is_request()` is called just when processing the footnotes, and the whole page is already built depending on priority levels. Also I’ve tested it with PHP_INT_MAX priority level and still doesn’t work. While it works perfectly in Transitional and Standard modes.

**Comment by westonruter** [comment]
What action are you calling it at?

**Comment by pewgeuges** [comment]
@westonruter 

> What action are you calling it at?

It is used to set the AMP-enabled Boolean that serves as a condition to add the AMP `on` attribute, not add `onclick`, and correct the hard-links-enabled Boolean. It is also used to select the templates. Thanks to the variable, `amp_is_request()` is not called more than thrice, but once is indeed not enough:

> Your issue is likely that you were calling amp_is_request() too early.

Thanks to your advice I’ve added two more calls, one before adding configurable style rules in the header, one before processing the footnotes. Thanks to this it now works in all three modes, except that in Reader mode, the configurable scroll offset is removed, only `.footnote_item_anchor, .footnote_referrer_anchor{position:absolute}` is kept from the style sheet. In Transitional mode and Standard mode, `.footnote_referrer_anchor,.footnote_item_anchor{bottom:20vh}` is kept too.


@milindmore22 

In response to [your question](https://github.com/markcheret/footnotes/issues/48#issuecomment-814193614)recently I noticed that it only works in Standard mode but didn’t have a chance to effectively update the dashboard:

![Screenshot from 2021-04-07 21-50-06](https://user-images.githubusercontent.com/73141620/113925544-6efb3e00-97eb-11eb-8624-b89a1148bc4d.png)

I understood that with this limitation the plugin is not fully compatible, wondered how others are doing, and forgot that a Contributor had posted in the forum a function name with link to the documentation. My apologies for missing out on it!

**Comment by westonruter** [comment]
@pewgeuges I'm still not understanding. The `amp_is_request()` function is only applicable to be called on the frontend. It will always be false in the admin. And it can only be called at or after the `wp` action since that is when the query is populated.

**Comment by pewgeuges** [comment]
@westonruter

Making the AMP Legacy Reader theme work with Footnotes failed at my end so far.

> The `amp_is_request()` function is only applicable to be called on the frontend.

That is likely to be true for all 3 calls:

1. It is called by `MCI_Footnotes::register_public()` that enqueues the stylesheet, because of a dedicated stylesheet for AMP tooltips concatenated for production;
1. It is now also called by `MCI_Footnotes_Task::footnotes_output_head()` that outputs the internal CSS, because some rules depend on AMP enabled status;
1. It is now also called by `MCI_Footnotes_Task::search()` that processes the footnotes, as templates and markup depend on AMP or not.

> It will always be false in the admin.

The admin has only the AMP compatibility mode setting metabox under the first dashboard tab, that should now be removed as pointless.

> And it can only be called at or after the `wp` action since that is when the query is populated.

It seems that this is always true too, but that the problem is that the AMP Legacy theme does not call the `wp_head` action. I’ve added a check that outputs that the internals have been added all the time except in Reader mode in AMP. Also when the style start tag is `<style amp-custom>`.Searching for `wp_head` in the AMP-WP plugin brought not up any instance where the AMP Legacy theme would apply the filters to `wp_head` (among which the one added by the Footnotes plugin).

To fix it I’ve tried to output the internal CSS appended to the footnotes list container. Then AMP-WP takes it and moves it inline, without the <style amp-custom></style> tags, at the start of the body element content (not inside a style element it populates).

**Comment by milindmore22** [comment]
Hello @pewgeuges 

I don't see any issue while testing my code snippet, You can test this on https://plugins.dev6.rt.gw/2021/04/footnotes-test/

```php
/**
* Enqueues external scripts.
*
* - Bugfix: Libraries: optimize processes by loading external and internal scripts only if needed, thanks to @docteurfitness issue report.
 *
* @since 2.5.5
* @reporter @docteurfitness
* @link https://wordpress.org/support/topic/simply-speed-optimisation/
*
* The condition about tooltips was missing, only the not-alternative-tooltips part was present.
*/
// Set conditions re-used for stylesheet enqueuing and in class/task.php.
//self::$a_bool_amp_enabled                  = MCI_Footnotes_Convert::to_bool( MCI_Footnotes_Settings::instance()->get( MCI_Footnotes_Settings::C_STR_FOOTNOTES_AMP_COMPATIBILITY_ENABLE ) );
self::$a_bool_tooltips_enabled             = MCI_Footnotes_Convert::to_bool( MCI_Footnotes_Settings::instance()->get( MCI_Footnotes_Settings::C_STR_FOOTNOTES_MOUSE_OVER_BOX_ENABLED ) );
self::$a_bool_alternative_tooltips_enabled = MCI_Footnotes_Convert::to_bool( MCI_Footnotes_Settings::instance()->get( MCI_Footnotes_Settings::C_STR_FOOTNOTES_MOUSE_OVER_BOX_ALTERNATIVE ) );
self::$a_str_script_mode                   = MCI_Footnotes_Settings::instance()->get( MCI_Footnotes_Settings::C_STR_FOOTNOTES_REFERENCE_CONTAINER_SCRIPT_MODE );

if ( did_action( 'wp' ) && function_exists( 'is_amp_endpoint' ) ) {
	self::$a_bool_amp_enabled = is_amp_endpoint();
}
```

Regarding Legacy theme it uses [amp_post_template_head](https://amp-wp.org/reference/hook/amp_post_template_head/) which equivalent to `wp_head` and you can also use [amp_post_template_css](https://amp-wp.org/reference/hook/amp_post_template_css/) for css.

This discussion seems to be specific to the footnotes plugin and not an issue with the AMP plugin. so I will mark this as close, Let's continue the discussion on https://github.com/markcheret/footnotes/issues/48 OR you can always [create a new support topic](https://wordpress.org/support/plugin/amp/#new-topic-0) on WordPress support forums

**Comment by pewgeuges** [comment]
@milindmore22 

Thank you! 

`amp_post_template_head` has fixed the scroll offset.
