### ISSUE TITLE
Deprecate amp_is_request() and rename it to amp_is_on()

### ISSUE THREAD

**Issue by pewgeuges** [Automattic/amp-wp#6056]
## Feature description

The `amp_is_request()` and `is_amp_endpoint()` function names contradict their design of returning always `true` in Standard template mode: “it returns true […] in standard mode if just the template is available.” So it would be great to give this a more descriptive name that makes always sense. 

Pick suggested at this point: `amp_is_on()`.

An AMP endpoint is used as a trigger to switch AMP on when the template mode is Reader or Transitional, whereas AMP is permanently on wherever the website is in the recommended Standard mode.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
The `is_amp_endpoint()` function is soft-deprecated in favor of `amp_is_request()`. 

> AMP is permanently on wherever the website is in the recommended Standard mode.

This is not correct. You can still only enable AMP for a subset of your site even in Standard mode. You can have it enabled only for the `singular` template for example, or you can turn if off for a singular post.

**Comment by pewgeuges** [comment]
> The `is_amp_endpoint()` function is soft-deprecated in favor of `amp_is_request()`.

Both are indeed currently in use.

> > AMP is permanently on wherever the website is in the recommended Standard mode.
> 
> This is not correct. You can still only enable AMP for a subset of your site even in Standard mode. You can have it enabled only for the `singular` template for example, or you can turn if off for a singular post.

I forgot about this. It can be turned off e.g. for the checkout page when it requires JavaScript. Then “request” is a good pick as the request may be internal and does not assume the URL has an AMP endpoint.
