### ISSUE TITLE
AMP  for WordPress appends a query string ?amp=1 is breaking popular PDF Embed plugin

### ISSUE THREAD

**Issue by dehaven2** [Automattic/amp-wp#6066]
Lever Technology now owns PDF Embed. They say "This conflict needs to be addressed on the AMP side due to how it appends a query string ?amp=1 to the end of the page URLs. When this happens, the scripts are not loaded correctly and the viewer isn't called to display the PDF." What was happening before we isolated this plugin conflict was that instead of displaying the PDF the file name is displayed, but clicking on that would always take someone tot he homepage.

**Comment by westonruter** [comment]
Please share the URL to the AMP page that has the problem.

**Comment by westonruter** [comment]
It sounds like the AMP plugin is removing the PDF viewer scripts make the page valid AMP. This is working as expected. If you can't find an AMP-compatible way to embed PDFs, then you should disable AMP for the pages that have the PDF viewers.

**Comment by westonruter** [comment]
There is a [`amp-google-document-embed`](https://amp.dev/documentation/components/amp-google-document-embed/?format=websites) component which can be used to add a PDF viewer to AMP pages.

The plugin in question is [PDF Embedder](https://wordpress.org/plugins/pdf-embedder/). @milindmore22 would you look into whether they'd take a contribution to make it AMP compatible and/or see about a mini plugin that would shim compatibility?

**Comment by dehaven2** [comment]
Sure Weston I will pass this along to the person who sent that evaluation of what is happening and put you two in contact. No problem.

**Comment by dehaven2** [comment]
Emma,

I am putting you in touch with a software engineer who works on the WordPress AMP plugin referenced below. Here is what he wrote to me in his last email:

> The plugin in question is PDF Embedder <https://wordpress.org/plugins/pdf-embedder/>. @milindmore22 <https://github.com/milindmore22> would you look into whether they'd take a contribution to make it AMP compatible and/or see about a mini plugin that would shim compatibility?

I would appreciate someone letting me know if this problem is resolved. I cannot Weston's suggestion for disable pages that are using PDF Embed because of the nature of my work. So until this is resolved, I cannot use the AMP plugin. 

Luther DeHaven
Austin, Texas

**Comment by dehaven2** [comment]
I checked and *Emma* ***@***.***>, is in the To box. I am sure she will contact you about the plugin conflict. I believe you asked me to do this.

**Comment by westonruter** [comment]
@dehaven2 ok, well I don't know, but your email is publicly visible at  https://github.com/ampproject/amp-wp/issues/6066#issuecomment-818296791

**Comment by dehaven2** [comment]
Thanks Weston. I misunderstood you.

**Comment by milindmore22** [comment]
Yes, I was unable to find their repo, I will contact them and check if they accept a contribution, Also, start working on a mini plugin that will support AMP compatibility for now.

**Comment by milindmore22** [comment]
Hello @dehaven2 

Please download and install [AMP support/compatibility for WordPress PDF Embedder](https://github.com/milindmore22/amp-pdf-embedder-compat), you just need to activate it, no settings needed.

You can check the demo of the same plugin [here] (https://plugins.dev6.rt.gw/2021/04/pdf-embedder-test/?amp ) 

Let me know if you need further assistance.
