### ISSUE TITLE
unable to get traces left removed in my wordpress site 

### ISSUE THREAD

**Issue by cryptomail2018** [Automattic/amp-wp#6068]
![Capture](https://user-images.githubusercontent.com/35930742/113189366-53d97d00-9285-11eb-9f70-ed514c812ee3.JPG)

unable to remove AMP left behinds after uninstall 

i been reading threaths about this previously but still not find the answer 

please advice soonest in basic terms how to resolve this please

im am not a developer programmer 

thank you 

Marc 

PS: my email : 
cs@achievedprofits.com

**Comment by kristoferbaxter** [comment]
Moving this item to `amp-wp`. Thanks @westonruter!
