### ISSUE TITLE
When categories are hidden from a site's Content options, they appear in the AMP preview (but not on the live mobile view)

### ISSUE THREAD

**Issue by gracie** [Automattic/amp-wp#607]
Steps to reproduce:

1. Activate a theme that has a Content Options section in the Customizer (example:Gateway or Lenscap).

2. Navigate to Customize > Content Options > Deselect Display categories.

3. Click Save & Publish

4. In https://wordpress.com/settings/general activaate AMP, then click Edit Design

What I expected: To see the categories hidden in the preview.

What happened: The categories show in the AMP preview.

https://cloudup.com/c_zpjCEQ43l

Reported in #576147-t

**Comment by westonruter** [comment]
I think this is something that should be reported to WordPress.com support.

The general answer here is that the AMP pages are served using bundled post templates that are different than the templates in your installed theme. The WordPress.com theme should extend the AMP post templates to ensure that the categories are hidden when the setting is changed for the non-AMP theme options.
