### ISSUE TITLE
Advise users to review site after enabling AMP to ensure working as expected

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6071]
## Feature description

We received an [honest review](https://wordpress.org/support/topic/good-but-check-your-website-thoroughly/) of the plugin which I think highlights something we are not currently capturing. Namely, once the user has activated the site we need there to be a call to action for the user to browse around their site to make sure it is working as intended. We need to emphasize that the user should check any interactive features, like mobile nav menus, forms, carousels, and other features to ensure they still work.

The upcoming site scanning feature will reduce the amount of manual checking required, but still the user needs to understand what to expect and what to look for. Eventually the onboarding wizard could have an interactive means of taking the user around the site and have a checklist of things to verify.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Upon completion of Onboarding Wizard, user is asked to review site (checking each template, trying navigation menu, etc) to ensure nothing is broken. This notice should be presented whenever there is a change to the template mode.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@westonruter I think this could also be an opportunity to emphasize that the plugin assists users to achieve AMP valid content and that CSS and JavaScript limitations are aspects of the AMP framework, and not plugin limitations. We've received another review based n possible misunderstanding of how the plugin works. 

One possible approach is to add a notice below the proposed call to action button, similar to the below:

_If you find something not working as expected or if you need assistance [reach out in the support forums](https://wordpress.org/support/plugin/amp/#new-post) || click here_

The "Click here" button could point to an updated sticky post. This could highlight that non AMP valid content including ad code, analytics code or JavaScript based functionality will be removed by default (on AMP URLs only) - to ensure fully AMP pages.

**Comment by westonruter** [comment]
We do have a [Welcome](https://github.com/ampproject/amp-wp/blob/develop/assets/src/settings-page/welcome.js) component which knows whether or not the plugin has been configured. This could include a paragraph that explains what to expect.

Also, the initial screen of the Onboarding Wizard should have similar messaging (#4943). The final screen of the Onboarding Wizard (#4954) should have a call to action to check out the site, and then also remind them about AMP's constraints so they know what to expect and what to look for. 

In each case, we can have a link off to the support forum to get additional help.

@jwold Could you review those screens (Settings, Onboarding Wizard Welcome, and Onboarding Wizard Done) to find where we can help users with understanding?

**Comment by westonruter** [comment]
This goes along with Site Scanning. After having done a Site Scan in the onboarding wizard, the results could recommend whether the user should use Standard mode. On the last step of the onboarding wizard, where we should the preview of the site, we can show them not only the latest post but have come up with a list of URLs to check and encourage the user to click each and see how the pages behave. The URLs could correspond to the set of URLs that we use for site scanning. If there are any problems, the user can go back to change the mode.

**Comment by jwold** [comment]
Further notes from today's call:

* MC > I saw that WR had a comment on the issue, and mentioned it could be part of site scanning, however on yesterday’s call the team thought about in the Curren onboarding wizard itself we could add a quick instruction about going ahead and testing out the site so that it’s something that could be included at the earliest. 
* WR > Yeah, I can’t remember the last screen of the onboarding wizard, I think it says congrats and has a paragraph. The preview doesn’t show up in one of the modes. If we don’t have instructions to say, “review site,” and click around in iframe to see how site is working, we should do that. Then we could also take that a step further to actually have a list of links perhaps, homepage, archive page, blog post, a sample set of URLs that have unique templates on the site; those same urls we use on an ongoing basis for site scanning, those urls could also be listed on that screen to do a cursory check.
* WR > The user might know as well which URLs are most important to check, we can provide those as hints or suggestions, and it’d be up to the user to check the site out. 
* RB > Maybe we can check URLs included in WP nav? Those are likely to be very important. 
* WR > Yeah that could be great.

**Comment by jwold** [comment]
![Welcome](https://user-images.githubusercontent.com/3411173/126228290-f07e8ce4-f74a-4471-9ce5-dd719be11ef4.png)

![Done standard](https://user-images.githubusercontent.com/3411173/126228303-4c7209b6-ef6f-42ba-aba7-0775bf6414cd.png)

Adding visual updates per latest discussion, pending approval on design. [Figma link](https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=2001%3A4812).

**Comment by westonruter** [comment]
For this line:

> • Try a different template mode in settings

I think it may make sense to link back to the Template modes screen in the wizard itself, instead of linking to the settings screen.

**Comment by jwold** [comment]
@westonruter 

1. Will the plugin be able to detect the top level navigational menu items on a site, and auto-populate those links under the `Review your site` section? (example: https://d.pr/i/81hfri)
2. If we can detect those items, would it be possible to make them clickable so that selecting them updates the preview window on the right? (example: https://d.pr/i/YqDv9G)

**Comment by westonruter** [comment]
> 1. Will the plugin be able to detect the top level navigational menu items on a site, and auto-populate those links under the `Review your site` section? (example: https://d.pr/i/81hfri)

This could look at the theme's registered nav menu locations and obtain any links from the associated nav menus. But that may not be the most representative of all the various templates of the site. What may be more helpful is to use the same URLs that we're thinking to use for Site Scanning. As mentioned in https://github.com/ampproject/amp-wp/issues/4795, the `ScannableURLProvider::get_urls()` function returns the URLs for key template types including homepage, single post, search results, category archive, etc. That may give a better sample set of URLs with varying templates to expose possible problems.

(Come to think of it, perhaps this `get_urls()` function could obtain the URLs from the nav menus and try to prioritize them among the sample set. So instead of getting the most recently-published `page` (which could be a simple Thank You page), use a `page` which appears in the nav menu.)

> 2\. If we can detect those items, would it be possible to make them clickable so that selecting them updates the preview window on the right? (example: https://d.pr/i/YqDv9G)

Yes, we can have clicking on those links cause navigations in the iframe.

**Comment by jwold** [comment]
That's great news, thanks!

**Comment by jwold** [comment]
The design for this is ready for engineering review and followup. Feel free to reach out with any questions!

Updated onboarding will include a few changes. 

## 1. New welcome screen - Updated bullet point. Note that the `Learn More` will turn blue on hover. 

![Welcome](https://user-images.githubusercontent.com/3411173/130864726-1e1b9cce-2757-405e-9f05-94b1f8ce99e6.png)

## 2. Technical background step - Unchanged

## 3. Template Modes step - Unchanged

## 4. Review step - Remove this step. Redundant now.

## 5.1. Done step - Standard mode

![Standard](https://user-images.githubusercontent.com/3411173/130865223-603d36db-1b6f-4e24-a041-adf00506a7e1.png)

Dev notes:
* The links provided are determined automatically. Should show the first 5-6 links, don't think we'll want to go past that.
* When the user clicks on a link, the site on the right is navigated to the corresponding landing page. 
* If no menu, we'll want to have a graceful fallback to find other urls. I think something was mentioned in a call about ways we can find URLs. 

## 5.2. Done step - Transitional mode

![Transitional](https://user-images.githubusercontent.com/3411173/130865358-244ddc88-a29f-4b92-a426-2f2e9b0de06b.png)

Dev notes: 
* The links are updated automatically to load the AMP/non-AMP version depending on the status of the toggle button (or checkboxes)
* Entire “links” section is clickable; not just radio 

## 5.3. Done step - Reader mode

![Reader](https://user-images.githubusercontent.com/3411173/130865425-d2d02ed9-e5bd-4da7-ab75-f7da91af668e.png)

Dev note:
* Are there other success/error states we should show other than the one visible? 

## 6. Settings page

![Settings](https://user-images.githubusercontent.com/3411173/130865601-5d3d8286-33a4-4a7d-8b54-1d05d66ffb1e.png)


Figma link: https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=2374%3A9285

cc @westonruter, @delawski, not sure who will pick this one up. Happy to answer any questions!

**Comment by delawski** [comment]
@jwold Thank you for providing the designs. I've already [started working](https://github.com/ampproject/amp-wp/compare/feature/6071-onboarding-site-review?expand=1) on this issue and have majority of work already done.

**Comment by delawski** [comment]
@jwold I have a question about the buttons on the Settings page:

1. Does the "Browse Site" button redirect a user to the site front-end in the AMP mode?
2. Does the "Dismiss" button remove the entire panel indefinitely or should it re-appear in some circumstances?

**Comment by jwold** [comment]
1. Does the "Browse Site" button redirect a user to the site front-end in the AMP mode?

That's perfect!

2. Does the "Dismiss" button remove the entire panel indefinitely or should it re-appear in some circumstances?

Great question. I think it could re-appear when users change template modes. What do you think?

**Comment by delawski** [comment]
> Great question. I think it could re-appear when users change template modes. What do you think?

Yes, this would be one of the scenarios. I think that changing a theme or adding new plugins could be another cases when it could re-appear. This may be a bit more complex, though.

One more thing I just noticed is about the second bullet:

> Try a different template mode in settings

Since we're already on the Settings page should we change the copy so that it better fits into the context?

**Comment by jwold** [comment]
> Yes, this would be one of the scenarios. I think that changing a theme or adding new plugins could be another cases when it could re-appear. This may be a bit more complex, though.

maybe for initial release we do it on template mode change. Site scan should trigger on new plugin activation, so I see that as a separate issue. 

> Try a different template mode in settings

Good catch! How about if we change this to: “Try a different template mode”, and hyper link to that section.

**Comment by westonruter** [comment]
As I just commented on https://github.com/ampproject/amp-wp/issues/4719#issuecomment-907381453:

> Something else that just came to mind in the context of reviewing the site after activation (#6071): we should make sure that the final screen again lists out the theme (if Standard/Transitional mode selected) and plugins that had validation errors, with a call to action to ensure that the related functionality still works as expected (e.g. a contact form from a forms plugin).

**Comment by westonruter** [comment]
> 5.1. Done step
> Entire “links” section is clickable; not just radio

The links should be actual links I think and not radio options. To me when I see a radio button I think that I'm going to be changing some setting.

> * If no menu, we'll want to have a graceful fallback to find other urls. I think something was mentioned in a call about ways we can find URLs.

The links will be those which are obtained from Site Scanning, which involves obtaining URLs for the various template types. So we'd not be using the menu to obtain the URLs. The paragraph before can mention, “See below for some example pages you check in the preview window.”

> The links are updated automatically to load the AMP/non-AMP version depending on the status of the toggle button (or checkboxes)

I like that toggle. Good idea.

> * Does the "Browse Site" button redirect a user to the site front-end in the AMP mode?

Yes, I think that makes sense. It would be similar to the “Browse AMP” button at the end of the onboarding wizard.

> 6. Settings page

Having the “Review” settings drawer appear when changing the template mode makes sense to me. (Related: #4843.) However, it also makes sense to put together with new Site Scanning section to have appear persistently. There's this new Site Scan section proposed in https://github.com/ampproject/amp-wp/issues/4719#issuecomment-905898102. I think if we detect a new plugin has been activated or the theme has switched (and this can be captured by storing the return value of `AMP_Validated_URL_Post_Type::get_validated_environment()` an an option and then checking if the current return value differs), or the template mode was changed then this Site Scan section should have a notice to say that it should be re-checked. At the end of Site Scan then it can have the “Review” state as depicted above, which would then be similar to the Done step of the Onboarding Wizard.

**Comment by delawski** [comment]
> The links should be actual links I think and not radio options. To me when I see a radio button I think that I'm going to be changing some setting.

I'd vote for radio buttons in this case. I think a preview state is actually a local (page-level) setting.

A set of links would mean a page redirect (a set of buttons would be more appropriate, then). However, a set of radio buttons seem to be the best suited approach. All those radio buttons relate to the same output element – a preview, and there's no way to toggle multiple page previews at once.

**Comment by westonruter** [comment]
I don't think I understand. Fundamentally the list of links is a nav menu. Clicking a link in the nav menu causes a navigation in the preview iframe. I don't see why radio buttons make more sense than links. The links can even be regular links so that they can be opened in new windows/tabs in addition to regular link clicks causing the navigation in the preview iframe.

**Comment by delawski** [comment]
I guess my take on it comes from the fact that I think of the Onboarding Wizard (and so the site preview feature) as being more an app and less a web page. In this case, the preview iframe is an output element controlled by the nav menu (radio buttons/filters) and the AMP toggle. (Speaking of the AMP toggle above the preview, a user might think that it changes some setting, too.) 

I'm open to go with either approach but radio buttons seem to make more sense to me (at least from the UI perspective).

**Comment by dhaval-parekh** [comment]
**QA passed for site review.** ✅ 

After setting up the AMP plugin from the onboarding wizard. I was able to review the site at the end of the wizard and able to navigate different pages.
And on the AMP setting page. after changing the template it also shows the displaying notice to the review site.

---
During the testing found two issues (which I don't think it is related to site review but related to the onboarding wizard.)
#6740, #6741
