### ISSUE TITLE
WordPress AMP Core Web Vitals Issues

### ISSUE THREAD

**Issue by fthead9** [Automattic/amp-wp#6073]
## Bug Description

Running PageSpeed Insights reports on our AMP themes that incorporate the official AMP plugin continues to generate low Core Web Vitals scores. Loading the AMP javascript library gets flagged as a blocker and PSI continues to recommend using AMP Optimizer despite it being incorporated in the plugin. This is causing potential customers to question the value of our native AMP themes. 

## Expected Behaviour

We'd expect to receive passing Core Web Vitals scores in PSI and https://amp.dev/page-experience/ 
GTMetrix gives our theme perfect scores 
![CBDSerenity Core Web Vitals 041521](https://user-images.githubusercontent.com/32467169/114921270-3b1dab00-9ddf-11eb-8641-31d302ff62a1.jpg)

but potential customers put more stock in the PSI test results. 

Core Web Vitals Issues Overall:
I know there has been previous discussion of CWV issues with AMP in general https://github.com/ampproject/amphtml/issues/28638 as well as the library specifically https://github.com/ampproject/amphtml/issues/25873#issuecomment-561832880

Given Core Web Vitals is going live next month are there any impending releases for creating an AMP validation mechanism for the self-hosted solutions discussed https://github.com/ampproject/amphtml/issues/25873#issuecomment-561832880
and https://docs.google.com/document/d/1Wv7jlnTlLYgo9b841W88yblcHJjLI7GhdBKF60IWaWc/edit#heading=h.xzptrog8pyxf

It's been mentioned that the AMP image tag is going to be deprecated, which might help CWV scores. Is that going to happen before May? 

Right now there is a big opportunity in the WordPress environment if we can prove AMP helps with CWV scores. Most popular WordPress themes perform poorly without significant optimizations, AMP should be the best solution but it's not being reflected in PSI, etc. CWV scores. If there is any hope for major WordPress AMP adoption now is the time. 

## Additional context

 - WordPress version: 5.7.1
 - Plugin version: 2.0.11
 - AMP plugin template mode: Standard

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Please re-check with the [2.1-beta2 prerelease](https://github.com/ampproject/amp-wp/releases/tag/2.1.0-beta2). It includes many optimizations, including prerendering of hero images which will reduce LCP. This release is due out this month.

Otherwise, you should review the action items in the [Page Experience Guide](https://amp.dev/page-experience/) to make sure you're following the appropriate recommendations. The 2.1-beta2 release will address some of these, including marking up of the hero images. But we can't implement all of the recommendations automatically since they can break the site.

**Comment by fthead9** [comment]
@westonruter Great to see 2.1 update. We'll test it ASAP and update this thread with results.
