### ISSUE TITLE
Fatal PHP error caused by is_amp_endpoint()

### ISSUE THREAD

**Issue by 16patsle** [Automattic/amp-wp#608]
Recently, probably after upgrading to WP 4.7, a fatal error caused by the is_amp_endpoint function appeared in my error log. This is error from the log (wordpress directory substituted for `wordpress`):

```
PHP Fatal error: Uncaught Error: Call to a member function get()
on null in /wordpress/wp-includes/query.php:28

Stack trace:

#0 /wordpress/wp-content/plugins/amp/includes/amp-helper-functions.php(42):
   get_query_var('AMP_QUERY_VAR', false)

#1 /wordpress/wp-content/plugins/w3-total-cache/Extension_Amp_Plugin.php(23):
   is_amp_endpoint()
```
I have attempted to find the cause of this error, but with no success. The is_amp_endpoint function is in this case called by W3 Total Cache, but i found no problems with the usage on the mentioned line. This is an excerpt from the file that runs is_amp_endpoint():

```php
private function is_amp_endpoint() {
		if ( is_null( $is_amp_endpoint ) && function_exists('is_amp_endpoint') ) {
			$is_amp_endpoint = is_amp_endpoint(); // This is line 23
		}

		return $is_amp_endpoint;
	}
```

Any suggestions to what the problem might be or if this is a bug in the AMP plugin? The only thing I possibly can come up with is that W3TC is messing things up by making a private function with the same name instead of using the function directly? It seems like it is only problematic in this case, because I am certain the is_amp_endpoint is being used elsewhere on the site.

**Comment by clotairer** [comment]
I've the same problem to load facet in ajax with the plugin Facet WP.


`plugins/accelerated-mobile-pages/accelerated-moblie-pages.php`

I fix the bug by checking if $wp_query is null at the begining of the method. 

```
        // AMP endpoint Verifier
        function ampforwp_is_amp_endpoint() {
global $wp_query;
if ($wp_query == null) {
return false; 
}
                return false !== get_query_var( 'amp', false );
        }
```

**Comment by 16patsle** [comment]
I'll try something like that and see if it helps. Thanks for the suggestion.

**Comment by AaronHolbrook** [comment]
I just ran into this as well when trying to publish a scheduled post during a wp-cron load on the `plugins_loaded` action.

Specifically:

![](http://d.pr/i/iwVbg6/2q7eIGeW+)
![](http://d.pr/i/MaiMSq/532fAUMV+)

**Comment by amedina** [comment]
This errors are not related to the plugin in itself Notice that in the first case the problem is with the 'w3-total-cache' plugin; in the second case the problem is with a different AMP plugin (accelerated-mobile-pages); and in the third case, the file calling the is_amp_endpoint() is not part of the AMP plugin.

**Comment by AaronHolbrook** [comment]
`is_amp_endpoint()` is definitely a part of the AMP plugin: https://github.com/Automattic/amp-wp/blob/master/includes/amp-helper-functions.php#L42

The constant should be checked before utilized in that function. Please re-open this issue, it is not resolved.

**Comment by 16patsle** [comment]
@amedina One last question then:

As mentioned in https://github.com/optimalisatie/above-the-fold-optimization/issues/32 , is there any reason the is_amp_endpoint() should fail because WP_Query/WPDB is unavailable? Like using it too early (all the plugins I know of at least check if the function exists before using it)?

**Comment by ProductivePhysician** [comment]
@amedina 
There still seems to be a problem here...
https://github.com/o10n-x/wordpress-html-optimization/issues/2

Can you advise further?

**Comment by westonruter** [comment]
@ProductivePhysician You should always check if `function_exists( 'is_amp_endpoint' )` before calling it. That is what you should do here.
