### ISSUE TITLE
Add support for embedding PDFs

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6083]
## Feature description

Gutenberg 10.5 adds support for embedding PDFs in the File block: https://github.com/WordPress/gutenberg/pull/30857.

It does so by adding an [`object`](https://github.com/WordPress/gutenberg/blob/d504910ad11339dff0d3186db32bc39f3c665501/packages/block-library/src/file/save.js#L32-L41) element to the page:

```jsx
<object
	className="wp-block-file__embed"
	data={ href }
	type="application/pdf"
	style={ {
		width: '100%',
		height: `${ previewHeight }px`,
	} }
	aria-label={ pdfEmbedLabel }
/>
```

We need to add an `AMP_Object_Sanitizer` which automatically converts `object[type=application/pdf]` into [`amp-google-document-embed`](https://amp.dev/documentation/components/amp-google-document-embed/?format=websites).

We also need to dequeue the new `wp-block-library-file` script which is getting enqueued in the `render_callback`, so dequeuing will need to be done at the `wp_print_footer_scripts` action. Or otherwise, we can just unset the `render_callback` entirely so that the `$content` is just passed through as-is.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Another implementation option, aside from a new sanitizer, would be to extend `AMP_Core_Block_Handler`. It could add a new entry to `\AMP_Core_Block_Handler::$block_ampify_methods` to override the output, and then also to eliminate the `render_callback` on that block to prevent the script from being enqueued.

On the other hand, adding a sanitizer would allow for any `object[type=application/pdf]` to be made AMP-compatible, not just those appearing in a File block.

**Comment by pierlon** [comment]
I've ran into a small issue with this. The `amp-google-document-embed` component is using the Google Docs Viewer to display the PDF. The problem is that this won't work if the PDF URL is not publicly accessible.

**Comment by westonruter** [comment]
I think that is fine, if the problem is just that it's not working for you because the file is only on your local machine.
