### ISSUE TITLE
Include wp_body_open() in the legacy reader theme. 

### ISSUE THREAD

**Issue by jamesozzie** [Automattic/amp-wp#6084]
## Feature description

Based on [one users experience](https://wordpress.org/support/topic/how-i-can-confirm-google-adsense-is-activated-on-amp-pages/) in the Site Kit support forums it looks like AdSense code is not placed on users sites when using the legacy reader theme. This is as a result of no [wp_body_open()](https://developer.wordpress.org/reference/functions/wp_body_open/) tag contained within the [html-start.php template](https://github.com/ampproject/amp-wp/blob/develop/templates/html-start.php). 

[Video showing behaviour
](https://recordit.co/iLwLpYnMRk)

To reproduce this issue:
1. Install and setup Site Kit  
2. Allow the plugin to insert AdSense code when connecting the AdSense module
3. Activate AMP using the legacy reader theme. There will be no AdSense code placed. 
4. Switch themes while in reader mode, ad code will be placed

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by jamesozzie** [comment]
@milindmore22 Do you want to take a look at this one?

**Comment by milindmore22** [comment]
Hello @jamesozzie 
The `amp_post_template_body_open` is equivalent to `wp_body_open`, A similar [issue](https://github.com/google/site-kit-wp/issues/1495) was reported on the site kit and was fixed, if themes don't use `wp_body_open` it should inject adsense code, or use `amp_post_template_body_open` to trigger similar action.

**Comment by jamesozzie** [comment]
Thanks @milindmore22. I'll discuss this with the Site Kit team and if needed open a GitHub issue on the Site Kit repository.

**Comment by westonruter** [comment]
Yes, the `amp_post_template_body_open` action was added in #1143 as a legacy AMP template equivalent to `wp_body_open`. So Site Kit should be using that action in legacy AMP Reader mode.
