### ISSUE TITLE
Mark optimizer CLI commands as experimental

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#6089]
The current optimizer CLI commands do not always produce the expected result, as WordPress is loaded in a generic fashion before the commands are even registered, due to them being part of a plugin and only being registered when the plugin is loaded. This cannot easily be changed without major hacks (see https://github.com/ampproject/amp-wp/pull/6080).

For now, we decided to keep the commands in the plugin for release v2.1, but mark them as experimental. This lets people (ab)use them to get testing feedback and bug reports, but it also makes it clear that some of the output might not be as expected, and is not consistent with what you get from an actual web server request.

- [ ] Create a note in the README/docs about the experimental nature of the following commands and what to expect for them: `amp optimizer optimize`, `amp optimizer transformer list`, `amp optimizer transformer config`.
- [x] Mark these commands as experimental in their docblock and link to the above note. => https://github.com/ampproject/amp-wp/pull/6116
- [ ] Do a discovery on how the correct frontend request could be simulated after the fact to get the expected output for the above commands from within the CLI context.

**Comment by schlessera** [comment]
The release notes from https://github.com/ampproject/amp-wp/releases/tag/2.1.0-beta2 should also be adapted once they are assembled into the release notes for the actual v2.1 release.

**Comment by westonruter** [comment]
> The release notes from https://github.com/ampproject/amp-wp/releases/tag/2.1.0-beta2 should also be adapted once they are assembled into the release notes for the actual v2.1 release.

I've updated them to include _(Experimental)_.

**Comment by schlessera** [comment]
It looks like the CLI commands are currently not being mentioned in the `README.md` file, so I assume that it's enough to add a mention to the release notes only, @westonruter ?

**Comment by westonruter** [comment]
Yes, that's correct. The only place where they are mentioned is manually in docs on amp-wp.org: https://amp-wp.org/documentation/getting-started/wp-cli-commands/

But they aren't yet listed there naturally, at least until #6072.

**Comment by schlessera** [comment]
I think we can deal with the actual documentation in v2.2 once we've actually fixed the commands' behavior. Right now, it'd be difficult to document their actual usage, because they don't do what they are supposed to do.

**Comment by westonruter** [comment]
I'm moving this issue to the 2.2 milestone because while we've marked the commands as experimental in #6116, we won't be addressing the other two checklist items for 2.1.
