### ISSUE TITLE
Some images doesn't get 100% width

### ISSUE THREAD

**Issue by andregumieri** [Automattic/amp-wp#609]
Hey guys! We got some images on our AMP that is not using 100% width. I understood that the reason why is that the padding-top on `<i-amphtml-sizer />` tag is set to 33.3333% instead of 100%, like other images that are working properly. But I'm not being able to understand why only some images are with this 33.3333% padding.

URL: https://www.g2have.com/cute-gifts-for-totoro-kawaii-fans/amp/
- 33%: http://d.pr/i/10dIA
- 100%: http://d.pr/i/YznB

URL: https://www.g2have.com/awesome-mugs/amp/
- 33%: http://d.pr/i/1334F
- 100%: http://d.pr/i/RS2v

Thanks in advance

**Comment by amedina** [comment]
HI @andregumieri, are you still observing this issue with your pages?

**Comment by amedina** [comment]
Closing this for now; please re-open if this is still an issue.
