### ISSUE TITLE
img sanitizer not working

### ISSUE THREAD

**Issue by eboye** [Automattic/amp-wp#611]
I was trying to figure out why img sanitizer works on one of my WP sites and not on another.

It turns out that for some reason the_content on the one that doesn't work has `&lt;img .... /&gt;` instead of `<img ... />` in it so the DOM parser doesn't get the img tag.

Is there something that I can do to prevent this? Or is there something that I can do to extend the sanitizer to match those as well. I tried to hook html_entity_decode in functions.php on the_content but then the_content turns out empty. Any ideas how can I make this work? My amp pages are getting validation errors all over the place because of this. Here's a console screenshot:

![image](https://cloud.githubusercontent.com/assets/624357/21988610/2c42a92a-dc08-11e6-863a-70926d4bbbee.png)

**Comment by amedina** [comment]
Can you provide a link to reproduce the validation errors. Closing this for now; please reopen if you are still experiencing the issue.
