### ISSUE TITLE
Validation count assets not enqueued when on any Dev Tools screen and Reader mode is enabled

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#6120]
## Bug Description

If a user hasn't explicitly enabled AMP Developer Tools in their profile and the site is in Reader template mode, when they go to any of the Dev Tools screens none of the validation count assets are enqueued, preventing the validation counts from being retrieved and updated in the AMP menu:

![image](https://user-images.githubusercontent.com/16200219/116165707-f7367a00-a6eb-11eb-9bbf-cc669d7205ef.png)

## Expected Behaviour

AMP validation counts should still be retrieved and updated in the AMP menu when Reader mode is enabled and the user has never explicitly enabled AMP Dev Tools for their profile.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
**QA Passed** per https://github.com/ampproject/amp-wp/pull/6122#issuecomment-827305935
