### ISSUE TITLE
Resource hint for Google Font stylesheets lack dns-prefetch

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6156]
## Bug Description

When doing a Google Font stylesheet is used on a page, Pixi is reporting the lack of a resource hint:

![image](https://user-images.githubusercontent.com/134745/116737494-2546e300-a9a6-11eb-9983-e6a403e9793f.png)

This is in spite of us actually adding one:

https://github.com/ampproject/amp-wp/blob/b28697beac7eaf54087eac11c2294e3ac1791e41/includes/sanitizers/class-amp-style-sanitizer.php#L1378-L1402

The issue is that we're adding `preconnect` only, when we should add `dns-prefetch` as well. The reason is that older browsers don't support `preconnect` but they do support `dns-prefetch`.

## Expected Behaviour

Stylesheets for Google Fonts should get `dns-prefetch` resource hint in addition to the existing `preconnect` one.

Also, when a Google Font stylesheet is extracted from an `@import`, it should likewise get the same resource hints. The logic is missing here:

https://github.com/ampproject/amp-wp/blob/b28697beac7eaf54087eac11c2294e3ac1791e41/includes/sanitizers/class-amp-style-sanitizer.php#L2877-L2888

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
> The reason is that older browsers don't support `preconnect` but they do support dns-prefetch.

Do note that Firefox has not supported `preconnect` for quite some time now, and as for `dns-prefetch` it only supports it on HTTP origins.

Support table for [preconnect](https://caniuse.com/link-rel-preconnect):
![image](https://user-images.githubusercontent.com/16200219/116760641-f6ac2500-aa04-11eb-9810-7c750e57eec8.png)

Support table for [dns-prefetch](https://caniuse.com/link-rel-dns-prefetch):

![image](https://user-images.githubusercontent.com/16200219/116760734-47238280-aa05-11eb-9d95-33b04f4129a5.png)

**Comment by westonruter** [comment]
Only HTTP origins?!

**Comment by pierlon** [comment]
> Only HTTP origins?!

It seems it was due to Chromium not supporting HTTPS origins at the time when it was introduced in Firefox ([Bugzilla comment](https://bugzilla.mozilla.org/show_bug.cgi?id=453403#c23)):

> ...prefetching is not done by default from an https based document, as per chromium. can be overriden with new pref

It seems this [Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1596935) should be fixing that though.

**Comment by pierlon** [comment]
Also, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch#best_practices) making use of both `dns-prefetch` and `preconnect` is considered a best practice:

> While `dns-prefetch` only performs a DNS lookup, `preconnect` establishes a connection to a server. This process includes DNS resolution, as well as establishing the TCP connection, and performing the TLS handshake—if a site is served over HTTPS.

**Comment by westonruter** [comment]
Yes, I've noted the same at https://core.trac.wordpress.org/ticket/53122

**Comment by schlessera** [comment]
Note that I've included a `ResourceHintManager` in one of the branches on the library, and it adds `dns-prefetch` as fallback by default. I'll see if I can turn that branch into a ready-to-merge PR on Monday...

**Comment by schlessera** [comment]
@pierlon I've created a PR that adds the `GoogleFontsPreconnect` transformer to the toolbox library:
https://github.com/ampproject/amp-toolbox-php/pull/179

Note that this now includes an abstraction in the `Dom\Document` that allows one to easily add resource hints:
![image](https://user-images.githubusercontent.com/83631/116880403-e02ae700-ac19-11eb-9d55-596cc88bf41f.png)

**Comment by westonruter** [comment]
Closing in favor of https://github.com/ampproject/amp-toolbox-php/pull/179.
