### ISSUE TITLE
Settings page empty after 2.1

### ISSUE THREAD

**Issue by coolrecep** [Automattic/amp-wp#6183]
## Bug Description

Settings page is empty. I believe this also broke Yoast. Attached it as well.

## Expected Behaviour

Able to see all the options.

## Steps to reproduce

WP DashBoard > AMP > Settings

## Screenshots

![image](https://user-images.githubusercontent.com/13221472/117446562-ec2de600-af44-11eb-923c-2ad8fdac900a.png)

![image](https://user-images.githubusercontent.com/13221472/117446948-83933900-af45-11eb-9d57-d5209e759b4d.png)

## Additional context

 - WordPress version: 5.7.1
 - Plugin version: 2.1
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version: 8.0.3
 - OS: Windows 10
 - Browser:  Chrome 90
 - Device: Desktop
 

Won't share site health as it contains too much info. Can share privately if requested.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by coolrecep** [comment]
Went back to 2.0.11 to solve the issue.

**Comment by milindmore22** [comment]
@coolrecep 
Are you able to check if there was an error in the Browser console? if yes, can you please copy the error here for our reference?

**Comment by westonruter** [comment]
> Won't share site health as it contains too much info. Can share privately if requested.

You can share your SIte Health info privately via https://forms.gle/6rbRycvL4GiZtMDo6

But yes, if you can share whether there was an error in the browser console that will be ideal.

**Comment by coolrecep** [comment]
Removed the /wp-content/amp/ folder, upgraded to 2.1.1 and solved. Thanks.
