### ISSUE TITLE
WP 4.9 + Gutenberg: `Uncaught TypeError: Object(...) is not a function` on settings page

### ISSUE THREAD

**Issue by aaemnnosttv** [Automattic/amp-wp#6194]
## Bug Description

As of AMP 2.1, the AMP settings page now loads a blank screen with the following error in the console with WP 4.9:

```
amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9 Uncaught TypeError: Object(...) is not a function
    at amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9
    at Object.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9)
    at n (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1)
    at Module.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29)
    at Module.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29)
    at n (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1)
    at Object.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29)
    at n (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1)
    at amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
    at amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9
n @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29
n @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29
n @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
```

## Expected Behaviour

The settings page should load as usual 🙏 

## Steps to reproduce

1. Use latest 4.9 version of WordPress
2. Install Gutenberg 4.9.0 (not possible to install newer version)
2. Install and activate the latest version of AMP (currently 2.1.1)
3. Navigate to the AMP settings page
4. See screen as shown above

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/117838789-4c919000-b283-11eb-890a-faaf78305f78.png)

## Additional context

 - WordPress version: 4.9.17
 - Plugin version: 2.1.1
 - Gutenberg plugin version (if applicable): 4.9.0
 - PHP version: 7.4.19

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

Test cases to check, if support is absent:

* Block editor should show upgrade notice.
* Classic editor (without Gutemberg in 4.9 and w/ Classic Editor plugin in 5.0+) should show notice with AMP enabled status.
* Validation Counts should be omitted from admin menu.
* AMP Settings screen should work as expected, but with an upgrade notice shown.
* Onboarding Wizard should work normally.
* Paired browsing should not be available.
* AMP Customizer _does_ still work.

Environments to check:

* WordPress 4.9 with Gutenberg 4.9.0
* WordPress 4.9 without Gutenberg
* WordPress 5.5.5 without Gutenberg nor Classic Editor
* WordPress 5.5.5 with Gutenberg 8.9.0
* WordPress 5.5.5 with Classic Editor
* WordPress 5.6.4 without Gutenberg nor Classic Editor
* WordPress 5.6.4 with Gutenberg 10.2.0
* WordPress 5.6.4 with Classic Editor
* WordPress 5.7 without Gutenberg nor Classic Editor
* WordPress 5.7 with latest Gutenberg
* WordPress 5.7 with Classic Editor

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
**QA Passed**

## WP 5.7.2

- ✅ No upgrade notice shown in block editor when neither Gutenberg nor Classic Editor plugins are active
- ✅ No upgrade notice shown in block editor when latest Gutenberg plugin (v10.6.1) active
- ✅ No notice about AMP Enabled status in editor when latest Classic Editor plugin (v1.6) active
- ✅ Validation counts are fetched and updated successfully via AJAX
- ✅ AMP Settings screen works normally
- ✅ AMP Onboarding Wizard screen works normally
- ✅ Paired Browsing works normally
- ✅ AMP Customizer works normally

## WP 4.9.17

- ✅ Upgrade notice shown in block editor when Gutenberg v4.9.0 is active
- ✅ Upgrade notice is shown below AMP Enabled status in classic editor
- ✅ Validation counts are omitted from admin menu
- ✅ AMP Settings screen works normally, and shows upgrade notice
- ✅ AMP Onboarding Wizard screen works normally
- ✅ Paired Browsing is not available
- ✅ AMP Customizer works normally
