### ISSUE TITLE
amp-video/amp-audio supports limited children

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#62]
amp-video only supports `<source>` `<div fallback>` and `<div placeholder>` as children.

amp-audio only supports  `<source>` and `<div fallback>`.

We should reformat the child nodes to match this.

**Comment by mjangda** [comment]
Aside: DOMDocument is a bit annoying since it does not handle non-closing tags like `source` very well. (i.e. `<video><source a><source b></video>` becomes `<video><source a><source b></source></source></video>`)

**Comment by kienstra** [comment]
**No Functional Testing Needed**

Feel free to comment if you have another opinion, but I won't move this into QA. This could possibly use more technical testing, but I don't see a need for functional testing.
