### ISSUE TITLE
AMP Not loading for Category pages

### ISSUE THREAD

**Issue by ravikumarinv** [Automattic/amp-wp#620]
I have installed the Automattic AMP plugin to our WP blog. It is working fine the posts, but unable to load the category pages.

Can anyone help us to overcome this issue?

Regards,
Ravi

**Comment by caraya** [comment]
pages are not currently supported. They are being worked on

**Comment by caraya** [comment]
from the [plugin page](https://wordpress.org/plugins/amp/)

Pages and archives are not currently supported. Pages are being worked on

**Comment by iDoka** [comment]
Please supports pages. That's really necessary for main plugin functionality

**Comment by amedina** [comment]
Hi @iDoka, we are working on support for pages. Stay tuned!
