### ISSUE TITLE
Pictures looks so blury

### ISSUE THREAD

**Issue by edwarddekker** [Automattic/amp-wp#621]
Hi,

When i viewing the pictures of the home and owner of the post with the AMP Pages. Than will it looks so verry blury. It should be more clear. How do i make that so.

@EdwardDekker

**Comment by mjangda** [comment]
Can you please provide a screenshot a URL to where this is occurring?

**Comment by edwarddekker** [comment]
This can be found [here](https://www.edwarddekker.nl/1080/een-heel-gelukkig-2017.html?amp=on) and everywhere into my website where I have installed AMP. On the profile pictures do I see that the resolution are very low.

It should be more clear as the profile pictures of WordPress itself.

**Comment by amedina** [comment]
Closing this for now; please feel free to re-open if you are still  experiencing the issue.
