### ISSUE TITLE
WP <= 5.5.5: post edit and create pages throw errors with the latest version of AMP plugin (>= 2.1.0)

### ISSUE THREAD

**Issue by nbcsteveb** [Automattic/amp-wp#6236]
## Bug Description

On WP versions <= 5.5.5 w/ latest AMP Plugin (2.1.*) post edit and create pages throw errors with the latest version of AMP plugin.

## Expected Behaviour

The post create or edit page screen should load without throwing any errors.

## Steps to reproduce

Given: WordPress version below 5.6 (<= 5.5.5)
And: AMP Plugin v2.1.0 or v2.1.1 is installed.
When: User tries to create or edit a post.
Then: There's an error thrown.

TypeError: Object(...) is not a function
    at /wp-content/plugins/amp/assets/js/amp-block-validation.js?ver=563a00395a4f44a548658de7c61d656b:15:10628
    at re (/wp-content/plugins/amp/assets/js/amp-block-validation.js?ver=563a00395a4f44a548658de7c61d656b:15:10773)
    at je (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:78:476)
    at ph (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:215:173)
    at lh (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:126:409)
    at O (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:121:71)
    at ze (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118:14)
    at /wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:53:49
    at unstable_runWithPriority (/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26:340)
    at Ma (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:280)

## Screenshots

![image](https://user-images.githubusercontent.com/9660445/118301749-6d3f2d00-b4b1-11eb-94f3-74e1e90747e7.png)

## Additional context

AMP made a change in 2.1.0 - 2.1.1 of their plugin that breaks on WP < 5.6.

https://github.com/ampproject/amp-wp/commit/af6d46552d25c92a0cc414997deb69a459b1ac99

The reason it breaks is because the useDebounce function exposed in the @wordpress/compose package wasn't introduced into WP core until 5.6.

https://github.com/WordPress/gutenberg/pull/25948

https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/

If you search for the word debounce in this file you will get zero (0) hits.

https://github.com/WordPress/WordPress/blob/5.5.5/wp-includes/js/dist/compose.js

If you search here, you will see the debounce functionality included:

https://github.com/WordPress/WordPress/blob/5.6/wp-includes/js/dist/compose.js#L2606

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
(@westonruter provided a more thorough comment below, go [check](https://github.com/ampproject/amp-wp/issues/6236#issuecomment-841391021) his out!)

@nbcsteveb thanks for reporting the bug. We've already fixed this (see https://github.com/ampproject/amp-wp/pull/6193) and it should be apart of our next patch release. Please try one of our up-to-the-minute builds for [`v2.1.x`](https://github.com/ampproject/amp-wp/wiki/Development-Builds) to confirm the bug is fixed.

**Comment by westonruter** [comment]
_Update:_ Ditto ☝️ 

@nbcsteveb Thanks for reporting. This is something we've just addressed in #6193 by bumping the minimum version required to use the block validation functionality in the editor. This will be part of v2.1.2 which will be released either later today or early next week. In the meantime, you have three options:

1. Turn off AMP Developer Tools in your user profile.
2. Update to AMP v2.1.2-alpha via the 2.1.x Production build link on our [Development Builds](https://github.com/ampproject/amp-wp/wiki/Development-Builds) wiki page.
3. Upgrade WordPress core
4. Activate Gutenberg

**Comment by westonruter** [comment]
Thank you for the thorough bug report nonetheless!

**Comment by westonruter** [comment]
**QA Passed**

Downgrading to WordPress 5.5.5, now when accessing the post editor there is an upgrade notice displayed instead of erroring out when loading the incompatible JS:

![image](https://user-images.githubusercontent.com/134745/118587033-ae08a180-b750-11eb-9faf-cedc7db66924.png)

**Comment by westonruter** [comment]
<a href="https://github.com/ampproject/amp-wp/releases/tag/2.1.2">v2.1.2</a> is now published on WordPress.org
