### ISSUE TITLE
change type of page

### ISSUE THREAD

**Issue by Digital-Trends** [Automattic/amp-wp#626]
hi ,

my amp page type is 'WebPage' ,
i add this code to change type of page to 'BlogPosting'
but the page type still WebPage ??

my code is 
-------------
function xyz_amp_modify_json_metadata( $metadata, $post ) {
    /*change type of page*/
	$metadata['@type'] = 'BlogPosting';

    return $metadata;
}

**Comment by Digital-Trends** [comment]
????

**Comment by mjangda** [comment]
See https://github.com/Automattic/amp-wp#schemaorg-json-metadata

**Comment by Digital-Trends** [comment]
hello
I already used the code above and the page type still WebPage (No change) ..
please check the page  https://goo.gl/ZpIyX7
