### ISSUE TITLE
Add GitHub action to auto-merge Dependabot pull requests

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6298]
## Feature description

After switching from dependabot-preview to dependabot (#6144), the auto-merging of approved PRs is no longer happening since it is not a feature of the native Dependabot. This functionality should be restored via a GitHub Action as it saves a lot of time. We should consider auto-merging dependency updates even without approval for `@wordpress` dependencies and perhaps other others which are well-trusted. Whatever we can do to minimize the manual effort of keeping the dependencies updated. 

For `@wordpress` dependencies, another thought would be to open a pull request that updates them all in one without opening a pull request for each one individually. Since these dependencies all get updated when a new version of Gutenberg is released, they should all be updated in unison anyway.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
> For `@wordpress` dependencies, another thought would be to open a pull request that updates them all in one without opening a pull request for each one individually. Since these dependencies all get updated when a new version of Gutenberg is released, they should all be updated in unison anyway.

I think that would be most appropriate as a feature of Dependabot. Alternatively though, maybe we could  monitor `@wordpress` dependency PRs and push those changes to a centralized PR that would later be merged once a new Gutenberg version is out.

**Comment by pierlon** [comment]
Then those Dependabot PRs would be closed once the centralized PR is updated successfully with the related changes.

**Comment by pierlon** [comment]
Actually I may have a workaround. Will test locally and see if it's viable or not.

**Comment by pierlon** [comment]
> Actually I may have a workaround. Will test locally and see if it's viable or not.

See https://github.com/ampproject/amp-wp/pull/6302#issuecomment-846342198.
