### ISSUE TITLE
Incorrect use of _n() in /src/admin/site-health.php

### ISSUE THREAD

**Issue by tobifjellner** [Automattic/amp-wp#6305]
## Bug Description
The translation function _n() should always include the actual number in the string. ("We found 1 error/We found 3 errors" would be ok, but not "We found an error/We found some errors")
Never use _n() to just distinguish between singular and plural. Some languages translate strings into 3 or even more versions, depending on the number. And if your steering number is, say, 21, then in Russian, for instance, you'll get singular, which is totally wrong if there's no number in the string. 

Two ways to fix:
- If you want to keep the strings as-is, then just test in PHP for 1== instead and handle them as two separate strings.
- Otherwise: Include the number in the string.

I've seen several instances of this problem in /src/admin/health-check.php

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Humm. The `/src/admin/health-check.php` file is not part of the AMP plugin. Maybe you reported this to the wrong repo?

**Comment by schlessera** [comment]
I assume this refers to these strings: https://github.com/ampproject/amp-wp/blob/develop/src/Admin/SiteHealth.php#L261-L289

**Comment by westonruter** [comment]
@tobifjellner Please take a look at #6306 to see if that change is what you had in mind.

**Comment by pierlon** [comment]
**QA Passed**

The number of undefined functions are included in the "cURL multi functions" Site Health check. When there is one undefined function:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/16200219/123177877-1a637880-d454-11eb-9796-b6410709bd7f.png">

And when there are more than one:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/16200219/123177927-31a26600-d454-11eb-8f32-4384b73a14e3.png">
