### ISSUE TITLE
Wrong usage of mysql2date to generate datePublished and dateModified, bug in time offsets

### ISSUE THREAD

**Issue by DrLightman** [Automattic/amp-wp#6316]
As the WordPress's `mysql2date()` PHP doc says:

`
$date is expected to be local time in MySQL format ('Y-m-d H:i:s').
`

Please note "**local time**", not GMT time.

Whereas the AMP plugin uses the GMT values instead, resulting in wrong values in datePublished and dateModified attributes of schemaorg metadata:

```php
[
	'@type'            => is_page() ? 'WebPage' : 'BlogPosting',
	'mainEntityOfPage' => get_permalink(),
	'headline'         => get_the_title(),
	'datePublished'    => mysql2date( 'c', $queried_object->post_date_gmt, false ),
	'dateModified'     => mysql2date( 'c', $queried_object->post_modified_gmt, false ),
]
```

The resulting datePublished will be wrongly comprised of a datetime local to GMT combined with a not zero offset.
The solution is to remove the `_gmt` parts from the properties:

```php
[
	'@type'            => is_page() ? 'WebPage' : 'BlogPosting',
	'mainEntityOfPage' => get_permalink(),
	'headline'         => get_the_title(),
	'datePublished'    => mysql2date( 'c', $queried_object->post_date, false ),
	'dateModified'     => mysql2date( 'c', $queried_object->post_modified, false ),
]
```

**Comment by pierlon** [comment]
Note that this bug only occurs in WP 5.3 and above, as `mysql2date()` now makes use of the [`wp_timezone()`](https://github.com/WordPress/wordpress-develop/blob/ea4707d9275b82d5cac9d45be02ba8f17da56d65/src/wp-includes/functions.php#L127-L138) function (introduced in WP 5.3) that returns the site's timezone setting.

**Comment by westonruter** [comment]
Related: #5335

**Comment by pierlon** [comment]
(QA comment: https://github.com/ampproject/amp-wp/pull/6318#issuecomment-871801935)
