### ISSUE TITLE
Support the form element

### ISSUE THREAD

**Issue by jeherve** [Automattic/amp-wp#632]
Since AMP now supports the `form` element via `amp-form` ([ref](https://www.ampproject.org/docs/reference/components/amp-form)), we could remove `form` from [the blacklist](https://github.com/Automattic/amp-wp/blob/master/includes/sanitizers/class-amp-blacklist-sanitizer.php#L202) and add support for the most popular Contact Form plugins out there, like Contact Form 7 or Jetpack's Contact Form module?

Reported here:
https://wordpress.org/support/topic/jetpack-contact-form-not-appearing-in-amp-page/

**Comment by TwisterMc** [comment]
Are you saying that Automattic's plugin is removing all forms currently?

**Comment by lkraav** [comment]
@TwisterMc as far as we could tell from a customer's discovery project, there's no way to have lead capturing work on AMP pages with this plugin right now.

**Comment by Meh0** [comment]
+1

The plugin offers a way to **add** blacklisted tags to the existing list by exposing user-provided args, but no way to unset them in a clean override (nearly everything is private). Only the sanitize function is public but the stripping of the tags happens immediately after creating the blacklist on the fly, with no chance to hook inbetween (IMO the creation of the blacklist should be in the constructor of the class, not in the sanitize function). 

Should we do a pull request with an updated list of tags, as the AMP specs evolved to officially allow forms and Automattic doesn't seem in a hurry ?

Anyway, best way to handle this for the moment I guess is to unset the whole Blacklist Sanitizer and add your own through the 'amp_content_sanitizers' filter.

Note that it's not enough. I also had to write another custom Sanitizer for Forms, as some attributes are specific to AMP (like 'action-xhr').

```php
/*
 *	Fix Issue 632 : Support the form element
 *	@see https://github.com/Automattic/amp-wp/issues/632
 */
add_filter( 'amp_content_sanitizers', 'meho_amp_add_form_sanitizer', 10, 2 );
function meho_amp_add_form_sanitizer( $sanitizer_classes, $post ) {
	
    require_once( dirname( __FILE__ ) . '/sanitizers/class-meho-amp-blacklist-sanitizer.php' );
    require_once( dirname( __FILE__ ) . '/sanitizers/class-meho-amp-form-sanitizer.php' );
    
    unset($sanitizer_classes[ 'AMP_Blacklist_Sanitizer' ]); // remove outdated Blacklist
    $sanitizer_classes[ 'MEHO_AMP_Blacklist_Sanitizer' ] = array(); // a new Blacklist that allows Forms support
    $sanitizer_classes[ 'MEHO_AMP_Form_Sanitizer' ] = array(); // the array can be used to pass args to your sanitizer and accessed within the class via `$this->args`

    return $sanitizer_classes;
}
```

Hope that helps meanwhile. Feel free to ask further tips if needed.

**Comment by IvanPr** [comment]
The following tags should be removed from blacklisting according to https://www.ampproject.org/docs/reference/components/amp-form :
			'form',
			'label',
			'input',
			'textarea',
			'select',
			'option',

http://i.imgur.com/2g0L9Sq.png

**Comment by ktmn** [comment]
Seems like version 0.5 removed them from blacklist, so forms like Contact Form 7 are now being displayed, but not functional.

**Comment by Meh0** [comment]
Yes, you have to either
- implement your own form endpoint 
- or buy a premium plugin to extend Contact Form 7 functionnality

**Comment by ktmn** [comment]
Placeholder attributes seem to be filtered out for some reason.

**Comment by westonruter** [comment]
Support for forms has been added in #907, with some additional loose ends to be done in #911.

The blacklist sanitizer has been deprecated (and discontinued) in favor of whitelist.

**Comment by arshidkv12** [comment]
Plugin released for contact form 7 https://wordpress.org/plugins/amp-contact-form-7/

**Comment by lee-supportedbusiness** [comment]
You should be looking to include Ninja Forms with this too, as there is no support and Ninja Forms will not load at all in AMP pages.

**Comment by westonruter** [comment]
Here is an extension to the AMP plugin which adds basic support for Contact Form 7: https://gist.github.com/westonruter/3501016b0d44af45d878067b1856e023
