### ISSUE TITLE
Tell Plugin to Remove !Important from Amp-Custom CSS?

### ISSUE THREAD

**Issue by casbboy** [Automattic/amp-wp#634]
Though I used to have no issue with AMP Verification, I've been failing lately due to the fact that !Important is appearing in the amp-custom style tag.

Possible to write the code to remove all instances of !important from the CSS?

Here is some custom functions I have working with AMP plugin. Not sure if these are fouling it up:

```
add_filter( 'amp_post_template_file', 'xyz_amp_set_custom_tax_meta_template', 10, 3 );

function xyz_amp_set_custom_tax_meta_template( $file, $type, $post ) {
    if ( 'meta-taxonomy' === $type ) {
        $file = dirname( __FILE__ ) . '/t/amp-taxonomies.php';
    }
    return $file;
}

add_filter( 'amp_post_template_file', 'xyz_amp_set_custom_template', 10, 3 );

function xyz_amp_set_custom_template( $file, $type, $post ) {
    if ( 'style' === $type ) {
        $file = dirname( __FILE__ ) . '/amp/style.php';
    }
    return $file;
}

add_filter( 'amp_post_template_file', 'set_my_amp_custom_template', 10, 3 ); 
//Setting custom template for amp page 
function set_my_amp_custom_template( $file, $type, $post ) { if ( 'single' === $type ) { $file = dirname( __FILE__ ) . '/amp/single.php'; } return $file; }
```

Cheers!
Ryan

**Comment by casbboy** [comment]
Actually, turns out I had some declarations of !important in this file:

 $file = dirname( __FILE__ ) . '/amp/style.php';

And it wasn't getting sanitized it seems. No worries, I just deleted the !important manually.

Cheers!
Ryan

**Comment by mjangda** [comment]
Glad you were able to sort this out!
