### ISSUE TITLE
amp-iframe not fully supported

### ISSUE THREAD

**Issue by danielcardoso5** [Automattic/amp-wp#635]
The resizable attribute on an iframe is not set in the converted amp-iframe. 
Also, setting the overflow and amp-img elements by AMP as in the docs here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md
is not supported.

**Comment by westonruter** [comment]
The `iframe` element does not have a `resizable` attribute, in HTML5 anyway.

**Comment by danielcardoso5** [comment]
Yes it doesn't, but since it's being removed by WP it's not possible to set resizable amp-iframes.

**Comment by westonruter** [comment]
@danielcardoso5 how are you indicating that the iframe is resizable in non-AMP? There _is_ a [`resize`](https://developer.mozilla.org/en-US/docs/Web/CSS/resize) CSS property which could be used as a signal:

```html
<iframe style="resize: vertical" src="https://example.com"></iframe>
```

It's not exactly the same semantics, as it means whether it should be user-resizable not whether it should be auto-resize. Otherwise, the closest thing I can think of would be the `seamless` attribute, but that has been abandoned from the specs..

**Comment by danielcardoso5** [comment]
In non-AMP situations, I use a script that receives postMessages coming from inside the iframe and then the script sets the communicated height to the iframe since they live in the same scope and don't have CORS issues. It behaves the same way AMP does, the difference is that since AMP doesn't allow scripts the message I send from inside the iframe matches the requirements AMP needs, like this:

```
window.parent.postMessage({
  sentinel: 'amp',
  type: 'embed-size',
  height: document.body.scrollHeight
}, '*');
```

For this to work, AMP needs the resizable attribute in the iframe but this is removed by WP. Check this topic in the amp-iframe spec: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-resizing

**Comment by danielcardoso5** [comment]
Check this code I'm using:

`<iframe data-template="collage" src="https://primetag2.azureedge.net/embed/collage.html?slug=z9M7E0n1N&owner=13" width="100%" height="334" layout="responsive" sandbox="allow-scripts allow-popups allow-same-origin allow-forms allow-popups-to-escape-sandbox" resizable frameborder="0" style="background:transparent;border:none;overflow:hidden;"></iframe><span style="display:none;"><script data-cfasync="false" async type="text/javascript" src="https://primetag2.azureedge.net/static/build/embed.js"></script></span>`

Ideally, this would be converted to something like this:

`<amp-iframe src="https://primetag2.azureedge.net/embed/collage.html?slug=z9M7E0n1N&owner=13" layout="responsive" sandbox="allow-scripts allow-popups allow-same-origin allow-forms allow-popups-to-escape-sandbox" resizable frameborder="0" width="320" height="100"></amp-iframe>`

I can provide users an AMP code version, but I couldn't find a way to set an already AMP code when creating a post, either it get's removed when switching between the HTML and Visual tabs in TinyMCE or the amp-iframe script is not loaded on the AMP page.

**Comment by westonruter** [comment]
All of the original iframe attributes should be carried over to amp-iframe as long as they are valid. Please test in 1.0-alpha1.

**Comment by westonruter** [comment]
See https://github.com/Automattic/amp-wp/pull/1147
