### ISSUE TITLE
Paired AMP URLs for comment pages result in 404s when Legacy Reader paired URL structure is selected

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6355]
## Bug Description

As reported in a [support topic](https://wordpress.org/support/topic/amp-errors-for-comment-pages/), attempting to access the AMP version of a comment page results in a 404.

For example, with the theme unit test data installed and going to `/2012/01/03/template-comments/comment-page-2/` there is an AMP link for:

```html
<link rel="amphtml" href="https://wordpressdev.lndo.site/2012/01/03/template-comments/comment-page-2/amp/">
```

Attempting to access that URL, however, results in a redirect to `https://wordpressdev.lndo.site/2012/01/03/template-comments/comment-page-2/amp/comment-page-2/?amp`

This then results in a 404 or else WordPress attempting to recover by redirecting me to `https://wordpressdev.lndo.site/2021/05/29/amp-fit-text/amp/`

## Steps to reproduce

1. Enable Transitional template mode
2. Enable “Legacy Reader” paired URL structure
3. Navigate to the comments page (after having enabled comment pagination in Discussion settings)
4. Try accessing the AMP version of the second comments page

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
As a quick fix this does the trick, but I'm not yet sure the underlying cause:

```diff
--- a/src/PairedUrlStructure/LegacyReaderUrlStructure.php
+++ b/src/PairedUrlStructure/LegacyReaderUrlStructure.php
@@ -63,6 +63,8 @@ public function add_endpoint( $url ) {
 			||
 			// Attachment pages don't accept the /amp/ endpoint.
 			'attachment' === get_post_type( $post_id )
+			||
+			get_query_var( 'cpage' )
 		);
 		if ( $use_query_var ) {
 			$amp_url = $this->paired_url->add_query_var( $url, '' );
```

**Comment by westonruter** [comment]
Seems like `redirect_canonical()` is causing the problems.

**Comment by dhaval-parekh** [comment]
Yes, It's `redirect_canonical()` that causing the issue.

In a normal scenario, It tries to remove the comment page section ( [reference](https://github.com/WordPress/wordpress-develop/blob/5.7/src/wp-includes/canonical.php#L445) ) and add the same ( [reference](https://github.com/WordPress/wordpress-develop/blob/5.7/src/wp-includes/canonical.php#L503-L511) )

Since, regex that removes the comment page part will only remove that section if that is the end of the URL. But it is not the case in the AMP version of the URL, Because of the `/amp/` suffix in the URL it fails to remove but it will still add the comment page part again.

A possible solution for this to add a filter on "redirect_canonical" and remove an additional part.

```php
add_filter( 'redirect_canonical', function ( $redirect_url ) {

	global $wp_rewrite;

	if ( $wp_rewrite->comments_pagination_base ) {

		// Reference: https://regex101.com/r/544758/1/
		$regex        = "#/({$wp_rewrite->comments_pagination_base}-[0-9]+?)/amp/\\1(/+)?($|\?)#";
		$redirect_url = preg_replace( $regex, '/\\1/amp\\2\\3', $redirect_url );

	}

	return $redirect_url;
} );

```

**Comment by westonruter** [comment]
Great. Then this seems like a special case we need to add similar to what we did in https://github.com/ampproject/amp-wp/pull/5862.

**Comment by westonruter** [comment]
Naturally, the `/amp/` in the pattern and replacement will need to be variable to be whatever `amp_get_slug()` returns. So something like the following will be better:

```php
$regex        = sprintf(
	":/(%s-[0-9]+?)/(%s)/\\1(/+)?($|\?|#):", // <= Note addition of URL fragment identifier # to pattern.
	preg_quote( $wp_rewrite->comments_pagination_base, ':' ),
	preg_quote( amp_get_slug(), ':' )
);
$redirect_url = preg_replace( $regex, '/\\1/\\2/\\3\\4', $redirect_url );
```

The filter would be added alongside the `get_pagenum_link` filter:

https://github.com/ampproject/amp-wp/blob/f46cdd0cd227b83d67375f30ad6130ede1a80eef/src/PairedRouting.php#L684-L687

**Comment by jwold** [comment]
I'm on AMP 2.1.2, and I can't replicate this issue. Here's a 40 second video of the steps I included: https://v.usetapes.com/EQECk9EtWm

**Comment by westonruter** [comment]
@jwold It doesn't seem you actually tried navigating to the AMP version.

**Comment by jwold** [comment]
Oh, forgot to click on that during the video (did it off recording). Still looks like everything is fine: https://v.usetapes.com/x4upe8IB6r

**Comment by pierlon** [comment]
**QA Passed**

When the Legacy Reader paired URL structure is enabled along with the Transitional template mode, accessing the AMP link of a comment page no longer results in a redirect to a 404 page:


https://user-images.githubusercontent.com/16200219/124048509-7abe6100-d9e4-11eb-857a-7707d38087f9.mov
