### ISSUE TITLE
Prohibited or invalid use of HTML Tag (Critical)

### ISSUE THREAD

**Issue by jiripik** [Automattic/amp-wp#636]
Can you pls review the errors? See https://www.screencast.com/t/Rgr2Qt4sI

**Comment by Ollibe13** [comment]
It's probably a typo where you have "a ref" that should be "a href" for a hyperlink

**Comment by Ollibe13** [comment]
I'd remove `"ref=magnificpopup"` - i dont think its supported by amp

**Comment by jiripik** [comment]
Yes, but the pure html supports it. 

Would it be please possible for the AMP-WP plugin to remove this tag when generating the AMP pages?

**Comment by amedina** [comment]
I suggest following Ollibe13's suggestion. The plugin cannot remove the attribute because it could break the expectation of the developer; in some cases the plugin can sanitize the page by removing complete tags but it is more challenging to remove just individual attributes. 

Closing for now. Feel free to reopen if you want to discuss further.

**Comment by jiripik** [comment]
If you run https://search.google.com/search-console/amp on https://jiripik.com, there are tons of errors. 

I agree that if you remove the attribute, the page might break. At the same time, however, I cannot manually try to manually fix every singe error since the page is generated by tens of WordPress plugins.

Not really sure what the best course of action would be. Closing is fine.

**Comment by JanBask** [comment]
we try to resolve amp related issue but not able to resolved how can i do for this website [https://www.janbasktraining.com/courses/digital-marketing](https://www.janbasktraining.com/courses/digital-marketing) please suggest me,

**Comment by uniquechukwuma** [comment]
I have tried several times to fix related issues in my AMP in order to have them prominently served to mobile users in my website http://foodforbloggers.com/free-web-directories-building-backlinks/?wpamp, only 2 was resolved out of 9. Please Help
