### ISSUE TITLE
Use dropdown for analytics type instead of input and add a link to vendor lists.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6367]
## Enhancement Description

Although we have clear instructions on the settings panel of analytics, people are still making mistakes while adding analytics configurations. it's been observed from support forums that most of the time they don't enter anything in type input or make a mistake while entering input to avoid let's provide a dropdown box.

### Scenario 2: Include only top/popular 10 ones with the option to input for more.

Following are the top 10 analytics vendors (I consider them top 10 feel free to update the list if needed ) we should consider in the dropdown with input, also please check the possibility of pre-filled vendor configurations for these 10 vendors. 

1. Google Analytics
2. Google Tag
3. Google Ads
4. Adobe Analytics
5. Alexa Metrics 
6. Baidu analytics
7. Facebook Pixel
8. New Relic
9. Nielsen
10. Yandex Metrica

#### Screenshots

![image](https://user-images.githubusercontent.com/1132541/121571981-50aafc00-ca41-11eb-88b2-a3600196034c.png)

## Additional context

 - WordPress version: 5.7.2
 - Plugin version: 2.1.2
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: All Modes
 - PHP version: 7.4
 - OS: Mac 
 - Browser: chrome, safari
 - Device: Macbook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
The list of vendors is available in this directory: https://github.com/ampproject/amphtml/tree/main/extensions/amp-analytics/0.1/vendors

We could have a JSON file which is constructed as part of the build that obtains the list to include with the plugin.

**Comment by pooja-muchandikar** [comment]
The drop-down is in place for Analytics section

![image](https://user-images.githubusercontent.com/41000648/161040106-01842083-8e48-4eb4-8735-8c6396964514.png)

---

But as per the following [description](https://github.com/ampproject/amp-wp/issues/6367#issue-917641421), I think on selecting the input from drop-down the vendors should get prefilled.
> we should consider in the dropdown with input, also please check the possibility of pre-filled vendor configurations for these 10 vendors.

**Comment by milindmore22** [comment]
[examples](https://github.com/ampproject/amphtml/blob/main/examples/analytics-vendors.amp.html)

**Comment by westonruter** [comment]
> But as per the following [description](https://github.com/ampproject/amp-wp/issues/6367#issue-917641421), I think on selecting the input from drop-down the vendors should get prefilled.
> 
> > we should consider in the dropdown with input, also please check the possibility of pre-filled vendor configurations for these 10 vendors.

We can address this in a follow-up issue.
