### ISSUE TITLE
AMP page created by the plugin are not AMP ready 

### ISSUE THREAD

**Issue by abioneperhobby** [Automattic/amp-wp#638]
Hi

i installed the plugin in my wordpress website www.machenotizia.info

every page has now the /amp page, for example

http://www.machenotizia.info/gli-alieni-erano-in-ungheria/amp/

but for google the page is not valid

https://search.google.com/search-console/amp?utm_source=wmx&utm_medium=link&utm_campaign=wmx-agg&id=p79OAI0586imj3gH8RPbnA

i don't know how to show the test page page in english and not in italian,

but google warn that there are custom code : 

<script custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js' async='async" async></script>
<script src="https://cdn.ampproject.org/v0.js' async='async" async></script>

i tried deactivating every plugin and cloudflare cdn, but the issue still the same.

any advice?

thanks.

**Comment by eangulus** [comment]
I get the same. Added the AMP plugin but pointless as Google won't use invalid AMP pages.

**Comment by eangulus** [comment]
Scratch that. Just realised I had my coming soon page enabled (but didn't see as I am logged in).

For others before testing make sure you have the site public.

**Comment by abioneperhobby** [comment]
I changed wordpresa theme and now it work

Il 24 Feb 2017 17:34, "Shaun Williams" <notifications@github.com> ha
scritto:

**Comment by amedina** [comment]
The link: http://www.machenotizia.info/gli-alieni-erano-in-ungheria/amp/#development=1 is validating properly. Closing this issue. Thanks for reporting!
