### ISSUE TITLE
Output <link rel="amphtml"> URL Incorrect

### ISSUE THREAD

**Issue by Woollins** [Automattic/amp-wp#6399]
Site URL is /blog (subdirectory). The preview on the AMP Settings > Paired URL Structure is correct (Legacy reader, also tried the other options). e.g. https://[domain]/blog/category/page/amp/
However the output is <link rel="amphtml" href="https://[domain]/category/page/amp/"> (missing /blog/).
I've tested output of site_url() and site_url( '/' ) - correct https://[domain]/blog/

I've looked into the code and found that **line 51 of amp-helper-functions.php** appears to be stripping the /blog/ and just selecting the domain, is this resulting $url what then gets output in the head tag? If so, this is possibly the issue. The regex could need changing to accommodate sites that are in subdirectory's.

```
function amp_get_current_url() {
$url = preg_replace( '#(^https?://[^/]+)/.*#', '$1', home_url( '/' ) );
...
}
```

**Comment by Woollins** [comment]
It turns out $_SERVER['REQUEST_URI'] does not include the subdirectory /blog/

**Comment by penguinawesome** [comment]
Hii @Woollins how did you managed to solve your problem? We are encountering the same issue as yours where the output url is missing the subdirectory (just pointing to the root url which leads the page to 404)

**Edit:** See #7245.

**Comment by stouch** [comment]
Hi,
We have the same issue on our blog, 
How did you patch this @firephantomassasin ?
Have you planned to release something in the next days @westonruter ?
Thank you

**Comment by penguinawesome** [comment]
@stouch none yet, i am waiting for the bug fix. Please +1 on my post here: https://github.com/ampproject/amp-wp/issues/7245

**Comment by stouch** [comment]
> @stouch none yet, i am waiting for the bug fix. Please +1 on my post here: #7245

I finally edited the extension myself by adding my `blog` prefix like that : 
```
	$current_url .= '/blog/';
```
at the end of the `function amp_get_current_url()` (includes/amp-helper-functions.php)

Hoping though that the next release will fix this big issue @westonruter
