### ISSUE TITLE
How to add data hero manually

### ISSUE THREAD

**Issue by mvneobux** [Automattic/amp-wp#6402]
I know we shouldn't make changes directly to the code. But I have made some manual adjustments and plan to keep them for a while longer before updating the plugin and redoing the changes correctly.

However, I need to include the "data-hero" in the highlighted images and I don't know how to do that.

Currently the image is called:

```
$featured_image = $this->get( 'featured_image' );

if ( empty( $featured_image ) ) {
	return;
}

$amp_html = $featured_image['amp_html'];
$caption  = $featured_image['caption'];
?>
<figure class="amp-wp-article-featured-image wp-caption">
	<?php echo $amp_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
	<?php if ( $caption ) : ?>
		<p class="wp-caption-text">
			<?php echo wp_kses_data( $caption ); ?>
		</p>
	<?php endif; ?>
</figure>
```
The image is generated in this right code: ``$amp_html = $featured_image['amp_html']``

I can pass parameter to be included inside ``<amp-img>`` ?? So that includes the data-hero ?

Help me resolve this temporarily. How can I do this ?

**Comment by westonruter** [comment]
Ah, so the hero image is not being identified for the featured image in the legacy reader template? That's something we should fix in the plugin if that's the case.

**Comment by mvneobux** [comment]
I think you got it wrong.

Everything is working perfectly fine.

I just need to manually add the data-hero to my featured image. So it looks like this: ``<amp-img data-hero src="img" layout="intrinsic" width="719" height="404" ...>``

That is, I just need to add the "data-hero" before the SRC. Can you help me solve this manually?

**Comment by westonruter** [comment]
But shouldn't the plugin be adding this attribute for you? If we aren't identifying that featured image as a hero then that would be a bug.

**Comment by westonruter** [comment]
I can see that `data-hero` is actually already correctly added automatically in the legacy Reader template. For example, look at this post: https://melchoyce.design/2020/12/09/twenty-twenty-one-available-for-download/amp/

**Comment by mvneobux** [comment]
I changed the class-amp-post-template.php file to call my template:
`$template_dir = apply_filters( 'amp_post_template_dir', AMP__DIR__ . '/templates/SonhosAmp2' )`

Because of this, I was wondering if I can make this adjustment without updating the plugin understands?

Because if I update I will lose some manual changes I made.

So it's not a bug, my plugin just isn't up to date.

**Comment by westonruter** [comment]
The AMP plugin adds the `data-hero` attribute dynamically. It doesn't need to be in the template itself.

The plugin adds the `data-hero` attribute (well, actually `data-hero-candidate`) with this code:

https://github.com/ampproject/amp-wp/blob/613cd2b1b323a8f9760699e87201d8041f0324d5/src/Optimizer/HeroCandidateFiltering.php#L91-L121

This means it is automatically added when the template calls `get_the_post_thumbnail()`.

The `PreloadHeroImage`  transformer then automatically adds `data-hero` to the first 2 images with `data-hero-candidate`.

**Comment by mvneobux** [comment]
I updated the plugin. And the featured image is automatically appearing the data-hero. However, the first image that would be the logo, the data-hero does not appear. What was there ?

My site: https://www.segredosdosonho.com.br/sonhar-com-ex-sogra/amp/

**Comment by mvneobux** [comment]
I managed to solve. Only include the data-hero-candidate in the logo image. And it was all normal. Thanks for your attention and help.
