### ISSUE TITLE
Disabling customizer from a theme is not possible.

### ISSUE THREAD

**Issue by ktmn** [Automattic/amp-wp#641]
You can disable the AMP customizer options by adding this filter:

    add_filter( 'amp_customizer_is_enabled', '__return_false' );

The output of this filter is consumed at:

    add_action( 'plugins_loaded', '_amp_bootstrap_customizer', 9 );

which is pretty much at the top of the list in the action sequence: https://codex.wordpress.org/Plugin_API/Action_Reference

You cannot disable the customizer from a theme because themes are loaded after plugins.

My use case is that I have a theme and I want to use my own theme options to customize the AMP template and therefore I want to disable the AMP customizer from inside the theme. But it doesn't seem to be possible.

**Comment by amedina** [comment]
Correct; the use case you describe is not possible. We are working on ways to leverage the underlying theme of a site instead of doing a template redirect to a simplified theme. This will be available in a future version of the plugin. Stay tuned.
