### ISSUE TITLE
Gallery Shortcode amp-carousel=true no longer works

### ISSUE THREAD

**Issue by rsmith4321** [Automattic/amp-wp#6414]
It seems like when using a gallery shortcode the amp-carousel=true no longer seems to have an effect.  Has this functionality been removed or am I missing something?  Thanks!

**Comment by westonruter** [comment]
It's working for me. 

I just tried adding a Shortcode block that contains:

```
[gallery ids="3004,3000,1948" amp-carousel=true]
```

And on the frontend it rendered as a gallery on an AMP page:

![image](https://user-images.githubusercontent.com/134745/123034250-05c4a900-d39e-11eb-98e2-f4887dfaff8c.png)

**Comment by rsmith4321** [comment]
Sorry for the trouble. It's funny I actually had disabled amp on the page I was testing and that was the only issue.  Thanks for the help.  

One other question. I notice object-fit="cover" is being adding inline to my carousel.  Is there a way to change this to "fill" so the images aren't cropped?  Unless it's something I've done by accident, it seems like fill should be the default.  Thanks!

`<amp-img width="1367" height="2048" src="https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet.jpg" class="attachment-full size-full amp-wp-enforced-sizes i-amphtml-layout-fill i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout" alt="Senior portraits in the sunset by the dunes - Huntington Beach State Park" aria-describedby="gallery-8-28774" srcset="https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet.jpg 1367w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-400x600.jpg 400w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-1001x1500.jpg 1001w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-200x300.jpg 200w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-734x1100.jpg 734w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-300x450.jpg 300w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-1025x1536.jpg 1025w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-601x900.jpg 601w" sizes="(max-width: 1367px) 100vw, 1367px" layout="fill" object-fit="cover" disable-inline-width="" i-amphtml-layout="fill" lightbox="carousel3" on="tap:amp-lightbox-gallery.activate"><noscript><img width="1367" height="2048" src="https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet.jpg" alt="Senior portraits in the sunset by the dunes - Huntington Beach State Park" loading="lazy" aria-describedby="gallery-8-28774" srcset="https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet.jpg 1367w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-400x600.jpg 400w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-1001x1500.jpg 1001w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-200x300.jpg 200w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-734x1100.jpg 734w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-300x450.jpg 300w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-1025x1536.jpg 1025w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-601x900.jpg 601w" sizes="(max-width: 1367px) 100vw, 1367px"></noscript><img decoding="async" alt="Senior portraits in the sunset by the dunes - Huntington Beach State Park" aria-describedby="gallery-8-28774" sizes="(max-width: 1367px) 100vw, 1367px" srcset="https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet.jpg 1367w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-400x600.jpg 400w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-1001x1500.jpg 1001w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-200x300.jpg 200w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-734x1100.jpg 734w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-300x450.jpg 300w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-1025x1536.jpg 1025w, https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet-601x900.jpg 601w" src="https://www.ryansmithphotography.com/wp-content/uploads/2017/09/senior-portraits-in-huntington-beach-state-park-murrells-inlet.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content" style="object-fit: cover;"></amp-img>`
