### ISSUE TITLE
Google indexed AMP pages without /amp in URL

### ISSUE THREAD

**Issue by djuric** [Automattic/amp-wp#6415]
## Bug Description

I have a clean installation of WordPress here https://tik.bar with only two active plugins, AMP and Yoast SEO. 
There are 8 published posts in total and all of them have AMP enabled. 

For some reason, AMP versions which were indexed don’t have /amp in the URL. For example: 

Original post URL: https://tik.bar/he-was-sitting-in-a-trash-can-with-high-street-class/
AMP post: https://tik.bar/he-was-sitting-in-a-trash-can-with-high-street-class/amp/
Indexed AMP post: https://www.google.com/amp/s/tik.bar/he-was-sitting-in-a-trash-can-with-high-street-class/

As you can see, the indexed AMP post doesn’t have /amp at the end of the URL. I’m not quite sure how it’s possible that Google can index an AMP page in the same URL format as a Desktop page.

## Expected Behaviour

Google should index AMP pages **with** /amp at the end of the URL. 
Example: https://www.google.com/amp/s/tik.bar/he-was-sitting-in-a-trash-can-with-high-street-class/amp

## Steps to reproduce

1. On mobile device, in Google type: `tik.bar he was sitting in a trash can with high street class`
2. Click on the first result 
3. You get https://www.google.com/amp/s/tik.bar/he-was-sitting-in-a-trash-can-with-high-street-class/ 

## Additional context

This wouldn’t bother me much if it wasn’t for the AMP content update which needs to be done occasionally https://developers.google.com/amp/cache/update-cache . When I hit Indexed AMP post (the one without /amp) then this page automatically becomes invalid AMP page.I get image of the sad robot saying that page is invalid and redirects to non-hosted AMP version. 

You can try it yourself, here is the link to the invalid page https://www.google.com/amp/s/tik.bar/cursive-writing-is-the-best-way-to-build-a-race-track/ . To me this is actually expected. The error says that HTML doesn’t have “amp” attribute (which makes sense because it’s Desktop version of the page on that location) 

 - WordPress version: 5.7.2
 - Plugin version: 2.1.2
 - AMP plugin template mode: Reader (AMP Legacy selected)
 - PHP version: 7.2.19
 - OS: Ubuntu 18.10
 - Browser: [e.g. chrome, safari] Chrome
 - Device: [e.g. iPhone6] Samsung

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
Hello @djuric 

Only valid AMP pages are eligible for AMP cache, if your page can be found on the AMP cache that means it's a valid AMP page, The AMP cache serves pages differently you don't need to re-validate it.

Regarding [AMP cache URL](https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls/?format=websites) it is a reference to canonical URL and may not have /amp/ at the end, if you have a question about how AMP URLs are cached I will recommend checking this [article](https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached/) or contact Google Support.

**Comment by djuric** [comment]
Thanks for your reply. 

> Only valid AMP pages are eligible for AMP cache, if your page can be found on the AMP cache that means it's a valid AMP page, The AMP cache serves pages differently you don't need to re-validate it.

This page https://tik.bar/cursive-writing-is-the-best-way-to-build-a-race-track/amp/ is a valid AMP page but in AMP cache it says it's invalid https://www.google.com/amp/s/tik.bar/cursive-writing-is-the-best-way-to-build-a-race-track/ . There were no changes to the page since it was created.

AMP page has correct canonical URL pointing back to original page and original page has `amphtml` set to /amp version

**Comment by westonruter** [comment]
If the AMP page is at https://tik.bar/cursive-writing-is-the-best-way-to-build-a-race-track/amp/ then the Google AMP viewer would indeed include `/amp/` in the URL. 

For example, if I search for [site:vintageportland.wordpress.com mount tabor map] then I get this result:

> ![image](https://user-images.githubusercontent.com/134745/123350319-9242a900-d50f-11eb-8c34-57c50908f10f.png)

When I tap that I am taken to a Google AMP Viewer with `/amp/` in the URL: https://www.google.com/amp/s/vintageportland.wordpress.com/2010/06/23/mt-tabor-map-1891/amp/

> ![image](https://user-images.githubusercontent.com/134745/123350350-a9819680-d50f-11eb-80b7-f29a2aa3b727.png)

However, if I search for [site:tik.bar cursive-writing-is-the-best-way-to-build-a-race-track] in a mobile viewport, I get:

> ![image](https://user-images.githubusercontent.com/134745/123349877-ad60e900-d50e-11eb-9934-435310869378.png)

When I tap that result I am taken to https://www.google.com/amp/s/tik.bar/cursive-writing-is-the-best-way-to-build-a-race-track/

And this says that the page is invalid AMP:

> ![image](https://user-images.githubusercontent.com/134745/123349999-f31db180-d50e-11eb-9975-73f3c0d1edb5.png)

Nevertheless, if I try adding `/amp/` to the end of the Google AMP Viewer URL: https://www.google.com/amp/s/tik.bar/cursive-writing-is-the-best-way-to-build-a-race-track/amp/

Then it sends me this redirect notice:

> ![image](https://user-images.githubusercontent.com/134745/123350113-2e1fe500-d50f-11eb-9c4f-4bf055e32c42.png)

That's strange.

I can, however, access that AMP version on the AMP cache directly: https://tik-bar.cdn.ampproject.org/c/s/tik.bar/cursive-writing-is-the-best-way-to-build-a-race-track/amp/

@djuric Did you used to have your site in Standard mode and then switch recently to Reader?

**Comment by djuric** [comment]
hey @westonruter thanks for taking the time to check this.

> @djuric Did you used to have your site in Standard mode and then switch recently to Reader?

Site has been in Reader mode from the start, I enabled Reader right after plugin activation. 

I also think that cached URL must have /amp, all the other sites (including the one you showed) have /amp or /?amp in google viewer. I have no idea how Google can cache the version without /amp and show it as valid AMP page.

**Note:** when this website was indexed for the first time, most of the posts **did have /amp** (at least those which I googled). But 3-4 days later, /amp was gone and results that appeared in Google for the same posts are now going to version without /amp 

Another thing: on my other domain (latest WP version, latest AMP plugin version, same number of posts and same Reader mode) when posts were indexed for the first time, **both** versions appeared in google as AMP. I could see the same post appearing twice in search results with AMP icon. First post goes to Google AMP viewer with /amp and second goes to Google AMP viewer without /amp in URL. After few days (again) the /amp version disappeared from results and now I only have version without /amp like I have on tik.bar

I think that anyone would be able to replicate this problem:

- Install latest version of AMP and latest version of WP (at this time it's 2.1.2 and 5.7.2). I also have Yoast SEO but I doubt this would make any difference
- Enable Reader mode with AMP Legacy theme
- Have path sufix as /amp/ 
- Create post(s) and enable AMP for it 

Google will index the site, it may show /amp in viewer for the first few days. After that, it will somehow remove /amp and show those pages without /amp

**Comment by westonruter** [comment]
> I think that anyone would be able to replicate this problem:

This isn't an issue with the Vintage Portland example I showed above. That site is using Reader mode as well, but it has the `/amp/` URLs showing up in the Google AMP Viewer. I'll have to ask around if anyone on the AMP team has an idea of what is going on.

**Comment by westonruter** [comment]
We're currently investigating this.

We're seeing some inconsistencies. For example, if I search for [site:tik.bar he-was-sitting-in-a-trash-can-with-high-street-class] then I get an AMP page showing in the viewer successfully. But if I search for [site:tik.bar cursive-writing-is-the-best-way-to-build-a-race-track] then it shows the sad phone and redirects me to the AMP page on origin. Something seems amiss with the index.

**Comment by djuric** [comment]
> We're seeing some inconsistencies. For example, if I search for [site:tik.bar he-was-sitting-in-a-trash-can-with-high-street-class] then I get an AMP page showing in the viewer successfully. But if I search for [site:tik.bar cursive-writing-is-the-best-way-to-build-a-race-track] then it shows the sad phone and redirects me to the AMP page on origin. Something seems amiss with the index.

Yep, very odd. For the one that is showing in AMP viewer successfully, I can force it to become invalid at any time by sending content update request like it's explained here https://developers.google.com/amp/cache/update-cache . I get "OK" from cache clearing response and then page becomes invalid in AMP viewer. I didn't yet do this for any of the posts on this website (I didn't even create private/public key pairs), the one which is invalid became invalid by itself.

I'm not sure why content update request would do this if it was indexed in the first place as valid AMP page.

**Comment by westonruter** [comment]
There may be an issue with how the AMP Cache understands (or fails to understand) the mobile redirection functionality, specifically the JavaScript-based redirection which is enabled by default. The reason we use JS for redirection is that it is the most compatible across various caching layers in WP, so you don't have to worry about varying the cache by user agent. We implemented this redirection according to Google Search Central's documentation: https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls

If your caching layers vary by the mobile user agents successfully, you can opt-in to server-side redirection in PHP via this helper plugin: https://gist.github.com/westonruter/e5032d805625f0f743237708c43d3783

It is preferable to use server-side redirection anyway for performance, since it is much faster to redirect with HTTP response header rather than to use JavaScript. This may mitigate the issue for you while investigating if there is a problem with how AMP Cache is handling such client-side redirects.

**Comment by westonruter** [comment]
Google internal: b/192232306

**Comment by djuric** [comment]
hey @westonruter 

I tried with server-side redirection in PHP and it's working! Google indexed the page with /amp in the URL 

I added this fix on another website (which has the same problem), it's currently not on https://tik.bar which I reported originally. But when I add it here I'm sure it will work too 

Thanks a bunch for assisting with this issue!
