### ISSUE TITLE
Support amp-playbuzz component

### ISSUE THREAD

**Issue by lysk88** [Automattic/amp-wp#643]
Playbuzz Content can be embedded by using code snippet (including Script element, that can reside in the head element and div with class="pb_feed").

# Issue 

Playbuzz items being embedded with code snippet are not being transformed to amp-playbuzz component.

**Steps required to reproduce Issue**
1. Install amp-wp Plugin 
2. Create a new WP post
3. Embed a Playbuzz item via code snippet (see below code snippet for example)
4. Published AMP post via amp-wp plugin 
5. The new AMP post doesn't contain Playbuzz embedded item

# Suggested solution
**Support Playbuzz out of the box**
1. Playbuzz embed handler should be part of the default embed handlers.
2. Playbuzz embed handler should support  [amp-playbuzz attributes](https://www.ampproject.org/docs/reference/components/amp-playbuzz) 

**Instructions on how to transform code snippet to amp component**

Code snippet
```js
<script type="text/javascript" src="//cdn.playbuzz.com/widget/feed.js"></script>
<div class="pb_feed"  data-item="3103bc0a-4633-43e6-8ca9-ae005551924d" data-game="HistoryUK/10-classic-christmas-movies" data-game-info="false" data-shares="true" data-comments="false"></div>
```
Should be converted to
```js
<amp-playbuzz src="https://www.playbuzz.com/HistoryUK/10-classic-christmas-movies" data-item="a6aa5a14-8888-4618-b2e3-fe6a30d8c51b" height="500" data-item-info="false" data-share-buttons="true" data-comments="false"></amp-playbuzz>
```

**Attributes to convert**

_data-item_  ( only if code snippet contains data-item )
- Take the value from the code snippet attribute  data-item.

_src_ ( only if code snippet contains data-game )
- Take the value from the code snippet attribute data-game and prefixing with www.playbuzz.com
Example:

Code snippet
```js

data-game="HistoryUK/10-classic-christmas-movies"
```

Should be converted to
```js
src="//www.playbuzz.com/HistoryUK/10-classic-christmas-movies"
```

_height_
- Value should be 500.

_data-item-info_  ( only if code snippet contains data-game-info )
- Take the value from the code snippet attribute data-game-info. 

_data-share-buttons_ ( only if code snippet contains data-shares ) 
- Take the value from the code snippet attribute data-shares.

_data-comments_  ( only if code snippet contains data-comments ) 
- Take the value from the code snippet attribute data-comments.

**Comment by rudygalfi** [comment]
It looks like with the merge of #664 this can be closed?

**Comment by mjangda** [comment]
Yep.
