### ISSUE TITLE
Add toggle to disable AMP page from within the AMP editor sidebar

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#6438]
## Feature description

Right now users can disable AMP on a per page basis by visiting the settings sidebar, and navigating to the page tab; from there they can expand the AMP accordion and disable AMP. We've added this ability here, as well as the pre-publish page. 

A new location we can add it to is the AMP specific sidebar. This is where we're trained to go to solve AMP related issues on a per page basis. Allowing someone to disable AMP on this page would reduce friction. Now, with that said I'd like validation on this issue before we add this as a feature enhancement. Would we want to prioritize disabling AMP over resolving issues? 

Following is my proposal for how we'd enable this:

![Group 1](https://user-images.githubusercontent.com/3411173/124019706-3c05b800-d99e-11eb-951b-9b66c1d3f2a8.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
One complication with this is that once AMP is disabled, then the AMP Validation sidebar is removed entirely. So the user wouldn't know how to enable AMP again. In other words, if it is added here then the toggle would never appear in an Off state. That being the case, maybe a button would make more sense?

**Comment by jwold** [comment]
Good point! Is it possible to make a button/link to open the other sidebar? Then we're training people where to go.

**Comment by westonruter** [comment]
Yes, I believe so. We actually do that already, as there is a button from the AMP status accordion item to open the AMP Validation sidebar. So we could add the reverse.

**Comment by jwold** [comment]
Tentative approach we could make:

![Group 4](https://user-images.githubusercontent.com/3411173/124035174-0b7b4980-d9b1-11eb-84cd-68685b08eb76.png)
