### ISSUE TITLE
Error for Sound file : Not a valid AMP page

### ISSUE THREAD

**Issue by KhalidAlmallahi** [Automattic/amp-wp#644]
There are problem in some page in my site, When you test this page: 

https://search.google.com/search-console/amp?utm_source=wmx&utm_medium=link&utm_campaign=wmx-agg&id=QJ9owsgYpzMn_4iKKSbvuw

we show Not a valid AMP page
Invalid AMP pages will not have AMP-specific features in Google search results.

in this code:

    <source type="audio/mpeg" src="http://traffic.libsyn.com/saudigamer/saudigamer_e212_010913.mp3?_=1"/></amp-audio></div><p class="powerpress_links powerpress_links_mp3">Podcast: <a href="http://traffic.libsyn.com/saudigamer/saudigamer_e212_010913.mp3" class="powerpress_link_pinw" target="_blank" title="Play in new window" rel="nofollow">Play in new window</a> | <a href="http://traffic.libsyn.com/saudigamer/saudigamer_e212_010913.mp3" class="powerpress_link_d" title="Download" rel="nofollow" download="saudigamer_e212_010913.mp3">Download</a></p>

Are AMP support sound file ?!

**Comment by KhalidAlmallahi** [comment]
Any Updates !!

**Comment by mjangda** [comment]
amp-audio requires audio files to be served over SSL (i.e. the protocol for the URL should be `https`).

Changing `http` to `https` in your post should work as libsyn supports SSL.

**Comment by KhalidAlmallahi** [comment]
why should be https !!

**Comment by mjangda** [comment]
It's an AMP requirement.

**Comment by KhalidAlmallahi** [comment]
but i cannot have https becase i buy server that have http only

**Comment by rmens** [comment]
Buy another server or disable amp.
