### ISSUE TITLE
Pagespeed Insights with low score

### ISSUE THREAD

**Issue by thiagovieiradev** [Automattic/amp-wp#6449]
The AMP versions of my site are rated low on the mobile version, which influences the best metrics for the google web. But I can't solve this problem because it is not possible to remove scripts from the plugin (which are essential for the operation). How to increase my grade?

Ps.: Sorry my English, I used the translator.

![erro1](https://user-images.githubusercontent.com/11833919/124786168-e3926580-df1d-11eb-931c-1b524571a5ea.JPG)
![erro2](https://user-images.githubusercontent.com/11833919/124786174-e4c39280-df1d-11eb-9fdd-3852a0c65bd4.JPG)

**Comment by mxbclang** [comment]
Hi there, @thiagovieiradev! We provide support for AMP on the [WordPress.org support forums](https://wordpress.org/support/plugin/amp/). If you [create a new topic ](https://wordpress.org/support/plugin/amp/#new-topic-0)there, we'd be happy to take a look.
