### ISSUE TITLE
amp-web-push support

### ISSUE THREAD

**Issue by rgomezp** [Automattic/amp-wp#6453]
## Feature description
Currently there is no easy way that I know of to integrate push notifications with the official AMP plugin for Wordpress. Setting up notifications requires writing some custom markup (adding the `amp-web-push` tag with configuration properties) that doesn't get removed by the plugin automatically (perhaps you could whitelist amp HTML tags to prevent removal). The plugin doesn't provide a way to add custom code whatsoever (see support ticket: https://wordpress.org/support/topic/how-can-i-add-custom-html-in-page/).

*Workaround*: 
The workaround currently is to add the markup via atomic blocks in each individual page or post. However, this is not optimal.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
Hello @rgomezp 

I created a [mini plugin](https://github.com/milindmore22/amp-onesignal-compat) to make OneSignal – Web Push Notifications AMP Compatible, we prompt using it to whoever asks for it in AMP Support Forums.

**Comment by rgomezp** [comment]
@milindmore22 ,
And this works with the official AMP plugin?

Are there any plans to integrate it into the official AMP plugin?

**Comment by milindmore22** [comment]
@rgomezp 
yes, this works with the official AMP plugin, The AMP plugin allows users to serve AMP pages, it is not purposed to serve push notifications. so it will best approach that AMP Compatability gets adopted in the OneSignal WordPress plugin.

I will try to contribute to the OneSignal WordPress plugin to make it AMP Compatible.
