### ISSUE TITLE
Meta tag getting stripped off in AMP List/Mustache

### ISSUE THREAD

**Issue by flixwatchsupport** [Automattic/amp-wp#6457]
## Bug Description

Meta tag getting stripped off in AMP List/Mustache

## Expected Behaviour

Meta tag should not be stripped off.

## Steps to reproduce

I am trying to add ItemList MicroData for Schema but the Meta tag is getting stripped off in the amp-list/mustache. Here's the code I am using for Microdata:

```
<div itemscope itemtype="https://schema.org/ItemList">
    <span itemprop="name"><?php $title; ?></span>
    <link itemprop="itemListOrder" href="https://schema.org/ItemListOrderDescending" />
    <amp-list height="100" width="auto" load-more="auto" src="https://www.flixwatch.co/stagin/list-schema/?post_id=<?php echo $post->ID; ?>" binding="no">
       <template type="amp-mustache">
        <div itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <meta itemprop="position" content="{{rank}}"/>
            <div itemprop="url">{{url}}</div>
        </div>
       </template> 
    </amp-list>
</div>
```
But in the [output](https://search.google.com/test/rich-results?id=lSysHk1EJGDReuSxjJIhxA), the meta tag is getting stripped.

Here's the [link](https://wordpress.org/support/topic/json-ld-markup-with-amp-list-mustache/) to the Wordpress AMP Plugin Support.

This is the [link](https://stackoverflow.com/questions/68255954/meta-tag-getting-stripped-off-in-amp-list-mustache) to stackoverflow post.

## Additional context

 - WordPress version: 5.7.2
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Standard
 - PHP version: 7.3
 - OS: All
 - Browser: [e.g. chrome, safari] All
 - Device: [e.g. iPhone6] All

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
Hello @flixwatchsupport 
I will recommend [creating an issue](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=Type%3A+Bug&template=bug-report.yml) in [AMP Core](https://github.com/ampproject/amphtml)

**Comment by pierlon** [comment]
@flixwatchsupport the `meta` tag is being stripped because the `amp-mustache` template is being sanitized, per the [docs](https://amp.dev/documentation/components/amp-mustache/?format=websites#sanitization):

> Mustache output is sanitized for security reasons and to maintain AMP validity. This may result in certain elements and attributes being silently removed.

It would be great to expose the removed elements and attributes as validation errors but that's currently not the case unfortunately. There is an open issue in AMP Core tracking that feature if you are interested: https://github.com/ampproject/amphtml/issues/17897.
