### ISSUE TITLE
AMP box doens't appear

### ISSUE THREAD

**Issue by br0k3n** [Automattic/amp-wp#646]
Hi, I install your plugin, but the proper box doesn't appear on any blog post.

How can I solve?
Thanks

**Comment by amedina** [comment]
Sorry, it is not clear what the problem is; could you provide examples or links to reproduce the error?

**Comment by amedina** [comment]
Closing for now. Feel free to re-open if you haven't been able to get your site going with the plugin and can provide more data to reproduce.
