### ISSUE TITLE
Update to v2.1.3 crashes website with Server Error

### ISSUE THREAD

**Issue by tailorvj** [Automattic/amp-wp#6460]
## Bug Description

After updating the plugin from v1.5.5 to v2.1.3, the website returns a Server Error. wp-admin is still available. 

## Expected Behaviour

I expected it to just work :)

## Steps to reproduce

1. Go to https://www.otot.tv/wp-admin/plugins.php and locate the AMP plugin
2. Click on update
3. Open the homepage

## Screenshots

Sorry, I don't feel like crashing my website again for it

## Additional context

 - WordPress version: 5.7.2
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable): 
 - AMP plugin template mode: Reader
 - PHP version: 7.4.15
 - OS: Linux
 
Kind regards,
Tailor

**Comment by pierlon** [comment]
Hello @tailorvj, thanks for reporting the issue. Unfortunately we won't be of much help unless we know why the update causes your site to crash. Could you submit your [site health information](https://docs.google.com/forms/d/1JTQmphDlk9YgHpDoFRbHXpkDqv8-QmzTT7MDR4AstyQ/viewform?edit_requested=true)?

**Comment by westonruter** [comment]
Indeed. We need to know what the error is.
