### ISSUE TITLE
Combine AMP with PWA

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/amp-wp#6465]
## Feature description

Continuing discussion from https://github.com/GoogleChromeLabs/pwa-wp/issues/564, to consider below as recommended by AMP team at https://amp.dev/documentation/guides-and-tutorials/learn/combine-amp-pwa/

- [ ]  AMP pages with PWA features
- [ ]  AMP as entry point into PWA
- [ ]  Use AMP as data source

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
For AMP as entry point and data source in a SPA, see exploration in https://github.com/ampproject/amp-wp/pull/1519. However, I don't see this PR being merged, as I don't see it as being in scope for this plugin.

Also, see issue for adding AMP content to REST API: https://github.com/ampproject/amp-wp/issues/1014 (and PR https://github.com/ampproject/amp-wp/pull/2827)
