### ISSUE TITLE
Notice - Undefined Variable -> AMP

### ISSUE THREAD

**Issue by HowdyMcGee** [Automattic/amp-wp#647]
I'm getting the following error repeatedly. 

> PHP Notice:  Undefined variable: is_amp_endpoint in /wp-content/plugins/w3-total-cache/Extension_Amp_Plugin.php on line 22

If we got there we need to define the variable at the top of the function so that if the conditional is false the variable will still exist:

```
private function is_amp_endpoint() {
	$is_amp_endpoint = false;
	
	if ( is_null( $is_amp_endpoint ) && function_exists('is_amp_endpoint') ) {
		$is_amp_endpoint = is_amp_endpoint();
	}

	return $is_amp_endpoint;
}
```

It's not that `$is_amp_endpoint` is null at this point it's that it's undefined and thus the error. The above code should resolve the issue.

**Comment by mjangda** [comment]
This is an issue with W3 Total Cache (and the code referenced is in their plugin).
