### ISSUE TITLE
The attribute 'width' may not appear in tag 'hr'.

### ISSUE THREAD

**Issue by dermatzeimnetz** [Automattic/amp-wp#648]
Example page where the error occurs:
http://www.westerwald-blog.de/2013/10/deutsch-hollaendischer-stoffmarkt-in-neuwied/amp/

**Comment by amedina** [comment]
Cannot have the attribute width for <hr> tags. Could you try removing it and see if the user experience is degraded in any way? Closing for now sine it is a restriction in the validation process.
