### ISSUE TITLE
Lightbox settings are not honored when Gutenberg is active.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6485]
## Bug Description

While debugging an issue for a user from [support topic](https://wordpress.org/support/topic/add-lightbox-effect/#post-14701750), I noticed that AMP Lightbox is forced on Images and Gallery even when the user has not opted-in for it.

The issue may be something similar to #5122 

## Expected Behaviour

Lightbox toggle settings should be honored images should not open in lightbox

## Steps to reproduce

1. Install and Activate the latest Gutenberg plugin
2. Create a New post
3. Add Image block ( do not opt-in for lightbox)
4. Add Gallery Block (do not opt-in for lightbox )
5. Save -> Visit Post -> AMP page
6. Click on Image (Open up in Lightbox)
7. Click on any image from Gallery (Opens up in Lightbox)

## Screenshots

https://recordit.co/SdhDQ4ZegK

## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable): 11.1.0
 - AMP plugin template mode: Transitional Mode
 - PHP version: 7.4
 - OS: Mac OS Catlina
 - Browser: [e.g. chrome, safari] Chrome
 - Device: [e.g. iPhone6] Macbook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@milindmore22 Please confirm if it is the same issue via https://github.com/ampproject/amp-wp/issues/5122#issuecomment-764883002 to turn off auto-lightbox.

**Comment by milindmore22** [comment]
Yes, it's the same issue, but it was reproducible with the Gutenberg plugin and not with Core Block Editor.

**Comment by westonruter** [comment]
I'm confused. The issue doesn't happen when Gutenberg is deactivated?

**Comment by milindmore22** [comment]
I am unable to reproduce the issue today, I think it may be the cached results that got me confused, sorry to take your time I will mark this issue as closed.
