### ISSUE TITLE
Consider adding UI setting for data removal upon uninstall

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6486]
## Feature description

Please see https://github.com/google/web-stories-wp/issues/8453, where there is a discussion of whether uninstallation should require an explicit user opt-in to delete plugin data. This is a follow-up on https://github.com/ampproject/amp-wp/issues/3210. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by kenrodriguesdesign** [comment]
I will be picking this issue up for the design

**Comment by kenrodriguesdesign** [comment]
Hey @westonruter 

For this, there were a couple of locations where the user could encounter the option to delete data.

1. An option for data removal in the plugin settings screen.
<img width="1281" alt="Screenshot 2021-08-25 at 9 32 10 PM" src="https://user-images.githubusercontent.com/61531990/130825252-f13eb8a4-404f-471d-9b1c-a4145eb1774a.png">

2. When the user deletes the plugin in the Plugins list page.
<img width="1158" alt="Screenshot 2021-08-25 at 9 32 24 PM" src="https://user-images.githubusercontent.com/61531990/130825261-653f7c32-ad53-4271-a617-5650f1074f7e.png">

By default both the options are unchecked.

Let me know your thoughts and whether this would work.

**Comment by westonruter** [comment]
> 1. An option for data removal in the plugin settings screen.

This could make sense in the new Other section: https://github.com/ampproject/amp-wp/pull/6501

> 2. When the user deletes the plugin in the Plugins list page.

This won't be feasible because when the plugin is deactivated we will not be able to provide a custom UI to add the checkbox.

**Comment by kenrodriguesdesign** [comment]
Okay, noted.

>This could make sense in the new Other section: #6501

Sending an updated UI.
<img width="1280" alt="Screenshot 2021-08-26 at 10 21 34 PM" src="https://user-images.githubusercontent.com/61531990/131003624-03307e3d-885f-4050-aa5c-2e3ef1902bd5.png">

>This won't be feasible because when the plugin is deactivated we will not be able to provide a custom UI to add the checkbox.

I was looking at a couple of examples when deleting a plugin came across an option which mentions the deletion of data.
<img width="1281" alt="Screenshot 2021-08-26 at 10 23 51 PM" src="https://user-images.githubusercontent.com/61531990/131004008-75497606-3194-4589-b126-e5cebfda80cb.png">

<img width="1283" alt="Screenshot 2021-08-26 at 8 40 18 PM" src="https://user-images.githubusercontent.com/61531990/131003735-8782d601-b632-4f5a-9416-d8f1d94bbf39.png">

I understand it's not custom UI, but is it possible to add that checkbox for a better experience, rather than deleting it without user intervention?

**Comment by westonruter** [comment]
> I understand it's not custom UI, but is it possible to add that checkbox for a better experience, rather than deleting it without user intervention?

Unfortunately this is something that would have to be done in WordPress core. In fact, this is proposed in an old core ticket: https://core.trac.wordpress.org/ticket/20578

So it seems the best we can do is add the toggle to the plugin settings screen.

**Comment by westonruter** [comment]
I just thought of a hack which may actually work. What we could do is add the prompt instructing the user to enable to toggle to the plugin description so that it shows up when the plugin is inactive. Then when the plugin is active, we can strip the notice out of the description:

<img width="1270" alt="Screen Shot 2021-08-26 at 12 48 38" src="https://user-images.githubusercontent.com/134745/131026956-3ea3e846-9a98-4881-928b-1d9c75d9ea75.png">
<img width="1263" alt="Screen Shot 2021-08-26 at 12 49 35" src="https://user-images.githubusercontent.com/134745/131026960-1164263a-af2e-4cf5-9db3-dc38b98e444f.png">

Quick patch to show how that could be achieved:

```diff
--- a/amp.php
+++ b/amp.php
@@ -1,7 +1,7 @@
 <?php
 /**
  * Plugin Name: AMP
- * Description: An easier path to great Page Experience for everyone. Powered by AMP.
+ * Description: An easier path to great Page Experience for everyone. Powered by AMP. <em class="amp-deletion-notice"><strong>Deletion Note:</strong> To delete all plugin data with uninstallation, first activate the the plugin, go to the settings screen, and enable the data deletion toggle (if you haven't done so already).</em>
  * Plugin URI: https://amp-wp.org
  * Author: AMP Project Contributors
  * Author URI: https://github.com/ampproject/amp-wp/graphs/contributors
@@ -17,6 +17,17 @@
 define( 'AMP__DIR__', dirname( __FILE__ ) );
 define( 'AMP__VERSION', '2.2.0-alpha' );
 
+// @todo Eliminate this once https://core.trac.wordpress.org/ticket/20578 has finally landed.
+add_filter(
+	'all_plugins',
+	function ( $meta ) {
+		if ( isset( $meta['amp/amp.php']['Description'] ) ) {
+			$meta['amp/amp.php']['Description'] = preg_replace( ':\s*<em class=\"amp-deletion-notice\">.+?</em>:', '', $meta['amp/amp.php']['Description'] );
+		}
+		return $meta;
+	}
+);
+
 /**
  * Errors encountered while loading the plugin.
  *
```

cc @swissspidy

**Comment by pierlon** [comment]
Quite an interesting workaround, I wonder how it would show on the WordPress plugins [search page](https://wordpress.org/plugins/search/amp/)...

![image](https://user-images.githubusercontent.com/16200219/131033007-5827e198-2290-4575-9157-a1dc5c198ae7.png)

**Comment by westonruter** [comment]
> Quite an interesting workaround, I wonder how it would show on the WordPress plugins [search page](https://wordpress.org/plugins/search/amp/)...

Unless I'm mistaken, that text comes from the `readme.txt`, which we have duplicated with `amp.php`:

https://plugins.trac.wordpress.org/browser/amp/tags/2.1.3/amp.php#L4
https://plugins.trac.wordpress.org/browser/amp/tags/2.1.3/readme.txt#L11

**Comment by pierlon** [comment]
Yep you're right. That can be verified with the Web Stories plugin that uses different descriptions in [`readme.txt`](https://github.com/google/web-stories-wp/blob/24fe648cb6e4f6c63a8e8d06a4fe2a8fec6a3920/readme.txt#L11) and [`web-stories.php`](https://github.com/google/web-stories-wp/blob/24fe648cb6e4f6c63a8e8d06a4fe2a8fec6a3920/web-stories.php#L11), for example:

`web-stories.php`
> Visual storytelling for WordPress.

`readme.txt`
> Web Stories are a visual storytelling format for the open web which immerses your readers in fast-loading, full-screen, and visually rich experiences.

WordPress plugin directory:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/16200219/131039682-14172810-db87-4129-bf18-669f9b0523b4.png">

**Comment by swissspidy** [comment]
Hmm we should probably update the description in `web-stories.php` 🤔 

Adding such an uninstall note to the description sounds very novel to me. Not aware of any other plugin doing this. Nice way to give users one last reminder before deletion.

What I am wondering: does the AMP plugin really need such a UI setting?

While the Web Stories plugin deals with user-generated content, the AMP plugin just stores validation errors, transients, and some user preferences. Even if removed unintentionally, that doesn't seem too bad to me.

**Comment by westonruter** [comment]
> While the Web Stories plugin deals with user-generated content, the AMP plugin just stores validation errors, transients, and some user preferences. Even if removed unintentionally, that doesn't seem too bad to me.

That's true. The AMP Settings could be a pain if they were wiped out unexpectedly, though. And validation errors have statuses (kept / removed) which would could be a pain to lose depending on the site. I dunno, safer than sorry seems usually to be the better approach.

**Comment by kenrodriguesdesign** [comment]
Looks like a really good solution @westonruter 
I like it.

Would it be possible to make the instructions looks like steps the user needs to follow, it seems to get lost in the text preset?
Something like this?
<img width="1281" alt="Screenshot 2021-09-01 at 3 00 57 PM" src="https://user-images.githubusercontent.com/61531990/131648048-33e6a39b-5bae-4e66-88a2-62d301b0d265.png">

**Comment by westonruter** [comment]
Yes, that should be doable. There are some restrictions to the text which can appear in the description, so that's why I've used `em` and `strong` for example. Here are the allowed tags: https://github.com/WordPress/wordpress-develop/blob/baa5ba32d8698f6a6a5928bcbd4fea35bd47a8c1/src/wp-admin/includes/plugin.php#L173-L186

**Comment by kenrodriguesdesign** [comment]
Adding a Figma link for reference and copy as well.

https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/AMP-Design?node-id=3293%3A26161

**Comment by bartoszgadomski** [comment]
**QA results:**

1. "Delete plugin data at uninstall" is set to "true" by default, while user have to opt-in for that in the earlier versions of AMP plugin. Is that change intentional? As @kenrodriguesdesign suggested in his designs, this option was supposed to be unchecked by default: https://github.com/ampproject/amp-wp/issues/6486#issuecomment-905673299, @dhaval-parekh @westonruter

2. Other than that, all good 👍

![Screenshot 2021-11-22 at 12 31 10](https://user-images.githubusercontent.com/4476915/142854464-44c67a17-8f47-4f84-910e-8e0338792eae.png)
![Screenshot 2021-11-22 at 12 31 01](https://user-images.githubusercontent.com/4476915/142854469-9beac00d-f575-428d-897f-40f346cd8280.png)

**Comment by dhaval-parekh** [comment]
> 1. "Delete plugin data at uninstall" is set to "true" by default, while user have to opt-in for that in the earlier versions of AMP plugin. Is that change intentional? As @kenrodriguesdesign suggested in his designs, this option was supposed to be unchecked by default: Consider adding UI setting for data removal upon uninstall #6486 (comment),

Yes, It has been changed as per [feedback](https://github.com/ampproject/amp-wp/pull/6632#discussion_r722665083). The unchecked "Keep my data" (from the design) and checked "Delete plugin data at uninstalling" are the same, so I think that should not be an issue.

**Comment by westonruter** [comment]
Yes, I think it makes sense to have this enabled by default regardless of whether it's a new install or an old install. When uninstalling WordPress will provide a prompt to say that uninstalling will delete data, so it's best if we go ahead and do that deletion by default. The user could go to the settings and toggle that option off if they want to keep the data, so even though the prompt will still say the data will be deleted, in actuality we won't be doing anything.
