### ISSUE TITLE
Lightbox gallery always show first image.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6489]
## Bug Description

If a page/post has multiple images and all images are opted-in for AMP Lightbox, clicking on any image shows/focus the first image on the page.

## Expected Behaviour

The clicked image should be opened up/focused in the lightbox gallery.

## Steps to reproduce

1. Create a Post
2. Add 3-4 images and Opt-in for Lightbox
3. Open Same Post's AMP endpoint
4. Scroll down and click 2nd, 3rd, or 4th image
5. The first Image shows up.

## Screenshots

https://recordit.co/bIdEHsi0gI

## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable): not active
 - AMP plugin template mode: Transitional Mode 
 - PHP version: 7.4
 - OS: Mac OS Catlina
 - Browser:  Chrome
 - Device: MacBook Air

Test URL (it will last for 6 days ): https://particular-copperhead.jurassic.ninja/2021/07/26/image-test-gutenberg-deactivated/amp/ 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
It looks like this may be an issue with AMP core. See https://github.com/ampproject/amphtml/issues/35402.

**Comment by westonruter** [comment]
Nevertheless, I don't think the workaround described in https://github.com/ampproject/amphtml/issues/35402#issuecomment-887837815 will work in the plugin because the unused `amp-carousel` script would get stripped out.

**Comment by milindmore22** [comment]
Closing this as it's fixed in upstream https://github.com/ampproject/amphtml/pull/36103 and we are no longer able to reproduce the bug.
