### ISSUE TITLE
Onboarding wizard sidebar stepper not showing step icons

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#6490]
## Bug Description

When I'm going through the onboarding wizard, I'll occasionally see the icons missing for the first three steps in the sidebar. 

This seems to only happen when reaching the end of the onboarding wizard, and attempting to go backward. 

Note: This only seems to happen in Safari on Mac, couldn't get it to replicate in Chrome.

## Expected Behaviour

The onboarding wizard stepper icons should stay visible at all times.

## Steps to reproduce

1. Go through the onboarding wizard a first time on a clean install
2. Go to AMP settings and reopen wizard
3. Choose `developer` in the technical background question (although this doesn't seem to matter)
4. Choose `transitional` in the modes (although this doesn't seem to matter)
5. Go to the `done` screen 
6. Go back to the `template modes` screen

## Screenshots

<img width="265" alt="Screen Shot 2021-07-27 at 3 11 31 PM" src="https://user-images.githubusercontent.com/3411173/127234216-e05ceead-e4e9-457f-8ae1-e08af3d35001.png">

Here's a 12 second video of it happening: https://v.usetapes.com/x2T8kgYqLj

## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable): N/A
 - AMP plugin template mode: N/A
 - PHP version: 7.3.5
 - OS: macOS Big Sur
 - Browser: Safari Version 14.1.1 (16611.2.7.1.4). 
 - Device: MacBook Air M1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Seems to be only occurring in Safari, looking into this...

**Comment by westonruter** [comment]
**QA Passed**

The stepper icons are showing after repeated back-and-forth in Safari:

https://user-images.githubusercontent.com/134745/131412490-465bcd6a-63aa-49a9-b924-f40b0906d08a.mov
