### ISSUE TITLE
Redirect Loop with multiple spaces in the url

### ISSUE THREAD

**Issue by rolandfarkasCOM** [Automattic/amp-wp#6492]
## Bug Description

A redirect loop is caused when more than one spaces are in the url.

## Expected Behaviour

Page to work normally

## Steps to Reproduce

defeated-leopard.jurassic.ninja/?test=test+this+out+as+it+breaks+your+site

I have uninstalled Jetpack, installed AMP, enabled standard mode, selected a static homepage, and changed the permalink settings to Post Name.

So by the looks of it, a combination of the above settings is the cause.

## Screenshots

N/A

## Additional context

 - WordPress version: Latest
 - Plugin version: Latest
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Standard
 - PHP version: 7.4,8.0
 - OS: UBUNTU
 - Browser: All
 - Device: All

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
I am able to reproduce this issue with Static Homepage and post name permalink structure.

**Comment by westonruter** [comment]
I can reproduce the issue as well, but only when a static front page is selected. It also happens only when the AMP plugin is active alone.

**Comment by westonruter** [comment]
I've traced the issue down to a behavior where `remove_query_arg()` is normalizing URLs to use `+` for spaces instead of `%20`:

```
wp> remove_query_arg('amp', '/?test=one+two+three')
=> string(20) "/?test=one+two+three"
wp> remove_query_arg('amp', '/?test=one%20two%20three')
=> string(20) "/?test=one+two+three"
```

In contrast, `redirect_canonical()` is [normalizing query strings](https://github.com/WordPress/wordpress-develop/blob/ad976addb3612a77e5e4e2211283514a2aedbf8a/src/wp-includes/canonical.php#L551-L562) to use `%20` instead of `+` for spaces, by means of `parse_str()` plus `rawurlencode_deep()`:

```
parse_str('test=one+two+three', $parsed_query); echo rawurlencode_deep($parsed_query['test']);
>> one%20two%20three
parse_str('test=one%20two%20three', $parsed_query); echo rawurlencode_deep($parsed_query['test']);
>> one%20two%20three
```

In this way, `\AmpProject\AmpWP\PairedRouting::redirect_extraneous_paired_endpoint()` is causing a redirect with query parameters including `+` but then `redirect_canonical()` is redirecting to use `%20`.

**Comment by westonruter** [comment]
I've created the fix in #6494.

**Comment by rolandfarkasCOM** [comment]
Thanks @westonruter & @milindmore22 hopefully an update will be available soon.

**Comment by westonruter** [comment]
To be closed when the PR is merged.

We'll give you a prerelease build to use while waiting for 2.1.4.

**Comment by rolandfarkasCOM** [comment]
Thank you 👍🙏

**Comment by westonruter** [comment]
@rolandfarkasCOM Please use the 2.1.x production build linked from the [Development Builds wiki page](https://github.com/ampproject/amp-wp/wiki/Development-Builds#:~:text=2.1.x%20production).

**Comment by westonruter** [comment]
**QA Passed**

After having set the template mode to Standard, setting the homepage to a static page, and setting the permalink structure to post name:

Before, going to: `https://wordpress-stable.lndo.site/?test=test+this+out+as+it+breaks+your+site`

> ![image](https://user-images.githubusercontent.com/134745/131411792-531bb681-a053-454d-9c27-cf2b127a2530.png)

After, no infinite redirect:

> ![image](https://user-images.githubusercontent.com/134745/131412017-910c030f-6288-42ed-bb46-8d7583392217.png)

**Comment by rolandfarkasCOM** [comment]
Thanks for the help @westonruter it is very much appreciated!
