### ISSUE TITLE
Google Showing AMP Results On Desktop Results

### ISSUE THREAD

**Issue by KhalidAlmallahi** [Automattic/amp-wp#650]
Looks like there is a bug with Google's implementation of AMP. Google is now showing AMP icons and content in the core desktop results. They recently launched AMP in the core mobile results but AMP should NOT show in the desktop results.

[Ashley ](https://twitter.com/BermanHale/status/780817240769769472)posted on Twitter that they are now showing up on desktop. And yes, I was able to replicate it. Here is a screen shot of this site showing its AMP pages in the core Google desktop results and yes, when I click on them, it goes to my AMP URLs.

Any Help !!

**Comment by mjangda** [comment]
It's possible they may be testing AMP on desktop search results. In any case, this is something on Google's end.
