### ISSUE TITLE
Fatal error in PHP 8 

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6505]
## Bug Description

The PHP 8 compatibility added in https://github.com/ampproject/amp-wp/issues/5480 was not proven to be exhaustive, and a [support topic](https://wordpress.org/support/topic/amp-plugins-not-working-using-php8/) has illuminated an area that needs to be fixed. They reported the following error: 

> A PHP error occurred while trying to prepare the AMP response. This may not be caused by the AMP plugin but by some other active plugin or the current theme. You will need to review the error details to determine the source of the error. &#8211; unserialize(): Argument 1 ($data) must be of type string, `AmpProject\AmpWP\RemoteRequest\CachedResponse` given (0) [TypeError]

Stack trace:

```
#0 /var/www/html/wp-content/plugins/amp/src/RemoteRequest/CachedRemoteGetRequest.php(116): unserialize()
#1 /var/www/html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/RuntimeVersion.php(78): AmpProject\\AmpWP\\RemoteRequest\\CachedRemoteGetRequest-&gt;get()
#2 /var/www/html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/Optimizer/Transformer/AmpRuntimeCss.php(163): AmpProject\\RuntimeVersion-&gt;currentVersion()
#3 /var/www/html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/Optimizer/Transformer/AmpRuntimeCss.php(139): AmpProject\\Optimizer\\Transformer\\AmpRuntimeCss-&gt;inlineCss()
#4 /var/www/html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/Optimizer/Transformer/AmpRuntimeCss.php(101): AmpProject\\Optimizer\\Transformer\\AmpRuntimeCss-&gt;addStaticCss()
#5 /var/www/html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/Optimizer/TransformationEngine.php(65): AmpProject\\Optimizer\\Transformer\\AmpRuntimeCss-&gt;transform()
#6 /var/www/html/wp-content/plugins/amp/src/Optimizer/OptimizerService.php(46): AmpProject\\Optimizer\\TransformationEngine-&gt;optimizeDom()
#7 /var/www/html/wp-content/plugins/amp/includes/class-amp-theme-support.php(2046): AmpProject\\AmpWP\\Optimizer\\OptimizerService-&gt;optimizeDom()
#8 /var/www/html/wp-content/plugins/amp/includes/class-amp-theme-support.php(1668): AMP_Theme_Support::prepare_response()
#9 [internal function]: AMP_Theme_Support::finish_output_buffering()
#10 /var/www/html/wp-includes/functions.php(4979): ob_end_flush()
#11 /var/www/html/wp-includes/class-wp-hook.php(303): wp_ob_end_flush_all()
#12 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters()
#13 /var/www/html/wp-includes/plugin.php(470): WP_Hook-&gt;do_action()
#14 /var/www/html/wp-includes/load.php(1097): do_action()
#15 [internal function]: shutdown_action_hook()
#16 {main}
```

## Expected Behaviour

No error should occur in PHP 8.

## Steps to reproduce

(Unknown)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version: 8
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
Seems the issue lies within `get_option()` unserializing the cached response before returning it. I think checking if the `$cached_response` is a string before attempting to unserialize it would be sufficient then.

**Comment by westonruter** [comment]
Fix verified by user on WordPress.org! https://wordpress.org/support/topic/amp-plugins-not-working-using-php8/#post-14732454
