### ISSUE TITLE
`<meta>` tags in post content not properly recognized

### ISSUE THREAD

**Issue by swissspidy** [Automattic/amp-wp#6507]
## Bug Description

On my personal site I am using the Twenty Nineteen and a few common plugins like Jetpack, Site Kit, AMP, Polylang, Yoast SEO, etc.

Whenever I create a new post, the AMP plugin's validation tool tells me about some duplicate `<meta charset="UTF-8">` tags that it gladly removed for me.

However, I don't know why there would be two such tags. Especially since the Twenty Nineteen theme is supported natively by the plugin.

Unfortunately there is no source stack information, so I have no idea where this seemingly duplicate tag is even coming from.

## Expected Behaviour

The AMP plugin should just remove those duplicate tags. On a simple install with the Twenty Nineteen theme I don't expect any entries in the validation manager.

## Screenshots

![Screenshot 2021-08-03 at 18 07 12](https://user-images.githubusercontent.com/841956/128049496-cabbcfae-8beb-4a90-8e7e-452eed5c440f.png)

## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable): 11.1.0
 - AMP plugin template mode: Standard
 - PHP version:
 - OS: maCOS
 - Browser: [e.g. chrome, safari] Chrome
 - Device: [e.g. iPhone6] MacBook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Interesting. If you switch to Transitional mode, do you see duplicated `meta[charset]` tags in the non-AMP version? 

Also, could you try the Site Health Troubleshooting mode? If you have the theme active and AMP active alone in Troubleshooting mode, does the error still happen? If not, could you then re-enable each plugin in Troubleshooting mode and re-check AMP validation to see at what point the duplicate tag error occurs?

Personally I haven't been able to reproduce this issue in Twenty Nineteen.

**Comment by swissspidy** [comment]
Wow, I think I found the issue 🤦 

I did some more testing and realized that this was only happening with this one draft post I was writing.

Then I turned on Transitional mode and looked for the duplicate tag in that post, only to find that this meta tag was somehow in the middle of my content:

![Screenshot 2021-08-03 at 19 18 10](https://user-images.githubusercontent.com/841956/128058434-ae23a7af-ca11-440d-b6ae-a2e90170156f.png)

![Screenshot 2021-08-03 at 19 19 16](https://user-images.githubusercontent.com/841956/128058576-5a3b200f-9e4a-4f55-b3a6-f68c02a07e8d.png)

No idea how this ended up there, nor why Gutenberg isn't removing or flagging it.

Plus, somehow the AMP plugin isn't detecting that it's actually part of my post content:

![Screenshot 2021-08-03 at 19 20 56](https://user-images.githubusercontent.com/841956/128058785-646d53d9-78e2-4462-a6c5-7748413732f5.png)

I think if that were the case I would have found this sooner 😅 

So _that_ seems like a possible bug?

**Comment by westonruter** [comment]
This is an interesting case. The reason why the source attribution isn't working is because the meta sanitizer is moving `meta` tags up to the `head`:

https://github.com/ampproject/amp-wp/blob/2f929028d2506bc048439f698bb0e54d63e7b414/includes/sanitizers/class-amp-meta-sanitizer.php#L117-L154

When the tags are moved, they lose their source stack comments so that's why they show up without attribution. 

If I try patching the plugin to only move the the first `charset`:

```diff
diff --git a/includes/sanitizers/class-amp-meta-sanitizer.php b/includes/sanitizers/class-amp-meta-sanitizer.php
index 3e1e7db93..6c1f36525 100644
--- a/includes/sanitizers/class-amp-meta-sanitizer.php
+++ b/includes/sanitizers/class-amp-meta-sanitizer.php
@@ -130,7 +130,9 @@ public function sanitize() {
 			 * @var DOMElement $meta_element
 			 */
 			if ( $meta_element->hasAttribute( Attribute::CHARSET ) ) {
-				$this->meta_tags[ self::TAG_CHARSET ][] = $meta_element->parentNode->removeChild( $meta_element );
+				if ( empty( $this->meta_tags[ self::TAG_CHARSET ] ) ) {
+					$this->meta_tags[ self::TAG_CHARSET ][] = $meta_element->parentNode->removeChild( $meta_element );
+				}
 			} elseif ( $meta_element->hasAttribute( Attribute::HTTP_EQUIV ) ) {
 				$this->meta_tags[ self::TAG_HTTP_EQUIV ][] = $meta_element->parentNode->removeChild( $meta_element );
 			} elseif ( Attribute::VIEWPORT === $meta_element->getAttribute( Attribute::NAME ) ) {
``` 

Then I see the `meta` tag as coming from the Custom HTML block:

> ![image](https://user-images.githubusercontent.com/134745/128059989-b4db16e2-c8a7-4750-bcec-ce449ffceea5.png)
 
So this could be a solution. Another solution could be to limit moving around `meta` tags that are in the `head` alone.

Or the `meta` tag optimization could be deferred until after sanitization entirely, such as in the Optimizer. This would probably be the best and would be the direction we're going in anyway.
