### ISSUE TITLE
AMP_Img_Sanitizer, stressful query on wp_postmeta

### ISSUE THREAD

**Issue by DrLightman** [Automattic/amp-wp#651]
Just to let you know that my database suffers a bit with this kind of query that it seems related to AMP_Img_Sanitizer:

`SELECT post_id FROM wp_postmeta WHERE meta_key = '_wp_attached_file' AND meta_value = '2001/01/foo.jpg' `

These queries are  frequent and take about half second on a 4mil rows table when my site is not on heavy traffic.

Right now I've disabled it with:

```php
function amp_no_extract_image_dimensions()
{
    remove_filter('amp_extract_image_dimensions', array('AMP_Image_Dimension_Extractor', 'extract_from_attachment_metadata'));
    remove_filter('amp_extract_image_dimensions', array('AMP_Image_Dimension_Extractor', 'extract_by_downloading_image'));
}
add_action('amp_extract_image_dimensions_callbacks_registered', 'amp_no_extract_image_dimensions');
```

Is this the right way to do it and without any bad consequence in your opinion?

**Comment by mjangda** [comment]
This was fixed as part of https://github.com/Automattic/amp-wp/pull/480
