### ISSUE TITLE
Plugin fails to render with NginX

### ISSUE THREAD

**Issue by kellyho67** [Automattic/amp-wp#652]
Apache seems to work fine.. NginX does not.. assume this is a problem with some config in my nginx but couldn't find any examples of making this work with nginx.

**Comment by mjangda** [comment]
The plugin runs fine on WordPress.com and many other hosts that use nginx. It's likely something specific with your config, but it's hard to pinpoint what exactly without seeing it.

**Comment by kellyho67** [comment]
It just gives a 500, no errors logged.

I assume it’s dealing with a rewrite issue not supported in the NginX config.. Apache works fine on the same site.

**Comment by mjangda** [comment]
There's probably a fatal error happening somewhere. Your PHP error log may have details.

**Comment by amedina** [comment]
Closing for now; feel free to re-open if you find the error again.

**Comment by rajuginne** [comment]
i am getting this problem how to fix

**Comment by kellyho67** [comment]
Ok I have solved this.. I went into the database and remove all the config options for this plugin.. I then was able to re-enable it and re-enter the settings.

It may be a good idea for this plugin to log errors to the wordpress log file when debug it turned on.

Kelly
