### ISSUE TITLE
AMP Block validation fails on widget screen

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6521]
## Bug Description

The Block based widgets are introduced in WordPress 5.8, The AMP plugins block validation runs on the widget editor which requires post ID and post type, creating 400 and 404 errors.

Also, The widget script adds PHP Notice for enqueuing script correctly.
`
Notice: wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.) in /srv/www/plyaground/public_html/wp-includes/functions.php on line 5535
`

## Expected Behaviour

The block-based widgets should validate without any errors or notice.

## Steps to reproduce

1. Go to Appearance -> Widgets
2. Open Browser Debug Tool -> Console Tab

## Screenshots

![image](https://user-images.githubusercontent.com/1132541/128739912-0ab36116-daf6-48ab-8f3e-ca05a4c222d8.png)

## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Transional mode
 - PHP version: 7.4
 - OS: Mac OS
 - Browser: All
 - Device: All

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
@milindmore22 The fix was just cherry-picked onto the 2.1 branch. Would you verify the fix for 2.1.4?

**Comment by milindmore22** [comment]
@westonruter Looks fine, one question can you please confirm if skipped block validation for widgets?

**Comment by westonruter** [comment]
@milindmore22 Do you mean the `amp-block-validation.css` and `amp-block-validation.js` assets? Yes, these are now omitted from the Widgets screen. The only AMP assets enqueued on the Widgets screen are `amp-validation-counts.css` and `amp-validation-counts.js` which are not for block validation but for lazily-populating the admin menu with validation counts.

**Comment by milindmore22** [comment]
@westonruter ok got it, tested seems working fine.

**Comment by westonruter** [comment]
**QA Passed**

Before on 2.1.3 there was a notice on the Widgets screen:

![image](https://user-images.githubusercontent.com/134745/131414549-7b5675ca-631d-45b7-9c2a-163f9b9c8020.png)

This goes away when switching to 2.1.4-alpha:

![image](https://user-images.githubusercontent.com/134745/131414605-313076e0-a9ef-4265-ad08-00ffad9c1c77.png)

Please note that if you activate Jetpack then the notice comes back. This is due to a bug in Jetpack and not the AMP plugin. See https://github.com/Automattic/jetpack/issues/20357.
