### ISSUE TITLE
AMP Validation issue in Search Console

### ISSUE THREAD

**Issue by wpgaurav** [Automattic/amp-wp#6535]
Google is showing AMP validation issues on almost all of my AMP pages. 

Looks like it has something to do with Gravatar images.

`<img alt class=i-amphtml-intrinsic-sizer height=auto src="data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjkxIiB3aWR0aD0iNTIwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIvPg==" width=100%></i-amphtml-sizer><img alt="Gaurav Tiwari" class="i-amphtml-fill-content i-amphtml-replaced-content" decoding=async loading=lazy src=https://gauravtiwari-org.cdn.ampproject.org/i/s/gauravtiwari.org/wp-content/uploads/2021/04/logo-520-dark.png srcset="https://gauravtiwari-org.cdn.ampproject.org/ii/w560/s/gauravtiwari.org/wp-content/uploads/2021/04/logo-520-dark.png 560w, https://gauravtiwari-org.cdn.ampproject.org/ii/w1200/s/gauravtiwari.org/wp-content/uploads/2021/04/logo-520-dark.png 1200w"></amp-img></a>`

First error.

**Comment by wpgaurav** [comment]
I cannot seem to find this code on view-source: page.

**Comment by westonruter** [comment]
Please share one of the URLs that has the issue reported for it.

**Comment by wpgaurav** [comment]
Hi,
Sorry for the delay. https://gauravtiwari.org/pass-core-web-vitals-test/?amp=1 

Please check on this

**Comment by wpgaurav** [comment]
Here's the total source code that Search console sees: https://gist.github.com/wpgaurav/d14c648bac2421d93486afdd9ceca9a5

**Comment by westonruter** [comment]
You appear to have an optimization plugin or some other optimization layer which is injecting `width="100%"` and `height="auto"` into these `img` tags.

The tag generated by the AMP Optimizer in the AMP plugin is as follows:

```html
<img alt="" aria-hidden="true" class="i-amphtml-intrinsic-sizer" role="presentation" src="data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjMyIiB3aWR0aD0iMzIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIi8+">
```

@milindmore22 can provide further assistance if you can't identify where those attributes are coming from.

**Comment by wpgaurav** [comment]
Oh yeah. It was a plugin that adds height and width to all images. Rectified.

**Comment by westonruter** [comment]
@wpgaurav Which plugin was it? Ideally the plugin would be updated to not add attributes to `img` elements that have a `data:` URL as their `src` so others don't have this issue in the future.
