### ISSUE TITLE
Broken “Re-enable transient caching” button for “Transient caching of parsed stylesheets is disabled” site health test

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6549]
## Bug Description

The Site Health test for “Transient caching of parsed stylesheets is disabled” has a “Re-enable transient caching” button that is supposed to dismiss the site health test, but as can be seen here there is something wrong with the button. The styling seems to be missing:

![image](https://user-images.githubusercontent.com/134745/130157293-61334965-60b0-4a9a-b0bd-b2035216c733.png)

Also, clicking the button has no effect. So the JS is also not being enqueued on this page.

It seems the problem is that I currently have the “Health Check & Troubleshooting” plugin active and so I'm accessing the page via `/wp-admin/tools.php?page=health-check`. 

But when that plugin is deactivated, then the Site Health page is located at `/wp-admin/site-health.php` and here I can see the Site Health test as expected:

![image](https://user-images.githubusercontent.com/134745/130157675-50bf45fc-f781-4891-aed8-6f51de258e12.png)

Nevertheless, even though the styling looks right, the button still doesn't do anything. So a required JS file is missing.

## Expected Behaviour

The stylesheet transient caching site health test should work properly when the “Health Check & Troubleshooting” plugin is active or deactivated.

## Steps to reproduce

1. Manually disable stylesheet transient caching by running WP-CLI `wp shell` and execute `AMP_Options_Manager::update_option('amp_css_transient_monitor_disable_caching', true)`
2. Go to the Site Health screen (with and without the “Health Check & Troubleshooting” plugin active)
3. Try to re-enable transient caching by clicking the button.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment]
The JS should be enqueued by the `ReenableCssTransientCachingAjaxAction` service, but that doesn't seem to be the case.

**Comment by westonruter** [comment]
**QA Passed**

The button in the test appears with proper styling and clicking the button takes the expected action:

![image](https://user-images.githubusercontent.com/134745/131416010-a9648ee8-e8f3-4384-b7b0-77c56d9b3f17.png)

![image](https://user-images.githubusercontent.com/134745/131416030-ed021367-1960-4525-8f93-dc81cca781d6.png)
