### ISSUE TITLE
Hamburger menu redirecting after click to homepage

### ISSUE THREAD

**Issue by Verticalmag** [Automattic/amp-wp#656]
When clicking Hamburger menu, page is redirected to homepage.  

Expected:
Menu to stay open and not redirect to homepage of website.

Testing in Chrome / Dev mobile view using amp review.

Version 0.9.44 and WP 4.7.3

**Comment by amedina** [comment]
Could you provide a link to reproduce the behavior?

**Comment by amedina** [comment]
Closing for now. Please reopen with more detailed information if this is still an issue.
