### ISSUE TITLE
Using this AMP plugin. Using ampUrls:batchGet function of the AMP API, we notice a strange behavior

### ISSUE THREAD

**Issue by DarthJahus** [Automattic/amp-wp#6564]
## Bug Description

When we pass some webpage's URL to `ampUrls:batchGet`, this is what we get as answer:

```json
{
  "urlErrors": [
    {
      "errorCode": "NO_AMP_URL",
      "errorMessage": "No AMP URL for the request URL.",
      "originalUrl": "https://example.com/2021/08/25/some-article/"
    }
  ]
}
```

Note that the webpage does have the `<link rel="amphtml" href="//example.com/2021/08/25/some-article/amp/">` tag.

However, if we add `/amp/` to the link before calling the API, the result is returned successfully.

## Expected Behaviour

Return cached AMP url correctly.

## Steps to reproduce

Can be reproduced on this site, with any article page: [example](https://observalgerie.com/2021/08/25/politique/maroc-reagit-decision-algerie-rompre-relations-diplomatiques/).

We notice that other websites (don't know which AMP plugin they are using), produce the expected result without adding `/amp/` to the URL. Their template doesn't look like using full-amp, though. [Example](https://www.tsa-algerie.com/lalgerie-rompt-ses-relations-avec-le-maroc/).

## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.3
 - Gutenberg plugin version (if applicable): 
 - AMP plugin template mode: Transitional, with Reco Child theme
 - PHP version: 7.4.x
 - OS: Linux 5.11.0-22-generic x86_64 / Apache 2

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Your `amphtml` link lacks the URL scheme (either `http:` or `https:`):

```html
<link rel="amphtml" href="//observalgerie.com/2021/08/25/politique/maroc-reagit-decision-algerie-rompre-relations-diplomatiques/amp/">
```

I believe this is what is causing the AMP URL to not be recognized. 

It's not showing up in the AMP Validator extension either. See [source code](https://github.com/ampproject/amphtml/blob/6b5c95112e73b0e1322d9d7503ec7c787ebf3262/validator/js/chromeextension/content_script.js#L46-L49) in Chrome extension:

```js
  // URL must begin with http:// or https://
  const validUrlPrefixRe = /^[\s\xa0]*https?:\/\//;
```

So you'll need to prevent the URL scheme from being removed from the `amphtml` link.

**Comment by DarthJahus** [comment]
@westonruter, your answer has helped a lot. I have found what was changing scheme from `https://` to `//`. So I'm leaving this comment in case someone needs it. In this case, it was "Protocol relative" enabled on CloudFlare by WPRocket plugin.
