### ISSUE TITLE
Custom post type amp

### ISSUE THREAD

**Issue by kingjonats** [Automattic/amp-wp#657]
By default, the plugin only creates AMP content for posts. You can add support for other post_types using the post_type parameter used when registering the custom post type (assume our post_type is xyz-review):

add_action( 'amp_init', 'xyz_amp_add_review_cpt' );
function xyz_amp_add_review_cpt() {
    add_post_type_support( 'xyz-review', AMP_QUERY_VAR );
}

I was using the above code for my custom post type for AMP, just wondering if I want multiple custom post to be added? How can I add? 

Thanks

**Comment by iDoka** [comment]
Similar troubles: how to supports page type by plugin?

Simple adding in function amp_init() doesnt work:
```
        add_post_type_support( 'post', AMP_QUERY_VAR );
        add_post_type_support( 'page', AMP_QUERY_VAR );

```

**Comment by matif78** [comment]
Hi,
I am trying to add custom post type but nothing is showing when i add /amp

Can you please tell me where i am wrong.

// Custom Post Type AMP //

add_action( 'amp_init', 'xyz_amp_add_review_cpt' );
function xyz_amp_add_review_cpt() {
	add_post_type_support( 'betting-site', AMP_QUERY_VAR );
}
add_filter( 'amp_post_template_file', 'xyz_amp_set_review_template', 10, 3 );

function xyz_amp_set_review_template( $file, $type, $post ) {
	if ( 'single' === $type && 'betting-site' === $post->post_type ) {
		$file = dirname( __FILE__ ) . '/single-betting-site.php';
	}
	return $file;
}

**Comment by amedina** [comment]
We are working to support pages and other types of post types. Stay tuned. In the mean time, the instructions in the README for adding support for custom post types should work (https://github.com/Automattic/amp-wp#custom-post-type-support)
