### ISSUE TITLE
Videos with unknown dimensions appear as stretched

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6571]
## Bug Description

Given a post containing a Video block with an external source:

```html
<!-- wp:video {"autoplay":true,"loop":true,"muted":false,"src":"https://blog.amp.dev/wp-content/uploads/2021/08/ezgif.com-gif-maker-13.mp4"} -->
<figure class="wp-block-video"><video autoplay controls loop src="https://blog.amp.dev/wp-content/uploads/2021/08/ezgif.com-gif-maker-13.mp4"></video></figure>
<!-- /wp:video -->
```

Actual | Expected
--------|----------
![image](https://user-images.githubusercontent.com/134745/131008317-02837686-185f-4300-9c00-8c34126f116f.png) | ![image](https://user-images.githubusercontent.com/134745/131009868-4bf2e02a-2ab3-47c2-86a1-c360e8c58fae.png)

Notice the unexpected stretching.

The HTML being generated is:

```html
<amp-video autoplay="" controls="" loop="" src="https://blog.amp.dev/wp-content/uploads/2021/08/ezgif.com-gif-maker-13.mp4" height="400" layout="fixed-height" width="auto" class="i-amphtml-layout-fixed-height i-amphtml-layout-size-defined" style="height:400px" i-amphtml-layout="fixed-height">
	<a href="https://blog.amp.dev/wp-content/uploads/2021/08/ezgif.com-gif-maker-13.mp4" fallback="">https://blog.amp.dev/wp-content/uploads/2021/08/ezgif.com-gif-maker-13.mp4</a>
	<noscript>
		<video autoplay controls loop src="https://blog.amp.dev/wp-content/uploads/2021/08/ezgif.com-gif-maker-13.mp4"></video>
	</noscript>
</amp-video>
```

Note the `height=400` and the `layout=fixed-height`. These are supplied because the video is external and we don't know the internal dimensions. If the video had been locally-uploaded, then the output would be as follows:

```html
<amp-video width="244" height="438" controls="" src="https://wordpressdev.lndo.site/content/uploads/2021/08/northern-sky-constellations.mp4" layout="responsive" class="i-amphtml-layout-responsive i-amphtml-layout-size-defined" i-amphtml-layout="responsive">
	<i-amphtml-sizer slot="i-amphtml-svc" style="display:block;padding-top:179.5082%"></i-amphtml-sizer>
	<a href="https://wordpressdev.lndo.site/content/uploads/2021/08/northern-sky-constellations.mp4" fallback="">https://wordpressdev.lndo.site/content/uploads/2021/08/northern-sky-constellations.mp4</a>
	<noscript>
		<video width="244" height="438" controls src="https://wordpressdev.lndo.site/content/uploads/2021/08/northern-sky-constellations.mp4"></video>
	</noscript>
</amp-video>
```

Note here the `responsive` layout with the actual dimensions of the video supplied as the `width`/`height`.

In any case, the problem is that when the dimensions aren't correct the video is appearing as stretched. This appears to be a regression introduced by https://github.com/ampproject/amp-wp/pull/5927, specifically here:

https://github.com/ampproject/amp-wp/blob/ab5a1e77f8b133e60880c51845b723cc059917e9/assets/css/src/amp-default.css#L102-L105

Either that was wrong, or we need to add the `amp-wp-unknown-size` class name to the `amp-video` as we're doing for `amp-img` so that this style rule applies:

https://github.com/ampproject/amp-wp/blob/ab5a1e77f8b133e60880c51845b723cc059917e9/assets/css/src/amp-default.css#L7-L11

The `object-it:inherit` is causing a `fill` value to be applied rather than `contain` from the user agent stylesheet:

![image](https://user-images.githubusercontent.com/134745/131010151-191ebb4d-67e9-460a-8852-cf060936f08b.png)

It's not clear to me why `fill` is showing up here 😕 

## Expected Behaviour

Videos should not appear as stretched when their dimensions are not available.

## Steps to reproduce

Add the first video block in the description to a post and view as AMP.

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> It's not clear to me why `fill` is showing up here 😕

Apparently this is just how browsers work, as I get the same thing in a standalone example: https://codepen.io/westonruter/pen/wveadmy

What's strange is that `img` with `object-fit:inherit` is showing `fill` but _without_ any user agent stylesheet of `contain`, but `video` does have this user agent stylesheet:

`img` | `video`
-------|--------
![image](https://user-images.githubusercontent.com/134745/131018728-ce0f61ca-753b-45e0-8c70-5d2e788a2478.png) | ![image](https://user-images.githubusercontent.com/134745/131018800-b4145c89-4761-4d3c-aecc-cdf128c7108f.png)

I guess `inherit` doesn't consider the user agent stylesheet?

**Comment by pierlon** [comment]
According to the CSS Images Module Level 3 spec the [`object-fit` property](https://drafts.csswg.org/css-images/#the-object-fit) does not inherit its value and its initial value is `fill`:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/16200219/131187753-8c0bdade-aeef-4de8-8917-711f00deedc1.png">

**Comment by pierlon** [comment]
So as expected, If I omit the `object-fit: inherit;` rule we supply it does use the user-agent rule:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/16200219/131188141-7a6979c2-ea75-4a31-aaa8-524010dfa24e.png">

**Comment by westonruter** [comment]
**QA Passed**

Adding an external video results in no stretching:

![image](https://user-images.githubusercontent.com/134745/131417047-cc5f0d5b-f713-4d54-a4fd-13cc5fc7594a.png)

The `video` is inheriting the `object-fit` from the parent:

![image](https://user-images.githubusercontent.com/134745/131417118-ce30922a-45d7-474b-81bc-0b0e2f5acaff.png)

And the parent has `object-fit:contain`:

![image](https://user-images.githubusercontent.com/134745/131417143-0ad00e62-a6ba-4a81-b59c-d12bfb765a09.png)

Testing another video from the media library which has dimensions hsa `object-fit:fill` as expected.
