### ISSUE TITLE
AMP cache and Form IDs issues

### ISSUE THREAD

**Issue by fthead9** [Automattic/amp-wp#6598]
## Bug Description

We have a form block. When that block is rendered it generates a unique
temporary key that we include in the form as a hidden field in the form
with "xhrid" as the field name. This ID is used to store the form data
in a Wordpress transient that expires after X minutes (5 default). We
also use it as a prefix for each form field's name. When the form is
submitted through AJAX the ID is used to retrieve the transient and
process the form.

This all works fine until early August. The problem we now face is that
the form cannot be processed because the ID on the cached page has
expired. 

## Expected Behaviour

We have to be able to include, pass and process a unique
temporary key in our forms, not just for processing purposes but also
for protection from those who would abuse the form.

## Steps to reproduce

We've tested on WordPress sites using the official AMP plugin as well as older versions of our framework that didn't use the plugin. Both broke sometime in August. You can see the AMP plugin issue here: 

1. Go to https://charliefoundation.org/
2. Scroll down to the bottom of the page and fill in the Sign Up For Our Newsletter form
3. Error message: This form session has timed out, please refresh your browser and try again.

Non-plugin AMP site: 
1. Go to https://dyernews.com/
2. In the left column of the page fill in the Subscribe for Latest News form
3. Error message: This form session has timed out, please refresh your browser and try again.
## Additional context

 - WordPress version: 5.8
 - Plugin version: 2.1.4
 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> This all works fine until early August. The problem we now face is that
> the form cannot be processed because the ID on the cached page has
> expired.

The AMP plugin does not cache the page output. Perhaps you have some other caching plugin that is caching blocks?
