### ISSUE TITLE
Structured data broken by `amphtml` link relation in AMP-to-AMP linking

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6599]
## Bug Description

In a recent [support topic](https://wordpress.org/support/topic/error-in-required-structured-data-element-51/), we found out that BreadCrumbList schema (RDFa) doesn't allow `rel="amphtml"` attributes and marks structured data as invalid, As per discussion on slack Weston suggested we don't need it.

Example HTML Snippet : 
```html
<div class="breadcrumb" typeof="BreadcrumbList" vocab="https://schema.org/">
	<span property="itemListElement" typeof="ListItem">
	    <a property="item" typeof="WebPage" title="Go to Visitor Guard®." href="https://www.example.com?amp" class="home" rel="amphtml">
	        <span property="name">
	            Home
	        </span>
	   </a>
	<meta property="position" content="1">
	</span>
	<span class="post post-page current-item">
	    The Page Title
	 </span>
</div>
```
Tests : 

1. [Invalid Test ](https://search.google.com/test/rich-results?id=cQnZu_lCE6bMUgEJ7JsMKA) 
2. [Valid Test ](https://search.google.com/test/rich-results?id=nlyaLWLFGcoWt3uIefvUZg)

## Expected Behaviour

The page links should be served without `"rel="amphtml"` attributes.

## Steps to reproduce

1. Install and activate BreadCrumb Navxt Plugin
2. Add Breadcrumb to your site
3. Check the Structured Data on https://search.google.com/test/rich-results

## Additional context

 - WordPress version: 5.8.1
 - Plugin version: 2.1.4
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Transional Mode / Reader Mode
 - PHP version: 7.4
 - OS: Mac
 - Browser: chrome, safari
 - Device: Macbook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
I've made an inquiry as to whether `rel` should indeed be invalid here.

**Comment by westonruter** [comment]
OK, we should indeed omit the `amphtml` relation. We can discontinue adding relations altogether. They aren't being used anwayway, so they're just extra decoration.

**Comment by milindmore22** [comment]
**QA Passed**

**Input**
```html
<a rel="noreferrer noopener" href="https://amp-local.test/hello-world/" data-type="post" data-id="1" target="_blank">Internal Link to AMP Page – Should not have amphtml</a>
```
**Output**
```html
<a rel="noreferrer noopener" href="https://amp-local.test/hello-world/amp/" data-type="post" data-id="1" target="_blank">Internal Link to AMP Page – Should not have amphtml</a>
```

| Input | amphtml | nonamphtml | Link Type |
| ----------- | ----------- | ----------- | ----------- |
| Internal Link to AMP page | Removed | N/A | Link to AMP page |
| Internal Link to non-AMP Page | Removed | N/A | Link to AMP Page ( redirects to non-AMP ) |
| Internal Link with noamphtml attribute | Removed | Present | Link with nonamp=mobile parameter |
| External Link | Removed | N/A | No change |
| External Link with noamphtml attribute | Removed | Present | No change |
