### ISSUE TITLE
GLOMEX Videos not playing on AMP

### ISSUE THREAD

**Issue by Yink0** [Automattic/amp-wp#6601]
## Bug Description

I use Glomex.com videos on my website, but when it comes to AMP page, the video is not working. I have blank (no dimensions video)

## Expected Behaviour

It should be able to AMP page  

## Steps to reproduce

1. Go to "https://www.sportime.gr/panathinaikos/giovanovits-echoume-polla-akomi-na-kanoume-os-omada". The video works
2.  On "https://www.sportime.gr/panathinaikos/giovanovits-echoume-polla-akomi-na-kanoume-os-omada/amp/" the video doesn't

## Additional context

 - WordPress version: 5.8.1
 - Plugin version: 2.1.4
 - Gutenberg plugin version (if applicable): -
 - AMP plugin template mode: custom
 - PHP version: 7.4
 - OS: Linux
 - Browser: All
 - Device: All

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by milindmore22** [comment]
Hello @Yink0 

As per [Glomex documentation](https://docs.glomex.com/publisher/video-player-integration/amp-code/), you can embed glomex player on AMP pages using the amp-iframe component, so I will recommend using [glomex iframe embed code](https://docs.glomex.com/publisher/video-player-integration/iframe-code/) so it will work on both AMP and non-AMP pages.

eg: 
```html 
<iframe allow="fullscreen; accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; monetization; payment" allowfullscreen referrerpolicy="unsafe-url" src="https://player.glomex.com/integration/1/iframe-player.html?integrationId=[INTEGRATION_ID]&playlistId=[PLAYLIST_ID]"></iframe>
```
The AMP plugin will convert it on the AMP pages as 

 ```html 
 <amp-iframe allow="fullscreen; accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; monetization; payment" allowfullscreen="" referrerpolicy="unsafe-url" src="https://player.glomex.com/integration/1/iframe-player.html?integrationId=%5BINTEGRATION_ID%5D&amp;playlistId=%5BPLAYLIST_ID%5D" height="400" layout="fixed-height" width="auto" sandbox="allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-scripts allow-top-navigation-by-user-activation" class="i-amphtml-layout-fixed-height i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout" style="height: 400px; --loader-delay-offset:103ms !important;" i-amphtml-layout="fixed-height" frameborder="0"></amp-iframe>
 ```
 
use your `INTEGRATION_ID` and `PLAYLIST_ID` in above examples.
 
If you have any further questions feel free to contact us on [WordPress support forums ](https://wordpress.org/support/plugin/amp/#new-topic-0)

**Comment by westonruter** [comment]
I suppose they don't support [`amp-video-iframe`](https://amp.dev/documentation/components/amp-video-iframe/).
