### ISSUE TITLE
Tag named amp can not be visit

### ISSUE THREAD

**Issue by Sorata** [Automattic/amp-wp#6602]
## Bug Description

If you add a Tag name amp, you can not visit by http://example.com/tag/amp, when you visit it you will be redirect to http://example.com/tag/.

## Expected Behaviour

It look like happened by \amp\src\PairedRouting.php redirect_extraneous_paired_endpoint function.

## Steps to reproduce

1. Add Tag named amp
2. Add post with the amp tag.
3. visit tag link
4. return 404

## Additional context

 - WordPress version:5.8.1
 - Plugin version:2.1.4
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode: Reader AMP Legacy
 - PHP version:8.0.10
 - OS: CentOS 7.9
 - Browser: [e.g. chrome, safari] Firefox
 - Device: [e.g. iPhone6] Windows 10 PC

## Demo
Tag:
https://shipengliang.com/tag/amp

Post with Tag amp:
https://shipengliang.com/software-exp/wordpress-amp%e6%8f%92%e4%bb%b6-featured-image%e5%92%8c%e6%96%87%e4%b8%ad%e5%9b%be%e7%89%87%e9%87%8d%e5%a4%8d%e9%97%ae%e9%a2%98%e8%a7%a3%e5%86%b3%e6%96%b9%e6%a1%88.html

## Changelog entry

*

**Comment by milindmore22** [comment]
@Sorata 

Creating tag with slug `amp` will create conflict as the `amp` is a reserved slug for the AMP endpoint to avoid that it's safely redirected to a non-AMP page. 

You will see a warning on the AMP settings section for AMP Paired URL structure

![image](https://user-images.githubusercontent.com/1132541/133088333-5a8db565-7974-485a-8dd7-41b0a7e973d9.png)


the easiest way to fix this is to change your tag slug to  `accelerated-mobile-pages`

If you insist on keeping the `amp` slug for tags, feel free to check our documentation for [customizing the AMP endpoint](https://amp-wp.org/documentation/getting-started/paired-url-structures/#customizing-amp-endpoints)  and convert `/amp/` endpoint to `/mobile/`, `/lite/` etc
