### ISSUE TITLE
Advertisement

### ISSUE THREAD

**Issue by Verticalmag** [Automattic/amp-wp#661]
Is this an error or just an oversight but Advertisement section can only use adsense code?

We should be able to use custom amp code from what ever vendor and not be limited to adsense. 

https://ampbyexample.com/components/amp-ad/  

<a target="_blank"
  href="https://ampbyexample.com/amp_for_ads_a4a/a4a_banner_ad/">
  <amp-img src="https://ampbyexample.com/img/amp-300x250.jpg"
    width="300"
    height="250"
    alt="a4a image"></amp-img>
</a> 

Is there a way around this?

Even the Facebook Instant article plugin supports code, iframes or facebooks own stream (like adsense)

Anyone else need the option for custom code?

**Comment by amedina** [comment]
Closing this as not an issue with the plugin; Ads support to be provided by 3P plugins.
