### ISSUE TITLE
AMP.printstate returning undefined

### ISSUE THREAD

**Issue by joblog** [Automattic/amp-wp#6612]
## Bug Description

AMP.printState() is no longer working on a site using official AMP plugin for WordPress 

## Expected Behaviour
With #development=1 appended to the url 
AMP.printState() typed in console returns AMP state

## Steps to reproduce

AMP.printState() typed in console returns undefined

## Additional context
My pages are valid amp
Entering AMP.setLogLevel(5) in console makes no difference

This is a continuation of the amphtml issue 35655
https://github.com/ampproject/amphtml/issues/35655
Solution there is to update to version > 2107302322000
Problem identified here 
https://github.com/ampproject/amphtml/pull/35690 

I don't see any mention of the issue here
https://github.com/ampproject/amp-wp/releases
Maybe it will be fixed in plugin version 2.2
In the meantime can you advise on how I can update/fix the issue so I can observe AMP.state
Thanks

 - WordPress version:5.8.1
 - Plugin version: 2.14
 - AMP plugin template mode:Standard
 - PHP version:7.2.34
 - Browser: firefox chrome
 - Device: any

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
Closing per https://github.com/ampproject/amphtml/issues/35655#issuecomment-921882835.
