### ISSUE TITLE
noopener on <amp-twitter> placeholder

### ISSUE THREAD

**Issue by kswro** [Automattic/amp-wp#6616]
## Bug Description

Does AMP-WP automatically add rel="noopener" or rel="noreferrer" to links with target="_blank" in the `<amp-twitter>` blockquote placeholder? Since it's tied to the `<amp>` tag I think AMP-WP does.

If so, it looks like AMP-WP missed adding the rel noopener/noreferrer property on links other than twitter.com (perhaps?). Please see the screenshot below.

![amp-twitter](https://user-images.githubusercontent.com/37024737/133887012-e642f28d-8ef5-4cd4-9f1d-e1afd39b16c4.jpg)

## Expected Behaviour

AMP-WP adds the rel="noopener" or rel="noreferrer" property to the link.

## Steps to reproduce

Embed this status https://twitter.com/samsungID/status/1439152219543285761 and note a number of links as I showed in the previous screenshot.

## Additional context

 - WordPress version: 5.8.1
 - Plugin version: 2.1.4
 - AMP plugin template mode: standard/native
 - PHP version: 7.4.23
 - OS: Debian 11
 - Browser: Latest chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
When I embed a Tweet, I get the following:

```html
<amp-twitter width="auto" height="197" layout="fixed-height" data-tweetid="1439152219543285761" class="twitter-tweet i-amphtml-layout-fixed-height i-amphtml-layout-size-defined" data-width="550" data-dnt="true" style="height:197px" i-amphtml-layout="fixed-height">
	<button overflow type="button">See more</button>
	<blockquote class="twitter-tweet" data-width="550" data-dnt="true" placeholder=""><p lang="en" dir="ltr">Missed the
		awesome <a href="https://twitter.com/hashtag/GalaxyA52s5G?src=hash&amp;ref_src=twsrc%5Etfw">#GalaxyA52s5G</a>
		pre-order?<br><br>Set up your reminder coz
		<a href="https://twitter.com/hashtag/GalaxyA52s5G?src=hash&amp;ref_src=twsrc%5Etfw">#GalaxyA52s5G</a> will be
		available on September 20th 2021 with more awesome deals at <a href="https://t.co/iuF27VUWLx">https://t.co/iuF27VUWLx</a>
		<a href="https://t.co/9QRrNKb4Hy">pic.twitter.com/9QRrNKb4Hy</a></p>— Samsung Indonesia (@samsungID)
		<a href="https://twitter.com/samsungID/status/1439152219543285761?ref_src=twsrc%5Etfw">September 18, 2021</a>
	</blockquote>
</amp-twitter>
```

On the non-AMP version, HTML is as follows:

```html
<blockquote class="twitter-tweet" data-width="550" data-dnt="true"><p lang="en" dir="ltr">Missed the awesome
	<a href="https://twitter.com/hashtag/GalaxyA52s5G?src=hash&amp;ref_src=twsrc%5Etfw">#GalaxyA52s5G</a> pre-order?<br><br>Set
	up your reminder coz <a href="https://twitter.com/hashtag/GalaxyA52s5G?src=hash&amp;ref_src=twsrc%5Etfw">#GalaxyA52s5G</a>
	will be available on September 20th 2021 with more awesome deals at <a href="https://t.co/iuF27VUWLx">https://t.co/iuF27VUWLx</a>
	<a href="https://t.co/9QRrNKb4Hy">pic.twitter.com/9QRrNKb4Hy</a></p>&mdash; Samsung Indonesia (@samsungID)
	<a href="https://twitter.com/samsungID/status/1439152219543285761?ref_src=twsrc%5Etfw">September 18, 2021</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

So you can see the `placeholder` for `amp-twitter` is copied exactly from the oEmbed response from Twitter. 

The AMP plugin doesn't add `target=_blank` to Twitter placeholders. You may have another plugin that is doing that.
