### ISSUE TITLE
Image Maps are not sanitized 

### ISSUE THREAD

**Issue by Cosrnos** [Automattic/amp-wp#663]
Posts containing the image map tag are not sanitized for the tag even though there is no amp equivalent, causing pages to not be amp compliant. It makes sense to me to remove these for AMP pages.

[Example](https://www.orwhateveryoudo.com/2015/07/strawberry-lemon-daiquiri.html/amp)

I can definitely work on a PR for this if it's something that we agree should be fixed in the plugin. Let me know if you have any thoughts on why we should leave the tags or if I should get started on the PR :)

**Comment by amedina** [comment]
Thanks for flagging this. For now the image maps should be sanitized. If you would like to submit a PR it would be great.

**Comment by amedina** [comment]
Hi @Cosrnos,

The supplied example: https://www.orwhateveryoudo.com/2015/07/strawberry-lemon-daiquiri.html/amp is validating properly: https://ampbench.appspot.com/validate?url=https%3A%2F%2Fwww.orwhateveryoudo.com%2F2015%2F07%2Fstrawberry-lemon-daiquiri.html%2Famp

Could you tell us if you are still seeing the issue on your end?
