### ISSUE TITLE
Duplicated script printed to hide admin bar in onboarding wizard

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6643]
### Bug Description

I just noticed that the we're printing the same script multiple times, including at `wp_head` and `wp_footer` and anywhere `wp_print_scripts()` is called:

![image](https://user-images.githubusercontent.com/134745/136717565-bb845391-f81c-46c2-b26a-ae8a07de683c.png)

The code in question is the following:

https://github.com/ampproject/amp-wp/blob/4547bfb2d6cd7f2699ae970a660c20d36ea192ad/includes/amp-helper-functions.php#L186-L222

Instead of the `wp_print_scripts` action we should consider the `wp_print_footer_scripts` action, or else the `wp_head` (and `amp_post_template_head`) action. Additionally, the script should be moved from a closure into a separate function.

### Expected Behaviour

The script should only be printed once.

### Plugin Version

2.1.4

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by dhaval-parekh** [comment]
✅  **QA Passed**

Below script render only once in the "completion screen" in onboarding wizard. which were rendering twice in 2.2.1

https://github.com/ampproject/amp-wp/blob/4547bfb2d6cd7f2699ae970a660c20d36ea192ad/includes/amp-helper-functions.php#L201-L218

---

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/8168027/161006633-70a73b62-0b3b-4d12-a0b2-6ff927772928.png">
