### ISSUE TITLE
 Ensure the Twenty Twenty-Two theme is AMP compatible

### ISSUE THREAD

**Issue by pierlon** [Automattic/amp-wp#6649]
### Feature Description

Development of the [Twenty-Two core theme](https://github.com/WordPress/twentytwentytwo) is now underway and is set to be released along with WP 5.9 in December. We should ensure it will be AMP compatible and also add it to the list of Reader themes.

### Acceptance Criteria

- Ensure sure the Twenty-Two theme is AMP compatible
- Add the theme as a Reader theme option

**Comment by westonruter** [comment]
Since this theme depends on full-site editing, it doesn't seem like there will be anything in the theme itself which is not AMP-compatible, as it is comprised of blocks coming from core. Therefore it's likely the majority or the work here will be to ensure that FSE is AMP-compatible.

For example: #6115 and #6319.

**Comment by westonruter** [comment]
So the good thing here is that if we can ensure AMP is FSE-compatible, then any such theme will just work.

**Comment by delawski** [comment]
**QA Not Passed**

✅ **Ensure sure the Twenty-Two theme is AMP compatible**

I've browsed a site based on WordPress 5.9 with Twenty-Two theme activated and everything seemed to be working as expected, including items like site navigation (navigation block), adding comments, and search.

There were no AMP validation errors reported.

🚫 **Add the theme as a Reader theme option**

Twenty-Two is not among Reader themes:

![AMP Onboarding Wizard ‹ amp-qa — WordPress](https://user-images.githubusercontent.com/478735/151543355-c47811e9-1fa2-4d66-8247-733e0f66e16b.png)

**Comment by westonruter** [comment]
If the only fail is the theme not being listed among the Reader themes, then great. We can easily add it. We'll just need a mobile screenshot to add to https://github.com/ampproject/amp-wp/tree/develop/assets/images/reader-themes

**Comment by delawski** [comment]
> If the only fail is the theme not being listed among the Reader themes, then great. We can easily add it. We'll just need a mobile screenshot to add to https://github.com/ampproject/amp-wp/tree/develop/assets/images/reader-themes

Thanks for the hint. I've added a Twenty Twenty-Two thumbnail to the repo and added its slug to the list of supported Reader Themes in #6870.

One unexpected thing I noticed is that the "Edit site" menu item is rendered in WP admin bar when TT2 is set as a Reader Theme:

![Screenshot 2022-01-31 at 15 56 40](https://user-images.githubusercontent.com/478735/151816507-ea972c60-f671-471c-a4da-3441f54919a4.png)

After clicking on the link, I get an error like:

![Screenshot 2022-01-31 at 16 02 02](https://user-images.githubusercontent.com/478735/151817322-2296485a-10c2-48f0-a598-9e845d51226f.png)

I think that there might be more of such little things here and there WordPress 5.9 and TT2 introduced quite a bit of changes.

**Comment by westonruter** [comment]
> After clicking on the link, I get an error like:

Do you get the same issue when the AMP plugin is deactivated?

**Comment by delawski** [comment]
> Do you get the same issue when the AMP plugin is deactivated?

No, when I select TT2 as a regular theme in Standard or Transitional mode (not as a Reader Theme), the link leads to the new site editor. In the same way, if AMP is completely deactivated, the link works as expected.

So this is only the case if TT2 is set as a Reader Theme. I guess we should probably remove this link from the admin bar if in Reader Mode. What do you think?

**Comment by westonruter** [comment]
> So this is only the case if TT2 is set as a Reader Theme. I guess we should probably remove this link from the admin bar if in Reader Mode. What do you think?

Oh yes, you're right. Humm, in that case I think we'll need to wait on adding TT2 to the list of Reader themes as we'll need to make the Site Editor accessible with the Reader theme active, in the same way we load the Reader theme when loading the AMP Customizer. Otherwise the user wouldn't be able to edit the AMP pages. It may end up being that the Site Editor can't be forced to load the Reader theme, but we'll need to do more research in that area. So I'll move the milestone to 2.3 for now. Thanks for identifying this!

**Comment by westonruter** [comment]
This is done.
