### ISSUE TITLE
Add in realtime validation with new online api 

### ISSUE THREAD

**Issue by dknecht** [Automattic/amp-wp#665]
Documentation on API
http://blog.cloudflare.com/amp-validator-api/

And example usage
http://jamesiv.es/adn/amp/2017/03/16/amp-validator-cat.html

**Comment by amedina** [comment]
Hi @dknecht, thanks for your suggestion. Will keep it in mind for our roadmap. Closing this issue for now and will reopen if there is an intent to implement.
