### ISSUE TITLE
Validate only AMP-enabled pages in Site Scan 

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#6650]
### Feature Description

A list of URLs being validated by the Site Scan feature should vary depending on the current state of the Template Mode or Supported Templates option.

---

As part of the Site Scan feature proposed in #4719 and implemented in #6610, a client-side AMP validation is performed on a set of URL.

The URLs are provided by the `ScannableURLProvider` via `ScannableURLsRestController`. They are meant to represent various types of pages so that the Site Scan gives best results.

The existing implementation of the `ScannableURLProvider` does not take the current Template Mode or Supported Template types into consideration when returning the URLs. For instance, even though in the Reader mode only the `post` and `page` templates are AMP-enabled, the provider returns other URLs like the homepage or archives.

Moreover, despite the fact that the `SiteScanContextProvider` proposed in #6610 will correctly invalidate the scan results whenever a Template Mode or Supported Template types change, it will still not refetch the scannable URLs from the REST endpoint in such a case.

**Comment by westonruter** [comment]
Note that in #6520 I have changes which will allow `ScannableURLsRestController` to return URLs for pages that are actually have AMP enabled.

**Comment by westonruter** [comment]
Also from https://github.com/ampproject/amp-wp/pull/6520#issuecomment-947932263:

> I haven't gotten the tests to run locally myself, so I'm shooting in the dark a bit. I suspect the issue is that now that `\AmpProject\AmpWP\Validation\ScannableURLProvider::get_urls()` only returns URLs on which AMP is enabled given the current template mode, if legacy Reader mode was initially selected then only singular posts will be returned among the URLs. 
> 
> @delawski So this is something else that needs to be added to #6650. In addition to re-fetching the scannable URLs for site scanning after changing the template mode, the Done screen of the Onboarding Wizard will also need to fetch the preview URLs _after_ the settings have been saved instead of exporting them up-front here:
> 
> https://github.com/ampproject/amp-wp/blob/ed75d8b1d05cd5f33946bbe4d2af4163f65a0d8d/src/Admin/OnboardingWizardSubmenuPage.php#L252

**Comment by delawski** [comment]
> Also from #6520 (comment):
>
> > I haven't gotten the tests to run locally myself, so I'm shooting in the dark a bit. I suspect the issue is that now that \AmpProject\AmpWP\Validation\ScannableURLProvider::get_urls() only returns URLs on which AMP is enabled given the current template mode, if legacy Reader mode was initially selected then only singular posts will be returned among the URLs.
> >
> > @delawski So this is something else that needs to be added to #6650. In addition to re-fetching the scannable URLs for site scanning after changing the template mode, the Done screen of the Onboarding Wizard will also need to fetch the preview URLs after the settings have been saved instead of exporting them up-front here:

As per the next [comment on #6520](https://github.com/ampproject/amp-wp/pull/6520#issuecomment-948534464), this has been already addressed in #6610 (ffe1c0e).

**Comment by westonruter** [comment]
- [ ] In Standard mode, only get the first scannable URL to preview per https://github.com/ampproject/amp-wp/pull/6520#discussion_r733722102

**Comment by westonruter** [comment]
Reopening because there is an outstanding issue not yet addressed with the merge of #6610: When legacy Reader mode is initially selected (as it currently is by default), the Site Scan in the onboarding wizard is only scanning the URLs that are available in legacy Reader mode (singular posts, pages, and attachments). In reality, since we're forcing Standard mode in the onboarding wizard's Site Scan, we should be obtaining the scannable URLs _for Standard mode_ as well. Then once the user saves the settings in the onboarding wizard, the scannable URLs should be re-fetched without any option overrides to obtain the URLs to show for the site preview on the Done screen.

**Comment by dhaval-parekh** [comment]
**QA Passed**

✅  Only the AMP pages are returning from `/wp-json/amp/v1/scannable-urls`
✅  Only the AMP page gets validated during the site scanning.
✅  After changing the template mode or supported template on the "AMP Settings" page. Page is refetching the scannable URL.
