### ISSUE TITLE
Improve theme support for navigation menu toggle

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6656]
### Bug Description

We are adding theme support for the navigation menu, but there is a wide range of elements are being used for toggle button elements eg: `div`, `a`, `span`

After adding theme support to them creates an AMP validation error of missing `tabindex` and `role` 

which can be avoided by adding those attributes in case the element is not a button in `AMP_Nav_Menu_Toggle_Sanitizer` 

```php
if ( 'button' !== $button_el->tagName ) {
	$button_el->setAttribute( 'role', 'button' );
	$button_el->setAttribute( 'tabindex', '0' ); 
}
```

The theme I was trying to add support: [Lightning](https://wordpress.org/themes/lightning/)

```php

add_theme_support(
	'amp',
	array(
		'nav_menu_toggle' => array(
			'nav_container_id'           => 'vk-mobile-nav',
			'nav_container_toggle_class' => 'vk-mobile-nav-open',
			'menu_button_id'             => 'vk-mobile-nav-menu-btn',
			'menu_button_toggle_class'   => 'menu-open',
		),
	)
);
```

### Expected Behaviour

Should not report AMP validation error 

### Screenshots

![image](https://user-images.githubusercontent.com/1132541/138731721-97105c8e-a11a-4d08-86a5-9a6ae74d800f.png)

### PHP Version

7.4

### Plugin Version

2.1.4

### AMP plugin template mode

Transitional

### WordPress Version

5.8

**Comment by westonruter** [comment]
Humm. This should have been handled automatically by the [`AMP_Accessibility_Sanitizer`](https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-accessibility-sanitizer.php).

**Comment by milindmore22** [comment]
Yes, that should have been handled by AMP_Accessibility_Sanitizer
in that case, the AMP_Accessibility_Sanitizer must be added at the very end of the sanitizers ie. post theme support sanitizers 


```php	
	if ( ! empty( $theme_support_args['nav_menu_toggle'] ) ) {
		$sanitizers[ AMP_Nav_Menu_Toggle_Sanitizer::class ] = $theme_support_args['nav_menu_toggle'];
	}

	if ( ! empty( $theme_support_args['nav_menu_dropdown'] ) ) {
		$sanitizers[ AMP_Nav_Menu_Dropdown_Sanitizer::class ] = $theme_support_args['nav_menu_dropdown'];
	}

	// Note: This validating sanitizer must come at the end to clean up any remaining issues the other sanitizers didn't catch.
	$sanitizers['AMP_Accessibility_Sanitizer'] = [];

```

**Comment by westonruter** [comment]
Ah yes. This will actually be fixed by https://github.com/ampproject/amp-wp/pull/6546 because now the key sanitizers get a [fixed order at the end](https://github.com/ampproject/amp-wp/pull/6546#:~:text=onload%3D%22alert(%27Hi!!!%27)%22%3E-,Sanitizer%20ordering,-Prior%20to%20this).

**Comment by maitreyie-chavan** [comment]
@milindmore22 with #6546 being released, please could you verify if this issue is still valid? Will accordingly have it either closed or added to the next release milestone.

**Comment by milindmore22** [comment]
Verified Fixed, Closing this as fixed in https://github.com/ampproject/amp-wp/pull/6546
