### ISSUE TITLE
Run AMP sanitizers over custom content

### ISSUE THREAD

**Issue by R3dRidle** [Automattic/amp-wp#666]
How can I run AMP sanitizers over custom content? Is there a function of some kind? I just want to use the standard sanitizers, no custom one.

**Comment by mjangda** [comment]
You can look at how we sanitize the featured image as an example:

https://github.com/Automattic/amp-wp/blob/8d9bc4dd9cd4d1e6faf14a07d0cd08fbd34c720c/includes/class-amp-post-template.php#L279-L285

There's no way to get a list of all sanitizers currently, but something we should add.

**Comment by R3dRidle** [comment]
I ended up adding following function to my functions.php
`function add_custom( $data ) {
    $amp_content = new AMP_Content( $data,
        apply_filters( 'amp_content_embed_handlers', array(
            'AMP_Twitter_Embed_Handler' => array(),
            'AMP_YouTube_Embed_Handler' => array(),
            'AMP_Instagram_Embed_Handler' => array(),
            'AMP_Vine_Embed_Handler' => array(),
            'AMP_Facebook_Embed_Handler' => array(),
            'AMP_Gallery_Embed_Handler' => array(),
        ) ),
        apply_filters( 'amp_content_sanitizers', array(
            'AMP_Blacklist_Sanitizer' => array(),
            'AMP_Img_Sanitizer' => array(),
            'AMP_Video_Sanitizer' => array(),
            'AMP_Audio_Sanitizer' => array(),
            'AMP_Iframe_Sanitizer' => array(
                'add_placeholder' => true,
            ),
        ) )
    );
    return $amp_content->get_amp_content();
}`
