### ISSUE TITLE
Ignore WordPress core when there is another error source in block editor AMP sidebar

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#6667]
### Bug Description

When a plugin generates a validation error by rendering invalid code in the block editor, the AMP Validation sidebar says WordPress core is the error source:

![image](https://user-images.githubusercontent.com/134745/138778167-2b607b01-e51a-4d18-b2ef-e7bb83b69068.png)

It seems the logic in the editor sidebar needs to be updated to treat Gutenberg like WordPress core, and also to ignore WordPress core when there is another source (e.g. a theme/plugin).

See: https://github.com/ampproject/amp-wp/pull/6610#issuecomment-951367883

---

### Steps to reproduce

1. Create a new plugin that will add a shortcode. The shortcode should generate invalid AMP markup, e.g.:
```php
<?php
/*
Plugin Name: Bad Tag Shortcode
*/

add_shortcode( 'bad-tag-shortcode', function () {
	return '<bad-tag-shortcode></bad-tag-shortcode>';
} );
```

2. Create a new post and add the new `[bad-tag-shortcode]` (via the Shortcode block).
3. Save and check out the AMP Validation sidebar in the block editor. It should say that the WordPress core is responsible for the `<bad-tag-shortcode>` error:
![Screenshot 2021-10-29 at 15 33 32](https://user-images.githubusercontent.com/478735/139444277-00553f33-4ba5-441a-bde3-fcf664b03fa6.png)

### Expected Behaviour

The logic in the editor sidebar needs to be updated to treat Gutenberg like WordPress core, and also to ignore WordPress core when there is another source (e.g. a theme/plugin).

### Plugin Version

2.2.0-alpha

### AMP plugin template mode

Transitional

**Comment by bartoszgadomski** [comment]
**QA passed:**

Source of an invalid element is correctly identified:
![Screenshot 2021-11-22 at 12 46 26](https://user-images.githubusercontent.com/4476915/142857358-803088be-65fe-490e-bf0f-e88cc86122ef.png)
