### ISSUE TITLE
Improve action items for when there are theme/plugin incompatibilities

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6689]
### Feature Description

Currently when there are either theme or plugin compatibility issues, the same copy appears in a paragraph above boxes containing the incompatible themes and plugins. 

- [ ] The action item to review and suppress plugins should rather only appear if there are plugins with incompatibilities, and this action item should appear inside the plugins box. 
- [ ] In the incompatible themes box, this is probably where the recommendation to change to Reader mode should be. Or else to consider switching to an alternative theme (see below).
- [ ] In the boxes for themes and plugins, there should be links to the AMP Compatible tabs for the the Theme Install and Plugin Install screens, if theme/plugin installation is available (i.e. if filesystem is not read only). If the theme/plugin installation is not available, there should rather be `ExternalLink`s going to the theme/plugin ecosystem pages on amp-wp.org.
- [ ] When a site scan completes, the `suppressed_plugins` option should be re-fetched so that the suppressed table is updated with which plugins have validation errors.
- [ ] Discontinue doing synchronous re-validation of validated URLs when updating suppressed plugins. Instead of doing this, initiating a re-scan should be done.

![image](https://user-images.githubusercontent.com/134745/140458058-2b041ccd-e1a1-46b9-9a3a-6274283cf668.png)

**Comment by dhaval-parekh** [comment]
**QA Passed**

✅  When there are incompatible plugins. It provides a link to suppress plugins and provide a link to browse AMP-compatible plugins.
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/8168027/144390476-94deeeea-6451-4d9d-b781-a93531cd60dc.png">

✅  When there is an incompatible theme. It shows a message to change templated mode and provide a link to browse AMP-compatible themes.
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/8168027/144390436-17e0d921-493b-49b7-82c2-44c49b2256c4.png">

However, I noticed that in a multisite setup ( and when a user is super admin ) It does redirect to the network screen of the respective theme/plugin screen. but not to the "AMP Compatible" tab. cc: @delawski 

✅  It re-fetch the list of suppressed plugins once site scanning is completed.

✅  Initiating a site scan once suppressed plugin is updated.

https://user-images.githubusercontent.com/8168027/144390719-adb817bc-7b9f-4904-84ae-f30b4d5ca16b.mov
