### ISSUE TITLE
Logo, height, width not shown in rich snippets

### ISSUE THREAD

**Issue by sjukunte** [Automattic/amp-wp#669]
I added below code for structured Data for NewsArticle. but is show below error, any suggestion.
![image](https://cloud.githubusercontent.com/assets/26623425/24244066/673ffd7a-0fe3-11e7-9739-9b9e7b65c5ed.png)

My code: 

add_filter( 'amp_post_template_metadata', 'xyz_amp_modify_json_metadata', 10, 2 );

function xyz_amp_modify_json_metadata( $metadata, $post ) {
	$metadata['@type'] = 'NewsArticle';

	$metadata['publisher']['logo'] = array(
		'@type' => 'ImageObject',
		'url' => get_template_directory_uri() . '/Unseen-Bollywood-Amp-Logo.png',
		'height' => 60,
		'width' => 600,
	);

	return $metadata;
}

**Comment by amedina** [comment]
Hi @sjukunte, I tried the metadata entry in your example and the height and width fields appear properly (see snapshot below); the only thing you may be missing is to put the values for the width and the height in quotes. 

<img width="692" alt="screen shot 2017-07-05 at 4 47 43 pm" src="https://user-images.githubusercontent.com/506089/27889509-b8092b22-61a1-11e7-8a6b-f65fbc73ba09.png">
