### ISSUE TITLE
Speed up Site Scan by doing up to 3 requests in parallel (with staggering)

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6691]
### Feature Description

The time it takes to perform a Site Scan could be sped up if some of the validation requests were parallelized. We wouldn't want to do too many requests in parallel for fear of overloading shared hosts, but up to 3 requests at a time seems reasonable. Additionally, in order to show some semblance of continuous progression in the progress bar and to avoid making multiple requests at exactly the same moment, it would make sense to initiate each subsequent request after a 500ms delay.

----

Note: Eventually on the Settings screen we'll want to not use a progress bar but instead list out all of the scannable URLs (which would potentially be customizable by the user) and then for each show a status: 

* In progress ⌛ 
* Has incompatibilities ⚠️ 
* All compatible ✅ 

Each URL can then link off to each respective Validated URL screen.

But this is to address later.

**Comment by fellyph** [comment]
**QA Passed** 

<img width="1435" alt="Screen Shot 2021-12-10 at 16 22 55" src="https://user-images.githubusercontent.com/330792/145610612-66313e5f-2327-4f53-bc2b-39b7f109e71b.png">

- [X] Slow 3g 
- [x] PHP 8
- [x] PHP 7.4.1 
- [x] PHP 5.6
- [x] WordPress 5.8.2
- [x] WordPress 5.9 Beta

**Comment by westonruter** [comment]
Great screenshot depicting what is going on! 👍
