### ISSUE TITLE
Google Search Console Will Not Find My AMP Pages

### ISSUE THREAD

**Issue by abridgedpause** [Automattic/amp-wp#671]
I installed the AMP plugin a little over a month ago. I activated it and customized some of the appearance everything seems to work smoothly from the WordPress end.
I’ve tested some posts and they work fine, as seen here: https://www.visioneternel.com/follow-vision-eternel-on-spotify/amp

I then went to my Google Search Console, and it said “We did not find any Accelerated Mobile Pages in your site”.
I read up in the section that said “Where are my pages? Think your pages aren’t showing up when they should? Read some basic troubleshooting tips.” Google gives you 2 suggestions.
1: Are you looking at the right property? Yes, I am.
2: Have you given Google time to crawl your AMP pages? So I gave it two weeks.

Two weeks later, I was still getting the same error, so I resubmitted my entire website sitemap and requested a new crawl. I waited another two weeks. Here I am a month after all of this and Google Search Console is still not detecting my AMP posts. I would really appreciate some assistance in figuring this out.

**Comment by amedina** [comment]
Unfortunately we cannot help with this issue; I recommend to reach out to the Search forums or your webmaster to triage this issue.
