### ISSUE TITLE
Ensure any changes to the "Enable Developer Tools" option reload the page to in

### ISSUE THREAD

**Issue by jamesozzie** [Automattic/amp-wp#6714]
### Bug Description

When a user changes the status of the "_Enable Developer Tools_" option and saves their AMP settings the additional tabs enabled/disabled by this toggle don't appear until the page is reloaded or exited. The 2 tabs are:
- Validated URLs
- Error Index

![image](https://user-images.githubusercontent.com/41326532/141342545-6ca0812d-3649-483d-8731-6ecd64f2074b.png)

![image](https://user-images.githubusercontent.com/41326532/141343177-489e4d61-5923-4b15-8aeb-b9ff971456de.png)

Consider refreshing the page upon any changes to this setting, once a user "Saves" their settings. 

### Expected Behaviour

The associated tabs that are enabled/disabled should be visible/removed upon saving any AMP configurations

### Screenshots

![2021-11-11-17-28-32](https://user-images.githubusercontent.com/41326532/141343553-74b47300-6382-47c5-a0cd-8b162d74979f.gif)

### Plugin Version

2.2.0 Alpha

### AMP plugin template mode

Transitional

### WordPress Version

5.8.2

### Browser(s) Affected

All

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Before: Tabs were not getting enabled/disabled and explicit refresh was necessary.

https://user-images.githubusercontent.com/41000648/159421584-a27a797f-8394-47ba-be1b-2aa0fe8a619b.mov

---

After: Tabs are now getting enabled/disabled as soon as AMP settings are saved.

https://user-images.githubusercontent.com/41000648/159421670-011b5935-b3e1-4c37-8b6d-67ebd3344b2e.mov
