### ISSUE TITLE
Highlighting AMP-compatible themes and plugins in network theme/plugin screens is not working properly.

### ISSUE THREAD

**Issue by dhaval-parekh** [Automattic/amp-wp#6725]
### Bug Description

The highlighting theme and plugin are not working properly in the network theme and plugin screens in the MU site setup.

**Installed Themes.**

The AMP-compatible theme does not show the message of "AMP Compatible" as we show on the installed plugin page.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/8168027/142154464-bb7fbe9f-eb82-4186-914d-982d0ba0138d.png">

**Add New Theme.**

The "AMP Compatible" tab and "AMP Compatible" badges are missing.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/8168027/142154704-3f8e39c0-a428-4ab9-8df5-d587f5712f52.png">

**Add New Plugin (Populer Tab)**

The "AMP Compatible" badges are missing.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/8168027/142154759-638cd143-c31f-41b2-850e-172a336038ad.png">

**Add New Plugin (AMP Compatible Tab)**

Additional detail section are rendring.
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/8168027/142154799-6c79f164-6409-4802-9e5a-16fe08f9b618.png">

### Expected Behaviour

**Installed Themes.**
- Show "AMP Compatible" message beside the theme author and theme site link.

**Add New Theme.**
- Add "AMP Compatible" badge for AMP-compatible themes.
- Add the "AMP Compatible" tab which shows a list of AMP-compatible themes.

**Add New Plugin (Populer Tab)**
- Add "AMP Compatible" badge for AMP-compatible plugins.

**Add New Plugin (AMP Compatible Tab)**
- Remove addition detail section from plugin card.
<img width="495" alt="image" src="https://user-images.githubusercontent.com/8168027/142155892-bcd3e617-ef18-4f9b-8763-2ac21acd64ad.png">

### Plugin Version

2.2-alpha

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by dhaval-parekh** [comment]
Related to #2313

**Comment by delawski** [comment]
**QA Passed**

The AMP Compatible badges are displayed on Add Theme and Add Plugin screens in a Multisite setup.

| Add Theme | Add Plugin |
| --- | --- |
| ![Screenshot 2021-11-29 at 23 38 05](https://user-images.githubusercontent.com/478735/143954639-e477c373-f3ff-4dae-a50d-0c759b3262c1.png) | ![Screenshot 2021-11-29 at 23 37 41](https://user-images.githubusercontent.com/478735/143954676-132091b0-f89a-4083-86b1-568d8b7c6a0d.png) |

| Add Theme<br>External link if not leading to wp.org | Add Plugin<br>External link if not leading to wp.org |
| --- | --- |
| ![Screenshot 2021-11-29 at 23 38 33](https://user-images.githubusercontent.com/478735/143954444-7c557458-0bee-49e6-8d36-36af21bdfadb.png) | ![Screenshot 2021-11-29 at 23 38 58](https://user-images.githubusercontent.com/478735/143954587-ab68fba6-3eb9-41bd-906d-4361e0976d28.png) |

| Themes<br>AMP Compatible label | Plugins<br>AMP Compatible label |
| --- | --- |
| ![Screenshot 2021-11-29 at 23 48 13](https://user-images.githubusercontent.com/478735/143954916-d1a92710-d346-4357-b801-779e3c75b110.png) | ![Screenshot 2021-11-29 at 23 47 50](https://user-images.githubusercontent.com/478735/143954930-c16080eb-9c8f-4622-a5bf-dd4cf0e032fd.png) |

_Tested on AMP Version 2.2.0-alpha-20211123T020732Z-5405daa_
