### ISSUE TITLE
Onboarding Wizard UI glitch.

### ISSUE THREAD

**Issue by dhaval-parekh** [Automattic/amp-wp#6740]
### Bug Description

There are two minor UI glitches in Onboarding Wizard.

1. Empty list item in "Standard" mode drawer of "Template Modes" screen. 
This can be reproduced when there are no plugins are suppressed and no AMP validation errors on the site.

2. In the footer when the focus is on the "Previous" button, the "Previous" and "Next" (or "Finish") buttons are too close. 

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/8168027/143191312-8e102b66-804b-4f25-92b4-7ad031b06a57.png">

### Expected Behaviour

1. There should not be an empty list item.
2. There should be a margin between the "Previous" and "Next" buttons in the footer.

### Plugin Version

2.2.0-alpha

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by bartoszgadomski** [comment]
**QA passed:**

- there is no empty list item under "Standard" template-mode box
- there is a good margin between the "Previous" and "Next" buttons in the footer

Well done 👍

![Screenshot 2021-12-7 at 11 18 19](https://user-images.githubusercontent.com/4476915/145011222-9f140076-2a96-459d-9b48-eef9678cd19b.png)
