### ISSUE TITLE
Oembed with same sites not rendered

### ISSUE THREAD

**Issue by Mte90** [Automattic/amp-wp#675]
As you can see on http://www.tvserial.it/britannia-serie-tv-streaming-cast-video/amp/ in the bottom there are 3 oembed made by links of the same website but in the amp version they are not rendered.
The online version http://www.tvserial.it/britannia-serie-tv-streaming-cast-video/ render them without problems.

Looking at the code I see that there isn't the support for oembed of the same site :-/

**Comment by amedina** [comment]
Hi @Mte90, there is no direct support for oembeds of the same site, but it should not be too difficult for you to add one: https://github.com/Automattic/amp-wp#custom-embed-handler

**Comment by Mte90** [comment]
I was thinking that is a bug of AMP because they are not showed completely but in any case the same site is a wordpress site I don't understand the problem. Works without amp but with the plugin no.
