### ISSUE TITLE
On multisite some AMP validation issues have incorrect source

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#6755]
### Bug Description

After activating the following test plugin on a site in a multisite network setup:

```php
<?php
/*
Plugin Name: AMP Error Plugin
Version: 0.1
Author: AMP Project Contributors
*/

add_action( 'wp_footer', function () {
	?>
		<bad-tag></bad-tag>
	<?php
} );
```

the AMP validation issue it causes is incorrectly attributed to `wp_footer` and not to the plugin. The same validation issue is attributed to the plugin on a non-multisite setup:

| Multisite | Single Site |
| --- | --- |
| ![Screenshot 2021-12-02 at 16 24 39](https://user-images.githubusercontent.com/478735/144451463-ebc6c03d-dda1-41e0-a450-740cb8700772.png) | ![Screenshot 2021-12-02 at 16 24 50](https://user-images.githubusercontent.com/478735/144451484-e7cd2962-e451-4dbe-b33e-31ac33cd6619.png) | 

Note that the issues caused by Contact Form 7 have correct source in both setups.

### Expected Behaviour

AMP validation issues caused by a plugin should be attributed to that plugin both on multisite and single site setup.

### Plugin Version

2.2.0-alpha

### AMP plugin template mode

Transitional

### WordPress Version

5.8.2

### Gutenberg Version

12.0.1

**Comment by westonruter** [comment]
I tried to replicate this on a multisite but I was unable. It seems to work as expected:

![image](https://user-images.githubusercontent.com/134745/144973470-c83aef81-788a-44f4-bcb9-df071b80e562.png)

I tested on the main network site, which it seems you did as well.

Is your `plugins` directory in a non-standard location perhaps?

**Comment by delawski** [comment]
My `plugins` directory is in the standard location.

What I noticed is that the Bad Block plugin is properly recognized, however my own AMP Error Plugin is not correctly attributed:

![Screenshot 2021-12-07 at 10 17 11](https://user-images.githubusercontent.com/478735/145001223-c46c3906-7e98-47e1-81d6-eabd9d449cba.png)

Here's the source of the plugin that's causing issues:

```php
<?php
/*
Plugin Name: AMP Error Plugin
Version: 0.1
Author: AMP Project Contributors
*/

add_action( 'wp_footer', function () {
	?>
		<bad-tag></bad-tag>
	<?php
} );

add_shortcode( 'bad-tag-shortcode', function () {
	return '<bad-tag-shortcode></bad-tag-shortcode>';
} );
```
