### ISSUE TITLE
Enqueued scripts are not printed on validation screens in WP 4.9

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6775]
### Bug Description

When testing in WP 4.9, I noticed that the Details failed to expand the error info on the Validated URL screen:

![image](https://user-images.githubusercontent.com/134745/145279867-e49535ad-deb7-4fb3-8cf1-0ad419d5e8fe.png)

It's not just that, as the search box doesn't work and the filter doesn't do anything. I believe there is a script dependency present which doesn't exist in 4.9. I tried registering the polyfills:

```diff
diff --git a/includes/validation/class-amp-validated-url-post-type.php b/includes/validation/class-amp-validated-url-post-type.php
index d018c774c..066332dfd 100644
--- a/includes/validation/class-amp-validated-url-post-type.php
+++ b/includes/validation/class-amp-validated-url-post-type.php
@@ -2127,6 +2127,9 @@ public static function enqueue_edit_post_screen_scripts() {
 			return;
 		}
 
+		/** This action is documented in includes/class-amp-theme-support.php */
+		do_action( 'amp_register_polyfills' );
+
 		// Eliminate autosave since it is only relevant for the content editor.
 		wp_dequeue_script( 'autosave' );
```

But this caused errors in the console:

![image](https://user-images.githubusercontent.com/134745/145280226-e58cc238-606e-4364-a1ed-138647b9d014.png)

In addition to the Validated URL screen, I'm also seeing that the scripts are not printed on the AMP Validated URLs screen, as clicking the tooltips aren't working:

![image](https://user-images.githubusercontent.com/134745/145280504-c7455c45-70a7-4331-8888-dc368d593fdc.png)

This is also the case on the Error Index screen:

![image](https://user-images.githubusercontent.com/134745/145280601-55aa4b2a-4c02-4cff-bb5c-66696e339a82.png)

This is very low priority given the very old WP version.

### Expected Behaviour

The UI should work as expected.

### Plugin Version

2.2

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by westonruter** [comment]
I think we should just prevent users access to validation screens in WP<5.6.

**Comment by delawski** [comment]
**QA Passed**

✅ The validation screens are not accessible on WP<5.6.

| WP 4.9 | WP 5.5 | WP 5.6 |
| --- | --- | --- |
| ![Screenshot 2021-12-15 at 11 47 50](https://user-images.githubusercontent.com/478735/146173062-44b4848d-1f52-447d-ae87-8272259681d1.png) | ![Screenshot 2021-12-15 at 11 47 17](https://user-images.githubusercontent.com/478735/146173094-8a336633-325c-40a0-bfc5-a2c5f3d9ed09.png) | ![Screenshot 2021-12-15 at 11 46 41](https://user-images.githubusercontent.com/478735/146173117-8be6930c-09ca-4558-b1f5-d8c3a43f6e1b.png) |
