### ISSUE TITLE
Errors from `wp-hooks` in WP 5.0-5.5

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6776]
### Bug Description

On the Settings Screen and Onboarding Wizard and AMP Customizer, I'm seeing `Uncaught TypeError: Cannot read properties of undefined (reading 'wp')` in WordPress 5.0-5.5:

> ![image](https://user-images.githubusercontent.com/134745/145282008-6e017194-59ed-407c-9be2-8d6bc14f0af9.png)

Nevertheless, the screens seem to work properly.

This is low priority given the old WP version.

### Expected Behaviour

No errors should occur on these screens.

### Plugin Version

2.2

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by westonruter** [comment]
In WordPress 5.3.10 & 5.4.8, the Customizer has many more errors than just this:

![image](https://user-images.githubusercontent.com/134745/145303420-47447eb5-8b90-4ad0-ba22-06ff1cb1ada0.png)

It breaks the Customizer entirely.

**Comment by westonruter** [comment]
The resolution for the Customizer issue should be just to disable AMP integration in WP<5.6.

**Update:** See https://github.com/ampproject/amp-wp/pull/6773#issuecomment-989544152.

**Comment by dhaval-parekh** [comment]
While further debugging the issue, Found that while generating polyfill files it assigned the polyfill object into `this.wp` instead of global `wp` (or `window.wp`). This can be changed by removing the below line from the webpack.config.js file.

https://github.com/ampproject/amp-wp/blob/4cd08b2982682b5641c8376694f5f5ad414ee636/webpack.config.js#L205

Though testing these changes with other features.

**Comment by westonruter** [comment]
Humm. But that shouldn't matter, should it? It should be that in a browser context, `this === window`.

**Comment by dhaval-parekh** [comment]
Yes, ideally `this === window` by default. But when the function uses strict mode `this` remains undefined and has to define manually. [Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#function_context)

**Comment by westonruter** [comment]
Ah yes, I forgot about strict mode. 👍

**Comment by bartoszgadomski** [comment]
### QA results

AMP plugin version: `2.2.0-RC1-20211210T171412Z-7e67d49`

#### Settings Screen

|WordPress version|Screenshot|Description|
|-|-|-|
|5.0.3, 5.1.1, 5.2.4, 5.3.2, 5.4.2|![Screenshot 2021-12-13 at 22 01 51](https://user-images.githubusercontent.com/4476915/145888296-afa33ffb-696d-4b35-8f63-a9577c5eb863.png)|REST requests failed for `/wp/v2/themes` (400: `Missing parameter(s): status`) and `/wp/v2/plugins` (404)|
|5.5.3, 5.6.2|![Screenshot 2021-12-13 at 22 19 32](https://user-images.githubusercontent.com/4476915/145890573-e80fa935-b9fa-466b-a818-4a0197d5746b.png)|REST request failed for `/wp/v2/themes` (400: `Missing parameter(s): status`)|
|5.7.2|![Screenshot 2021-12-13 at 22 27 31](https://user-images.githubusercontent.com/4476915/145891547-712a5d02-ee8f-4923-a25e-3ec7bff661de.png)|No issues|

#### Onboarding wizzard

|WordPress version|Screenshot|Description|
|-|-|-|
|5.0.3, 5.1.1, 5.2.4, 5.3.2, 5.4.2|![Screenshot 2021-12-13 at 22 31 25](https://user-images.githubusercontent.com/4476915/145892132-109b16e3-9122-434e-adfd-1ededac02890.png)|REST requests failed for `/wp/v2/themes` (400: `Missing parameter(s): status`) and `/wp/v2/plugins` (404)|
|5.5.3, 5.6.2|![Screenshot 2021-12-13 at 22 36 09](https://user-images.githubusercontent.com/4476915/145892684-cd982143-cd29-430c-832f-83a4defb85cc.png)|REST request failed for `/wp/v2/themes` (400: `Missing parameter(s): status`)|
|5.7.2|![Screenshot 2021-12-13 at 22 28 58](https://user-images.githubusercontent.com/4476915/145891782-b38a282d-5aaa-4f51-9ce9-44723037a3fa.png)|No issues|

CC: @westonruter @delawski

**Comment by delawski** [comment]
@bartoszgadomski Those issues are fixed in #6773. Since it's not merged yet, I think it's best to wait with the QA until it's in `develop`.

**Comment by delawski** [comment]
**QA Passed**

| WordPress Version | QA | AMP Settings | QA | Onboarding Wizard |
| --- | --- | --- | --- | --- |
| 4.9.8 | ✅ | ![Screenshot 2021-12-15 at 11 57 21](https://user-images.githubusercontent.com/478735/146174686-af80b191-5842-4fde-9119-ec41a4d96f03.png) | ✅ | ![Screenshot 2021-12-15 at 11 58 21](https://user-images.githubusercontent.com/478735/146174707-355bf7c8-1c6e-4c85-b41b-b05b0e32ba07.png) |
| 5.5.7 | ✅ | ![Screenshot 2021-12-15 at 11 57 51](https://user-images.githubusercontent.com/478735/146174843-7cd0a9d0-a4d3-43b3-b082-4ab2324379d0.png) | ✅ | ![Screenshot 2021-12-15 at 11 58 30](https://user-images.githubusercontent.com/478735/146174862-e10e6021-3e09-470f-8b55-b42e64502b23.png) |
| 5.6.6 | ✅ | ![Screenshot 2021-12-15 at 11 58 05](https://user-images.githubusercontent.com/478735/146174899-cf848db5-6bfb-42f0-871d-2c4ab7acb604.png) | ✅ | ![Screenshot 2021-12-15 at 11 58 41](https://user-images.githubusercontent.com/478735/146174916-647a2f98-3a20-4961-8f10-987062691227.png) |

Version 2.2.0-RC1-20211214T235253Z-fda381f

---

@bartoszgadomski If you have capacity today, please confirm everything works as expected with the latest [2.2 production build](https://github.com/ampproject/amp-wp/wiki/Development-Builds).
