### ISSUE TITLE
Empty JS files are generated as part of build

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6778]
### Bug Description

Webpack is creating empty JS files when it is processing stylesheets:

![image](https://user-images.githubusercontent.com/134745/145309466-ed3e520e-5725-47fc-b625-9c74e512e028.png)

These need to be omitted from the build, either by preventing them from being generated or by deleting them after running webpack.

### Expected Behaviour

No empty JS files should be created.

### Plugin Version

2.2

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by delawski** [comment]
I found out that it the issue is caused because of Webpack update from version 4 to 5. The API for plugins has changed and now our `IgnoreExtraneousStyleAssets` plugin doesn't work as expected (actually it doesn't work at all). I'm working on a fix.

**Comment by delawski** [comment]
**QA Passed**

✅ There are no empty JS or extraneous `.asset.php` files in the `/assets/js` folder in the latest production build (files are ordered by size in the screenshot).

<img width="753" alt="Screenshot 2021-12-15 at 11 41 23" src="https://user-images.githubusercontent.com/478735/146172071-289d2a6e-b7e7-490b-94fe-c6086ad8dc83.png">
