### ISSUE TITLE
problem with amp

### ISSUE THREAD

**Issue by lidolove201046** [Automattic/amp-wp#678]
i have problem with some urls of my site 
and this url is one of the urls which had the problem
https://www.alfransia.com/%D8%B4%D8%B1%D9%83%D8%A9-%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9-%D8%AD%D8%B4%D8%B1%D8%A7%D8%AA-%D8%A8%D8%A7%D9%84%D8%A7%D8%AD%D8%B3%D8%A7%D8%A1/amp/

![2017-03-28_19-17-40](https://cloud.githubusercontent.com/assets/25593687/24424760/0c22ae92-1402-11e7-877f-9ea834c4aef7.jpg)
![2017-03-28_19-18-22](https://cloud.githubusercontent.com/assets/25593687/24424759/0c1d0384-1402-11e7-9515-b4515487fb61.jpg)

**Comment by lysk88** [comment]
What is basically says is that the meta tag support content and name attributes. 
So the issue here is with the href attribute which added to the meta tag, not with the url itself.
you can have a look  [here](https://www.w3schools.com/tags/tag_meta.asp)

**Comment by lidolove201046** [comment]
i am sorry i donot understand you 
can you help me to fix it in wordpress

**Comment by amedina** [comment]
It seems you are using a plugin (for SEO?) which is adding met tags that cause the AMP pages to become invalid. Could you tell us which plugins are being used by your site?

**Comment by amedina** [comment]
Closing for now. Please re-open if you still have the issue.
