### ISSUE TITLE
Add support for dark mode user toggle in Twenty Twenty-One

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6783]
### Feature Description

When AMP compatibility was added to Twenty Twenty-One (https://github.com/ampproject/amp-wp/pull/5648), the dark mode toggle button had to be hidden on AMP pages since there was no way to persist the state:

> Currently, dark mode support is only available to users if their system supports it. The theme toggle that is shown which allows the user to switch between light and dark mode has been removed from the frontend, due to the inability to persist the theme preference and being able to unserialize that into the AMP state without explicit user interaction. This issue is being tracked in [ampproject/amphtml#20951](https://github.com/ampproject/amphtml/issues/20951).

However, as of https://github.com/ampproject/amphtml/pull/36958 there is now an `AMP.toggleTheme()` action which can be used to toggle dark mode via user preference. So this can be utilized to add that toggle on AMP pages.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

But note that this comment https://github.com/ampproject/amp-wp/pull/6874#pullrequestreview-877568300 is yet to be resolved. There is still a minor difference between AMP and non-AMP pages which is the toggle button is not hidden/shown on scroll.
