### ISSUE TITLE
i have problem in AMP WordPress

### ISSUE THREAD

**Issue by ismailkho** [Automattic/amp-wp#680]
hi
I have a problem on all pages of the site
https://www.msaydati.com/%d8%a7%d8%b9%d8%b1%d8%a7%d8%b6-%d8%a7%d9%84%d8%ad%d9%85%d9%84/amp
![image](https://cloud.githubusercontent.com/assets/26851085/24586195/d385e88a-1792-11e7-811c-69b2eff03fa9.png)

**Comment by amedina** [comment]
Please reopen if needed with more info to understand and track the issue.
