### ISSUE TITLE
Facilitate users to share validation issues with 3rd party theme/plugin developers

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6807]
### Feature Description

When a user indicates they are not technically savvy, we hide links to the Validated URLs screen. When Site Scanning completes, we list the plugins and themes that have AMP validation issues, and then we again only show the link to the Validated URLs screen if the user is technical. This is problematic in the case where a user may want to report validation errors to a theme/plugin developer. In fact, as per #4668 we want to encourage this as much as possible instead of having all support requests go through the AMP plugin forum. 

This was originally requested by @futtta in a [support topic](https://wordpress.org/support/topic/site-scanner-results-allowing-developers-to-act-on-issues/#post-15187136):

> Remaining question (remark); it would be great if the “site scanner” could provide more technical info (hidden by default) for users to pass on to developers of conflicting plugins/ themes 🙂

Given the Site Scan results where we currently list each theme/plugin on a separate row:

![image](https://user-images.githubusercontent.com/134745/147166044-7eee579c-72d6-4065-893f-71c68294ac98.png)

I suggest that we make each line item expandable. When expanded, we can show:

1. The URLs on which the plugin/theme has validation errors occurring. (We currently show this when activating a plugin, but we don't have this useful information as part of the full Site Scanning.)
2. A summary of the validation errors. This likely should be similar to the “Raw data” field on the Support screen along with a button to copy to the clipboard. In fact, this would be very similar to the capability we have to copy validation errors to the clipboard from the Validated URL screen in #5500. So there could be a button saying in effect “Copy validation data to share with developer”. This could be also incorporated into the plugin post-activation scan notice.

The version information could be shown in the expanded view (along with other metadata), instead of showing it floated to the right.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ for the new enhancement implemented.

Before: On Site Scan screen links were hidden for non-technical savvy

<img width="1264" alt="Screenshot 2022-03-23 at 11 01 37 AM" src="https://user-images.githubusercontent.com/41000648/159630653-83e6aed4-113a-4cf7-a8af-2d0edc141c8b.png">

---

After: On Site Scan screen links are displayed for non-technical savvy

<img width="1269" alt="Screenshot 2022-03-23 at 11 01 25 AM" src="https://user-images.githubusercontent.com/41000648/159630751-acbda514-050b-4cc8-a56c-e882e9202951.png">

---

**But found an regression issue on Safari Browser Version 14.0.3** 

**Though it is working fine in latest Safari Version 15.03**

On site scan screen from AMP settings page and also on Onboarding Wizard, the error displayed for theme/plugins are not aligned. The title of plugin/theme appears below the arrow

Onboarding Wizard Screen

<img width="1254" alt="Screenshot 2022-03-23 at 11 00 02 AM" src="https://user-images.githubusercontent.com/41000648/159630979-544465c6-a346-4f05-8093-1af39529809b.png">

---

Site scan AMP settings screen

<img width="1253" alt="Screenshot 2022-03-23 at 11 00 38 AM" src="https://user-images.githubusercontent.com/41000648/159631015-6b639d2d-fe89-4a44-8887-a2550bf6ba83.png">
