### ISSUE TITLE
Plugin suppression can fail to work during validate requests

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6809]
### Bug Description

In a [support topic](https://wordpress.org/support/topic/site-scanner-results-allowing-developers-to-act-on-issues/#post-15189614) I discovered that even though I suppressed Autoptimize, validation errors for it were still showing up when validating the page. However, they would not appear in the admin bar. 

I found a way to replicate the issue with the following plugin:

```php
<?php
/**
 * Plugin Name: Auto Add Script to Footer
 */

namespace Auto_Add_Script_To_Footer;

function print_script() {
	echo '<script>document.write("Automatically added to footer!");</script>';
}

function add_wp_footer_hook() {
	add_action( 'wp_footer', __NAMESPACE__ . '\print_script' );
}

function add_wp_hook() {
	add_action( 'wp', __NAMESPACE__ . '\add_wp_footer_hook' );
}

add_action( 'plugins_loaded', __NAMESPACE__ . '\add_wp_hook' );
```

With that plugin active and suppressed:

![image](https://user-images.githubusercontent.com/134745/147171612-ef285b66-b13c-411a-ab83-d2d7b43943a4.png)

Going to an AMP page on the frontend shows no validation errors being detected:

![image](https://user-images.githubusercontent.com/134745/147171650-685f7ed3-1cbf-4356-ae98-53d5ecc581d7.png)

However, if I go to the Validated URL screen then I see an error detected:

![image](https://user-images.githubusercontent.com/134745/147171707-3e3eed7c-9d21-44f9-8df6-3657887fc56a.png)

I believe it has to do with this logic in `AMP_Validation_Manager::wrap_hook_callbacks()`:

https://github.com/ampproject/amp-wp/blob/c2b9b38c4b21b152ec44138da49f73f27394dd30/includes/validation/class-amp-validation-manager.php#L1463-L1481

The replacement of the original callback with the wrapped callback closure I believe is interfering with `PluginSuppression::suppress_hooks()` specifically when it calls `$this->is_callback_plugin_suppressed( $callback['function'], $suppressed_plugins )`:

https://github.com/ampproject/amp-wp/blob/c2b9b38c4b21b152ec44138da49f73f27394dd30/src/PluginSuppression.php#L368-L379

Since at this point `$callback['function']` may be the closure and not the original callable from the other plugin, the check fails because the AMP plugin is detected and not the Auto Add Script to Footer function.

What's strange is that this issue specifically happens when the `wp` action is involved. If I change my test plugin as follows:

```php
function print_script() {
	echo '<script>document.write("Automatically added to footer!");</script>';
}

function add_wp_footer_hook() {
	add_action( 'wp_footer', __NAMESPACE__ . '\print_script' );
}

add_action( 'plugins_loaded', __NAMESPACE__ . '\add_wp_footer_hook' );
```

Then the suppression works successfully.

### Expected Behaviour

The plugin should be suppressed on the frontend and during a validate request.

### Plugin Version

2.2

### AMP plugin template mode

Transitional

**Comment by westonruter** [comment]
The issue is that the `maybe_suppress_plugins` method runs at the `wp` action (unless a Reader theme is being served):

https://github.com/ampproject/amp-wp/blob/c2b9b38c4b21b152ec44138da49f73f27394dd30/src/PluginSuppression.php#L107-L123

Since it is running at `wp` and `AMP_Validation_Manager::wrap_hook_callbacks()` has already wrapped all the hooks in closures, `maybe_suppress_plugins` is not able to see the original callback when it runs during that action.

**Comment by westonruter** [comment]
I think `is_callback_plugin_suppressed` needs to do something similar to what was done in #6579 to get the original underlying callback:

https://github.com/ampproject/amp-wp/blob/c2b9b38c4b21b152ec44138da49f73f27394dd30/includes/validation/class-amp-validation-manager.php#L1297-L1302

**Comment by westonruter** [comment]
(QA still necessary on 2.2 branch.)

**Comment by delawski** [comment]
**QA Passed**

For QA I've used the sample plugin shared in the PR description and AMP Version 2.2.1-alpha-20220127T170248Z-78e27d9.

Before suppressing the plugin, an AMP validation issue was displayed in the WP admin bar, on the AMP Validated URL screen and in the Site Scan panel.

After suppressing the plugin, there was no AMP validation issue in neither of the mentioned locations:

| WP admin bar | AMP Validated URL | Site Scan panel |
| --- | --- | --- |
| ![Screenshot 2022-01-28 at 12 34 14](https://user-images.githubusercontent.com/478735/151540519-c252caa7-ce4d-4641-aaca-10b6f4d44a7d.png) | ![Screenshot 2022-01-28 at 12 34 19](https://user-images.githubusercontent.com/478735/151540537-57ea6ba6-f295-487b-aa89-e65984ec7cf6.png) | ![Screenshot 2022-01-28 at 12 34 08](https://user-images.githubusercontent.com/478735/151540564-39771358-a2ce-47a4-ae6c-d35d166e3809.png) |
