### ISSUE TITLE
Mixed Content Was Loaded Insecure

### ISSUE THREAD

**Issue by yunvonks** [Automattic/amp-wp#6813]
### Bug Description

this is bug is mixed content on google search console

### Expected Behaviour

how to solve mixed content was loaded insecure on amp for wp

### Screenshots

![Screenshot_2021-12-22-22-02-09-264_com android chrome](https://user-images.githubusercontent.com/90853571/147261159-829b987c-599c-47df-9b7e-d4c983258227.jpg)

### PHP Version

7.4

### Plugin Version

1.07.9.33

### AMP plugin template mode

Standard

### WordPress Version

5.8.2

### Site Health

good

### OS(s) Affected

Wordpress

### Browser(s) Affected

Chrome

**Comment by westonruter** [comment]
Hi. You're not using this AMP plugin but rather https://github.com/ahmedkaludi/accelerated-mobile-pages

Please report the issue there or on their support forum: https://wordpress.org/support/plugin/accelerated-mobile-pages/
