### ISSUE TITLE
Do async site scanning after theme activation

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6814]
### Feature Description

With #6685 we now do async site scanning after plugin activation. The same should be done when activating a new theme. Granted, it is much less common to be switching themes vs activating plugins, so this is not as high of a priority. Also the weekly cron will show theme results when it runs eventually. But still it would be good to show scan results sooner rather than later.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ for the main feature implemented. 

Scan results with no errors after theme activation

<img width="1249" alt="Scan-results with no errors" src="https://user-images.githubusercontent.com/41000648/159272867-b7438bce-fbdc-4d40-ad60-8059d3e42d04.png">

---

Scan results with errors after theme activation

<img width="1262" alt="Scan results with errors" src="https://user-images.githubusercontent.com/41000648/159272946-02cd8bf7-2cf4-4c2c-9335-d4ae52cf5cf1.png">

---

<img width="1279" alt="Screenshot 2022-03-21 at 7 09 44 PM" src="https://user-images.githubusercontent.com/41000648/159273067-f418f2cc-bcaa-4ded-bacf-159d82390979.png">


---

But following are some observations:

- [ ] 1. As per [comment](https://github.com/ampproject/amp-wp/pull/6685#issuecomment-983612091) Message for technical and non-technical user are different. But currently same message is shown to both type of users.


https://user-images.githubusercontent.com/41000648/159272009-78f40835-6769-482d-90aa-867412e754f4.mov

**Comment by westonruter** [comment]
> * Message for technical and non-technical user are different. But currently same message is shown to both type of users.

The difference is non-technical users wouldn't be shown the list of URLs? I see no reason why that would be preferable. So I think the way it is now is best. 

Moving to QA Passed.
