### ISSUE TITLE
Using blog charset instead of hardcoded `utf-8`

### ISSUE THREAD

**Issue by moorscode** [Automattic/amp-wp#682]
In the following files a charset is being used, but it is hardcoded to `utf-8`.
I believe this should be retrieved from the blog settings using `get_bloginfo( 'charset' )`.

See:
https://github.com/Automattic/amp-wp/blob/2d201cf567271c4c7428081b2ff042d30ca97096/includes/utils/class-amp-dom-utils.php#L12
And:
https://github.com/Automattic/amp-wp/blob/e3b3cdb362a2a465ced8b43d9301b03915a9b7fa/templates/single.php#L4

**Comment by moorscode** [comment]
After talking about this thing I got informed that `utf-8` is a requirement of AMP.
Though this sounds like it will give problems with blogs that are not configured for UTF-8.

**Comment by westonruter** [comment]
The issue with parsing is being fixed in https://github.com/Automattic/amp-wp/pull/865/commits/5a21c85c66f2e7ec215ef20b514889a1c848003f

And then with that in place, support for sites in charsets other than UTF-8 will be supported via #855 by converting the encoding when output buffering finishes.
