### ISSUE TITLE
Optimize : Plugin uninstallation with data

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6826]
### Bug Description

We have been receiving support topics mentioning failing to delete data while uninstalling the plugin 

1. https://wordpress.org/support/topic/delete-amp-plugin/
1. https://wordpress.org/support/topic/error-on-uninstall-amp/
1. https://wordpress.org/support/topic/can-not-uninstall-amp/
1. https://wordpress.org/support/topic/cant-delete-amp-plugin/
1. https://wordpress.org/support/topic/amp-uninstall/
1. https://wordpress.org/support/topic/does-not-allow-to-uninstall-amp/
1. https://wordpress.org/support/topic/how-to-delete-the-amp-plugin/
1. https://wordpress.org/support/topic/cant-uninstall-the-amp-plugin/

I am not able to reproduce the issue, but I doubt that cause maybe the timeout error failing to delete 1000 posts and taxonomies one by one, as in some cases there are plugins that have heavy processing or 50+ plugins on a site creating large number of invalidation record.

Please check the possibility of optimizing the uninstallation process (500 posts?), we can consider executing [SQL queries](https://wordpress.org/support/topic/how-do-i-uninstall-the-plugin-and-databases-2/#post-13997354), instead of using `wp_delete_post`  and `wp_delete_term`

### Expected Behaviour

Hassle-free Uninstallation process 💯 

### PHP Version

7.4

### Plugin Version

2.2.0

### AMP plugin template mode

Transitional, Reader

### WordPress Version

5.8.2

### Site Health

ampwp-45d67ac7-6236-5036-b88d-8d797b7833cc

### Gutenberg Version

12.2.0

### OS(s) Affected

all

### Browser(s) Affected

all

### Device(s) Affected

all

**Comment by westonruter** [comment]
I wonder if there are plugins that are trying to purge some caches after each `wp_delete_post()` call. If every call is causing a the site's page cache to be purged, then that could be why cause of the problem.

> Please check the possibility of optimizing the uninstallation process (500 posts?), we can consider executing [SQL queries](https://wordpress.org/support/topic/how-do-i-uninstall-the-plugin-and-databases-2/#post-13997354), instead of using `wp_delete_post` and `wp_delete_term`

A challenge here is that the object cache can be left populated with data, but better to have stale cache than having data permanently left in the DB.

We could also consider obtaining the current `max_execution_time` and then keep track of how long it is taking us to delete data. If we're approaching 50% of the total `max_execution_time` then we could bail running the `wp_delete_post()` and `wp_delete_term()` calls to instead.

Another option would be to obtain all the IDs that we need to delete, then to do a SQL batch `DELETE`, and finally pass each ID into `clean_post_cache()` and `clean_term_cache()`.

**Comment by westonruter** [comment]
Another thought is that we could call `wp_suspend_cache_invalidation( true )` at the beginning before deleting everything, and then `wp_suspend_cache_invalidation( false )` at the end. But this assumes other plugins are checking the `$_wp_suspend_cache_invalidation` when the `delete_post` and `delete_term` actions fire.

**Comment by westonruter** [comment]
@milindmore22 Something to check is if users get the same error when they have the “uninstall at delete” toggle turned off in the settings. Is the issue the removal of data or that the plugin has a large number of files?

**Comment by milindmore22** [comment]
[The user confirmed](https://wordpress.org/support/topic/delete-amp-plugin/#post-15241065) that by toggling off he is able to delete the AMP plugin.

**Comment by westonruter** [comment]
@milindmore22 Have you been able to identify a common factor across users who have data deletion failures? Do they have a caching plugin in common, for example?

**Comment by milindmore22** [comment]
I have checked three site info, available  with us, they have very few similarities

| [ampwp-45d67ac7-6236-5036-b88d-8d797b7833cc](https://insights.amp-wp.org/admin/report/uuid/ampwp-45d67ac7-6236-5036-b88d-8d797b7833cc) | [ampwp-71a5b4c4-ff59-5e3c-b3a9-5aa95ef33186](https://insights.amp-wp.org/admin/report/uuid/ampwp-71a5b4c4-ff59-5e3c-b3a9-5aa95ef33186) | [ampwp-6fa79782-72ca-53ba-8f6d-c3893dd569a5](https://insights.amp-wp.org/admin/report/uuid/ampwp-6fa79782-72ca-53ba-8f6d-c3893dd569a5) |
| ------------- | ------------- | ------------- |
| WP Super Cache  | WP Rocket  | WP Super cache  |
| Gutenberg with Classic 🤷🏼   | Beaver Builder | Elementor |
| ------------- | UpdraftPlus | UpdraftPlus |
| WooCommerce | ---------- | WooCommerce |
| Rank Math SEO | Rank Math SEO | Rank Math SEO |

I have tested, Rank Math SEO, WooCommerce, and Updraftplus plugins and didn't encounter any issue while deleting the AMP plugin.

**Comment by westonruter** [comment]
Let's go ahead with just doing the SQL `DELETE` queries. 

In looking at [what WooCommerce does](https://github.com/woocommerce/woocommerce/blob/cd73b571917b0bb64192c6cbe8b8e3569454b2c1/plugins/woocommerce/uninstall.php#L58-L110), they do SQL `DELETE` for posts and taxonomy terms, and then at the very end they do `wp_cache_flush()`. The flushing of the object cache at the end is the missing piece that had me hesitating.

**Comment by ghost** [comment]
Hey, I am also facing this issue. Cannot delete the plugin until I turn off that delete all data button. But why I am writing here is because AMP left some children somewhere and cannot find where to remove it.

This is the Notice I get from RankMath : SEO Notice: A previously published term has been moved to trash. You may redirect https://example.com/?taxonomy=amp_validation_error&term=a6703459abe929936dadcce26e4f7fe4

Where do I find this to delete it? It really bothers me that notification.

Here is the Support UUID : ampwp-d7974cae-5b93-5bb9-9820-74df0166b945

Thank you in advance

**Comment by milindmore22** [comment]
Hello @rfseapp We are working on optimizing the delete data process, which is likely to release with 2.2.1, meanwhile, you can try and use the WP CLI commands or SQL queries mentioned in [this reply](https://wordpress.org/support/topic/how-do-i-uninstall-the-plugin-and-databases-2/#post-13997354) (Please use those SQL queries at your own risk, also once you execute those queries please clear Site cache and Object Cache)

**Comment by westonruter** [comment]
In addition to checking the uninstallation visually via the admin, here's a good way to QA the uninstallation by examining the result of the specific SQL `DELETE` queries being run:

```bash
wp db export - --extended-insert=FALSE  > /tmp/before-uninstall.sql
# Now do uninstall.
wp db export - --extended-insert=FALSE  > /tmp/after-uninstall.sql
diff /tmp/before-uninstall.sql /tmp/after-uninstall.sql  | cut -c1-200 | egrep '^<'
```

The resulting diff will show the rows that have been deleted from the database.

**Comment by delawski** [comment]
**QA Passed**

The AMP-related data is successfully removed after deleting the plugin.

I've set up a set of test posts and activated several plugins that cause AMP incompatibilities. Then, I've validated a bunch of posts.

The DB dump before uninstalling had over 2000 lines. The dump done after the uninstall had almost 1600 lines which means that AMP related data has been removed.

I've also reviewed the after-uninstall DB dump manually and could find a few remaining occurrences of `amp_validated_url` string. They were part of the rewrite rules and the admin screen layout metadata which I guess is expected.

**Comment by ocha1** [comment]
en react alguien me podria ayudar con este error No se pudo ejecutar 'removeChild' en 'Nodo': el nodo que se va a eliminar no es un hijo de este nodo.
NotFoundError: No se pudo ejecutar 'removeChild' en 'Node': El nodo que se va a eliminar no es un hijo de este nodo.
    en removeChild (http://localhost:3000/static/js/bundle.js:16899:20)
    en runWithFiberInDEV (http://localhost:3000/static/js/bundle.js:7645:14)
    en commitDeletionEffectsOnFiber (http://localhost:3000/static/js/bundle.js:13229:11)
    en recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:13334:7)
    en commitMutationEffectsOnFiber (http://localhost:3000/static/js/bundle.js:13431:9)
    en recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:13342:104)
    en commitMutationEffectsOnFiber (http://localhost:3000/static/js/bundle.js:13431:9)
    en recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:13342:104)
    en commitMutationEffectsOnFiber (http://localhost:3000/static/js/bundle.js:13352:9)
    en recursivelyTraverseMutationEffects (http://localhost:3000/static/js/bundle.js:13342:104)
