### ISSUE TITLE
Error: `s.sources` is not iterable

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6827]
### Bug Description

As reported in a [support forum topic](https://wordpress.org/support/topic/s-sources-is-not-iterable/):

![image](https://user-images.githubusercontent.com/134745/148852747-9d934085-4fe8-4829-868f-61ee42cb5c24.png)

The culprit may be one of these lines:

https://github.com/ampproject/amp-wp/blob/c2b9b38c4b21b152ec44138da49f73f27394dd30/assets/src/block-validation/components/error/get-error-source-title.js#L20

https://github.com/ampproject/amp-wp/blob/c2b9b38c4b21b152ec44138da49f73f27394dd30/assets/src/block-validation/hooks/use-validation-error-state-updates.js#L214

https://github.com/ampproject/amp-wp/blob/c2b9b38c4b21b152ec44138da49f73f27394dd30/assets/src/components/site-scan-context-provider/get-sources-from-scannable-urls.js#L32

I suggest we investigate what could be causing `sources` to end up not being an array (like either `null` or `{}`) and then guard against that case.

Support topics:

* https://wordpress.org/support/topic/r-sources-not-iterable/
* https://wordpress.org/support/topic/s-sources-is-not-iterable/

### Expected Behaviour

The `sources` prop should never be a non-array.

### Plugin Version

2.2

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by westonruter** [comment]
cc @delawski

**Comment by milindmore22** [comment]
[Another report ](https://wordpress.org/support/topic/r-sources-not-iterable/)for same issue 

Possible cause : 
```json
 "url": "https://viodi.com/wordpress",
  "home": "https://viodi.com",
  ```

**Comment by westonruter** [comment]
For that support topic, it's interesting to note that the error is slightly different: `r.sources is not iterable`. So here the object is `r` but in the original topic the object is `s`. That would seem to indicate it's happening in multiple places, perhaps two of the code instances I cited.

**Comment by westonruter** [comment]
I was able to reproduce the issue. In looking at the preloaded data for `scannable-urls`, the search results item included this:

```
"validation_errors":[{"node_name":"script","parent_name":"body","code":"DISALLOWED_TAG","type":"js_error","node_attributes":[],"text":"document.write(__DOUBLE_QUOTED_STRING__);","node_type":1,"sources":null}]
```

I'm not sure why it was saved with `null`, and after rescanning it is no longer `null`.

**Comment by westonruter** [comment]
I think this code may be the problem:

https://github.com/ampproject/amp-wp/blob/bf8aa7f9cdb05c1ea745b69578f6bbbee495f876/includes/validation/class-amp-validation-manager.php#L785-L799

Notice how `$sources` is set to have an initial value of `null`, and then it is set to be an array only if `$error['sources']` is not empty or `$node` is not empty. But in the `else` condition, nothing happens and so it can remain `null`. That then causes the error to happen.

Rather than make sure that every possible `sources` is set to be an array (including in data stored), I think it may be simpler just to treat `sources` as nullable in JS, and to check to see if it is an array before looping over it.

**Comment by westonruter** [comment]
Or maybe actually even simpler to just ensure that `sources` is an array in the REST API response:

```diff
diff --git a/src/Validation/ScannableURLsRestController.php b/src/Validation/ScannableURLsRestController.php
index f5117a768..762689789 100644
--- a/src/Validation/ScannableURLsRestController.php
+++ b/src/Validation/ScannableURLsRestController.php
@@ -189,7 +189,15 @@ public function prepare_item_for_response( $item, $request ) {
 
 			$data = json_decode( $validated_url_post->post_content, true );
 			if ( is_array( $data ) ) {
-				$item['validation_errors'] = wp_list_pluck( $data, 'data' );
+				$item['validation_errors'] = array_map(
+					static function ( $validation_error ) {
+						if ( ! isset( $validation_error['sources'] ) || ! is_array( $validation_error['sources'] ) ) {
+							$validation_error['sources'] = [];
+						}
+						return $validation_error;
+					},
+					wp_list_pluck( $data, 'data' )
+				);
 			}
 
 			$item['validated_url_post'] = [
```

(This may also need to handle ensuring nested `sources` also being arrays.)

**Comment by westonruter** [comment]
This would need to be combined with fixing the non-cached validation response as well:

```diff
diff --git a/includes/validation/class-amp-validation-manager.php b/includes/validation/class-amp-validation-manager.php
index 4ab6746c0..b14accf4e 100644
--- a/includes/validation/class-amp-validation-manager.php
+++ b/includes/validation/class-amp-validation-manager.php
@@ -784,7 +784,7 @@ public static function has_cap( $user = null ) {
 	 */
 	public static function add_validation_error( array $error, array $data = [] ) {
 		$node    = null;
-		$sources = null;
+		$sources = [];
 
 		if ( isset( $data['node'] ) && $data['node'] instanceof DOMNode ) {
 			$node = $data['node'];
```

**Comment by delawski** [comment]
@westonruter Thanks for the investigation.

> I was able to reproduce the issue.

Can you share more on this? I tried reproducing the error on a multisite instance but with no luck.

**Comment by westonruter** [comment]
> Can you share more on this? I tried reproducing the error on a multisite instance but with no luck.

That's a good question. It was happening when I opened the Settings screen, but I don't know how I caused it! I then reproduced the issue by manually causing the condition to happen. I'm trying to find a way to reproduce the issue otherwise.

**Comment by westonruter** [comment]
> [Another report ](https://wordpress.org/support/topic/r-sources-not-iterable/)for same issue
> 
> Possible cause :
> 
> ```json
>  "url": "https://viodi.com/wordpress",
>   "home": "https://viodi.com",
> ```

I created an environment like this but I got no issues with detecting validation error sources.  I tried with Contact Form 7.

I also tried creating a multisite subdirectory install, and for a subdirectory subsite I also didn't get any errors from detecting sources.

So the kind of WordPress install may not be the issue. It may be a specific kind of error scenario that is resulting in `null` as `sources`.

**Comment by westonruter** [comment]
I'm at a loss for how to replicate the issue (other than by forcing the error state by modifying the code). Maybe @milindmore22 or @fellyph will have better luck based on the active plugins from the users?

If we can't find the cause, I think we'll need to end up merging #6846 and then investigate further the failure to locate sources later.

**Comment by westonruter** [comment]
User QA [verified](https://wordpress.org/support/topic/r-sources-not-iterable/#post-15287471) fix:

> ![image](https://user-images.githubusercontent.com/134745/151034418-47f50e95-14a2-476c-80ef-144d79958db8.png)

**Comment by dhaval-parekh** [comment]
✅ **QA Passed.**

The Site scanning on AMP setting page work fine even when the error source is `null`.

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/8168027/151573604-0786c7a7-9de5-4234-adfb-2348fbcbd130.png">

**Comment by fellyph** [comment]
Tested on 2.2.x and ✅  **QA Passed.**

**Comment by zdenys** [comment]
Just wanted to let share that some WordPress.com customers have also been affected by this bug. Is there a timeline for when version 2.2.1 will be released?

**Comment by westonruter** [comment]
@zdenys The plan is to release 2.2.1 today.

**Comment by westonruter** [comment]
@zdenys It was released several hours ago: https://github.com/ampproject/amp-wp/releases/tag/2.2.1
