### ISSUE TITLE
AMP plugin broke my website

### ISSUE THREAD

**Issue by coachunt** [Automattic/amp-wp#6829]
Hi

I think the AMP plugin has broken my website and
Google stopped submitting my website homepage into sitemap after using AMP.

When I tried to uninstall the AMP plugin then I got the error “Deletion failed: There has been a critical error on this website. Learn more about troubleshooting WordPress.”

Could you please tell me how to fix this issue?

**Comment by milindmore22** [comment]
Hello @coachunt 
Please create a support topic in [WordPress support forums](https://wordpress.org/support/plugin/amp/#new-topic-0), We will recommend creating a support topic after submitting Site details using AMP->Support 
https://www.youtube.com/watch?v=wXoHwRvYsW8

We are currently investigating an issue with failure on uninstalling you follow this [GitHub issue](https://github.com/ampproject/amp-wp/issues/6826) to get updates
