### ISSUE TITLE
Iframe having width="100%" with youtube embed link are not converted to fixed-height layout

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6834]
### Bug Description

As noted by Weston on the [support topic ](https://wordpress.org/support/topic/youtube-video-31/#post-15237963)
the `width="100%"` should be converted to `layout=fixed-height` 

it converts other sites, but not for youtube embed links

Input Youtube Embed
```html
<iframe width="100%" height="315" src="https://www.youtube.com/embed/s52JNMT59s8"></iframe>
```
Output:
No Output

Input Site
```html
<iframe width="100%" height="315" src="https://amp-wp.org"></iframe>
```
Output
```html
<amp-iframe width="auto" height="315" src="https://amp-wp.org" layout="fixed-height" sandbox="allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-scripts allow-top-navigation-by-user-activation" class="i-amphtml-layout-fixed-height i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout" style="height: 315px; --loader-delay-offset:221ms !important;" i-amphtml-layout="fixed-height" frameborder="0"><span placeholder="" class="amp-wp-iframe-placeholder amp-hidden"></span><noscript><iframe width="100%" height="315" src="https://amp-wp.org"></iframe></noscript><i-amphtml-scroll-container class="amp-active"><iframe class="i-amphtml-fill-content" name="amp_iframe0" frameborder="0" allow="" sandbox="allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-scripts allow-top-navigation-by-user-activation" src="https://amp-wp.org#amp=1" style="z-index: 0;"></iframe></i-amphtml-scroll-container></amp-iframe>
```

### Expected Behaviour

Convert youtube embed with width="100%" into amp-youtube with layout fixed-height 

### Screenshots

| non-AMP        | AMP
| ------------- |-------------|
| ![image](https://user-images.githubusercontent.com/1132541/149357692-d4922abd-cd5e-4cac-922e-a75dcfa9b5ce.png) | ![image](https://user-images.githubusercontent.com/1132541/149357750-e544bb91-d44d-4715-9b2c-d0b2d5945c0f.png) |

### PHP Version

7.4

### Plugin Version

2.2.0

### AMP plugin template mode

Transitional

### WordPress Version

5.8.3

**Comment by westonruter** [comment]
The lack of output is due to there being a validation error:

![image](https://user-images.githubusercontent.com/134745/149394533-b58c1c1f-6fb8-4758-bfc3-17fefd50b991.png)

The issue is that `AMP_Iframe_Sanitizer` is normally able to handle this case, as it is able reuse this logic in `AMP_Base_Sanitizer::set_layout()`:

https://github.com/ampproject/amp-wp/blob/bf8aa7f9cdb05c1ea745b69578f6bbbee495f876/includes/sanitizers/class-amp-base-sanitizer.php#L455-L458

However, the YouTube video conversion is happening in a subclass of `AMP_Base_Embed_Handler` not `AMP_Base_Sanitizer`. So this is not available to us directly.

**Comment by dhaval-parekh** [comment]
✅ **QA Passed.**

The Youtube embeds (used in an iframe) are now converting into the `amp-youtube` component.

| Before                                                                                                                                   | After                                                                                                                                    |
|------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="592" alt="image" src="https://user-images.githubusercontent.com/8168027/151568349-45d3c92f-48e1-4f54-b92d-dd29d17d7642.png"> | <img width="628" alt="image" src="https://user-images.githubusercontent.com/8168027/151568249-4ca0b48a-736c-4001-80a2-e90b8717e9f9.png"> |



Markup of the `amp-youtube` component.
```html
<amp-youtube layout="fixed-height" width="auto" height="315" data-videoid="s52JNMT59s8" class="i-amphtml-layout-fixed-height i-amphtml-layout-size-defined" style="height:315px" i-amphtml-layout="fixed-height"><a placeholder="" href="https://www.youtube.com/watch?v=s52JNMT59s8"><amp-img src="https://i.ytimg.com/vi/s52JNMT59s8/hqdefault.jpg" layout="fill" object-fit="cover" class="amp-wp-enforced-sizes i-amphtml-layout-fill i-amphtml-layout-size-defined" data-hero i-amphtml-ssr i-amphtml-layout="fill"><img class="i-amphtml-fill-content i-amphtml-replaced-content" decoding="async" src="https://i.ytimg.com/vi/s52JNMT59s8/hqdefault.jpg" style="object-fit:cover"></amp-img></a></amp-youtube>
```
