### ISSUE TITLE
Custom Post Type not working

### ISSUE THREAD

**Issue by matif78** [Automattic/amp-wp#684]
Hi,
I am trying to add custom post type but nothing is showing when i add /amp

Can you please tell me where i am wrong.

// Custom Post Type AMP //

add_action( 'amp_init', 'xyz_amp_add_review_cpt' );
function xyz_amp_add_review_cpt() {
add_post_type_support( 'betting-site', AMP_QUERY_VAR );
}
add_filter( 'amp_post_template_file', 'xyz_amp_set_review_template', 10, 3 );

function xyz_amp_set_review_template( $file, $type, $post ) {
if ( 'single' === $type && 'betting-site' === $post->post_type ) {
$file = dirname( FILE ) . '/single-betting-site.php';
}
return $file;
}

**Comment by k-atul** [comment]
either try flushing your site permalinks or try below
$file = dirname( __FILE__ ) . '/single-betting-site.php';

**Comment by amedina** [comment]
Most likely will be solved by a flushing of the rewrite rules, as suggested by @k-atul.
