### ISSUE TITLE
AMP Carousel no longer works in WP 5.9 or latest Gutenberg

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#6848]
### Bug Description

Relates to #6832
Relates to #6508

The AMP Carousel feature no longer works for the core Gallery block on WordPress 5.9-beta or the latest Gutenberg plugin version.

This is caused by the fact that the core Gallery block has been updated recently. Instead of storing media IDs in the block attributes property, the images are output as core Image blocks. Because of that, the new gallery no longer consist of a UL list. Instead, a set of FIGURE elements are used:

| Legacy gallery markup | New gallery markup |
| --- | --- |
| ![Screenshot 2022-01-20 at 15 27 55](https://user-images.githubusercontent.com/478735/150357577-6bf9d6d3-daf6-48fb-9d66-b10ffa24915c.png) | ![Screenshot 2022-01-20 at 15 27 36](https://user-images.githubusercontent.com/478735/150357596-78be3f34-474f-4e0a-8857-118f62fd3577.png) |

### Expected Behaviour

Toggling the "Display as carousel" option in the block editor should enable AMP Carousel on WordPress 5.9 and latest Gutenberg.

### Screenshots

| Editor | Frontend |
| --- | --- |
| ![Screenshot 2022-01-20 at 15 22 07](https://user-images.githubusercontent.com/478735/150356618-c319d63e-062a-4fa5-8beb-7796789a7cee.png) | ![Screenshot 2022-01-20 at 15 22 20](https://user-images.githubusercontent.com/478735/150356636-ba28271d-636e-4fb1-a901-ad3724a7d360.png) |

 

### Plugin Version

2.2

### AMP plugin template mode

Transitional

### WordPress Version

5.8.3

### Gutenberg Version

12.0.1

**Comment by westonruter** [comment]
I'm investigating this. It may end up making sense to fix as part of #6833. I may amend that PR with what I find.

**Comment by westonruter** [comment]
OK, I think I got it. See https://github.com/ampproject/amp-wp/pull/6833/commits/6271ffc3197acbb39346f818d7a66d3d54ce9f3b.

**Comment by dhaval-parekh** [comment]
✅ **QA Passed**

-  "Display as carousel" option in the Gallary block is working fine with new markup (as well as with old markup)
