### ISSUE TITLE
Site scan fail with custom post type

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#6855]
### Bug Description

When the user selects only a custom post type to be served by AMP, at the plugin's settings the site scan fails. To reproduce this behavior, I have created a simple custom post type and selected only this CPT to be served by AMP.  The result is, the site scan started to fail because wasn't able to find AMP URLs. 

### Expected Behaviour

If the user selects a specific custom post type, the site scan should be able to point to the new URLs

### Screenshots

**Selecting Custom post type** 
![Screen Shot 2022-01-25 at 16 30 52](https://user-images.githubusercontent.com/330792/151018464-46080ea2-3cc6-43cf-9ae8-1827c12e3f09.png)

**Site scan results**
![Screen Shot 2022-01-25 at 16 29 44](https://user-images.githubusercontent.com/330792/151018537-53fc09c1-171a-453a-91b9-5a09d9a66054.png)

**Site scan URLs not available** 
![Screen Shot 2022-01-25 at 16 33 01](https://user-images.githubusercontent.com/330792/151018752-f06909ab-0264-44f6-909e-0f68ed647213.png)

### PHP Version

7.4

### Plugin Version

2.2

### AMP plugin template mode

Reader

### WordPress Version

5.8.3

### OS(s) Affected

Mac

### Browser(s) Affected

Chrome

**Comment by westonruter** [comment]
Did you create a Movie post in addition to having registered the post type?

**Comment by fellyph** [comment]
Hi @westonruter,

No, I haven't it was empty when I checked. 
When I've included one Movie post it is working fine. 
<img width="1098" alt="Screen Shot 2022-01-25 at 22 38 47" src="https://user-images.githubusercontent.com/330792/151071823-c872d452-8099-4b8f-9c42-fdd1fc6f900f.png">

**Comment by westonruter** [comment]
OK, then that's probably a pretty rare scenario, right? 

If anything, when no scannable URLs are returned perhaps a special notice should be displayed saying that no URLs are available. This would be better and more specific than "Site scan failed. Try again."

**Comment by fellyph** [comment]
Sure, this is a rare scenario.

The message is not clear, that is why I got confused. 

For example, if no post type is selected a different message is displayed:

<img width="1096" alt="Screen Shot 2022-01-25 at 23 50 19" src="https://user-images.githubusercontent.com/330792/151079316-0e392a54-c1f8-4995-9a77-3c7e4e76e7f8.png">

**Comment by fellyph** [comment]
**QA Passed**

Site scan before: 
<img width="1133" alt="Screen Shot 2022-01-29 at 08 43 39" src="https://user-images.githubusercontent.com/330792/151654467-bc7808d2-32e3-4cd6-93ab-2a91711c7f75.png">

Site scan version 2.2.x:
<img width="1120" alt="Screen Shot 2022-01-29 at 08 44 43" src="https://user-images.githubusercontent.com/330792/151654476-37391097-a977-47a4-a58b-fb174f91b530.png">
