### ISSUE TITLE
Improve determination of eligible post types for AMP

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6883]
### Feature Description

As noted in https://github.com/ampproject/amp-wp/pull/6881#issuecomment-1029267449:

> the only post types that are eligible for being AMP-enabled are those which have `'public' => true`:
> 
> https://github.com/ampproject/amp-wp/blob/36edf69661e8ee6c7c35bce1c483c9524dbf386f/includes/class-amp-post-type-support.php#L44-L64
> 
> It's true that a post type could have `public` set to true but have `publicly_queryable` set to false, I think, and in that case it may be possible that we could accidentally show or hide the preview button. It would be marginally better to here instead do the following since there is now a `is_post_type_viewable` filter in WP 5.9:
> 
> ```diff
> diff --git a/includes/class-amp-post-type-support.php b/includes/class-amp-post-type-support.php
> index 3d4560641..17eb6519b 100644
> --- a/includes/class-amp-post-type-support.php
> +++ b/includes/class-amp-post-type-support.php
> @@ -42,14 +42,9 @@ public static function get_builtin_supported_post_types() {
>  	 * @return string[] Post types eligible for AMP.
>  	 */
>  	public static function get_eligible_post_types() {
> -		$post_types = array_values(
> -			get_post_types(
> -				[
> -					'public' => true,
> -				],
> -				'names'
> -			)
> -		);
> +		$post_types = array_values( get_post_types( [], 'names' ) );
> +
> +		$post_types = array_filter( $post_types, 'is_post_type_viewable' );
>  
>  		/**
>  		 * Filters the list of post types which may be supported for AMP.
> ```

### Acceptance Criteria

Only post types for which `is_post_type_viewable()` returns `true` should be listed among the post types for which AMP can be enabled. Only these post types should have an AMP preview button shown in a paired AMP mode (transitional or reader).

**Comment by dhaval-parekh** [comment]
Step for QA is provided here https://github.com/ampproject/amp-wp/pull/6897#issuecomment-1084258761

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Eligible post types for AMP are visible in Supported Templates section

<img width="1162" alt="Screenshot 2022-03-31 at 2 21 20 PM" src="https://user-images.githubusercontent.com/41000648/161016337-8665ed38-ae80-4edd-b03d-58c2692e32fa.png">
