### ISSUE TITLE
Whitelist Sanitizer Improvements

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#689]
With the sanitizer merged as part of #600, it would be nice to have the following updates:

- [x] Make filters into args that args that are passed via the constructor (follows the convention of other sanitizers). There are some filters we can probably remove for now as well.
- [x] Remove `test-data`; not used.

### Spec Generation Script

- [x] Minor: The script should do the `git clone` be able to output the generated class in the right directory (fixed in #823)

### Code Quality

- [ ] Flatten out `is_amp_allowed_attribute`
- [ ] Flatten out `check_attr_spec_rule_mandatory`
- [x] Minor: Update constants in `AMP_Spec` to be uppercase

**Comment by westonruter** [comment]
@mjangda do you have any further info on what you had in mind for flattening out those two methods?

Otherwise, I think this issue can be closed.

**Comment by westonruter** [comment]
We can re-open if need be.
