### ISSUE TITLE
AMP Preview button is not showing up in WP 5.6, 5.7, and 5.8 initially

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#6893]
I've just noticed an issue: the preview button is not showing up in WP 5.6, 5.7, and 5.8 until the user makes a change and then saves a draft. 

https://user-images.githubusercontent.com/134745/152435922-22360a24-892e-441e-8577-f17f71af929d.mov

It seems the container is empty:

![image](https://user-images.githubusercontent.com/134745/152436149-37b3741c-117e-42d5-bc53-ee948773316c.png)

And also, when I load a post that is _published_ I see the button show up for a moment and then disappear until I make a change and save the post:

https://user-images.githubusercontent.com/134745/152436429-7a6ba4fd-e53b-4017-8dc5-91a896a2e1bb.mov

It doesn't happen in either 5.9 or in 5.7 or 5.8 with the latest Gutenberg is active.

So I don't consider this a blocker for 2.2.1, but it should be fixed in 2.2.2.

_Originally posted by @westonruter in https://github.com/ampproject/amp-wp/issues/6881#issuecomment-1029444377_

**Comment by dhaval-parekh** [comment]
✅  **QA Pass**

Test in WordPress 5.8 (Similar result found in WordPress versions 5.6 and 6.7)

**Before**

https://user-images.githubusercontent.com/8168027/161268889-956739ba-540a-438f-82fd-754ff3e34acc.mov


**After** 

https://user-images.githubusercontent.com/8168027/161268551-3e85a17d-7c28-427f-afd2-0860f79fbf4e.mov

--- 

Similar results ( As shown in after video ) were found in the latest version the WordPress (5.9.2) with the new changes (and even without new changes)
