### ISSUE TITLE
Undefined class constant 'TIKTOK'

### ISSUE THREAD

**Issue by adrianvintu** [Automattic/amp-wp#6899]
### Bug Description

When requesting to see any article https://adrianvintu.net/articole/ like this one https://adrianvintu.net/2021/11/26/bitcoin-ul-la-romani/ as an AMP by addyng /amp/ to the link https://adrianvintu.net/2021/11/26/bitcoin-ul-la-romani/amp/, an error message appears:

![2022-02-07 17_34_38-Window](https://user-images.githubusercontent.com/33379688/152819703-b6576a53-88a0-4d86-b9b4-4f7adbbbdfec.png)

The stack is:
```
[07-Feb-2022 15:27:35 UTC] A PHP error occurred while trying to prepare the AMP response. This may not be caused by the AMP plugin but by some other active plugin or the current theme. You will need to review the error details to determine the source of the error. - Undefined class constant 'TIKTOK' (0) [Error]
#0 /home/adrvin1/adrianvintu.net/wp-content/plugins/amp/includes/sanitizers/class-amp-embed-sanitizer.php(47): AMP_TikTok_Embed_Handler->sanitize_raw_embeds(Object(AmpProject\Dom\Document), Array)
#1 /home/adrvin1/adrianvintu.net/wp-content/plugins/amp/includes/templates/class-amp-content-sanitizer.php(147): AMP_Embed_Sanitizer->sanitize()
#2 /home/adrvin1/adrianvintu.net/wp-content/plugins/amp/includes/class-amp-theme-support.php(2035): AMP_Content_Sanitizer::sanitize_document(Object(AmpProject\Dom\Document), Array, Array)
#3 /home/adrvin1/adrianvintu.net/wp-content/plugins/amp/includes/class-amp-theme-support.php(1753): AMP_Theme_Support::prepare_response('<!doctype html>...')
#4 [internal function]: AMP_Theme_Support::finish_output_buffering('<!doctype html>...', 9)
#5 /home/adrvin1/adrianvintu.net/wp-includes/functions.php(5212): ob_end_flush()
#6 /home/adrvin1/adrianvintu.net/wp-includes/class-wp-hook.php(307): wp_ob_end_flush_all('')
#7 /home/adrvin1/adrianvintu.net/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#8 /home/adrvin1/adrianvintu.net/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#9 /home/adrvin1/adrianvintu.net/wp-includes/load.php(1100): do_action('shutdown')
#10 [internal function]: shutdown_action_hook()
#11 {main}
```

AMP version is:
![2022-02-07 17_36_49-Window](https://user-images.githubusercontent.com/33379688/152820132-d323862a-e600-490a-a64c-bb29f9c2f838.png)

### Expected Behaviour

Expected to not show error message but the amp page.

### PHP Version

 PHP 7.4.14 (cli) (built: Feb  9 2021 19:30:37) ( NTS ) Copyright (c) The PHP Group Zend Engine v3.4.0, Copyright (c) Zend Technologies     with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

### Plugin Version

2.2.1

### AMP plugin template mode

Reader

### WordPress Version

5.9

**Comment by westonruter** [comment]
The issue is probably because you have both the Accelerated Mobile Pages plugin _and_ the AMP plugin active at the same time. If the Accelerated Mobile Pages plugin includes an old copy of the `Extension` class, then it may not have its `TIKTOK` constant defined yet.

You can see that `Extension::TIKTOK` is present in the latest plugin version: https://plugins.trac.wordpress.org/browser/amp/tags/2.2.1/vendor/ampproject/amp-toolbox/src/Extension.php#L163

Either this is bug for the Accelerated Mobile Pages plugin, or you should deactivate one of the plugins.

**Comment by adrianvintu** [comment]
Deactivating 
```
AMP for WP - Accelerated Mobile Pages for WordPress
Versiunea 1.0.77.35 | De [Ahmed Kaludi, Mohammed Kaludi](https://ampforwp.com/) 
```
fixed the issue.

Thank you for your support.
