### ISSUE TITLE
PHP 8 Warning

### ISSUE THREAD

**Issue by fellyph** [Automattic/amp-wp#6921]
### Bug Description

A user at the AMP Support forum [reported](https://wordpress.org/support/topic/error-log-warnings-2/) the following warning:

`[09-Feb-2022 19:33:57 UTC] PHP Warning: Undefined array key "url" in /home/../wp-content/plugins/amp/src/Validation/ScannableURLsRestController.php on line 181
[09-Feb-2022 19:33:57 UTC] PHP Warning: Undefined array key "url" in /home/../wp-content/plugins/amp/src/Validation/ScannableURLsRestController.php on line 186`

### Expected Behaviour

Not display the warnings on PHP 8

### PHP Version

8.0.13

### Plugin Version

2.2.1

### AMP plugin template mode

Standard

### WordPress Version

5.9

**Comment by dhaval-parekh** [comment]
I'm not able to reproduce this issue with PHP version 8.0.16, And with same the AMP configuration provided  in `ampwp-16f02fc7-3324-5533-882a-b1cb9de83705` support request.

Waiting for further information from [WordPress.org support](https://wordpress.org/support/topic/error-log-warnings-2/)
