### ISSUE TITLE
Site Health test for page caching does not account for `wp_remote_retrieve_header()` returning arrays

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#6937]
### Bug Description

As reported in a [support forum topic](https://wordpress.org/support/topic/amp-plugin-breaks-my-site/), an error can occur in the page caching detection test:

```
An error of type E_ERROR was caused in line 548 of the file /var/www/html/a-c-d.net/public_html/wp-content/plugins/amp/src/Admin/SiteHealth.php. Error message: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /var/www/html/a-c-d.net/public_html/wp-content/plugins/amp/src/Admin/SiteHealth.php:548
Stack trace:
#0 /var/www/html/a-c-d.net/public_html/wp-content/plugins/amp/src/Admin/SiteHealth.php(548): preg_match()
#1 /var/www/html/a-c-d.net/public_html/wp-content/plugins/amp/src/Admin/SiteHealth.php(634): AmpProject\AmpWP\Admin\SiteHealth::AmpProject\AmpWP\Admin\{closure}()
#2 /var/www/html/a-c-d.net/public_html/wp-content/plugins/amp/src/Admin/SiteHealth.php(491): AmpProject\AmpWP\Admin\SiteHealth->check_for_page_caching()
#3 /var/www/html/a-c-d.net/public_html/wp-content/plugins/amp/src/Admin/OptionsMenu.php(230): AmpProject\AmpWP\Admin\SiteHealth->get_page_cache_detail()
#4 /var/www/html/a-c-d.net/public_html/wp-includes/class-wp-hook.php(307): AmpProject\AmpWP\Admin\OptionsMenu->enqueue_assets()
#5 /var/www/html/a-c-d.net/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /var/www/html/a-c-d.net/public_html/wp-includes/plugin.php(474): WP_Hook->do_action()
#7 /var/www/html/a-c-d.net/public_html/wp-admin/admin-header.php(118): do_action()
#8 /var/www/html/a-c-d.net/public_html/wp-admin/admin.php(239): require_once(‘…’)
```

The `preg_match()` call in question is here:

https://github.com/ampproject/amp-wp/blob/7c2b5ae700c460bea95fda7e68dde145ae6a0537/src/Admin/SiteHealth.php#L547-L549

The `$header_value` is being passed here:

https://github.com/ampproject/amp-wp/blob/7c2b5ae700c460bea95fda7e68dde145ae6a0537/src/Admin/SiteHealth.php#L626-L639

So apparently we're not accounting for `wp_remote_retrieve_header()` returning an array instead of a string.

Note the site is running PHP 8.1 which is the cause for the fatal due to the additional strictness.

### Expected Behaviour

No error should occur.

### PHP Version

8.1

### Plugin Version

2.1.4

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by milindmore22** [comment]
another user [reported](https://wordpress.org/support/topic/amp-page-caching-detected-3/) error

**Comment by dhaval-parekh** [comment]
✅ **QA Passed**

With then new changes Fatal error is not occurring when `wp_remote_retrieve_header()` returning arrays [here](https://github.com/ampproject/amp-wp/blob/7c2b5ae700c460bea95fda7e68dde145ae6a0537/src/Admin/SiteHealth.php#L627).

Notes: I couldn't able to reproduce this issue without modifying the code, And testing is done after tweaking the code to reproduce this issue.
