### ISSUE TITLE
Parent theme with AMP incompatibilities is greyed-out in the Site Scan results

### ISSUE THREAD

**Issue by delawski** [Automattic/amp-wp#6958]
### Bug Description

When both a child theme and its parent cause AMP incompatibilities, the parent theme appears to be inactive in the Site Scan results. This affects AMP Settings screen and in the Onboarding Wizard.

### Expected Behaviour

Both child and the parent theme should be displayed as active (similarly to plugins) if they cause AMP incompatibilities.

### Screenshots

![Screenshot 2022-03-05 at 13 12 07](https://user-images.githubusercontent.com/478735/156894479-1c6ef698-1fa0-4620-b025-8d0750c71893.png)
 

### Plugin Version

2.2.1

### AMP plugin template mode

Standard, Transitional

### WordPress Version

5.9

**Comment by delawski** [comment]
This has been discovered while working on #6814 / #6859.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Before: Parent theme being greyed out

<img width="1263" alt="parent-theme-after-scan-greyed-out" src="https://user-images.githubusercontent.com/41000648/159296267-9c501def-3664-4789-95ef-0395f6ade437.png">

---

After: Parent theme looks fine

<img width="1277" alt="parent-theme-after-scan-looks-fine" src="https://user-images.githubusercontent.com/41000648/159296414-9d7cce20-3f28-4e90-b038-8c09726dc2e8.png">

---
