### ISSUE TITLE
Youtube AMP script loaded, but amp-iframe is used

### ISSUE THREAD

**Issue by R3dRidle** [Automattic/amp-wp#697]
There is an issue when adding a Youtube video. It does succesfuly add the right script:
<script custom-element="amp-youtube" src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js" async></script>

But when you look at the code it still user <amp-iframe in stead of <amp-youtube

This should be fixed as Google states that this could become a problem in the future.
The extension 'amp-youtube extension .js script' was found on this page, but is unused (no 'amp-youtube' tag seen). This may become an error in the future.

https://www.ampproject.org/docs/reference/components/amp-youtube

**Comment by amedina** [comment]
Thanks for reporting this. Could you add a snippet showing the addition of a Youtube video to your AMP page? Will help to try to reproduce the problem.

**Comment by R3dRidle** [comment]
By example this is my page with the error:
https://www.webton.nl/blog/amp-ranking/amp.html

As you an see it adds the youtube amp js sucessfully, yet it uses amp-iframe tag.

I use my own template and this is the function i use to sanitize my content:
`function add_custom( $data ) {
    $amp_content = new AMP_Content( $data,
        apply_filters( 'amp_content_embed_handlers', array(
			'AMP_Twitter_Embed_Handler' => array(),
			'AMP_YouTube_Embed_Handler' => array(),
			'AMP_DailyMotion_Embed_Handler' => array(),
			'AMP_SoundCloud_Embed_Handler' => array(),
			'AMP_Instagram_Embed_Handler' => array(),
			'AMP_Vine_Embed_Handler' => array(),
			'AMP_Facebook_Embed_Handler' => array(),
			'AMP_Gallery_Embed_Handler' => array(),
		)),
        apply_filters( 'amp_content_sanitizers', array(
				 'AMP_Style_Sanitizer' => array(),
				 // 'AMP_Blacklist_Sanitizer' => array(),
				 'AMP_Img_Sanitizer' => array(),
				 'AMP_Video_Sanitizer' => array(),
				 'AMP_Audio_Sanitizer' => array(),
				 'AMP_Playbuzz_Sanitizer' => array(),
				 'AMP_Iframe_Sanitizer' => array(
					 'add_placeholder' => true,
				 ),
				 'AMP_Tag_And_Attribute_Sanitizer' => array(),
			) )
    );
    return $amp_content->get_amp_content();
}`

**Comment by R3dRidle** [comment]
Ahw and i just the oEmbed within the normal editor from ACF. So i basicly just copy a Youtube URL and paste it.

**Comment by amedina** [comment]
Cannot reproduce this problem. I am adding a youtube link to an AMP post and the amp-youtube component is being generated properly. This is the link I added to the post: https://www.youtube.com/watch?v=PahsgJn0sgU

Check that the youtube embed is added in this way.

**Comment by R3dRidle** [comment]
Sorry, but this is exacylu what i am doing. It is still an issue!

**Comment by amedina** [comment]
Can you paste here the YouTube link you are embedding in your post?

**Comment by R3dRidle** [comment]
That would be this link:
http://www.youtube.com/watch?v=Rit5bVrFmlw

![screen](https://user-images.githubusercontent.com/13661524/27897482-e15f8a1e-6220-11e7-8d7d-4d9763888cba.PNG)
