### ISSUE TITLE
Unable to install as git submodule

### ISSUE THREAD

**Issue by anubisthejackle** [Automattic/amp-wp#6974]
### Bug Description

It appears we are unable to install as a git submodule using the `2.2.1-built` tag, as the branch was deleted and left the tag as an orphan.

### Expected Behaviour

We should be able to install as a git submodule.

### Plugin Version

2.2.1

### AMP plugin template mode

Standard

**Comment by anubisthejackle** [comment]
Scratch this. I didn't realize I wasn't getting the tags when I ran fetch.

`git fetch --all --tags` found the right tag for me, and I was able to update my submodule.

**Comment by westonruter** [comment]
Excellent. 

(BTW, your surname is great.)
