### ISSUE TITLE
AMP Settings Page > Site Scan screen there should be space between buttons

### ISSUE THREAD

**Issue by pooja-muchandikar** [Automattic/amp-wp#7001]
### Bug Description

Site scan screen can we have some padding between the Rescan Site and Browse Site buttons?

The buttons looks attached on click.

### Expected Behaviour

There should be some padding between the buttons

### Screenshots

![image](https://user-images.githubusercontent.com/41000648/160322039-b0e8a0d6-e5b5-4d88-b9d9-e01e0199854b.png)

### Plugin Version

2.2.2alpha

### AMP plugin template mode

Standard

### WordPress Version

5.9.2

**Comment by westonruter** [comment]
I see this is also the case for the Review section:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/134745/160711164-c7fe0b87-89ad-4ae0-8780-3a52c72ce579.png">

**Comment by westonruter** [comment]
In the Onboarding Wizard there is a 1rem space: 

<img width="408" alt="image" src="https://user-images.githubusercontent.com/134745/160711518-d0edd31a-f315-44a6-bc9b-821e10cad863.png">

**Comment by westonruter** [comment]
I believe it will be as simple as this:

```diff
diff --git a/assets/src/settings-page/style.css b/assets/src/settings-page/style.css
index e22f669a8..0e65d6fad 100644
--- a/assets/src/settings-page/style.css
+++ b/assets/src/settings-page/style.css
@@ -578,6 +578,10 @@ li.error-kept {
 	padding-right: 2.25rem;
 }
 
+.amp .settings-site-scan__footer .components-button + .components-button {
+	margin-left: 1rem;
+}
+
 /* Review. */
 #site-review {
 	margin-bottom: 2.5rem;
@@ -637,6 +641,10 @@ li.error-kept {
 	padding-right: 2.25rem;
 }
 
+.amp .settings-site-review__actions .components-button + .components-button {
+	margin-left: 1rem;
+}
+
 /* Other Settings */
 .amp-other-settings section + section {
 	margin-top: 2rem;
```

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Spacing between buttons is fixed for Site Scan and Review section. 

### Before: 
Site Scan Section
<img width="1240" alt="Screenshot 2022-03-30 at 11 48 06 AM" src="https://user-images.githubusercontent.com/41000648/160764282-d02c0d73-de25-46ed-a230-e9ea74bd07d6.png">

---

Review Section
<img width="1138" alt="Screenshot 2022-03-30 at 11 49 24 AM" src="https://user-images.githubusercontent.com/41000648/160764446-a4d1b97b-0fd9-4968-928c-67bde73a62ea.png">

---

### After fix:
Site Scan Section
<img width="1257" alt="Screenshot 2022-03-30 at 11 38 57 AM" src="https://user-images.githubusercontent.com/41000648/160764549-94f0af2f-d79b-449d-87c1-c91c225733bb.png">

---

Review Section
<img width="1141" alt="Screenshot 2022-03-30 at 11 42 27 AM" src="https://user-images.githubusercontent.com/41000648/160764761-dfdc34eb-9102-43a9-a8d6-5f3341902878.png">

---
