### ISSUE TITLE
UI glitch in Site scanning in safari browser (version 14.0.3)

### ISSUE THREAD

**Issue by dhaval-parekh** [Automattic/amp-wp#7013]
### Bug Description

As mentioned in https://github.com/ampproject/amp-wp/issues/6807#issuecomment-1076212257 by @pooja-muchandikar

> **But found an regression issue on Safari Browser Version 14.0.3** 
>
> On site scan screen from AMP settings page and also on Onboarding Wizard, the error displayed for theme/plugins are not aligned. The title of plugin/theme appears below the arrow
>
> Onboarding Wizard Screen
> 
> <img width="1254" alt="Screenshot 2022-03-23 at 11 00 02 AM" src="https://user-images.githubusercontent.com/41000648/159630979-544465c6-a346-4f05-8093-1af39529809b.png">

### Expected Behaviour

UI should be consistent in the safari browser safari browser (version 14.0.3)

### Plugin Version

2.2.2-alpha

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 
The UI looks fine in Safar browser 14.0.3 and also the latest version. 

UI looks fine in Chrome too..

Safari Version 14.0.3
<img width="1107" alt="Screenshot 2022-03-31 at 10 50 37 AM" src="https://user-images.githubusercontent.com/41000648/160982081-e3326340-39f0-493b-a5ef-92747c6a1abf.png">

---

Safari Version 15
<img width="1008" alt="Screenshot 2022-03-31 at 10 46 01 AM" src="https://user-images.githubusercontent.com/41000648/160982169-680fcce1-380c-4b23-b142-5e5cebdd6b14.png">

---

<img width="934" alt="Screenshot 2022-03-31 at 10 43 01 AM" src="https://user-images.githubusercontent.com/41000648/160982196-dea45a21-c62f-431e-8746-1c5e8c465411.png">
