### ISSUE TITLE
Not supported AMP

### ISSUE THREAD

**Issue by tofunofficel** [Automattic/amp-wp#7033]
### Bug Description

![Screenshot_20220407-060020_Chrome](https://user-images.githubusercontent.com/67199357/162097088-2fda8680-fbce-4035-bdbf-2b4405b19b19.jpg)

### Expected Behaviour

AMP not support
My PHP & WordPress both are updated. But Steel showing critical error.

### Screenshots

![Screenshot_20220407-060020_Chrome](https://user-images.githubusercontent.com/67199357/162097115-e44abb71-a314-49b8-940a-eac007e44021.jpg)

### PHP Version

8.0

### Plugin Version

2.2.3

### AMP plugin template mode

Reader

### Site Health

Good

**Comment by milindmore22** [comment]
Hello @tofunofficel 

We provide support using [WordPress Support Forums](https://wordpress.org/support/plugin/amp/#new-topic-0), 
Please visit AMP->Support and and Generate the UUID

Here is how
https://www.youtube.com/watch?v=wXoHwRvYsW8&t

Once you got UUID please [create a support topic](https://wordpress.org/support/plugin/amp/#new-topic-0) using WordPress Support forum, add details about your issue and UUID.
