### ISSUE TITLE
Add toggle to manage whether native `img` is used instead of `amp-img` and add admin pointer

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7035]
### Feature Description

With #6805 we're now defaulting to native `img` instead of `amp-img`. However, this could have unintended side effects (e.g https://github.com/ampproject/amp-wp/issues/7029#issuecomment-1090497930) since `amp-img` has been around from the beginning and there may be CSS selectors written that specifically target `amp-img`. Previously the CSS sanitizer would convert `img` selector to `amp-img` (and `amp-anim`) while converting the elements in the DOM. But when using native image, no such conversion is done. So if someone was expecting to style an image with `amp-img` this would no longer match.

Therefore, in order to mitigate this major change it is warranted to add a new toggle to the Settings screen in the Advanced section for whether native `img` is enabled. True this can be managed via a PHP filter as well, but this would require a user to add a mini plugin which is greater friction than just a simple toggle. The toggle should be omitted or disabled if a site has any `amp_native_img_used` filter.

Upon upgrading to 2.3, there should be an admin pointer that alerts users to the fact that native images are now being used, with a deep link to that toggle in the Settings screen. The toggle description should advise users to check their site for issues with images rendering, and if so, to try turning off native images to see if that resolves the issue.

**Comment by westonruter** [comment]
To avoid headaches with regressions where `img` isn't yet supported fully (e.g. https://github.com/ampproject/amp-wp/issues/7029#issuecomment-1090497930), I think we should continue to default to `amp-img` and then have a toggle to opt-in to native `img`.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

- Toggle is implemented to manage whether to use native img instead of amp-img
- With this toggle being disable, the image will have `amp-img` by default
- If toggle is enabled, then image will use `img` ✅ 


https://user-images.githubusercontent.com/41000648/172150813-8b0b07dd-607a-469b-90da-93065f308145.mov

---
