### ISSUE TITLE
Use Non-AMP link in transitional mode

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/amp-wp#7067]
### Feature Description

Currently while using transitional mode, all internal links are appended with paired URL structure like /amp/. 

An option can be added to keep all internal links on page as non-amp, this is for use case where first page can be AMP from SERP and then next page visit utilise all features (which are not supported by AMP as of now)

**Comment by westonruter** [comment]
AMP-to-AMP linking is enabled by default when either:

1. You're using Transitional mode.
2. You have mobile redirection enabled in Reader mode.

You can turn off AMP-to-AMP linking with this filter:

```php
add_filter( 'amp_to_amp_linking_enabled', '__return_false' );
```
