### ISSUE TITLE
Slow query in wp_postmeta

### ISSUE THREAD

**Issue by llpereiras** [Automattic/amp-wp#708]
Hi Guys, I got this warning in new relic.

![amp-slow-query](https://user-images.githubusercontent.com/3936337/26935080-6aae1740-4c41-11e7-90d9-86ab704df781.png)

My table wp_postmeta has indexer in meta_key field.

So, What more could be done to resolve this problem ?

It's could be a specific problem in the plugin ?

Thanks for help.

**Comment by aimarv** [comment]
Despite the efforts already done, the way the AMP plugin handles images is a source of... slowness

If this is a screenshot from New Relic then you can already see it on top 3 slowest plugins list - I do :(

**Comment by amedina** [comment]
Hi @llpereiras, Cannot check/reproduce if there is any factor only related to the plugin playing a factor in the reported slow query. We are currently making changes to the plugin and will address performance issues as much as possible. Thanks for using the plugin and filing your comments.
