### ISSUE TITLE
Injection into the amp plugin

### ISSUE THREAD

**Issue by ReeseStrive** [Automattic/amp-wp#710]
Just noticed today that there is an injection on my site that only shows within the amp view itself. Has anyone else seen this at all? 

![image](https://user-images.githubusercontent.com/29292842/26956002-9966b2e4-4c6f-11e7-8c08-35ea16987f9a.png)

All amp pages that have text had this injected into it.

Ideas? wpengine is no use and say to come here so, any help is appreciated. I dont want to have to uninstall the plugin.

**Comment by nicopujol** [comment]
Are you file permissions locked from external writes for the AMP folder and files?

**Comment by amedina** [comment]
This is not  an issue with the plugin. Closing for now. Please reopen and provide more details if still experiencing it.
