### ISSUE TITLE
Custom user post display

### ISSUE THREAD

**Issue by saritahealthtotal12** [Automattic/amp-wp#712]
Hello Team,
please let me know about ,
In AMP, As per user post selection in admin panel , in front end home page post listing should be display.
Please give me solution to display user selected post on site....

**Comment by amedina** [comment]
Please follow the following format to specify clearly the issue experienced:

## What's the issue?

Briefly describe the bug/feature request.

## How do we reproduce the issue?

If this is a bug please provide a public URL and ideally a reduced test case that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:

1. Step 1 to reproduce
2. Step 2 to reproduce
3. …

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.
