### ISSUE TITLE
Scripts added by PWA plugin on error template are removed by sanitizer

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7122]
### Bug Description

The PWA plugin adds a couple scripts to the error template:

```html
<script id="wp-navigation-request-properties" type="application/json">{{{WP_NAVIGATION_REQUEST_PROPERTIES}}}</script>	<script type="module">
		const shouldRetry = () => {
			if (
				new URLSearchParams(location.search.substring(1)).has(
					'wp_error_template'
				)
			) {
				return false;
			}

			const navigationRequestProperties = JSON.parse(
				document.getElementById('wp-navigation-request-properties').text
			);
			if ('GET' !== navigationRequestProperties.method) {
				return false;
			}

			return true;
		};

		if (shouldRetry()) {
			/**
			 * Listen to changes in the network state, reload when online.
			 * This handles the case when the device is completely offline.
			 */
			window.addEventListener('online', () => {
				window.location.reload();
			});

			// Create a counter to implement exponential backoff.
			let count = 0;

			/**
			 * Check if the server is responding and reload the page if it is.
			 * This handles the case when the device is online, but the server is offline or misbehaving.
			 */
			async function checkNetworkAndReload() {
				try {
					const response = await fetch(location.href, {
						method: 'HEAD',
					});
					// Verify we get a valid response from the server
					if (response.status >= 200 && response.status < 500) {
						window.location.reload();
						return;
					}
				} catch {
					// Unable to connect so do nothing.
				}
				window.setTimeout(
					checkNetworkAndReload,
					Math.pow(2, count++) * 2500
				);
			}

			checkNetworkAndReload();
		}
	</script>
```

These are getting stripped from the page when in Moderate/Strict standboxing, and in Loose they are getting retained with a `data-amp-unvalidated-tag` attribute added to them. In Loose mode, this is causing the CSS processing to be disabled, resulting in no `style[amp-custom]` to be added to the page. Since the PWA plugin relies on the runtime cache to store CSS files, this means that when the Offline page is served to the user, no stylesheets will be available in the cache.

The fix is simple: we need to add a PWA sanitizer which adds `data-px-verified-tag` to both of these scripts.

### Expected Behaviour

Scripts on PWA error template should not trigger the Loose sandboxing level.

### Screenshots

> <img width="707" alt="image" src="https://user-images.githubusercontent.com/134745/170547515-01948838-9deb-479e-a040-397aaa41ef7f.png">

### Plugin Version

2.3-alpha

### AMP plugin template mode

Standard

### WordPress Version

6.0

**Comment by maitreyie-chavan** [comment]
Having @thelovekesh pick this one up

**Comment by thelovekesh** [comment]
Thanks, @maitreyie-chavan!  I’ve begun working on this and will aim to send over the PR by Monday.

**Comment by thelovekesh** [comment]
@westonruter I think sanitizer should work on both offline and 500 pages as we have added reload script to both.

It will result something like:
```php
class AMP_PWA_Plugin_Sanitizer extends AMP_Base_Sanitizer {

	public function sanitize() {
		if (
			! ( function_exists( 'is_offline' ) && is_offline() ) &&
			! ( function_exists( 'is_500' ) && is_500() )
		) {
			return;
		}

		$scripts = $this->dom->getElementsByTagName( Tag::SCRIPT );

		foreach ( $scripts as $script ) {
			if (
				( 'wp-navigation-request-properties' === $script->getAttribute( Attribute::ID ) ) ||
				( 'module' === $script->getAttribute( Attribute::TYPE ) && false !== strpos( $script->textContent, 'checkNetworkAndReload()' ) )
			) {
				ValidationExemption::mark_node_as_px_verified( $script );
			}
		}
	}
}
```

**Comment by westonruter** [comment]
@thelovekesh That looks like it will work. I think it could be optimized a bit further by using XPath to query for the two scripts as opposed to looping over all scripts on the page.

**Comment by thelovekesh** [comment]
> That looks like it will work.

I have tested it and it's working fine. I will optimize it further by using XPath to query.

I have named the file `class-amp-pwa-plugin-sanitizer.php`. Does it look right to you?

**Comment by westonruter** [comment]
> I have named the file `class-amp-pwa-plugin-sanitizer.php`. Does it look right to you?

Let's call it rather `class-amp-pwa-script-sanitizer.php` since if PWA is merged into core then it wouldn't be a plugin anymore.

**Comment by thelovekesh** [comment]
@westonruter Should I introduce a filter to generate an XPath query?
e.g.
```php
$scripts = array(
    'script-id-1',
    'script-id-2'
)

$scripts = apply_filters( 'amp-pwa-script-sanitizer', $scripts )
```

There can be use cases when users want to add more scripts in offline or 500 error pages. Thoughts?

**Comment by westonruter** [comment]
@thelovekesh nah, I think that would be overkill.

**Comment by westonruter** [comment]
✅ **QA Passed**

I deployed to weston.ruter.net and when I was offline I saw:

> <img width="654" alt="image" src="https://user-images.githubusercontent.com/134745/173421426-d4476226-bf26-49ac-94eb-710969903135.png">

The scripts have `data-px-verified-tag` as expected:

> <img width="883" alt="image" src="https://user-images.githubusercontent.com/134745/173421908-ed08117c-0ba1-4f09-87b8-b8c158ea317d.png">

And because all PX-verified, stylesheet processing is retained:

> <img width="367" alt="image" src="https://user-images.githubusercontent.com/134745/173422020-56a0689a-ccad-45a5-9b6e-a202c31fed57.png">

----

Aside: Because a Mustache template tag is used in place of the JSON `script` for the offline template, the AMP optimizer transformer complains about invalid JSON not allowing it to optimize it:

> <img width="422" alt="image" src="https://user-images.githubusercontent.com/134745/173422346-28d4bba4-97ec-45e0-9998-e47686906b24.png">

In this case it's no problem, except for the error causing some unnecessary noise. That's more something to think about for the PWA plugin than AMP here.
