### ISSUE TITLE
amp-base-carousel heights attribute is not rendered properly.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7130]
### Bug Description

We got a [support topic](https://wordpress.org/support/topic/icons-not-displaying-when-amp-is-activated/), from a theme developer who was working to implement amp-base-carousel and found out that the heights attribute is not properly rendered when used with the AMP plugin.

Sample Code to reproduce the issue.

```html
<amp-base-carousel layout="responsive" width="1" height="1" heights="(min-width: 1199px) 23%,(min-width: 900px) 31.33%,(min-width: 600px) 48%, 100%" visible-count="(min-width: 1199px) 4,(min-width: 900px) 3,(min-width: 600px) 2, 1" auto-advance="true" auto-advance-interval="3000">
    <div>
      <img src="https://amp-support.rt.gw/wp-content/uploads/2008/06/img_8399.jpg" />
    </div>
    <div>
      <img src="https://amp-support.rt.gw/wp-content/uploads/2008/06/img_0767.jpg" />
    </div>
    <div>
      <img src="https://amp-support.rt.gw/wp-content/uploads/2008/06/img_0747.jpg" />
    </div>
    <div>
      <img src="https://amp-support.rt.gw/wp-content/uploads/2008/06/img_0513-1.jpg" />
    </div>
    <div>
      <img src="https://amp-support.rt.gw/wp-content/uploads/2008/06/windmill.jpg" />
    </div>
    <div>
      <img src="https://amp-support.rt.gw/wp-content/uploads/2008/06/michelle_049.jpg" />
    </div>
  </amp-base-carousel>
  ```
The non-AMP version renders correctly, but the AMP version has seen extra height. aligning the carousel on top and controls at the center of the carousel.

The above observation also occurs when the heights attribute is removed.

You can find more examples on the [AMP Support test site](https://amp-support.rt.gw/2022/06/01/amp-base-carousel-test/?amp=1). (let me know if you need access to it)

### Expected Behaviour

The non-AMP and AMP version should have the same height.

### Screenshots

| non-AMP  | AMP |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1132541/171472724-51489f69-d0f7-4d75-a8ed-88683b1fb6cc.png) |  ![image](https://user-images.githubusercontent.com/1132541/171472809-c149c166-17e7-4b33-9068-50c9a7bd4cb1.png) |

### PHP Version

7.4

### Plugin Version

2.2.4

### AMP plugin template mode

Transitional

### WordPress Version

6

### Gutenberg Version

not active

**Comment by westonruter** [comment]
@ediamin Is this the same as you reported in https://github.com/ampproject/amp-toolbox/issues/1314 and https://github.com/ampproject/amp-toolbox-php/issues/511?

**Comment by westonruter** [comment]
Or it could be https://github.com/ampproject/amp-toolbox/issues/1304.

@milindmore22 If you turn off SSR does that fix the issue?

**Comment by milindmore22** [comment]
@westonruter Yes, If I turn off SSR it does fixes that issue

**Comment by ediamin** [comment]
Yes, I believe it's related to the inline padding-top property of the sizer element.

**Comment by milindmore22** [comment]
Recently [merged PR](https://github.com/ampproject/amp-wp/pull/7121) by @ediamin fixed the issue, tested on dev
