### ISSUE TITLE
CTP + Routing + Endpoint problem

### ISSUE THREAD

**Issue by IIM-Andreas** [Automattic/amp-wp#7140]
Hi
i have my problem with a special case.

Example:
I have a custom post type with the slug foobar. I didn't like the routing so I made a custom route 
`'<domain>/cakes/<foobar-name>/bar'`.
This CTP routing works fine.
But when I then call 
`'<domain>/cakes/<foobar-name>/bar/amp'`
with the AMP plugin, I get a 302 redirect (back to `'<domain>/cakes/<foobar-name>/bar'`) and not the appropriate amp page.

Best regards
Andreas

**Comment by milindmore22** [comment]
@IIM-Andreas 

All support requests are handled on WordPress support forums,  please create a [new support topic](https://wordpress.org/support/plugin/amp/#new-topic-0) on the WordPress support forum, and please share the code that registers your custom post type in the Support forum description along with your AMP Support UUID 

AMP support UUID can be generated by visiting AMP->Support

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/wXoHwRvYsW8/0.jpg)](http://www.youtube.com/watch?v=wXoHwRvYsW8)
