### ISSUE TITLE
Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7148]
### Bug Description

When running `npm install` now, I'm getting:

```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

### Expected Behaviour

No warning.

### Plugin Version

2.3.0

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by thelovekesh** [comment]
QA Passed ✅ 

While running `npx browserslist@latest --update-db` on the default branch there are no target browser changes.

![image](https://user-images.githubusercontent.com/54371619/216688704-137d99a5-7a14-4777-8c92-8359c407437f.png)
