### ISSUE TITLE
Add a fallback Settings.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7155]
### Feature Description

We are getting a lot of support topics where they can't access settings this might be due to third-party plugins or themes conflicting sometimes wrong configuration etc. we can't pinpoint a single issue.
example topics: [topic1](https://wordpress.org/support/topic/amp-settings-something-went-wrong-2/) [topic2](https://wordpress.org/support/topic/amp-scan-fails-cannot-read-properties-of-null/#post-15737242), [topic3](https://wordpress.org/support/topic/amp-plugin-javascript-error-and-outdated-content/#post-15739588)

My idea is to add fallback settings with something simple like Settings API or something custom but simple and doesn't use scripts, where users can at least access basic settings like template mode, Reader Theme selection, Supported template, Mobile redirection, Plugin suppression, etc.

The Fallback Setting will come into action (we will show a link or button for fallback settings) on LoadingError

This will enable users to access settings with their conflicting plugin or theme.

Adding it to the loading error will indicate that there are more features like site scan and wizard that are not working for them because of the conflicting plugins and they are using fallback settings.

**Comment by milindmore22** [comment]
another [support topic](https://wordpress.org/support/topic/cannot-read-properties-of-null-reading-type-3/)

**Comment by westonruter** [comment]
Adding fallback settings would essentially be bringing back the old settings screen which relied on the Settings API, with full page reloads and no JS being required. However, I'd want to avoid adding a parallel UI for managing settings. Maybe we can be more aggressive about ensuring our polyfilled scripts are loaded? What if the loading error message had a link which had a query parameter that caused the page to load with our script polyfills forced? Currently polyfills are only loaded on older versions of WordPress (<5.6). If we force our polyfilled scripts in ≥5.6 if requested, would this allow the pages to load successfully?

**Comment by westonruter** [comment]
@milindmore22 Do you think that a WP-CLI interface for the settings (https://github.com/ampproject/amp-wp/issues/5783) would satisfy this well enough?

**Comment by milindmore22** [comment]
@westonruter yes, that will also work!
cc : @thelovekesh

**Comment by westonruter** [comment]
Closing in favor of the WP-CLI alternative.
