### ISSUE TITLE
Using html_entity_decode

### ISSUE THREAD

**Issue by talgalili** [Automattic/amp-wp#716]
I just discovered (way too late), that using `$content = html_entity_decode($content);` with  `add_filter('the_content','fun_name);` will lead to MANY errors in the AMP page.
I'm not sure if this is something you can detect in the plugin, but thought it is worth mentioning.

**Comment by amedina** [comment]
Hi @talgalili, which type of errors were generated?

You are correct with respect to the fact that we are not be able to detect all cases like this. Similar things may happen with the addition of plugins that tinker with content once it has been processed by the plugin. 

Closing this for now as it is not an actual issue with the plugin; feel free to comment further or reopen if you'd like to contribute additional things.
