### ISSUE TITLE
How is the AMP component supported in Gutenberg Block

### ISSUE THREAD

**Issue by Bruse-Lee** [Automattic/amp-wp#7164]
I'm having a hard time developing gutenberg block.

AMP is enabled in my WordPress plug-in, so that my posts have AMP Page and non-AMP

The Gutenberg Block I developed is a search box that references custom scripts, which works well on non-AMP pages
But this doesn't work in AMP pages.I don't know how to modify my Gutenberg block to support AMP

Here is the core of my code, can someone tell me what to do?

![my-script](https://user-images.githubusercontent.com/62770320/174984984-59c82489-dc25-49b6-a083-312efb88cfc0.png)

![not-render](https://user-images.githubusercontent.com/62770320/174985400-86e0baf2-246e-47f2-bd9a-aa550d168b14.png)

**Comment by westonruter** [comment]
Is the screenshot of the rendering from the frontend? It could be that `amp-script` tag is getting stripped out due to Kses. You may need to add it to the allowlist via the `wp_kses_allowed_html` filter. For example:

```php
add_filter( 'wp_kses_allowed_html', static function ( $tags ) {
    $tags['amp-script'] = array_fill_keys( [ 'src', 'sandbox' ], true );
    return $tags;
} );
