### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\OnlineExam\home.php on line 54

### ISSUE THREAD

**Issue by mahamudxmx** [Automattic/amp-wp#718]
home
=======

<table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>name</th>
        <th>email</th>
		<th>image</th>
      </tr>
    </thead>
    <tbody>
	
	<?php
	foreach($profile->data as $prof)
	{ 
	?> 
	<tr>
	<td><?php echo $prof['id']; ?></td>
	<td><?php echo $prof['name']; ?></td> 
	<td><?php echo $prof['email']; ?></td>
	<td><img src="img/<?php echo $prof['img']; ?>" alt="" width="25px" height="20px" /></td>
	</tr> 
	</tbody>
	<?php 
	} 
	?>
  </table>

users.php
=========
<?php
session_start();
class users{
	
	public $host="localhost";
	public $username="root";
	public $pass="";
	public $db_name="exam_app";
	public $conn;
	public $data;
	
	public function __construct()
	{
		$this->conn=new mysqli($this->host,$this->username,$this->pass,$this->db_name);
		if($this->conn->connect_errno)
		{
			die ("database connection failed".$this->conn->connect_errno);
		}
	}
	
	public function signup($data)
	{
		$this->conn->query($data);
		return true;
	}
	
	
	public function signin($email,$pass)
	{
		$query=$this->conn->query("select email,pass from signup where email='$email' and pass='$pass'");
		$query->fetch_array(MYSQLI_ASSOC);
		if($query->num_rows>0)
		{
			$_SESSION['email']=$email;
			return true;
		}
		else
		{
			return false;
		}
	}
	public function users_profile($email)
	{
		$query=$this->conn->query("select * from signup where email='$email'");
		$row=$query->fetch_array(MYSQLI_ASSOC);
		if($query->num_rows>0)
		{
			$tihs->data[]=$row;
		}
		return $this->data;
	}
	
	public function url($url)
	{
		header("location:".$url);
	}
	
}

?>

**Comment by amedina** [comment]
Closing since it is not a properly reported issue.
