### ISSUE TITLE
No drop down menu on mobiles with AMP enabled

### ISSUE THREAD

**Issue by redac2022** [Automattic/amp-wp#7186]
### Bug Description

In mobile version, my drop-down menu no longer works with AMP enabled. 
I am using Elementor Pro, OCEAN theme.
(AMP currently desactivated)

### Expected Behaviour

I would like to be able to continue using the AMP plugin but this dropdown needs to work

### Screenshots

website : [https://redacteur-seo-freelance.com](https://redacteur-seo-freelance.com)

### PHP Version

7.4.25

### Plugin Version

AMP 2.3.0

### AMP plugin template mode

Standard

### WordPress Version

6.0

**Comment by westonruter** [comment]
Hi there. Please open a topic on our support forum: https://wordpress.org/support/plugin/amp/
