### ISSUE TITLE
Plugin removes `lighbox` attribute when using native `img` instead of `amp-img`

### ISSUE THREAD

**Issue by rafaucau** [Automattic/amp-wp#7193]
### Bug Description

When the `Use native HTML image tag` option is enabled, this plugin considers the lightbox attribute as invalid and removes it by default.

### Expected Behaviour

The attribute is valid and should not be deleted or reported as invalid.

### Screenshots

![image](https://user-images.githubusercontent.com/25438601/180645235-ecac828a-3612-4578-8d49-76d01dafa59b.png)
![image](https://user-images.githubusercontent.com/25438601/180645198-021431fd-dbac-4871-8250-f6ab7f226ad7.png)
![image](https://user-images.githubusercontent.com/25438601/180645210-3ac0ca3e-9f60-4929-a7ea-3a4fc7eac643.png)
![image](https://user-images.githubusercontent.com/25438601/180645442-0def9854-ba0e-4f07-ad03-887137558bff.png)

### PHP Version

8.1

### Plugin Version

2.3.0

### AMP plugin template mode

Transitional

### WordPress Version

6.0

**Comment by westonruter** [comment]
@rafaucau Thanks for reporting. We've actually fixed this recently in #7158 (for #7152), but it's not yet released. If you want to test the fix in a pre-release build, you can do so at https://github.com/ampproject/amp-wp/wiki/Development-Builds
