### ISSUE TITLE
Update the Wordpress.org version

### ISSUE THREAD

**Issue by israelshmueli** [Automattic/amp-wp#720]
Current wordpress.org version of this plugin is **8 month old**. And triggers PHP notices in customizer screen.
https://wordpress.org/support/topic/error-amp_customizer_design_settingsregister_customizer_ui/#post-9249212
Seems that you fixed it here.
It would be nice to have it working properly even if downloaded from WordPress.org.

**Comment by amedina** [comment]
@israelshmueli Thanks for filing an issue; we are working on updating the version of the plugin in Wordpress.org. Stay tuned. Will close this issue for now; will reopen later if needed.

**Comment by amedina** [comment]
Check: https://github.com/Automattic/amp-wp/issues/697

**Comment by amedina** [comment]
Plugin has been updated!
