### ISSUE TITLE
Select a coloured theme to you social media

### ISSUE THREAD

**Issue by edwarddekker** [Automattic/amp-wp#721]
Hi @mjangda,

I want to know if we could select a variety coloured theme.

As for now could we select a white or dark theme. I would have some more choices and having the ability to select my own colours from the administration panel. Also these colour scheme should applied to all kind of social media where we can find this at `wp-content/plugins/amp/includes/embeds/`.

Regards,
Edward

**Comment by amedina** [comment]
Hi @edwarddekker, thanks for using the plugin and filing your request. We are working on ways to enhance the look-and-feel of the templates used by the plugin and also leveraging the underlying theme of any given site. Hopefully in such cases you will have more control over the theme via the regular mechanisms in WP (e.g. the customizer). 

Closing this issue for now. Stay tuned :).
