### ISSUE TITLE
How to remove data-ampdevmode=""

### ISSUE THREAD

**Issue by balajidamodare** [Automattic/amp-wp#7256]
### Bug Description

How to remove or disable adding this attribute data-ampdevmode=""?

### Expected Behaviour

This is a question but here don't have the option to raise a question so I selected it as bug sorry for that. because of this I can't validate directly local and dev ENV on the AMP validator.

so please help to disable the data-ampdevmode="" attribute through a plugin.

### Screenshots

![Screenshot 2022-09-13 at 5 38 55 PM](https://user-images.githubusercontent.com/8907250/189897085-077dc79e-3f86-4325-8464-93246a2b0f6a.png)

### PHP Version

8

### Plugin Version

2.3.0

### AMP plugin template mode

Reader

### WordPress Version

6.0.1

**Comment by milindmore22** [comment]
Hello @balajidamodare 

The `data-ampdevmode=""` attribute will be added only when the user is logged in and if you have the WordPress admin bar enabled.

I'll mark this as resolved Open a <a href="https://wordpress.org/support/plugin/amp/#new-topic-0" rel="noopener" target="_blank">new support topic</a> in WordPress Support forum if you face further issues.
