### ISSUE TITLE
Extend Sandboxing experiment to Paired AMP modes

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7268]
### Feature Description

Currently the Sandboxing experiment is limited to Standard mode. This is because pages using the experiment are not valid AMP, meaning they will not get indexed. Nevertheless, invalid paired AMP pages are still useful for one important case: a mobile-optimized version of the site. When mobile redirection is enabled in particular, being able to serve pages using the AMP runtime and our optimizations (e.g. Reader theme) will enable the plugin to be usable as a "mobile theme" plugin.

- [x] Show the Sandboxing experiment panel when any template mode is selected on the Settings screen, not just when the Standard mode is selected.
- [x] When a non-strict sandboxing level is selected, _never_ output the `link[rel=amphtml]` element but _always_ output `link[rel=alternate]` which is output when mobile redirection is enabled. The reason here is that we do not want to advertise to Googlebot in this case that there is an AMP page because then it will complain if there are validation errors.
- [x] Prevent redirecting from AMP to non-AMP when in a paired mode if the Sandboxing level is not set to Strict (and there is kept invalid markup).
- [x] https://github.com/ampproject/amp-wp/issues/5293

**Comment by westonruter** [comment]
> * Prevent redirecting from AMP to non-AMP when in a paired mode if the Sandboxing level is not set to Strict.

This specifically has in mind this code:

https://github.com/ampproject/amp-wp/blob/08906e47d2d5ee7e2b5aaf34fd84aff1e8738c95/includes/validation/class-amp-validation-manager.php#L2035-L2052

Note the check for `amp_is_canonical()`. Essentially this needs to be changed to also return `true` if sandboxing is enabled and it is set to level 1 or 2. This will prevent redirecting to the non-AMP version when there is invalid markup that is kept making the page invalid AMP.

**Comment by westonruter** [comment]
> Prevent redirecting from AMP to non-AMP when in a paired mode if the Sandboxing level is not set to Strict (and there is kept invalid markup).

This can be seen by creating a post with the following content:

```html
<!-- wp:paragraph -->
<p>This is a script using <code>document.write()</code>:</p>
<!-- /wp:paragraph -->

<!-- wp:html -->
<script>document.write('HELLO WORLD');</script><noscript>SCRIPT WAS BLOCKED</noscript>
<!-- /wp:html -->
```

If I then set template mode to Reader mode and enable _loose_ sandboxing, I see:

![image](https://user-images.githubusercontent.com/134745/217156625-093cd5da-05fd-4af0-b6a3-8079d14742e1.png)

Notice how even though there is invalid AMP markup, it is not redirecting to the non-AMP page. (Actually, this should rather be tested when the user is logged-out, and indeed I see that is the case.) Instead the `amp` attribute is removed from the `html` element.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

> Show the Sandboxing experiment panel when any template mode is selected on the Settings screen, not just when the Standard mode is selected.

**Before**
The sandboxing experiment panel was visible only in standard mode. 

![image](https://user-images.githubusercontent.com/44057535/217017038-5ae7473e-416c-47ec-b5a1-822556813fcc.png)

**After fix:** 
Now the sandboxing experiment panel is visible in all three modes. 

![image](https://user-images.githubusercontent.com/44057535/217017308-f04ae6f2-a9c4-40ca-b591-29803f3ac0c7.png)


---


> When a non-strict sandboxing level is selected, never output the link[rel=amphtml] element but always output link[rel=alternate] which is output when mobile redirection is enabled. The reason here is that we do not want to advertise to Googlebot in this case that there is an AMP page because then it will complain if there are validation errors

Now, In transitional mode with the sandboxing strict mode, the link[rel=amphtml] is added and with the loose/moderate mode the link[rel=alternate] is displayed and link[rel=amphtml] is not visible. 


**sandboxing strict mode:** 
![image](https://user-images.githubusercontent.com/44057535/217018525-f5f2ef94-9f18-4e10-bc8f-312eb14ba651.png)


**sandboxing Loose/moderate mode:** 
![image](https://user-images.githubusercontent.com/44057535/217019742-67dcd127-4784-4777-acb2-f75458396f6e.png)

---

> Prevent redirecting from AMP to non-AMP when in a paired mode if the Sandboxing level is not set to Strict (and there is kept invalid markup).

After setting the reader sandboxing to lose/moderate mode, the page is not rendering to non-AMP mode. working fine. 

![image](https://user-images.githubusercontent.com/44057535/217183228-c9768930-d2fc-4aad-8f60-cef56772b967.png)
