### ISSUE TITLE
Missing embedded video on AMP page

### ISSUE THREAD

**Issue by KhalidAlmallahi** [Automattic/amp-wp#727]
Hello 

we receive this message from google :

Google systems have detected AMP pages on your site that are missing videos contained in their corresponding canonical pages. Users expect to find all of the relevant content on an AMP page they would find on the equivalent canonical page. For the best user experience, we strongly recommend embedding all relevant videos in both pages.

What can do ?

**Comment by KhalidAlmallahi** [comment]
Link:

https://goo.gl/ZvN2pB
https://goo.gl/r8WuMi
https://goo.gl/NefYbs

**Comment by amedina** [comment]
@KhalidAlmallahi In[ this link](http://abunawaf.com/%D9%83%D8%B4%D9%81-%D8%A7%D9%84%D9%86%D9%82%D8%A7%D8%A8-%D8%B9%D9%86-%D9%85%D8%B9%D8%A7%D9%86%D9%8A-%D8%A7%D9%84%D8%A3%D9%84%D9%82%D8%A7%D8%A8/amp/) from the list, I can't see the videos being included in the canonical page. 

Please provide detailed information about the issue, including the video embed type you are trying to use, and the version of the plugin used.

**Comment by amedina** [comment]
Closing this for now; please comment if problem persists and provide more info to track it. Thanks!
