### ISSUE TITLE
Redirecting desktop request to AMP Mobile page

### ISSUE THREAD

**Issue by balajidamodare** [Automattic/amp-wp#7270]
### Bug Description

Hi There,

Not sure if this is a bug or a question.
but when I am hitting AMP URL on the Desktop it's redirecting to AMP Page how we can redirect only mobile requests to AMP pages otherwise keep all Desktop requests on the Normal page.

### Expected Behaviour

If Requests came form mobile instead of redirecting it to the AMP page it needs to show the normal desktop page.

### PHP Version

8.0

### Plugin Version

2.3.0

### AMP plugin template mode

Reader

**Comment by milindmore22** [comment]
Hello @balajidamodare 

There seems some confusion, 

If you visit a non-AMP page on the desktop it will not redirect to the AMP page but if you visit the non-AMP page on Mobile it will redirect to the AMP page.

It's very unlikely that users will find an AMP page when they search for something on a desktop unless he is using Standard Mode or directly using AMP page URL

If a user searches for something on mobile he will get a result page that may contain an AMP cache, which is most likely the mobile version of the AMP page (Accelerated Mobile Pages )

Please create a new support topic in case you have [further questions](https://wordpress.org/support/plugin/amp/#new-topic-0)
