### ISSUE TITLE
Incorrect assumption of hex input by `ReaderThemeSupportFeatures::get_relative_luminance_from_hex()`

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7285]
### Bug Description

See [support forum topic](https://wordpress.org/support/topic/php-8-0-compatibility-error/).

The `ReaderThemeSupportFeatures::get_relative_luminance_from_hex()` method incorrectly assumes hex input:

https://github.com/ampproject/amp-wp/blob/a373ac8f65f26ee7df7313ff5d734b5704781ab0/src/ReaderThemeSupportFeatures.php#L364-L383

It turns out that in some cases, a theme may be passing a CSS variable like `var(--base-2)`, or presumably `rgba(...)` could also be passed.

To account for this, the `print_editor_color_palette_styles` method should skip passing the color value into `get_relative_luminance_from_hex` when it is not a valid hex.

This could be achieved by adding:

```php
if ( ! preg_match( '/^[0-9a-f]{3}[0-9a-f]{3}?$/i', ltrim( $color_option[ self::KEY_COLOR ], '#' ) ) ) {
    continue;
}
```

After the following condition (or as part of it):

https://github.com/ampproject/amp-wp/blob/a373ac8f65f26ee7df7313ff5d734b5704781ab0/src/ReaderThemeSupportFeatures.php#L281-L286

### Expected Behaviour

If a non-hex color is used, no deprecated error should be raised from `hexdec()` here:

https://github.com/ampproject/amp-wp/blob/a373ac8f65f26ee7df7313ff5d734b5704781ab0/src/ReaderThemeSupportFeatures.php#L375-L377

### Plugin Version

2.3.0

### AMP plugin template mode

Reader

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue with the below snippet and the fix is working as expected. 

```php
add_action(
	'after_setup_theme',
	static function() {
		add_theme_support( 'editor-color-palette', array(
			array(
				'name'  => 'bar',
				'slug'  => 'bar',
				'color' => 'var(--bar)',
			)
		) );
	}
);
```

Before: 


https://user-images.githubusercontent.com/44057535/216975393-947f475f-fcdf-41f7-80fd-96bf964524eb.mp4


**After fix:** 

https://user-images.githubusercontent.com/44057535/216977042-7d6494e3-de28-428d-936d-19cade6a096e.mp4
