### ISSUE TITLE
Add support for <amp-sidebar>

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#729]
Check: [amp-sidebar](https://www.ampproject.org/docs/reference/components/amp-sidebar)

This component can be used to implement menus/navigation use cases.

**Comment by westonruter** [comment]
Support for `amp-sidebar` is now present in 0.7; any theme that includes an `amp-sidebar` tag will get the required component script included. I don't think there's anything else needed in the plugin itself. It now goes to themes to leverage.
