### ISSUE TITLE
wp_nav_menu suffix in Custom links to remote websites

### ISSUE THREAD

**Issue by stouch** [Automattic/amp-wp#7329]
### Bug Description

This plugin adds a suffix /amp to my custom links to remote websites in my footer menu (wp_nav_menu).

My blog is under a subpath (/blog) so I was able to manually remove this suffix (and keep it only for my blog links) with :

```
		if(strstr($parsed_url['path'], 'blog')){
			$parsed_url['path'] .= user_trailingslashit( amp_get_slug(), 'amp' );
		}
```
in `amp/src/PairedUrl.php`.

### Expected Behaviour

The suffix must no be added to custom links in wp menus.

### PHP Version

7.3

### Plugin Version

latest

### AMP plugin template mode

Transitional

**Comment by westonruter** [comment]
The plugin should only be adding the AMP endpoint to links on the same domain as the WP install. Are you saying it is adding the link to other parts of your site which are not part of the WordPress subdirectory install? What does `home_url()` return for you?

The logic for determining whether a given link should get the AMP endpoint is as follows:

https://github.com/ampproject/amp-wp/blob/092b4b8a717c0ed7d7dc257fe5e042e6aab566f9/includes/sanitizers/class-amp-link-sanitizer.php#L280-L319

It seems it is not taking into account the `path` of the `home_url` and is only considering the `host`.

Nevertheless, there is a filter you should be able to use to prevent this from happening in the immediate term. Something like this should do it:

```php
add_filter( 
  'amp_to_amp_linking_element_excluded', 
  static function( $excluded, $url ) {
    if ( ! str_contains( $url, '/blog' ) ) {
      $excluded = true;
    }
    return $excluded;
  }, 
  10, 
  2
);
```

**Comment by stouch** [comment]
Thanks. 
Actually, We have a website under ourdomain.com/app and we have our blog under /blog. And we have some wp_nav_menu custom links that point to  ourdomain.com/app/xxx etc.
I already had an issue with the fact that this plugin does not handle well the case when wp is hosted under a subdirectory : 
https://github.com/ampproject/amp-wp/issues/6399

Thank you for your add_filter solution (I did not tested it yet)

**Comment by westonruter** [comment]
@thelovekesh Would you update the logic in `is_frontend_url()` to verify that the provided `$url` has the same `path` prefix as the `home_url()`? We an add a `home_path` member variable where we are currently storing the `home_host`:

https://github.com/ampproject/amp-wp/blob/092b4b8a717c0ed7d7dc257fe5e042e6aab566f9/includes/sanitizers/class-amp-link-sanitizer.php#L82

```php
$parsed_home     = wp_parse_url( home_url() );
$this->home_host = $parsed_home['host'];
$this->home_path = $parsed_home['path'];
```

**Comment by westonruter** [comment]
@stouch The fix has been merged, and there is a pre-release production build you can test: https://github.com/ampproject/amp-wp/pull/7330#issuecomment-1308283943

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue, Fix is working as expected. Now, the suffix(/amp) for the custom link is not visible. 

**Update**
Steps to test: 
1. On the multisite network, Create two sub-directory site named `/app`, `/blogs` and enable the AMP plugin on any one of these sites and enable the transitional mode. 
2. Now add the custom link from the non-amp site to the AMP site. 
3. Once done, validate the Custom link from the AMP site. The result should be as follows:

**Before:**
![image](https://user-images.githubusercontent.com/44057535/217040232-9e6a304f-9330-40b3-9bb1-c803d4b8fe40.png)

**After Fix:**
![image](https://user-images.githubusercontent.com/44057535/217036343-171740f9-70a9-4b3b-ab6c-778b1d4e5a57.png)
