### ISSUE TITLE
Theme customizer gets initialized outside of admin area.

### ISSUE THREAD

**Issue by EkoAlex** [Automattic/amp-wp#733]
I noticed that the theme customizer changes that the plugin integrates get initialized even on the frontend regardless of whether the user is an admin or not. 

In `amp.php`:

```php
function _amp_bootstrap_customizer() {
	$amp_customizer_enabled = apply_filters( 'amp_customizer_is_enabled', true );

	if ( true === $amp_customizer_enabled ) {
		amp_init_customizer();
	}
}
add_action( 'plugins_loaded', '_amp_bootstrap_customizer', 9 );
```

Wouldn't it make more sense to only load them when the admin is accessing the theme customizer?

**Comment by westonruter** [comment]
No. The Customizer needs to be able to bootstrap in any request, whether in the admin or not. When the Customizer preview window loads, it's actually the frontend of the site, but with the Customizer bootstrapped. You'll see that core as well looks to bootstrap the Customizer at `plugins_loaded`: https://github.com/WordPress/wordpress-develop/blob/138ffd4/src/wp-includes/default-filters.php#L406
