### ISSUE TITLE
Optimize Production Composer Build to reduce needless file lookups

### ISSUE THREAD

**Issue by andyblackwell** [Automattic/amp-wp#7337]
### Bug Description

I recently did an optimization pass on our sites, and after profiling them found that several plugins with local composer /vendor builds were not fully optimized for production, AMP being one of these.

The plugin's local composer autoloader is not built with `--classmap-authoritative`, and by default the composer ClassLoader will prepend itself to the list of autoloaders. Both of these issues combined can cause thousands of needless file lookups for classes flowing through this loader that it doesn't need to handle. When not built with `--classmap-authoritative` and a class isn't found in the local classmap, then composer makes a few fallback attempts to find the class, resulting in all the needless file lookups.

Looks like this plugin already uses `--optimize-autoloader`, so would propose adding `--classmap-authoritative`
so adding either of these to the production build:  `-oa` or `--optimize-autoloader --classmap-authoritative`

and potentially also adding `prepend-autoloader: false` to the composer.json config, so this autoloader doesn't prepend itself ahead of other more site specific autoloaders:
```
"config": {
    "prepend-autoloader": false
}
```

### Expected Behaviour

Expected behavior is that the local composer build **only** handles autloading the classes it includes.

### Plugin Version

2.3.0

### AMP plugin template mode

Standard, Transitional, Reader

### WordPress Version

6.0.2

**Comment by westonruter** [comment]
Thank you for this. Closely related to #7324 which we're also investigating right now.

**Comment by thelovekesh** [comment]
QA Passed ✅ 

There are file lookups when we execute `composer install --no-dev -o`:
![image](https://user-images.githubusercontent.com/54371619/216913125-5299394e-cdf8-4ffe-8822-58154f2419fe.png)

There are no file lookups when we execute `composer install --no-dev -oa`(i.e. composer autoload is build with `--classmap-authoritative`):
![image](https://user-images.githubusercontent.com/54371619/216913596-8ba9ca3c-c2ba-47ac-95e2-a3733dde9f85.png)

**Comment by westonruter** [comment]
Wow! How did you generate those graphs?

**Comment by thelovekesh** [comment]
Used Xdebug profiler(wp-env) and visualized them using [KCachegrind](https://kcachegrind.sourceforge.net/).
