### ISSUE TITLE
AMP breaks site functionality

### ISSUE THREAD

**Issue by artby04** [Automattic/amp-wp#7338]
### Bug Description

I installed the amp plugin, there were no compatibility errors.

After installation, the site stopped working as it should. For example: the self-written form for submitting stopped working
(photo below)

Also, the built-in chat and recaptcha stopped working.

How can I fix this and is it possible at all?

### Expected Behaviour

Everything is working

### Screenshots

![2022-11-11 11 50 07](https://user-images.githubusercontent.com/52202830/201302562-d99759d7-8fe1-4ef9-90bc-c6cf834a510d.jpg)

### PHP Version

7.3

### Plugin Version

2.3.0

### AMP plugin template mode

Transitional

### WordPress Version

5.8

**Comment by milindmore22** [comment]
@artby04 We provide support actively on WordPress support forums, Please [create a new support topic](https://wordpress.org/support/plugin/amp/#new-topic-0) on WordPress Support forums
