### ISSUE TITLE
“Buy now” button act as “add to cart” instead of link to product page

### ISSUE THREAD

**Issue by johocen168** [Automattic/amp-wp#7356]
### Feature Description

When connecting "Shopping" with WooCommerce in the web story setting, the "Shop Now" button will bring up the product page with product title, price, images and description (which is retrived from the product page of WooCommerce) together with a “Buy now” button.

Click the “Buy now” button will link to the product page of WooCommerce again, means the visitor will see the same product information twice (maybe some extra info in the product page of WooCommerce), which is quite confusion. 

Suggest the “Buy now” button should act as “add to cart” instead of link to product page for quick shopping, or make it optional for admin, if link to product page is needed.

**Comment by milindmore22** [comment]
@johocen168  We provide support actively on WordPress support forums, Please [create a new support topic](https://wordpress.org/support/plugin/amp/#new-topic-0) on WordPress Support forums

**Comment by johocen168** [comment]
I was guided from [web story](https://wordpress.org/support/topic/settingshoppingmanage-products-in-woocommerce/) plugin support to here...you could log an [AMP project GitHub request](https://github.com/ampproject/amphtml/issues/new/choose)

Anyway, I will create a new support topic on WordPress Support forums.
Thanks
