### ISSUE TITLE
Amp storing way too many transient into wp_options database

### ISSUE THREAD

**Issue by joesatch** [Automattic/amp-wp#737]
is there any way for making this plugin not storing transient into database, my wp_option table grows to 60k rows (yeah its considerably still small) but its great if we have some options to make it little bit efficient for small/minimum specs server.

thanks!

**Comment by westonruter** [comment]
Yes, if you switch to using a [persistent external object cache](https://codex.wordpress.org/Class_Reference/WP_Object_Cache#Persistent_Cache_Plugins) like Memcached or Redis (and you should), then the transients will not be stored in the database.
