### ISSUE TITLE
Fatal error (division by zero) in `AMP_Core_Theme_Sanitizer::add_twentytwenty_custom_logo_fix()` 

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7427]
### Bug Description

See [support topic](https://wordpress.org/support/topic/critical-error-on-amp-version-of-site/).

This code is not accounting for the case where the site logo image for some reason has a height of zero:

https://github.com/ampproject/amp-wp/blob/4e54b03dce6f360845bfde5dbd19f85cccab7287/includes/sanitizers/class-amp-core-theme-sanitizer.php#L878-L879

This is also the case in this line:

https://github.com/ampproject/amp-wp/blob/4e54b03dce6f360845bfde5dbd19f85cccab7287/includes/sanitizers/class-amp-core-theme-sanitizer.php#L590

In both cases, we should make sure that when we cast the value to `int` that it is not zero, and if so, bail.

### Expected Behaviour

No fatal error caused by division by zero should occur when site logo has an unexpected height of zero.

### Plugin Version

2.3.0

### AMP plugin template mode

Standard, Transitional

**Comment by milindmore22** [comment]
Just an Observation the user who reported this error is using an SVG image for logo

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue, Used the below snippet to verify the issue. The fix is working as expected. 

```
if ( 'Twenty Twenty' === wp_get_theme()->get('Name') || 'Twenty Seventeen' === wp_get_theme()->get('Name') ) {
	add_filter(
		'get_custom_logo',
		static function () {
			return '<img src="https://avatars.githubusercontent.com/u/14114390?v=4" width="200" height="0">';
		}
	);
}
```

**Before:** 

![image](https://user-images.githubusercontent.com/44057535/216965534-bcba9721-75ae-43bd-8246-2f1bbd48885c.png)


**After fix:**

![image](https://user-images.githubusercontent.com/44057535/216966964-aa05f570-91f1-4017-bb7f-2b90620dc850.png)
