### ISSUE TITLE
Replace references to 2.3.1 with 2.4.0

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7428]
### Feature Description

Since we're going to skip `2.3.1` and go straight to `2.4.0`, let's replace all references.

**Comment by westonruter** [comment]
cc @maitreyie-chavan I'm moving all issues/PRs to the new milestone now

**Comment by westonruter** [comment]
Current board for the next release: https://github.com/ampproject/amp-wp/projects/13?card_filter_query=milestone%3Av2.4

**Comment by thelovekesh** [comment]
@westonruter Since all the references have been transferred from `2.3.1` to `2.4.0` should we close this now?

**Comment by westonruter** [comment]
@thelovekesh I mean the references in code. They haven't been updated right?

**Comment by thelovekesh** [comment]
> They haven't been updated right?

I misunderstood it with milestone references. Sorry for the confusion 😕

**Comment by westonruter** [comment]
Sorry for the confusion. I meant for https://github.com/ampproject/amp-wp/issues/7428#issuecomment-1405549843 to be an aside.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-checked the issue, Searched in the codebase, and No reference related to 2.3.1 found. All the references related to 2.3.1 is updated to 2.4.0.
