### ISSUE TITLE
Adsense code in paragraf web version cannot remove

### ISSUE THREAD

**Issue by fahmi182** [Automattic/amp-wp#743]
Hi, new version always included adsense code in paragraf, make amp version not valid because script google adsense, how to remove element from "contents" wordpress?

**Comment by fahmi182** [comment]
Better back to 0.42 version :)

**Comment by caouic** [comment]
Hi, same problem here.
The script adsense in post is also in amp version.
The amp version is not valid ...

**Comment by westonruter** [comment]
This should be fixed in 0.5.1.
