### ISSUE TITLE
What's so wrong with the amp_backcompat_use_v03_templates() that you had to break them completely?

### ISSUE THREAD

**Issue by jerclarke** [Automattic/amp-wp#7441]
### Bug Description

I am using `amp_backcompat_use_v03_templates()` which continues to work on my site after updating the AMP plugin. When I updated AMP my error logs filled with deprecation notices:

```
PHP Deprecated:  amp_backcompat_use_v03_templates is <strong>deprecated</strong> since version 2.0 with no alternative available. in /.../wp-includes/functions.php on line 4727 
```

This is because you've added the following to `back-compat.php`:

```
function amp_backcompat_use_v03_templates() {
	_deprecated_function( __FUNCTION__, '2.0' );
	add_filter( 'amp_customizer_is_enabled', '__return_false' );
	add_filter( 'amp_post_template_dir', '_amp_backcompat_use_v03_templates_callback', 0 ); // Early in case there are other overrides.
}
```

### Expected Behaviour

Let me keep taking advantage of the system which ain't broke and which does not need fixing. 

**Why did you kill this option? What about it doesn't work?** 

When I test my AMP pages, everything is working perfectly, just how I like it and just how I spent dozens of hours configuring already. I don't want to redo this work with a "reader" theme, why would I when it functions fine. Am I missing something? 

Why not let me make the decision to use the old templates or not?

Calling `_deprecated_function()` is extremely aggressive, because it leaves me no way to intentionally disregard your advice. `_deprecated_function()` doesn't have a filter to ignore a specific function, I'll have to do a bunch of ugly hacks just to silence this notice. 

Please add a filter or something that lets me silence this `_deprecated_function()` call, e.g. 

```
	if (apply_filters('amp_deprecate_v03_templates', true)) {
		_deprecated_function( __FUNCTION__, '2.0' );
	}
```

Unless there's a reason why the old templates are currently broken, users should have the option to keep using them at their own discretion. 

Thank you for considering this. 

### Plugin Version

2.3.0

### AMP plugin template mode

Reader

**Comment by jerclarke** [comment]
In case anyone else has this issue/desire, here is some filter code that can silence the `_deprecated_function()` error logs. It's very complicated and ugly, but I think it works and should avoid silencing errors related to any other functions, as well as avoiding messing with any other filters manipulating `_deprecated_functions()`


```php
/**
 * Filter _deprecated_function() to silence errors from amp_backcompat_use_v03_templates() being marked as deprecated
 * 
 * The devs of AMP plugin decided that using the legacy templates should be broken, even though it still works fine, 
 * so they added _deprecated_function() inside amp_backcompat_use_v03_templates(). 
 * 
 * This causes error logs that are almost impossible to silence, because of how _deprecated_function() works.
 * 
 * We can silence them using this two-stop filter, needed because _deprecated_function() doesn't give us
 * access to the function name in the 'deprecated_function_trigger_error' filter which can actually disable it.
 * 
 * So in this first part, we filter the 'deprecated_function_run' action which has the $function name, and
 * we add the 'deprecated_function_trigger_error' filter which will return false and remove itself. 
 * 
 * Note that another working solution is to just add __return_false as the filter on deprecated_function_trigger_error, 
 * and remove it right at the start of this function, but that seemed too aggressive, as it could mess with other
 * code trying to filter deprecated_function_trigger_error with __return_false. This solution is clean and obvious
 * and leaves a more useful breadcrumb in the list of registered actions.
 *
 * @link https://github.com/ampproject/amp-wp/issues/7441
 * @param string $function
 * @param string $replacement
 * @param string $version
 * @return void
 */
function gv_amp_disable_legacy_template_deprecation_part_1($function, $replacement, $version) {

	if ('amp_backcompat_use_v03_templates' != $function) {

		return;
	}

	add_filter('deprecated_function_trigger_error', 'gv_amp_disable_legacy_template_deprecation_part_2');
}
add_filter('deprecated_function_run', 'gv_amp_disable_legacy_template_deprecation_part_1', 10, 3);

/**
 * Part 2 of the _deprecated_function() fix for amp_backcompat_use_v03_templates() above
 *
 * Removes itself, then returns false. 
 * 
 * @param bool $trigger_error
 * @return void
 */
function gv_amp_disable_legacy_template_deprecation_part_2($trigger_error) {

	remove_filter('deprecated_function_trigger_error', 'gv_amp_disable_legacy_template_deprecation_part_2');

	return false;
}
```

**Comment by westonruter** [comment]
The reason why we deprecated these old templates is because they are used very infrequently by users (I'm surprised you're using them) and they lack the latest features we developed for the plugin. These old templates add a maintenance burden for our team. We don't test the old templates so they could break with new updates, so that is why we discourage their use.

That being said, silencing the deprecation notice like you have done is a good approach.

Aside: It's a shame that the `deprecated_function_trigger_error` filter doesn't pass the `$function` as an argument!

**Comment by jerclarke** [comment]
> Aside: It's a shame that the deprecated_function_trigger_error filter doesn't pass the $function as an argument!

Yeah seriously! For devs like you it would be such an easier sell to just tell me to silence it with one filter. 

Ok, I'll just keep trucking and see if anything breaks. Thanks for anything you can do to not break the legacy templates in the future, they are very valuable to me at least.

**Comment by westonruter** [comment]
Good to know. We have no plans to touch them.
