### ISSUE TITLE
slider in post cause amp version not valid 

### ISSUE THREAD

**Issue by caouic** [Automattic/amp-wp#745]
Hi,
I use metaslider plugin and any post with a slider is nota valid in amp version.
amp validator:
CUSTOM_JAVASCRIPT_DISALLOWED
`<script><![CDATA[
        var metaslider_XXXX = function($) {
            $('#metaslider_XXXX').responsiveSlides({ 
                timeout:7000,
                pager:false,
                nav:true,
                pause:true,
                speed:600,
                prevText:"&lt;",
                nextText:"&gt;",
                auto:true
            });
        };
        var timer_metaslider_XXXX = function() {
            var slider = !window.jQuery ? window.setTimeout(timer_metaslider_XXXX, 100) : !jQuery.isReady ? window.setTimeout(timer_metaslider_XXXX, 1) : metaslider_XXXX(window.jQuery);
        };
        timer_metaslider_XXXX();
    ]]></script>`
I don't have this problem in amp version 0.4.2.
Best regards

**Comment by caouic** [comment]
Back to 0.4.2 no problem with metaslider
post amp page: 
[http://www.lesgoodnews.fr/2017/07/13/lethique-quete-des-fermes-davenir/amp/](url)

**Comment by westonruter** [comment]
This issue should be fixed in 0.5.1.

**Comment by caouic** [comment]
I confirm the issue is fixed in 0.5.1.
Thanks a lot !
Best regards
