### ISSUE TITLE
Blog Pagination URL Structure mismatch

### ISSUE THREAD

**Issue by gellerby** [Automattic/amp-wp#746]
When accessing /blog/amp/, pagination works correctly however `/blog/page/6/` has a canonical `<link>` tag to `/amp/blog/page/6/` instead of `/blog/amp/page/6/`.

Google WMT is now saying there's a content mismatch between `/amp/blog/page/6/` and `/blog/page/6/` because `/amp/blog/page/6/` actually shows the first ten posts not page 6. 

Any ideas? Thanks for the plugin by the way.

**Comment by westonruter** [comment]
What is `/blog/` here? Is it an index page?

Please share the actual URLs for your site where the problem can be seen.

**Comment by westonruter** [comment]
@gellerby The AMP plugin doesn't currently apply to the blog index page, so unless you can provide more details we'll not be able to advise.
