### ISSUE TITLE
Javascript Error in Google Console When Wordads Is Enabled

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/amp-wp#747]
Two users reported this error in the Google Search Console when Wordads was enabled with AMP: 

`Accelerated Mobile Pages > User-authored JavaScript found on page (Critical 
issue). `

One user tracked it down to this:
```
<script><![CDATA[ 
(function(g){g.__ATA.initAd({sectionId:1304173541, width:300, 
height:250});})(window); 
]]></script> 
```
@dbspringer had a look and thinks it's something in the code here. Can someone take a look?

Internal reference: 627192-zen, 565431-hc

**Comment by fahmi182** [comment]
Script, form inside article not remove automatically.. so many error with this version.

**Comment by dbspringer** [comment]
Some context: the WordAds plugin is emitting some divs which contain a <script> tag in `the_content`. It seems the plugin is trying to do something helpful with this script by wrapping it in CDATA, but the desired result is to remove the script altogether.

**Comment by pppdog** [comment]
Me too.
`<script type="application/ld+json"><![CDATA[
{"@context":"http:\/\/schema.org\/",
 "@type": "Product",
text.......more]]></script>`

**Comment by seejacobscott** [comment]
636092-zen

**Comment by RavanH** [comment]
Yep, same with the Post Adverts plugin script tags...

Seems that since class AMP_Blacklist_Sanitizer has been replaced by the class AMP_Tag_And_Attribute_Sanitizer, script tags are no longer stripped out. In fact, it seems that the script tag is now listed under the "additional_allowed_tags" with a mandatory attribute "text/javascript" or "application/json". See https://github.com/Automattic/amp-wp/blob/master/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L958

But it's weird. In the specs on https://www.ampproject.org/docs/reference/spec it still says about script tags: "Prohibited unless the type is application/ld+json"

**Comment by RavanH** [comment]
Note: I just tested:
1. uncommenting 'script' in the $node_types_to_remove_if_invalid array on https://github.com/Automattic/amp-wp/blob/master/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L938
2. removing the two 'script' values from the $additional_allowed_tags array on https://github.com/Automattic/amp-wp/blob/master/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php#L950

Script tags still are being "sanitized" (CDATA added, src attribute removed) but not completely removed.

A tag like `<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>` (from Google Ads) is stripped down to `<script></script>` and even if it is missing the (supposedly?!) mandatory type attribute, then just left to pass into the amp source. 

Further Google Ads script `<script>(adsbygoogle = window.adsbygoogle \|\| []).push({});</script>` is converted to 

```
<script><![CDATA[
--
  | (adsbygoogle = window.adsbygoogle \|\| []).push({});
  | ]]></script>

```

Apart from invalid javascript, this obviously creates an AMP "User written javascript" validation error.

**Comment by RavanH** [comment]
Note 2:

Only thing that seems to be helping is to revert to the AMP_Blacklist_Sanitizer.

Go to https://github.com/Automattic/amp-wp/blob/master/includes/class-amp-post-template.php#L246 and uncomment that line. Then comment out line 254

**Comment by amedina** [comment]
Hi Folks, @mjangda and I are looking into this asap.
