### ISSUE TITLE
Invisible cover block background colors

### ISSUE THREAD

**Issue by akmetin** [Automattic/amp-wp#7471]
### Bug Description
Cover block background colors do not work as expected.

### Expected Behaviour
Should render as in the editor.

### Screenshots
<img width="628" alt="Screenshot at Feb 23 17-37-57" src="https://user-images.githubusercontent.com/6942200/220939769-b97491ff-7827-41d2-9629-8f8a3962d09c.png">
<img width="628" alt="Screenshot at Feb 23 17-37-57" src="https://user-images.githubusercontent.com/6942200/220941521-3721617a-6052-4cf3-9ff5-a78beecb3670.png">

### PHP Version
8.1

### Plugin Version
2.4.0

### AMP plugin template mode
Reader

### WordPress Version
6.1.1

### Site Health
No issues

### Gutenberg Version
No response

### OS(s) Affected
No response

### Browser(s) Affected
No response

### Device(s) Affected
No response

### Acceptance Criteria
No response

### Implementation Brief
No response

### QA Testing Instructions
No response

### Demo
No response

### Changelog Entry
No response

**Comment by westonruter** [comment]
@deepnees what primary (non-AMP) theme are you using?

We did seek to address this previously in #6039.

**Comment by thelovekesh** [comment]
I think a block-based theme is being used here.

Blocks-based themes rely on `theme.json` and our logic for determining styles, and the color palette is based on `theme_support` 

https://github.com/ampproject/amp-wp/blob/0737c7896f910e8470379b4eedc2ffd0cc5f0136/src/ReaderThemeSupportFeatures.php#L206-L210

Also, check this [note](https://developer.wordpress.org/themes/advanced-topics/theme-json/#:~:text=Note%20that%20the%20settings%20in%20theme.json%20replace%20many%20of%20the%20calls%20to%20add_theme_support().%20The%20color%20palette%20in%20theme.json%20is%20the%20equivalent%20of%20add_theme_support(%20%27editor%2Dcolor%2Dpalette%27%2C%20%E2%80%A6).%0AWhen%20both%20are%20present%2C%20the%20palette%20from%20theme.json%20takes%20precedence.). According to this we will need to get `editor-color-palette` from `theme.json`'s color palette.

**Comment by milindmore22** [comment]
Yes, I tested it with TT1 theme 
https://amp-support.rt.gw/2023/03/02/cover-background-color-test/?amp=1

**Comment by westonruter** [comment]
Looks like the way to get the `theme.json` data is via `wp_get_global_settings( [], 'theme' )`.

**Comment by westonruter** [comment]
And more specifically: `wp_get_global_settings( [ 'color', 'palette' ], 'theme' )`

**Comment by thelovekesh** [comment]
@westonruter Should we take into account the fluid font sizes that WordPress 6.1 offers?

**Comment by westonruter** [comment]
I'm not very familiar with them. If not taken into account, would the AMP version seem broken?

**Comment by thelovekesh** [comment]
Fluid font sizes are all about using [`clamp()`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp) and more of a responsive utility. So, it will not break AMP in any way.

It is being used in theme.json like:
```json
"fontSizes": [
	{
		"fluid": {
			"min": "0.875rem",
			"max": "1rem"
		},
		"size": "1rem",
		"slug": "small"
	},
]
```

and being outputted as:
```css
--wp--preset--font-size--small: clamp(0.875rem, 0.875rem + ((1vw - 0.48rem) * 0.24), 1rem);
```
If fluid typography is not used, then it will use font size from default/theme presets:
```css
--wp--preset--font-size--small: 13px;
```

**Comment by westonruter** [comment]
Got it. At the moment, these will be broken entirely due to php-css-parser failing to parse such complex CSS values. This was just raised in a [support topic](https://wordpress.org/support/topic/block-theme-incompatibility/) which we had already reported in https://github.com/ampproject/amp-wp/issues/7291. I'm going to re-open the issue and think about a workaround.

**Comment by westonruter** [comment]
But yes, we should preserve fluid font sizes from the main theme when in Reader mode, same as we try to preserve the color palette. But the color palette is more important since lack of support can mean the text is impossible to read due to being white-on-white or black-on-black.

**Comment by pavanpatil1** [comment]
Cross-checked the issue and the fix is working fine. background-color is now visible and text is also visible properly in the reader mode. However, in the cover block, the background color for the paragraph inside the cover is visible outside the container. 



![image](https://user-images.githubusercontent.com/44057535/226591347-facd4553-a56a-447a-90a6-a4c527c85ebc.png)

**Comment by thelovekesh** [comment]
https://github.com/ampproject/amp-wp/pull/7496 aims to fix the above issue. It happened because of `p.has-background` CSS which was implemented for every `p.has-background` selector instead of `.amp-wp-article-content > p.has-background`.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Verified the fix. It is working as expected. The block style is visible properly. 

![image](https://user-images.githubusercontent.com/44057535/226830572-ca428da8-c782-4bf8-a6a5-2df68d4830da.png)

**Comment by westonruter** [comment]
@deepnees This is now released on the WordPress.org Plugin Directory.
