### ISSUE TITLE
Google Analytics in Facebook Instant Articles

### ISSUE THREAD

**Issue by maxinnos** [Automattic/amp-wp#748]
We have been unable to find a way to have Google Analytics track anything in Facebook Instant Articles. We have added our GA code, but there is no reporting coming back into GA from our FB Instant Articles despite seeing traffic with other tools.

We have also tried adding in this structure to the page, both with <iframe> and <amp-iframe>, however both create validation errors:
`<figure class="op-tracker"> 
    <iframe hidden>
        <script>
            (function (i,s,o,g,r,a,m) {i['GoogleAnalyticsObject']=r;i[r]=i[r]||function () {(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-   analytics.com/analytics.js','ga');
            ga('create', 'UA-xxxxxxxxx-1', 'auto');
            ga('require', 'displayfeatures');
            ga('set', 'campaignSource', 'Facebook');
            ga('set', 'campaignMedium', 'Social Instant Article');
            ga('set', 'title', ia_document.title); 
            ga('send', 'pageview');
        </script>
    </iframe>
</figure>`

Is there something we're missing in the setup here, or is GA tracking in FB Instant Articles not supported with this plugin?

Thanks

**Comment by amedina** [comment]
Hi @maxinnos, are you referring to the FB Instant articles plugin? Here is the repository for that one: https://github.com/Automattic/facebook-instant-articles-wp
