### ISSUE TITLE
Make the plugin build system and toolings cross-platform compatible

### ISSUE THREAD

**Issue by thelovekesh** [Automattic/amp-wp#7480]
The existing plugin build system and toolings are made up of different bash scripts and commands (like npm and composer scripts), which never function properly on Windows. When a developer tries to work on a project on Windows with Local WP, there may be specific use situations where some procedures don't work.

Considerable tasks include the following:
-  Try to use [shelljs](https://www.npmjs.com/package/shelljs) and execute bash scripts in NodeJS.
-  Explore if we can use [zx](https://github.com/google/zx) by Google to keep all our scripts platform independent using NodeJS.

**Comment by westonruter** [comment]
I wonder how often this would be a problem on Windows now? Wouldn't most developers be using WSL and thus be able to use regular Linux utilities?

**Comment by thelovekesh** [comment]
Not sure how much the developer base faces this problem but I think less tech-savvy people can. In the current scenario, the `npm run build:*` command fails on Windows. 

Check this job for instance: https://github.com/thelovekesh/amp-wp/actions/runs/4364834271/jobs/7632644049

**Comment by westonruter** [comment]
Yeah. Well, I suggest we keep this on the backlog until we have a contributor on Windows who needs this.

**Comment by thelovekesh** [comment]
SGTM

**Comment by westonruter** [comment]
We can revisit as need arises.
