### ISSUE TITLE
Remove React 17 requirement for certain features

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7489]
### Feature Description

Let's undo aspects of #7421 which made certain services dependent on React 17. As seen in the below [Make/Core post](https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/#:~:text=New%20API%20for%20mounting%20a%20root), any React 17 code will continue to work with React 18 by invoking a legacy API:

> ![image](https://user-images.githubusercontent.com/134745/223522534-73f4eadf-7e05-42cc-bb59-ba5860ac619a.png)

In particular, this is considering the following line (at least):

https://github.com/ampproject/amp-wp/blob/f8249c1506f7d2f0cc59b27f73294cf148fea01b/src/Admin/AfterActivationSiteScan.php#L104

Related: https://github.com/ampproject/amp-wp/pull/7394

**Comment by thelovekesh** [comment]
QA Passed ✅ 

See https://github.com/ampproject/amp-wp/pull/7490#issuecomment-1476094281
