### ISSUE TITLE
Improvements in Legacy Theme

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7491]
### Serves images with low resolution
The gravatar is being served in low resolution 24X24 as per updated standards we should serve images with 36X36 resolutions 
![image](https://user-images.githubusercontent.com/1132541/226266627-5762db35-8bc8-4df2-b1b8-a23418b42ab7.png)

For this we can simply increase the image size to 36X36

### Background and foreground colors do not have a sufficient contrast ratio.
According to the new [WCGA Standard (2.2), AAA draft](https://www.w3.org/TR/WCAG22/#contrast-enhanced) the contrast ratio should be 7:1 and the [Current AA standards it's 4.5:1](https://www.w3.org/TR/WCAG22/#contrast-minimum)

![image](https://user-images.githubusercontent.com/1132541/226268612-5b0f7006-337f-447c-8ef0-f57242c6ae3e.png)

As I checked the contrast ratio on [this online tool](https://dequeuniversity.com/rules/axe/4.6/color-contrast), I can adjust the background color's contrast ratio to find the following colors that can meet requirements, I am proposing to update the default background colors as per following

WCGA Standard Contrast Ratio

| Standard | AA | AAA |
| ------------- | ------------- | ------------- |
| Ratio | 4.5:1  | 7:1  |
| Color | #0A7DB3  | #0A5F85  |
| Status | Published | Drafted  |

## Page Speed
[Before  ](https://pagespeed.web.dev/analysis/https-amp-support-rt-gw-2012-01-07-template-sticky/c3e5i3uuki?form_factor=mobile)
[After](https://pagespeed.web.dev/analysis/https-amp-support-rt-gw-2012-01-07-template-sticky/az6w4wevmf?form_factor=mobile)

### Expected Behaviour

Should pass an audit that we control using the AMP plugin to be passed as per updated standards.

### PHP Version

8.0

### Plugin Version

2.4.0

### AMP plugin template mode

Reader

### WordPress Version

6.1.1

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Verified the issue, The issues related to A11y and low-resolution images in the legacy theme are fixed. 

**Before**: 

![image](https://user-images.githubusercontent.com/44057535/226557273-4a41686c-30aa-448a-8d3a-c9fa7c5b7731.png)
[before.pdf](https://github.com/ampproject/amp-wp/files/11026688/before.pdf)


**After**: 
![image](https://user-images.githubusercontent.com/44057535/226563517-3ce9ce1f-c82a-4fe8-97e6-d259eaa7e47d.png)

[After.pdf](https://github.com/ampproject/amp-wp/files/11026681/After.pdf)

**Comment by milindmore22** [comment]
Looks good 👍🏼
