### ISSUE TITLE
Version 0.5 makes site inaccessible when AMP for WP also installed

### ISSUE THREAD

**Issue by jenstarz** [Automattic/amp-wp#750]
If you have the AMP for WP plugin installed (https://wordpress.org/plugins/accelerated-mobile-pages/) and you update the Automattic AMP plugin to .5, it causes the entire site (both front end and back end) to become inaccessible, except for the AMP version of the page/site if you access the site via an AMP URL.  You need to FTP to the site to remove the AMP plugin folder, update the AMP for WP plugin, then reinstall this plugin.  There seemed to be a conflict with the .5 version and the AMP for WP plugin prior to 0.9.57

Reference: https://wordpress.org/support/topic/error-site-crash-on-update-to-0-5/
https://ampforwp.com/compatibility-issue-fixed-63rd-update/
https://wordpress.org/support/topic/amp-by-automattic-not-getting-activated/
https://ampforwp.com/beginning-of-an-update-proof-ux-64th-update/

**Comment by amedina** [comment]
Thanks for reporting this @jenstarz; this issue is related to both plugins becoming incompatible after the latest release of this plugin. As you pointed out @ Twitter, the AMP for WP plugin has removed the dependency with the Automattic plugin; hopefully their users will upgrade their plugin soon.

**Comment by amedina** [comment]
Closing this issue for now; it would be good if the AMP for WP plugin authors indicate some specific issues to make the Automattic plugin compatible with them, and we would look at addressing them.
