### ISSUE TITLE
React warning on activation: `ReactDOM.render is no longer supported in React 18`

### ISSUE THREAD

**Issue by aaemnnosttv** [Automattic/amp-wp#7507]
### Bug Description

When activating the AMP plugin on WP 6.2, the following console error is raised by the AMP site scan notice.

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

### Expected Behaviour

No console error should be raised.

### Screenshots

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/1621608/228962300-1e07964a-4bc3-4ee4-a577-a924de49fcc2.png">

### PHP Version

7.4

### Plugin Version

2.4.1

### AMP plugin template mode

Standard

### WordPress Version

6.2

**Comment by westonruter** [comment]
Thanks for the report. This is expected. See #7489.
