### ISSUE TITLE
Error: 'action' attribute missing in Form tag

### ISSUE THREAD

**Issue by fokhwar** [Automattic/amp-wp#751]
Hello guys,
Thank you for your effort on amp-wp plugin.

Below is my original article link. **(No 'action' attribute is missing in every 'form' tag)**
http://www.panacea-soft.com/teamps_product/restaurateur-ios/

But google amp tester shows error for amp page that **'action' attribute is missing in 'form' tag**.
http://www.panacea-soft.com/teamps_product/restaurateur-ios/amp

Please kindly help me and I apologize in advanced if it is not plugin's error.

**Comment by fokhwar** [comment]
Hello guys,
Error was solved after all in one schema.org plugin is disabled.
Currently I am using WP SEO Structure Plugin and no issue with AMP.
Thanks!

**Comment by amedina** [comment]
Thanks @fokhwar! Glad to hear the issue was solved.
