### ISSUE TITLE
Reader mode showing incorrect timestamps for posts

### ISSUE THREAD

**Issue by orenwolf** [Automattic/amp-wp#7518]
### Bug Description

Currently, if you view an amp page using the reader template, the timestamp in the upper-right corner is incorrect.

This timestamp is generated with the following code:

```
<?php $this->load_parts( apply_filters( 'amp_post_article_header_meta', array( 'meta-author', 'meta-time' ) ) ); ?>
```
However, it appears `meta-time` doesn't work. For a post created at 10am PST for me, it shows as having been posted "6 hours ago", despite having been created about 30 minutes ago. Blog Timezone is `America/Los Angeles`

### Expected Behaviour

`meta-time` should return either the time relative to the blog TZ or the browser TZ. It's currently doing neither.

### Screenshots

Example URL here:

https://boingboing.net/2023/04/10/boob-jokes-about-renaming-twitter.html/amp - this was posted at 10:14 AM PDT, for reference.

### PHP Version

8.0

### Plugin Version

2.4.1

### AMP plugin template mode

Reader

### WordPress Version

6.2

### Site Health

<img width="1281" alt="Screen Shot 2023-04-10 at 2 11 18 PM" src="https://user-images.githubusercontent.com/1264142/230964785-5f6fc7f7-9077-45cf-a55c-998389cd1b1d.png">

### Gutenberg Version

WP 6.2 native

### OS(s) Affected

IOS/OSX

### Browser(s) Affected

Chrome, Safari

### Device(s) Affected

Mac Desktop, IPhone 14 Pro (current OS release)

**Comment by thelovekesh** [comment]
I tried to replicate it on my end, but it is working as intended. I am able to get the time diff based on UTC + my TZ.

@orenwolf Can you please attempt to write a new article and give the link as well as the timestamp that corresponds to your time zone? Also, It would be helpful to share information about your time settings in WordPress admin `Settings > General`
