### ISSUE TITLE
Sanitizer: JSON scripts are wrapped in CDATA

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#755]
Something like the following:

```
<script type="application/json">{}</script>
```

is allowed by the AMP spec. However, when output, they get wrapped in CDATA tags:

```
<script type="application/json"><![CDATA[{}]]></script>
```

This fails AMP validation.

The CDATA may be added because we use `saveXML` to output the resulting HTML after sanitizing (see `AMP_DOM_Utils::get_content_from_dom()`) and may need a workaround here.

**Comment by westonruter** [comment]
This was fixed in #891.
