### ISSUE TITLE
Feature image stretched on Legacy theme, when native image is being used.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7550]
### Bug Description

I received a few support topics [topic 1](https://wordpress.org/support/topic/distorted-main-image/) and [topic 2](https://wordpress.org/support/topic/amp-post-thumbnail-size-problem/#post-16781818) where use experience images being stretched on mobile devices.

I am able to reproduce the issue on my local.

We can prevent this by adding CSS 
```css
figure.amp-wp-article-featured-image img {
    height: auto;
}
```

### Expected Behaviour

Feature image in legacy theme working correctly on mobile and tablet devices

### Screenshots

![image](https://github.com/ampproject/amp-wp/assets/1132541/e3759f45-ea54-43da-bfa2-7050c6574be0)

### Plugin Version

2.4.1

### AMP plugin template mode

Reader

### WordPress Version

6.2.2

**Comment by pooja-muchandikar** [comment]
QA Passed ✅

Verified the issue, the featured native image is visible properly now on mobile and tablet. 

Before fix:
![image](https://github.com/ampproject/amp-wp/assets/41000648/1cd9ec37-482a-41a7-9cb5-37b71a191bd9)

---

After fix:
![image](https://github.com/ampproject/amp-wp/assets/41000648/15a70524-7639-4d5c-8c0c-4275af356453)
