### ISSUE TITLE
Deprecate googleanalytics (UA) vendor type in favor of gtag (GA4)

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7567]
### Feature Description

As is well known, the universal analytics (UA) version of Google Analytics is being sunset imminently in favor of GA4. Support for GA4 in AMP just landed: https://github.com/ampproject/amphtml/issues/24621#issuecomment-1610286610

The GA4 configuration uses the `gtag` vendor type as opposed to `googleanalytics`. Therefore:

1. The entry label for "Google Analytics" should be updated to say "Google Analytics (Deprecated)" in:

https://github.com/ampproject/amp-wp/blob/3007b1387f0ace236b25f70a63829c092cdd547f/includes/ecosystem-data/analytics-vendors.php#L160-L161

Note that the [vendor entry](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors#google-analytics) on AMP.dev will be updated accordingly.

2. There is a notice currently displayed when the user has selected `googleanalytics` to consider using Site Kit instead (which will support GA4 shortly per https://github.com/google/site-kit-wp/issues/7221). However, the notice should be updated to be a warning here, perhaps by adding this sentence to the end of the paragraph: 

> Nevertheless, the `googleanalytics` type is obsolete as Google Analytics has switched to use `gtag` in the transition from Universal Analytics (UA) to GA4. Please use `gtag` instead. Learn more about [GA4 in AMP](https://support.google.com/analytics/topic/13706307?hl=en&ref_topic=9303319&sjid=7478006548081699185-NA).

![image](https://github.com/ampproject/amp-wp/assets/134745/9591e640-609d-43e2-8e66-2d1b16ca9bc3)

**Comment by thyngster** [comment]
Universal Analytics will kept working for 360 users for 1 more year. Not having it available freely for everyone may not be a synonim for "deprecated", maybe "legacy" is a better tag until it gets really deprecated...

**Comment by pooja-muchandikar** [comment]
QA Passed ✅

**Before Fix:** 

![image](https://github.com/ampproject/amp-wp/assets/41000648/95b14024-04d3-4ef8-9a93-10d317c0d41b)

---

**After Fix:**

![image (3)](https://github.com/ampproject/amp-wp/assets/41000648/31d37ef1-0b9c-4c5f-b804-3c9dd2fea836)
