### ISSUE TITLE
Eliminate gutenberg-packages-update workflow in favor of native Dependabot grouping

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7576]
### Feature Description

Dependabot has native beta support for dependency grouping: https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1623832701. We should use that instead of our `gutenberg-packages-update` workflow.

Potentially include other dependencies grouped.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅

Verified the issue, and the Gutenberg package update workflow file is removed successfully and instead dependent bot file has been updated.
