### ISSUE TITLE
Parsing script Jquery issue

### ISSUE THREAD

**Issue by SeoLifePRO** [Automattic/amp-wp#758]
When finding of the tag < / div > parsing stops and everything after him gets to a amp page.

`jQuery("#"+id+" .quasar-portfolio-body .relative-container").wrap("<div class=\"relative-container-holder large-"+img_col+" medium-"+img_col+" columns\" "+boxed_extra_style+"></div>");
if(jQuery("#"+id+" `

AMP Page:
`</div>");
if(jQuery("#"+id+" .`

How to correct this error?

**Comment by mjangda** [comment]
What version are you using?

**Comment by SeoLifePRO** [comment]
I using version 0.5.1

**Comment by westonruter** [comment]
Please share the AMP URL that demonstrates the problem.

Nevertheless, jQuery and JavaScript generally are [not allowed](https://www.ampproject.org/learn/about-how/) in AMP:

> AMP pages can’t include any author-written JavaScript. Instead of using JavaScript, interactive page features are handled in custom AMP elements. The custom AMP elements may have JavaScript under the hood, but they’re carefully designed to make sure they don’t cause performance degradation.

So I don't think this is something that is an AMP plugin problem.
