### ISSUE TITLE
Update theme_has_theme_json to reflect WP 6.3 changes

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7582]
1. Update `theme_has_theme_json` method to reflect what was [actually committed](https://core.trac.wordpress.org/changeset/56185).
2. Uncomment the call to `wp_theme_has_theme_json()` if defined.

https://github.com/ampproject/amp-wp/blob/d7a6af86824d2601ca2221a3900dec55e1ab0245/src/ReaderThemeSupportFeatures.php#L581-L626

**Comment by pooja-muchandikar** [comment]
QA Passed ✅

Checked the issue, and verified it on WP6.1 and WP6.2 and WP6.3 beta versions and the 2023 theme with the legacy mode appears to be working fine.
