### ISSUE TITLE
Warning Shown

### ISSUE THREAD

**Issue by Salaikawltu** [Automattic/amp-wp#759]
I recently use an facebook instant article for my website. After the approval. Still i cannot post and submit the post appropriately to the instant article.

It shows this warning. Please help the easiest way to fix this.

 This post was transformed into an Instant Article with some warnings [Learn more | Transformer rule configuration | Toggle debug information]

No rules defined for <div> in the context of InstantArticle
No rules defined for <div> in the context of InstantArticle

**Comment by mjangda** [comment]
This is the repo for the AMP plugin. For Instant Articles, please go to https://github.com/Automattic/facebook-instant-articles-wp

**Comment by Salaikawltu** [comment]
Thanks bro letme try it

**Comment by Salaikawltu** [comment]
brother still same thing happen. I have install what you have recommended. I already installl this Instant Articles for WP before as well. Help please

**Comment by amedina** [comment]
@Salaikawltu You need to file the issue in the repository for the FB Instant Articles plugin. This is not that plugin.
