### ISSUE TITLE
Very Urgent : AMP Runtime error

### ISSUE THREAD

**Issue by askmeoffersglobal** [Automattic/amp-wp#7598]
### Bug Description

Description
I am seeing issues on AMP Runtime

Powered by AMP ⚡ HTML – Version 2308042153000 https://askmeoffers.com/aliexpress-coupons/
error-reporting.js:205 Cannot access 't' before initialization
wn @ error-reporting.js:205
(anonymous) @ error-reporting.js:293
amp-worker.js:101 Uncaught (in promise) ReferenceError: Cannot access 't' before initialization
at new (amp-worker.js:101:9)
at Y (service-helpers.js:350:13)
at q (service-helpers.js:141:10)
at amp-worker.js:38:18
at Object.aEt (bind-impl.js:1603:12)
at Object.Te (bind-impl.js:594:17)
at bind-impl.js:202:12

Reproduction Steps
Open [Aliexpress Coupon code](https://askmeoffers.com/aliexpress-coupons/)
Hit the search bar to popup which is implemented in AMP
check the console it shows error and nothing works

### Expected Behaviour

search bar should open , with amp runtime its not working

### Screenshots

![image](https://github.com/ampproject/amp-wp/assets/109058077/ea21abf1-a0d1-4bfd-8e60-79575649493a)

### Plugin Version

latest

### AMP plugin template mode

Standard

### WordPress Version

8.3

### Site Health

`
### wp-core ###

version: 6.3
site_language: en_US
user_language: en_US
timezone: Asia/Kolkata
permalink: /news/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 102
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /code
wordpress_size: 115.41 MB (121016748 bytes)
uploads_path: /code/wp-content/uploads
uploads_size: 57.00 B (57 bytes)
themes_path: /code/wp-content/themes
themes_size: 5.62 MB (5891309 bytes)
plugins_path: /code/wp-content/plugins
plugins_size: 147.02 MB (154164116 bytes)
database_size: 1.54 GB (1654095872 bytes)
total_size: 1.80 GB (1935168102 bytes)

### wp-active-theme ###

name: Askmeoffers News Pack Child (newspack-theme-child)
version: 1.0.0
author: Ratnesh Singh
author_website: http://askmeoffers.com
parent_theme: Newspack (newspack-theme)
theme_features: core-block-patterns, widgets-block-editor, title-tag, post-thumbnails, menus, automatic-feed-links, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, editor-gradient-presets, custom-spacing, responsive-embeds, amp, post-subtitle, infinite-scroll, jetpack-responsive-videos, jetpack-geo-location, jetpack-content-options, web-stories, widgets
theme_path: /code/wp-content/themes/newspack-theme-child

### wp-parent-theme ###

name: Newspack (newspack-theme)
version: 1.74.0
author: Automattic
author_website: https://newspack.com
theme_path: /code/wp-content/themes/newspack-theme

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.2, author: the WordPress team

### wp-mu-plugins (1) ###

Pantheon MU Plugin Loader: version: 1.0, author: Pantheon Systems

### wp-plugins-active (20) ###

Akismet Anti-Spam: Spam Protection: version: 5.2, author: Automattic - Anti Spam Team
AMP: version: 2.4.2, author: AMP Project Contributors
Better Search Replace: version: 1.4.2, author: WP Engine
Coupon Store Widget: version: 1.0, author: Your Name
Fastly: author: (undefined), version: 1.2.23
Instant Indexing: version: 1.1.16, author: Rank Math
Jetpack: version: 12.4, author: Automattic
Native PHP Sessions for WordPress: version: 1.3.6, author: Pantheon
Newspack: version: 2.3.0, author: Automattic
Newspack Blocks: version: 1.73.0, author: Automattic
Newspack Newsletters: version: 1.67.4, author: Automattic
Pantheon Advanced Page Cache: version: 1.4.1, author: Pantheon
PublishPress Capabilities: version: 2.9.1, author: PublishPress
PWA: version: 0.7.1, author: PWA Plugin Contributors
S3 Uploads: version: 3.0.3, author: Human Made Limited
WordPress Backup & Security Plugin - BlogVault: version: 5.22, author: Backup by BlogVault
WP GDPR Cookie Notice: version: 1.0.0-rc.2, author: Felix Arntz
WP Offload Media Lite: version: 3.2.4, author: Delicious Brains
Yoast SEO: version: 20.13, author: Team Yoast
Yoast SEO: News: version: 13.1, author: Team Yoast

### wp-plugins-inactive (4) ###

Batcache Manager: version: 1.5, author: Andy Skelton
Site Kit by Google: version: 1.107.0, author: Google
WP Crontrol: version: 1.15.3, author: John Blackbourn & crontributors
WP Redis: version: 1.4.3, author: Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1692
imagemagick_version: ImageMagick 6.9.12-86 Q16 x86_64 17814 https://legacy.imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 100M
max_effective_size: 100 MB
max_file_uploads: 50
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 251 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 24576
	imagick::RESOURCETYPE_MAP: 126 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 5.10.177+ x86_64
httpd_software: nginx/1.21.6
php_version: 8.2.1 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 120
memory_limit: 512M
admin_memory_limit: 1048M
max_input_time: 900
upload_max_filesize: 100M
php_post_max_size: 100M
curl_version: 7.61.1 OpenSSL/1.1.1k
suhosin: false
imagick_availability: true
pretty_permalinks: true
current: 2023-08-16T17:42:15+00:00
utc-time: Wednesday, 16-Aug-23 17:42:15 UTC
server-time: 2023-08-16T23:12:14+05:30

### wp-database ###

extension: mysqli
server_version: 10.6.8-MariaDB-log
client_version: mysqlnd 8.2.1
max_allowed_packet: 67108864
max_connections: 1024

### wp-constants ###

WP_HOME: https://askmeoffers.com
WP_SITEURL: https://askmeoffers.com
WP_CONTENT_DIR: /code/wp-content
WP_PLUGIN_DIR: /code/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 1048M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: not writable
uploads: writable
plugins: not writable
themes: not writable
mu-plugins: not writable

### jetpack ###

site_id: 210107367
ssl_cert: No
time_diff: undefined
version_option: 12.4:1692122129
old_version: 12.4:1692122129
public: Public
master_user: #4 askmeoffers
is_offline_mode: off
is_offline_mode_constant: off
current_user: #4 askmeoffers
tokens_set: Blog User
blog_token: #gnERrF$nIt3@FK0OMMzIx@yX%yogSjD
user_token: 1K)4$JBROuQrSgtdPn$%4yQx7^KYTDf3
version: 12.4
jp_plugin_dir: /code/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"HTTP_X_FORWARDED_FOR","segments":0,"reverse":false}
full_sync: {"started":"Tue, 15 Aug 2023 17:55:53 +0000","finished":"Tue, 15 Aug 2023 17:55:55 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"4"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[4],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/askmeoffers.com","siteurl":"https:\/\/askmeoffers.com","WP_HOME":"https:\/\/askmeoffers.com","WP_SITEURL":"https:\/\/askmeoffers.com"}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### amp_wp ###

amp_slug_query_var: amp
amp_slug_defined_late: false
amp_mode_enabled: standard
amp_reader_theme: legacy
amp_templates_enabled: post, page, attachment, review, coupon, newspack_nl_cpt, is_singular, is_front_page, is_home, is_archive, is_author, is_date, is_search, is_404, is_category, is_tag, is_tax[coupon_review], is_tax[coupon_store], is_tax[fastly_cache_tag], is_post_type_archive[coupon], is_post_type_archive[newspack_nl_cpt]
amp_serve_all_templates: true
amp_css_transient_caching_disabled: false
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 3535
amp_css_transient_caching_time_series: 
	20230816: 943
amp_libxml_version: 2.9.7

`

**Comment by westonruter** [comment]
This would be an upstream AMP core issue, for which I see you already opened https://github.com/ampproject/amphtml/issues/39380.

**Comment by askmeoffersglobal** [comment]
Yes but its happening for all amp sites , all themes, this is very major bug AMP is completely broken

**Comment by askmeoffersglobal** [comment]
Request you to please escalate this with AMP framework team

**Comment by westonruter** [comment]
I have already done so. Please do not ping everyone associated with the AMP team.

**Comment by askmeoffersglobal** [comment]
Thank you @westonruter Sir you have always helped me
