### ISSUE TITLE
Update node to 16 or 18

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7599]
### Feature Description

Now that Gutenberg and WordPress core have been updated to node 16, we can do the same (perhaps even node 18).

**Comment by westonruter** [comment]
Blocked by Gutenberg 16.5 release, due out on August 23rd.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

All workflows are running with the node v18 and the plugin build is passing and working fine. 


![image](https://github.com/ampproject/amp-wp/assets/44057535/b92ce2d4-0b28-45f5-a3c9-b50faccfac12)


![image](https://github.com/ampproject/amp-wp/assets/44057535/22da655a-0fc9-4aa5-ab96-ca25ef3142a8)
