### ISSUE TITLE
Auto insert playbuzz ID

### ISSUE THREAD

**Issue by brunomosciatti** [Automattic/amp-wp#760]

**Comment by amedina** [comment]
Please provide details of the issue filed. Thanks!

**Comment by brunomosciatti** [comment]
On WP we insert the playbuzz tag like this: 
`[playbuzz-item item="id-from-the-content-here" format="story"]`

and the <amp> tag for playbuzz is:
```
<amp-playbuzz
	    src="id-from-the-content-here"
	    height="500"
	    data-item-info="true"
	    data-share-buttons="true"
	    data-comments="true">
	</amp-playbuzz>
```

I need to when inserted the playbuzz-item in wordpress, automatically insert the id of this content into the "src" of <amp>

**Comment by amedina** [comment]
Hi @brunomosciatti, Playbuzz is not currently supported by the plugin. I will create an issue to add support for it. Will link this issue there and close this one.
