### ISSUE TITLE
Call to `_admin_bar_bump_cb` causes deprecation error in WordPress 6.4+

### ISSUE THREAD

**Issue by tofumatt** [Automattic/amp-wp#7619]
### Bug Description

The call to `_admin_bar_bump_cb` at https://github.com/ampproject/amp-wp/blob/2c4df9e1dec74c798e11f06cd02e470f1f988705/includes/class-amp-theme-support.php#L1226C9-L1226C9 causes PHP Deprecation notices to appear when using the AMP plugin with WordPress 6.4+.

The entire notice is:

```
PHP Deprecated:  Function _admin_bar_bump_cb is deprecated since version 6.4.0! Use wp_enqueue_admin_bar_bump_styles instead. in /var/www/html/wp-includes/functions.php on line 6032
```

It seems using `wp_enqueue_admin_bar_bump_styles` instead will fix the issue, when the version of WordPress is equal-to/above `6.4.0`.

### Expected Behaviour

No deprecation errors appear in the WordPress debug log/elsewhere when using the AMP plugin with WordPress 6.4+.

### Screenshots

![CleanShot 2023-09-29 at 11 50 33](https://github.com/ampproject/amp-wp/assets/90871/9299af72-a82c-4708-b717-5ce0b06b9ab7)

### PHP Version

7.4

### Plugin Version

2.4.2

### AMP plugin template mode

Standard

### WordPress Version

6.4.0 (Nightly)

**Comment by westonruter** [comment]
Yes, this is result of https://core.trac.wordpress.org/ticket/58775

We'll need to fix by the time WordPress 6.4 is released.

As for the fix, the code in question is:

https://github.com/ampproject/amp-wp/blob/2c4df9e1dec74c798e11f06cd02e470f1f988705/includes/class-amp-theme-support.php#L1228-L1241

I believe it can be rewritten as follows, or something like it:

```php
if ( ! function_exists( 'wp_enqueue_admin_bar_header_styles' ) ) {
    remove_action( 'wp_head', $header_callback );
}
 if ( '__return_false' !== $header_callback ) { 
 	if ( ! function_exists( 'wp_enqueue_admin_bar_header_styles' ) ) {
 		ob_start(); 
 		$header_callback(); 
 		$style = ob_get_clean(); 
 		$data  = trim( preg_replace( '#<style[^>]*>(.*)</style>#is', '$1', $style ) ); // See wp_add_inline_style(). 
 	} else {
 		$data = '';
 	}
  
 	// Override AMP's position:relative on the body for the sake of the AMP viewer, which is not relevant an an Admin Bar context. 
 	if ( amp_is_dev_mode() ) { 
 		$data .= 'html:not(#_) > body { position:unset !important; }'; 
 	} 
  
 	wp_add_inline_style( 'admin-bar', $data ); 
 }
```

**Comment by westonruter** [comment]
cc @spacedmonkey

**Comment by pavanpatil1** [comment]
QA Passed ✅ 


Cross-verified the issue and the applied solution is functioning correctly. Now, the deprecation warning related to the `_admin_bar_bump_cb` is not  visible. 

| Before | After |
| :------: | :------------: |
![image](https://github.com/ampproject/amp-wp/assets/44057535/4497a843-1620-428f-95a8-51d921632b9b)| ![image](https://github.com/ampproject/amp-wp/assets/44057535/d2516952-f19a-400d-a662-f07d4af2e58b)|
