### ISSUE TITLE
amp-playbuzz not working 

### ISSUE THREAD

**Issue by lysk88** [Automattic/amp-wp#764]
hey guys,  seems like amp-playbuzz not working as expected on version 0.5.1.
amp-playbuzz tag seems to be stripped out.
however, the amp-playbuzz script does loaded.

Version 0.5 working fine though.

Any ideas? Thanks.

**Comment by amedina** [comment]
Hi @lysk88, Looking into it. Closing this issue to track it [here](https://github.com/Automattic/amp-wp/issues/761) (you are in that thread as well)
