### ISSUE TITLE
Omit page caching and object caching tests for Site Health if on WP>=6.1

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7643]
### Feature Description

New description from @westonruter:  The Site Health tests for page caching and object caching from the AMP plugin have been incorporated into WordPress core as of 6.1. See https://github.com/WordPress/performance/issues/220 ([Core-56041](https://core.trac.wordpress.org/ticket/56041)) and https://github.com/WordPress/performance/issues/35 ([Core-56040](https://core.trac.wordpress.org/ticket/56040)). At the very least these tests can be disabled in WP  6.1+. But I think it would be better to just remove them entirely.

<details><summary>Original description</summary>

We got a [support topic](https://wordpress.org/support/topic/amp-cache-error/) where the user is getting a site health a warning for cache plugin, although he is using a cache plugin (Litespeed cache) because LiteSpeed uses a different header it's not able to detect it.

The Litespeed author suggested that we use a filter so that other vendors can pass their headers so it will fix warnings for their plugins.

</details>

**Comment by westonruter** [comment]
Actually, since page caching detection is now [part of Site Health in WordPress core](https://github.com/WordPress/wordpress-develop/blob/ce342f1a33051dcafdb47132f8e07d0597f49124/src/wp-admin/includes/class-wp-site-health.php#L2488-L2600), I think we can just remove our check entirely now, right?

There is a [filter](https://github.com/WordPress/wordpress-develop/blob/ce342f1a33051dcafdb47132f8e07d0597f49124/src/wp-admin/includes/class-wp-site-health.php#L3317-L3363) that caching plugins can use to add recognition of their own headers, as noted in the support topic.

**Comment by westonruter** [comment]
For the impending release, we could just disable the tests by default. Then in the next release we could remove them entirely, if this would make it easier to get the release out the door.

**Comment by thelovekesh** [comment]
We are also using page cache tests internally.

https://github.com/ampproject/amp-wp/blob/a2d841893ee30cbe50677f316e41a30f7dce8850/src/Admin/OptionsMenu.php#L250

https://github.com/ampproject/amp-wp/blob/a2d841893ee30cbe50677f316e41a30f7dce8850/assets/src/settings-page/settings-footer.js#L120

**Comment by westonruter** [comment]
Presumably these should be using what core has now for WP>=6.1.

**Comment by thelovekesh** [comment]
I need to dig in more but seems like it could be tricky to determine due to the visibility of methods.

https://github.com/WordPress/wordpress-develop/blob/ce342f1a33051dcafdb47132f8e07d0597f49124/src/wp-admin/includes/class-wp-site-health.php#L3458

**Comment by westonruter** [comment]
Ah yes. Well, in that case, we can just add a condition to only include the following tests if WP<6.1:

https://github.com/ampproject/amp-wp/blob/a2d841893ee30cbe50677f316e41a30f7dce8850/src/Admin/SiteHealth.php#L183-L186

https://github.com/ampproject/amp-wp/blob/a2d841893ee30cbe50677f316e41a30f7dce8850/src/Admin/SiteHealth.php#L220-L227

The latter essentially already has such a test, but for WP 5.6.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-verified the issue and the page caching and object caching test notices are not visible. Now, it is only visible if WP version is less than 6.1. 



Before fix        |  After fix
:----------------:|:-------------------------:
![image](https://github.com/ampproject/amp-wp/assets/44057535/acea13f4-f7a4-42e0-a239-f6705e71fd91)|![image](https://github.com/ampproject/amp-wp/assets/44057535/ac51108f-7aaa-4c48-a7e6-4700f8bb2173)
