### ISSUE TITLE
Update `AMP_Core_Block_Handler` to handle interactivity API enabled blocks

### ISSUE THREAD

**Issue by thelovekesh** [Automattic/amp-wp#7647]
### Bug Description

With https://github.com/WordPress/gutenberg/pull/54297 the support for disabling interactivity API has been removed due to which the `core/navigation` block now is using interactivity API by default and is not working as expected.

### Expected Behaviour

`AMP_Core_Block_Handler` should be updated to ampify interactivity API supported blocks and blocks should work as expected like they were before.

### Plugin Version

2.4.2

### AMP plugin template mode

Standard, Transitional

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Cross-verified the issue and the navigation menu block is functioning fine. Verified the block with the WP 6.4 and with the 6.3 and Gutenberg latest version it is functioning fine. The Hamburger menu is working fine.

**With WP v6.4 RC2.** 

<details><summary>Details</summary>

https://github.com/ampproject/amp-wp/assets/44057535/c978275b-5278-4c43-bfa0-b878c582425c

</details> 

---

**With WP v6.3 and latest Gutenberg plugin.** 

<details><summary>Details</summary>

[with63.webm](https://github.com/ampproject/amp-wp/assets/44057535/61bbbe87-69c3-4129-977d-0adbb9417811)

</details>
