### ISSUE TITLE
WordAds "Advertisements" Shown Incorrectly on AMP Pages

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/amp-wp#766]
In sites running Jetpack Ads (Wordads) and AMP, the "Advertisements" heading is shown in the incorrect location. 

To replicate:
1. Connect Jetpack and add a Premium or Professional plan.
2. Activate the Ads module.
3. Load the /amp version of any post or page.

Example page: https://www.binaryworld.es/2017/08/21/general/noticias/rumores-nuevos-posibles-elementos-iphone-8/amp/

This is in Spanish so it appears as "Anuncios."

Screenshot: https://cloudup.com/c51cpQl6-UE

At the moment, we have passed along the code that @dbspringer wrote to remove wordads from AMP pages.

cc: @codestor4 

Internal ref: 643958-zen

**Comment by westonruter** [comment]
It appears that AMP is no longer active on the site.

Nevertheless, I should think that Jetpack should actually be patched to fix compatibility with AMP, and not the other way around.

See also #217.
