### ISSUE TITLE
 The attribute 'fetchpriority' may not appear in tag 'img'

### ISSUE THREAD

**Issue by khabarsatta** [Automattic/amp-wp#7679]
### Bug Description

Chrome Extention SHowing Error: The attribute 'fetchpriority' may not appear in tag 'img'

### Expected Behaviour

Chrome Extention SHowing Error: The attribute 'fetchpriority' may not appear in tag 'img'

### Screenshots

![image](https://github.com/ampproject/amp-wp/assets/64256639/70c8b894-ae8a-4ff1-816b-1aa71cb5fb73)

### PHP Version

8.2

### Plugin Version

2.5.0

### AMP plugin template mode

Transitional

### WordPress Version

6.4.1

### Site Health

`
### wp-core ###

version: 6.4.1
site_language: en_US
user_language: en_US
timezone: +05:30
permalink: /%category%/%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 400
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/khabarsatta/public_html
wordpress_size: 12.99 GB (13943096221 bytes)
uploads_path: /home/khabarsatta/public_html/wp-content/uploads
uploads_size: 11.61 GB (12465060361 bytes)
themes_path: /home/khabarsatta/public_html/wp-content/themes
themes_size: 9.25 MB (9696928 bytes)
plugins_path: /home/khabarsatta/public_html/wp-content/plugins
plugins_size: 203.89 MB (213795238 bytes)
database_size: 601.94 MB (631177216 bytes)
total_size: 25.39 GB (27262825964 bytes)

### wp-dropins (4) ###

advanced-cache.php: true
db.php: true
maintenance.php: true
object-cache.php: true

### wp-active-theme ###

name: Foxiz (foxiz)
version: 2.1.5
author: Theme-Ruby
author_website: https://themeforest.net/user/theme-ruby/
parent_theme: none
theme_features: core-block-patterns, amp, automatic-feed-links, title-tag, html5, post-formats, post-thumbnails, editor-style, responsive-embeds, align-wide, woocommerce, wc-product-gallery-lightbox, wc-product-gallery-slider, menus, widgets
theme_path: /home/khabarsatta/public_html/wp-content/themes/foxiz
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (20) ###

Ad Inserter: version: 2.7.32, author: Igor Funa, Auto-updates disabled
Akismet Anti-spam: Spam Protection: version: 5.3, author: Automattic - Anti-spam Team, Auto-updates disabled
AMP: version: 2.5.0, author: AMP Project Contributors, Auto-updates disabled
Breadcrumb NavXT: version: 7.2.0, author: John Havlik, Auto-updates disabled
Elementor: version: 3.17.3, author: Elementor.com, Auto-updates disabled
Envato Market: version: 2.0.10, author: Envato, Auto-updates disabled
Foxiz Core: version: 2.1.5, author: Theme-Ruby, Auto-updates disabled
Jetpack: version: 12.8.1, author: Automattic, Auto-updates disabled
Perfmatters: version: 2.1.9, author: forgemedia, Auto-updates disabled
Performance Lab: version: 2.7.0, author: WordPress Performance Team, Auto-updates disabled
Query Monitor: version: 3.15.0, author: John Blackbourn, Auto-updates disabled
Redis Object Cache: version: 2.5.0, author: Till Krüss, Auto-updates disabled
Site Kit by Google: version: 1.114.0, author: Google, Auto-updates disabled
Web Stories: version: 1.35.0, author: Google, Auto-updates disabled
Wordfence Security: version: 7.11.0, author: Wordfence, Auto-updates disabled
WP Super Cache: version: 1.11.0, author: Automattic, Auto-updates disabled
Yoast SEO: version: 21.6, author: Team Yoast, Auto-updates disabled
Yoast SEO: News: version: 13.1, author: Team Yoast, Auto-updates disabled
Yoast SEO Premium: version: 21.6, author: Team Yoast, Auto-updates disabled
Yoast Test Helper: version: 1.17, author: Team Yoast, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1692
imagemagick_version: ImageMagick 6.9.12-93 Q16 x86_64 17898 https://legacy.imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 61 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 31 GB
	imagick::RESOURCETYPE_MEMORY: 15 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FLV, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.18.0-513.5.1.el8_9.x86_64 x86_64
httpd_software: Apache
php_version: 8.2.12 64bit
php_sapi: fpm-fcgi
max_input_variables: 2000
time_limit: 900
memory_limit: 1024M
max_input_time: 900
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.61.1 OpenSSL/1.1.1k
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2023-11-29T16:48:21+00:00
utc-time: Wednesday, 29-Nov-23 16:48:21 UTC
server-time: 2023-11-29T22:18:16+05:30

### wp-database ###

extension: mysqli
server_version: 8.0.35
client_version: mysqlnd 8.2.12
max_allowed_packet: 268435456
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/khabarsatta/public_html/wp-content
WP_PLUGIN_DIR: /home/khabarsatta/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: true
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 140035208
ssl_cert: No
time_diff: 1
version_option: 12.8.1:1700653932
old_version: 12.8.1:1700653932
public: Public
master_user: #8 Shubham Sharma
is_offline_mode: off
is_offline_mode_constant: off
current_user: #8 Shubham Sharma
tokens_set: Blog User
blog_token: v36guH98Xzxzop#BV6pPCNkM%%VW1KA^
user_token: 0w7j)oaggMsl0$!amzFg3eRUPH7c6PUV
version: 12.8.1
jp_plugin_dir: /home/khabarsatta/public_html/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Sat, 25 Nov 2023 16:20:11 +0000","finished":"Sat, 25 Nov 2023 16:20:22 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"8"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[8],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/khabarsatta.com","siteurl":"https:\/\/khabarsatta.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### google-site-kit ###

version: 1.114.0
php_version: 8.2.12
wp_version: 6.4.1
reference_url: https://khabarsatta.com
amp_mode: secondary
site_status: connected-site
user_status: authenticated
verification_status: verified-non-site-kit
connected_user_count: 1
active_modules: site-verification, search-console, adsense, analytics, analytics-4, pagespeed-insights, tagmanager
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/adsense.readonly: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_update_plugins: ✅
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ✅
	googlesitekit_view_wp_dashboard_widget: ✅
	googlesitekit_view_admin_bar_menu: ✅
	googlesitekit_view_shared_dashboard: ⭕
	googlesitekit_read_shared_module_data::["search-console"]: ⭕
	googlesitekit_read_shared_module_data::["adsense"]: ⭕
	googlesitekit_read_shared_module_data::["analytics"]: ⭕
	googlesitekit_read_shared_module_data::["analytics-4"]: ⭕
	googlesitekit_read_shared_module_data::["pagespeed-insights"]: ⭕
	googlesitekit_manage_module_sharing_options::["search-console"]: ✅
	googlesitekit_manage_module_sharing_options::["adsense"]: ✅
	googlesitekit_manage_module_sharing_options::["analytics"]: ✅
	googlesitekit_manage_module_sharing_options::["analytics-4"]: ✅
	googlesitekit_manage_module_sharing_options::["pagespeed-insights"]: ✅
	googlesitekit_delegate_module_sharing_management::["search-console"]: ✅
	googlesitekit_delegate_module_sharing_management::["adsense"]: ✅
	googlesitekit_delegate_module_sharing_management::["analytics"]: ✅
	googlesitekit_delegate_module_sharing_management::["analytics-4"]: ✅
	googlesitekit_delegate_module_sharing_management::["pagespeed-insights"]: ⭕
enabled_features: 
	adsenseSetupV2: ✅
	enhancedMeasurement: ✅
	gm3Components: ⭕
	keyMetrics: ⭕
search-console_shared_roles: none
search-console_management: owner
adsense_shared_roles: none
adsense_management: owner
analytics_shared_roles: none
analytics_management: owner
analytics-4_shared_roles: none
analytics-4_management: owner
pagespeed-insights_shared_roles: none
pagespeed-insights_management: all_admins
search_console_property: https://khabarsatta.com/
adsense_account_id: pub-691•••••••••••••
adsense_client_id: ca-pub-691•••••••••••••
adsense_account_status: ready
adsense_site_status: ready
adsense_use_snippet: yes
adsense_web_stories_adunit_id: 9228330247
adsense_setup_completed_timestamp: 1690653733
adsense_abr_use_snippet: yes
adsense_abr_use_error_protection_snippet: yes
adsense_abr_setup_status: setup-confirmed
analytics_account_id: 7311••••
analytics_property_id: UA-7311••••••
analytics_profile_id: 1664•••••
analytics_use_snippet: yes
analytics_4_property_id: 3084787••
analytics_4_web_data_stream_id: 3367••••••
analytics_4_measurement_id: G-KZ••••••••
analytics_4_use_snippet: yes
tagmanager_account_id: 4388••••••
tagmanager_container_id: GTM-5M6••••
tagmanager_amp_container_id: GTM-K8C••••
tagmanager_use_snippet: yes

### amp_wp ###

amp_slug_query_var: amp
amp_slug_defined_late: false
amp_mode_enabled: transitional
amp_reader_theme: legacy
amp_templates_enabled: post, page, is_singular
amp_serve_all_templates: false
amp_css_transient_caching_disabled: n/a
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 515
amp_css_transient_caching_time_series: 
	20231122: 286
amp_libxml_version: 2.11.5

### web_stories ###

web_stories_version: 1.35.0
web_stories_db_version: 3.0.16
web_stories_amp_version: 2.5.1-alpha
web_stories_cdn_url: https://wp.stories.google/static/19
web_stories_dev_mode: false
web_stories_theme_support: Disabled
web_stories_enabled_experiments: No experiments enabled
web_stories_libxml_version: 2.11.5

`

**Comment by westonruter** [comment]
This appears to be an issue with the AMP Validator extension. Namely, it seems to be out of date with the latest spec.

Try validating an AMP pages using the AMP Playground, for example: https://playground.amp.dev/?url=https%3A%2F%2Fkhabarsatta.com%2Fmp-news%2Fmp-weather-update-rain-expected-in-18-districts-on-november-26-western-disturbance-active-over-iran%2F%3Famp

No validation errors are reported.

**Comment by westonruter** [comment]
I've reported this upstream: https://github.com/ampproject/amphtml/issues/39661

You can just ignore this bug otherwise.

**Comment by westonruter** [comment]
FYI: The Chrome extension has been updated so it no longer reports an error.
