### ISSUE TITLE
Forms aren't able to validate correctly

### ISSUE THREAD

**Issue by stephywells** [Automattic/amp-wp#769]
The verify-xhr attribute is missing and needs to be allowed for forms in order to run validation and show the error messages. 

Also, the options currently allowed for visible-when-invalid do not pass AMP formatting validation. These must be camel caps in order to pass.

Pull request: https://github.com/Automattic/amp-wp/pull/768

**Comment by westonruter** [comment]
Closing since #768 has been merged.
