### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by kalyani2003** [Automattic/amp-wp#7695]
### Feature Description

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/ampproject/amp-wp/assets/84217977/478e0961-bda1-440f-92b4-6ee0182e5a41)

**Comment by kalyani2003** [comment]
@westonruter  Kindly assign me this issue, I want to work on it! Thank You.

**Comment by westonruter** [comment]
@kalyani2003 Hi! We list out the contributors who are involved with each release. See https://github.com/ampproject/amp-wp/releases

**Comment by kalyani2003** [comment]
okay, Thanks ;)
