### ISSUE TITLE
Multiposts do not work

### ISSUE THREAD

**Issue by Goran-n** [Automattic/amp-wp#770]
We are using amped sense to display ads.

Our site uses multi posts, example:

http://reciperoost.com/2017/08/27/this-3-in-1-breakfast-lunch-and-snack-recipe-will-make-you-everyones-favorite-person/
and
http://reciperoost.com/2017/08/27/this-3-in-1-breakfast-lunch-and-snack-recipe-will-make-you-everyones-favorite-person/2

When we install amp the multi post does not work. Instead the entire post which is broken into blocks in the wordpress editor gets shown as one post.

**Comment by Goran-n** [comment]
bump

**Comment by westonruter** [comment]
Did you disable the AMP plugin on your site? Multi-paged posts are not supported yet.

**Comment by westonruter** [comment]
Multi-paged posts are supported in the upcoming 0.7 release, if you have a theme that has `amp` theme support.
