### ISSUE TITLE
Featured image not getting shown on WhatsApp.

### ISSUE THREAD

**Issue by vintageanurag** [Automattic/amp-wp#7718]
### Bug Description

When AMP plugin is activated on WordPress website then when I share link of my post on WhatsApp then featured image is not visible with the link. I have tested it with Newspaper theme mostly. I have deactivated all cache related plugins along with optimization.

### Expected Behaviour

Expected behavior in this case should be that featured image should be visible.  

### PHP Version

8.1.27

### Plugin Version

2.5.2

### AMP plugin template mode

Reader

### WordPress Version

6.4.2

**Comment by milindmore22** [comment]
Hello @vintageanurag 

Thank you for reaching out to us, When we tested a [few pages](https://amp-wp.org/how-to-add-push-notifications-to-your-amp-wordpress-site/) from our websites and pages on WhatsApp, and we didn't locate any issues with preview. On both occasions, the preview was generated successfully. 

| While the link entered  | When Link is sent |
| ------------- | ------------- |
| ![Screenshot_20240118-124911](https://github.com/ampproject/amp-wp/assets/1132541/55131536-2e43-4f42-8259-8a141a39fd81) | ![Screenshot_20240118-124924](https://github.com/ampproject/amp-wp/assets/1132541/ac4fcf57-d1f9-4e0f-b64b-2564f5dc0424) |

We will recommend contacting us on the [WordPress support forums](https://wordpress.org/support/plugin/amp/#new-topic-0) with more details for further support related questions.
