### ISSUE TITLE
A not allowed script tag appeared

### ISSUE THREAD

**Issue by brunomosciatti** [Automattic/amp-wp#772]
Hey guys, after updating my plugin Im with some issues according to Google Search Console.

AMP Page for example: https://todateen.com.br/anitta-dj-alok-produzindo-parceria/amp/

The Amp Validator (https://validator.ampproject.org/) says that is a <script> tag not allowed
Printscreen: https://sketch.io/render/sk-974a93e9b0d78d4a3ac7bc2e9a57ba73.jpeg

The playbuzz tag:` [playbuzz-item item="5ea7b9e0-d919-4de0-b729-43171f0a2729" info="false" shares="false" comments="false" recommend="undefined" format="video-snaps"]`

Can you help me, please? :)

**Comment by brunomosciatti** [comment]
anyone?

**Comment by westonruter** [comment]
See also #761.
