### ISSUE TITLE
Update PHP-CSS-Parser to v8.5.0

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7721]
### Feature Description

There have finally been new releases of PHP-CSS-Parser. The most recent being [v8.5.0](https://github.com/sabberworm/PHP-CSS-Parser/releases/tag/8.5.0). We're currently pinned to a commit on `master`:

https://github.com/ampproject/amp-wp/blob/716c4188a9ee39e76222c2e20e16a748d93e4775/composer.json#L20

There haven't actually been many commits between where we pinned and the latest version: https://github.com/sabberworm/PHP-CSS-Parser/compare/cc791ad...8.5.0

Getting onto an actual version would be good so that dependabot can start updating it automatically.

**Comment by swissspidy** [comment]
This would be a nice change, especially now since the master branch has been renamed. That means I can't do a simple `composer update` in the Web Stories repo anymore

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

Verified it with themes such as Twenty Twenty-Four and Twenty Twenty-One, everything appears to be in order. No CSS breaking changes were observed.
