### ISSUE TITLE
Add support for amp-install-serviceworker

### ISSUE THREAD

**Issue by cungminh2710** [Automattic/amp-wp#773]
Check out [amp-install-serviceworker](https://www.ampproject.org/docs/reference/components/amp-install-serviceworker).
Wordpress users can enable their service worker script in AMP

P/s: I would love to contribute if possible

**Comment by westonruter** [comment]
There is a Jetpack PR that that is exploring service worker support for AMP: https://github.com/Automattic/jetpack/pull/7963/files#diff-97de6c62610ad3a332813a5f0e5aaa2eR107
