### ISSUE TITLE
Need a wordpress hook to change the form submit-success and submit-error element templates html content before rendered.

### ISSUE THREAD

**Issue by NovaYear** [Automattic/amp-wp#7744]
### Feature Description

We want to make changes to the default html content of the form submission result handler template, which looks much more compatible with the site design, but we cannot do this because there is no hook for this. It would be very functional if a compatible hook was made for this.

**Comment by westonruter** [comment]
The form sanitizer will [inject](https://github.com/ampproject/amp-wp/blob/2efb5c8fe9d31235269acddbb31a58016f569b70/includes/sanitizers/class-amp-form-sanitizer.php#L310-L332) a `submit-success`, `submit-error`, and `submitting` element templates _if_ it doesn't find them in the `form`. So you can override the default templates simply by adding them to your form so that the defaults aren't provided.

**Comment by NovaYear** [comment]
> The form sanitizer will [inject](https://github.com/ampproject/amp-wp/blob/2efb5c8fe9d31235269acddbb31a58016f569b70/includes/sanitizers/class-amp-form-sanitizer.php#L310-L332) a `submit-success`, `submit-error`, and `submitting` element templates _if_ it doesn't find them in the `form`. So you can override the default templates simply by adding them to your form so that the defaults aren't provided.

For now I'm doing it as you say. However, doing the same operation for many forms is tiring. If there was one hook, it would be much easier to get the same result in all forms by writing some code. 
in amp\includes\sanitizers\class-amp-form-sanitizer.php line 375 add after, maybe one line simple code "do_action( 'amp_ensure_response_message_elements_hook', $div);"
Moreover, it is very easy to integrate the hook, it only consists of 1 line of code, I will add it myself, but it will return to its previous state after the update. It would be much better if it was added officially by the community.

**Comment by milindmore22** [comment]
Hello @NovaYear 

Please try [this mini](https://github.com/milindmore22/amp-default-form-response) plugin, which inserts for response template and lets you modify the default response for forms on your AMP pages. To customize it, modify the code in `class-sanitizers.php` file and create the desired DOM elements. 
I hope this helps in customizing your website experience. 

Please let me know in case you need any help!

**Comment by NovaYear** [comment]
> Hello @NovaYear
> 
> Please try [this mini](https://github.com/milindmore22/amp-default-form-response) plugin, which inserts for response template and lets you modify the default response for forms on your AMP pages. To customize it, modify the code in `class-sanitizers.php` file and create the desired DOM elements. I hope this helps in customizing your website experience.
> 
> Please let me know in case you need any help!

Thank you very much for your time and effort. The code you prepared is a very smart idea. This made it easier for me to design my site, all forms are now in the same layout. I can easily add additional elements I need to the forms. Thank you again for sharing. I recommend it to those who need it. The plugin you provided meets the required need. In this case, the topic can be closed.
