### ISSUE TITLE
AMP error: Call to a member function hasAttribute() on null (0) [Error]

### ISSUE THREAD

**Issue by diabitogoaway** [Automattic/amp-wp#7757]
hello there, I've installed AMP plugin on my WordPress website but got the error below:
Call to a member function hasAttribute() on null (0) [Error]
/home/amatac/domains/amatacompany.com/public_html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/Dom/Document.php:400

#0 /home/amatac/domains/amatacompany.com/public_html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/Dom/Document.php(336): AmpProject\Dom\Document->loadHTMLFragment('<!DOCTYPE html>...', Array)
#1 /home/amatac/domains/amatacompany.com/public_html/wp-content/plugins/amp/vendor/ampproject/amp-toolbox/src/Dom/Document.php(234): AmpProject\Dom\Document->loadHTML('<!DOCTYPE html>...', Array)
#2 /home/amatac/domains/amatacompany.com/public_html/wp-content/plugins/amp/includes/class-amp-theme-support.php(1969): AmpProject\Dom\Document::fromHtml('<!DOCTYPE html>...', Array)
#3 /home/amatac/domains/amatacompany.com/public_html/wp-content/plugins/amp/includes/class-amp-theme-support.php(1732): AMP_Theme_Support::prepare_response('<!DOCTYPE html>...')
#4 [internal function]: AMP_Theme_Support::finish_output_buffering('<!DOCTYPE html>...', 9)
#5 /home/amatac/domains/amatacompany.com/public_html/wp-includes/functions.php(5373): ob_end_flush()
#6 /home/amatac/domains/amatacompany.com/public_html/wp-includes/class-wp-hook.php(324): wp_ob_end_flush_all('')
#7 /home/amatac/domains/amatacompany.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 /home/amatac/domains/amatacompany.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /home/amatac/domains/amatacompany.com/public_html/wp-includes/load.php(1260): do_action('shutdown')
#10 [internal function]: shutdown_action_hook()
#11 {main}

Also the template mode is on standard in AMP settings

These are the things I've tried:
I changed the theme to default WordPress themes
I deactivated all of other plugins
I updated the WordPress core to version: 6.4.3
All of my plugins are updated
None of them worked

I use the karaous theme
And this is my website:
amatacompany.com

**Comment by milindmore22** [comment]
Hello @diabitogoaway 

Can you please send your support UUID so that we can better understand your site? 

[![Support request](http://img.youtube.com/vi/wXoHwRvYsW8/0.jpg)](http://www.youtube.com/watch?v=wXoHwRvYsW8 "Support UUID")

**Comment by westonruter** [comment]
Closing due to lack of response.
