### ISSUE TITLE
How to enable it on the main theme?

### ISSUE THREAD

**Issue by htrex** [Automattic/amp-wp#778]
I'm starting to build a custom WP theme with native AMP code and planning to introduce service workers later on to transform it in a Progressive Web AMP (PWA) application.

I understand that this plugin offers alternative amp urls  instead, using a simplified theme to render posts while doing the hard job to cleanup the content.

I'd like to remove the alternative amp url that is injected in the page head and enable the content sanification and cleanup for regular *non* /amp urls.

Could please someone give some clue about how to proceed?

**Comment by westonruter** [comment]
What you're looking for is “AMP-as-canonical” (AMP Canonical) and initial support for this is being worked on in #668. It is planned for but it's not yet a capability. You can follow that pull request for updates.
