### ISSUE TITLE
Incorrect use of $query->get_posts(), resulting in double request processing

### ISSUE THREAD

**Issue by oglekler** [Automattic/amp-wp#7781]
### Bug Description

The WP_Query() constructor calls $this->get_posts() inside __constructor() and it is the longest method in the class and the next time it is called it does not return the result but rebuilds the entire query. The plugin uses this methog in 5 places.

### Expected Behaviour

The same as before but avoiding unnecessary data processing and requests.

### Plugin Version

2.5.3

### AMP plugin template mode

Standard

### WordPress Version

6.5

**Comment by westonruter** [comment]
@OlaIola Hi! So you're saying that anywhere that we're calling `$query->get_posts()` we should replace with `$query->posts`?

**Comment by oglekler** [comment]
Hi @westonruter 👋🏻
We should use getters if possible, but in this case it is not working as expected, and $posts property is public, so `$query->posts` is fine and will be a minimal change. Or it can be:
```
$query = new WP_Query(); 
$found_posts = $query->query( $args );
```

**Comment by westonruter** [comment]
I've opened #7782 to fix this. 

@OlaIola How did you discover this issue?

**Comment by oglekler** [comment]
I discovered this issue at my own code with Query Monitor, it indicated that I am making some requests twice. Data can be served from the cache object the second time, but WP_Query is still processing the request. Query Monitor is not working with feeds, but I went to look in the site code base for this issue in general.

**Comment by thelovekesh** [comment]
QA Passed ✅

See https://github.com/ampproject/amp-wp/pull/7782#issuecomment-2227444593
