### ISSUE TITLE
not compatible with php 7

### ISSUE THREAD

**Issue by rajuginne** [Automattic/amp-wp#779]
[php7:error] [pid 10793] [client 203.187.233.104:4344] PHP Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/wpdirectory/wp-content/plugins/amp/includes/utils/class-amp-dom-utils.php:7\nStack trace:\n#0 /**var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-content.php(98)**: 
AMP_DOM_Utils::get_dom_from_content('<p>Welcome to W...')\n#1 /var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-content.php(85): AMP_Content_Sanitizer::sanitize('<p>Welcome to W...', Array, Array)\n#2 /var/www/wpdirectory/wp-content/plugins/**amp/includes/class-amp-content.php(46):** 
AMP_Content->sanitize('<p>Welcome to W...')\n#3 /var/www/wpdirectory/wp-content/plugins/**amp/includes/class-amp-content.php(22):** AMP_Content->transform()\n#4 /var/www/wpdirectory/wp-content/plugins/**amp/includes**/class-**amp-post-template.php(257):****** AMP_Content->__construct('Welcome to Word...', Array, Array, Array)\n#5 /var/www/wpdirectory/wp-content/plugins/amp/includes/**class-amp-post-template.php(95):** 
AMP_Post_Template->build_post_content()\n#6 /var/www/de in /var/www/wpdirectory/wp-content/plugins/**amp/includes/utils/class-amp-dom-utils.php on line 7**

**Comment by rajuginne** [comment]
Not worked even php 7.0 also

[Sun Sep 17 14:57:02.503179 2017] [:error] [pid 18036] [client 203.187.233.104:3224] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/wpdirectory/wp-content/plugins/amp/includes/utils/class-amp-dom-utils.php:7\nStack trace:\n#0 /var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-content.php(98): AMP_DOM_Utils::get_dom_from_content('')\n#1 /var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-content.php(85): AMP_Content_Sanitizer::sanitize('', Array, Array)\n#2 /var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-content.php(46): AMP_Content->sanitize('')\n#3 /var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-content.php(22): AMP_Content->transform()\n#4 /var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-post-template.php(257): AMP_Content->__construct('', Array, Array, Array)\n#5 /var/www/wpdirectory/wp-content/plugins/amp/includes/class-amp-post-template.php(95): AMP_Post_Template->build_post_content()\n#6 /var/www/wpdirectory/wp-content/plugins/amp/amp.php(144): AMP_Post_Template- in /var/www/wpdirectory/wp-content/plugins/amp/i**ncludes/utils/class-amp-dom-utils.php on line 7**


# But worked with php5
| PHP 5.6.30-0

**Comment by rajuginne** [comment]
<?php

require_once( AMP__DIR__ . '/includes/utils/class-amp-dom-utils.php' );
require_once( AMP__DIR__ . '/includes/sanitizers/class-amp-base-sanitizer.php' );
require_once( AMP__DIR__ . '/includes/embeds/class-amp-base-embed-handler.php' );

**class AMP_Content {**  //line 7
	private $content;
	private $amp_content = '';
	private $amp_scripts = array();
	private $amp_styles = array();
	private $args = array();
	private $embed_handler_classes = array();
	private $sanitizer_classes = array();

	public function __construct( $content, $embed_handler_classes, $sanitizer_classes, $args = array() ) {
		$this->content = $content;
		$this->args = $args;
		$this->embed_handler_classes = $embed_handler_classes;
		$this->sanitizer_classes = $sanitizer_classes;

		$this->transform();
	}

**Comment by rajuginne** [comment]
`<?php

require_once( AMP__DIR__ . '/includes/utils/class-amp-dom-utils.php' );
require_once( AMP__DIR__ . '/includes/sanitizers/class-amp-base-sanitizer.php' );
require_once( AMP__DIR__ . '/includes/embeds/class-amp-base-embed-handler.php' );

class AMP_Content {  //line 7
	private $content;
	private $amp_content = '';
	private $amp_scripts = array();
	private $amp_styles = array();
	private $args = array();
	private $embed_handler_classes = array();
	private $sanitizer_classes = array();

	public function __construct( $content, $embed_handler_classes, $sanitizer_classes, $args = array() ) {
		$this->content = $content;
		$this->args = $args;
		$this->embed_handler_classes = $embed_handler_classes;
		$this->sanitizer_classes = $sanitizer_classes;

		$this->transform();
	}
`

**Comment by lkraav** [comment]
@rajuginne I think the problem may be that your PHP7 haven't built or enabled the DOMDocument module. Review your server software configuration.

**Comment by rajuginne** [comment]
Thank you, it's working after installing this

**sudo apt-get install php-xml**

**Comment by davideuler** [comment]
for php 7.1,
apt-get install php7.1-xml
systemctl restart php7.1-fpm

**Comment by DarthJahus** [comment]
Thanks, @rajuginne, you've saved my a**!
