### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by developdaly** [Automattic/amp-wp#78]
Using 0.1.

Photon enabled this first working block is what my typical image HTML looks like. The second block is with AMP. The image URLs are a bit different, but both are valid.

Console:
<img width="794" alt="screen shot 2015-11-14 at 9 15 32 am" src="https://cloud.githubusercontent.com/assets/167528/11164240/559e9e50-8ab0-11e5-9a15-caf09002063a.png">

Works:
`<img class=" size-full wp-image-2202 alignleft" src="http://i0.wp.com/developdaly.com/shared/content/uploads/2015/05/Screen-Shot-2015-05-12-at-1.38.51-PM.png?zoom=2&amp;resize=115%2C36" alt="Insecure https" width="115" height="36" srcset="http://i0.wp.com/developdaly.com/shared/content/uploads/2015/05/Screen-Shot-2015-05-12-at-1.38.51-PM.png?zoom=2&amp;resize=115%2C36" src-orig="http://i0.wp.com/developdaly.com/shared/content/uploads/2015/05/Screen-Shot-2015-05-12-at-1.38.51-PM.png?resize=115%2C36" scale="2">`

Doesn't work:
`<amp-img class=" size-full wp-image-2202 alignleft -amp-element -amp-layout-container -amp-error" src="http://i0.wp.com/developdaly.com/wp/../shared/content/uploads/2015/05/Screen-Shot-2015-05-12-at-1.38.51-PM.png?resize=115%2C36" alt="Insecure https" id="AMP_2"><img amp-img-id="AMP_2" alt="Insecure https" class="-amp-fill-content -amp-replaced-content" width="0" height="0"></amp-img>`

http://developdaly.com/seriously-banks-obvious-website-security-issues-at-major-us-banks/
vs
http://developdaly.com/seriously-banks-obvious-website-security-issues-at-major-us-banks/amp/

**Comment by mjangda** [comment]
Looks like the main validation issue is from the fact that the width and
height aren't being added to the amp-img tag.

Also concerning is the path traversal added to the URL in the amp-img tag
(not sure if related).

Does the same issue occur with the latest version in Github?

**Comment by developdaly** [comment]
`master` fixed the broken image.
