### ISSUE TITLE
Deprecation error with PHP 8.2

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#7817]
### Bug Description

A user [reported](https://wordpress.org/support/topic/deprecated-warning-in-php-8-2/) an error with PHP 8.2 version.

```
PHP Deprecated: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/www/wp-includes/formatting.php on line 4494
```
The error occurs when you choose a static page as home page and disable AMP on the home page, the error appears on the settings page when you disable support for all templates

### Expected Behaviour

The AMP version should be compatible with PHP 8.2

### Screenshots

![Screen Shot 2024-06-11 at 5 47 36 PM](https://github.com/ampproject/amp-wp/assets/1132541/77c95323-0349-4543-9975-d136e125280b)

Also note the over espcaing of the message.

### PHP Version

8.2

### Plugin Version

2.5.3

### AMP plugin template mode

Transitional

### WordPress Version

6.5.4

**Comment by pexlechris** [comment]
.

**Comment by Takshil-Kunadia** [comment]
Tried to reproduce this issue with PHP 8.2 but this issue doesn't seem to be present anymore.
Confirmed with @milindmore22 as well.
