### ISSUE TITLE
AUTHOR_STYLESHEET_PROBLEM,CUSTOM_JAVASCRIPT_DISALLOWED

### ISSUE THREAD

**Issue by Itsathere** [Automattic/amp-wp#784]
I am unable to use style-sheet from project directory and also unable to use **<script>** without type="application/ld+json" but if i use **type="application/ld+json"** instead  of **type="text/javascript"** then script not getting loaded.

I have script like below
**<script src="~/lib_bower/sweetalert/dist/sweetalert.min.js"></script>**
or
**<script type="text/javascript">
    $(document).on("ready", function () {
        LoadCartPorducts(function (result){});
        $(".homeCart").click(function () {
            $(this).toggleClass("open");
        });
    });
</script>**

I have style like below

**`<link rel="stylesheet" href="~/lib_bower/bootstrap/dist/css/bootstrap.min.css" />`**

Exception for style-sheet
**The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value '/**
Exception for script
**Only AMP runtime 'script' tags are allowed, and only in the document head.**

**Comment by rachmatyanuarsyah** [comment]
`<script>` tags are generally not allowed in AMP. There are a handful of external javascript files, built as part of the AMP project, which are allowed and even required in some cases. Other than those, javascript is not allowed. Custom script tags are not possible with AMP.

AMP pages can’t include external stylesheets, with the exception of custom fonts. You can embed custom fonts into your page in two ways according on [AMP Doc](https://www.ampproject.org/docs/guides/responsive/style_pages):

1. Through a <link> tag (white-listed font providers only)
 The following origins are white-listed and allowed for font serving via link tags:

- Typography.com: https://cloud.typography.com
-  Fonts.com: https://fast.fonts.net
-  Google Fonts: https://fonts.googleapis.com
-  Typekit: https://use.typekit.net
-  Font Awesome: https://maxcdn.bootstrapcdn.com

ie: `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">`

2. Via @font-face (no restrictions, all fonts allowed)
Alternatively, you can use @font-face within your AMP stylesheet:
`<style amp-custom>
  @font-face {
    font-family: "Bitstream Vera Serif Bold";
    src: url("https://somedomain.org/VeraSeBd.ttf");
  }
</style>`

**Comment by amedina** [comment]
Thanks for answering this @rachmatyanuarsyah
