### ISSUE TITLE
Checkbox icons are not properly visible 

### ISSUE THREAD

**Issue by pavanpatil1** [Automattic/amp-wp#7843]
### Bug Description

In the latest build from the develop branch, there is an issue with the visibility of checkbox icons on the settings page.

### Expected Behaviour

The check icons should be visible properly

### Screenshots

<img width="1429" alt="Screenshot 2024-07-09 at 3 34 02 PM" src="https://github.com/ampproject/amp-wp/assets/44057535/de0cebca-b32e-42bf-b663-bd0a9db062dd">

### Plugin Version

Version 2.5.4-alpha-20240708T165153Z-3175da6

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by thelovekesh** [comment]
Thanks @pavanpatil1! Can you please test if https://github.com/ampproject/amp-wp/pull/7844 fixes the issue?

**Comment by pavanpatil1** [comment]
Verified the fix and it is working fine. The checkbox is now visible properly.

![arrow](https://github.com/user-attachments/assets/9be340ad-89fd-4099-88c4-de68eb233f50)

**Comment by thelovekesh** [comment]
QA Passed ✅ 

The checkbox is visible as expected.

![image](https://github.com/user-attachments/assets/a045f8c4-9796-48f1-8a22-a8834622a9cd)
