### ISSUE TITLE
Warnings with arguments passed to function with amp_post_template_metadata hook

### ISSUE THREAD

**Issue by thomkitchen** [Automattic/amp-wp#785]
Just noticed that in trying to modify the json metadata created by the plugin, the example uses:

```
function xyz_amp_modify_json_metadata( $metadata, $post ){
  ...
}
```

I'm getting: 
Warning: Missing argument 2 for nesn_amp_modify_json_metadata(), called in...

When I remove $post as a parameter, warning isn't present.

**Comment by mjangda** [comment]
Does your `add_filter` call look like this:

```
add_filter( 'amp_post_template_metadata', 'nesn_amp_modify_json_metadata', 10, 2 );
```

Note the `2` as the fourth param.

**Comment by thomkitchen** [comment]
Woops!

I did not and that did it. Thank you.
