### ISSUE TITLE
AdSense or DoubleClick integration

### ISSUE THREAD

**Issue by abrambailey** [Automattic/amp-wp#787]
Is there a way to add AdSense or DoubleClick to AMP pages??

**Comment by websevendev** [comment]
You need to load the amp-ad component 

```
add_filter('amp_post_template_data', function($data) {
	$data['amp_component_scripts']['amp-ad'] = 'https://cdn.ampproject.org/v0/amp-ad-0.1.js';
	return $data;
});
```

and in templates put your ad network code:

[Adsense](https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.md):
```
<amp-ad width=300 height=250
      type="adsense"
      data-ad-client="ca-pub-2005682797531342"
      data-ad-slot="7046626912">
 </amp-ad>
```

[DoubleClick](https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md):
```
<amp-ad width=320 height=50
    type="doubleclick"
    data-slot="/4119129/mobile_ad_banner">
</amp-ad>
```
