### ISSUE TITLE
Google CMP not working nor any Cookie Plugin

### ISSUE THREAD

**Issue by trinikid101** [Automattic/amp-wp#7898]
Hey guys. I recently implemented AMP on my website trinikid.com and I am having problems with ads. Firstly, I don't see any in-page ads. Only ads at the top and bottom and I can't seem to install Google CMP messages. How do I get cookie consent messages on my amp site? I used CookieYes before but now it is not compatible. What do I do?

**Comment by westonruter** [comment]
@trinikid101 Hello! This seems like an appropriate question for the [support forum](https://wordpress.org/support/plugin/amp/). Could you please re-post it in a [new support topic](https://wordpress.org/support/plugin/amp/#new-topic-0)?
