### ISSUE TITLE
How to add navigation menu and sidebar menu

### ISSUE THREAD

**Issue by sureshpulipati** [Automattic/amp-wp#792]
How to add navigation menu and sidebar menu in AMP and also hot import scripts like `<script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>`. I'm using custom theme in my wordpress

**Comment by websevendev** [comment]
Create a template for the sidebar

```
// sidebar.php
<amp-sidebar id="sidebar-nav-menu" layout="nodisplay" sizes="(min-width:500px) 360px, 80vw">
	<button on="tap:sidebar-nav-menu.close">
		<i class="fa fa-close" aria-hidden="true"></i>
	</button>
	<?php wp_nav_menu([...]); ?>
</amp-sidebar>
```

You'll probably need to fork your menu walker and customize it to output amp-accordions and sections.

Then load the template in header-bar.php or where you need it:

`$this->load_parts(['sidebar']);`

and also add a trigger button:

`<button class="hamburger fa fa-bars" on="tap:sidebar-nav-menu.toggle"></button>`

If the sidebar is going to be on every page you can import your dependancies normally in functions.php or something:

```
add_filter('amp_post_template_data', function($data) {
	$data['font_urls']['FontAwesome'] = 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css';
	$data['amp_component_scripts']['amp-sidebar'] = 'https://cdn.ampproject.org/v0/amp-sidebar-0.1.js';
	$data['amp_component_scripts']['amp-accordion'] = 'https://cdn.ampproject.org/v0/amp-accordion-0.1.js';
	return $data;
});
```

I'm not sure about "hot importing". You could add some conditions to the function where scripts are loaded and same conditions to the `$this->load_parts(['sidebar'])` so they match. Or for example if you only want to load an AMP script when a certain shortcode is on the page, then I believe you are able to add that filter in the shortcode's render function.

**Comment by westonruter** [comment]
The recommended way for doing this going forward is to enable theme support so that you can fully reuse your active theme's templates, including whatever menus they use.

**Comment by Hoodlum-Z** [comment]
@westonruter AMP has removed my menu icon, but has left the text menu in the header. This is fine on desktop, but unsightly on mobile. So I added the AMP navbar and it works great, but now I've got two menus and if I try and disable the original menu on mobile it disables the AMP one as well. I've even asked my theme devs and they didn't have an answer. Tried implementing code from the various AMP websites, but still can't resolve it. Have you any advice please? https://gossiplolly.com Thanks

**Comment by westonruter** [comment]
@Hoodlum-Z please see https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/
