### ISSUE TITLE
Stylesheet for `amp-icons.css` is erroneously enqueued on frontend for non-AMP apge

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7922]
### Bug Description

I just noticed that `amp-icons.css` is getting printed on non-AMP pages:

```html
<link rel='stylesheet' id='amp-icons-css' href='http://localhost:10053/wp-content/plugins/amp/assets/css/amp-icons.css?ver=2.5.5' media='all' />
```

We need to figure out where this is getting enqueued from and prevent it.

### Expected Behaviour

Stylesheet should only be enqueued if it is needed. On the frontend, this would be if the admin bar is being shown.

### Plugin Version

2.5.5

### AMP plugin template mode

Transitional, Reader

**Comment by westonruter** [comment]
@Takshil-Kunadia FYI

**Comment by Takshil-Kunadia** [comment]
Thanks! @westonruter . I had a look into it.

> I just noticed that amp-icons.css is getting printed on non-AMP pages:

I can confirm this as well. It is being loaded on non-AMP pages.

> Stylesheet should only be enqueued if it is needed. On the frontend, this would be if the admin bar is being shown.

I can see that the AMP menu-item on non-amp pages uses the `amp-icons` css to display the icon & style it. Is the icon to be added in a different way?

<img width="1470" alt="Screenshot 2024-11-27 at 3 44 36 PM" src="https://github.com/user-attachments/assets/a11f7d19-ecc8-49e8-b118-c119f834b74b">

**Comment by westonruter** [comment]
Oh no, my mistake. I was checking while being logged-in so of course the `amp-icons.css` file would be present! Sorry for the misdirection.
