### ISSUE TITLE
> ### وصف الخلل

### ISSUE THREAD

**Issue by Zi55550** [Automattic/amp-wp#7939]
> ### وصف الخلل
> منذ الترقية إلى WP 6.7.1 توقفت جميع صفحات AMP عن العمل ويتم عرضها الآن بدون أي CSS.
> 
> ### السلوك المتوقع
> لتحميل CSS
> 
> ### لقطات الشاشة
> _لا يوجد رد_
> 
> ### نسخة PHP
> 8.3.13
> 
> ### إصدار البرنامج الإضافي
> 2.5.5
> 
> ### وضع قالب البرنامج الإضافي AMP
> انتقالي
> 
> ### نسخة ووردبريس
> 6.7.1
> 
> ### صحة الموقع
> _لا يوجد رد_
> 
> ### نسخة جوتنبرج
> _لا يوجد رد_
> 
> ### أنظمة التشغيل المتأثرة
> _لا يوجد رد_
> 
> ### المتصفحات المتأثرة
> _لا يوجد رد_
> 
> ### الأجهزة المتأثرة
> _لا يوجد رد_
> 
> ### معايير القبول
> _لا يوجد رد_
> 
> ### ملخص التنفيذ
> _لا يوجد رد_
> 
> ### تعليمات اختبار ضمان الجودة
> _لا يوجد رد_
> 
> ### العرض التوضيحي
> _لا يوجد رد_
> 
> ### إدخال سجل التغييرات
> _لا يوجد رد_

Git

_Originally posted by @Zi55550 in https://github.com/ampproject/amp-wp/issues/7923#issuecomment-2519208425_

**Comment by milindmore22** [comment]
Hello @Zi55550 
Please open a new topic on the [support forum](https://wordpress.org/support/plugin/amp/). Please share the Site Health information. closing this issue for now, we will reopen in case there are actual bugs found.
