### ISSUE TITLE
Issue Filtering Content

### ISSUE THREAD

**Issue by apautler** [Automattic/amp-wp#794]
I am using a variety of custom fields in my post, so I wrote a function to add those to the AMP pages. I am using an action/filter to run the custom field data through the_content filter via:

```php
add_action( 'pre_amp_render_post', 'ap_amp_add_custom_actions', 10 );
function ap_amp_add_custom_actions() {
   add_filter( 'the_content', 'ap_amp_add_custom_fields' );
}
```

The ap_amp_add_custom_fields is where I have all of the custom field data output. The main issue is I have YouTube links included in the custom fields. On some posts it appears to be filtering the content correctly, outputting the videos as files and adding the properly amp YouTube JS. On others though, it seems to be skipping the video, leaving the video link as text and not adding the proper AMP YouTube JS. Any ideas why this would be happening? Is there a better/different way to filter content in custom fields? Or is there a way to force the AMP YouTube JS file to load on all post pages?

**Comment by westonruter** [comment]
You need to amend `the_content` at a lower priority. You're currently appending at the priority 10 (which is the default). Embeds are processed at a priority of 8. Try this code:

```php
function ap_amp_add_custom_fields( $content ) {
	$content .= "\n\nhttps://www.youtube.com/watch?v=Nl6U7UotA-M";
	return $content;
}

add_action( 'pre_amp_render_post', 'ap_amp_add_custom_actions', 10 );
function ap_amp_add_custom_actions() {
	add_filter( 'the_content', 'ap_amp_add_custom_fields', 7 ); // 👈 6 instead of default 10
}
```

See underlying code in [`WP_Embed::__construct()`](https://github.com/WordPress/wordpress-develop/blob/a4f27c25bc86483491959ccbb364cfccff4d6f8d/src/wp-includes/class-wp-embed.php#L32-L40) for where the priority of 8 is defined.
