### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#797]
In order to make AMP Canonical possible (#668) we'll need native support for WordPress commenting. We could create an `amp-wordpress-comments` component, and extend `comment_form()` and `wp_list_comments()` to accept `format=amp` which would then render this. 

See also:
https://www.ampproject.org/docs/tutorials/login_requiring 
https://ampbyexample.com/samples_templates/comment_section/

**Comment by amedina** [comment]
@westonruter creating an amp-wordpress-comments component may not be necessary (and it would be hard to land it into the library); but the referenced methods can be extended to generate a  AMP-compatible format.

**Comment by westonruter** [comment]
I saw the [`amp-facebook-comments`](https://github.com/ampproject/amphtml/tree/master/extensions/amp-facebook-comments) component so I thought that might be a path, but yeah, it probably wouldn't be necessary since we could just use `amp-form` and other existing components.

**Comment by amedina** [comment]
Thinking more in general, I wonder if it would make sense to propose the creation of a set of AMP components that are specific to WordPress; given the prevalence of WP in the web ecosystem, the requirement of "general utility" would be satisfied. Will run the idea around to gather perspective.

**Comment by DavidCramer** [comment]
further information on this is on https://github.com/Automattic/amp-wp/issues/862

**Comment by westonruter** [comment]
The bare minimum it seems to add AMP support for the comment list is just to make sure that Gravatars use `amp-img` as opposed to `img`. In short, the following could be adapted and integrated into the theme support class:

```php
add_filter( 'get_avatar', function( $avatar ) {
	$avatar = str_replace( '<img', '<amp-img', $avatar );
	return $avatar;
} );
```

**Comment by westonruter** [comment]
It would be great to eventually support [`amp-list`](https://www.ampproject.org/docs/reference/components/amp-list) for comments, but that will require a lot more work, especially to support nested comment replies.

**Comment by alcurrie** [comment]
Functionality looks good and works well, but I noticed a couple of items that were not as expected:

1) **Issue:** Comment moderation does not display comments for previously approved comment authors. 
**Expected**
In the Discussion Settings, when the Before a comment appears:  Comment must be manually approved (is 'unchecked'), and  Comment Author must have a previously approved comment is checked:   https://cl.ly/442k1O2z1J0b
I expect that when I enter the same Name and email as a user whose comments have already been approved, that my comment will display right away. 
**Actual**
Even if the comment author has been previously approved, comment does not display. 

2) The confirmation of the comment post, is too close to the Post comment button:
![screen shot 2018-02-05 at 7 27 41 pm](https://user-images.githubusercontent.com/18579988/35835801-cf36935e-0aaa-11e8-90fd-ff75d201dd61.png)

3) From a usability perspective the comments seem quite far away from the actual article with several other articles between the bottom of the article the user is commenting on, with 3 other articles between the article and the comments on the article
https://cl.ly/1x0g0H0K421k

**Comment by westonruter** [comment]
> From a usability perspective the comments seem quite far away from the actual article with several other articles between the bottom of the article the user is commenting on, with 3 other articles between the article and the comments on the article
> https://cl.ly/1x0g0H0K421k

This is a known issue. See https://github.com/ampproject/amphtml/issues/5396#issuecomment-360873006

We may want to show the comment form _above_ the list because of this?

**Comment by Garcicasti** [comment]
Hi there,

Is it possible to get this functionality in lastest Wordpress, with Official AMP plugin in classic mode? I don't seem to have the capability for this.

Thanks a lot

**Comment by westonruter** [comment]
@Garcicasti See https://github.com/ampproject/amp-wp/issues/2044#issuecomment-608986964

**Comment by Garcicasti** [comment]
> @Garcicasti See [#2044 (comment)](https://github.com/ampproject/amp-wp/issues/2044#issuecomment-608986964)

Thanks a lot! Looks promising, though I can see that it still has some refinement coming.

**Comment by westonruter** [comment]
It provides a starting point for you to add comments to the classic post templates. 

We'll be adding full support for comments in Reader mode when selecting other themes: https://github.com/ampproject/amp-wp/issues/4560. We'll be allowing the user to select other templates from the core themes to be used in Reader mode, and these will include comments by default.
