### ISSUE TITLE
Add post preview support for AMP

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#799]
**[Edited] Refer to the latest [acceptance criteria](https://github.com/Automattic/amp-wp/issues/799#issuecomment-346622668).**
___
There is currently no way to preview how a post will look in AMP mode prior to publishing. We could add an AMP button next to existing Preview button which opens post with `?amp=1` in URL. Given post url of `http://example.com/?p=2043&preview=true` you just add `&amp=1` to it, then you get the AMP version of the post preview in your desktop browser.

Since “mobile” specifically in AMP itself is obsolete (as it is just as relevant for tablet and desktop), it is important to see how AMP looks across all devices sizes (Canonical AMP). If a user wants to see what mobile looks like they can just resize their browser window (or optionally include device preview buttons in admin bar like in Customizer).

**Comment by jwold** [comment]
Attached are some ideas for how we could display an AMP preview button within the WordPress admin. Would love feedback on these and other suggestions:

<img width="1366" alt="amp preview" src="https://user-images.githubusercontent.com/3411173/32465590-dd6fa590-c2f8-11e7-865c-fd3239cd955c.png">

**Comment by westonruter** [comment]
@jwold what about having a “combo” button similar to the Customizer in 4.9:

![image](https://user-images.githubusercontent.com/134745/32469007-91de3c7e-c305-11e7-91c4-239f057f8d8e.png)

But instead of the gear icon it could the AMP logo.

**Comment by jwold** [comment]
Adding the AMP logo in place of the gear could work well, my main concern would be if people know what that is.

**Comment by westonruter** [comment]
We could add have a tooltip, though we'd need to keep in mind accessibility and touch users.

**Comment by ThierryA** [comment]
### Acceptance criteria:
1. The existing “preview” button within the publish metabox will be updated to be a button group. 
2. The button will display “Preview”, as it does today. 
3. The right side of the button (separated by a vertical pipe) will display the AMP logo.
4. Selecting the left side of the button where “Preview” is displayed will allow the user to preview the original version of the page, same as they do today.
5. Selecting the right side of the button where the AMP logo is displayed will allow the user to preview the AMP version of the page.
6. If a page does not have AMP enabled (see ACs for #709 and #798) the Preview button will only display as a regular button, and a user will not have access the AMP logo to preview the page in AMP.

**Comment by csossi** [comment]
@westonruter , if a user is creating an "AMP optional" page and sets their ENABLE AMP radio button to "disabled", and then SAVE DRAFT, the refreshed screen has the new AMP LOGO button disappear. Makes sense.

But if they do the same thing except elect to PREVIEW before SAVE, then a preview will appear. It's a non-AMP page that shows up but wondering if it's possible to have the AMP LOGO button disappear/reappear on toggling between the enabled/disabled radio buttons. If it's "ok as is", then I'll move this over to ReadyToMerge

**Comment by westonruter** [comment]
@csossi I think it makes sense the way it is now. The switch from enabled to disabled should only cause the post to not be previewable once the change has been saved. The same goes for switching from published to password-protected: the password is only enforced once you hit save.

**Comment by csossi** [comment]
Understood - thanks
