### ISSUE TITLE
Initial feedback - many things not working (possible JetPack issue)

### ISSUE THREAD

**Issue by galbaras** [Automattic/amp-wp#80]
Just tried the plugin on http://www.get-business-online.com/ and saw the following:

<ol>
	<li>Static front page is not handled properly. When adding "amp/" to my home page, you get a 404</li>
	<li>When adding ?amp=1 to the home page, you get the blog page instead, apparently unchanged</li>
	<li>Links on AMP pages should have "amp/" to them. We can't expect mobile users to add that manually</li>
	<li>Pages and posts show with some standard theme and no navigation</li>
	<li>Sidebars seem to be ignored</li>
	<li>Sharing widget styling seems to be ignored and sharing links appear as simply links</li>
	<li>Permalinks must be updated after activation to make the "amp/" option work</li>
	<li>Adding "amp/" to a post category URL gives a 404</li>
	<li>Adding "?amp=1" to a post category URL shows the page unchanged</li>
</ol>

This plugin is seriously in its early stages.

Cheers,
Gal

**Comment by galbaras** [comment]
Why are you closing this?

**Comment by mjangda** [comment]
Sorry, I should have left some more context. Most of these are intentional design decisions (e.g. sidebars, category pages), known issues (sharing buttons, Pages), or already covered by other issues in this repo.
