### ISSUE TITLE
Move admin menu from top-level

### ISSUE THREAD

**Issue by michaeltorbert** [Automattic/amp-wp#803]
Having a top-level menu seems like overkill and goes against the plugin handbook: https://developer.wordpress.org/plugins/administration-menus/

<img width="777" alt="screen shot 2017-11-10 at 9 02 52 am" src="https://user-images.githubusercontent.com/17364998/32661732-0f7f5558-c5f6-11e7-8b34-6a34a133207a.png">
<img width="193" alt="screen shot 2017-11-10 at 9 02 47 am" src="https://user-images.githubusercontent.com/17364998/32661733-0f8cdf70-c5f6-11e7-97a5-2acf2fe83bc5.png">

I see that it can be removed by just returning false on amp_options_menu_is_enabled, but it would be helpful to just add it as a submenu.

**Comment by westonruter** [comment]
Agreed. We're thinking of consolidating the options into the Customizer. This will then allow for analytics changes to be tested before they go live. In 4.9 with the Customizer's frontend preview link, you'd be able to navigate to the site's frontend and then inspect the analytics calls.

Aside: In ≥4.9 we should use the new code editor control to add syntax highlighting and and linting for the JSON that is entered.

**Comment by michaeltorbert** [comment]
@westonruter That sounds awesome! 
In the meantime, it would be pretty quick and easy to demote the existing menu to a submenu.

**Comment by westonruter** [comment]
In the current version of the plugin in `develop` (0.6.0-alpha) there are now two admin screens: one for general settings (for now the supported post types) and the second for analytics:

![image](https://user-images.githubusercontent.com/134745/33789659-1cd7f904-dc2f-11e7-83b3-86b774a0ad3d.png)
