### ISSUE TITLE
Update allowed tags according to AMP specification

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#804]
**[Edited] Refer to the latest [acceptance criteria](https://github.com/Automattic/amp-wp/issues/798#issuecomment-346595030).**
___
It appears that the [`amp_wp_build.py`](https://github.com/Automattic/amp-wp/blob/647b003d90d7141ca7b54329ca186942ae149e46/bin/amp_wp_build.py) script hasn't been run since it was introduced at the end of 2016. Since that time, the [changes](https://github.com/Automattic/amp-wp/commits/master/includes/sanitizers/class-amp-allowed-tags-generated.php) to [`class-amp-allowed-tags-generated.php`](https://github.com/Automattic/amp-wp/blob/647b003d90d7141ca7b54329ca186942ae149e46/includes/sanitizers/class-amp-allowed-tags-generated.php) appear to have been done manually. There have been [95 commits](https://github.com/ampproject/amphtml/commits/master?path%5B%5D=spec) to the `spec` since the end of 2016, and these changes need to be comprehensively added to the plugin. 

I understand the `amp_wp_build.py` script has to be updated to account for some changes to the spec and to the amphtml project. For example, a dependency has been removed which has to be reverted or restored in some way: https://github.com/ampproject/amphtml/pull/10830

Additionally, the spec changes need to be more regularly applied, such as via Travis CI cron, if not done manually.

**Comment by ThierryA** [comment]
### Acceptance criteria:
1. We will conduct a Discovery to fully determine how the existing script is working.
2. Based on the findings of the Discovery we will determine the best way to fix the components/functions of the script that are either broken or not working as intended.
3. More details to come post Discovery...
