### ISSUE TITLE
Build out list of all vanilla WordPress “blocks” and their AMP compatibility

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#806]
**[Edited] Refer to the latest [acceptance criteria](https://github.com/Automattic/amp-wp/issues/806#issuecomment-348982141).**

_____

We want to ensure that if you have AMP installed as the sole plugin in a WordPress install that everything you can do in a vanilla WordPress site is compatible with AMP: every embed that a user can add to a post, every inserted media, every widget added to a sidebar, and even the various template parts that WordPress outputs (e.g. `wp_nav_menu()`, `get_search_form()`, and `comments_template()`). This can be paired with [Theme Unit Test](https://codex.wordpress.org/Theme_Unit_Test) sample data and validation checklists.

If we do this right, we can then incorporate the test data into the build process to make sure that we don't break AMP compatibility with anything WordPress does.

This will also need to be done for Gutenberg blocks.

**Comment by MackenzieHartung** [comment]
# Acceptance Criteria

1. Anything that WordPress allows to be input into post content, regarding embeds, should be supported by AMP.
2. Generate a list of all embeds that exist within WordPress (out of the box experience).
3. Verify which of the embed types work in AMP, somewhat work in AMP, or do not work in AMP.

**Comment by ThierryA** [comment]
## AMP Support

AMP Support | Status
------------ | -------------
Media Gallery | ✅ 
Media Image | ✅ 
Media Video | ✅
Media Audio | ✅ 
Media Video playlist | ❌ 
Media Audio playlist | ❌

**Comment by kienstra** [comment]
**Supported Embed Types**

Hi @ThierryA,
Your [comment above](https://github.com/Automattic/amp-wp/issues/806#issuecomment-350790526) shows whether most of WordPress's [supported embeds](https://codex.wordpress.org/Embeds#Okay.2C_So_What_Sites_Can_I_Embed_From.3F) render properly in AMP.

There are some embeds that don't even render in the standard WordPress page, like [Scribd](http://scribd.com) and [Photobucket](http://photobucket.com).

And @westonruter's [pull request](https://github.com/Automattic/amp-wp/pull/829) has the `wp-cli` script to create a test page with those embeds and media types.

**Comment by westonruter** [comment]
@kienstra It looks like some of the oEmbed providers aren't all listed yet. I'm looking at the list here: https://github.com/WordPress/wordpress-develop/blob/c6326694380722ccbdd78e21a2bd0d079383291c/src/wp-includes/class-oembed.php#L54-L119

I don't see animoto, speakerdeck, or amazon for example. Could you please make sure every oEmbed is included in the list and in the test data?

**Comment by kienstra** [comment]
**Will Add Missing oEmbed URLS**

Hi @westonruter,
Sure, I'll add the missing oEmbed URLs tomorrow (Thursday) if that's alright.

**Comment by westonruter** [comment]
Deployed changes to the testbed site and created test page with embeds:

Non-AMP: http://amp-xwp-testbed.pantheonsite.io/amp-test-embeds/
AMP: http://amp-xwp-testbed.pantheonsite.io/amp-test-embeds/?amp

**Comment by ahmadawais** [comment]
@ThierryA it would be great to have that AMP Support table there on the `README.md` or in a AMP-`SUPPORT.md` what do you think?

Also excited about this enhancement.

**Comment by ThierryA** [comment]
Thanks for your suggestion @ahmadawais, a wiki page would probably be the best place for that. The readme is already pretty long and we plan to do more "Vanilla WordPress Support" discovery such as widgets etc.

**Comment by westonruter** [comment]
The wiki is easier to update on an ongoing basis as well.

**Comment by ahmadawais** [comment]
Right about that. Works for me.

**Comment by kienstra** [comment]
**Wiki Page**

Hi @ahmadawais and @westonruter,
Here's the [wiki page](https://github.com/Automattic/amp-wp/wiki/Native-WordPress-Widget-and-Embed-Support) that shows widget and embed support.
