### ISSUE TITLE
Add meta tag for identifying AMP pages generated by plugin

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#807]
**[Edited] Refer to the latest [acceptance criteria](https://github.com/Automattic/amp-wp/issues/807#issuecomment-347297897).**
___

It would be very useful to have a distinct signature for easily identifying AMP pages generated by the plugin; something along these lines:

```html
<meta name="generator" content="AMP Plugin v0.5.1" />
```

**Comment by MackenzieHartung** [comment]
***Acceptance Criteria

1. The plugin will automatically generate a meta tag for easy identification of AMP Pages.
2.  The meta tag will be as follows (or the like): <meta name="generator" content="AMP Plugin v0.5.1" />

**Comment by csossi** [comment]
Tag appearing as:
<meta name="generator" content="AMP Plugin v0.6.0-alpha" />

on AMP pages
