### ISSUE TITLE
Convert Vine oEmbed URL and shortcode to <amp-vine>

### ISSUE THREAD

**Issue by niallkennedy** [Automattic/amp-wp#81]
A Vine video is described in an AMP template as `<amp-vine vineid="">`

A Vine video may appear in WordPress content as an oEmbed-compatible URL. Vine is a supported oEmbed provider as of WordPress 4.1.

A Vine video may be specified in a shortcode as `[vine url=""]` or `[vine id=""]`

* [WordPress.com Vine docs](https://en.support.wordpress.com/videos/vine/)
* [AMP template component](https://github.com/ampproject/amphtml/blob/master/extensions/amp-vine/amp-vine.md)

**Comment by mjangda** [comment]
Are there any other URL formats for vine than `https://vine.co/v/MdKjXez002d`?

**Comment by niallkennedy** [comment]
A video link appears as:
https://vine.co/v/MdKjXez002d

It may have additional query parameters such as ref=email, which do not affect display and which do not need to be interpreted for <amp-vine>. There is currently no autoplay audio or postcard template option for the AMP Vine component.
