### ISSUE TITLE
WordPress.org version not in sync

### ISSUE THREAD

**Issue by stephengreer08** [Automattic/amp-wp#814]
It seems like the [WordPress Repo](https://wordpress.org/plugins/amp/) version of this plugin is a different code base, yet they link to each other and have the same version number.

Are there plans to update the WP.org version to the same as what is here? If not, they probably shouldn't link to each other, or at least have a note in the README about this and different version numbers.

**Comment by westonruter** [comment]
The version in GitHub will always be ahead of what is on WordPress.org. The GitHub version is bleeding edge “trunk” whereas WordPress.org is the last stable release.

**Comment by stephengreer08** [comment]
@westonruter okay, that makes sense. We were cloning the most recent version of the develop branch, rather than the actual release. Thank you for clearing that up.
