### ISSUE TITLE
Exclude content on a per-post basis 

### ISSUE THREAD

**Issue by justinferrell** [Automattic/amp-wp#82]
A lot of pages that use custom templates may not have a conventional IMAGE/TITLE/CONTENT structure. The ability to prevent those pages from generating what would essentially be empty AMP pages would be useful.

**Comment by mjangda** [comment]
For now, the best way to skip specific posts is to use the `amp_skip_post` filter:

This example will skip all posts with the "photo" tag:

```
add_filter( 'amp_skip_post', 'mj_skip_photo_posts', 2 );

function mj_skip_photo_posts( $skip, $post_id ) {
    if ( has_tag( 'photo', get_post( $post_id ) ) {
        $skip = true;
    }
    return $skip;
}
```
