### ISSUE TITLE
Add caption support to all amp-instagram embeds

### ISSUE THREAD

**Issue by hrkhal** [Automattic/amp-wp#822]
We've started to receive "Social Media Issues" emails from the Google Search Console because our `amp-instagram` embeds are missing captions which we display on the canonical by default.

They state: "Instagram posts embedded in the article are missing captions, which leads to context being lost."

Caption support for `amp-instagram` embeds was only added at the end of March this year.
https://github.com/ampproject/amphtml/pull/8243

I propose making the necessary changes to `amp-wp/includes/embeds/class-amp-instagram-embed.php` to allow captions to be shown as default for all `amp-instagram` embeds to avoid future "Social Media Issues" for publishers.

If people are happy for this go ahead, I'll knock up the needed PR as soon as I can.

**Comment by westonruter** [comment]
Makes sense to me. Feel free to open a pull request.
