### ISSUE TITLE
How to disable contactform 7 or make it work on amp page?

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [Automattic/amp-wp#824]
IN current situation my amp [page](http://www.greenaircleaningnyc.com/new-york-city-sanitation-garbage-recycling-procedures/amp/#development=1.) is showing jquery is not defined causing the contact form ( "Get a free quote" ) not working. I would like to be working as expected same to non-amp page or would like remove it from all amp pages. Please give me some idea how I can achieve it?

**Comment by beeriz** [comment]
Did you find a solution? 
I need to disable a plugin on AMP too
