### ISSUE TITLE
Customize the navbar at the top

### ISSUE THREAD

**Issue by justinferrell** [Automattic/amp-wp#83]
Replace the SVG logo with the site icon if one is available and allow the color of the bar to be specify in the appearance customizer.
- [x] Show <a href="https://make.wordpress.org/core/2015/07/27/site-icon/">Site Icon</a>, if set (instead of WP logo)
- [ ] Show <a href="https://codex.wordpress.org/get_header_image">header image</a>, if set

**Comment by mjangda** [comment]
Plus, header image if set.

**Comment by westonruter** [comment]
This is obsolete now that the plugin encourages use of AMP with your active theme's templates (as of 1.0).
