### ISSUE TITLE
Where to remove a anchor text link underline?

### ISSUE THREAD

**Issue by matif78** [Automattic/amp-wp#834]
Hi,

I am struggling to remove underline but don't know where this styling come from ?

I have removed all styling from templates/style.php but still showing even its not in Custom CSS.
a, a:active, a:visited {
    text-decoration: underline;
}

Can you please help me out

Thanks in Advance
Atif

**Comment by westonruter** [comment]
Underline is a default style in browsers. You should instead add `text-decoration: none`.
