### ISSUE TITLE
Removing featured image from AMP

### ISSUE THREAD

**Issue by hakhan201** [Automattic/amp-wp#838]
Hello,

I added the following code to my themes function.php file but it didn't remove the featured image from AMP pages.

```
add_filter( 'amp_post_template_data', 'xyz_amp_remove_featured_image' );

function xyz_amp_remove_featured_image( $data ) {
    $data['featured_image'] = false;
    return $data;
}
```

Any idea what could be the issue? 

I was able to change the "Schema.org (JSON) Metadata logo and article type" easily with the code [provided in the readme.md file](https://github.com/Automattic/amp-wp/blob/master/readme.md).

Thank you

**Comment by Mathivananme** [comment]
Don't paste it in function.php.. Just go to plugins and then click editor and choose amp plugin then paste this code it'll work

**Comment by westonruter** [comment]
@hakhan201 you need to put the code in your theme's `functions.php` (plural) not `function.php` (singular). WordPress doesn't recognize the latter. I just tried adding the code you my theme's `functions.php` and it removed the featured image as expected.
