### ISSUE TITLE
Discovery to determine support for all native WordPress widgets

### ISSUE THREAD

**Issue by MackenzieHartung** [Automattic/amp-wp#844]
### Acceptance Criteria 

AC1: Need to conduct a Discovery to determine all native WordPress sidebar widgets, and the support that exists for them today. Screenshot: https://d.pr/i/vBQaFt .
AC2: One story will be created as an outcome of the Discovery to address enhanced/added support for sidebar widgets.

**Comment by westonruter** [comment]
Closing in favor of #839.
