### ISSUE TITLE
Conduct a Discovery to determine support for Gutenberg blocks.

### ISSUE THREAD

**Issue by MackenzieHartung** [Automattic/amp-wp#845]
### Acceptance Criteria

AC1: Create a wp-cli script to output all native Gutenberg blocks on a test page to identify which will need to be supported (see this [script](https://github.com/Automattic/amp-wp/blob/develop/bin/create-embed-test-post.php) for reference).

**Comment by kienstra** [comment]
**Example wp-cli Scripts**

 Hi @DavidCramer,
It looks like you wrote the `wp-cli` script [create-comments-on-test-post.php](https://github.com/Automattic/amp-wp/blob/develop/bin/create-comments-on-test-post.php), so you probably have a good handle on this. This issue's script for Gutenberg blocks should probably be similar to [create-embed-test-post.php](https://github.com/Automattic/amp-wp/blob/develop/bin/create-embed-test-post.php).

**Comment by kienstra** [comment]
**Permutations Of Blocks**

We should probably output all of the blocks in [blocks/library/](https://github.com/WordPress/gutenberg/tree/8b4a61df4b2b1b57c99cb26a8b7f6978ae2f071f/blocks/library). Here are some blocks that I think could use permutations:

* [Categories](https://github.com/WordPress/gutenberg/tree/8b4a61df4b2b1b57c99cb26a8b7f6978ae2f071f/blocks/library/categories) 
1. With dropdown
2. Without dropdown

* [Columns](https://github.com/WordPress/gutenberg/tree/8b4a61df4b2b1b57c99cb26a8b7f6978ae2f071f/blocks/library/columns)
2 and 4 columns

* [Cover Image](https://github.com/WordPress/gutenberg/tree/8b4a61df4b2b1b57c99cb26a8b7f6978ae2f071f/blocks/library/cover-image) 
1. Fixed Background on
2. Fixed Background off

* [Embed](https://github.com/WordPress/gutenberg/tree/8b4a61df4b2b1b57c99cb26a8b7f6978ae2f071f/blocks/library/embed)
2 or 3 embed URLs should be enough. #841 handles embed support, though not in Gutenberg.

* [Gallery](https://github.com/WordPress/gutenberg/tree/8b4a61df4b2b1b57c99cb26a8b7f6978ae2f071f/blocks/library/gallery)
2 and 3 columns

* [Shortcode](https://github.com/WordPress/gutenberg/tree/8b4a61df4b2b1b57c99cb26a8b7f6978ae2f071f/blocks/library/shortcode)
2 or 3 shortcodes should be enough, as we've tested several in #841.

**Comment by westonruter** [comment]
Results should be added to this Wiki page: https://github.com/Automattic/amp-wp/wiki/Native-WordPress-Widget-and-Embed-Support

**Comment by amedina** [comment]
@westonruter should we create another wiki page to track exclusively Gutenberg blocks (both Gutenberg => AMP and AMP => Gutenberg)?

**Comment by westonruter** [comment]
Yeah, that would work as well. Maybe we should have separate wiki pages for embeds and widgets. Main thing is that there should be a wiki page to document it.

**Comment by kienstra** [comment]
**Gutenberg Fixtures**

The [test fixtures in Gutenberg](https://github.com/WordPress/gutenberg/tree/master/blocks/test/fixtures) could be useful for this. This script could use the `.html` files in [blocks/test/fixtures/](https://github.com/WordPress/gutenberg/blob/master/blocks/test/fixtures/), like [core__categories.html](https://github.com/WordPress/gutenberg/blob/master/blocks/test/fixtures/core__categories.html). 

But the [core-embed__*.html](https://github.com/WordPress/gutenberg/blob/master/blocks/test/fixtures/core-embed__wordpress.html) files might not be as useful, as they don't have specific embed URLs.

**Comment by kienstra** [comment]
**In Progress**

I'm working on this now.

**Comment by kienstra** [comment]
**[Gutenberg Block](https://github.com/WordPress/gutenberg/tree/master/blocks/library) Support**

Here are the results of running the `wp-cli` script from PR #1018. When Gutenberg is active, its built stylesheet `gutenberg/blocks/build/style.css` apparently makes the inlined CSS go over the 50 KB limit. 

So the ampconf theme's [main.css](https://github.com/xwp/ampconf/blob/develop/assets/dist/css/main.css) file wasn't part of `<style amp-custom>`. I manually copied that file into the inspector stylesheet to test this. So these tests assume that the Gutenberg stylesheet above is applied.

I'll move this matrix into the [project wiki](https://github.com/Automattic/amp-wp/wiki/) when the script passes review.

Block | Support | Notes
--- | --- | ---
[Audio](https://github.com/WordPress/gutenberg/tree/master/blocks/library/audio)  | ✅|
[(Reusable) Block](https://github.com/WordPress/gutenberg/tree/master/blocks/library/block)  |  ✅|
[Button](https://github.com/WordPress/gutenberg/tree/master/blocks/library/button)  |  ✅|
[Categories](https://github.com/WordPress/gutenberg/tree/master/blocks/library/categories)  | 🔸| Styling issue: inherits the `text-align:center` of `div.wp-block-categories`
[Categories With Dropdown](https://github.com/WordPress/gutenberg/tree/master/blocks/library/categories)  | ❌ | Selecting an `<option>` in the dropdown doesn't redirect to the category page. See Weston's solution for the [Categories widget](https://github.com/Automattic/amp-wp/blob/develop/includes/widgets/class-amp-widget-categories.php#L70).
[Code](https://github.com/WordPress/gutenberg/tree/master/blocks/library/code)  |  ✅|
[Columns](https://github.com/WordPress/gutenberg/tree/master/blocks/library/columns)  | ✅|
[Cover Image](https://github.com/WordPress/gutenberg/tree/master/blocks/library/cover-image)  | ✅| 
[Cover Image](https://github.com/WordPress/gutenberg/tree/master/blocks/library/cover-image) With Fixed Background  | ✅| 
[Embed](https://github.com/WordPress/gutenberg/tree/master/blocks/library/embed)  | ✅| 
[Freeform](https://github.com/WordPress/gutenberg/tree/master/blocks/library/freeform)  | ✅| 
[Gallery](https://github.com/WordPress/gutenberg/tree/master/blocks/library/gallery)  | 🔸| Styling issues with 2 or 3 columns ([screenshot](https://cloudup.com/cS-_wINgLxg))
[Heading](https://github.com/WordPress/gutenberg/tree/master/blocks/library/heading)  | ✅|
[HTML](https://github.com/WordPress/gutenberg/tree/master/blocks/library/html)  | 🔸| The `<marquee>` [element is stripped](https://github.com/WordPress/gutenberg/blob/master/blocks/test/fixtures/core__html.html#L3)
[Image](https://github.com/WordPress/gutenberg/tree/master/blocks/library/image)  | 🔸| Styling issue: the caption should be centered when set to 'Align center' ([screenshot](https://cloudup.com/cudE562KX1G)) 
[Latest Posts](https://github.com/WordPress/gutenberg/tree/master/blocks/library/latest-posts)  | 🔸| Styling issue: the posts are in the center, bullets on the left ([screenshot](https://cloudup.com/cfEG0ETmC4N))
[List](https://github.com/WordPress/gutenberg/tree/master/blocks/library/list)  | ✅ | 
[More](https://github.com/WordPress/gutenberg/tree/master/blocks/library/more)  |  ❌| Doesn't appear
[Paragraph](https://github.com/WordPress/gutenberg/tree/master/blocks/library/paragraph)  | ✅ |
[Preformatted](https://github.com/WordPress/gutenberg/tree/master/blocks/library/preformatted)  | ✅ |
[Pullquote](https://github.com/WordPress/gutenberg/tree/master/blocks/library/pullquote)  | 🔸| Styling issue: the pullquotes aren't wide enough ([screenshot](https://cloudup.com/c88Xz-wRK_b))
[Pullquote](https://github.com/WordPress/gutenberg/tree/master/blocks/library/pullquote)  | 🔸| Styling issue: the pullquotes aren't wide enough
([screenshot](https://cloudup.com/c88Xz-wRK_b))
[Quote](https://github.com/WordPress/gutenberg/tree/master/blocks/library/quote)  | ✅ |
[Separator](https://github.com/WordPress/gutenberg/tree/master/blocks/library/separator)  |  ❌| Doesn't appear
[Shortcode](https://github.com/WordPress/gutenberg/tree/master/blocks/library/preformatted)  | ✅ | 'Gallery' and 'Caption' appear as expected. This is tested more extensively in [this wiki page].(https://github.com/Automattic/amp-wp/wiki/Native-WordPress-Widget-and-Embed-Support)
[Subhead](https://github.com/WordPress/gutenberg/tree/master/blocks/library/subhead)  | ✅ |
[Table](https://github.com/WordPress/gutenberg/tree/master/blocks/library/table)  | ✅ |
[Text Columns](https://github.com/WordPress/gutenberg/tree/master/blocks/library/text-columns)  | ✅ |
[Verse](https://github.com/WordPress/gutenberg/tree/master/blocks/library/verse)  | ✅ |
[Video](https://github.com/WordPress/gutenberg/tree/master/blocks/library/video)  | ✅ |





**Legend**

 ✅ Supported
 🔸 Partially supported
 ❌ Not supported

**Comment by westonruter** [comment]
Note that the test page created with #1018 should be tested with the Gutenberg block validation from #1019.

**Comment by miina** [comment]
Question on the `Categories` issue of `aligncenter` -- the default alignment of `core/categories` block is `center` -- would't this be the expected behavior in this case?

**Comment by kienstra** [comment]
**Categories Alignment**

Hi @miina,
Good question. I think the issue with the categories widget from the [screenshot](https://cloudup.com/cGstQL-pPHj) is that the bullets are on the left, while the text is center-aligned.

**Comment by miina** [comment]
Hey @kienstra Thanks for the answer.
Looks like the `li` elements have max width and since the bullet is always before the `li` element and the text of the contained `a` is in the center, then that's the default result.

Perhaps that's how it's supposed to be without any additional styling?
Or any thoughts on what would be the correct behavior with `aligncenter`?

**Comment by miina** [comment]
**More block**

Looks like the `More` block is meant to show up only on the index pages -- it displays a link to continue reading (in case of desktop and tablet), displaying the text on index pages only until the `More` block and hiding the rest (in case of mobile it looks like it's just cutting the text off after `More` block without showing the link at all). If I'm not mistaken then in case of the test page the `More` block is not supposed to show up.

**Comment by kienstra** [comment]
**Thanks, Matrix Moved To Wiki**

Hi @miina,
Thanks for these point you raised, which I'm looking at now. And thanks for pointing out that the separator display.

Let's used the matrix on the [wiki page now](https://github.com/Automattic/amp-wp/wiki/Gutenberg-Block-Support), instead of the one above. I'll keep updating the wiki, not this issue.

**Comment by kienstra** [comment]
**Categories Alignment**

Hi @miina,
Thanks for your points about the 'Categories' block styling. I think you're right that the block behaves as expected. 

This is probably from how [the theme handles](https://github.com/xwp/ampconf/blob/10397dddef6133a00cf452b22ee66c2e32f97de2/assets/src/css/components/_entry.scss#L110) `.aligncenter`. Though [it looks](https://cloudup.com/cGstQL-pPHj) a little strange to me, maybe that's what's expected.

There doesn't look to be an issue with Gutenberg here, as it only applies the class `aligncenter`.

This is the same case in the 'Latest Posts' block. I'm changing both in the [wiki page](https://github.com/Automattic/amp-wp/wiki/Gutenberg-Block-Support) to 'supported.'

**Comment by kienstra** [comment]
**More Tag**

Hi @miina,
Thanks for your point about the [More](https://en.support.wordpress.com/more-tag/) block. I think you're right that it's not expected to display on this page, so I'm changing support on the [wiki page](https://github.com/Automattic/amp-wp/wiki/Gutenberg-Block-Support) to 'supported.'

**Comment by miina** [comment]
@kienstra Thanks for looking into these issues and for the quick update.

**Comment by kienstra** [comment]
**Changed HTML Block To 'Supported'**

AMP stripped the `<marquee>` element, but that [looks to be obsolete](https://github.com/WordPress/gutenberg/tree/master/blocks/library/html).

**Comment by kienstra** [comment]
**Results Of Using Validator On Block Test Page**

Hi @westonruter,
Here are the results of using your validation of blocks in #1019.

**Gutenberg Issues**
* [Categories](https://github.com/WordPress/gutenberg/blob/master/blocks/library/categories/index.php#L70) with a dropdown: the preprocessor stripped the [script that it output](https://github.com/WordPress/gutenberg/blob/master/blocks/library/categories/index.php#L70). That's now noted on the [wiki page](https://github.com/Automattic/amp-wp/wiki/Gutenberg-Block-Support).
* CSS overflow property removed from `gutenberg/blocks/build/style.css`

**Shortcode Issue**
* [Shortcode](https://github.com/WordPress/gutenberg/tree/master/blocks/library/shortcode) block with an 'audio' shortcode: not specifically an issue with Gutenberg, just the shortcode. The preprocessor stripped several scripts and styles from [wp_audio_shortcode()](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/media.php#L2314).

**Comment by miina** [comment]
Thank you for the update, @kienstra, looks like as of this moment the issue to handle within #1010 is just the `Categories` with a dropdown.

**Comment by kienstra** [comment]
Sure, @miina. You probably saw it, but Weston's solution for the [Categories widget](https://github.com/Automattic/amp-wp/blob/develop/includes/widgets/class-amp-widget-categories.php#L70) would probably help with this.

**Comment by miina** [comment]
Yes, saw your note about it in the table, definitely helpful, thanks @kienstra!

**Comment by westonruter** [comment]
I think the discovery has been completed so this can be closed?

**Comment by kienstra** [comment]
Hi @westonruter, yes, this can be closed.
