### ISSUE TITLE
AMP Tag and Attribute Sanitizer doesn't handle namespaced attributes

### ISSUE THREAD

**Issue by cilquirm** [Automattic/amp-wp#847]
It appears that the AMP_Tag_And_Attribute_Sanitizer that runs at the end of the sanitizer list doesn't strip out attributes that are namespaced.

For example, if you create a post that has the following html:

```html
<p xml:lang="EN_US" lang="EN_US"> This is a test </p>
```
 ( which can occasionally happen when people copy from sites such as twitter ).

the lang property is stripped, but the xml:lang, ostensibly because it's under the XML namespace, is not.

The sanitizer should check if an attribute is namespaced, and then use the corresponding 

`removeAttributeNS` to remove the attribute.

**Comment by westonruter** [comment]
I think this is something that should be raised on the [amphtml](https://github.com/ampproject/amphtml) project. XML-namespaced attributes aren't allowed by the spec at all. For example, if you go to https://validator.ampproject.org/ and try adding `<p xml:lang="EN_US" lang="EN_US"> This is a test </p>` then it will output the error:

> The attribute 'xml:lang' may not appear in tag 'p'.

**Comment by cilquirm** [comment]
Maybe I missed something, but I thought the point of the AMP_Tag_And_Attribute_Sanitizer was to clean up tags and attributes that don't follow the spec, thereby resulting in a valid AMP document.  At least from my reading of the code, it seems to remove DOM nodes that don't qualify as whitelisted tags and attributes.

I'm not saying `xml:lang` attributes should be allowed; i posted an issue here because i noticed that, while many tags and attributes were being properly "sanitized', such as the `lang` property in our examples, namespaced attributes and tags were not.

Is the contention here that this is not the job of the Tag_And_Attribute_Sanitizer?

**Comment by westonruter** [comment]
Sorry, I think I misunderstood your issue. I can indeed see that `xml:lang` is not getting stripped as it should be, and that is a defect.

@kienstra Do you have a recommendation for a fix?

**Comment by cilquirm** [comment]
For what it's worth, i've been testing by doing this:

```php

$attr_node = $node->attributes->getNamedItem( $attr_name );
				if ( ! empty( $attr_node ) ) {
					$node->removeAttributeNode( $attr_node );
				} else {
					$node->removeAttribute( $attr_name );
```

and it seems to work.

**Comment by westonruter** [comment]
@cilquirm Would you please test #916?

**Comment by csossi** [comment]
verified in qa
