### ISSUE TITLE
Allow themes to register support for AMP canonical mode

### ISSUE THREAD

**Issue by ThierryA** [Automattic/amp-wp#848]
### Acceptance Criteria

AC1: Allow themes to register support for AMP canonical with `add_theme_support( 'amp' )` (As @westonruter’s [comment proposed](https://github.com/Automattic/amp-wp/issues/827#issuecomment-351827719)).
AC2: If support is added, this would remove paired mode. The site would only serve AMP, and there wouldn’t be `/amp` or `?amp` URLs.

#### Tasks

- [x] Check if AMP theme support exists, and if so, do not activate  the current AMP templating system and the current paired mode.
- [x] When AMP theme support is present, prevent AMP rel link in head and other frontend actions that assume paired mode.

**Comment by kienstra** [comment]
**In Development**

Hi @ThierryA,
Thanks for these acceptance criteria. I'm working on this now.
