### ISSUE TITLE
Discovery to ensure all relevant WordPress actions/filters are AMP compatible

### ISSUE THREAD

**Issue by MackenzieHartung** [Automattic/amp-wp#850]
### Acceptance Criteria

AC1: Conduct a Discovery to ensure all relevant WordPress actions/filters are AMP compatible
AC2: Create an issue/issues as an outcome of the Discovery.

#### Tasks
- [ ] Catalog all actions and filters that are triggered in the course of rendering a WordPress template, and then identify which ones are problematic for AMP. For example, `wp_head`, `wp_footer`, primarily what Core uses to output code in template, in particular the printing of scripts and stylesheets, `wp_print_head_scripts`.

**Comment by DavidCramer** [comment]
## WIP: key actions called during render of a template ##
Action | State | Note
--- | --- | ---
wp | :white_check_mark: |
template_redirect | :white_check_mark: |
get_header | :white_check_mark: |
wp_enqueue_scripts | :white_check_mark: |
wp_head | :x: | Calls main header rendering functions - `wp_resource_hints`: can add `preconnect, prefetch, and prerender` links; `locale_stylesheet`: can include additional stylsheets; `print_emoji_detection_script`: adds additional script tags;  `wp_print_head_scripts`: prints out header scripts; `wp_custom_css_cb`: renders header styles;   
wp_print_styles | :x: | outputs multiple `style` tags 
wp_print_scripts | :x: | outputs multiple `style` tags
pre_get_search_form | :white_check_mark: |
loop_start | :white_check_mark: |
the_post | :white_check_mark: |
get_template_part_content | :white_check_mark: |
loop_end | :white_check_mark: |
get_sidebar | :white_check_mark: |
dynamic_sidebar | :white_check_mark: |
get_search_form | :white_check_mark: |
pre_get_comments | :white_check_mark: |
wp_meta | :white_check_mark: |
get_footer | :white_check_mark: |
get_sidebar | :white_check_mark: |
wp_footer | :x: | Calls footer rendering functions - `wp_print_footer_scripts` see below:
wp_print_footer_scripts | :x: | renders footer scripts.

**Comment by westonruter** [comment]
Is wp_resource_hints something we need to block?

**Comment by DavidCramer** [comment]
@westonruter I think it would be safe. That particularly aids in rendering in a browser, which is not necessary in AMP.

**Comment by DavidCramer** [comment]
@westonruter I think I got this all listed now and is ready to be reviewed.

**Comment by westonruter** [comment]
> I think it would be safe. That particularly aids in rendering in a browser, which is not necessary in AMP.

Aside from removing the `emoji_svg_url` from the resource hints array, I don't see how AMP would make them all obsolete. I think we can safely keep them.

**Comment by westonruter** [comment]
@DavidCramer Would you take your findings and then open a PR to incorporate them into https://github.com/Automattic/amp-wp/blob/develop/includes/class-amp-theme-support.php ?

The existing code is removing actions, but perhaps some of the filters you discovered would be preferred.

Note that `wp_custom_css_cb` is removed and its output is replaced to be added to the AMP custom CSS.

Then you can look specifically at comments in #797 and #862, and the unique filters and actions that occur there which will need to be hooked into.

**Comment by DavidCramer** [comment]
@westonruter Will do. I spoke briefly to @ThierryA on this yesterday. will sync with him again and move forward. Thanks!

**Comment by westonruter** [comment]
@DavidCramer Here's the info from @amedina re: Resource Hints:
 
>Resource hints still make sense with AMP. One use case is preloading a hero image in the first viewport: 
>
> `<link href=hero.png rel=preload>`
>
>Another use case is preconnect for Google fonts (the WP plugin could do this even automatically!):
>
> `<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>`
>
>Another thing we should consider is adding a default preload for v0.js:
>
> `<link href=https://cdn.ampproject.org/v0.js rel=preload>`

**Comment by DavidCramer** [comment]
@westonruter nice one!
