### ISSUE TITLE
AMP not showing "APPLY FOR JOB" button

### ISSUE THREAD

**Issue by tsanren89** [Automattic/amp-wp#854]
Hi there,

I install AMP for WP plugin and also bought custom post type plugin, and also purchase Custom Post Type extension to display job listing in AMP.

But for AMP site, not showing "APPLY FOR JOB" button after Job Overview.

Normal site: https://betteraviationjobs.com/job/aerologic-first-officer-december-2017/
AMP site: https://betteraviationjobs.com/job/aerologic-first-officer-december-2017/amp

Any solution on this?

Thanks and appreciated.

**Comment by westonruter** [comment]
It's difficult to know without knowing how the button is added to the non-AMP site in the first place. Is it part of a custom post template? Or is it injected via `the_content` filter?

**Comment by westonruter** [comment]
I can see the “Apply for Job” button is a widget. Widgets are not supported by the current AMP post templates. Support for widgets _is_ being added in the new `amp` theme support work. See #870.
