### ISSUE TITLE
Support submitting comments to WordPress

### ISSUE THREAD

**Issue by ThierryA** [Automattic/amp-wp#862]
### Acceptance Criteria

AC1: The commenting experience that is native to WordPress needs to be supported in the AMP theme.
AC2: A user will need the ability to access the comment form, enter comment, and successfully submit a comment, as they do today.

#### Tasks
- [x] Add comment list template
- [x] Add comment form template + submission

**Comment by alcurrie** [comment]
**These are the same notes as in #862**
Functionality looks good and works well, but I noticed a few items that were not as expected:

1) **Issue:** Comment moderation does not display comments for previously approved comment authors. 
**Expected**
In the Discussion Settings, when the Before a comment appears:  Comment must be manually approved (is 'unchecked'), and  Comment Author must have a previously approved comment is checked  (See screen cast of settings  https://cl.ly/442k1O2z1J0b)
I expect that when I enter the same Name and email as a user whose comments have already been approved, that my comment will display right away. 
**Actual**
Even if the comment author has been previously approved, comment does not display. 

2) The confirmation of the comment post, is too close to the Post comment button:
![screen shot 2018-02-05 at 7 27 41 pm](https://user-images.githubusercontent.com/18579988/35835801-cf36935e-0aaa-11e8-90fd-ff75d201dd61.png)

3) From a usability perspective the comments seem quite far away from the actual article with several other articles between the bottom of the article the user is commenting on, with 3 other articles between the article and the comments on the article
https://cl.ly/1x0g0H0K421k

**Comment by csossi** [comment]
see Anne Louise's comments above
