### ISSUE TITLE
List AMP support for all native WordPress widgets

### ISSUE THREAD

**Issue by kienstra** [Automattic/amp-wp#864]
**Acceptance criteria:**
AC1: List the AMP support for all native WordPress widgets, as produced by the script in #839. 

This from AC5 in #839:
`AC5: One story will be created as an outcome of the Discovery to address enhanced/added support for sidebar widgets.`

When AMP doesn't support a widget, either describe it in detail here, or open a sub-issue.

There doesn't seem to be [an issue](https://github.com/Automattic/amp-wp/issues?utf8=%E2%9C%93&q=is%3Aissue+widget+) for this yet.

**Comment by kienstra** [comment]
**Widget AMP Support**
(Comment WIP)

Widget | Status | Note
--- | --- | ---
[Audio](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/widgets/class-wp-widget-media-audio.php) | 🔸 | Mainly functional, but has an AMP error
[Archives](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/widgets/class-wp-widget-archives.php) *without* 'dropdown' |  ✅ 
[Archives](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/widgets/class-wp-widget-archives.php) *with* 'dropdown' | 🔸 |  AMP error from the script on the `onchange` attribute
[Calendar](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/widgets/class-wp-widget-calendar.php) |  ✅ 


**AMP Errors**
[Audio Widget](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/widgets/class-wp-widget-media-audio.php)
* The tag 'audio' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-audio'? (2 occurrences) 
Though the plugin's [sanitize function](https://github.com/Automattic/amp-wp/blob/b94b10bade418d7710138a8d7bb88ccc39ce5140/includes/templates/class-amp-content.php#L184) doesn't yet apply to widgets.

[Archives Widget](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/widgets/class-wp-widget-archives.php) 
* The attribute 'onchange' may not appear in tag 'select':
```<select id="archives-dropdown-106" name="archive-dropdown" onchange='document.location.href=this.options[this.selectedIndex].value;'>```

**Comment by westonruter** [comment]
@kienstra these are all supported now via #870, right?

**Comment by westonruter** [comment]
@kienstra I just found that neither YouTube nor Vimeo videos work in the video widget:

![image](https://user-images.githubusercontent.com/134745/35546965-43976f1e-052b-11e8-8364-905acf5e4336.png)

![image](https://user-images.githubusercontent.com/134745/35547002-7634348e-052b-11e8-8fee-8c6f3366bbd2.png)

This may require extending the video widget like you had done originally.

See relevant logic in https://github.com/WordPress/wordpress-develop/blob/1c4f57f425fed9bec01e558d22d1fb751881e347/src/wp-includes/widgets/class-wp-widget-media-video.php#L128-L145

Another option would be to add a `wp_video_shortcode_override` filter. In fact, this would work for the gallery as well via the `post_gallery` filter. I'm not 100% sure if it is better to use the filter vs. override the `gallery` shortcode. Jetpack actually uses the `post_gallery` filter:

https://github.com/Automattic/jetpack/blob/cadaa581381aae1906680ab3312b5b3be30dc60e/modules/shortcodes/slideshow.php#L19-L51

**Comment by kienstra** [comment]
**Thanks For The Details**

Hi @westonruter,
Thanks for catching that YouTube and Vimeo videos don't work, and for your details on fixing it. If it's alright, I'll work on this tomorrow (Tuesday).

**Comment by kienstra** [comment]
**Request For QA***

Hi @csossi,
Could you please test this ticket? The widgets look to appear and work as expected in my local environment.

The [test site](https://test-ampconfdemo.pantheonsite.io/) might not be the best place for this, as it'll distort the pages when we place 20-30 test widgets in the sidebar.

We should run the [widget test script](https://github.com/Automattic/amp-wp/blob/develop/bin/add-test-widgets-to-sidebar.php) on a site, as it will insert all of the needed widgets. As long as the site already has 3 videos and 3 audio files.

**Comment by kienstra** [comment]
**Test Page**

Hi @csossi,
Could you please test the widgets on [this test page](https://dev-ampconfdemo.pantheonsite.io/2018/02/)?

Please verify these widgets:
* Audio
* Archives (without dropdown)
* Archives (with dropdown)
* Calendar
* Categories (without dropdown)
* Categories (with dropdown)
* Custom HTML
* Gallery
* Image
* Menu
* Pages
* Recent Posts
* RSS
* Tag Cloud (without count)
* Tag Cloud (with count)
* Text
* Video

**Comment by csossi** [comment]
verified in QA

**Comment by ThierryA** [comment]
@kienstra could kindly update the list of widget supported now that the work is done. It would be great to have it in the WIKI and then change all instances of the tables to link to the wiki to avoid confusion.

PS: this should apply to embeds too

**Comment by kienstra** [comment]
**Added Page To Wiki**

Hi @ThierryA,
This [new page](https://github.com/Automattic/amp-wp/wiki/Native-WordPress-Widget-and-Embed-Support) in the project wiki has the updated matrices for widget and embed support. Also, I made a comment in [the](https://github.com/Automattic/amp-wp/issues/864#issuecomment-357834012) [existing](https://github.com/Automattic/amp-wp/issues/806#issuecomment-350790526) [matrices](https://github.com/Automattic/amp-wp/pull/889), referencing that wiki page.

**Comment by ThierryA** [comment]
Awesome, thanks @kienstra
