### ISSUE TITLE
Version 0.6 get_support_errors() filter?

### ISSUE THREAD

**Issue by ktmn** [Automattic/amp-wp#867]
I have previously provided support in a theme for having a chosen page as AMP front page by manually changing the global WP_Query, setting proper template and calling `amp_prepare_render()` when applicable.

0.6 introduced a problem when trying to render an AMP front page that is also the main front page due to this code [here](https://github.com/Automattic/amp-wp/blob/0.6/includes/class-amp-post-type-support.php#L85):

```php
// Homepage and page for posts are not supported yet.
if ( 'page' === get_post_type( $post ) && 'page' === get_option( 'show_on_front' ) ) {
	if ( (int) get_option( 'page_for_posts' ) === (int) $post->ID ) {
		$errors[] = 'page-for-posts';
	} elseif ( (int) get_option( 'page_on_front' ) === (int) $post->ID ) {
		$errors[] = 'page-on-front';
	}
}
```

It forces the AMP to be disabled in the [metabox](https://i.imgur.com/J43zf73.png) and redirects to canonical when visiting it.

I think if the `AMP_Post_Type_Support::get_support_errors()` [return array](https://github.com/Automattic/amp-wp/blob/0.6/includes/class-amp-post-type-support.php#L110) had a filter I could just unset the `'page-for-posts'` and `'page-on-front'` error values and would be able to keep the support for front pages.

**Comment by westonruter** [comment]
@ktmn I have written up a proposal for what I think would be a better solution than adding a new filter: https://github.com/Automattic/amp-wp/issues/837#issuecomment-358144627

Please review.

**Comment by ktmn** [comment]
Looks good

**Comment by westonruter** [comment]
@ktmn would you test #872?

**Comment by ktmn** [comment]
Works well, thank you

**Comment by westonruter** [comment]
@ktmn can you share your code that mutates `WP_Query`? That code would seem to be needed by the plugin in order for the front page to render as AMP when the query var is present.

**Comment by westonruter** [comment]
@ktmn actually, take a look at https://github.com/Automattic/amp-wp/pull/872/commits/c9acad7e7b376c2e615af996219429c8b7717b09

**Comment by ktmn** [comment]
Yeah that works, replaces my custom implementation.
