### ISSUE TITLE
Add Schema.org metadata to theme support

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#873]
Note comment:

https://github.com/Automattic/amp-wp/blob/e60cb152a50e2ffbf5504d41aee859ad1d0e0baa/includes/class-amp-theme-support.php#L169

With the initial introduction of theme support in in #857, the Schema.org metadata functionality was not ported over from the AMP post templates. This needs to be done.

**Comment by westonruter** [comment]
This should probably involve extracting the following logic into a global reusable function:

https://github.com/Automattic/amp-wp/blob/e60cb152a50e2ffbf5504d41aee859ad1d0e0baa/includes/templates/class-amp-post-template.php#L283-L317

**Comment by kienstra** [comment]
**Steps To Test**

1. Navigate to any page on the [test site](https://test-ampconfdemo.pantheonsite.io/)
2. View the HTML source of the page (in Chrome, Developer > View Source)
3. Search the source for `schema.org`
4. Expected: there are values for
* `@context`
* `publisher`
* `@type` 
* `name`

Example:
```
<script type="application/ld+json">{"@context":"http:\/\/schema.org","publisher":{"@type":"Organization","name":"The DailyNews"}}</script>
```

**Comment by csossi** [comment]
verified in QA
