### ISSUE TITLE
Add analytics to theme support

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#874]
Note comment:

https://github.com/Automattic/amp-wp/blob/e60cb152a50e2ffbf5504d41aee859ad1d0e0baa/includes/class-amp-theme-support.php#L169

With the initial introduction of theme support in in #857, the injection of analytics functionality was not ported over from the AMP post templates. This needs to be done.

**Comment by westonruter** [comment]
There is a `amp_post_template_add_analytics_data` function already which in the existing post template paired mode is added to the `amp_post_template_footer` action:

https://github.com/Automattic/amp-wp/blob/e60cb152a50e2ffbf5504d41aee859ad1d0e0baa/includes/amp-post-template-actions.php#L133-L161

With themes support, however, there is no `AMP_Post_Template`. So so this bit of logic would need to be refactored to work in theme support mode: `$analytics_entries = $amp_template->get( 'amp_analytics' );`

**Comment by csossi** [comment]
verified in QA
