### ISSUE TITLE
Post content is not parsed on UTF-8

### ISSUE THREAD

**Issue by j3j5** [Automattic/amp-wp#88]
The dummy tags used when loading the HTML on the DOMDocument ](https://github.com/Automattic/amp-wp/blob/master/class-amp-sanitizer.php#L27) make the encoding of the document to be ignored, causing issues on UTF-8 posts. I have a fix on [my fork](https://github.com/j3j5/amp-wp/commit/c15c1e454cc66cd9ffeafed4604a8662e485e820) which loads UTF-8 by default, although I'm not sure if more encodings should be supported. I guess the best solution would be to try and read the original encoding of the page and if not, use UTF-8.

**Comment by besttechie** [comment]
Thanks for the fix! Just implemented it and it works well. The encoding issues were driving me nuts.

**Comment by j3j5** [comment]
You are welcome @besttechie, let's see what @mjangda thinks so I can open a PR.

**Comment by mjangda** [comment]
Good catch; can you start a PR and I'll run with that to start?

**Comment by j3j5** [comment]
Sure!
