### ISSUE TITLE
Tags script not being deleted on AMP page

### ISSUE THREAD

**Issue by eduardcotmrf** [Automattic/amp-wp#883]
Testing with version 0.6 I've encountered that pages that have a tag '<script type="text/javascript">' are failing on their AMP version. The tag it's not being deleted while cleaning the body of the article.

I think it's related to this change: https://github.com/Automattic/amp-wp/commit/5c1fa2086d316a77e404e4f03de11766ac4d8daf#diff-ee41b32e64c90445a71328ca93cfa799 

The allowed script type for tag amp-analytics I think should be 'application/json' not 'text/javascript'.

**Comment by westonruter** [comment]
@eduardcotmrf would you please share the content you're using to test with? Are you putting this in the `post_content`?

**Comment by westonruter** [comment]
@eduardcotmrf good catch. I was able to reproduce the issue in any case. Please test #884.
