### ISSUE TITLE
Any plans for monetisation plugin in WP AMP?

### ISSUE THREAD

**Issue by DigitalDavo** [Automattic/amp-wp#913]
I love how quickly AMP pages from my site load on mobile. All good. I am seeing more and more traffic to my site from Google's AMP snapshot. Alas this means a loss of potential monetisation traffic. If the trend continues then AMP may not enjoy long term success.

Are there any plans to allow some sort of plugin/interface to load a fast block that can display some kind of ad or call to action or something like that?

**Comment by jasti** [comment]
@amedina is there public documentation for the AdSense options already available that work with Wordpress generated from AMP?

**Comment by davisshaver** [comment]
@jasti The AMP docs for AdSense units work, as seen here. https://onwardstate.com/2018/02/19/best-features-thon-2018/amp

This requires template change. Can you be more specific about the problem you are trying to solve?
