### ISSUE TITLE
YouTube video displays an error on AMP page (doesn't use amp-youtube component)

### ISSUE THREAD

**Issue by rudygalfi** [Automattic/amp-wp#92]
If you embed a YouTube video onto a page, it will render OK on the non-AMP page but it shows an error on the AMP page:

<img width="609" alt="screen shot 2016-01-05 at 11 19 10 am" src="https://cloud.githubusercontent.com/assets/3888212/12125095/3240ce4e-b39e-11e5-84a4-01bd5aebdb3c.png">

Repro steps:
1. Write a new post.
2. Paste in a YouTube video URL so that the editor will resolve it into the YouTube player embed.
3. Publish the page. Notice that the non-AMP page displays the YouTube embed without an issue.
4. Go to the AMP version by appending /amp and you see the YouTube video displayed as above.

Looking at the source, it shows up as something like this:

```
<amp-iframe width="840" height="473" src="https://www.youtube.com/embed/YQHsXMglC9A?feature=oembed" frameborder="0" allowfullscreen layout="responsive"></amp-iframe>
```

when it should be using the `amp-youtube` extension instead.

cc @cramforce

**Comment by cramforce** [comment]
It should use `amp-youtube`! This will comes with lots of benefits like automatic poster image, etc.

**Comment by mjangda** [comment]
@rudygalfi Odd, it should be using `amp-youtube` already. Can you share the full YouTube URL you're using?

**Comment by rudygalfi** [comment]
@mjangda The URL I pasted into the editor was "https://www.youtube.com/watch?v=YQHsXMglC9A" and then it just resolved into a YouTube player embed.

**Comment by mjangda** [comment]
I haven't been able to reproduce this with the URL provided.

@rudygalfi if you're still having issues, can you re-open with more details (full content of post, version of plugin, etc.)?
