### ISSUE TITLE
AMP version 0.6.0 still showing /amp/ instead of ?amp

### ISSUE THREAD

**Issue by mganand** [Automattic/amp-wp#925]
In one of my WordPress blog I did the AMP plugin update but according to the new update changelog 
Note that AMP URLs will end in `?amp` instead of `/amp/`. Still, it is showing /amp/ at the end of the post URL. Is it a problem. What should I do?

**Comment by westonruter** [comment]
@mganand it is _pages_ specifically (and any non-hierarchical post types) that will have their `amphtml` URLs ending in `?amp`. Posts continue to use `/amp/`.

**Comment by mganand** [comment]
Thanks Weston
