### ISSUE TITLE
Images in a gallery display one at a time in sequence and click through to a non-AMP page

### ISSUE THREAD

**Issue by rudygalfi** [Automattic/amp-wp#93]
We set up a gallery of images like this:

<img width="615" alt="screen shot 2016-01-06 at 6 29 00 pm" src="https://cloud.githubusercontent.com/assets/3888212/12160702/78f7c094-b4a3-11e5-82c4-536873b804ab.png">

When viewing this on an AMP page, the images all display one at a time and are stretched to fill the available container width. In addition, a click on the image goes to a non-AMP landing page.

<img width="161" alt="screen shot 2016-01-06 at 6 30 40 pm" src="https://cloud.githubusercontent.com/assets/3888212/12160712/9e16ee04-b4a3-11e5-871c-810c5f1f4d05.png">

The gallery rendering should be kept in tact in the AMP version and clicks should take advantage of the amp-lightbox component.

**Comment by mjangda** [comment]
The gallery implementation is a bit rough right now. We just default to `amp-carousel`.

I agree that maintaining the layout and using `amp-lightbox` would be good improvements.

**Comment by mjangda** [comment]
Tracking this at #169
