### ISSUE TITLE
Change comment confirmation message based on approval settings

### ISSUE THREAD

**Issue by DavidCramer** [Automattic/amp-wp#936]
As mentioned in https://github.com/Automattic/amp-wp/issues/797#issuecomment-363272601 and https://github.com/Automattic/amp-wp/issues/862#issuecomment-363275416
The message indicated "..subject to moderation".
This message should be adjusted based on the moderation settings.
An indication of refresh times should also be mentioned.

**Comment by westonruter** [comment]
Code in question:

https://github.com/Automattic/amp-wp/blob/215860d618cc114d37f17f8efb477e6b5e3ccc40/includes/class-amp-theme-support.php#L360-L376

We should make the `submit-success` also contain a `<template type="amp-mustache">`. Then the message could say if the newly posted comment is _actually_ moderated or not. Currently the success is just sent with success data without any data. But if this were changed to have a message like then the template can be added to render it.

In regards to the refresh time, we won't know what interval the `amp-live-list` is using in the theme. So if not moderated, then for now it should probably just say it will be available soon.

**Comment by csossi** [comment]
verified in QA (dev/paired/legacy)
