### ISSUE TITLE
Sanitizers should not strip valid 'amp-mathml' tags

### ISSUE THREAD

**Issue by adamsilverstein** [Automattic/amp-wp#941]
AMP recently introduced support for MathML via the `amp-mathml` tag - https://www.ampproject.org/docs/reference/components/amp-mathml. When trying to add this tag to a WordPress site, I'm seeing mathml tags stripped by the amp-wp sanitizer. 

If I add this to `class-amp-allowed-tags-generated.php` everything works as expected, how do I go about adding this to the plugin correctly? I couldn't tell how the file is currently generated, if I can get some direction happy to add a pull request to add this support.

```
		'amp-mathml' => array(
			array(
				'attr_spec_list' => array(
					'data-formula' => array(
						'mandatory' => true,
					),
				),
				'tag_spec' => array(
					'html_format' => array(
							'amp',
					),
					'spec_url' => 'https://www.ampproject.org/docs/reference/components/amp-mathml',
				),

			),
		),

```

**Comment by adamsilverstein** [comment]
@westonruter I see you have been working on the sanitizers :) any tips appreciated

**Comment by westonruter** [comment]
@adamsilverstein yes, given that `amp-mathml` is now defined among the validator protoascii files ([`validator-amp-mathml.protoascii`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-mathml/validator-amp-mathml.protoascii)), then all we need to do is run [`bin/amphtml-update.sh`](https://github.com/Automattic/amp-wp/blob/develop/bin/amphtml-update.sh), and it should just work. We need to do an update of the generated PHP anyway, so it will be included as part of that.

**Comment by adamsilverstein** [comment]
@westonruter I fired up VVV and ran the updated script, the result is in https://github.com/Automattic/amp-wp/pull/943
