### ISSUE TITLE
AMP meta box is active on post types that are not public

### ISSUE THREAD

**Issue by renatonascalves** [Automattic/amp-wp#957]
The AMP plugin adds the meta box in the back-end for post types that are not public. A good example I stumbled upon now while in the BuddyPress email area.

BuddyPress uses post types to manager its emails. The post types are not public. Still, in the admin area, one can see the notice that AMP is not active because of post type support.

![post-type-support](https://user-images.githubusercontent.com/19148962/36180889-07c22f2e-1101-11e8-9d8b-9b28126ac179.jpg)

Clicking on the link sends the user to the AMP settings page where the email post type, correctly, by the way, is not available for activation.

The verification made on `AMP_Post_Meta_Box::render_status()` that uses `post_supports_amp()` is not enough. There is a filter available that plugins can use, but I believe this should be fixed in the AMP plugin.

Theoretically, non-public post types will not be used in the front-end and so, will have no AMP support. So the meta box in the back-end is unnecessary.

What do you guys think? :)

**Comment by renatonascalves** [comment]
By the way, something like that should work fine. I'm happy to send a PR.

```
/**
 * Render AMP status.
 *
 * @since 0.6
 * @param WP_Post $post Post.
 */
public function render_status( $post ) {
	$p = get_post_type_object( $post->post_type );

	$verify = (
		isset( $post->ID )
		&&
		$p->public
		&&
		current_user_can( 'edit_post', $post->ID )
	);

	if ( true !== $verify ) {
		return;
	}

	... 
```

**Comment by westonruter** [comment]
@renatonascalves good catch. Yes, please do open a PR! You may want to use `is_post_type_viewable( 
$post->post_type )`.

**Comment by postphotos** [comment]
Hey @renatonascalves, this was a good suggestion, thanks for contributing!
