### ISSUE TITLE
Custom templates with amp_post_template_file filter results in error

### ISSUE THREAD

**Issue by notatamas** [Automattic/amp-wp#963]
I get an error when I try to use custom templates. 

AMP_Post_Template::verify_and_include was called incorrectly.Path validation for template (/var/www/html/wp-content/themes/xyz/amp/templates/single.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`

I use the amp_post_template_file filter as follows:
```
function xyz_amp_custom_templates( $file, $type, $post ) {
	if ( 'single' === $type ) {
		$file = dirname( __FILE__ ) . '/templates/single.php';
	} elseif ( 'style' === $type ) {
	  	$file = dirname( __FILE__ ) . '/templates/style.php';
	}
	return $file;
}
add_filter( 'amp_post_template_file', 'xyz_amp_custom_templates', 10, 3 );
```

And the single.php file is just an exact copy of the one in the plugin's templates directory.
AMP-WP Version: 0.6.1

**Comment by westonruter** [comment]
One of the conditions in this method is failing:

https://github.com/Automattic/amp-wp/blob/8edc4152b1bd633dc27b6f9d78ea513670ce18c1/includes/templates/class-amp-post-template.php#L576-L588

That's where I'd look.
