### ISSUE TITLE
The tag 'amp-ad extension .js script' appears more than once in the document.

### ISSUE THREAD

**Issue by RetroJamz** [Automattic/amp-wp#970]
Hi,

Anytime I activate your plugin, google search console mails me about an error as stated above, but when i disable the plugin the error is fixed.

I need a solution as this is really messing up my presence in search results.

**Comment by daneshcamp** [comment]
hi
i have same issue

[my link](https://cibu.io/telegram/free-telegram-members/) 


eror : An AMP component 'script' tag is present more than once in the document
