### ISSUE TITLE
Malformed url in links creates an invalid AMP page

### ISSUE THREAD

**Issue by rubengonzalezmrf** [Automattic/amp-wp#977]
If an editor ads a link like `<a href="http://foo%20bar">foo bar</a>` by mistake, the generated amp page will be invalid.

I think it would be great to add an AMP_Link_Sanitizer class that checks the urls of the links and remove the <a> tag if the url is malformed.

**Comment by westonruter** [comment]
Interesting. When validating the AMP Validator just links to https://www.ampproject.org/docs/reference/spec#links which says:

> The javascript: schema is disallowed.

I'm not sure how the validator is understanding a URL like `http://foo%20bar`, but somehow the domain is causing a validation error. I don't see why such a URL would be disallowed from looking at the spec:

https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L1436-L1470

Sanitization of the value should be done in the [`AMP_Tag_And_Attribute_Sanitizer`](https://github.com/Automattic/amp-wp/blob/develop/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php), maybe in the `check_attr_spec_rule_allowed_protocol` method? I'm not sure if the validator is complaining about the protocol or about something else.

**Comment by rubengonzalezmrf** [comment]
Hi, the validator is complaining about the host, the protocol seems to be correct, it's `http:` but looking at the validator code, in the file:

`amphtml/validator/engine/parse-url.js`

There's this code in line 290 which validates that the host doesn't contain any url encoded content:

```javascript
let unescapedHost = '';
try {
  unescapedHost = decodeURIComponent(host);
} catch (e) {
  // Indicates that host had escaped multibyte characters which
  // when unescaped were not UTF-8 valid.
  this.isValid = false;
  return host;
}
```

I agree it should be in `AMP_Tag_And_Attribute_Sanitizer` class but maybe in a new `check_attr_spec_rule_allowed_host` method?

**Comment by westonruter** [comment]
Sounds good!

**Comment by davisshaver** [comment]
I have run into this, too. Other examples seen in the wild during validation:

- User types `mail to:` instead of `mailto`, breaks validation.
- User accidentally inputs text into link, breaks validation.
- User accidentally includes a space in the URL, which gets caught as mentioned at top.

Might be test case fodder, lemme know if you want help @rubengonzalezmrf

**Comment by westonruter** [comment]
@rubengonzalezmrf from your comments I assumed you were looking to open a PR?

**Comment by rubengonzalezmrf** [comment]
@westonruter yes, i've done it already: [Pull request #983](https://github.com/Automattic/amp-wp/pull/983)

**Comment by rubengonzalezmrf** [comment]
@davisshaver if a user inputs just text in a link like "foo bar", wordpress automatically prepends the protocol http:// so it's the same case than the "http://foo bar"

**Comment by davisshaver** [comment]
@rubengonzalezmrf I encountered the issue mentioned above while testing/migrating legacy content. Seems like the editor behavior probably changed since the content was originally produced but I still think the test cases are warranted for backwards compatibility (even if they seem unlikely to happen today).

**Comment by rubengonzalezmrf** [comment]
I added more test cases and checks. But i don't really know why the unit tests are not passing, the code works in my wordpress installation. I'm sure i'm missing something with the tests, but can't find what it is. Some help would be appreciated
