### ISSUE TITLE
Enforce `image` in json metadata

### ISSUE THREAD

**Issue by mjangda** [Automattic/amp-wp#98]
AMP metadata examples suggest including an `image` object. We should attempt the following order:

- [x] Featured Image
- [x] First attachment on post
- [ ] Site Icon
- [ ] Fallback image (blank or WP logo?)

Spec: https://developers.google.com/structured-data/rich-snippets/articles

**Comment by Otto42** [comment]
Schema.org specs actually require the image; it's not optional. So adding in a default blank image would be a good idea as well.

**Comment by mjangda** [comment]
No point in forcing an image if one is not available. This is something Webmaster Tools needs to change.
