### ISSUE TITLE
WooCommerce + AMP: Conflict

### ISSUE THREAD

**Issue by mzakariya** [Automattic/amp-wp#987]
A site owner with both WooCommerce + AMP is reporting that:

> Google Search Console returns a major content mismatch. I've checked and the AMP pages doesn't show the woocommerce cart and information.

More details, including site URL, available in: 990666-zen

**Comment by westonruter** [comment]
Please see: https://wordpress.org/support/topic/woocommece-usage-of-this-plugin/
