### ISSUE TITLE
Add option to remove  "Powered by Wordpress" in footer

### ISSUE THREAD

**Issue by stopspazzing** [Automattic/amp-wp#991]
There is no reason that someone should be forced to show powered by wordpress. Is there an easy way to disable this without modifying the footer.php code so it survives updates?

`<p>
			<a href="<?php echo esc_url( esc_html__( 'https://wordpress.org/', 'amp' ) ); ?>">
				<?php
				// translators: %s is WordPress.
				echo esc_html( sprintf( __( 'Powered by %s', 'amp' ), 'WordPress' ) );
				?>
			</a>
		</p>`

**Comment by westonruter** [comment]
Yes.

See: https://wordpress.org/support/topic/how-do-i-remove-powered-by-wordpress-from-footer-of-amp-posts-2/
Or: https://wordpress.org/support/topic/how-do-i-remove-powered-by-wordpress-from-footer-of-amp-posts/
