### ISSUE TITLE
500 Error when PREG Backtrack Limit Exhausted

### ISSUE THREAD

**Issue by christianc1** [Automattic/amp-wp#993]
PHP versions 5.2.x have a default value of `100000` on `pcre.backtrack_limit`.  We stumbled on the issue in `0.7-beta` with the work supporting amp-bind.

We are using `amp-iframe` as a container for a table with a lot of rows and some javascript to help filter that table.  We're injecting the iframe source through the `srcdoc` attribute.  The regex matching tag attributes eventually will hit backtrack limit, fail with a `PREG_BACKTRACK_LIMIT_ERROR` silently, and `AMP_Dom_Utils::convert_amp_bind_attributes` will return `null`.

Further along the stack, this `null` value will be fed to `DOMDocument` which will cause a fatal error.
I'm opening up a PR shortly with some failing tests.  I've made an attempt at modifying the regex, but I can't get all the tests to pass with my changes so I'm opening up this issue to the broader community.

**Comment by christianc1** [comment]
@westonruter no, this issue will occur on PHP versions > 5.2.  Independent of PHP version, this may affect any environment with `pcre.backtrack_limit` ini value of 100,000, which is the default on 5.2+.

**Comment by westonruter** [comment]
Strange I can't get the issue to reproduce on my system (VVV). I tried doing `ini_set( 'pcre.backtrack_limit', 100000 );` at the start of the method but it doesn't cause the issue to manifest. 

At issue is this regular expression?

```php
'#^\s+(?P<name>\[?[a-zA-Z0-9_\-]+\]?)(?P<value>=(?:"[^"]*"|\'[^\']*\'|[^\'"\s]+))?#'
```

**Comment by westonruter** [comment]
Or is it?

```php
'#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s+[^>]+\]=[^>]+)\s*>#'
```

**Comment by adamsilverstein** [comment]
@westonruter Do you get the error if you run the tests in https://github.com/Automattic/amp-wp/pull/994? I believe the regex that causes the issue is the second one: `'#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s+[^>]+\]=[^>]+)\s*>#'`

**Comment by westonruter** [comment]
@adamsilverstein no, I get no errors on that `ix/993-preg-backtrack-limit-exhausted` branch in VVV:

```
$ phpunit --filter test_attribute_conversion_on_long_iframe_srcdocs
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 5.7.25 by Sebastian Bergmann and contributors.

.....                                                               5 / 5 (100%)

Time: 8.83 seconds, Memory: 49.25MB

OK (5 tests, 0 assertions)
```

**Comment by westonruter** [comment]
@christianc1 Try simplifying the regex a bit like this:

```diff
- '#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s+[^>]+\]=[^>]+)\s*>#'
+ '#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s[^>]+\]=[^>]+)>#'
```

That seems like it would reduce the amount of backtracking required.

**Comment by christianc1** [comment]
That helped a bit.  Travis is [still failing](https://travis-ci.org/Automattic/amp-wp/jobs/351363168) though.
```diff
- '#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s[^>]+\]=[^>]+)>#'
+ '#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s[^>\]]+\]=[^>]+)>#'
```

Excluding both `>` and `]` from the second capture group takes some complexity and gets us a match in less steps given the following test string:

```
<amp-state id="myAnimals">
  <script type="application/json">
    {
      "dog": {
        "imageUrl": "/img/dog.jpg",
        "style": "greenBackground"
      },
      "cat": {
        "imageUrl": "/img/cat.jpg",
        "style": "redBackground"
      }
    }
  </script>
</amp-state>

<p [text]="'This is a ' + currentAnimal + '.'">This is a dog.</p>

<!-- CSS classes can also be added or removed with [class]. -->
<p class="greenBackground" [class]="myAnimals[currentAnimal].style">
  Each animal has a different background color.
</p>

<!-- Or change an image's src with the [src] binding. -->
<amp-img width="300" height="200" src="/img/dog.jpg"
    [src]="myAnimals[currentAnimal].imageUrl">
</amp-img>

<button on="tap:AMP.setState({currentAnimal: 'cat'})">Set to Cat</button>
```
`'#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s[^>]+\]=[^>]+)>#'` : *3 matches in 277 steps*
`'#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s[^>\]]+\]=[^>]+)>#'` : *3 matches in 87 steps*

**Comment by westonruter** [comment]
How are you obtaining the number of steps?

**Comment by christianc1** [comment]
@westonruter I use https://regex101.com, there is some profiling information in the top right above where you enter the regex.

**Comment by westonruter** [comment]
@christianc1 The row of HTML is 360 bytes. The test is failing at 10,000 iterations. That means a `srcdoc` that is almost 4MB (❗️) . Is that reasonable to expect this? The average AMP document is 80KB in total. As per https://github.com/Automattic/amp-wp/issues/875 if the AMP document is more than 1MB there will be other performance problems to worry about.
